### ISSUE TITLE
Fcitx5 not working with XIM after libx11 1.8.8 update

### ISSUE THREAD

**Issue by bbaa-bbaa** [fcitx/fcitx5#1000]
**Describe the bug**
I cannot enter any characters using Xim when setting XMODIFIERS=@im=fcitx

**To Reproduce**
Steps to Reproduce

1. set XMODIFIERS=@im=fcitx
2. Open a program that uses xim and try to type (Chromium on Xwayland/GTK2 Program(Gimp))
3. Cannot enter any characters and shortcuts

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.
https://fars.ee/WB4U

**Additional context**
Relate to: https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/205

**Comment by wengxt** [comment]
So first of a quick workaround: run those apps with GTK_IM_MODULE=fcitx.

**Comment by bbaa-bbaa** [comment]
> So first of all, a quick workaround: run those apps with GTK_IM_MODULE=fcitx.

Already using Workaround to add gtk-im-module=fcitx to ~/.config/gtk-3.0/settings.ini and is only effective for XWayland.
Thanks for you help.

**Comment by wengxt** [comment]
I updated the section:

https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#TL.3BDR_Do_we_still_need_XMODIFIERS.2C_GTK_IM_MODULE_and_QT_IM_MODULE.3F

So, to enforce gtk im module only for Gtk2 & Gtk3/X11, you can update and ~/.gtkrc-2.0 and ~/.config/gtk-3.0/settings.ini correspondingly.

For ~/.gtkrc-2.0
```
gtk-im-module="fcitx"
```

For ~/.config/gtk-3.0/settings.ini

```
[Settings]
gtk-im-module=fcitx
```

**Comment by command-z-z** [comment]
I'm sure the libx11 upgrade(1.8.8-1 -> 1.8.8-2) is causing the problem, I rolled back the version, and fcitx5 works well. But, I set the two environment variables, can't solve this problem. i can't input in any software running in Xwayland, the float typing bar appear in left top.

**Comment by wengxt** [comment]
@command-z-z there's a libx11 patch you might want to try https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/246

**Comment by fakeGenuis** [comment]
It also freeze emacs in X randomly (just can not input), restarting fcitix possibly work. Rolling back works fine.

**Comment by wengxt** [comment]
not a fcitx bug.

**Comment by wengxt** [comment]
Some useful information: 

archlinux libx11 applied fix in 1.8.8-3
I sent a MR to revert the problematic change: https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/247 if you need patch for compiling you can grab it there.

For Gtk, it is possible to enforce gtk im module for only Gtk2/Gtk3 when running for Xwayland, while still using text-input-v3 for wayland gtk, the method can be found at this section. 

https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#TL.3BDR_Do_we_still_need_XMODIFIERS.2C_GTK_IM_MODULE_and_QT_IM_MODULE.3F

For other XIM app, you may or may not see the issue, really depending on the application's implementation. unset XMODIFIERS to disable input method completely for them can be used as a workaround.
