### ISSUE TITLE
在lazarus中快速录入时会出现类似连击的情况

### ISSUE THREAD

**Issue by afrusrsc** [fcitx/fcitx5#1006]
**Describe the bug**
在`lazarus`中快速录入时，会出现类似连击的情况

**To Reproduce**
1. 打开 lazarus (2.2.6)
2. 在代码编辑器中快速录入`show`，实际出现的是`sshhoww`之类，点退格也会出现类似行为

**Expected behavior**
键盘点击一次只出现一个对应的字母

**Desktop (please complete the following information):**
 - Desktop: xfce4(debian 12)
 - Display server type: X11

**Additional context**
- 仅安装并使用`fcitx4`时，行为正常
- 仅安装并使用`ibus`时，行为正常

**Additional context**
- `lazarus`中不能输入中文（不能切换到中文或中文不生效），有可能是`lazarus`的bug

**Comment by wengxt** [comment]
@afrusrsc fcitx5-diagnose please

**Comment by wengxt** [comment]
我在我的系统上测试了几个不同的 lazarus （3.2） ，gtk3 版没能成功在代码编辑器里用输入法，但 qt6 和 qt5 姑且都能使用虽然有一些问题

搜索一下对应的代码找到 WITH_GTK2_IM，看起来如果需要输入法支持必须手动启用。

https://www.cnblogs.com/qiufeng2014/p/15722762.html

另外在测试时没有遇到你描述的问题。说实话，如果本来就不能用输入法，按键应该没有发给 fcitx，只可能是别的什么配置意外影响，和 fcitx 自己无关

**Comment by afrusrsc** [comment]
> @afrusrsc fcitx5-diagnose please

[1.txt](https://github.com/fcitx/fcitx5/files/14831647/1.txt)

**Comment by afrusrsc** [comment]
> @afrusrsc fcitx5-diagnose please

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`。**

        **无法找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        **无法找到 gtk 3 的 `gtk-query-immodules`。**

        **无法找到 gtk 3 的 fcitx5 输入法模块。**

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        在 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        **无法输入法模块缓存 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 中找到 fcitx5**

        **无法在缓存中找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        在 `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.38` 的输入法模块缓存。
        版本行：

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.38

        已找到 gtk `3.24.38` 的 fcitx5 输入法模块。

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **无法找到 gtk 4 的输入法模块缓存**

        **无法在缓存中找到 gtk 4 的 fcitx5 输入法模块。**

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

**Comment by wengxt** [comment]
完整的 fcitx5-diagnose ，另外你的 lazarus 是什么 toolkit 的版本

**Comment by afrusrsc** [comment]
# 系统信息:
1.  `uname -a`:

        Linux vm 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

2.  `lsb_release -a`:

        Distributor ID:	Debian
        Description:	Debian GNU/Linux 12 (bookworm)
        Release:	12
        Codename:	bookworm

3.  `lsb_release -d`:

        Description:	Debian GNU/Linux 12 (bookworm)

4.  `/etc/lsb-release`:

    `/etc/lsb-release` 未找到.

5.  `/etc/os-release`:

        PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
        NAME="Debian GNU/Linux"
        VERSION_ID="12"
        VERSION="12 (bookworm)"
        VERSION_CODENAME=bookworm
        ID=debian
        HOME_URL="https://www.debian.org/"
        SUPPORT_URL="https://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"

6.  桌面环境：

    桌面环境为 `xfce`。

7.  XDG 会话类型：

        XDG_SESSION_TYPE='x11'

8.  Bash 版本：

        BASH_VERSION='5.2.15(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':0.0'


        WAYLAND_DISPLAY=''

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn", "", ""

3.  Locale：

    1.  全部可用 locale：

            C
            C.utf8
            POSIX
            zh_CN.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LANGUAGE=zh_CN:zh
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME="zh_CN.UTF-8"
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/jxq

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/jxq/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/jxq/.config/fcitx5`)。

5.  当前用户：

    脚本作为 jxq (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: `5.0.21`

3.  进程：

    找到了 1 个 fcitx5 进程：

          16214 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` 工作正常。

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.95`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `16214`。

    来自 dbus 的调试信息：

           Group [x11::0] has 3 InputContext(s)
          IC [f0dcf1860a324aa1aefe8758ffe224ec] program:xfce4-terminal frontend:dbus cap:6000000012 focus:1
          IC [5fe0eef0580a4aefbcd90bf327124dc0] program:lazarus frontend:xim cap:4000000000 focus:0
          IC [783057da90ee4c58b098faab65823fe7] program:lazarus frontend:xim cap:4000000000 focus:0
        Input Context without group

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

    **`kcmshell5` 未找到.**

# 前端设置：
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    Xim 服务的名称与环境变量中设置的相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

3.  Qt 输入法模块文件：

    找到了 fcitx5 的 qt6 输入法模块：`/usr/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了 fcitx5 qt5 模块：`/usr/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    找到了 fcitx5 的 qt5 输入法模块：`/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。

    下列错误也许并不准确，因为对 Qt 版本的猜测取决于发行版如何打包 Qt。如果您不使用任何对应版本的 Qt 程序，或者在 Wayland 下使用 Qt 的 text-input 支持，下列错误也也不是严重问题。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`。**

        **无法找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        **无法找到 gtk 3 的 `gtk-query-immodules`。**

        **无法找到 gtk 3 的 fcitx5 输入法模块。**

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        在 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        **无法输入法模块缓存 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 中找到 fcitx5**

        **无法在缓存中找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        在 `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.38` 的输入法模块缓存。
        版本行：

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.38

        已找到 gtk `3.24.38` 的 fcitx5 输入法模块。

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **无法找到 gtk 4 的输入法模块缓存**

        **无法在缓存中找到 gtk 4 的 fcitx5 输入法模块。**

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 28 个已启用的插件：

            Simplified and Traditional Chinese Translation 5.0.16
            Classic User Interface 5.0.21
            Clipboard 5.0.21
            Cloud Pinyin 5.0.16
            DBus 5.0.21
            DBus Frontend 5.0.21
            Emoji 5.0.21
            Fcitx4 Frontend 5.0.21
            Full width character 5.0.16
            IBus Frontend 5.0.21
            Lua IME API 5.0.10
            Input method selector 5.0.21
            Keyboard 5.0.21
            KDE Input Method Panel 5.0.21
            Lua Addon Loader 5.0.10
            Status Notifier 5.0.21
            Notification 5.0.21
            Pinyin 5.0.16
            Extra Pinyin functionality 5.0.16
            Punctuation 5.0.16
            Quick Phrase 5.0.21
            Spell 5.0.21
            Table 5.0.16
            Unicode 5.0.21
            Wayland 5.0.21
            Wayland Input method frontend 5.0.21
            XCB 5.0.21
            X Input Method Frontend 5.0.21

    2.  找到了 0 个被禁用的插件：

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 2 个已启用的用户界面插件：

        Classic User Interface
        KDE Input Method Panel

## 输入法：
1.  `/home/jxq/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=默认
        # Layout
        Default Layout=cn
        # Default Input Method
        DefaultIM=wbpy

        [Groups/0/Items/0]
        # Name
        Name=keyboard-cn
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=wbpy
        # Layout
        Layout=

        [GroupOrder]
        0=默认

# 日志：
1.  `date`:

        2024年 04月 02日 星期二 13:51:30 CST

2.  `/home/jxq/.config/fcitx5/crash.log`:

    `/home/jxq/.config/fcitx5/crash.log` 未找到.

**警告：fcitx5-diagnose 的输出可能包含敏感信息，包括发行版名称，内核版本，正在运行的程序名称等。**

**尽管这些信息对于开发者诊断问题有帮助，请在公开发送到在线网站前检查并且根据需要移除的对应信息。**

**Comment by wengxt** [comment]
我用虚拟机测试了一下，可以重现你的问题，但基本上可以确定是因为你在用 gtk2 的 xim immodule 的缘故。

当我用 ibus + xim 的时候同样也可以触发一样的问题，但 apt install ibus 会因为 recommends 自动安装 gtk2 的 im module （ibus-gtk）

你只需要安装 fcitx5-frontend-gtk2 即可避免你遇见的这个连击情况

**Comment by wengxt** [comment]
当然 lazarus-gtk2 还是不能正常使用输入法，上面编译的我就不尝试了，你有兴趣可以自己试试

可以试试 qt5 的 lazarus，lazarus-ide-qt5 ，卸载 lazarus-ide-gtk2，fcitx5-frontend-qt5 已经安装了不用再手动安装

**Comment by afrusrsc** [comment]
@wengxt 非常感谢🙏🙏🙏，安装`fcitx5-frontend-gtk2`后连击问题已解决，其它问题我会自己尝试
