### ISSUE TITLE
在Deepin-QQ、Deepin-WeChat中切到英文时自动大写

### ISSUE THREAD

**Issue by kqwyf** [fcitx/fcitx5#101]
系统：Manjaro (最后更新于20200823)
软件：archlinuxcn上的deepin.com.qq.im，aur上的deepin.com.wechat2
复现：安装好fcitx5  fcitx5-chinese-addons fcitx5-qt fcitx5-gtk kcm-fcitx5后，使用拼音输入法，光标放在在QQ/微信输入框中，多按几次Shift切换至英文状态（经验证若一开始默认在英文状态则不会出现问题，必须要按Shift至少一次），然后输入任意英文字符，将发现字符自动大写，且按住Shift也无法切换为小写。当输入如“/”符号时也会自动变为“?”，现象与Shift键未松开十分类似。已确认过大写锁定键未开启。
其他现象：若在大写问题发生后用鼠标点击输入框，则大写问题消失（但再次按Shift后该问题重新出现）。若在QQ中按Ctrl+Alt+Z（激活会话窗口快捷键），则大写问题消失（但再次按Shift后该问题重新出现）。

此外，非wine程序未出现该问题。

感觉可能是按Shift切换中英文状态后wine程序没有检测到Shift松开的事件。。

**Comment by interskh** [comment]
我今天也发现了类似的问题 后来有解决不？

**Comment by kqwyf** [comment]
> 我今天也发现了类似的问题 后来有解决不？

已经解决了。

@interskh 在你的留言上方可以看到，作者wengxt在2020年8月23日提交了553d85a这个commit关闭了这个issue，这个commit就是解决的这个问题。如果你用的是Arch或Manjaro的话，更新到最新版就好。如果是其它发行版，仓库中打包的不是fcitx5的最新版本，你可能需要自己想办法安装最新版。
