### ISSUE TITLE
opensuse tumbleweed with kde6 wayland: flatpak package doesn't work but system package (installed using zypper) works

### ISSUE THREAD

**Issue by nerditation** [fcitx/fcitx5#1017]
**Describe the bug**

I was trying out kde6 on opensuse. if I install fcitx5 from flathub, it shows up as a virtual keyboard, but it cannot be activated, nor can the configtool window be opened by right clicking. however, if I install fcitx5 using the system package manager `zypper`, it works as expected.

if I manually launch fcitx: `flatpak run org.fcitx.Fcitx5`, I **can** open the config tool to add additional languages, but I get a warning about wayland and kwin and virtual keyboard stuff, and input method is not working (apparently).

**To Reproduce**

1. install opensuse, selecting KDE desktop environment
2. make sure `flathub` registry is added to flatpak
   - manual configuration: `flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`
   - use the "flatpak-remote-flathub" package: `zypper in flatpak-remote-flathub`
4. install fcitx5 using flatpak
   - `flatpak install org.fcitx.Fcitx5`
5. open KDE system settings, search "virtual keyboard"
6. select "fcitx5" and apply
7. may need to re-login or reboot.
8. activate input method using shortcut key or the system tray icon

**Expected behavior**

when right click the "input method" icon on the system tray, then click "configuration", should show fcitx config window
when an application has keyboard focus, should be able to activate fcitx and use input method. 

**Desktop:**

 - Desktop: kde6
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.
   - cannot figure out how to run `fcitx5-diagnose` inside flatpak container (is it even packaged with flatpak???)

**Additional context**

out of curiosity, I played with several systems:

- kde neon (physical machine, not VM): everything works as expected, no problem at all:
  - `apt install fcitx5`, shows two virtual keyboard `Fcitx5` and `Fcitx5 Wayland Launcher`, both works
  - `flatpak --system install org.fcitx.Fcitx5`, shows single `Fcitx5` virtual keyboard, works
  - `flatpak --user install org.fcitx.Fcitx5`,  same as `flatpak --system`, single `Fcitx5` virtual keyboard, works
- opensuse Kalpa (both physical machine **AND** VM, result is same): `rpm` package works, `flatpak` broken
  - `transactional-update pkg in fcitx5`, two virtual keyboard `Fcitx5` and `Fcitx5 Wayland Launcher`, both works
  - `flatpak --system install org.fcitx.Fcitx5`, shows single `Fcitx5` virtual keyboard, but **NOT** working
  - `flatpak --user install org.fcitx.Fcitx5`,  same as `flatpak --system`, single `Fcitx5` virtual keyboard, NOT working
- opensuse tumbleweed (virtualbox): same as `Kalpa`, `rpm` package (using `zypper`) works, `flatpak` broken
- fedora Kinoite 40 beta (virtualbox): same as opensuse, `rpm` package (using `rpm-ostree`) works, `flatpak` broken

also, just for completeness, `flatpak` package works fine with `gnome` desktop on opensuse tumbleweed.

I think it might be a package issue, and I tend to report to the opensuse package maintainer, but I don't even know where to look at, as I have absolute no idea how input method works on KDE wayland.

**Comment by wengxt** [comment]
I believe it's due to https://github.com/flatpak/flatpak/issues/5614 .  I have been waiting for a new flatpak release to include my fix https://github.com/flatpak/flatpak/commit/0402e1614c79de2fbc17042132f4dee0b2b80bcd

Let me try if flathub has this new flatpak or not.. otherwise I can't add this flag.

Does tumbleweed has flatpak 1.15.7 ?

**Comment by wengxt** [comment]
I just added this flag to fcitx5-unstable repo, flathub build machine doesn't have 1.15.7 https://github.com/flathub/org.fcitx.Fcitx5/pull/22 .

I can see now it works here on archlinux with flatpak 1.15.7. 

Can you paste the output of 
```
qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
```

with your current not-working flatpak package?

**Comment by nerditation** [comment]
thanks for the quick reply. here's some more information.

> I believe it's due to [flatpak/flatpak#5614](https://github.com/flatpak/flatpak/issues/5614) .
> [...]
> Does tumbleweed has flatpak 1.15.7 ?

I see, that's probably it. opensuse has flatpak 1.15.6 as of today.



> Can you paste the output of
> 
> ```
> qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
> ```
> 
> with your current not-working flatpak package?

sure, here it is:

```console
~$ qdbus6 org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
Group [x11::1] has 0 InputContext(s)
Input Context without group

```

**Comment by wengxt** [comment]
https://groups.google.com/g/fcitx/c/sJPrFn0CT2U/m/8PKxQg7AAQAJ

**Comment by nerditation** [comment]
I can confirm that, flatpak 1.15.7 indeed fixed the problem.

for opensuse tumbleweed users who reached this thread through searching, until the official package is updated, if you want to try it out but don't want to build flatpak from source, I have forked the official tumbleweed package and adapted the build spec to version 1.15.7 and the meson build system. here's the link to the obs community package:

https://software.opensuse.org//download.html?project=home%3Anerditation&package=flatpak
