### ISSUE TITLE
Cannot type Vietnamese (fcitx5-unikey) in self-written application with pyqt5 in linux mint

### ISSUE THREAD

**Issue by thanhnguyenhy234** [fcitx/fcitx5#1021]
**Describe the bug**
I cannot type Vietnamese (fcitx5-unikey) in my self-written application using pyqt5, even though I have set environment variables in /etc/environment:
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

**Desktop (please complete the following information):**
 - Desktop: Cinnamon (linux mint)
 - Display server type: X11
 - The output of fcitx5-diagnose if possible.

# System Info:
1.  `uname -a`:

        Linux lediem 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Linuxmint
        Description:	Linux Mint 21.3
        Release:	21.3
        Codename:	virginia

3.  `lsb_release -d`:

        Description:	Linux Mint 21.3

4.  `/etc/lsb-release`:

        DISTRIB_ID=LinuxMint
        DISTRIB_RELEASE=21.3
        DISTRIB_CODENAME=virginia
        DISTRIB_DESCRIPTION="Linux Mint 21.3 Virginia"

5.  `/etc/os-release`:

        NAME="Linux Mint"
        VERSION="21.3 (Virginia)"
        ID=linuxmint
        ID_LIKE="ubuntu debian"
        PRETTY_NAME="Linux Mint 21.3"
        VERSION_ID="21.3"
        HOME_URL="https://www.linuxmint.com/"
        SUPPORT_URL="https://forums.linuxmint.com/"
        BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
        PRIVACY_POLICY_URL="https://www.linuxmint.com/"
        VERSION_CODENAME=virginia
        UBUNTU_CODENAME=jammy

6.  Desktop Environment:

    Desktop environment is `gnome3`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)+group(win_space_toggle)+terminate(ctrl_alt_bksp)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", "grp:win_space_toggle,terminate:ctrl_alt_bksp"

3.  Locale:

    1.  All locales:

            C
            C.utf8
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IL
            en_IL.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            POSIX
            vi_VN
            vi_VN.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LANGUAGE=en_US
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC=vi_VN
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY=vi_VN
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER=vi_VN
            LC_NAME=vi_VN
            LC_ADDRESS=vi_VN
            LC_TELEPHONE=vi_VN
            LC_MEASUREMENT=vi_VN
            LC_IDENTIFICATION=vi_VN
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/lediem

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/lediem/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/lediem/.config/fcitx5`).

5.  Current user:

    The script is run as lediem (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.14`

3.  process:

    Found 1 fcitx5 process:

           1399 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.47`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `1399`.

    Debug information from dbus:

           Group [x11::0] has 9 InputContext(s)
          IC [23f587e93e5f431487141188bef0a8fa] program:gnome-terminal- frontend:fcitx4 cap:12 focus:1
          IC [1d68e628453c4396b0a578742f7e8e30] program:thorium frontend:fcitx4 cap:12 focus:0
          IC [5496b7539be542538af120b84623dbe9] program:nemo-desktop frontend:fcitx4 cap:12 focus:0
          IC [528a76c9cc764b8e9f48ae77cfd10b10] program:kdeconnectd frontend:fcitx4 cap:12 focus:0
          IC [523074c14dc94791978ccbeacd755657] program:nemo-desktop frontend:fcitx4 cap:12 focus:0
          IC [4fff5a0c7b5e49cdbb4b37f53a8378c5] program:kdeconnectd frontend:fcitx4 cap:12 focus:0
          IC [1111a64c028a4b94b98214d8fada9889] program:nemo-desktop frontend:fcitx4 cap:12 focus:0
          IC [fb35853bc56749deb665844d0f02d976] program:Telegram frontend:dbus cap:6800800072 focus:0
          IC [20e6c768baca405abd5e1c95edcb966f] program:nemo-desktop frontend:fcitx4 cap:12 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx5-unikey-macro-editor.so`.
    Found unknown fcitx qt module: `/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    Found fcitx5 im module for qt5: `/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/lib/x86_64-linux-gnu/fcitx/qt/libfcitx-unikey-macro-editor.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.33` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.33

        Found fcitx5 im modules for gtk `3.24.33`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 22 enabled addons:

            Classic User Inteface 5.0.14
            Clipboard 5.0.14
            DBus 5.0.14
            DBus Frontend 5.0.14
            Emoji 5.0.14
            Fcitx4 Frontend 5.0.14
            IBus Frontend 5.0.14
            Lua IME API 5.0.6
            Input method selector 5.0.14
            Keyboard 5.0.14
            KDE Input Method Panel 5.0.14
            Lua Addon Loader 5.0.6
            Status Notifier 5.0.14
            Notification 5.0.14
            Quick Phrase 5.0.14
            Spell 5.0.14
            Unicode 5.0.14
            Unikey Wrapper For Fcitx 5.0.8
            Wayland 5.0.14
            Wayland Input method frontend 5.0.14
            XCB 5.0.14
            X Input Method Frontend 5.0.14

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Inteface
        KDE Input Method Panel

## Input Methods:
1.  `/home/lediem/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=unikey

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=unikey
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Mon Apr 22 02:43:14 PM +07 2024

2.  `/home/lediem/.config/fcitx5/crash.log`:

        =========================
        Fcitx 5.0.14 -- Get Signal No.: 11
        Date: try "date -d @1713748272" if you are using GNU date ***
        ProcessID: 1409
        /usr/bin/fcitx5(+0xf9cd)[0x564607c669cd]
        /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7efcf8380520]
        /usr/lib/x86_64-linux-gnu/fcitx5/unikey.so(+0x1aaac)[0x7efcf4febaac]
        /usr/lib/x86_64-linux-gnu/fcitx5/unikey.so(+0x15620)[0x7efcf4fe6620]
        /lib/x86_64-linux-gnu/libFcitx5Core.so.7(_ZNK5fcitx8Instance9postEventERNS_5EventE+0x394)[0x7efcf88eaa74]
        /lib/x86_64-linux-gnu/libFcitx5Core.so.7(_ZN5fcitx12InputContext8keyEventERNS_8KeyEventE+0xa9)[0x7efcf890b2f9]
        /usr/lib/x86_64-linux-gnu/fcitx5/libdbusfrontend.so(+0xc3ff)[0x7efcf670b3ff]
        /usr/lib/x86_64-linux-gnu/fcitx5/libdbusfrontend.so(+0xd0c2)[0x7efcf670c0c2]
        /lib/x86_64-linux-gnu/libFcitx5Utils.so.2(+0x36f37)[0x7efcf882ff37]
        /lib/x86_64-linux-gnu/libFcitx5Utils.so.2(+0x3cb39)[0x7efcf8835b39]
        /lib/x86_64-linux-gnu/libsystemd.so.0(+0x3327b)[0x7efcf825a27b]
        /lib/x86_64-linux-gnu/libsystemd.so.0(+0x4176d)[0x7efcf826876d]
        /lib/x86_64-linux-gnu/libsystemd.so.0(+0x49467)[0x7efcf8270467]
        /lib/x86_64-linux-gnu/libsystemd.so.0(+0x73669)[0x7efcf829a669]
        /lib/x86_64-linux-gnu/libsystemd.so.0(sd_event_dispatch+0x13d)[0x7efcf829a98d]
        /lib/x86_64-linux-gnu/libsystemd.so.0(sd_event_run+0xc8)[0x7efcf829d1c8]
        /lib/x86_64-linux-gnu/libsystemd.so.0(sd_event_loop+0x5f)[0x7efcf829d3ef]
        /lib/x86_64-linux-gnu/libFcitx5Utils.so.2(_ZN5fcitx9EventLoop4execEv+0x15)[0x7efcf88346a5]
        /lib/x86_64-linux-gnu/libFcitx5Core.so.7(_ZN5fcitx8Instance4execEv+0x54)[0x7efcf88ed3d4]
        /usr/bin/fcitx5(+0xdee7)[0x564607c64ee7]
        /lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7efcf8367d90]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7efcf8367e40]
        /usr/bin/fcitx5(+0xeef5)[0x564607c65ef5]

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by thanhnguyenhy234** [comment]
The above problem does not occur when I use other distros such as endeavor os kde, kubuntu, etc.

**Comment by wengxt** [comment]
Likely missing some package, or your pyqt is not system qt.

Do you have fcitx5-frontend-qt5 installed?

Is your pyqt from distro package?

**Comment by thanhnguyenhy234** [comment]
fcitx5-frontend-qt5 is already the newest version (5.0.10-1build1).

**Comment by wengxt** [comment]
Ah, that's probably the reason.

pip installed pyqt5 doesn't use the system Qt, but the one directly downloaded from pypi, which means it can not load system qt im module plugin.

I would suggest you use pyqt from system. https://packages.ubuntu.com/jammy/python3-pyqt5

Or, you can set QT_IM_MODULE=ibus before you run your pyqt app since ibus im module is part of qt, to use fcitx5's ibus frontend, I think that will also work.
