### ISSUE TITLE
SOVERSION and PROPERTIES VERSION mismatch

### ISSUE THREAD

**Issue by zhsj** [fcitx/fcitx5#103]
Now we get:

```
lrwxrwxrwx  1 zhsj zhsj   20 Aug 25 18:18 libFcitx5Config.so -> libFcitx5Config.so.6
-rw-r--r--  1 zhsj zhsj 3.8M Aug 25 18:16 libFcitx5Config.so.5.0
lrwxrwxrwx  1 zhsj zhsj   22 Aug 25 18:18 libFcitx5Config.so.6 -> libFcitx5Config.so.5.0
lrwxrwxrwx  1 zhsj zhsj   18 Aug 25 18:18 libFcitx5Core.so -> libFcitx5Core.so.6
-rw-r--r--  1 zhsj zhsj  21M Aug 25 18:17 libFcitx5Core.so.5.0
lrwxrwxrwx  1 zhsj zhsj   20 Aug 25 18:18 libFcitx5Core.so.6 -> libFcitx5Core.so.5.0
lrwxrwxrwx  1 zhsj zhsj   19 Aug 25 18:18 libFcitx5Utils.so -> libFcitx5Utils.so.2
lrwxrwxrwx  1 zhsj zhsj   21 Aug 25 18:18 libFcitx5Utils.so.2 -> libFcitx5Utils.so.5.0
-rw-r--r--  1 zhsj zhsj  14M Aug 25 18:16 libFcitx5Utils.so.5.0
drwxr-xr-x  2 zhsj zhsj 4.0K Aug 25 18:18 pkgconfig
```

Looks quite strange.

**Comment by wengxt** [comment]
It's totally OK and common.

**Comment by zhsj** [comment]
Ok, find another problem... libFcitx5Core.so `SONAME` is bumped from 5 to 6, but `PROPERTIES VERSION` is still 5.0.
This makes downstream can't coinstall both version during the library transition.

For example,

Previously we can have libfcitx5config5, which contains,

```
/usr/lib/x86_64-linux-gnu/libFcitx5Config.so.5.0
/usr/lib/x86_64-linux-gnu/libFcitx5Config.so.5
```

If we take the same procedure for new version, we call it libfcitx5config6, it will contain,

```
/usr/lib/x86_64-linux-gnu/libFcitx5Config.so.5.0
/usr/lib/x86_64-linux-gnu/libFcitx5Config.so.6
```

Now the old and new version has same file /usr/lib/x86_64-linux-gnu/libFcitx5Config.so.5.0, so they can't coinstall.

It causes difficulty for library transition. When other packages haven't been rebuilt for new version, they got a broken status.

So the problem now is reusing PROPERTIES VERSION when changing SOVERSION.

**Comment by wengxt** [comment]
Well, there's no offical release. So I don't bother fix that. And coinstall 5/6 so version doesn't make any sense for fcitx case.

**Comment by zhsj** [comment]
coinstall is a transient status, since distributions need time to rebuild all reverse build-depends packages.

**Comment by wengxt** [comment]
Even so, the co-install doesn't make much sense to me. For a packaging environment, shouldn't it only install necessary packages to avoid any side effects during build? Why would it want to install both during the packaging?

To be honest, I don't even need to bother bump so version at all since there's not "stable" API yet (mostly, but I can't guarantee until a stable version is released). I just bump the so version to make distro like arch doesn't hit random crash because of building own AUR package.

**Comment by zhsj** [comment]
> Why would it want to install both during the packaging

It's not. During building of course only the latest version is used.

It's for users. When fcitx5 has bumped version, but some fcitx5-* packages haven't been rebuild(the time frame is usually short). But users may partially upgrade fcitx5, without upgrading fctix5-*  packages. I think it's same for Arch, the random crash I guess is because some packages haven't been rebuilt, but using the new library.

**Comment by zhsj** [comment]
The usual way for library transition is:

1. libfoo bump from 1 -> 2. So package name is renamed to libfoo1 -> libfoo2.
2. Now all reverse packages begin to rebuild, some quick, some slow.
3. Users begin to upgrade, some packages have been rebuilt, so users now install the libfoo2. But some packages haven't been rebuilt, so libfoo1 is not uninstalled. The libfoo1 and libfoo2 should be coinstallable.
4. All packages have been rebuilt. And users have upgraded all reverse packages. They can remove libfoo1 safely now.

**Comment by yuyichao** [comment]
Well at least in this case, the packages that depends on fcitx5 won’t be useable anyway even if you have the old version of the library installed so that should not be a concern.

In another word, those will be broken no matter what and keeping the old Lin doesn’t fix that.
