### ISSUE TITLE
5.1.9 buggy in hyprland

### ISSUE THREAD

**Issue by GanddoffChan** [fcitx/fcitx5#1037]
**Describe the bug**
when using 5.1.9 in hyprland, sometimes after switching window focus, the border shows the focus has been changed, but typing anything doesn't register on the new window
downgrading to 5.1.8 solves the issue

**To Reproduce**
1. install hyprland 0.39.1-5 and fcitx5 5.1.9 on archlinux
2. configure the enviornment variables as described in the arch wiki
3. run fcitx5 in hyprland
4. open window, try to type, switch workspace and open window and type and so on
**Expected behavior**
occational failure to type anything
**Desktop (please complete the following information):**
hyprland
Wayland
 
**Additional context**

**Comment by wengxt** [comment]
Fixed on hyprland master

https://github.com/hyprwm/Hyprland/issues/5763
