### ISSUE TITLE
智能手环通过采集肌肉电信号实现输入设备升级能否可行？

### ISSUE THREAD

**Issue by chenshijie-uos-edu** [fcitx/fcitx5#105]
感觉用手写代码太麻烦了，希望可以支持脑电信号，或者肌肉点信号。前辈们觉得这个想法可行吗？

**Comment by zccrs** [comment]
这个问题的难度不在于输入法框架，建议先关闭issue，你可以先推进解决生物学方面的问题，之后再讨论如何跟输入法方面做对接
