### ISSUE TITLE
中文输入法在查找应用程序和设置里的问题

### ISSUE THREAD

**Issue by flowerseacar** [fcitx/fcitx5#1055]
### Summary

在查找应用程序的时候无法打出中文
设置里我明明是中文输入状态，结果第一个字出来的确实英文。不过我不是在搜索框里打的第一个字，我是直接光标在设置里的其他位置打的第一个字

### Steps to Reproduce

使用中文在设置非搜索框位置和查找应用程序搜索框那里打字就可以了

### Expected Behavior

正常是可以正常打出中文，并且第一个字也是中文状态

### Output of fcitx5-diagnose command

 LC_ALL=C fcitx5-diagnose
# System Info:
1.  `uname -a`:

        Linux ubuntu22 6.5.0-35-lowlatency #35.1~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 11:32:45 UTC x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu 22.04.4 LTS
        Release:	22.04
        Codename:	jammy

3.  `lsb_release -d`:

        Description:	Ubuntu 22.04.4 LTS

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=22.04
        DISTRIB_CODENAME=jammy
        DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"

5.  `/etc/os-release`:

        PRETTY_NAME="Ubuntu 22.04.4 LTS"
        NAME="Ubuntu"
        VERSION_ID="22.04"
        VERSION="22.04.4 LTS (Jammy Jellyfish)"
        VERSION_CODENAME=jammy
        ID=ubuntu
        ID_LIKE=debian
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        UBUNTU_CODENAME=jammy

6.  Desktop Environment:

    Desktop environment is `gnome3`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IL
            en_IL.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            zh_CN.utf8
            zh_SG.utf8

    2.  Current locale:

            LANG=zh_CN.UTF-8
            LANGUAGE=zh_CN:zh:en_US:en
            LC_CTYPE="C"
            LC_NUMERIC="C"
            LC_TIME="C"
            LC_COLLATE="C"
            LC_MONETARY="C"
            LC_MESSAGES="C"
            LC_PAPER="C"
            LC_NAME="C"
            LC_ADDRESS="C"
            LC_TELEPHONE="C"
            LC_MEASUREMENT="C"
            LC_IDENTIFICATION="C"
            LC_ALL=C

4.  Directories:

    1.  Home:

            /home/ubuntu22

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/ubuntu22/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/ubuntu22/.config/fcitx5`).

5.  Current user:

    The script is run as ubuntu22 (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.14`

3.  process:

    Found 1 fcitx5 process:

           2644 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.311`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `2644`.

    Debug information from dbus:

           Group [x11::1] has 16 InputContext(s)
          IC [c0bdf868a6b04619bda2c456532f5de6] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [532170e3447548ffbead9331ef1ca556] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [460e48903d3240a59bca7426a71d2697] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [cf0a764b320a425daaebb5d91da481f5] program:gnome-control-center frontend:dbus cap:6000000052 focus:0
          IC [df4185f936ec4c0da461fbdd22ab6655] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [3eff37332c0a40c699dcc3b94bb3b173] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [6dab9ed3a4e843d7bf3d0903b2b0c060] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [8d3e3356fabc435ea13796cb788288b0] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [6c7633b5aea24e02925fbde2b98f534a] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [9b4c370920b74e31b1692dd7bf3ed8d0] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [b39c24a23b994006820b23bedc520302] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [943e608369024e6798d2b35f309955d2] program:gnome-control-center frontend:dbus cap:6000000012 focus:0
          IC [8bd797cff8514c39886140f8e4e355db] program:brave frontend:fcitx4 cap:12 focus:0
          IC [78d3041b75c64b7c883423effc9816bc] program:gnome-terminal-server frontend:dbus cap:6000000012 focus:0
          IC [dde9d564a1ab4c39afc7e57a93c950a5] program:gnome-terminal-server frontend:dbus cap:6000000012 focus:1
          IC [102dab170fde4073a0d6287a1abdddab] program:gjs frontend:dbus cap:6000000012 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM encoding:

    **Your LC_CTYPE is set to C whose encoding is not UTF-8. You may have trouble committing strings using XIM.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for qt5: `/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.33` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.33

        Found fcitx5 im modules for gtk `3.24.33`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 21 enabled addons:

            Simplified and Traditional Chinese Translation 5.0.11
            Classic User Inteface 5.0.14
            Clipboard 5.0.14
            Cloud Pinyin 5.0.11
            DBus 5.0.14
            DBus Frontend 5.0.14
            Emoji 5.0.14
            Fcitx4 Frontend 5.0.14
            Full width character 5.0.11
            Input method selector 5.0.14
            Keyboard 5.0.14
            Status Notifier 5.0.14
            Notification 5.0.14
            Pinyin 5.0.11
            Extra Pinyin functionality 5.0.11
            Punctuation 5.0.11
            Spell 5.0.14
            Table 5.0.11
            Unicode 5.0.14
            Wayland 5.0.14
            XCB 5.0.14

    2.  Found 5 disabled addons:

            IBus Frontend 5.0.14
            KDE Input Method Panel 5.0.14
            Quick Phrase 5.0.14
            Wayland Input method frontend 5.0.14
            X Input Method Frontend 5.0.14

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 1 enabled user interface addons:

        Classic User Inteface

## Input Methods:
1.  `/home/ubuntu22/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name="分组 1"
        # Layout
        Default Layout=cn
        # Default Input Method
        DefaultIM=pinyin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-cn
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=pinyin
        # Layout
        Layout=

        [GroupOrder]
        0="分组 1"

# Log:
1.  `date`:

        Fri May 17 13:58:32 CST 2024

2.  `/home/ubuntu22/.config/fcitx5/crash.log`:

    `/home/ubuntu22/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by wengxt** [comment]
主要是程序的问题，type on search 类型的功能日常对输入法支持很差劲
