### ISSUE TITLE
A bug with electron

### ISSUE THREAD

**Issue by zdy023** [fcitx/fcitx5#106]
When I have typed something in the `electronic-wechat` and press `ctrl+space' to deactivate the fcitx5, it turns to switch to the next input method rather than deactivate the fcitx5, if there is a prediction box on the screen. It works well if there isn't any prediction item.

My Environment:

System and desktop:

* Manjaro 20.1 Mikah
* x86_64 Linux 5.7.15-1-MANJARO
* KDE 5.73.0 / Plasma 5.19.4

Relative software:

* node v8.17.0 (nodejs 14.8.0)
* electron v9.2.0
* Electronic Wechat v2.3.1
* fcitx5 - the git version in the archlinuxcn repository which is compiled from the latest version in the github repository

**Comment by wengxt** [comment]
Doesn't sounds like a bug. You probably triggered a feature.
If you don't release ctrl, you will be able to continuously press space to enumerate all the input method.

There's an option to disable this behavior.

electronics-wechat doesn't allow me to login so I can't really test. I tried another electron app but didn't see the exact behavior you mentioned.
