### ISSUE TITLE
在GTK程序中快速打字会掉字

### ISSUE THREAD

**Issue by chitang233** [fcitx/fcitx5#107]
OS: Arch Linux 5.8.4
DE: KDE Plasma      WM:KWin
使用X11显示服务
安装了 fcitx5-git fcitx5-gtk-git fcitx5-pinyin-moegirl fcitx5-pinyin-zhwiki fcitx5-qt4-git fcitx5-qt5-git fcitx5-anthy fcitx5-chewing fcitx5-chinese-addons fcitx5-config-qt-git fcitx5-configtool-git
具体表现：在GTK程序中快速打字会出现漏字的情况，包括但不限于Chrome Code-OSS Typora
但在Qt程序中没有这样的问题 包括但不限于 Konsole KDE系统设置 LibreOffice OBS-Studio Neovim-Qt
[问题表现](https://github.com/fcitx/fcitx5/files/5139558/2020-08-28.09-31-14.tar.gz)

**Comment by wengxt** [comment]
根据你在 Code-OSS 中没有 preedit 可以看出你没有用上 fcitx5-gtk 的 im module，建议检查配置设置好 GTK_IM_MODULE=fcitx

**Comment by chitang233** [comment]
设置过了...
以下为我的.xprofile文件
export LANG=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
export WINEARCH=win32
export WINEPREFIX=/home/chitang/Wine/.wine
export GTM_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS="@im=fcitx5"
export PATH="$PATH:/home/chitang/.gem/ruby/2.7.0/bin"

**Comment by sadhen** [comment]
在我自己开发的Qt程序里面也遇到了这样的问题

我的~/.xprofile 的有这样的配置：
```
export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT_IM_MODULE=fcitx
```

**Comment by sadhen** [comment]
估计是我自己开发的代码有问题，然后导致fcitx自动提交了

**Comment by sadhen** [comment]
问题在于，我这边的代码，有一个动态更新的工具栏，然后这个工具栏的更新触发的时间，会导致输入法出问题

**Comment by wengxt** [comment]
你这个是 qt 程序，完全不是一回事。如果需要帮忙可以到邮件列表帮你看看代码

**Comment by sadhen** [comment]
非常感谢 昨天joris已经修复了那个问题 see https://github.com/texmacs/texmacs/commit/2b8348c43b1f2dea7d53c19987871213d65e2b43
