### ISSUE TITLE
用fcitx-rime,fcitx5-chinese-addons 在konsole与qterminal中输入时光标不跟随

### ISSUE THREAD

**Issue by knm100** [fcitx/fcitx5#1072]
### Summary

环境：
Arch Linux+LXQT2.0.1(wayland会话）+LABWC0.72窗口合成器+FCITX5-RIME
在Konsole中启动nano，如果不设置QT_IM_MODULE，输入中文时，侯选词框不跟随光标;  设置QT_IM_MODULE=fcitx后, 侯选词框能正常跟随光标
备注：在Konsole及其它QT程序中本身中输入不需要设置QT_IM_MODULE=fcitx也可以正常光标跟随，只有在konsole中启动的nano里输入时会有这个问题，需要设置QT_IM_MODULE=fcitx才能解决。

如果把LABWC 换成KWIN_Wayland,  不需要设置QT_IM_MODULE,也可以nano中正常输入

保持窗口合成器为LABWC, 更换输入法模块为 fcitx5-chinese-addons,  不设置QT_IM_MODULE=fcitx,  在konsole（包括在Konsole中启动nano时）等QT程序中也会光标不跟随， 设置QT_IM_MODULE=fcitx后，输入正常。

### Steps to Reproduce

具体步骤已经在Summary中详细描述

### Expected Behavior

期望不用额外设置QT_IM_MODULE=fcitx 而用 text input v3 协议输入

### Output of fcitx5-diagnose command

nm@archlinux ~]$ fcitx5-diagnose
# 系统信息:
1.  `uname -a`:

        Linux archlinux 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:    n/a
        Distributor ID: Arch
        Description:    Arch Linux
        Release:        rolling
        Codename:       n/a

3.  `lsb_release -d`:

        Description:    Arch Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="Arch"
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

6.  桌面环境：

    无法确定桌面环境。

7.  XDG 会话类型：

        XDG_SESSION_TYPE='wayland'

8.  Bash 版本：

        BASH_VERSION='5.2.26(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=''

        WAYLAND_DISPLAY='wayland-0'

2.  键盘布局：

    1.  `setxkbmap`:

            Cannot open display "default display"

    2.  `xprop`:

            xprop:  unable to open display ''

3.  Locale：

    1.  全部可用 locale：

            C
            C.utf8
            en_US.utf8
            POSIX
            zh_CN.utf8
            zh_TW.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC=zh_CN.UTF-8
            LC_TIME=zh_CN.UTF-8
            LC_COLLATE=zh_CN.UTF-8
            LC_MONETARY=zh_CN.UTF-8
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT=zh_CN.UTF-8
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/knm

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 是设定为 `/home/knm/.config` 。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/knm/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/knm/.config/fcitx5`)。

5.  当前用户：

    脚本作为 knm (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: `5.1.10`

3.  进程：

    找到了 1 个 fcitx5 进程：

           4215 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` 工作正常。

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.139`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `4215`。

    来自 dbus 的调试信息：

           Group [wayland:] has 3 InputContext(s)
          IC [faae1093c4154abaab10e4f4f4fa960a] program:org.kde.konsole frontend:wayland_v2 cap:d0072 focus:1
          IC [61d787f57f7f4855989fe77be13216f0] program:chromium frontend:wayland_v2 cap:d0072 focus:0
          IC [ec5c1fb0fd594c1a90614be9ee7aa3be] program: frontend:wayland_v2 cap:d0072 focus:0
        Input Context without group

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

    **`kcmshell5` 未找到.**

# 前端设置：
此脚本检查的环境变量仅能显示当前命令行的环境。仍有可能您的环境并没有应用于整个桌面。您可以通过使用命令对某个无法正常工作的进程使用命令 `xargs -0 -L1 /proc/$PID/environ` 检查此进程的实际的环境变量。

## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS 没有设置**

    **请使用您发行版提供的工具将环境变量 XMODIFIERS 设为 "@im=fcitx" 或者将 `export XMODIFIERS=@im=fcitx` 添加到您的 `~/.xprofile` 中。参见 [输入法相关的环境变量：XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#XMODIFIERS)。**
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    **无法在根窗口找到 xim_server。**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **请使用您发行版提供的工具将环境变量 QT_IM_MODULE 设为 "fcitx" 或者将 `export QT_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中。参见 [输入法相关的环境变量：QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#QT_IM_MODULE)。**

    **`fcitx5-qt4-immodule-probing` 未找到.**

2.  qt5 - `${QT_IM_MODULE}`:

    **请使用您发行版提供的工具将环境变量 QT_IM_MODULE 设为 "fcitx" 或者将 `export QT_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中。参见 [输入法相关的环境变量：QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#QT_IM_MODULE)。**

    **如果您的混成器完全支持 qt5 使用的 text-input 协议，您也可以使用 qt5 内置的 Wayland 模块。**

    使用 fcitx5-qt5-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

3.  qt6 - `${QT_IM_MODULE}`:

    **请使用您发行版提供的工具将环境变量 QT_IM_MODULE 设为 "fcitx" 或者将 `export QT_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中。参见 [输入法相关的环境变量：QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#QT_IM_MODULE)。**

    **如果您的混成器完全支持 qt6 使用的 text-input 协议，您也可以使用 qt6 内置的 Wayland 模块。**

    使用 fcitx5-qt6-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

4.  Qt 输入法模块文件：

    找到了 fcitx5 的 qt6 输入法模块：`/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了未知的 fcitx qt 模块：`/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`。
    找到了 fcitx5 的 qt 输入法模块：`/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了 fcitx5 qt5 模块：`/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    找到了 fcitx5 qt6 模块：`/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`。

    下列错误也许并不准确，因为对路径所对应的 Qt 版本的猜测取决于发行版如何打包 Qt。如果您不使用任何对应版本的 Qt 程序，或者在 Wayland 下使用 Qt 的 text-input 支持，下列错误也不是严重问题。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **请使用您发行版提供的工具将环境变量 GTK_IM_MODULE 设为 "fcitx" 或者将 `export GTK_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中。参见 [输入法相关的环境变量：GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#GTK_IM_MODULE)。**

    **如果您的混成器完全支持 gtk 使用的 text-input 协议，您也可以使用 gtk 内置的 Wayland 模块。**

    使用 fcitx5-gtk2-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

    使用 fcitx5-gtk3-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        GTK_IM_MODULE=wayland

    使用 fcitx5-gtk4-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`。**

        **无法找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        在 `/usr/bin/gtk-query-immodules-3.0` 找到了 gtk `3.24.42` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.42

        已找到 gtk `3.24.42` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        **无法找到 gtk 2 的输入法模块缓存**

        **无法在缓存中找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.42` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.42

        已找到 gtk `3.24.42` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 21 个已启用的插件：

            Classic User Interface 5.1.10
            Clipboard 5.1.10
            DBus 5.1.10
            DBus Frontend 5.1.10
            Emoji 5.1.10
            Fcitx4 Frontend 5.1.10
            IBus Frontend 5.1.10
            Input method selector 5.1.10
            Keyboard 5.1.10
            KDE Input Method Panel 5.1.10
            Status Notifier 5.1.10
            Notification 5.1.10
            Quick Phrase 5.1.10
            Rime 5.1.8
            Spell 5.1.10
            Unicode 5.1.10
            DBus Virtual Keyboard 5.1.10
            Wayland 5.1.10
            Wayland Input method frontend 5.1.10
            XCB 5.1.10
            X Input Method Frontend 5.1.10

    2.  找到了 0 个被禁用的插件：

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 3 个已启用的用户界面插件：

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## 输入法：
1.  `/home/knm/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=默认
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=rime

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=rime
        # Layout
        Layout=

        [GroupOrder]
        0=默认

# 日志：
1.  `date`:

        2024年 06月 10日 星期一 11:58:01 CST

2.  `/home/knm/.config/fcitx5/crash.log`:

    `/home/knm/.config/fcitx5/crash.log` 未找到.

**警告：fcitx5-diagnose 的输出可能包含敏感信息，包括发行版名称，内核版本，正在运行的程序名称等。**

**尽管这些信息对于开发者诊断问题有帮助，请在公开发送到在线网站前检查并且根据需要移除的对应信息。**

**Comment by wengxt** [comment]
不跟随的时候它显示在哪？能不能截个图？

**Comment by knm100** [comment]
一般会在截图中红圈那两个地方，不是确定的，有时侯在上面，有时侯在下面。
![swappy-20240611-185413](https://github.com/fcitx/fcitx5/assets/166389780/a60ae757-fdf0-49dc-8416-b5a422f21262)

**Comment by knm100** [comment]
有时侯出现在上面会让人产生光标跟随的感觉，但实际上不跟随的，把光标移动到窗口底部，那个侯选词框也还是会在上面。

**Comment by knm100** [comment]
补充如下信息供你参考：
在同样的环境下，如果把konsole换成xfce4-terminla或者alacritty,  设置与不设置QT_IM_MODULE两种情况下， nano在这两个终端里输入都是可以光标跟随的。

**Comment by wengxt** [comment]
我阅读了一下，应该是 qt text-input-v3 的实现问题吧，那个实现一直就……还挺有问题的

kwin 下默认是 text-input-v2 实现得比较好，和 kwin 的配合也好。
