### ISSUE TITLE
When installed package "fcitx5", Kdialog letting user to install package "kcm-fcitx" conflicts with package "fcitx5".

### ISSUE THREAD

**Issue by Gen0vo** [fcitx/fcitx5#1076]
### Summary

I reported this bug to KDE
https://bugs.kde.org/show_bug.cgi?id=488342
But an user below told me to report this bug there

### Steps to Reproduce

1. sudo pacman -S fcitx5
2. choose fcitx5 in System Settings > Keyboard > Virtual Keyboard
3. Right clicking the keyboard icon at the right side of taskbar and choose "configure"
4. (!)Kdialog report to user to install package "kcm-fcitx"
5. sudo pacman -S kcm-fcitx, but did not succeeded because they are in conflict
Two packages are conflicted , and still not able to configure file in GUI.

### Expected Behavior

Kdialog should let user install fcitx5-configtool instead, so user can configure fcitx5 in GUI.
OR
No conflict report occurs when installing fcitx5 and kcm-fcitx together 

### Output of fcitx5-diagnose command

# System Info:
1.  `uname -a`:

        Linux archiso 6.6.32-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 25 May 2024 20:20:51 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:    n/a
        Distributor ID: Arch
        Description:    Arch Linux
        Release:        rolling
        Codename:       n/a

3.  `lsb_release -d`:

        Description:    Arch Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="Arch"
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

8.  Bash Version:

        BASH_VERSION='5.2.26(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY='wayland-0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)" };
                xkb_types     { include "complete"      };
                xkb_compat    { include "complete"      };
                xkb_symbols   { include "pc+us+inet(evdev)"     };
                xkb_geometry  { include "pc(pc105)"     };
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            en_US.utf8
            zh_CN.utf8

    2.  Current locale:

            LANG=C.UTF-8
            LC_CTYPE="C.UTF-8"
            LC_NUMERIC="C.UTF-8"
            LC_TIME="C.UTF-8"
            LC_COLLATE="C.UTF-8"
            LC_MONETARY="C.UTF-8"
            LC_MESSAGES="C.UTF-8"
            LC_PAPER="C.UTF-8"
            LC_NAME="C.UTF-8"
            LC_ADDRESS="C.UTF-8"
            LC_TELEPHONE="C.UTF-8"
            LC_MEASUREMENT="C.UTF-8"
            LC_IDENTIFICATION="C.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/Gen0

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/Gen0/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/Gen0/.config/fcitx5`).

5.  Current user:

    The script is run as Gen0 (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.10`

3.  process:

    Found 1 fcitx5 process:

          30099 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.167`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `30099`.

    Debug information from dbus:

           Group [wayland:] has 29 InputContext(s)
          IC [ba4a1a5def234f839b006a6e207dc874] program:org.kde.spectacle frontend:wayland cap:72 focus:0
          IC [06711e7ce9d44d50b02cf8b77ad27a61] program:org.kde.discover frontend:wayland cap:72 focus:0
          IC [d1656f92fd804b8c9c19d814c5a8a94c] program:khelpcenter frontend:dbus cap:1e001800072 focus:0
          IC [f2e052808e2e40d4a88e9229dc9a51d4] program:plasma-discover frontend:dbus cap:1e001800072 focus:0
          IC [ae2b3329624b4c27b3da970bc4080457] program:org.kde.khelpcenter frontend:wayland cap:72 focus:0
          IC [598ec29500a44893b6e66f1591a3bb8b] program: frontend:dbus cap:12 focus:0
          IC [cac2562bbeea45ddbf621de3801ea653] program: frontend:dbus cap:1000012 focus:0
          IC [6e84d272b7e147d1addccb6d88e93e0f] program: frontend:dbus cap:12 focus:0
          IC [8e3f1d1cda414d7caa6d245e90d3e81f] program: frontend:dbus cap:12 focus:0
          IC [4a027f26660a4d23b6d6c3c370a9d624] program: frontend:dbus cap:1000012 focus:0
          IC [6961a4ec714b4cca96e461768c9d0477] program: frontend:dbus cap:12 focus:0
          IC [0dcd43a1a5e548c0a67c9d63b4d09e5d] program: frontend:dbus cap:1000012 focus:0
          IC [21d73a1453ae4950ac7daf3864bce8e7] program: frontend:dbus cap:1000012 focus:0
          IC [5870a51a3d9d41ab8a67a5fd8d27ae0c] program: frontend:wayland cap:72 focus:0
          IC [852991fbb1ca4bba9e02b0913d176a2e] program: frontend:dbus cap:1000012 focus:0
          IC [5d5ad78e666f4284a38cce57a2e88c63] program: frontend:dbus cap:12 focus:0
          IC [06212856e505445984ab1e127f12a5ce] program: frontend:dbus cap:1000012 focus:0
          IC [2f76e4b1dd3c4193a096b0433532615c] program:QQ frontend:wayland cap:72 focus:0
          IC [390e77eb028d4cb2b7a228b12519675a] program:firefox frontend:wayland cap:72 focus:0
          IC [f823f4a91f5744398c440866aa642c9f] program: frontend:dbus cap:1000052 focus:0
          IC [b76b8a02abac4881a2f3749eaed2e4ef] program: frontend:dbus cap:1000052 focus:0
          IC [0248a7fa1c354540b4048a1855dd84c0] program:firefox frontend:wayland cap:72 focus:0
          IC [7d49e8e45249439fac2b51d37ca76ed3] program: frontend:dbus cap:1000012 focus:0
          IC [967d46a4798e4ce5bf45ace53d4fffa4] program: frontend:dbus cap:1000012 focus:0
          IC [0121f695fb864bf1b0916fac5b6869e2] program: frontend:dbus cap:12 focus:0
          IC [8901f8d312144c32a990cb1b04d55cac] program: frontend:dbus cap:1000012 focus:0
          IC [52d246e703794274bc9ad45b76647aef] program: frontend:dbus cap:1000052 focus:0
          IC [860e546879dc40afade93d793edc3d1f] program:discord frontend:wayland cap:72 focus:0
          IC [12458926eda345008909ab7902557d67] program:org.kde.konsole frontend:wayland cap:72 focus:0
        Group [x11::1] has 8 InputContext(s)
          IC [44d30e7a72b447669e00fbf02a395ee3] program:firefox frontend:fcitx4 cap:1000012 focus:0
          IC [5d3f75d2ff694e3285faf888e575fb96] program:firefox frontend:fcitx4 cap:1000012 focus:0
          IC [71d35d7027384411a32ab37426550a40] program:firefox frontend:fcitx4 cap:1000012 focus:0
          IC [b33eaa3fcf6740798b21c465205aefc9] program:firefox frontend:fcitx4 cap:1000052 focus:0
          IC [0e92574c35bc497a813b73b817b41525] program:Discord frontend:fcitx4 cap:12 focus:0
          IC [6abe41c05a1d4f7e93b2caec1a36f891] program:firefox frontend:fcitx4 cap:1000012 focus:0
          IC [df3a6e9d475742e1ad672b721c6c1e02] program:firefox frontend:fcitx4 cap:1000052 focus:0
          IC [d5236b7c6aca4d0487085155e9620a30] program:qq frontend:fcitx4 cap:12 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    **Config GUI for qt not found.**

3.  Config GUI for kde:

    **`kcmshell5` not found.**

    **Cannot find a GUI config tool, please install one of `kcm-fcitx5`, or `fcitx5-config-qt`.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-gtk2-immodule-probing` not found.**

    **`fcitx5-gtk3-immodule-probing` not found.**

    **`fcitx5-gtk4-immodule-probing` not found.**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.42` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.42

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0`**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.42` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.42

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 3 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 28 enabled addons:

            Simplified and Traditional Chinese Translation 5.1.5
            Classic User Interface 5.1.10
            Clipboard 5.1.10
            Cloud Pinyin 5.1.5
            DBus 5.1.10
            DBus Frontend 5.1.10
            Emoji 5.1.10
            Fcitx4 Frontend 5.1.10
            Full width character 5.1.5
            IBus Frontend 5.1.10
            Input method selector 5.1.10
            Keyboard 5.1.10
            KDE Input Method Panel 5.1.10
            Status Notifier 5.1.10
            Notification 5.1.10
            Pinyin 5.1.5
            Extra Pinyin functionality 5.1.5
            Punctuation 5.1.5
            Quick Phrase 5.1.10
            Rime 5.1.8
            Spell 5.1.10
            Table 5.1.5
            Unicode 5.1.10
            DBus Virtual Keyboard 5.1.10
            Wayland 5.1.10
            Wayland Input method frontend 5.1.10
            XCB 5.1.10
            X Input Method Frontend 5.1.10

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/Gen0/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=rime

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=rime
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Tue Jun 11 16:35:53 CST 2024

2.  `/home/Gen0/.config/fcitx5/crash.log`:

    `/home/Gen0/.config/fcitx5/crash.log` not found.

**Comment by CoelacanthusHex** [comment]
这一行没更新
https://github.com/fcitx/fcitx5/blob/4ea4aa779685c19d3ee75492ba95879f18c361ad/data/fcitx5-configtool.sh#L134

**Comment by Gen0vo** [comment]
所以下一次推出更新的时候就会修了吗
没有其它问题了，可以Close了
