### ISSUE TITLE
freebsd 14.1 chromium can not use wubi-pinyin to input

### ISSUE THREAD

**Issue by runsys** [fcitx/fcitx5#1082]
### Summary

freebsd 14.1 chromium can not use wubi-pinyin to input

### Steps to Reproduce

pkg install chromium
chrome
any input edit can not input chinese.

### Expected Behavior

every input edit include text area can input chinese.

### Output of fcitx5-diagnose command

root@KPC:~ # fcitx5-diagnose
# System Info:
1.  `uname -a`:

        FreeBSD KPC 14.1-RELEASE FreeBSD 14.1-RELEASE releng/14.1-n267679-10e31f0946d8 GENERIC amd64

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME=FreeBSD
        VERSION="14.1-RELEASE"
        VERSION_ID="14.1"
        ID=freebsd
        ANSI_COLOR="0;31"
        PRETTY_NAME="FreeBSD 14.1-RELEASE"
        CPE_NAME="cpe:/o:freebsd:freebsd:14.1"
        HOME_URL="https://FreeBSD.org/"
        BUG_REPORT_URL="https://bugs.FreeBSD.org/"

5.  Desktop Environment:

    Desktop environment is `kde`.

6.  XDG SESSION TYPE:

        XDG_SESSION_TYPE=''

7.  Bash Version:

        BASH_VERSION='5.2.26(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)" };
                xkb_types     { include "complete"      };
                xkb_compat    { include "complete"      };
                xkb_symbols   { include "pc+us+inet(evdev)"     };
                xkb_geometry  { include "pc(pc104)"     };
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc104", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.UTF-8
            POSIX
            af_ZA.ISO8859-1
            af_ZA.ISO8859-15
            af_ZA.UTF-8
            am_ET.UTF-8
            ar_AE.UTF-8
            ar_EG.UTF-8
            ar_JO.UTF-8
            ar_MA.UTF-8
            ar_QA.UTF-8
            ar_SA.UTF-8
            be_BY.CP1131
            be_BY.CP1251
            be_BY.ISO8859-5
            be_BY.UTF-8
            bg_BG.CP1251
            bg_BG.UTF-8
            ca_AD.ISO8859-1
            ca_AD.ISO8859-15
            ca_AD.UTF-8
            ca_ES.ISO8859-1
            ca_ES.ISO8859-15
            ca_ES.UTF-8
            ca_FR.ISO8859-1
            ca_FR.ISO8859-15
            ca_FR.UTF-8
            ca_IT.ISO8859-1
            ca_IT.ISO8859-15
            ca_IT.UTF-8
            cs_CZ.ISO8859-2
            cs_CZ.UTF-8
            da_DK.ISO8859-1
            da_DK.ISO8859-15
            da_DK.UTF-8
            de_AT.ISO8859-1
            de_AT.ISO8859-15
            de_AT.UTF-8
            de_CH.ISO8859-1
            de_CH.ISO8859-15
            de_CH.UTF-8
            de_DE.ISO8859-1
            de_DE.ISO8859-15
            de_DE.UTF-8
            el_GR.ISO8859-7
            el_GR.UTF-8
            en_AU.ISO8859-1
            en_AU.ISO8859-15
            en_AU.US-ASCII
            en_AU.UTF-8
            en_CA.ISO8859-1
            en_CA.ISO8859-15
            en_CA.US-ASCII
            en_CA.UTF-8
            en_GB.ISO8859-1
            en_GB.ISO8859-15
            en_GB.US-ASCII
            en_GB.UTF-8
            en_HK.ISO8859-1
            en_HK.UTF-8
            en_IE.ISO8859-1
            en_IE.ISO8859-15
            en_IE.UTF-8
            en_NZ.ISO8859-1
            en_NZ.ISO8859-15
            en_NZ.US-ASCII
            en_NZ.UTF-8
            en_PH.UTF-8
            en_SG.ISO8859-1
            en_SG.UTF-8
            en_US.ISO8859-1
            en_US.ISO8859-15
            en_US.US-ASCII
            en_US.UTF-8
            en_ZA.ISO8859-1
            en_ZA.ISO8859-15
            en_ZA.US-ASCII
            en_ZA.UTF-8
            es_AR.ISO8859-1
            es_AR.UTF-8
            es_CR.UTF-8
            es_ES.ISO8859-1
            es_ES.ISO8859-15
            es_ES.UTF-8
            es_MX.ISO8859-1
            es_MX.UTF-8
            et_EE.ISO8859-1
            et_EE.ISO8859-15
            et_EE.UTF-8
            eu_ES.ISO8859-1
            eu_ES.ISO8859-15
            eu_ES.UTF-8
            fa_AF.UTF-8
            fa_IR.UTF-8
            fi_FI.ISO8859-1
            fi_FI.ISO8859-15
            fi_FI.UTF-8
            fr_BE.ISO8859-1
            fr_BE.ISO8859-15
            fr_BE.UTF-8
            fr_CA.ISO8859-1
            fr_CA.ISO8859-15
            fr_CA.UTF-8
            fr_CH.ISO8859-1
            fr_CH.ISO8859-15
            fr_CH.UTF-8
            fr_FR.ISO8859-1
            fr_FR.ISO8859-15
            fr_FR.UTF-8
            ga_IE.UTF-8
            he_IL.UTF-8
            hi_IN.ISCII-DEV
            hi_IN.UTF-8
            hr_HR.ISO8859-2
            hr_HR.UTF-8
            hu_HU.ISO8859-2
            hu_HU.UTF-8
            hy_AM.ARMSCII-8
            hy_AM.UTF-8
            is_IS.ISO8859-1
            is_IS.ISO8859-15
            is_IS.UTF-8
            it_CH.ISO8859-1
            it_CH.ISO8859-15
            it_CH.UTF-8
            it_IT.ISO8859-1
            it_IT.ISO8859-15
            it_IT.UTF-8
            ja_JP.SJIS
            ja_JP.UTF-8
            ja_JP.eucJP
            kk_KZ.UTF-8
            ko_KR.CP949
            ko_KR.UTF-8
            ko_KR.eucKR
            lt_LT.ISO8859-13
            lt_LT.UTF-8
            lv_LV.ISO8859-13
            lv_LV.UTF-8
            mn_MN.UTF-8
            nb_NO.ISO8859-1
            nb_NO.ISO8859-15
            nb_NO.UTF-8
            nl_BE.ISO8859-1
            nl_BE.ISO8859-15
            nl_BE.UTF-8
            nl_NL.ISO8859-1
            nl_NL.ISO8859-15
            nl_NL.UTF-8
            nn_NO.ISO8859-1
            nn_NO.ISO8859-15
            nn_NO.UTF-8
            pl_PL.ISO8859-2
            pl_PL.UTF-8
            pt_BR.ISO8859-1
            pt_BR.UTF-8
            pt_PT.ISO8859-1
            pt_PT.ISO8859-15
            pt_PT.UTF-8
            ro_RO.ISO8859-2
            ro_RO.UTF-8
            ru_RU.CP1251
            ru_RU.CP866
            ru_RU.ISO8859-5
            ru_RU.KOI8-R
            ru_RU.UTF-8
            se_FI.UTF-8
            se_NO.UTF-8
            sk_SK.ISO8859-2
            sk_SK.UTF-8
            sl_SI.ISO8859-2
            sl_SI.UTF-8
            sr_RS.ISO8859-2
            sr_RS.ISO8859-5
            sr_RS.UTF-8
            sr_RS.UTF-8@latin
            sv_FI.ISO8859-1
            sv_FI.ISO8859-15
            sv_FI.UTF-8
            sv_SE.ISO8859-1
            sv_SE.ISO8859-15
            sv_SE.UTF-8
            tr_TR.ISO8859-9
            tr_TR.UTF-8
            uk_UA.CP1251
            uk_UA.ISO8859-5
            uk_UA.KOI8-U
            uk_UA.UTF-8
            zh_CN.GB18030
            zh_CN.GB2312
            zh_CN.GBK
            zh_CN.UTF-8
            zh_CN.eucCN
            zh_HK.UTF-8
            zh_TW.Big5
            zh_TW.UTF-8

    2.  Current locale:

            LANG=C.UTF-8
            LC_CTYPE="C.UTF-8"
            LC_COLLATE="C.UTF-8"
            LC_TIME="C.UTF-8"
            LC_NUMERIC="C.UTF-8"
            LC_MONETARY="C.UTF-8"
            LC_MESSAGES="C.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /root

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/root/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/root/.config/fcitx5`).

5.  Current user:

    The script is run as root (0).

    1.  `sudo` Environment Variables:

        SUDO_COMMAND is not set.

        SUDO_USER is not set.

        SUDO_UID is not set.

        SUDO_GID is not set.

    2.  Running as root:

        **You are probably logging in as `root` or using `sudo` to run this script. This either means you have security problems or the result of this script may not be accurate. See [Why is it bad to run as root](https://www.google.com/search?q=Why+is+it+bad+to+run+as+root) or [sudo environment variables](https://www.google.com/search?q=sudo+environment+variables) for more information.**

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/local/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.23`

3.  process:

    Found 1 fcitx5 process:

        36901 fcitx5

4.  `fcitx5-remote`:
/usr/local/bin/fcitx5-diagnose: line 916: 96405 Abort trap              (core dumped) fcitx5-remote &> /dev/null

    **Cannot connect to fcitx5 correctly.**

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.29`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `36901`.

    Debug information from dbus:

           Group [x11::0] has 18 InputContext(s)
          IC [5e97d31eb5964e628a3a6d93e8f7f0f0] program:konsole frontend:dbus cap:6000820872 focus:1
          IC [7c62a870d69e47ae8b10fda86d4a304d] program:konsole frontend:dbus cap:6000820872 focus:0
          IC [a89fecbc3d6746ee88bc15c5bc5a17ee] program:kwin_x11 frontend:dbus cap:16000800072 focus:0
          IC [3eec2822537a4a7f85f371c20fd698d0] program:konsole frontend:dbus cap:6000820872 focus:0
          IC [7aed2813582044a892c339390cc2bf2f] program:HttpsFolderSyncMon frontend:dbus cap:16000800072 focus:0
          IC [2c971b8d787a475eae41183ad7c3bcd5] program:liteide frontend:dbus cap:16000800072 focus:0
          IC [22fdb4983f89400f8816d861da06e5e0] program:dolphin frontend:dbus cap:16000800072 focus:0
          IC [33f632a502794ba194da8a754f7d4ea3] program:kate frontend:dbus cap:16000800072 focus:0
          IC [27b5c863a557419f9ef9654dd9dd8f6c] program:firefox frontend:dbus cap:6000000032 focus:0
          IC [2318711451e143189ed95e278c8e28f9] program:firefox frontend:dbus cap:6000000032 focus:0
          IC [ca4528d280c64ba19d6cab8239b18f33] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [6ce0c487734d40609604fb5f0aab6293] program:kate frontend:dbus cap:6000800072 focus:0
          IC [48208ce1a3e94269a393480852e8b7db] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [bbcace86045445d0a766faf6e7e27ea8] program:liteide frontend:dbus cap:16000800072 focus:0
          IC [0a643b5e8f6145d6ab85a2523cbd658c] program:firefox frontend:dbus cap:6000000072 focus:0
          IC [3bdac1eb4c1c4b8fafcb2431a4ef871e] program:liteide frontend:dbus cap:6800800072 focus:0
          IC [c662b1d202b548bf9554c9e72eb32b92] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [527c4d4dc8774abebbcd56d2b8320021] program:firefox frontend:dbus cap:6000000032 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/local/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/local/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    Found fcitx5 kcm module.

        kcm_fcitx5                     - Configure Input Method

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS is not set**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 im module for qt5: `/usr/local/lib/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/local/lib/qt5/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 im module for qt6: `/usr/local/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/local/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/local/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/local/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/local/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/local/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/local/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.42` at `/usr/local/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/local/bin/gtk-query-immodules-3.0 from gtk+-3.24.42

        Found fcitx5 im modules for gtk `3.24.42`.

            "/usr/local/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/local/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/local/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/local/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/local/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/local/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/local/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/local/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.42` at `/usr/local/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/local/bin/gtk-query-immodules-3.0 from gtk+-3.24.42

        Found fcitx5 im modules for gtk `3.24.42`.

            "/usr/local/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/local/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/local/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/local/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 28 enabled addons:

            Simplified and Traditional Chinese Translation 5.0.17
            Classic User Interface 5.0.23
            Clipboard 5.0.23
            Cloud Pinyin 5.0.17
            DBus 5.0.23
            DBus Frontend 5.0.23
            Emoji 5.0.23
            Fcitx4 Frontend 5.0.23
            Full width character 5.0.17
            IBus Frontend 5.0.23
            Lua IME API 5.0.10
            Input method selector 5.0.23
            Keyboard 5.0.23
            KDE Input Method Panel 5.0.23
            Lua Addon Loader 5.0.10
            Status Notifier 5.0.23
            Notification 5.0.23
            Pinyin 5.0.17
            Extra Pinyin functionality 5.0.17
            Punctuation 5.0.17
            Quick Phrase 5.0.23
            Spell 5.0.23
            Table 5.0.17
            Unicode 5.0.23
            Wayland 5.0.23
            Wayland Input method frontend 5.0.23
            XCB 5.0.23
            X Input Method Frontend 5.0.23

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/root/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=wbpy

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=wbpy
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Wed Jul  3 17:14:21 CST 2024

2.  `/root/.config/fcitx5/crash.log`:

    `/root/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**
root@KPC:~ #

**Comment by wengxt** [comment]
Check https://fcitx-im.org/wiki/FAQ#Chromium_or_any_other_chromium_based_browser_.28E.g._Microsoft_Edge.29
