### ISSUE TITLE
在Falkon浏览器输入框，输入法会被关键词联想影响导致无法输入

### ISSUE THREAD

**Issue by fxzxmic** [fcitx/fcitx5#1083]
### Summary

在Falkon浏览器的地址栏和搜索栏，只有输入框内无文本时才可以使用输入法，内部有文本的话，输入法会被关键词联想影响而导致无法输入。

### Steps to Reproduce

1. 打开Falkon浏览器
2. 在地址栏或者搜索栏输入一些文本
3. 浏览器显示出关键词联想后，就无法使用输入法了

### Expected Behavior

在显示关键词联想的情况下依旧可以使用输入法输入。

### Output of fcitx5-diagnose command

# System Info:
1.  `uname -a`:

**

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME="openSUSE Tumbleweed-Slowroll"
        # VERSION="20240605"
        ID="opensuse-slowroll"
        ID_LIKE="opensuse suse"
        VERSION_ID="20240605"
        PRETTY_NAME="openSUSE Tumbleweed-Slowroll"
        ANSI_COLOR="0;32"
        # CPE 2.3 format, boo#1217921
        CPE_NAME="cpe:2.3:o:opensuse:slowroll:20240605:*:*:*:*:*:*:*"
        #CPE 2.2 format
        #CPE_NAME="cpe:/o:opensuse:slowroll:20240605"
        BUG_REPORT_URL="https://bugzilla.opensuse.org"
        SUPPORT_URL="https://bugs.opensuse.org"
        HOME_URL="https://www.opensuse.org"
        DOCUMENTATION_URL="https://en.opensuse.org/openSUSE:Slowroll"
        LOGO="distributor-logo-Slowroll"

5.  Desktop Environment:

    Desktop environment is `kde`.

6.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

7.  Bash Version:

        BASH_VERSION='5.2.26(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY='wayland-0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)" };
                xkb_types     { include "complete"      };
                xkb_compat    { include "complete"      };
                xkb_symbols   { include "pc+us+inet(evdev)"     };
                xkb_geometry  { include "pc(pc105)"     };
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            aa_DJ
            aa_DJ.utf8
            aa_ER
            aa_ET
            af_ZA
            af_ZA.utf8
            agr_PE
            ak_GH
            am_ET
            an_ES
            an_ES.utf8
            anp_IN
            ar_AE
            ar_AE.utf8
            ar_BH
            ar_BH.utf8
            ar_DZ
            ar_DZ.utf8
            ar_EG
            ar_EG.utf8
            ar_IN
            ar_IQ
            ar_IQ.utf8
            ar_JO
            ar_JO.utf8
            ar_KW
            ar_KW.utf8
            ar_LB
            ar_LB.utf8
            ar_LY
            ar_LY.utf8
            ar_MA
            ar_MA.utf8
            ar_OM
            ar_OM.utf8
            ar_QA
            ar_QA.utf8
            ar_SA
            ar_SA.utf8
            ar_SD
            ar_SD.utf8
            ar_SS
            ar_SY
            ar_SY.utf8
            ar_TN
            ar_TN.utf8
            ar_YE
            ar_YE.utf8
            as_IN
            ast_ES
            ast_ES.utf8
            ayc_PE
            az_AZ
            az_IR
            be_BY
            be_BY.utf8
            be_BY@latin
            bem_ZM
            ber_DZ
            ber_MA
            bg_BG
            bg_BG.utf8
            bhb_IN.utf8
            bho_IN
            bho_NP
            bi_VU
            bn_BD
            bn_IN
            bo_CN
            bo_IN
            br_FR
            br_FR.utf8
            br_FR@euro
            brx_IN
            bs_BA
            bs_BA.utf8
            byn_ER
            ca_AD
            ca_AD.utf8
            ca_ES
            ca_ES.utf8
            ca_ES@euro
            ca_ES@valencia
            ca_FR
            ca_FR.utf8
            ca_IT
            ca_IT.utf8
            ce_RU
            chr_US
            ckb_IQ
            cmn_TW
            crh_RU
            crh_UA
            cs_CZ
            cs_CZ.utf8
            csb_PL
            cv_RU
            cy_GB
            cy_GB.utf8
            da_DK
            da_DK.utf8
            de_AT
            de_AT.utf8
            de_AT@euro
            de_BE
            de_BE.utf8
            de_BE@euro
            de_CH
            de_CH.utf8
            de_DE
            de_DE.utf8
            de_DE@euro
            de_IT
            de_IT.utf8
            de_LI.utf8
            de_LU
            de_LU.utf8
            de_LU@euro
            doi_IN
            dsb_DE
            dv_MV
            dz_BT
            el_CY
            el_CY.utf8
            el_GR
            el_GR.utf8
            el_GR@euro
            en_AG
            en_AU
            en_AU.utf8
            en_BW
            en_BW.utf8
            en_CA
            en_CA.utf8
            en_DK
            en_DK.utf8
            en_GB
            en_GB.iso885915
            en_GB.utf8
            en_HK
            en_HK.utf8
            en_IE
            en_IE.utf8
            en_IE@euro
            en_IL
            en_IN
            en_NG
            en_NZ
            en_NZ.utf8
            en_PH
            en_PH.utf8
            en_SC.utf8
            en_SG
            en_SG.utf8
            en_US
            en_US.iso885915
            en_US.utf8
            en_ZA
            en_ZA.utf8
            en_ZM
            en_ZW
            en_ZW.utf8
            eo
            es_AR
            es_AR.utf8
            es_BO
            es_BO.utf8
            es_CL
            es_CL.utf8
            es_CO
            es_CO.utf8
            es_CR
            es_CR.utf8
            es_CU
            es_DO
            es_DO.utf8
            es_EC
            es_EC.utf8
            es_ES
            es_ES.utf8
            es_ES@euro
            es_GT
            es_GT.utf8
            es_HN
            es_HN.utf8
            es_MX
            es_MX.utf8
            es_NI
            es_NI.utf8
            es_PA
            es_PA.utf8
            es_PE
            es_PE.utf8
            es_PR
            es_PR.utf8
            es_PY
            es_PY.utf8
            es_SV
            es_SV.utf8
            es_US
            es_US.utf8
            es_UY
            es_UY.utf8
            es_VE
            es_VE.utf8
            et_EE
            et_EE.iso885915
            et_EE.utf8
            eu_ES
            eu_ES.utf8
            eu_ES@euro
            fa_IR
            ff_SN
            fi_FI
            fi_FI.utf8
            fi_FI@euro
            fil_PH
            fo_FO
            fo_FO.utf8
            fr_BE
            fr_BE.utf8
            fr_BE@euro
            fr_CA
            fr_CA.utf8
            fr_CH
            fr_CH.utf8
            fr_FR
            fr_FR.utf8
            fr_FR@euro
            fr_LU
            fr_LU.utf8
            fr_LU@euro
            fur_IT
            fy_DE
            fy_NL
            ga_IE
            ga_IE.utf8
            ga_IE@euro
            gbm_IN
            gd_GB
            gd_GB.utf8
            gez_ER
            gez_ER@abegede
            gez_ET
            gez_ET@abegede
            gl_ES
            gl_ES.utf8
            gl_ES@euro
            gu_IN
            gv_GB
            gv_GB.utf8
            ha_NG
            hak_TW
            he_IL
            he_IL.utf8
            hi_IN
            hif_FJ
            hne_IN
            hr_HR
            hr_HR.utf8
            hsb_DE
            hsb_DE.utf8
            ht_HT
            hu_HU
            hu_HU.utf8
            hy_AM
            hy_AM.armscii8
            ia_FR
            id_ID
            id_ID.utf8
            ig_NG
            ik_CA
            is_IS
            is_IS.utf8
            it_CH
            it_CH.utf8
            it_IT
            it_IT.utf8
            it_IT@euro
            iu_CA
            ja_JP.eucjp
            ja_JP.shiftjisx0213
            ja_JP.sjis
            ja_JP.utf8
            ka_GE
            ka_GE.utf8
            kab_DZ
            kk_KZ
            kk_KZ.utf8
            kl_GL
            kl_GL.utf8
            km_KH
            kn_IN
            ko_KR.euckr
            ko_KR.utf8
            kok_IN
            ks_IN
            ks_IN@devanagari
            ku_TR
            ku_TR.utf8
            kv_RU
            kw_GB
            kw_GB.utf8
            ky_KG
            lb_LU
            lg_UG
            lg_UG.utf8
            li_BE
            li_NL
            lij_IT
            ln_CD
            lo_LA
            lt_LT
            lt_LT.utf8
            lv_LV
            lv_LV.utf8
            lzh_TW
            mag_IN
            mai_IN
            mai_NP
            mfe_MU
            mg_MG
            mg_MG.utf8
            mhr_RU
            mi_NZ
            mi_NZ.utf8
            miq_NI
            mjw_IN
            mk_MK
            mk_MK.utf8
            ml_IN
            mn_MN
            mni_IN
            mnw_MM
            mr_IN
            ms_MY
            ms_MY.utf8
            mt_MT
            mt_MT.utf8
            my_MM
            nan_TW
            nan_TW@latin
            nb_NO
            nb_NO.utf8
            nds_DE
            nds_NL
            ne_NP
            nhn_MX
            niu_NU
            niu_NZ
            nl_AW
            nl_BE
            nl_BE.utf8
            nl_BE@euro
            nl_NL
            nl_NL.utf8
            nl_NL@euro
            nn_NO
            nn_NO.utf8
            no_NO
            no_NO.utf8
            nr_ZA
            nso_ZA
            oc_FR
            oc_FR.utf8
            om_ET
            om_KE
            om_KE.utf8
            or_IN
            os_RU
            pa_IN
            pa_PK
            pap_AW
            pap_CW
            pl_PL
            pl_PL.utf8
            ps_AF
            pt_BR
            pt_BR.utf8
            pt_PT
            pt_PT.utf8
            pt_PT@euro
            quz_PE
            raj_IN
            rif_MA
            ro_RO
            ro_RO.utf8
            ru_RU
            ru_RU.koi8r
            ru_RU.utf8
            ru_UA
            ru_UA.utf8
            rw_RW
            sa_IN
            sah_RU
            sat_IN
            sc_IT
            sd_IN
            sd_IN@devanagari
            se_NO
            sgs_LT
            shn_MM
            shs_CA
            si_LK
            sid_ET
            sk_SK
            sk_SK.utf8
            sl_SI
            sl_SI.utf8
            sm_WS
            so_DJ
            so_DJ.utf8
            so_ET
            so_KE
            so_KE.utf8
            so_SO
            so_SO.utf8
            sq_AL
            sq_AL.utf8
            sq_MK
            sr_ME
            sr_RS
            sr_RS@latin
            ss_ZA
            ssy_ER
            st_ZA
            st_ZA.utf8
            su_ID
            sv_FI
            sv_FI.utf8
            sv_FI@euro
            sv_SE
            sv_SE.utf8
            sw_KE
            sw_TZ
            syr
            szl_PL
            ta_IN
            ta_LK
            tcy_IN.utf8
            te_IN
            tg_TJ
            tg_TJ.utf8
            th_TH
            th_TH.utf8
            the_NP
            ti_ER
            ti_ET
            tig_ER
            tk_TM
            tl_PH
            tl_PH.utf8
            tn_ZA
            to_TO
            tok
            tpi_PG
            tr_CY
            tr_CY.utf8
            tr_TR
            tr_TR.utf8
            ts_ZA
            tt_RU
            tt_RU@iqtelif
            ug_CN
            uk_UA
            uk_UA.utf8
            unm_US
            ur_IN
            ur_PK
            uz_UZ
            uz_UZ.utf8
            uz_UZ@cyrillic
            ve_ZA
            vi_VN
            wa_BE
            wa_BE.utf8
            wa_BE@euro
            wae_CH
            wal_ET
            wo_SN
            xh_ZA
            xh_ZA.utf8
            yi_US
            yi_US.utf8
            yo_NG
            yue_HK
            yuw_PG
            zgh_MA
            zh_CN
            zh_CN.gb18030
            zh_CN.gbk
            zh_CN.utf8
            zh_HK
            zh_HK.utf8
            zh_SG
            zh_SG.gbk
            zh_SG.utf8
            zh_TW
            zh_TW.euctw
            zh_TW.utf8
            zu_ZA
            zu_ZA.utf8

    2.  Current locale:

            LANG=zh_CN.UTF-8
            LC_CTYPE="C"
            LC_NUMERIC="C"
            LC_TIME="C"
            LC_COLLATE="C"
            LC_MONETARY="C"
            LC_MESSAGES="C"
            LC_PAPER="C"
            LC_NAME="C"
            LC_ADDRESS="C"
            LC_TELEPHONE="C"
            LC_MEASUREMENT="C"
            LC_IDENTIFICATION="C"
            LC_ALL=C

4.  Directories:

    1.  Home:

            /home/dev

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/dev/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/dev/.config/fcitx5`).

5.  Current user:

    The script is run as dev (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.9`

3.  process:

    Found 3 fcitx5 processes:

           1012 fcitx5-wayland-
           1015 fcitx5
           1027 fcitx5-plasma-t

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.15`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `1015`.

    Debug information from dbus:

           Group [wayland:] has 4 InputContext(s)
          IC [9b773033930c4b628dec32453a9a7dbd] program:org.kde.konsole frontend:wayland cap:72 focus:1
          IC [d03bf2fc4dbe43b297517994c48310f4] program:org.kde.discover frontend:wayland cap:80072 focus:0
          IC [037fd3f3beb84081aa5ea9296e78f432] program:org.kde.falkon frontend:wayland cap:80072 focus:0
          IC [b5bdb08f523e4f848a4f63f42dc40c39] program: frontend:wayland cap:72 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    **Config GUI for qt not found.**

3.  Config GUI for kde:

    **`kcmshell5` not found.**

    **Cannot find a GUI config tool, please install one of `kcm-fcitx5`, or `fcitx5-config-qt`.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    **Cannot find xim_server on root window.**

3.  XIM encoding:

    **Your LC_CTYPE is set to C whose encoding is not UTF-8. You may have trouble committing strings using XIM.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt5 built-in Wayland im module if your compositor fully supports text-input protocol used by qt5.**

    **`fcitx5-qt5-immodule-probing` not found.**

3.  qt6 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt6 built-in Wayland im module if your compositor fully supports text-input protocol used by qt6.**

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt6: `/usr/lib64/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`.
    Found fcitx5 qt6 module: `/usr/lib64/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**
    **Cannot find fcitx5 input method module for Qt5.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

    **It is OK to use gtk built-in Wayland im module if your compositor fully supports text-input protocol used by gtk.**

    **`fcitx5-gtk2-immodule-probing` not found.**

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=wayland

    **`fcitx5-gtk4-immodule-probing` not found.**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.42` at `/usr/bin/gtk-query-immodules-3.0-64`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0-64 from gtk+-3.24.42

        Found fcitx5 im modules for gtk `3.24.42`.

            "/usr/lib64/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.42` at `/usr/lib64/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0-64 from gtk+-3.24.42

        Found fcitx5 im modules for gtk `3.24.42`.

            "/usr/lib64/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 17 enabled addons:

            Simplified and Traditional Chinese Translation 5.1.5
            Classic User Interface 5.1.9
            Cloud Pinyin 5.1.5
            DBus 5.1.9
            Full width character 5.1.5
            Keyboard 5.1.9
            KDE Input Method Panel 5.1.9
            Status Notifier 5.1.9
            Notification 5.1.9
            Pinyin 5.1.5
            Extra Pinyin functionality 5.1.5
            Punctuation 5.1.5
            Quick Phrase 5.1.9
            Spell 5.1.9
            DBus Virtual Keyboard 5.1.9
            Wayland 5.1.9
            Wayland Input method frontend 5.1.9

    2.  Found 10 disabled addons:

            Clipboard 5.1.9
            DBus Frontend 5.1.9
            Emoji 5.1.9
            Fcitx4 Frontend 5.1.9
            IBus Frontend 5.1.9
            Input method selector 5.1.9
            Table 5.1.5
            Unicode 5.1.9
            XCB 5.1.9
            X Input Method Frontend 5.1.9

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/dev/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=默认
        # Layout
        Default Layout=cn
        # Default Input Method
        DefaultIM=pinyin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-cn
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=pinyin
        # Layout
        Layout=

        [GroupOrder]
        0=默认

# Log:
1.  `date`:

        Thu Jul  4 20:05:37 CST 2024

2.  `/home/dev/.config/fcitx5/crash.log`:

    `/home/dev/.config/fcitx5/crash.log` not found.

**Comment by wengxt** [comment]
请汇报 bug 给 falkon，另外 workaround 你可以按 esc 关掉联想再继续输入。
