### ISSUE TITLE
ubuntu20.04系统下fcitx5输入法无法输入中文

### ISSUE THREAD

**Issue by xiangdaos** [fcitx/fcitx5#1092]
### Summary

ubuntu20.04系统下fcitx5输入法无法输入中文，只能输入英文。fcitx的输入法配置文件是在~/.config/fcitx/config，但是我安装fcitx5后，在~/.config/fcitx5/路径下没有这个config文件，只有这些文件：
fcitx5
├── conf
│   └── cached_layouts
└── profile

### Steps to Reproduce

在ubuntu20.04系统下，通过sudo apt install fcitx5 fcitx5-pinyin fcitx5-chinese-addons  fcitx5-chinese-addons-bin 
fcitx5-chinese-addons-data

### Expected Behavior

期望能正常输入中文

### Output of fcitx5-diagnose command

没有fcitx5-diagnose命令，只有fcitx-diagnose命令

**Comment by hantengc** [comment]
@xiangdaos 安装fcitx5 fcitx5-pinyin之后终端执行fcitx5有什么输出？ 看看当前是不是还有fcitx的进程存在

**Comment by CSUDaXiang** [comment]
@hantengc 当前没有fcitx进程在哦，只有fcitx5进程：
运行fcitx5输出如下：
caayun@0000000g-dpu1kah6of:~/.config/fcitx5$ fcitx5 
I instance.cpp:919] Override Enabled Addons: {}
I instance.cpp:920] Override Disabled Addons: {}
I addonmanager.cpp:177] Loaded addon wayland
I addonmanager.cpp:177] Loaded addon unicode
I addonmanager.cpp:177] Loaded addon xcb
I addonmanager.cpp:177] Loaded addon quickphrase
I addonmanager.cpp:177] Loaded addon punctuation
I isocodes.cpp:42] 639-3
I isocodes.cpp:42] 3166-1
I addonmanager.cpp:177] Loaded addon keyboard
I addonmanager.cpp:177] Loaded addon clipboard
I addonmanager.cpp:177] Loaded addon waylandim
I addonmanager.cpp:177] Loaded addon dbus
I addonmanager.cpp:177] Loaded addon ibusfrontend
execl: 没有那个文件或目录
E xim.cpp:99] Failed to open xim, retrying.
I addonmanager.cpp:177] Loaded addon xim
I addonmanager.cpp:177] Loaded addon dbusfrontend
I inputmethodmanager.cpp:117] Found 683 input method(s) in addon keyboard
I addonmanager.cpp:177] Loaded addon kimpanel
I addonmanager.cpp:177] Loaded addon classicui
I addonmanager.cpp:177] Loaded addon notificationitem
I kimpanel.cpp:101] Kimpanel new owner

运行配置命令报没有config文件：
fcitx5-configtool 
gio: file:///home/caayun/.config/fcitx5/config: 获取文件“/home/caayun/.config/fcitx5/config”的信息时出错：没有那个文件或目录

**Comment by wengxt** [comment]
20.04的版本太老了，甚至在fcitx5的第一个正式版之前
不推荐在20.04用apt安装源里的fcitx5

你的问题大概是没有在配置里添加一个中文输入法



升22.04吧……

**Comment by CSUDaXiang** [comment]
> 20.04的版本太老了，甚至在fcitx5的第一个正式版之前 不推荐在20.04用apt安装源里的fcitx5
> 
> 你的问题大概是没有在配置里添加一个中文输入法
> 
> 升22.04吧……

请问fcitx输入法在ubunt的dash软件管理中无法输入中文进行搜索，这个问题有遇到过吗，用ibus是可以输入中文的。

**Comment by wengxt** [comment]
@CSUDaXiang 答案就是用新版本的支持模拟ibus的fcitx5

**Comment by CSUDaXiang** [comment]
@wengxt 你好，咨询一下，在ubuntu20.04系统中，如果要安装fcitx5输入法，有没有推荐的版本，目前我安装的是5.0.17版本，初步验证了一下基本功能正常，想咨询一下是否能升级到稍微比较新的版本（操作系统暂时没办法升级至22.04系统）。
是否有哪个版本开始一定是要在ubuntu22.04的系统上才能安装运行？

**Comment by wengxt** [comment]
> @wengxt 你好，咨询一下，在ubuntu20.04系统中，如果要安装fcitx5输入法，有没有推荐的版本，目前我安装的是5.0.17版本，初步验证了一下基本功能正常，想咨询一下是否能升级到稍微比较新的版本（操作系统暂时没办法升级至22.04系统）。 是否有哪个版本开始一定是要在ubuntu22.04的系统上才能安装运行？

ci一直跑在20.04上，最新版本也可以用

你还可以装flatpak版不用编译
