### ISSUE TITLE
Doesn't work in Plasma 6

### ISSUE THREAD

**Issue by aaronliu0130** [fcitx/fcitx5#1094]
### Summary

I tried to get this working in Plasma 6. After the steps to reproduce, I don't see anything special save the little box that tells you you've switched to the Chinese input method.

Something interesting is that the configuration dialog fails to open through the procedure outlined in the second paragraph of the steps to reproduce. I had to manually run `fcitx5-config-qt` to add the Chinese input method. A maybe-relevant line from the diagnostics is the following:
```md
3.  Config GUI for kde:

**`kcmshell5` not found.**
```
Considering I use Plasma 6, it should be searching for `kcmshell6`.

### Steps to Reproduce

adding the Chinese addon and input method, opening kwrite, switching to the Chinese input method, typing stuff

install kcitx5-configtool and right click the keyboard icon in the taskbar before clicking configure.

### Expected Behavior

works

### Output of fcitx5-diagnose command

# System Info:
1.  `uname -a`:

Linux bestbuy 6.9.8-zen1-1.1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 08 Jul 2024 01:09:39 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

LSB Version:    n/a
Distributor ID: EndeavourOS
Description:    EndeavourOS Linux
Release:        rolling
Codename:       rolling

3.  `lsb_release -d`:

Description:    EndeavourOS Linux

4.  `/etc/lsb-release`:

DISTRIB_ID="EndeavourOS"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME="rolling"

5.  `/etc/os-release`:

NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

6.  Desktop Environment:

Desktop environment is `kde`.

7.  XDG SESSION TYPE:

XDG_SESSION_TYPE='wayland'

8.  Bash Version:

BASH_VERSION='5.2.26(1)-release'

# Environment:
1.  DISPLAY:

DISPLAY=':1'

WAYLAND_DISPLAY='wayland-0'

2.  Keyboard Layout:

1.  `setxkbmap`:

WARNING: Running setxkbmap against an Xwayland server
xkb_keymap {
xkb_keycodes  { include "evdev+aliases(qwerty)" };
xkb_types     { include "complete"      };
xkb_compat    { include "complete+mod_led(compose)"     };
xkb_symbols   { include "pc+us+inet(evdev)+compose(ralt)"       };
xkb_geometry  { include "pc(pc105)"     };
};

2.  `xprop`:

_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", "compose:ralt,mod_led:compose"

3.  Locale:

1.  All locales:

C
C.utf8
en_US.utf8
POSIX

2.  Current locale:

LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

4.  Directories:

1.  Home:

/home/aliu

2.  `${XDG_CONFIG_HOME}`:

Environment variable `XDG_CONFIG_HOME` is not set.

Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/aliu/.config`).

3.  Fcitx5 Settings Directory:

Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/aliu/.config/fcitx5`).

5.  Current user:

The script is run as aliu (1000).

# Fcitx State:
1.  executable:

Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

Fcitx version: `5.1.10`

3.  process:

Found 1 fcitx5 process:

47392 fcitx5

4.  `fcitx5-remote`:

`fcitx5-remote` works properly.

5.  DBus interface:

Using `dbus-send` to check dbus.

Owner of DBus name `org.fcitx.Fcitx5` is `:1.241`.

PID of DBus name `org.fcitx.Fcitx5` owner is `47392`.

Debug information from dbus:

Group [wayland:] has 6 InputContext(s)
IC [89e77f7cbb0440bdb0052e775e164ada] program:org.kde.yakuake frontend:wayland cap:72 focus:1
IC [039f33315e3f4f099a094b4f91adf12d] program:waydroid.com.maimemo.android.momo frontend:wayland cap:d0072 focus:0
IC [97f4e3569b3441fea2bf56f5a727ce34] program:org.kde.kwrite frontend:wayland cap:d0072 focus:0
IC [cb2158c483db41418ae2cd1782068632] program:systemsettings frontend:wayland cap:72 focus:0
IC [5363187ba5e74574be4219c383a9daf9] program:waterfox-g frontend:wayland cap:72 focus:0
IC [4d4d9117e80b4cd1bc5e9eccee6bd6bd] program: frontend:wayland cap:72 focus:0
Group [x11::1] has 0 InputContext(s)
Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

**`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

**XMODIFIERS is not set**

**Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

**Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

**`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

**Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

**It is OK to use qt5 built-in Wayland im module if your compositor fully supports text-input protocol used by qt5.**

Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

QT_QPA_PLATFORM=wayland
QT_IM_MODULE=
IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

3.  qt6 - `${QT_IM_MODULE}`:

**Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

**It is OK to use qt6 built-in Wayland im module if your compositor fully supports text-input protocol used by qt6.**

Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

QT_QPA_PLATFORM=wayland
QT_IM_MODULE=
IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

4.  Qt IM module files:

Found unknown fcitx qt module: `/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`.
Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not useany Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
**Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

**Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

**It is OK to use gtk built-in Wayland im module if your compositor fully supports text-input protocol used by gtk.**

**`fcitx5-gtk2-immodule-probing` not found.**

**`fcitx5-gtk3-immodule-probing` not found.**

**`fcitx5-gtk4-immodule-probing` not found.**

2.  `gtk-query-immodules`:

1.  gtk 2:

**Cannot find `gtk-query-immodules` for gtk 2**

**Cannot find fcitx5 im module for gtk 2.**

2.  gtk 3:

Found `gtk-query-immodules` for gtk `3.24.43` at `/usr/bin/gtk-query-immodules-3.0`.
Version Line:

# Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

**Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0`**

**Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

1.  gtk 2:

**Cannot find immodules cache for gtk 2**

**Cannot find fcitx5 im module for gtk 2 in cache.**

2.  gtk 3:

Found immodules cache for gtk `3.24.43` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
Version Line:

# Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

**Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`**

**Cannot find fcitx5 im module for gtk 3 in cache.**

4.  Gtk IM module files:

1.  gtk 2:

All found Gtk 2 immodule files exist.

2.  gtk 3:

All found Gtk 3 immodule files exist.

3.  gtk 4:

All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

1.  Found 27 enabled addons:

Simplified and Traditional Chinese Translation 5.1.6
Classic User Interface 5.1.10
Clipboard 5.1.10
Cloud Pinyin 5.1.6
DBus 5.1.10
DBus Frontend 5.1.10
Emoji 5.1.10
Fcitx4 Frontend 5.1.10
Full width character 5.1.6
IBus Frontend 5.1.10
Input method selector 5.1.10
Keyboard 5.1.10
KDE Input Method Panel 5.1.10
Status Notifier 5.1.10
Notification 5.1.10
Pinyin 5.1.6
Extra Pinyin functionality 5.1.6
Punctuation 5.1.6
Quick Phrase 5.1.10
Spell 5.1.10
Table 5.1.6
Unicode 5.1.10
DBus Virtual Keyboard 5.1.10
Wayland 5.1.10
Wayland Input method frontend 5.1.10
XCB 5.1.10
X Input Method Frontend 5.1.10

2.  Found 0 disabled addons:

3.  Addon Libraries:

All libraries for all addons are found.

4.  User Interface:

Found 3 enabled user interface addons:

Classic User Interface
KDE Input Method Panel
DBus Virtual Keyboard

## Input Methods:
1.  `/home/aliu/.config/fcitx5/profile`:

[Groups/0]
# Group Name
Name=Default
# Layout
Default Layout=us
# Default Input Method
DefaultIM=keyboard-cn

[Groups/0/Items/0]
# Name
Name=keyboard-us
# Layout
Layout=

[Groups/0/Items/1]
# Name
Name=keyboard-cn
# Layout
Layout=

[GroupOrder]
0=Default

# Log:
1.  `date`:

Thu Jul 11 11:04:08 PM CDT 2024

2.  `/home/aliu/.config/fcitx5/crash.log`:

`/home/aliu/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by wengxt** [comment]
fcitx5 doesn't use kcmshell anymore.

It launches with system settings. Do you have systemsettings installed? fcitx5-configtool works fine on my system

fcitx5-diagnose itself might be wrong, but shouldn't affect fcitx5-configtool.

**Comment by aaronliu0130** [comment]
Okay, it didn't work 2 days ago, but it works today. Huh.

**Comment by aaronliu0130** [comment]
I still have some problems. Despite fcitx5-chinese-addons being installed, typing anywhere in Chinese mode still does nothing, including Wayland applications (I'm in Wayland mode). Enabling hinting by default somehow enables that for every mode instead of just Chinese and only works in English.

**Comment by wengxt** [comment]
@aaronliu0130 there's a qml cache issue in plasma 6, I'm not sure if that's relevant to your configtool issue. If you see any "loading qml error" in systemsettings, try delete `~/.cache/systemsettings/` 

As for latter one, I can assure it works in plasma 6 and I have been use it every day since plasma 6 beta.

since you're using wayland, checkout https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma

You might just not add Pinyin or any other input method that you want to use, since your system language is English and the default profile generation won't add any Chinese input method for you automatically.

**Comment by aaronliu0130** [comment]
I later realized I confused the "Pinyin" input method with the "Hanyu Pinyin Letters with AltGr dead keys" *keyboard layout*.
