### ISSUE TITLE
Is it possible to package fcitx5 without systemd? 

### ISSUE THREAD

**Issue by rtlanceroad** [fcitx/fcitx5#11]
I ever asked this question in #fcitx IRC channel, but nobody seems avaliable at that time. Now I think, I should open an issue to ask about it. In `CMakeLists.txt` , there is: 
```
find_package(Systemd REQUIRED)
```
This is a hard dependency and it hurts for systemd-free distro packagers. A reasonable question to ask is **Is it possible to package fcitx5 without systemd?** It would be nice to see that an input method will be independent of any init system or service manager with respect to systemd.

**Comment by wengxt** [comment]
once libevent support got merged it can be built without systemd. Also,
when it’s built with systemd it only need systemd library and it doesn't
need to be run under systemd.

**Comment by rtlanceroad** [comment]
Thanks for your quick reply! It's a very good news to me. I would keep systemd away as far as I can, no systemd both in build time and in runtime.
