### ISSUE TITLE
Manjaro xfce无法输入拼音，也不能自选双拼方案

### ISSUE THREAD

**Issue by ajmz** [fcitx/fcitx5#111]
Manjaro-xfce-20，X11，装了fcitx5-config-qt-git，也修改了 ~/.config/fcitx5/profile和 ~/.xprofile。
添加双拼，无法选择下拉菜单显示双拼方案，请问怎样配置，谢谢。

**Comment by ayalhw** [comment]
你是不是混用了git版和非git版，
非git版请使用 fcitx5-configtool 包内的 `fcitx5-config-qt` 程序配置（就是不知道 manjaro 更新了吗，如果没更新就安装 kcm-fcitx5 然后使用里面的 `fcitx5-config-qt`
**永远不要混用两个版本**

**Comment by ayalhw** [comment]
> kcm-fcitx5只用于KDE，我提到了用的是xfce，应用库里没有fcitx5-config-qt，所以只能装fcitx5-config-qt-git。

这个包名是不是引起了你什么误解……当时这个包叫这个是因为上游就叫这个……这个包实际上 KCM 相关都是可选依赖，fcitx5-config-qt 是这个包的一部分，git版有单独的只不过是拆了包而已…… 
https://aur.archlinux.org/packages/fcitx5-config-qt-git/
你好好看看 pkgbase…… https://aur.archlinux.org/pkgbase/fcitx5-configtool-git/

> 另外，有个fcitx5-configtool，非git版是安装这个就能解决吗？

非 git 版就应该使用这个（这个包其实就是之前的 kcm-fcitx5

https://wiki.archlinux.org/index.php/Fcitx5#Configuration_tool

**Comment by ajmz** [comment]
> > kcm-fcitx5只用于KDE，我提到了用的是xfce，应用库里没有fcitx5-config-qt，所以只能装fcitx5-config-qt-git。
> 
> 这个包名是不是引起了你什么误解……当时这个包叫这个是因为上游就叫这个……这个包实际上 KCM 相关都是可选依赖，fcitx5-config-qt 是这个包的一部分，git版有单独的只不过是拆了包而已……
> https://aur.archlinux.org/packages/fcitx5-config-qt-git/
> 你好好看看 pkgbase…… https://aur.archlinux.org/pkgbase/fcitx5-configtool-git/
> 
> > 另外，有个fcitx5-configtool，非git版是安装这个就能解决吗？
> 
> 非 git 版就应该使用这个（这个包其实就是之前的 kcm-fcitx5
> 
> https://wiki.archlinux.org/index.php/Fcitx5#Configuration_tool

刚才没有刷新评论，已经在上面评论中做了更新。
之前看了几个网上教程，都没有提到fcitx5-configtool，可能是xfce和KDE安装时，可选依赖不一样？
还是和fcitx4一样，直接用fcitx5-im包组安装省事。
问题已经解决，谢谢。
