### ISSUE TITLE
Can not switch input methods

### ISSUE THREAD

**Issue by drunkwcodes** [fcitx/fcitx5#1111]
### Summary

想用 Ctrl+Space 在三個輸入法之間切換。但設定無效。
![螢幕快照 2024-08-04 11-36-01](https://github.com/user-attachments/assets/ca970f02-c019-4bd5-b76f-fae747777fff)

### Steps to Reproduce

1. Open fcitx setting
2. Open global settings tab
3. Change "枚舉輸入法向前" 並套用

### Expected Behavior

可以用 ctrl + space 切換輸入法

### Output of fcitx5-diagnose command

# System Info:
1.  `uname -a`:

        Linux drunkwcodes-TUF-GAMING-FX504GD-FX80GD 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        Distributor ID:	Ubuntu
        Description:	Ubuntu 24.04 LTS
        Release:	24.04
        Codename:	noble

3.  `lsb_release -d`:

        Description:	Ubuntu 24.04 LTS

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=24.04
        DISTRIB_CODENAME=noble
        DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"

5.  `/etc/os-release`:

        PRETTY_NAME="Ubuntu 24.04 LTS"
        NAME="Ubuntu"
        VERSION_ID="24.04"
        VERSION="24.04 LTS (Noble Numbat)"
        VERSION_CODENAME=noble
        ID=ubuntu
        ID_LIKE=debian
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        UBUNTU_CODENAME=noble
        LOGO=ubuntu-logo

6.  Desktop Environment:

    Desktop environment is `gnome3`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.2.21(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105+inet", "cn", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            ja_JP.utf8
            zh_CN.utf8
            zh_HK.utf8
            zh_SG.utf8
            zh_TW.utf8

    2.  Current locale:

            LANG=zh_TW.UTF-8
            LANGUAGE=zh_TW:zh_CN
            LC_CTYPE="C"
            LC_NUMERIC="C"
            LC_TIME="C"
            LC_COLLATE="C"
            LC_MONETARY="C"
            LC_MESSAGES="C"
            LC_PAPER="C"
            LC_NAME="C"
            LC_ADDRESS="C"
            LC_TELEPHONE="C"
            LC_MEASUREMENT="C"
            LC_IDENTIFICATION="C"
            LC_ALL=C

4.  Directories:

    1.  Home:

            /home/drunkwcodes

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/drunkwcodes/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/drunkwcodes/.config/fcitx5`).

5.  Current user:

    The script is run as drunkwcodes (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.7`

3.  process:

    Found 4 fcitx5 processes:

           4881 fcitx5
           5409 fcitx5-config-q
           6385 fcitx5-config-q
           6458 fcitx5-config-q

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.133`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `4881`.

    Debug information from dbus:

           Group [x11::1] has 8 InputContext(s)
          IC [ab0df1ae45994a09936b3281a84c4700] program:gnome-terminal-server frontend:dbus cap:6000000032 focus:1
          IC [d1a31bf0abb54e04aee883063ceb2926] program:fcitx5-config-qt frontend:dbus cap:16000800072 focus:0
          IC [83a0c56d2a7f40a8bbe84468ca806103] program:google-chrome-stable frontend:dbus cap:6000000032 focus:0
          IC [4386900bb4d24a9c909f4b62103be527] program:fcitx5-config-qt frontend:dbus cap:16000800072 focus:0
          IC [4cc99d13297a45468538f66612d7ef76] program:fcitx5-config-qt frontend:dbus cap:16000800072 focus:0
          IC [8701d43baec44f10891d1011f238c1e5] program: frontend:ibus cap:52 focus:0
          IC [94d4c3a208de4d87ae6d251e4396d8a3] program:gnome-terminal-server frontend:dbus cap:6000000032 focus:0
          IC [8f9a6aafae3c427abcc4f34721f7498b] program:google-chrome-stable frontend:dbus cap:6000000032 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM encoding:

    **Your LC_CTYPE is set to C whose encoding is not UTF-8. You may have trouble committing strings using XIM.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt6: `/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt6 module: `/lib/x86_64-linux-gnu/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for qt5: `/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-gtk2-immodule-probing` not found.**

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

    Using fcitx5-gtk4-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0t64/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.41` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0t64/gtk-query-immodules-3.0 from gtk+-3.24.41

        Found fcitx5 im modules for gtk `3.24.41`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 22 enabled addons:

            Anthy 5.1.3
            Classic User Interface 5.1.7
            Clipboard 5.1.7
            DBus 5.1.7
            DBus Frontend 5.1.7
            Emoji 5.1.7
            Fcitx4 Frontend 5.1.7
            IBus Frontend 5.1.7
            Input method selector 5.1.7
            Keyboard 5.1.7
            KDE Input Method Panel 5.1.7
            Status Notifier 5.1.7
            Notification 5.1.7
            Quick Phrase 5.1.7
            Rime 5.1.4
            Spell 5.1.7
            Unicode 5.1.7
            DBus Virtual Keyboard 5.1.7
            Wayland 5.1.7
            Wayland Input method frontend 5.1.7
            XCB 5.1.7
            X Input Method Frontend 5.1.7

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/drunkwcodes/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=預設
        # Layout
        Default Layout=cn
        # Default Input Method
        DefaultIM=rime

        [Groups/0/Items/0]
        # Name
        Name=keyboard-cn
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=rime
        # Layout
        Layout=

        [Groups/0/Items/2]
        # Name
        Name=anthy
        # Layout
        Layout=

        [GroupOrder]
        0=預設

# Log:
1.  `date`:

        Sun Aug  4 11:38:37 CST 2024

2.  `/home/drunkwcodes/.config/fcitx5/crash.log`:

    `/home/drunkwcodes/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by Smart-SangGe** [comment]
I'm encountered the same situation. Now I can only type English.:-(

**Comment by drunkwcodes** [comment]
@Smart-SangGe The workaround is set it to super(win)+space

**Comment by Smart-SangGe** [comment]
@drunkwcodes 好奇怪我可以在terminal切換和輸入，但是其他應用程序沒反應，像是chrome和qq

**Comment by drunkwcodes** [comment]
@Smart-SangGe 這我就不清楚了。說不定這是另一個 issue.

**Comment by wengxt** [comment]
@drunkwcodes 你配置能完整截图吗，默认 ctrl space 是分配给另一个功能

**Comment by wengxt** [comment]
@Smart-SangGe 请 https://github.com/fcitx/fcitx5/discussions 提问贴出 fcitx5-diagnose 的输出

**Comment by drunkwcodes** [comment]
原來如此，我看沒有其他的功能用到啊？

![螢幕快照 2024-10-09 01-09-58](https://github.com/user-attachments/assets/f7e62036-ae3a-43ff-a443-5862413c232f)

**Comment by wengxt** [comment]
@drunkwcodes  看起来你已经移除了那个 ctrl space （在你截图的第一项配置默认的配置里有 ctrl space）

能否在终端中运行这个命令
```
fcitx5 --verbose=key_trace=5 -rd
```

然后把按 ctrl space 时的输出贴一下。预期会看到类似下面的输出

```
10月 08 11:06:37 arch-rog fcitx5[736628]: D2024-10-08 11:06:37.652977 instance.cpp:919] KeyEvent: Key(Control_L states=0) rawKey: Key(Control_L states=0) origKey: Key(Control_L states=0) Release:0 keycode: 37
10月 08 11:06:37 arch-rog fcitx5[736628]: D2024-10-08 11:06:37.653113 inputcontext.cpp:321] KeyEvent handling time: 0ms result:0
10月 08 11:06:38 arch-rog fcitx5[736628]: D2024-10-08 11:06:38.133655 instance.cpp:919] KeyEvent: Key(Control+space states=4) rawKey: Key(Control+space states=4) origKey: Key(Control+space states=4) Release:0 keycode: 65
10月 08 11:06:38 arch-rog fcitx5[736628]: D2024-10-08 11:06:38.134800 inputcontext.cpp:321] KeyEvent handling time: 1ms result:1
10月 08 11:06:38 arch-rog fcitx5[736628]: D2024-10-08 11:06:38.277613 instance.cpp:919] KeyEvent: Key(Control+space states=4) rawKey: Key(Control+space states=4) origKey: Key(Control+space states=4) Release:1 keycode: 65
10月 08 11:06:38 arch-rog fcitx5[736628]: D2024-10-08 11:06:38.277738 inputcontext.cpp:321] KeyEvent handling time: 0ms result:0
10月 08 11:06:40 arch-rog fcitx5[736628]: D2024-10-08 11:06:40.878836 instance.cpp:919] KeyEvent: Key(Control+space states=4) rawKey: Key(Control+space states=4) origKey: Key(Control+space states=4) Release:0 keycode: 65
10月 08 11:06:40 arch-rog fcitx5[736628]: D2024-10-08 11:06:40.879584 inputcontext.cpp:321] KeyEvent handling time: 0ms result:1
10月 08 11:06:40 arch-rog fcitx5[736628]: D2024-10-08 11:06:40.956666 instance.cpp:919] KeyEvent: Key(Control+space states=4) rawKey: Key(Control+space states=4) origKey: Key(Control+space states=4) Release:1 keycode: 65
10月 08 11:06:40 arch-rog fcitx5[736628]: D2024-10-08 11:06:40.956769 inputcontext.cpp:321] KeyEvent handling time: 0ms result:0
10月 08 11:06:42 arch-rog fcitx5[736628]: D2024-10-08 11:06:42.436865 instance.cpp:919] KeyEvent: Key(Control+Control_L states=4) rawKey: Key(Control+Control_L states=4) origKey: Key(Control+Control_L states=4) Release:1 keycode: 37
10月 08 11:06:42 arch-rog fcitx5[736628]: D2024-10-08 11:06:42.436968 inputcontext.cpp:321] KeyEvent handling time: 0ms result:0
```

**Comment by drunkwcodes** [comment]
奇怪，我按壓 Ctrl + Space 沒有相關 log, 只有 Ctrl + Ctrl_L出現，唯有按壓  Super + Space 才有 log.

```
drunkwcodes@drunkwcodes-TUF-GAMING-FX504GD-FX80GD:~$ fcitx5 --verbose=key_trace=5 -rd
drunkwcodes@drunkwcodes-TUF-GAMING-FX504GD-FX80GD:~$ I2024-10-09 05:25:19.898888 instance.cpp:1346] Override Enabled Addons: {}
I2024-10-09 05:25:19.898981 instance.cpp:1347] Override Disabled Addons: {}
E2024-10-09 05:25:19.903234 waylandmodule.cpp:230] Failed to open wayland connection
I2024-10-09 05:25:19.903254 addonmanager.cpp:195] Loaded addon wayland
I2024-10-09 05:25:19.906127 xcbconnection.cpp:189] Connecting to X11 display, display name::1.
I2024-10-09 05:25:19.906495 addonmanager.cpp:195] Loaded addon xcb
I2024-10-09 05:25:19.908567 addonmanager.cpp:195] Loaded addon quickphrase
I2024-10-09 05:25:19.916183 addonmanager.cpp:195] Loaded addon keyboard
I2024-10-09 05:25:19.918934 addonmanager.cpp:195] Loaded addon dbus
I2024-10-09 05:25:19.922047 addonmanager.cpp:195] Loaded addon dbusfrontend
I2024-10-09 05:25:19.933199 addonmanager.cpp:195] Loaded addon fcitx4frontend
I2024-10-09 05:25:19.933994 addonmanager.cpp:195] Loaded addon imselector
I2024-10-09 05:25:19.937909 addonmanager.cpp:195] Loaded addon ibusfrontend
I2024-10-09 05:25:19.940206 addonmanager.cpp:195] Loaded addon clipboard
I2024-10-09 05:25:19.941233 addonmanager.cpp:195] Loaded addon waylandim
I2024-10-09 05:25:19.941992 addonmanager.cpp:195] Loaded addon unicode
E2024-10-09 05:25:19.944334 xim.cpp:137] Failed to open xim, retrying.
I2024-10-09 05:25:20.945223 addonmanager.cpp:195] Loaded addon xim
I2024-10-09 05:25:20.985272 inputmethodmanager.cpp:190] Found 737 input method(s) in addon keyboard
I2024-10-09 05:25:21.006719 addonmanager.cpp:195] Loaded addon kimpanel
I2024-10-09 05:25:21.007403 addonmanager.cpp:195] Loaded addon virtualkeyboard
I2024-10-09 05:25:21.054532 classicui.cpp:66] Created classicui for x11 display::1
I2024-10-09 05:25:21.054572 addonmanager.cpp:195] Loaded addon classicui
I2024-10-09 05:25:21.054940 addonmanager.cpp:195] Loaded addon notificationitem
I2024-10-09 05:25:21.055486 addonmanager.cpp:195] Loaded addon notifications
I2024-10-09 05:25:21.066487 kimpanel.cpp:116] Kimpanel new owner: 
I2024-10-09 05:25:21.066524 virtualkeyboard.cpp:223] VirtualKeyboard new owner: 
I2024-10-09 05:25:21.066552 portalsettingmonitor.cpp:91] A new portal show up, start a new query.
E2024-10-09 05:25:21.068754 portalsettingmonitor.cpp:115] DBus call error: org.freedesktop.portal.Error.NotFound 找不到請求的設定
I2024-10-09 05:25:22.219657 addonmanager.cpp:195] Loaded addon rime
D2024-10-09 05:25:26.470893 instance.cpp:910] KeyEvent: Key(Control_L states=0) rawKey: Key(Control_L states=16) origKey: Key(Control_L states=16) Release:0 keycode: 37
D2024-10-09 05:25:26.471197 inputcontext.cpp:323] KeyEvent handling time: 0ms result:0
D2024-10-09 05:25:26.734648 instance.cpp:910] KeyEvent: Key(Control+Control_L states=4) rawKey: Key(Control+Control_L states=20) origKey: Key(Control+Control_L states=20) Release:1 keycode: 37
D2024-10-09 05:25:26.734923 inputcontext.cpp:323] KeyEvent handling time: 0ms result:0
D2024-10-09 05:26:13.572919 instance.cpp:910] KeyEvent: Key(Super+space states=64) rawKey: Key(Super+space states=67108944) origKey: Key(Super+space states=67108944) Release:0 keycode: 65
D2024-10-09 05:26:13.598024 inputcontext.cpp:323] KeyEvent handling time: 25ms result:1
D2024-10-09 05:26:13.781361 instance.cpp:910] KeyEvent: Key(Super+space states=64) rawKey: Key(Super+space states=67108944) origKey: Key(Super+space states=67108944) Release:1 keycode: 65
D2024-10-09 05:26:13.781492 inputcontext.cpp:323] KeyEvent handling time: 0ms result:0
D2024-10-09 05:26:13.814724 instance.cpp:910] KeyEvent: Key(Super+Super_L states=64) rawKey: Key(Super+Super_L states=67108944) origKey: Key(Super+Super_L states=67108944) Release:1 keycode: 133
D2024-10-09 05:26:13.815196 inputcontext.cpp:323] KeyEvent handling time: 0ms result:0
D2024-10-09 05:26:30.137950 instance.cpp:910] KeyEvent: Key(Control_L states=0) rawKey: Key(Control_L states=16) origKey: Key(Control_L states=16) Release:0 keycode: 37
D2024-10-09 05:26:30.138360 inputcontext.cpp:323] KeyEvent handling time: 0ms result:0
D2024-10-09 05:26:30.458457 instance.cpp:910] KeyEvent: Key(Control+Control_L states=4) rawKey: Key(Control+Control_L states=20) origKey: Key(Control+Control_L states=20) Release:1 keycode: 37
D2024-10-09 05:26:30.458864 inputcontext.cpp:323] KeyEvent handling time: 0ms result:0

```

**Comment by wengxt** [comment]
@drunkwcodes 看起来这个就是导致你遇见问题的原因了，我在虚拟机里全新安装了一个 24.04.1 并没有重现你的问题，应该是你改动过什么配置导致的。最有可能就是你的桌面全局快捷键里面指定了 ctrl space

你可以打开 gnome-control-center 看看（特别如果你曾经使用 ibus 并且将它的切换键从 super space 改成了 ctrl space 的话）

![image](https://github.com/user-attachments/assets/73c70c9f-15cd-40b2-8812-632e8a277abd)

**Comment by drunkwcodes** [comment]
@wengxt 沒錯！ `gnome-control-center` 裡的設置改掉就可以用 Ctrl+Space了！感謝 Debug!
