### ISSUE TITLE
在arc-menu插件的搜索框中输入中文，拼音会被遮挡

### ISSUE THREAD

**Issue by CSUDaXiang** [fcitx/fcitx5#1112]
### Summary

![image](https://github.com/user-attachments/assets/57b6709f-7a2c-4100-966f-673c67ecf46f)
我在ubuntu系统中装了一个插件arc-menu，在这个插件的搜索框中，输入中文，拼音会被遮挡,，只能显示候选词。在其他的软件中输入中文没有这种被遮挡的问题，想咨询一下这个问题是否是fcitx5输入法的bug？

### Steps to Reproduce

稍后补充

### Expected Behavior

稍后补充

### Output of fcitx5-diagnose command

稍后补充

**Comment by CSUDaXiang** [comment]
经过验证，用ibus-libpinyin输入法不会有这种问题。
![Uploading image.png…]()

**Comment by CSUDaXiang** [comment]
![image](https://github.com/user-attachments/assets/fe8fafae-e05c-482e-b308-19c4a217a528)
经过验证，用ibus-libpinyin输入法不会有这种问题。

**Comment by wengxt** [comment]
装 https://github.com/wengxt/gnome-shell-extension-kimpanel

**Comment by wengxt** [comment]
https://extensions.gnome.org/extension/261/kimpanel/

**Comment by afatcat-xie** [comment]
我也遇到了类似的问题，但略有不同，我在使用ctrl+space切换到中文输入法后，在其它软件（例如浏览器、QQ）中可以正常显示候选框和输入的字符，但在Arc Menu的搜索框输入时，英文可以正常键入，输入中文时只显示键入的拉丁字符，不显示候选框，而且与原本的“搜索..."重合。安装这个插件以后，候选框可以显示，但文字还是会与“搜索..."重合。
