### ISSUE TITLE
Fix the input window

### ISSUE THREAD

**Issue by Melas-Wang** [fcitx/fcitx5#1116]
### Summary

I know it that cursor following disabled is not the fault of fcitx itself, but how can I fix the input window in the middle of the screen instead of certain corner?
I'm using omegat for translating on Linux, and unfortunately, a common cursor following problem happened, which works perfect on Windows.

I'd appreciate it if somebody can help me with this : )
It's really very important to improve my efficiency

**Comment by LeMonMonOTS** [comment]
Same here. This could be even more upset when using multi monitors...
I think allowing the input window to be "dragged" and "pinned" somewhere in default case would be a nice feature.

**Comment by wengxt** [comment]
> Same here. This could be even more upset when using multi monitors... I think allowing the input window to be "dragged" and "pinned" somewhere in default case would be a nice feature.

Based on the window type, it may not be possible at all, especially on wayland.
omegat itself is a java based program, which is a jre issue. 

However, there IS a fix around. 

https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04

Jetbrains patched there own JDK with the fix.
Here's the version that I tested and confirmed work: 21.0.5b631.19-1

So as long as you run their own patched jdk, it will work properly.


@muxueqz chrome should work, or at least can be made to work. Check
https://fcitx-im.org/wiki/FAQ
https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron

**Comment by muxueqz** [comment]
@wengxt I already use google-chrome --ozone-platform-hint=auto --gtk-version=4, but the input window on another monitor sometimes(not current monitor)
