### ISSUE TITLE
在焦点更改时显示输入法信息意见

### ISSUE THREAD

**Issue by yueduz** [fcitx/fcitx5#112]
我注意到提示的位置不是每次都正确。似乎是鼠标点击的更改焦点不能更新光标位置数据。每次定位不正确时按一下键盘上的任意键就能得到正确的位置。我想那能不能通过软件发送一个键盘事件来更新光标位置数据呢?比如发送Ctrl键。

另外提示如果能改成缩小的输入法挺盘图标不用文字提示就更好了。

**Comment by wengxt** [comment]
1、额外发送按键，肯定不行。有 bug 应该找程序自己修复。
2、用图标，暂时不考虑，因为是借用输入框来画的。
