### ISSUE TITLE
Candidate window position not right when use vertical candidate list

### ISSUE THREAD

**Issue by sonnycalcr** [fcitx/fcitx5#1135]
### Summary

My desktop info is Arch + hyprland:

hyprland version: 0.43.0
fcitx5 version: 5.1.10
monitor: 4K(3840x2160)

When I use fcitx5 to input some Chinese charaters, the pop up candidate window will appear in a wrong position.

### Steps to Reproduce

1.Make fcitx5 candidate list to be vertical,

![image](https://github.com/user-attachments/assets/f1777737-911c-46dc-9295-4612e4068fce)

2. Change the monitor settings in the hyprland.conf,

```
monitor = DP-1, 3840x2160@60, 0x0, 1.6
monitor = DP-2, 3840x2160@60, auto, 1.6
```

or,

```
monitor=,preferred,auto,auto
```

3. To use fcitx5 type some words in the bottom half area of the screen. Test in the area that closer to the bottom edge of the screen will be better.

### Expected Behavior

The candidate window follows the preedit in precise position.

### Output of fcitx5-diagnose command

# System Info:
1.  `uname -a`:

        Linux archlinux 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

5.  Desktop Environment:

    Cannot determine desktop environment.

6.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

7.  Bash Version:

        BASH_VERSION='5.2.32(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY='wayland-1'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)" };
                xkb_types     { include "complete"      };
                xkb_compat    { include "complete"      };
                xkb_symbols   { include "pc+us+inet(evdev)"     };
                xkb_geometry  { include "pc(pc105)"     };
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            en_US.utf8
            POSIX

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/sonnycalcr

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/sonnycalcr/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/sonnycalcr/.config/fcitx5`).

5.  Current user:

    The script is run as sonnycalcr (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.10`

3.  process:

    Found 2 fcitx5 processes:

           7754 fcitx5
          35552 fcitx5-config-q

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.106`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `7754`.

    Debug information from dbus:

           Group [wayland:] has 18 InputContext(s)
          IC [68c276ff8bec4913a0c062806e3f552d] program:org.fcitx.fcitx5-config-qt frontend:wayland_v2 cap:100000
072 focus:0
          IC [5646f2b051f441f4a7c11443b5dd8d89] program:org.kde.dolphin frontend:wayland_v2 cap:d0072 focus:0
          IC [854ba989bfe74c34b5809bc70c885707] program:google-chrome frontend:wayland_v2 cap:100000072 focus:0
          IC [938e2facdc1c4359b485b93efc851177] program:microsoft-edge frontend:wayland_v2 cap:72 focus:0
          IC [e029f588359e49faa9a4311512884473] program:kitty frontend:wayland_v2 cap:100000072 focus:0
          IC [9d13ab11f5b64ad6abb441c3ef861fd5] program:firefox frontend:wayland_v2 cap:72 focus:0
          IC [357812a731b34d5589fc37e3cca5100f] program:google-chrome frontend:wayland_v2 cap:100000072 focus:0
          IC [c79327b77c894f699eddd192ef0b77c7] program:kitty frontend:wayland_v2 cap:100000072 focus:0
          IC [c250b10eba994d8aa8c716b1bd72399a] program: frontend:wayland_v2 cap:100000072 focus:0
          IC [99643312f2cf4cb798dd37f96f909c1c] program:google-chrome frontend:wayland_v2 cap:100000072 focus:0
          IC [ed45bed0d58240f98597694cf7cc76b2] program:microsoft-edge frontend:wayland_v2 cap:82072 focus:0
          IC [7b8dc13e53ab431e8671534dfee63ea6] program:microsoft-edge frontend:wayland_v2 cap:100000072 focus:0
          IC [24d0ed51b8a44673a9be8c52c8bcd094] program:microsoft-edge frontend:wayland_v2 cap:82072 focus:0
          IC [ce4e5565fe2e4772baf4158de4d706f1] program:kitty frontend:wayland_v2 cap:100000072 focus:0
          IC [acf9165eaab240b380046ff5265a3c6e] program:kitty frontend:wayland_v2 cap:100000072 focus:1
          IC [b50ae1d7bdc24e72be21433810b56da8] program:kitty frontend:wayland_v2 cap:100000072 focus:0
          IC [b58f14f753014a92900f45f2f55377f9] program:microsoft-edge frontend:wayland_v2 cap:82072 focus:0
          IC [0e0ead277d3740feadba46047df470c7] program:firefox frontend:wayland_v2 cap:72 focus:0
        Group [x11::1] has 0 InputContext(s)
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possi
ble that you did not set the environment to the whole graphic desktop session. You may inspect the actual environ
ment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find
 not working.

## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS is not set**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add 
`export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS]
(http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `e
xport QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](h
ttp://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `e
xport QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](h
ttp://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt5 built-in Wayland im module if your compositor fully supports text-input protocol used b
y qt5.**

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QComposeInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `e
xport QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](h
ttp://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt6 built-in Wayland im module if your compositor fully supports text-input protocol used b
y qt6.**

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin
.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplug
in.so`.
    Found unknown fcitx qt module: `/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution pa
ckages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are 
using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `
export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE
](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

    **It is OK to use gtk built-in Wayland im module if your compositor fully supports text-input protocol used b
y gtk.**

    **`fcitx5-gtk2-immodule-probing` not found.**

    **`fcitx5-gtk3-immodule-probing` not found.**

    **`fcitx5-gtk4-immodule-probing` not found.**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.43` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0`**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.43` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 3 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 27 enabled addons:

            Simplified and Traditional Chinese Translation 5.1.6
            Classic User Interface 5.1.10
            Clipboard 5.1.10
            Cloud Pinyin 5.1.6
            DBus 5.1.10
            DBus Frontend 5.1.10
            Emoji 5.1.10
            Fcitx4 Frontend 5.1.10
            Full width character 5.1.6
            IBus Frontend 5.1.10
            Input method selector 5.1.10
            Keyboard 5.1.10
            KDE Input Method Panel 5.1.10
            Status Notifier 5.1.10
            Notification 5.1.10
            Pinyin 5.1.6
            Extra Pinyin functionality 5.1.6
            Punctuation 5.1.6
            Quick Phrase 5.1.10
            Spell 5.1.10
            Table 5.1.6
            Unicode 5.1.10
            DBus Virtual Keyboard 5.1.10
            Wayland 5.1.10
            Wayland Input method frontend 5.1.10
            XCB 5.1.10
            X Input Method Frontend 5.1.10

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/sonnycalcr/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=shuangpin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=shuangpin
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Sun Sep 22 04:11:02 PM CST 2024

2.  `/home/sonnycalcr/.config/fcitx5/crash.log`:

    `/home/sonnycalcr/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel 
version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as 
necessary before posting it online publicly.**

**Comment by wengxt** [comment]
can you provide screenshot when position is wrong?

**Comment by sonnycalcr** [comment]
> can you provide screenshot when position is wrong?

Sorry, forgot that. Here are screenshots:

when I input in the bottom half area, it was wrong:

![image 2](https://github.com/user-attachments/assets/28b0b94d-c17f-482e-956b-5fe3b40acb35)

![image 3](https://github.com/user-attachments/assets/15633bc1-db8e-47ce-91c7-b30e57513b54)

and on the top half area, it works fine:

![image](https://github.com/user-attachments/assets/91ea0d67-f7b1-40cd-865f-feff13bd0acc)

**Comment by wengxt** [comment]
Please report to hyprland.

The native wayland input method window is placed by compositor.
