### ISSUE TITLE
Need help on touchscreen keyboard on KDE plasma 6 wayland

### ISSUE THREAD

**Issue by stkevintan** [fcitx/fcitx5#1143]
### Summary

Hi, I installed archlinux on my Surface Go2 recently. everything works fine except that no on screen keyboard appears after I removed the physical keyboard away and started using the Surface as a tablet device with touchscreen.

My system details:
KDE plasma 6.1.5 Wayland

I noticed that you closed one similar issue before: https://github.com/fcitx/fcitx5/issues/87#issuecomment-1678074723

But unfortunately, after I installed the package from [AUR](https://aur.archlinux.org/packages/kylin-virtual-keyboard-git), nothing changed, no new item was added to the virtual keyboard list from system settings:
![image](https://github.com/user-attachments/assets/3623dd1b-9f3f-435e-9989-4aa2d23fca92)

Here are a few questions:
1. Can anyone help me to make Kylin virtual keyboard work on KDE plasma 6?
2. Do we have any plan to add **native** OSK support for tablet (touchscreen without physical keyboard) ?

Thanks for your great job!

**Comment by wengxt** [comment]
as I mentioned in the blog  https://www.csslayer.info/wordpress/fcitx-dev/%e6%bc%94%e7%a4%ba%e4%b8%80%e4%b8%8b%e5%92%8c-openkylin-%e5%90%88%e4%bd%9c%e5%bc%80%e5%8f%91%e7%9a%84%e8%99%9a%e6%8b%9f%e9%94%ae%e7%9b%98/

you can use it under X11 and get better experience, as for wayland.. not so well.

You can try to enforce it to run with xwayland
QT_QPA_PLATFORM=xcb ./kylin-virtual-keyboard

But as far as I know it doesn't work very well that well.
