### ISSUE TITLE
刚刚更新的Libreoffice Writer不能输入中文，Libreoffice套件中的其它程序中文输入正常

### ISSUE THREAD

**Issue by 3xpert** [fcitx/fcitx5#1144]
### Summary

如题，输入中文显示为方框

### Steps to Reproduce

1.切换到fcitx5
2.人任何键
3.中文显示为方框

### Expected Behavior

正确地显示所输入的中文

### Output of fcitx5-diagnose command

❯ LC_ALL=C fcitx5-diagnose
# System Info:
1.  `uname -a`:

        Linux tiger 6.10.11-2-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Sep 26 03:28:26 UTC 2024 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	ManjaroLinux
        Description:	Manjaro Linux
        Release:	24.1.0
        Codename:	Xahea

3.  `lsb_release -d`:

        Description:	Manjaro Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="ManjaroLinux"
        DISTRIB_RELEASE="24.1.0"
        DISTRIB_CODENAME="Xahea"
        DISTRIB_DESCRIPTION="Manjaro Linux"

5.  `/etc/os-release`:

        NAME="Manjaro Linux"
        PRETTY_NAME="Manjaro Linux"
        ID=manjaro
        ID_LIKE=arch
        BUILD_ID=rolling
        ANSI_COLOR="32;1;24;144;200"
        HOME_URL="https://manjaro.org/"
        DOCUMENTATION_URL="https://wiki.manjaro.org/"
        SUPPORT_URL="https://forum.manjaro.org/"
        BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
        PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
        LOGO=manjarolinux

6.  Desktop Environment:

    Desktop environment is `gnome3`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.2.32(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+us:2+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105+inet", "us,us", ",", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            en_US.utf8
            zh_CN.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="C"
            LC_NUMERIC="C"
            LC_TIME="C"
            LC_COLLATE="C"
            LC_MONETARY="C"
            LC_MESSAGES="C"
            LC_PAPER="C"
            LC_NAME="C"
            LC_ADDRESS="C"
            LC_TELEPHONE="C"
            LC_MEASUREMENT="C"
            LC_IDENTIFICATION="C"
            LC_ALL=C

4.  Directories:

    1.  Home:

            /home/tom

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/tom/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/tom/.config/fcitx5`).

5.  Current user:

    The script is run as tom (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.10`

3.  process:

    Found 1 fcitx5 process:

           1234 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.64`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `1234`.

    Debug information from dbus:

           Group [x11::0] has 34 InputContext(s)
          IC [74a0b36a1cac435e92131717459ffe5d] program:soffice frontend:dbus cap:6000000072 focus:0
          IC [5caf6691776944819778ee2adb36b283] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [87eba9859db74982843f5775b206b120] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [dc66140568bf4850811dbe4e96d4c550] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [1d6c74cd2e1447cfaa69e7db1e4fd138] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [c1eeb28cc7744a8f9a93d1ed9ac1c97b] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [ce2439eeca444060b06319f82f67cbd9] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [ae5149d8e05344b1b241da189a30a193] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [7e20ea788cc44b02a19fe6a7003d860e] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [8f6d95b9850d4f65bf5e0bcdc66c2ec4] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [a40866b2d2114179b26894472c79bffa] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [22bba405d33947ebb256ebf1634671c8] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [a406cbd3af534f01bcfbbf8d0d04fc24] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [5f748619f9a94deb819ac098dc89e6c4] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [5c5e89d789df49a9bd54aef6107f71a3] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [38c74c3cb47044e59c4b6f2a01f5e323] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [a7849d6ceb27408b9c52425da1a66f22] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [396c6702c9df43f39a877e688fb9cdfb] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [a62f384b3d524ecdad2d0fc31bae558c] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [68f81ca3fd7d48d4b8fcee0bceba8c5f] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [9a1293d6c7df480096dee89a919ed7d3] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [0373f63d8d0d46ada38511d207ede111] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [30fa2d1a5860484eb2277196a367e0c6] program:xpad frontend:dbus cap:6000000032 focus:0
          IC [3699b080b8a44cd5a410cc6f1ed01272] program:google-chrome frontend:dbus cap:6000000032 focus:0
          IC [6fe51af33aa7464a9b3dd89a7ce0d09d] program:telegram-desktop frontend:dbus cap:16000800072 focus:0
          IC [aeb43f642fd144eab5141373745550a2] program:xpad frontend:dbus cap:6000000032 focus:0
          IC [7d95bdaf3f684f998ca04c55ceb30f14] program:xpad frontend:dbus cap:6000000032 focus:0
          IC [6c129ec0ca4f4a28812821dd6aa2aac5] program:xpad frontend:dbus cap:6000000032 focus:0
          IC [85aa65f47fdb4ef1a409eef6fb9827dc] program:xpad frontend:dbus cap:6000000032 focus:0
          IC [bc304a4ee16e44ecb46f8bb8dc20adf7] program:com.github.amezin.ddterm frontend:dbus cap:6000000032 focus:0
          IC [8f3fb187d157479db4ae056ddac6e65e] program:soffice frontend:dbus cap:6000000032 focus:0
          IC [0da7b311b08c4ff1b3a266ea184e531f] program:com.github.amezin.ddterm frontend:dbus cap:6000000032 focus:0
          IC [80c169cd634d48dea630e485b81d2e8d] program:com.github.amezin.ddterm frontend:dbus cap:6000000032 focus:1
          IC [7fb52525d3cc4e9e908e82d2bf61f6bb] program: frontend:ibus cap:52 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM encoding:

    **Your LC_CTYPE is set to C whose encoding is not UTF-8. You may have trouble committing strings using XIM.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-gtk2-immodule-probing to check the actual im module to be used under current environment:

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

    Using fcitx5-gtk4-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.43` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        Found fcitx5 im modules for gtk `3.24.43`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.43` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        Found fcitx5 im modules for gtk `3.24.43`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 27 enabled addons:

            Simplified and Traditional Chinese Translation 5.1.6
            Classic User Interface 5.1.10
            Clipboard 5.1.10
            Cloud Pinyin 5.1.6
            DBus 5.1.10
            DBus Frontend 5.1.10
            Emoji 5.1.10
            Fcitx4 Frontend 5.1.10
            Full width character 5.1.6
            IBus Frontend 5.1.10
            Input method selector 5.1.10
            Keyboard 5.1.10
            KDE Input Method Panel 5.1.10
            Status Notifier 5.1.10
            Notification 5.1.10
            Pinyin 5.1.6
            Extra Pinyin functionality 5.1.6
            Punctuation 5.1.6
            Quick Phrase 5.1.10
            Spell 5.1.10
            Table 5.1.6
            Unicode 5.1.10
            DBus Virtual Keyboard 5.1.10
            Wayland 5.1.10
            Wayland Input method frontend 5.1.10
            XCB 5.1.10
            X Input Method Frontend 5.1.10

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/tom/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=wbpy

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=wbpy
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Wed Oct  2 16:29:18 CST 2024

2.  `/home/tom/.config/fcitx5/crash.log`:

    `/home/tom/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by wengxt** [comment]
你既然已经输入了，那就不是输入法的问题
