### ISSUE TITLE
如何设置默认的输入法

### ISSUE THREAD

**Issue by Huangyong657** [fcitx/fcitx5#1149]
### Summary

我使用的是fcitx4，在debian11系统上。我没有使用fcitx的ui界面进行配置，而是使用的是qt的qdbus发送命令给fcitx，进行设置和写入。我下载了fcitx-pinyin和英文，我启动我的系统，默认输入法为pinyin，我想改为默认输入法为英文，我如何设置（修改哪个文件），我指的是我重启系统，默认系统输入法为英文。

**Comment by CoelacanthusHex** [comment]
fcitx4 的问题为什么要报到 fcitx5 的仓库来……

**Comment by wengxt** [comment]
所以你为什么不用配置界面呢 ´_>` …

如果你的目的是想要自动化，那我教你个办法，你先用界面配置好，然后看看文件有什么区别
