### ISSUE TITLE
更新 kde 6.2 后， wayland text-input 协议无法使用

### ISSUE THREAD

**Issue by microcai** [fcitx/fcitx5#1153]
### Summary

使用 text-input 协议，qt 不需要设置 QT_IM_MODULE 模块，不用载入 fcitx-qt 模块，就能使用 wayland 的输入协议工作。 一直工作很正常，直到更新了 KDE 6.2 后，就必须要设置 QT_IM_MODULE 变量才能使用输入法了。
另外 chromium 也必须得使用 --gtk-version=4 才能使用输入法了。之前只要 --enable-waylane-ime ，然后使用 wayland text-input v1 协议就能工作了。
猜测可能是 kwin 的修改导致 fcitx 的 wayland text input 协议对接出了问题。

### Steps to Reproduce

从 KDE 6.1 升级到 6.2

### Expected Behavior

正常使用

### Output of fcitx5-diagnose command

[fcitx-diagnoselog.txt](https://github.com/user-attachments/files/17341394/fcitx-diagnoselog.txt)

**Comment by CoelacanthusHex** [comment]
无法复现，请首先检查你的 fcitx5 是否是由 kwin 启动的。在 systemd 的发行版上可以检查 `plasma-kwin_wayland.service` 用户服务单元内是否有 fcitx5 或者 fcitx5-wayland-launcher 进程。

**Comment by wengxt** [comment]
他不小心把 kwin 的输入法功能关了
