### ISSUE TITLE
[SPELL_EN_DICT]: Alternative means to get en_dict.txt

### ISSUE THREAD

**Issue by raghavgururajan** [fcitx/fcitx5#116]
Currently, the en_dict.txt file is set to be downloaded from internet. This is problematic, as some build-system build packages in an isolated environment, where internet access in not available. Because of this, fcitx fails to build.

@wengxt 
Could you please create an cmake option, to get the en_dict.txt file from a specified path?

**Comment by wengxt** [comment]
What you need to do is simple put the downloaded file in the source directory, then you'll avoid the actual download.
