### ISSUE TITLE
是否只能在输入框内才能正确切换输入法

### ISSUE THREAD

**Issue by Huangyong657** [fcitx/fcitx5#1160]
### Summary

我在fcitx上切换输入法。有两种方式，一个是快捷键，一个是通过dbus发送SetCurrentIM。asyncCallWithArgumentList(QStringLiteral("SetCurrentIM"), argumentList);用于切换输入法。
我发现只有在输入框内发送或是快捷键才有focus消息，其他比如在非输入框内没有该消息。对应的情况为
只有在输入框内输入才能正常正确切换输入法

### Steps to Reproduce

有两种方式，一个是快捷键，一个是通过dbus发送SetCurrentIM。asyncCallWithArgumentList(QStringLiteral("SetCurrentIM"), argumentList);当焦点不在输入框或是输入栏切换输入法。

### Expected Behavior

输入法可以切换

### Output of fcitx5-diagnose command

fcitx5-diagnose表明此刻输入法默认值是英文，实际输入还是中文

**Comment by CoelacanthusHex** [comment]
当前输入法是一个 IC（IME context）里的状态吧，你要是不 focus 怎么知道要改哪个 IC 的状态呢（还有一种可能是这时候改的全局状态，但是 IC 有自己的状态覆盖了全局状态）。不知道设置「全局共享输入法状态」会不会有变化。

我没看代码，以上仅作为个人根据以往经验的猜测。

**Comment by Huangyong657** [comment]
如何设置全局状态？

**Comment by wengxt** [comment]
这里有几个不同的问题
每个框允许有不同的状态，所以必须有框才知道你要设置状态给谁

如果你在配置里设置了全局共享状态的话，可以允许没有框再设置状态。
