### ISSUE TITLE
can't get it working on KDE Plasma 

### ISSUE THREAD

**Issue by tubbadu** [fcitx/fcitx5#1161]
### Summary

 I'm trying to set up fcitx5 virtual keyboard on my x86 tablet running EndeavourOS (KDE Wayland, plasma 6). I installed `extra/fcitx5`, `extra/fcitx5-qt` and `extra/fcitx5-gtk`. I followed the instructions [here](https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma), and set 
```sh
export XMODIFIERS="@im=fcitx"
```
in both my .bashrc and .zshrc, just to be sure (zsh is the default shell)
I then set in the system settings Fcitx5 as virtual keyboard, and rebooted. When I now try to tap on any textbox (in tablet mode, no mouse nor keyboard attached) the keyboard does not pop up at all, no signs of life. in the system settings there's also "fcitx5 wayland launcher experimental", I tried to do the same selecting it instead of "fcitx5" but nothing changed. Maliit instead works correctly (if I select it in the system settings). 
Any idea what am I doing wrong?

### Steps to Reproduce

install the mentioned packages, set the environmental variable, enable fcitx5 from system settings and reboot

### Expected Behavior

the virtual keyboard pops up when a textbox gets focus

### Output of fcitx5-diagnose command

see attached file
[fcitxlog.txt](https://github.com/user-attachments/files/17486999/fcitxlog.txt)

**Comment by wengxt** [comment]
Every thing looks pretty normal. I didn't see you added any input method

please check https://fcitx-im.org/wiki/Input_method_engines for engine package you may want to install, and then you can add them via fcitx5-configtool.

**Comment by wengxt** [comment]
Also, the virtual keyboard kcm is not really about "virtual keyboard". It's just a bad name for now. (what it actually does is to set which wayland input method that kwin talks to)

If you want a real virtual keyboard with fcitx5 you'll need to compile https://gitee.com/openkylin/kylin-virtual-keyboard and use x11 for now.

**Comment by tubbadu** [comment]
> Also, the virtual keyboard kcm is not really about "virtual keyboard". It's just a bad name for now. (what it actually does is to set which wayland input method that kwin talks to)
> 
> If you want a real virtual keyboard with fcitx5 you'll need to compile https://gitee.com/openkylin/kylin-virtual-keyboard and use x11 for now.

thanks for the reply! So fcitx5 does not currently provide a UI, but just the "backend"?

**Comment by wengxt** [comment]
@tubbadu no, there's no UI in fcitx that can be used as virtual keyboard.

There's another project that does some adhoc patch https://github.com/clear-code/fcitx5-virtualkeyboard-ui if you're interested, but that may only work on an old patched fcitx5.

https://gitee.com/openkylin/kylin-virtual-keyboard is the one that we supports. 

The code here https://github.com/fcitx/fcitx5/tree/master/src/ui/virtualkeyboard is just sending/receiving dbus request with https://gitee.com/openkylin/kylin-virtual-keyboard .

**Comment by tubbadu** [comment]
got it, thank you very much for the explanation!
