### ISSUE TITLE
Under the Nouveau driver, in the Chinese input method, in Google Chrome, Under wayland settings ，Pinyin will turn yellow

### ISSUE THREAD

**Issue by fshytt** [fcitx/fcitx5#1164]
### Summary

For example, if you enter Chinese in GitHub,

### Steps to Reproduce

1.Nouveau drive
2.Google
3.chrome://flags 
Preferred Ozone platform  wayland
text-input-v3   enabled

### Expected Behavior

Pinyin will not turn yellow

### Output of fcitx5-diagnose command

# Log:
1.  `date`:

        Wed Oct 30 22:21:06 CST 2024

2.  `/home/xxx/.config/fcitx5/crash.log`:

    `/home/xxx/.config/fcitx5/crash.log` not found.

**Comment by wengxt** [comment]
We have seen this before and conclude it to be some theme configuration on gtk/chrome side. Also just to let you know fcitx has no control the color directly.

**Comment by wengxt** [comment]
@fshytt I believe it's chrome itself hardcode this color somewhere in its own code. 

There's no api to allow fcitx send a specific rgb color.

From what I know, using a light theme instead of dark one can make it more useable as a workaround before chrome fix it.
