### ISSUE TITLE
Add new input method

### ISSUE THREAD

**Issue by d1Bihkte** [fcitx/fcitx5#1165]
### Summary

Latest fcitx5 doesn't have standard keyboard for Sinhala language. Existing keyboards are difficult to use and unlike typing using the standard keyboard, typing using other keyboards takes longer.

![Screenshot from 2024-10-30 15-47-45](https://github.com/user-attachments/assets/8f803a64-11ab-4a73-8b49-6ed05ce6d743)

@wengxt Can you make standard Sinhala keyboard for fcitx5 using below resources?

IBus standard Sinhala keyboard layout (Aka. wijesekara layout)
https://git.savannah.nongnu.org/cgit/m17n/m17n-db.git/tree/MIM/si-wijesekara.mim

Documentation for standard Sinhala keyboard

Sinhala character code for information interchange (3rd revision)
Sri Lanka standard 1134:2011 UDC 003:035 : 003.336
[SLS-1134-2011-3-v7.0.pdf](https://github.com/user-attachments/files/17577439/SLS-1134-2011-3-v7.0.pdf)

**Comment by wengxt** [comment]
did you install fcitx5-m17n?

![图片](https://github.com/user-attachments/assets/c46c279d-6b8f-4cda-922c-c13f3483bbc2)

**Comment by d1Bihkte** [comment]
> did you install fcitx5-m17n?

I didn't know that. Now i installed it. Thank you.

**Request - 1**
Please add the wiki link to main fcitcx configuration interface. If someone new to fcitcx, they need to ask help from people or search third-party guides or give-up.

![image](https://github.com/user-attachments/assets/5621e66a-75d9-4d39-aad5-68014d7c19c6)


E.g. If you can't find required keyboard, please follow [this guide](https://fcitx-im.org/wiki/Input_method_engines) to install other input method engines

**Request - 2**

Please add description to fcitx5-m17n
https://fcitx-im.org/wiki/Input_method_engines
![image](https://github.com/user-attachments/assets/e37ba7d4-cf8a-4d6a-b984-a03fc85986fa)

Just like this
![image](https://github.com/user-attachments/assets/79800ff4-85a3-48c1-b3a0-fedcb145287e)

**Comment by wengxt** [comment]
The actual plan was to use package kit to list uninstalled input method 

https://github.com/fcitx/fcitx5-configtool/issues/49

As for wiki, any contribution is welcome, you can also help!

As for m17n tiself, it provides more than 200 engines. I don't think I could enumerate all of them.

**Comment by d1Bihkte** [comment]
> fcitx/fcitx5-configtool#49

It's a good idea
