### ISSUE TITLE
Support greek alphabet

### ISSUE THREAD

**Issue by Firestar-Reimu** [fcitx/fcitx5#1172]
### Summary

Support quick type of greek alphabet so that it will be more convenient for math and physics workers

for example, I type `delta` and `Δ`,`δ` will both appear on the top 5 of my select list

the map between latin names and greek alphabet can see [wikipedia](https://en.wikipedia.org/wiki/Greek_alphabet) or latex commands

**Comment by wengxt** [comment]
quick phrase already does this

try  super + ' and type \alpha 

or with unicode addon 
ctrl alt shift + u and type alpha
