### ISSUE TITLE
fcitx5-skk doesn't work, show "Not available"

### ISSUE THREAD

**Issue by Rw9393** [fcitx/fcitx5#1181]
### Summary

I use Gentoo Linux.
I built libskk and fcitx5-skk.
But it doesn't work, it was showed me this.
![image](https://github.com/user-attachments/assets/38769d19-6dcd-4521-9e3f-5bab7dc7ee2f)

I don't know how I do. Please tell me what I should do.

### Steps to Reproduce

1. Build "libskk" from [here](https://github.com/ueno/libskk)
2. Build "fcitx5-skk" from [here](https://github.com/fcitx/fcitx5-skk)

### Expected Behavior

Fcitx5 will be showed you this.
![image](https://github.com/user-attachments/assets/211f4401-6906-4055-a7fa-b528122e66f9)

### Output of fcitx5-diagnose command

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.10`

3.  process:

    Found 1 fcitx5 process:

         2544 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.0`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `2544`.

    Debug information from dbus:

           Group [x11::0] has 5 InputContext(s)
          IC [1a60fcfec5b04a1e931aaed5bad6f353] program:firefox-esr frontend:dbus cap:6000000032 focus:0
          IC [3e6ecaee01b94939a299773954e6a00f] program:firefox-esr frontend:dbus cap:6000000032 focus:0
          IC [5f92cee689604b80ae8fcbb7bb6a26a5] program:firefox-esr frontend:dbus cap:6000000032 focus:0
          IC [c1b8c3ba919e4a27a85bb6940949cbf6] program:firefox-esr frontend:dbus cap:6000000072 focus:0
          IC [c0ba4863b4e84c1897627a35ead05704] program: frontend:xim cap:4000000000 focus:1
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM for Emacs:

    **Your LC_CTYPE is set to en_GB.utf8 instead of one of zh, ja, ko. You may not be able to use input method in emacs because of an really old emacs bug that upstream refuse to fix for years.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt IM module files:

    Found fcitx5 qt6 module: `/usr/lib64/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/usr/lib64/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for qt5: `/usr/lib64/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 im module for qt6: `/usr/lib64/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt6 module: `/usr/local/lib64/fcitx5/qt6/libfcitx5-skk-config.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-gtk2-immodule-probing` not found.**

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

    Using fcitx5-gtk4-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.41` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.41

        Found fcitx5 im modules for gtk `3.24.41`.

            "/usr/lib64/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.41` at `/usr/lib64/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/x86_64-pc-linux-gnu-gtk-query-immodules-3.0 from gtk+-3.24.41

        Found fcitx5 im modules for gtk `3.24.41`.

            "/usr/lib64/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 19 enabled addons:

            Anthy 5.1.3
            Classic User Interface 5.1.10
            Clipboard 5.1.10
            DBus 5.1.10
            DBus Frontend 5.1.10
            Emoji 5.1.10
            Fcitx4 Frontend 5.1.10
            IBus Frontend 5.1.10
            Input method selector 5.1.10
            Keyboard 5.1.10
            KDE Input Method Panel 5.1.10
            Status Notifier 5.1.10
            Notification 5.1.10
            Quick Phrase 5.1.10
            Spell 5.1.10
            Unicode 5.1.10
            DBus Virtual Keyboard 5.1.10
            XCB 5.1.10
            X Input Method Frontend 5.1.10

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/Username/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name="Group 2"
        # Layout
        Default Layout=gb
        # Default Input Method
        DefaultIM=keyboard-gb

        [Groups/0/Items/0]
        # Name
        Name=keyboard-gb
        # Layout
        Layout=

        [Groups/1]
        # Group Name
        Name="Group 1"
        # Layout
        Default Layout=jp
        # Default Input Method
        DefaultIM=anthy

        [Groups/1/Items/0]
        # Name
        Name=skk
        # Layout
        Layout=

        [Groups/1/Items/1]
        # Name
        Name=anthy
        # Layout
        Layout=

        [GroupOrder]
        0="Group 1"
        1="Group 2"

**Comment by wengxt** [comment]
There was a bug discovered recently in libskk that prevent it from working 

https://github.com/ueno/libskk/issues/89

Did you apply the fix?

Can you explain how you build it? From gentoo ebuild or manually run cmake etc?

**Comment by Rw9393** [comment]
I built it manually.
I cloned from master branch. and run configure script, `make install`

**Comment by wengxt** [comment]
Did you install the required data files?

On arch linux it’s like, you can read through the build script and figure out where to get them
https://archlinux.org/packages/extra/any/skk-jisyo/

Did you install fcitx5-skk to the same prefix as fcitx5? Specifically, where is your skk.so installed? does it go with other fcitx5/*.so files, or it’s in its own directory?

**Comment by Rw9393** [comment]
I installed skk-jisyo from ebuild.
```
$ find / -name skk.so
/usr/local/lib64/fcitx5/skk.so
```

**Comment by wengxt** [comment]
Ok, that’s the reason.

basically, there’s no standard for plugin library like xdg data/config, so fcitx will not try to look for /usr/local. (there’s a fcitx specific environment variables FCITX_ADDON_DIRS though ).

Try install fcitx5-skk to same prefix as fcitx5. `-DCMAKE_INSTALL_PREFIX=/usr`

**Comment by Rw9393** [comment]
it solved.
I appreciate your support.
