### ISSUE TITLE
Tray icon is transparent

### ISSUE THREAD

**Issue by jesHrz** [fcitx/fcitx5#1191]
### Summary

the tray icons of some input methods are transparent and can not be clearly identified on the waybar.

Keyboard-English (US), Rime, Pinyin, Wubi pinyin, these methods have transparent icon while mozc is not。

![图片](https://github.com/user-attachments/assets/6343c9e7-17b2-4f99-b39a-ec99c783c187)

![图片](https://github.com/user-attachments/assets/468c5bfa-50a1-4af1-9329-5764464b0fe1)

### Steps to Reproduce

my environment: hyprland + waybar with fcitx5 autostarted by `exec = fcitx5 -d` in the hyprland configuration file.

this issue always exists when the system is booted.

### Expected Behavior

I think the icon should be clearly identified (see other tray icons like wechat or just the mozc method).

But actually, when the background of waybar is white, this icon is very clear but I dont like the white background at all.

### Output of fcitx5-diagnose command

# System Info:
1.  `uname -a`:

        Linux MSIArch 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	Arch
        Description:	Arch Linux
        Release:	rolling
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	Arch Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="Arch"
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

6.  Desktop Environment:

    Cannot determine desktop environment.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

8.  Bash Version:

        BASH_VERSION='5.2.37(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY='wayland-1'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            en_US.utf8
            zh_CN.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="C"
            LC_NUMERIC="C"
            LC_TIME="C"
            LC_COLLATE="C"
            LC_MONETARY="C"
            LC_MESSAGES="C"
            LC_PAPER="C"
            LC_NAME="C"
            LC_ADDRESS="C"
            LC_TELEPHONE="C"
            LC_MEASUREMENT="C"
            LC_IDENTIFICATION="C"
            LC_ALL=C

4.  Directories:

    1.  Home:

            /home/jeshrz

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/jeshrz/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/jeshrz/.config/fcitx5`).

5.  Current user:

    The script is run as jeshrz (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.11`

3.  process:

    Found 2 fcitx5 processes:

         136758 fcitx5
         393549 fcitx5-config-q

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.178`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `136758`.

    Debug information from dbus:

           Group [wayland:] has 10 InputContext(s)
          IC [800c54f273664cd4b016dfd26a3ce522] program:fcitx5-config-qt frontend:dbus cap:1e001800072 focus:0
          IC [e6c2f4ba708349aa841444278be36165] program:org.fcitx.fcitx5-config-qt frontend:wayland_v2 cap:72 focus:0
          IC [a01afabd1c55439fbe6b4105ce8027d8] program:kitty frontend:wayland_v2 cap:100000072 focus:1
          IC [370b63a4d6174fb6999f8ba7f2bea3b9] program:kitty frontend:wayland_v2 cap:100000072 focus:0
          IC [ad6ee76365a0428eaf076c4144885e19] program:code frontend:wayland_v2 cap:72 focus:0
          IC [5e9dc20ecbad48d49cf852e99afb2dac] program:code frontend:wayland_v2 cap:100000072 focus:0
          IC [0bdeac6f7b38466190462b53791bc052] program:firefox frontend:wayland_v2 cap:72 focus:0
          IC [660df283854f44ffa3f883144bbdaebe] program:kitty frontend:wayland_v2 cap:100000072 focus:0
          IC [4cf1c7ddc7e0442db45b96930819951c] program:fcitx5-config-qt frontend:dbus cap:e001800072 focus:0
          IC [0d12ba33388d47deaf42e341c29487ec] program: frontend:wayland_v2 cap:100000072 focus:0
        Group [x11::1] has 3 InputContext(s)
          IC [80248fe389ea4c839285c168b8698771] program:WeChatAppEx frontend:dbus cap:6000000032 focus:0
          IC [0db968d7401c4f0a9d03d6200d91f70b] program:wechat frontend:dbus cap:800072 focus:0
          IC [70eae80a33d141abba12ecd0e7301dd8] program:wechat frontend:dbus cap:800072 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    **Environment variable XMODIFIERS is "@im=fcitx5" instead of "@im=fcitx". Please check if you have exported it incorrectly in any of your init files.**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**

    Xim Server Name from Environment variable is fcitx5.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM encoding:

    **Your LC_CTYPE is set to C whose encoding is not UTF-8. You may have trouble committing strings using XIM.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`.
    Found unknown fcitx qt module: `/usr/lib/office6/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

    **It is OK to use gtk built-in Wayland im module if your compositor fully supports text-input protocol used by gtk.**

    Using fcitx5-gtk2-immodule-probing to check the actual im module to be used under current environment:

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=wayland

    Using fcitx5-gtk4-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=wayland

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.43` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        Found fcitx5 im modules for gtk `3.24.43`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.43` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        Found fcitx5 im modules for gtk `3.24.43`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 29 enabled addons:

            Simplified and Traditional Chinese Translation 5.1.7
            Classic User Interface 5.1.11
            Clipboard 5.1.11
            Cloud Pinyin 5.1.7
            DBus 5.1.11
            DBus Frontend 5.1.11
            Emoji 5.1.11
            Fcitx4 Frontend 5.1.11
            Full width character 5.1.7
            IBus Frontend 5.1.11
            Input method selector 5.1.11
            Keyboard 5.1.11
            KDE Input Method Panel 5.1.11
            Mozc 
            Status Notifier 5.1.11
            Notification 5.1.11
            Pinyin 5.1.7
            Extra Pinyin functionality 5.1.7
            Punctuation 5.1.7
            Quick Phrase 5.1.11
            Rime 5.1.9
            Spell 5.1.11
            Table 5.1.7
            Unicode 5.1.11
            DBus Virtual Keyboard 5.1.11
            Wayland 5.1.11
            Wayland Input method frontend 5.1.11
            XCB 5.1.11
            X Input Method Frontend 5.1.11

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/jeshrz/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=jp
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=mozc

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=mozc
        # Layout
        Layout=

        [Groups/1]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=rime

        [Groups/1/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/1/Items/1]
        # Name
        Name=rime
        # Layout
        Layout=

        [Groups/1/Items/2]
        # Name
        Name=pinyin
        # Layout
        Layout=

        [GroupOrder]
        0=Default
        1=jp

# Log:
1.  `date`:

        Wed Nov 27 19:48:51 CST 2024

2.  `/home/jeshrz/.config/fcitx5/crash.log`:

    `/home/jeshrz/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by wengxt** [comment]
If you look closely, it's not transparent, but just a symbolic black keyboard in your screenshot.

Use another icon theme instead.

On unknown desktop fcitx will use gtk3 icon theme.

It seems that you're using breeze. However, it is a icon theme can only work well on kde since kde has it's own svg css support, which means under kde it will be rendered with theme color.
