### ISSUE TITLE
在 Firefox 地址栏输入中文进行搜索的时候会输入原字母而不是汉字

### ISSUE THREAD

**Issue by oodzchen** [fcitx/fcitx5#1194]
### Summary

KDE 上的 Firefox 进行搜索，尤其是自定义的搜索引擎，输入中文的时候，偶尔会出现一个词语前半部分是中文后半部分把字母给输进去了，没有正确翻译成中文，感觉好像是有延迟，需要输入字母完成后等几秒钟按 space 键，才能正常输入。不太清楚是 fcitx 的问题还是 Firefox 的问题。

### Steps to Reproduce

1. Linux 安装最新的 Firefox 浏览器
2. 安装 fictx5 并配置双拼输入
3. 在 Firefox 浏览器地址栏输入中文

### Expected Behavior

正常输入正文

### Output of fcitx5-diagnose command

 # System Info:
1.  `uname -a`:

        Linux pc-edv 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	EndeavourOS
        Description:	EndeavourOS Linux
        Release:	rolling
        Codename:	rolling

3.  `lsb_release -d`:

        Description:	EndeavourOS Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="EndeavourOS"
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="EndeavourOS Linux"
        DISTRIB_CODENAME="rolling"

5.  `/etc/os-release`:

        NAME="EndeavourOS"
        PRETTY_NAME="EndeavourOS"
        ID="endeavouros"
        ID_LIKE="arch"
        BUILD_ID="2024.04.20"
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://endeavouros.com"
        DOCUMENTATION_URL="https://discovery.endeavouros.com"
        SUPPORT_URL="https://forum.endeavouros.com"
        BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
        PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
        LOGO="endeavouros"

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.2.37(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc104", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            en_US.utf8
            zh_CN.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="C"
            LC_NUMERIC="C"
            LC_TIME="C"
            LC_COLLATE="C"
            LC_MONETARY="C"
            LC_MESSAGES="C"
            LC_PAPER="C"
            LC_NAME="C"
            LC_ADDRESS="C"
            LC_TELEPHONE="C"
            LC_MEASUREMENT="C"
            LC_IDENTIFICATION="C"
            LC_ALL=C

4.  Directories:

    1.  Home:

            /home/xxx

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/xxx/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/xxx/.config/fcitx5`).

5.  Current user:

    The script is run as xxx (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.11`

3.  process:

    Found 2 fcitx5 processes:

           2565 fcitx5
           2700 fcitx5-plasma-t

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.75`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `2565`.

    Debug information from dbus:

           Group [x11::0] has 29 InputContext(s)
          IC [34edd38e5d964d71bae888c4609efd6a] program:chromium frontend:dbus cap:6000000032 focus:0
          IC [648972fc83354f3ca1683bb6fd7ea0ea] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [44f6a0fe0f654c22a73e1cc6bec6edcc] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [643f8c42b26444d888da2b56f8f499a3] program:krunner frontend:dbus cap:6000820072 focus:0
          IC [ede95a117900480295ab1aa478d2b1ad] program:chromium frontend:dbus cap:6000000032 focus:0
          IC [a81963c8d0bf493e9ca26c9b5949e30a] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [435d61a62e3b4d6989875455437e04ba] program:firefox-aurora frontend:dbus cap:6000000032 focus:0
          IC [affddea854284a70bbb465018aab412f] program:konsole frontend:dbus cap:6000820872 focus:1
          IC [3751cac6a064445fbf7bcc00f4ac775e] program:akregator frontend:dbus cap:16000820072 focus:0
          IC [bd6653edfaca4a0f97f8886b272c94e4] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [1b0ca3195c994c2fb53ba975f080168b] program:clash-verge frontend:dbus cap:6000000020 focus:0
          IC [a5b8117977754ba990403358012effaa] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [f887e405ca1c4753bfa238057e9d3ba9] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [91dd3e13fb5b4a788dc02ac44030599a] program:caffeine frontend:dbus cap:6000000032 focus:0
          IC [f1a89716a7e24a45a47b61ec3293de26] program:caffeine frontend:dbus cap:6000000032 focus:0
          IC [387477daf56249788beb4dc85ce3b8c5] program:qbittorrent frontend:dbus cap:6000800072 focus:0
          IC [9b2b58e36373473da24ae1615a1200cc] program:kwin_x11 frontend:dbus cap:16000800072 focus:0
          IC [094a2481ae61463db770d62cc58495df] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [2d7d01bede2b4ae7b08f8835111ad5ed] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [ea7363875b214c75abf90e5d2885d147] program:emacs-29.4 frontend:xim cap:4000000000 focus:0
          IC [1aae37362c0849caaff11a0bd3e464f7] program:emacs frontend:dbus cap:6000000032 focus:0
          IC [50c074efebfa48f3b6cc673c80086c0e] program:emacs frontend:dbus cap:6000000032 focus:0
          IC [813cc1b212144b4ebf4128ed84f0015d] program:emacs-29.4 frontend:xim cap:4000000000 focus:0
          IC [f876917d5d1047e093cfc93513bf6f47] program:emacs-29.4 frontend:xim cap:4000000000 focus:0
          IC [7cc9f4be13f640ebb5e90126f92a2311] program:emacs-29.4 frontend:xim cap:4000000000 focus:0
          IC [93d2c363241847f38744c4e768eeb196] program:caffeine frontend:dbus cap:6000000032 focus:0
          IC [376affcdaf604f67a8e68e56c8ee99da] program:emacs frontend:dbus cap:6000000032 focus:0
          IC [4aa3034edbca497db52fe4c1e6969efa] program:emacs frontend:dbus cap:6000000032 focus:0
          IC [c98e5673c25f48de8a30abf9c446ba9e] program:firefox-aurora frontend:dbus cap:6000000072 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM for Emacs:

    **Your LC_CTYPE is set to C instead of one of zh, ja, ko. You may not be able to use input method in emacs because of an really old emacs bug that upstream refuse to fix for years.**

4.  XIM encoding:

    **Your LC_CTYPE is set to C whose encoding is not UTF-8. You may have trouble committing strings using XIM.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-gtk2-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

    Using fcitx5-gtk4-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.43` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        Found fcitx5 im modules for gtk `3.24.43`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.43` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        Found fcitx5 im modules for gtk `3.24.43`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 27 enabled addons:

            Simplified and Traditional Chinese Translation 5.1.7
            Classic User Interface 5.1.11
            Clipboard 5.1.11
            Cloud Pinyin 5.1.7
            DBus 5.1.11
            DBus Frontend 5.1.11
            Emoji 5.1.11
            Fcitx4 Frontend 5.1.11
            Full width character 5.1.7
            IBus Frontend 5.1.11
            Input method selector 5.1.11
            Keyboard 5.1.11
            KDE Input Method Panel 5.1.11
            Status Notifier 5.1.11
            Notification 5.1.11
            Pinyin 5.1.7
            Extra Pinyin functionality 5.1.7
            Punctuation 5.1.7
            Quick Phrase 5.1.11
            Spell 5.1.11
            Table 5.1.7
            Unicode 5.1.11
            DBus Virtual Keyboard 5.1.11
            Wayland 5.1.11
            Wayland Input method frontend 5.1.11
            XCB 5.1.11
            X Input Method Frontend 5.1.11

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/xxx/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=shuangpin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=shuangpin
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Sat Nov 30 12:44:34 CST 2024

2.  `/home/xxx/.config/fcitx5/crash.log`:

    `/home/xxx/.config/fcitx5/crash.log` not found.

**Comment by wengxt** [comment]
一般问题是 firefox 重置了输入法状态，触发可能的条件是firefox用预编辑进行匹配，可以关掉预编辑或者改变预编辑内容的形式绕过

过去一个曾经的例子： https://bugzilla.mozilla.org/show_bug.cgi?id=1693726

如果你有稳定重现的办法可以汇报给 firefox

**Comment by oodzchen** [comment]
@wengxt 最近还发现有些网站的输入框，在输入中文的时候也遇到这个问题，比 Firefox 地址栏还严重，输入的瞬间候选词面板被强制消失来，只能输入字母或者空格进去，偶尔能输入一个中文，但是直接复制粘贴中文进去就没事。这个问题在最新的 Firefox 开发版和 Chromium 上都有复现。

目前发现的有两个地方，一个是机核网文章下的评论框，一个是 Discord 在创建频道的时候频道名称输入框。我用浏览器审查代码看了下，共同点是输入框元素都绑定了 [invalid 事件](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event)，而且页面都用到了 React.js。不知道这些平台用了什么特殊代码触发这种情形，我在自己的 React 项目里面试了给输入框绑定 invalid 事件却没有任何问题。
