### ISSUE TITLE
Jetbrains apps use fcitx5 sometime not dismiss pop-up 

### ISSUE THREAD

**Issue by gczgcz2015** [fcitx/fcitx5#1196]
### Summary

在使用jetbrains时，有选择框消失后存留灰框的bug,我使用fcitx时没有这个问题。
![image](https://github.com/user-attachments/assets/d78b5ffd-770f-49ed-b594-c33a7bae0ddd)

这个问题并非在输入时出现。

### Steps to Reproduce

1. 开启fcitx5
2. 在jetbrains任何软件中 右键调出选择框 此时有概率选择框消失后会有一个灰色的框

### Expected Behavior

灰色框消失

### Output of fcitx5-diagnose command

# System Info:
1.  `uname -a`:

        Linux g-vmwarevirtualplatform 6.11.10-2-MANJARO #1 SMP PREEMPT_DYNAMIC Mon, 25 Nov 2024 05:29:44 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	ManjaroLinux
        Description:	Manjaro Linux
        Release:	24.2.0
        Codename:	Yonada

3.  `lsb_release -d`:

        Description:	Manjaro Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="ManjaroLinux"
        DISTRIB_RELEASE="24.2.0"
        DISTRIB_CODENAME="Yonada"
        DISTRIB_DESCRIPTION="Manjaro Linux"

5.  `/etc/os-release`:

        NAME="Manjaro Linux"
        PRETTY_NAME="Manjaro Linux"
        ID=manjaro
        ID_LIKE=arch
        BUILD_ID=rolling
        ANSI_COLOR="32;1;24;144;200"
        HOME_URL="https://manjaro.org/"
        DOCUMENTATION_URL="https://wiki.manjaro.org/"
        SUPPORT_URL="https://forum.manjaro.org/"
        BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
        PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
        LOGO=manjarolinux

6.  Desktop Environment:

    Cannot determine desktop environment.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.2.37(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            aa_DJ
            aa_DJ.utf8
            aa_ER
            aa_ET
            af_ZA
            af_ZA.utf8
            agr_PE
            ak_GH
            am_ET
            an_ES
            an_ES.utf8
            anp_IN
            ar_AE
            ar_AE.utf8
            ar_BH
            ar_BH.utf8
            ar_DZ
            ar_DZ.utf8
            ar_EG
            ar_EG.utf8
            ar_IN
            ar_IQ
            ar_IQ.utf8
            ar_JO
            ar_JO.utf8
            ar_KW
            ar_KW.utf8
            ar_LB
            ar_LB.utf8
            ar_LY
            ar_LY.utf8
            ar_MA
            ar_MA.utf8
            ar_OM
            ar_OM.utf8
            ar_QA
            ar_QA.utf8
            ar_SA
            ar_SA.utf8
            ar_SD
            ar_SD.utf8
            ar_SS
            ar_SY
            ar_SY.utf8
            ar_TN
            ar_TN.utf8
            ar_YE
            ar_YE.utf8
            as_IN
            ast_ES
            ast_ES.utf8
            ayc_PE
            az_AZ
            az_IR
            be_BY
            be_BY@latin
            be_BY.utf8
            bem_ZM
            ber_DZ
            ber_MA
            bg_BG
            bg_BG.utf8
            bhb_IN.utf8
            bho_IN
            bho_NP
            bi_VU
            bn_BD
            bn_IN
            bo_CN
            bo_IN
            br_FR
            br_FR@euro
            br_FR.utf8
            brx_IN
            bs_BA
            bs_BA.utf8
            byn_ER
            C
            ca_AD
            ca_AD.utf8
            ca_ES
            ca_ES@euro
            ca_ES.utf8
            ca_ES@valencia
            ca_FR
            ca_FR.utf8
            ca_IT
            ca_IT.utf8
            ce_RU
            chr_US
            ckb_IQ
            cmn_TW
            crh_RU
            crh_UA
            csb_PL
            cs_CZ
            cs_CZ.utf8
            C.utf8
            cv_RU
            cy_GB
            cy_GB.utf8
            da_DK
            da_DK.utf8
            de_AT
            de_AT@euro
            de_AT.utf8
            de_BE
            de_BE@euro
            de_BE.utf8
            de_CH
            de_CH.utf8
            de_DE
            de_DE@euro
            de_DE.utf8
            de_IT
            de_IT.utf8
            de_LI.utf8
            de_LU
            de_LU@euro
            de_LU.utf8
            doi_IN
            dsb_DE
            dv_MV
            dz_BT
            el_CY
            el_CY.utf8
            el_GR
            el_GR@euro
            el_GR.utf8
            en_AG
            en_AU
            en_AU.utf8
            en_BW
            en_BW.utf8
            en_CA
            en_CA.utf8
            en_DK
            en_DK.utf8
            en_GB
            en_GB.utf8
            en_HK
            en_HK.utf8
            en_IE
            en_IE@euro
            en_IE.utf8
            en_IL
            en_IN
            en_NG
            en_NZ
            en_NZ.utf8
            en_PH
            en_PH.utf8
            en_SC.utf8
            en_SG
            en_SG.utf8
            en_US
            en_US.utf8
            en_ZA
            en_ZA.utf8
            en_ZM
            en_ZW
            en_ZW.utf8
            eo
            es_AR
            es_AR.utf8
            es_BO
            es_BO.utf8
            es_CL
            es_CL.utf8
            es_CO
            es_CO.utf8
            es_CR
            es_CR.utf8
            es_CU
            es_DO
            es_DO.utf8
            es_EC
            es_EC.utf8
            es_ES
            es_ES@euro
            es_ES.utf8
            es_GT
            es_GT.utf8
            es_HN
            es_HN.utf8
            es_MX
            es_MX.utf8
            es_NI
            es_NI.utf8
            es_PA
            es_PA.utf8
            es_PE
            es_PE.utf8
            es_PR
            es_PR.utf8
            es_PY
            es_PY.utf8
            es_SV
            es_SV.utf8
            es_US
            es_US.utf8
            es_UY
            es_UY.utf8
            es_VE
            es_VE.utf8
            et_EE
            et_EE.iso885915
            et_EE.utf8
            eu_ES
            eu_ES@euro
            eu_ES.utf8
            fa_IR
            ff_SN
            fi_FI
            fi_FI@euro
            fi_FI.utf8
            fil_PH
            fo_FO
            fo_FO.utf8
            fr_BE
            fr_BE@euro
            fr_BE.utf8
            fr_CA
            fr_CA.utf8
            fr_CH
            fr_CH.utf8
            fr_FR
            fr_FR@euro
            fr_FR.utf8
            fr_LU
            fr_LU@euro
            fr_LU.utf8
            fur_IT
            fy_DE
            fy_NL
            ga_IE
            ga_IE@euro
            ga_IE.utf8
            gbm_IN
            gd_GB
            gd_GB.utf8
            gez_ER
            gez_ER@abegede
            gez_ET
            gez_ET@abegede
            gl_ES
            gl_ES@euro
            gl_ES.utf8
            gu_IN
            gv_GB
            gv_GB.utf8
            hak_TW
            ha_NG
            he_IL
            he_IL.utf8
            hif_FJ
            hi_IN
            hne_IN
            hr_HR
            hr_HR.utf8
            hsb_DE
            hsb_DE.utf8
            ht_HT
            hu_HU
            hu_HU.utf8
            hy_AM
            hy_AM.armscii8
            ia_FR
            id_ID
            id_ID.utf8
            ig_NG
            ik_CA
            is_IS
            is_IS.utf8
            it_CH
            it_CH.utf8
            it_IT
            it_IT@euro
            it_IT.utf8
            iu_CA
            ja_JP.eucjp
            ja_JP.utf8
            kab_DZ
            ka_GE
            ka_GE.utf8
            kk_KZ
            kk_KZ.utf8
            kl_GL
            kl_GL.utf8
            km_KH
            kn_IN
            kok_IN
            ko_KR.euckr
            ko_KR.utf8
            ks_IN
            ks_IN@devanagari
            ku_TR
            ku_TR.utf8
            kv_RU
            kw_GB
            kw_GB.utf8
            ky_KG
            lb_LU
            lg_UG
            lg_UG.utf8
            li_BE
            lij_IT
            li_NL
            ln_CD
            lo_LA
            ltg_LV.utf8
            lt_LT
            lt_LT.utf8
            lv_LV
            lv_LV.utf8
            lzh_TW
            mag_IN
            mai_IN
            mai_NP
            mdf_RU
            mfe_MU
            mg_MG
            mg_MG.utf8
            mhr_RU
            mi_NZ
            mi_NZ.utf8
            miq_NI
            mjw_IN
            mk_MK
            mk_MK.utf8
            ml_IN
            mni_IN
            mn_MN
            mnw_MM
            mr_IN
            ms_MY
            ms_MY.utf8
            mt_MT
            mt_MT.utf8
            my_MM
            nan_TW
            nan_TW@latin
            nb_NO
            nb_NO.utf8
            nds_DE
            nds_NL
            ne_NP
            nhn_MX
            niu_NU
            niu_NZ
            nl_AW
            nl_BE
            nl_BE@euro
            nl_BE.utf8
            nl_NL
            nl_NL@euro
            nl_NL.utf8
            nn_NO
            nn_NO.utf8
            nr_ZA
            nso_ZA
            oc_FR
            oc_FR.utf8
            om_ET
            om_KE
            om_KE.utf8
            or_IN
            os_RU
            pa_IN
            pap_AW
            pap_CW
            pa_PK
            pl_PL
            pl_PL.utf8
            POSIX
            ps_AF
            pt_BR
            pt_BR.utf8
            pt_PT
            pt_PT@euro
            pt_PT.utf8
            quz_PE
            raj_IN
            rif_MA
            ro_RO
            ro_RO.utf8
            ru_RU
            ru_RU.koi8r
            ru_RU.utf8
            ru_UA
            ru_UA.utf8
            rw_RW
            sah_RU
            sa_IN
            sat_IN
            sc_IT
            scn_IT
            sd_IN
            sd_IN@devanagari
            se_NO
            sgs_LT
            shn_MM
            shs_CA
            sid_ET
            si_LK
            sk_SK
            sk_SK.utf8
            sl_SI
            sl_SI.utf8
            sm_WS
            so_DJ
            so_DJ.utf8
            so_ET
            so_KE
            so_KE.utf8
            so_SO
            so_SO.utf8
            sq_AL
            sq_AL.utf8
            sq_MK
            sr_ME
            sr_RS
            sr_RS@latin
            ssy_ER
            ss_ZA
            st_ZA
            st_ZA.utf8
            su_ID
            sv_FI
            sv_FI@euro
            sv_FI.utf8
            sv_SE
            sv_SE.utf8
            sw_KE
            sw_TZ
            syr
            szl_PL
            ta_IN
            ta_LK
            tcy_IN.utf8
            te_IN
            tg_TJ
            tg_TJ.utf8
            the_NP
            th_TH
            th_TH.utf8
            ti_ER
            ti_ET
            tig_ER
            tk_TM
            tl_PH
            tl_PH.utf8
            tn_ZA
            tok
            to_TO
            tpi_PG
            tr_CY
            tr_CY.utf8
            tr_TR
            tr_TR.utf8
            ts_ZA
            tt_RU
            tt_RU@iqtelif
            ug_CN
            uk_UA
            uk_UA.utf8
            unm_US
            ur_IN
            ur_PK
            uz_UZ
            uz_UZ@cyrillic
            uz_UZ.utf8
            ve_ZA
            vi_VN
            wa_BE
            wa_BE@euro
            wa_BE.utf8
            wae_CH
            wal_ET
            wo_SN
            xh_ZA
            xh_ZA.utf8
            yi_US
            yi_US.utf8
            yo_NG
            yue_HK
            yuw_PG
            zgh_MA
            zh_CN
            zh_CN.gb18030
            zh_CN.gbk
            zh_CN.utf8
            zh_HK
            zh_HK.utf8
            zh_SG
            zh_SG.gbk
            zh_SG.utf8
            zh_TW
            zh_TW.euctw
            zh_TW.utf8
            zu_ZA
            zu_ZA.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC=zh_CN.UTF-8
            LC_TIME=zh_CN.UTF-8
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY=zh_CN.UTF-8
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER=zh_CN.UTF-8
            LC_NAME=zh_CN.UTF-8
            LC_ADDRESS=zh_CN.UTF-8
            LC_TELEPHONE=zh_CN.UTF-8
            LC_MEASUREMENT=zh_CN.UTF-8
            LC_IDENTIFICATION=zh_CN.UTF-8
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/g

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/g/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/g/.config/fcitx5`).

5.  Current user:

    The script is run as g (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.11`

3.  process:

    Found 1 fcitx5 process:

           1498 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.27`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `1498`.

    Debug information from dbus:

           Group [x11::0] has 7 InputContext(s)
          IC [77241e7c6323420d829b15808c85c5bf] program:datagrip frontend:xim cap:4000000000 focus:1
          IC [f189163c84234e49b44c8abe3a3dc698] program:google-chrome frontend:dbus cap:6000000032 focus:0
          IC [2dd64eeae6f441799ff52cc2a1e8b47f] program:com.alibabainc.dingtalk frontend:dbus cap:6000000032 focus:0
          IC [7717e2816e764a7884448bfeefbb706e] program:com.alibabainc.dingtalk frontend:fcitx4 cap:800072 focus:0
          IC [f440740d6b954f7db40c5c4da8cf4dbc] program: frontend:xim cap:4000000000 focus:0
          IC [8abdf8fb962746e5a422f244faf206f4] program: frontend:xim cap:4000000000 focus:0
          IC [a838f7975c2b4e7e83d86ab0572f3aec] program:phpstorm frontend:xim cap:4000000000 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt IM module files:

    Found unknown fcitx qt module: `/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-gtk2-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

    Using fcitx5-gtk4-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.43` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        Found fcitx5 im modules for gtk `3.24.43`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.43` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        Found fcitx5 im modules for gtk `3.24.43`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 27 enabled addons:

            Simplified and Traditional Chinese Translation 5.1.7
            Classic User Interface 5.1.11
            Clipboard 5.1.11
            Cloud Pinyin 5.1.7
            DBus 5.1.11
            DBus Frontend 5.1.11
            Emoji 5.1.11
            Fcitx4 Frontend 5.1.11
            Full width character 5.1.7
            IBus Frontend 5.1.11
            Input method selector 5.1.11
            Keyboard 5.1.11
            KDE Input Method Panel 5.1.11
            Status Notifier 5.1.11
            Notification 5.1.11
            Pinyin 5.1.7
            Extra Pinyin functionality 5.1.7
            Punctuation 5.1.7
            Quick Phrase 5.1.11
            Spell 5.1.11
            Table 5.1.7
            Unicode 5.1.11
            DBus Virtual Keyboard 5.1.11
            Wayland 5.1.11
            Wayland Input method frontend 5.1.11
            XCB 5.1.11
            X Input Method Frontend 5.1.11

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/g/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=pinyin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=pinyin
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        2024年 12月 04日 星期三 16:53:58 CST

2.  `/home/g/.config/fcitx5/crash.log`:

    `/home/g/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by wengxt** [comment]
这和输入法有关系吗……

你用xwininfo指一下那个窗口看看是什么

**Comment by gczgcz2015** [comment]
> 这和输入法有关系吗……
> 
> 你用xwininfo指一下那个窗口看看是什么

emmm，应该是有关系的，因为我关掉fcitx5之后就没这个问题了。切到fcitx也没这个问题。并不能用xwininfo来看窗口的信息，因为单击和按$mod键之后该窗口就消失了。
这个框框是我在软件里面单击右键弹出的选择框，大部分的时间能正常消失，有大约10%的概率无法正常消失。
无论如何感谢回复

**Comment by wengxt** [comment]
你窗口管理器或者显卡驱动之类的东西的bug

如果窗口甚至都不是fcitx的窗口的话
