### ISSUE TITLE
Unabale to find kcmshell5 after I upgrade to KDE 6

### ISSUE THREAD

**Issue by Bob0111** [fcitx/fcitx5#1197]
### Summary

**`kcmshell5` not found.**

### Steps to Reproduce

Upgrade to KDE6 under debian, and cannot find fcitx5 settings in settings menu. Instead, when I try to set the software, it'll open fcitx5-config-qt.

### Expected Behavior

Open KDE settings app instead of the separate setting app.

### Output of fcitx5-diagnose command

# System Info:
1.  `uname -a`:

        Linux familyseven 6.11.10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.11.10-1 (2024-11-23) x86_64 GNU/Linux

2.  `lsb_release -a`:

        Distributor ID: Debian
        Description:    Debian GNU/Linux trixie/sid
        Release:        n/a
        Codename:       trixie

3.  `lsb_release -d`:

        Description:    Debian GNU/Linux trixie/sid

4.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

5.  `/etc/os-release`:

        PRETTY_NAME="Debian GNU/Linux trixie/sid"
        NAME="Debian GNU/Linux"
        VERSION_CODENAME=trixie
        ID=debian
        HOME_URL="https://www.debian.org/"
        SUPPORT_URL="https://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

8.  Bash Version:

        BASH_VERSION='5.2.32(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY='wayland-0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)" };
                xkb_types     { include "complete"      };
                xkb_compat    { include "complete"      };
                xkb_symbols   { include "pc+us+inet(evdev)"     };
                xkb_geometry  { include "pc(pc105)"     };
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            en_US.utf8
            ja_JP.utf8
            zh_CN.utf8

    2.  Current locale:

            LANG=C
            LANGUAGE=zh_CN:en_US:ja
            LC_CTYPE="C"
            LC_NUMERIC="C"
            LC_TIME="C"
            LC_COLLATE="C"
            LC_MONETARY="C"
            LC_MESSAGES="C"
            LC_PAPER="C"
            LC_NAME="C"
            LC_ADDRESS="C"
            LC_TELEPHONE="C"
            LC_MEASUREMENT="C"
            LC_IDENTIFICATION="C"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/lenovo

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/lenovo/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/lenovo/.config/fcitx5`).

5.  Current user:

    The script is run as lenovo (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.11`

3.  process:

    Found 3 fcitx5 processes:

           1590 fcitx5-wayland-
           1592 fcitx5
           1709 fcitx5-plasma-t

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.33`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `1592`.

    Debug information from dbus:

           Group [x11::1] has 0 InputContext(s)
        Group [wayland:] has 5 InputContext(s)
          IC [82bdd217510249eb934323ed5d1bdaa2] program:org.kde.konsole frontend:wayland cap:60 focus:1
          IC [ba88e3fbcda348e08ec2d4a638269c19] program:org.kde.kate frontend:wayland cap:d0060 focus:0
          IC [d32407e3445543c18db6fd321b3c69f5] program:firefox-esr frontend:wayland cap:60 focus:0
          IC [b7f37a0d9287401ea174e17b3c01d675] program:org.kde.dolphin frontend:wayland cap:8000d0060 focus:0
          IC [1ab77305a45b4ad79a2a2ecd9d7f4012] program: frontend:wayland cap:60 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

**Comment by wengxt** [comment]
should be no harm, especially configtool script now execute systemsettings directly, not kcmshell.

Will consider remove that section.

**Comment by Bob0111** [comment]
But with KDE 6, when I open configuration tool, it opens Qt Widgets based UI instead of Kirigami 2 based UI. And there are no fcitx5 config module in KDE systemsettings app.
![Screenshot_20241207_093849](https://github.com/user-attachments/assets/285fb797-c67f-4728-a34a-a2bbc06b53db)

**Comment by wengxt** [comment]
@Bob0111 You might be missing some package.

Did you install this?

https://packages.debian.org/sid/kde-config-fcitx5

**Comment by Bob0111** [comment]
Yes. I excute apt search kde-config-fcitx5, and the terminal outputs: 

kde-config-fcitx5/testing,now 5.1.7-1 amd64 [installed,automatic]

**Comment by Bob0111** [comment]
I compared the package in sid and trixie, and find out why. The 5.1.7-1 package put kcmshell module under QT 5 directory and 5.1.7-2 put it under QT6 directory. Upgrade the package kde-config-fcitx from sid repo and now it works like a charm. Thanks for your help!

**Comment by wengxt** [comment]
this package can be built against either qt5 or qt6. It is recommended for debian packager to build against qt6 if distro provides kde6 instead of kde5.
