### ISSUE TITLE
fcitx5 input methods duplicate input on Brave address bar

### ISSUE THREAD

**Issue by Revival8697** [fcitx/fcitx5#1201]
### Summary

fcitx5 input methods duplicate input on Brave address bar. Tested with [fcitx5-bamboo](https://github.com/fcitx/fcitx5-bamboo) and [fcitx5-unikey](https://github.com/fcitx/fcitx5-unikey).

### Steps to Reproduce

1. Install and setup [fcitx5](https://wiki.archlinux.org/title/Fcitx5). 
2. Launch Brave with `brave --incognito --ozone-platform=wayland --enable-wayland-ime --wayland-text-input-version=3`. 
3. Go to the address bar, switch input methods and type anything followed by a space.

https://github.com/user-attachments/assets/4a623c06-1b97-47fd-b8e8-c3f6c0e7b5bf

### Expected Behavior

Words don't duplicate.

### Output of fcitx5-diagnose command

# System Info:
1.  `uname -a`:

        Linux ally-x 6.12.2-2-cachyos-deckify #1 SMP PREEMPT_DYNAMIC Thu, 05 Dec 2024 18:53:45 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	cachyos
        Description:	CachyOS
        Release:	rolling
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	CachyOS

4.  `/etc/lsb-release`:

        DISTRIB_ID=cachyos
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="CachyOS"

5.  `/etc/os-release`:

        NAME="CachyOS Linux"
        PRETTY_NAME="CachyOS"
        ID=cachyos
        ID_LIKE=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://cachyos.org/"
        DOCUMENTATION_URL="https://wiki.cachyos.org/"
        SUPPORT_URL="https://discuss.cachyos.org/"
        BUG_REPORT_URL="https://github.com/cachyos"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=cachyos

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

8.  Bash Version:

        BASH_VERSION='5.2.37(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY='wayland-0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX
            en_US.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="C"
            LC_NUMERIC="C"
            LC_TIME="C"
            LC_COLLATE="C"
            LC_MONETARY="C"
            LC_MESSAGES="C"
            LC_PAPER="C"
            LC_NAME="C"
            LC_ADDRESS="C"
            LC_TELEPHONE="C"
            LC_MEASUREMENT="C"
            LC_IDENTIFICATION="C"
            LC_ALL=C

4.  Directories:

    1.  Home:

            /home/sp1cyf0x

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/sp1cyf0x/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/sp1cyf0x/.config/fcitx5`).

5.  Current user:

    The script is run as sp1cyf0x (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.11`

3.  process:

    Found 2 fcitx5 processes:

           2958 fcitx5-wayland-
           2959 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.42`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `2959`.

    Debug information from dbus:

           Group [x11::0] has 0 InputContext(s)
        Group [wayland:] has 11 InputContext(s)
          IC [32a1850ad0fc43999d1e1cb8446da2c5] program:org.kde.konsole frontend:wayland cap:72 focus:1
          IC [cc208d15413049e58f4ab7a843b374be] program:brave-browser frontend:wayland cap:72 focus:0
          IC [b2c9fd2649264fb093469fd32d1bce4f] program:org.kde.konsole frontend:wayland cap:72 focus:0
          IC [74e139294d014a959a7c7a0909629832] program:org.kde.dolphin frontend:wayland cap:1072 focus:0
          IC [0c523c6439fe45e3867ea0798bfe169b] program: frontend:ibus cap:0 focus:0
          IC [2ad909505a474b3da5744647a87616f1] program: frontend:ibus cap:0 focus:0
          IC [537c1bef536840a08eae6b7c412177ff] program: frontend:ibus cap:0 focus:0
          IC [cab1551cc86a4d23853a4357fd1ae9ec] program: frontend:ibus cap:0 focus:0
          IC [25f41f81c3ae45e198043b0f6ae43e4d] program: frontend:ibus cap:0 focus:0
          IC [9d8451e5d1534cfaa85e3f14fcf340df] program: frontend:ibus cap:0 focus:0
          IC [6e4ec7990e0f4365969e55c8de6221c2] program: frontend:wayland cap:72 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS is not set**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM encoding:

    **Your LC_CTYPE is set to C whose encoding is not UTF-8. You may have trouble committing strings using XIM.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt5 built-in Wayland im module if your compositor fully supports text-input protocol used by qt5.**

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt6 built-in Wayland im module if your compositor fully supports text-input protocol used by qt6.**

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx5-unikey-keymap-editor.so`.
    Found fcitx5 qt6 module: `/usr/lib/fcitx5/qt6/libfcitx5-unikey-macro-editor.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

    **It is OK to use gtk built-in Wayland im module if your compositor fully supports text-input protocol used by gtk.**

    **`fcitx5-gtk2-immodule-probing` not found.**

    **`fcitx5-gtk3-immodule-probing` not found.**

    **`fcitx5-gtk4-immodule-probing` not found.**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-2.0`**

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0-32`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0-32 from gtk+-2.24.33

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-2.0-32`**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.43` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0`**

        Found `gtk-query-immodules` for gtk `3.24.43` at `/usr/bin/gtk-query-immodules-3.0-32`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0-32 from gtk+-3.24.43

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0-32`**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`**

        Found immodules cache for gtk `2.24.33` at `/usr/lib32/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0-32 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/usr/lib32/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.43` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.43

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`**

        Found immodules cache for gtk `3.24.43` at `/usr/lib32/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0-32 from gtk+-3.24.43

        **Failed to find fcitx5 in immodule cache at `/usr/lib32/gtk-3.0/3.0.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 3 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 22 enabled addons:

            Bamboo Wrapper For Fcitx 1.0.6
            Classic User Interface 5.1.11
            Clipboard 5.1.11
            DBus 5.1.11
            DBus Frontend 5.1.11
            Emoji 5.1.11
            Fcitx4 Frontend 5.1.11
            IBus Frontend 5.1.11
            Input method selector 5.1.11
            Keyboard 5.1.11
            KDE Input Method Panel 5.1.11
            Status Notifier 5.1.11
            Notification 5.1.11
            Quick Phrase 5.1.11
            Spell 5.1.11
            Unicode 5.1.11
            Unikey Wrapper For Fcitx 5.1.5
            DBus Virtual Keyboard 5.1.11
            Wayland 5.1.11
            Wayland Input method frontend 5.1.11
            XCB 5.1.11
            X Input Method Frontend 5.1.11

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/sp1cyf0x/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=unikey

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=unikey
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Mon Dec  9 14:03:09 +07 2024

2.  `/home/sp1cyf0x/.config/fcitx5/crash.log`:

    `/home/sp1cyf0x/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by Revival8697** [comment]
https://github.com/brave/brave-browser/issues/42761

**Comment by wengxt** [comment]
I tried to test this on both chromium and brave.

chromium works with both v1 and v3
brave can reproduce your issue with v3, but not v1. So it's more likely the bug is triggered on brave side.

text-input-v1 seems better. So for user, I'd suggest you try `--wayland-text-input-version=1`. 

Also, https://issues.chromium.org/issues/40113488#comment127 & https://bugs.kde.org/show_bug.cgi?id=492225 are probably relevant context.
