### ISSUE TITLE
在vscode中快速输入中文时，有些字母将直接以英文输入。

### ISSUE THREAD

**Issue by wzhengsen** [fcitx/fcitx5#1213]
### Steps to Reproduce

[录屏 2024-12-18 00-29-44.webm](https://github.com/user-attachments/assets/afb47c37-302c-48f9-91da-682ca10b65c1)

见以上视频，nihao 的拼音某些字母，如 'o' 等， 有时候没有经过输入法，直接以英文输入了。

### Expected Behavior

应当正确输出“你好你好你好你好……”。

即使拼音输入顺序错误，如错误地输入了“niaho”，也不应该输出英文字母。

在其他应用中，行为是正确的，比如，当前使用的microsoft-edge：

[录屏 2024-12-18 00-23-53.webm](https://github.com/user-attachments/assets/de2b5298-0733-4231-8604-0903a196ccfc)

### Output of fcitx5-diagnose command

# 系统信息:
1.  `uname -a`:

        Linux MSI 6.8.0-50-generic #51-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov  9 17:58:29 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        Distributor ID:	Ubuntu
        Description:	Ubuntu 24.04.1 LTS
        Release:	24.04
        Codename:	noble

3.  `lsb_release -d`:

        Description:	Ubuntu 24.04.1 LTS

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=24.04
        DISTRIB_CODENAME=noble
        DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"

5.  `/etc/os-release`:

        PRETTY_NAME="Ubuntu 24.04.1 LTS"
        NAME="Ubuntu"
        VERSION_ID="24.04"
        VERSION="24.04.1 LTS (Noble Numbat)"
        VERSION_CODENAME=noble
        ID=ubuntu
        ID_LIKE=debian
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        UBUNTU_CODENAME=noble
        LOGO=ubuntu-logo

6.  桌面环境：

    桌面环境为 `gnome3`。

7.  XDG 会话类型：

        XDG_SESSION_TYPE='x11'

8.  Bash 版本：

        BASH_VERSION='5.2.21(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY=''

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+us:2+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105+inet", "us,us", ",", ""

3.  Locale：

    1.  全部可用 locale：

            C
            C.utf8
            POSIX
            zh_CN.utf8
            zh_SG.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LANGUAGE=
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC=zh_CN.UTF-8
            LC_TIME=zh_CN.UTF-8
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY=zh_CN.UTF-8
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER=zh_CN.UTF-8
            LC_NAME=zh_CN.UTF-8
            LC_ADDRESS=zh_CN.UTF-8
            LC_TELEPHONE=zh_CN.UTF-8
            LC_MEASUREMENT=zh_CN.UTF-8
            LC_IDENTIFICATION=zh_CN.UTF-8
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/wzhengsen

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/wzhengsen/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/wzhengsen/.config/fcitx5`)。

5.  当前用户：

    脚本作为 wzhengsen (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: `5.1.7`

3.  进程：

    找到了 2 个 fcitx5 进程：

           2892 fcitx5
           9726 fcitx5-config-q

4.  `fcitx5-remote`:

    `fcitx5-remote` 工作正常。

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.18`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `2892`。

    来自 dbus 的调试信息：

           Group [x11::1] has 8 InputContext(s)
          IC [efaa6e4df29f403497ffb58ec27eb5d6] program:gnome-terminal- frontend:fcitx4 cap:0 focus:1
          IC [df71fc1a1cc14cd4951ebcfd425303b7] program:org.gnome.Nautilus frontend:dbus cap:4000021020 focus:0
          IC [c60eb58ff9d34c229d36e2aec30dccd5] program:org.gnome.Nautilus frontend:dbus cap:4000000020 focus:0
          IC [6a2bffcf88524fc1b52759f0cd7afca5] program:msedge frontend:fcitx4 cap:0 focus:0
          IC [56e166caa9bc4d358adc4c7be74917b7] program:fcitx5-config-qt frontend:dbus cap:16000800060 focus:0
          IC [7d9e8285ca4a4b88bba1aaa783ddd4c6] program:code frontend:xim cap:4000000000 focus:0
          IC [9d68e3ce15a54600bebd282cf79ee2ed] program: frontend:dbus cap:0 focus:0
          IC [9411f1b08cf24a9bbab9e63d3aad22c6] program: frontend:ibus cap:40 focus:0
        Input Context without group

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

    **`kcmshell5` 未找到.**

# 前端设置：
此脚本检查的环境变量仅能显示当前命令行的环境。仍有可能您的环境并没有应用于整个桌面。您可以通过使用命令对某个无法正常工作的进程使用命令 `xargs -0 -L1 /proc/$PID/environ` 检查此进程的实际的环境变量。

## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    Xim 服务的名称与环境变量中设置的相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

    **`fcitx5-qt4-immodule-probing` 未找到.**

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

    使用 fcitx5-qt5-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

    使用 fcitx5-qt6-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt 输入法模块文件：

    找到了未知的 fcitx qt 模块：`/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`。
    找到了 fcitx5 的 qt5 输入法模块：`/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了 fcitx5 的 qt6 输入法模块：`/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了 fcitx5 qt6 模块：`/lib/x86_64-linux-gnu/fcitx5/qt6/libfcitx-quickphrase-editor5.so`。
    找到了未知的 fcitx qt 模块：`/lib/x86_64-linux-gnu/fcitx/qt/libfcitx-quickphrase-editor5.so`。

    下列错误也许并不准确，因为对路径所对应的 Qt 版本的猜测取决于发行版如何打包 Qt。如果您不使用任何对应版本的 Qt 程序，或者在 Wayland 下使用 Qt 的 text-input 支持，下列错误也不是严重问题。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

    使用 fcitx5-gtk2-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        GTK_IM_MODULE=fcitx

    使用 fcitx5-gtk3-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        GTK_IM_MODULE=fcitx

    使用 fcitx5-gtk4-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        GTK_IM_MODULE=fcitx

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`。**

        **无法找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        **无法找到 gtk 3 的 `gtk-query-immodules`。**

        **无法找到 gtk 3 的 fcitx5 输入法模块。**

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        在 `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0t64/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        在 `/lib/i386-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.41` 的输入法模块缓存。
        版本行：

            # Created by /usr/lib/i386-linux-gnu/libgtk-3-0t64/gtk-query-immodules-3.0 from gtk+-3.24.41

        **无法输入法模块缓存 `/lib/i386-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 中找到 fcitx5**

        在 `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.41` 的输入法模块缓存。
        版本行：

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0t64/gtk-query-immodules-3.0 from gtk+-3.24.41

        已找到 gtk `3.24.41` 的 fcitx5 输入法模块。

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 29 个已启用的插件：

            Simplified and Traditional Chinese Translation 5.1.3
            Classic User Interface 5.1.7
            Clipboard 5.1.7
            Cloud Pinyin 5.1.3
            DBus 5.1.7
            DBus Frontend 5.1.7
            Emoji 5.1.7
            Fcitx4 Frontend 5.1.7
            Full width character 5.1.3
            IBus Frontend 5.1.7
            Lua IME API 5.0.12
            Input method selector 5.1.7
            Keyboard 5.1.7
            KDE Input Method Panel 5.1.7
            Lua Addon Loader 5.0.12
            Status Notifier 5.1.7
            Notification 5.1.7
            Pinyin 5.1.3
            Extra Pinyin functionality 5.1.3
            Punctuation 5.1.3
            Quick Phrase 5.1.7
            Spell 5.1.7
            Table 5.1.3
            Unicode 5.1.7
            DBus Virtual Keyboard 5.1.7
            Wayland 5.1.7
            Wayland Input method frontend 5.1.7
            XCB 5.1.7
            X Input Method Frontend 5.1.7

    2.  找到了 0 个被禁用的插件：

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 3 个已启用的用户界面插件：

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

    Kimpanel 进程:

           3041 /usr/bin/gnome-shell

## 输入法：
1.  `/home/wzhengsen/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=默认
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=pinyin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=pinyin
        # Layout
        Layout=

        [GroupOrder]
        0=默认

# 日志：
1.  `date`:

        2024年 12月 18日 星期三 00:25:42 CST

2.  `/home/wzhengsen/.config/fcitx5/crash.log`:

    `/home/wzhengsen/.config/fcitx5/crash.log` 未找到.

**警告：fcitx5-diagnose 的输出可能包含敏感信息，包括发行版名称，内核版本，正在运行的程序名称等。**

**尽管这些信息对于开发者诊断问题有帮助，请在公开发送到在线网站前检查并且根据需要移除的对应信息。**

**Comment by wengxt** [comment]
vscode没有用fcitx的gtk im module

你的vscode是怎么安装的

**Comment by wzhengsen** [comment]
@wengxt snap应用中心安装的

**Comment by wengxt** [comment]
vscode 的 snap 里面没有 ibus 或者 fcitx 的 im modules ，在 chromium 或者 electron 上使用 xim 的 immodules 就会有这种现象
![图片](https://github.com/user-attachments/assets/f27b7356-e282-4583-8438-e8a0d83a16ed)

建议用官网的 deb 安装，它可以使用系统原生的 im modules

或者 flatpak 安装，flatpak 的共享 runtime 里有 fcitx 的 im module
