### ISSUE TITLE
Ghostty can not activate fcitx when run with GTK_IM_MODULE=fcitx

### ISSUE THREAD

**Issue by ttys3** [fcitx/fcitx5#1218]
### Summary

Ghostty version: main branch latest version

OS: Fedora Linux 41 Workstation Edition

DE:  GNOME 47

gtk version: 4.16.5

Window System: Wayland

related env: 

```ini
LANG=en_US.UTF-8


GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus
```

`/etc/locale.conf` content:

```
LANG="en_US.UTF-8"
```

run `env GTK_IM_MODULE=fcitx ghostty` not work, input method can not activated

if we run `fcitx5 -D -r --verbose 'default=4,key_trace=5'` and then press `ctrl+shift` to switch input method, we can see that fcitx got the key event, but input method not activate. I do not know if this info is helpful

## workaround

1. using `env GTK_IM_MODULE=must-not-exists-im-module ghostty` does the tricks, and somehow, it works. but this is not the right solution

2. run with `unset GTK_IM_MODULE &&  ghostty` works fine

3. run with `env GTK_IM_MODULE=wayland && ghostty` works fine

## why the workaround is not a good solution?

we still have problems when run with `env GTK_IM_MODULE=wayland && ghostty`

the problem is, when user run a non-wayland native app, the app it self still need `GTK_IM_MODULE=fcitx`,  and `GTK_IM_MODULE=wayland` will cause the app panic.

for example, running vscode from Ghostty, since vscode currently default to X11 mode, so it runs as XWayland client

--------------------------

related:  https://github.com/ghostty-org/ghostty/discussions/3628

**Comment by wengxt** [comment]
works for me.

![图片](https://github.com/user-attachments/assets/436da085-50c4-4ee5-98f0-a4313a36b009)

I'm using KDE on Arch.

```
Group [wayland:] has 12 InputContext(s)
  IC [87be87fb6b104c91a0c54d481b4c0602] program: frontend:dbus cap:4001000032 focus:0
  IC [f40f3aa32fb64bbbacdec22d5326398b] program: frontend:dbus cap:c001000032 focus:1
```

Debug info shows it can load GTK_IM_MODULE=fcitx correctly.

Also works for GTK_IM_MODULE=wayland, but not preedit.

```
WAYLAND_DEBUG=1 ghostty 2>&1 | grep text_input
```

Shows correct interaction with text_input protocol. So it's likely a ghostty issue between gtk's wayland im context and ghostty, not related to fcitx.

One thing to notice is that wayland im module sets a different preedit style (pango attr), which might be the trigger to the issue.

As for your GTK_IM_MODULE=fcitx, are you sure you installed fcitx's gtk4 im module? I compiled ghostty from source so it's definitely using host system gtk im module.

I can see for fedora https://pkgs.org/search/?q=fcitx5-gtk4 it's a separate package.

**Comment by wengxt** [comment]
Also see my reply on https://github.com/fcitx/fcitx5/issues/1218#issuecomment-2564442499

**Comment by ttys3** [comment]
yes, I'm very sure that I have related IM module installed

```shell
❯ sudo dnf list --installed | grep fcitx 
fcitx5.x86_64                                        5.1.11-1.fc41                              updates-testing
fcitx5-chinese-addons.x86_64                         5.1.7-1.fc41                               updates-testing
fcitx5-chinese-addons-data.noarch                    5.1.7-1.fc41                               updates-testing
fcitx5-configtool.x86_64                             5.1.7-1.fc41                               updates-testing
fcitx5-data.noarch                                   5.1.11-1.fc41                              updates-testing
fcitx5-gtk.x86_64                                    5.1.3-2.fc41                               @commandline
fcitx5-gtk2.x86_64                                   5.1.3-2.fc41                               @commandline
fcitx5-gtk3.x86_64                                   5.1.3-2.fc41                               @commandline
fcitx5-gtk4.x86_64                                   5.1.3-2.fc41                               @commandline
fcitx5-libs.x86_64                                   5.1.11-1.fc41                              updates-testing
fcitx5-lua.x86_64                                    5.0.13-2.fc41                              @commandline
fcitx5-mozc.x86_64                                   2.17.2102.102.1-36.20230508git242b4f7.fc41 fedora
fcitx5-qt-libfcitx5qt5widgets.x86_64                 5.1.8-3.fc41                               updates
fcitx5-qt-libfcitx5qt6widgets.x86_64                 5.1.8-3.fc41                               updates
fcitx5-qt-libfcitx5qtdbus.x86_64                     5.1.8-3.fc41                               updates
fcitx5-qt-qt5gui.x86_64                              5.1.8-3.fc41                               updates
fcitx5-qt-qt6gui.x86_64                              5.1.8-3.fc41                               updates
fcitx5-qt5.x86_64                                    5.1.8-3.fc41                               updates
fcitx5-qt6.x86_64                                    5.1.8-3.fc41                               updates
fcitx5-table-extra.noarch                            5.1.6-4.fc41                               @commandline
```

```
ls /usr/lib64/gtk-4.0/4.0.0/immodules
libim-fcitx5.so  libim-ibus.so
```

```shell
env GTK_IM_MODULE=fcitx WAYLAND_DEBUG=1 ghostty 2>&1 | grep text_input 
[ 458468.375] {Default Queue} wl_registry#2.global(26, "zwp_text_input_manager_v3", 1)
[ 458514.351] wl_registry#44.global(26, "zwp_text_input_manager_v3", 1)
[ 458569.653] wl_registry#48.global(26, "zwp_text_input_manager_v3", 1)
```

**Comment by wengxt** [comment]
@ttys3 thanks. I didn't realize that you mean only "ctrl+shift" & "shift" not working. See my new reply https://github.com/ghostty-org/ghostty/discussions/3628#discussioncomment-11688161 on investigation

As for your workaround:

You can check on https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#GTK_IM_MODULE about some alternative way to set gtk im module (via gtk config file), this allows gtk to use different gtk im module for x, xwayland & wayland.

Also, if you use GTK_IM_MODULE=wayland, you can use Ctrl+Alt+P to quickly disable embedded preedit, as a workaround, so fcitx will display preedit in its own window, not a perfect solution. but allow you to use it.

You may also set env var FCITX_NO_PREEDIT_APPS. This is a comma separated regular expression. BTW, default value is `gvim.*,wps.*,wpp.*,et.*`, you may make ghostty disable embedded preedit permanent by set this value.

From what I observe, `gvim.*,wps.*,wpp.*,et.*,com.mitchellh.ghostty` should work. You can also check how fcitx resolve the client name via (check "program:" of focus:1 entry when you have focus in ghostty):

```
dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
```

**Comment by ttys3** [comment]
> @ttys3 thanks. I didn't realize that you mean only "ctrl+shift" & "shift" not working.

Yes, I have already seen that reply. Thank you.

my bad: I did not clearly describe the issue. I have updated the issue's description to avoid confusion.
