### ISSUE TITLE
首次启动会卡5s左右，终端退出或者pkill fcitx5终端直接卡死。

### ISSUE THREAD

**Issue by Delayless** [fcitx/fcitx5#122]
## 问题描述
如果设置了fcitx5开机启动项的话解锁之后会卡个5s左右
然后如果使用中文，第一次输入中文的时候也会卡2s左右
当然都只有开机后第一次，之后就非常nice了。

## 相关信息
我尝试在终端打开fcitx5（而不是后台）,发现卡在输出loaded addon ibusfrontend之前(dbus之后)
![image](https://user-images.githubusercontent.com/42591058/93991810-48c9ff80-fdbf-11ea-8cef-b17c8aa30312.png)
当我按Ctrl+c关闭程序的话，终端会直接卡死。如果是后台运行的fcitx5，`pkill fcitx5`也会卡死。
![image](https://user-images.githubusercontent.com/42591058/93991992-934b7c00-fdbf-11ea-843c-54fcf52c743f.png)
我看到您在别的issue里面提到看sysprof,所以我提前截了图，不知道对我解决问题有帮助没有
![image](https://user-images.githubusercontent.com/42591058/93964560-777db100-fd92-11ea-9f0e-85098596b1b8.png)

**Comment by wengxt** [comment]
先杀掉 fcitx5
用 xterm（重要），然后 gdb -r fcitx5 --disable xim -r，在你说觉得卡死的地方 ctrl c 然后执行 thread apply all bt

第一次输入中文之前卡一下是加载数据，你电脑比较慢？…

**Comment by Delayless** [comment]
gdb没有--disable诶，我看了gdb的manual还谷歌了好久，实在不好意思，gdb我只稍微了解了调试源码，没调试过进程。

**Comment by Delayless** [comment]
![image](https://user-images.githubusercontent.com/42591058/94336010-46131880-0012-11eb-880c-eae4abb642e0.png)
红线是我执行了的命令（除了最后一条），请问是什么原因导致的启动慢呢？

另外第一次输入中文卡的问题，应该不是我电脑慢吧， windows10下跑win7虚拟机都不怎么卡，固态跑物理Manjaro应该不至于卡吧。这个问题能够解决最好实在解决不了倒也算了。
主要解决的是启动卡那个问题，因为这个问题我都没把fcitx5加入启动项了，挺麻烦的，希望能够解决，谢谢您。

**Comment by wengxt** [comment]
可是在gdb看起来到这里并没有卡吧？我看时间都在一秒以内，这时候不能在程序里面输入么

**Comment by wengxt** [comment]
close because no update from reporter.

**Comment by Delayless** [comment]
@wengxt 知道问题出在哪了，家目录有完整的.Xmodmap。
可以删除该文件或者只保留修改了的keymap。

不过我也是无意中看到别人帖子解决的，想请教一下您有什么办法或者思路可以定位到问题出在这个文件吗？

**Comment by wengxt** [comment]
这个不太有办法，因为卡的不是 fcitx 自己，是 X …… Xmodmap 是很慢的

建议不要用 xmodmap ，用 xkb option 之类

**Comment by Delayless** [comment]
> 

恩，后来我用的都是setxkbmap，xmodmap是最开始用的，太久没用了，久到我自己都忘了有这么个文件在了，我还放在我的dotfiles了，换电脑还是一样(笑哭)。
anyway，非常感谢你！！
