### ISSUE TITLE
第四码的字符有时候会自己上屏

### ISSUE THREAD

**Issue by thallium** [fcitx/fcitx5#124]
比如说我要打“mubn",有时候会出现n上屏但mub还留在候选框中的情况。

**Comment by wengxt** [comment]
感觉是没安装 im module

**Comment by thallium** [comment]
im module是什么？求解释

**Comment by wengxt** [comment]
https://github.com/fcitx/fcitx5-gtk/ https://github.com/fcitx/fcitx5-qt

以及设置对环境变量 https://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-hans

**Comment by thallium** [comment]
现在貌似没问题了，谢谢你！

**Comment by wanghuibin0** [comment]
我都设置好了啊，怎么还会遇到这个问题
