### ISSUE TITLE
关于「纵行候选字列表」的建议

### ISSUE THREAD

**Issue by jasonvenn** [fcitx/fcitx5#126]
现有候选字列表的「垂直」形式固然好，但我们想要更符合中文传统排列布局的候选窗口，以此契合传统书法与古籍「从右至左，从上至下」的文字排列方式。

设想：
![圖](https://user-images.githubusercontent.com/40714226/94672419-d4a3d480-0347-11eb-8b04-e81b66700115.png)

特此建议，望早日回复。

**Comment by Hulenkius** [comment]
臣附議

**Comment by wengxt** [comment]
没有什么实质意义，不考虑。
