### ISSUE TITLE
您好，fcitx5 不支持在 foxit reader 2.4.4.0911 中进行中文输入

### ISSUE THREAD

**Issue by archpython** [fcitx/fcitx5#131]
您好，首先感谢辛苦的制作和维护。fcitx5 不支持在 foxit reader 2.4.4.0911 中进行中文输入。fcitx5 安装了community/fcitx5-chinese-addons 和 community/manjaro-asian-input-support-fcitx5 2020.08-1 模块，在金山PDF中可以顺利输入中文，但在 foxit reader 中不可以，按网上修改了配置也没有成功。请问，能否有解决方法？

**Comment by wengxt** [comment]
Duplicate of #72
