### ISSUE TITLE
native wayland下没有候选框

### ISSUE THREAD

**Issue by ziyouwa** [fcitx/fcitx5#132]
编程方面我是小白，只是提出这个疑问：是否是因为wayland的支持没有更新到最新，导致没有候选框的？之前的issue也有人遇到跟我同样的问题

我的环境是Gentoo + sway + termite+firefox, 关闭了xwayland的。

至于是否纯原生wayland, 其实有个很简单的方法去识别，ps -ef |grep X, 结果如果有XWayland，那就不是。

我尝试了clone源码编译，发现一个异常：

> -- Found WaylandScanner: /usr/bin/wayland-scanner  
-- Found WaylandProtocols: //usr/share/wayland-protocols (found version "") 

这里并没有正确识别我的wayland protocols的版本号。
我发现extra-cmake-modules 5.75.0中有这个cmake文件，就替换了cmake目录下的FindWaylandProtocols.cmake.替换之后能正常识别版本了：

> -- Found WaylandScanner: /usr/bin/wayland-scanner  
-- Found WaylandProtocols: //usr/share/wayland-protocols (found version "1.20") 

但是编译报错：

> [ 28%] Built target Fcitx5WaylandCore
make[2]: *** 没有规则可制作目标“/unstable/input-method/input-method-unstable-v1.xml”，由“src/lib/fcitx-wayland/input-method/wayland-input-method-unstable-v1-client-protocol.h” 需求。 停止。
make[1]: *** [CMakeFiles/Makefile2:1260：src/lib/fcitx-wayland/input-method/CMakeFiles/Fcitx5WaylandInputMethod.dir/all] 错误 2
make: *** [Makefile:160：all] 错误 2

**Comment by wengxt** [comment]
目前就是没有。编译感觉是你用的代码不够新？指编译错误

因为用 wayland 画窗口如果输入法是走 dbus 没有意义，没有办法随意定位窗口。
