### ISSUE TITLE
fcitx5不兼容旧版码表了吗？

### ISSUE THREAD

**Issue by chwt163** [fcitx/fcitx5#133]
以前的码表是mb文件，现在是dict文件，我把旧的码表改成dict扩展名，放到 /usr/share/libime/ 以及 ~/.config/fcitx5/table 里面，重启fcitx5，都识别不了。
另外，自带的那个两笔输入法，不能直接输入逗号、句号等标点符号，建议更新新版的超强两笔码表。超强两笔官网：http://fds8866.ys168.com/

**Comment by wengxt** [comment]
txt 格式方面兼容，你可以先转换成 mb2txt 再用 libime_tabledict 转换
或者用 libime_migrate_fcitx4_table 转换
