### ISSUE TITLE
Feature request: (1) 讓不同群組可以有不同的快捷鍵 (2) 讓fcitx5-remote可以切換輸入法群組

### ISSUE THREAD

**Issue by axzxc1236** [fcitx/fcitx5#138]
(1) 我想要讓預設群組可以用shift開關輸入法  令一個群組則不行
現在所有群組都採用全域的快捷鍵...無法做到讓不同群組有不同快捷鍵

(2) 我想要讓特定程式在啟動時順便切換輸入法群組
現在的fcitx5-remote沒有相關的功能
嘗試用xdotool模擬快捷鍵過了  在沒有選取文字輸入框時切換群組的快捷鍵沒有作用  (但還是可以用工具列圖示手動切換)

**Comment by wengxt** [comment]
第一个要求不太想要默认支持，但你可以自己单独实现一个 addon 来做切换。

**Comment by wengxt** [comment]
fcitx5-remote 切换的功能已添加 https://github.com/fcitx/fcitx5/commit/0045b4ab94fca4c906212edba6253e2610364355

**Comment by axzxc1236** [comment]
最後我用了兩個.sh檔案達到我的要求 (控制shift鍵能不能使用)  得自己多做一些設定在需要的時間呼叫

fcitx_shift_disable.sh
```
#! /usr/bin/sh
sed -i s/1=Shift+Shift_L/#1=Shift+Shift_L/ ~/.config/fcitx5/config
sed -i s/2=Shift+Shift_R/#2=Shift+Shift_R/ ~/.config/fcitx5/config
fcitx5-remote -r 
```
fcitx_shift_enable.sh
```
#! /usr/bin/sh
sed -i s/#1=Shift+Shift_L/1=Shift+Shift_L/ ~/.config/fcitx5/config
sed -i s/#2=Shift+Shift_R/2=Shift+Shift_R/ ~/.config/fcitx5/config
fcitx5-remote -r
```
