### ISSUE TITLE
Question: Remove Words?

### ISSUE THREAD

**Issue by qingxiang-jia** [fcitx/fcitx5#141]
For pinyin, sometimes I type a wrong word, Fcitx 5 remembers it. Is there anyway to remove it? (I checked Fcitx 5 Configuration tool and didn't see it as an option. I also searched among the issues and didn't get information.)

Thanks!

**Comment by Aloxaf** [comment]
You can use Ctrl-7

**Comment by qingxiang-jia** [comment]
Thank you! Indeed it works! I will close the issue.
