### ISSUE TITLE
problem in `rime-addon.conf.in`

### ISSUE THREAD

**Issue by lebensterben** [fcitx/fcitx5#147]
Currently in this line would result in an error when calling "fcitx5-diagnose"
https://github.com/fcitx/fcitx5-rime/blob/c90df10ac5eebafd5f633544ae858702a6b275f7/src/rime-addon.conf.in#L5

Because it will look for "export:rime.so" instead of the correct "rime.so".
To fix this, we just need to remove "export:" from the field of "Library".

**Comment by wengxt** [comment]
Export is expected, it has special meaning. The problem is that fcitx5-diagnose doesn't recognize it.
