### ISSUE TITLE
ubuntu new folder can't see chinese ime

### ISSUE THREAD

**Issue by xingwozhonghua** [fcitx/fcitx5#149]
System Info:
uos@ubuntu:~/Desktop$ fcitx5-diagnose
System Info:

    uname -a:

    Linux ubuntu 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

    lsb_release -a:

    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.1 LTS
    Release:	20.04
    Codename:	focal

    lsb_release -d:

    Description:	Ubuntu 20.04.1 LTS

    /etc/lsb-release:

    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=20.04
    DISTRIB_CODENAME=focal
    DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

    /etc/os-release:

    NAME="Ubuntu"
    VERSION="20.04.1 LTS (Focal Fossa)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 20.04.1 LTS"
    VERSION_ID="20.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=focal
    UBUNTU_CODENAME=focal

    Desktop Environment:

    Desktop environment is gnome3.

    Bash Version:

    BASH_VERSION='5.0.17(1)-release'

Environment:

    DISPLAY:

    DISPLAY=':0'

    Keyboard Layout:

        setxkbmap:

        xkb_keymap {
        	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
        	xkb_types     { include "complete"	};
        	xkb_compat    { include "complete"	};
        	xkb_symbols   { include "pc+us+cn:2+us:3+inet(evdev)"	};
        	xkb_geometry  { include "pc(pc105)"	};
        };

        xprop:

        _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us,cn,us", ",,", ""

    Locale:

        All locale:

        C
        C.UTF-8
        en_AG
        en_AG.utf8
        en_AU.utf8
        en_BW.utf8
        en_CA.utf8
        en_DK.utf8
        en_GB.utf8
        en_HK.utf8
        en_IE.utf8
        en_IL
        en_IL.utf8
        en_IN
        en_IN.utf8
        en_NG
        en_NG.utf8
        en_NZ.utf8
        en_PH.utf8
        en_SG.utf8
        en_US.utf8
        en_ZA.utf8
        en_ZM
        en_ZM.utf8
        en_ZW.utf8
        POSIX
        zh_CN.utf8
        zh_SG.utf8

        Current locale:

        LANG=zh_CN.UTF-8
        LANGUAGE=zh_CN:en_US:en
        LC_CTYPE="zh_CN.UTF-8"
        LC_NUMERIC=zh_CN.UTF-8
        LC_TIME=zh_CN.UTF-8
        LC_COLLATE="zh_CN.UTF-8"
        LC_MONETARY=zh_CN.UTF-8
        LC_MESSAGES="zh_CN.UTF-8"
        LC_PAPER=zh_CN.UTF-8
        LC_NAME=zh_CN.UTF-8
        LC_ADDRESS=zh_CN.UTF-8
        LC_TELEPHONE=zh_CN.UTF-8
        LC_MEASUREMENT=zh_CN.UTF-8
        LC_IDENTIFICATION=zh_CN.UTF-8
        LC_ALL=

    Directories:

        Home:

        /home/uos

        ${XDG_CONFIG_HOME}:

        Environment variable XDG_CONFIG_HOME is not set.

        Current value of XDG_CONFIG_HOME is ~/.config (/home/uos/.config).

        Fcitx5 Settings Directory:

        Current fcitx5 settings directory is ~/.config/fcitx5 (/home/uos/.config/fcitx5).

    Current user:

    The script is run as uos (1000).

Fcitx State:

    executable:

    Found fcitx5 at /usr/local/bin/fcitx5.

    version:

    Fcitx version: 5.0.1

    process:

    Found 1 fcitx5 process:

       2889 fcitx5

    fcitx5-remote:

    fcitx5-remote works properly.

    DBus interface:

    Using dbus-send to check dbus.

    Owner of DBus name org.fcitx.Fcitx5 is :1.105.

    PID of DBus name org.fcitx.Fcitx5 owner is 2889.

Fcitx Configure UI:

    Config Tool Wrapper:

    Found fcitx5-configtool at /usr/local/bin/fcitx5-configtool.

    Config GUI for qt:

    Found fcitx5-config-qt at /usr/bin/fcitx5-config-qt.

    Config GUI for kde:

    kcmshell5 not found.

Frontends setup:
Xim:

    ${XMODIFIERS}:

    Environment variable XMODIFIERS is "@im=fcitx5" instead of "@im=fcitx". Please check if you have exported it incorrectly in any of your init files.

    Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add export XMODIFIERS=@im=fcitx to your ~/.xprofile. See Input Method Related Environment Variables: XMODIFIERS.

    Xim Server Name from Environment variable is fcitx5.

    XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

Qt:

    qt4 - ${QT4_IM_MODULE}:

    Environment variable QT_IM_MODULE is "fcitx5" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.
    You may have trouble using fcitx in qt4 programs.

    Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add export QT_IM_MODULE=fcitx to your ~/.xprofile. See Input Method Related Environment Variables: QT_IM_MODULE.

    qt5 - ${QT_IM_MODULE}:

    Environment variable QT_IM_MODULE is "fcitx5" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.
    You may have trouble using fcitx in qt5 programs.

    Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add export QT_IM_MODULE=fcitx to your ~/.xprofile. See Input Method Related Environment Variables: QT_IM_MODULE.

    Qt IM module files:

    Found unknown fcitx5 qt module: /lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/kcm_fcitx.so.
    Found unknown fcitx5 qt module: /lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libfcitx-quickphrase-editor5.so.
    Found unknown fcitx5 qt module: /lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/platforminputcontexts/libfcitxplatforminputcontextplugin.so.
    Found unknown fcitx5 qt module: /lib/x86_64-linux-gnu/qt5/plugins/kcm_fcitx.so.
    Found unknown fcitx5 qt module: /lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so.
    Found unknown fcitx5 qt module: /lib/x86_64-linux-gnu/fcitx/qt/libfcitx-quickphrase-editor5.so.
    Found unknown fcitx5 qt module: /lib/x86_64-linux-gnu/fcitx/qt/libfcitx-libpinyin-dictmanager.so.
    Found fcitx5 qt5 module: /usr/local/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so.
    Cannot find fcitx5 input method module for Qt4.
    Cannot find fcitx5 input method module for Qt5.

Gtk:

    gtk - ${GTK_IM_MODULE}:

    Environment variable GTK_IM_MODULE is "fcitx5" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.
    You may have trouble using fcitx in gtk programs.

    Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add export GTK_IM_MODULE=fcitx to your ~/.xprofile. See Input Method Related Environment Variables: GTK_IM_MODULE.

    gtk-query-immodules:

        gtk 2:

        Cannot find gtk-query-immodules for gtk 2

        Cannot find fcitx5 im module for gtk 2.

        gtk 3:

        Cannot find gtk-query-immodules for gtk 3

        Cannot find fcitx5 im module for gtk 3.

    Gtk IM module cache:

        gtk 2:

        Found immodules cache for gtk 2.24.32 at /lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache.
        Version Line:

        # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.32

        Failed to find fcitx5 in immodule cache at /lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache

        Cannot find fcitx5 im module for gtk 2 in cache.

        gtk 3:

        Found immodules cache for gtk 3.24.20 at /lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache.
        Version Line:

        # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.20

        Failed to find fcitx5 in immodule cache at /lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache

        Cannot find fcitx5 im module for gtk 3 in cache.

    Gtk IM module files:

        gtk 2:

        All found Gtk 2 immodule files exist.

        gtk 3:

        All found Gtk 3 immodule files exist.

Configuration:
Fcitx Addons:

    Addon Config Dir:

    Found fcitx5 addon config directory: /usr/local/share/fcitx5/addon.

    Addon List:

        Found 25 enabled addons:

        Simplified and Traditional Chinese Translation
        Classic User Inteface
        Clipboard
        Cloud Pinyin
        DBus
        DBus Frontend
        Emoji
        Full width character
        IBus Frontend
        Input method selector
        Keyboard
        KDE Input Method Panel
        Status Notifier
        Notification
        Pinyin
        Extra Pinyin functionality
        Punctuation
        Quick Phrase
        Spell
        Table
        Unicode
        Wayland
        Wayland Input method frontend
        XCB
        X Input Method Frontend

        Found 0 disabled addons:

    Addon Libraries:

    All libraries for all addons are found.

    User Interface:

    Found 2 enabled user interface addons:

    Classic User Inteface
    KDE Input Method Panel

Log:

    date:

    2020年 11月 19日 星期四 03:34:36 PST

    /home/uos/.config/fcitx5/crash.log:

    /crash.log not found.

它的窗口是模态的。
![](https://user-images.githubusercontent.com/69958796/99659121-5cca6e80-2a9b-11eb-9be7-d20f04db2edb.png)

重命名桌面文件夹的时候显示输入法信息通知框是在下面的。
![](https://user-images.githubusercontent.com/69958796/99660835-e418e180-2a9d-11eb-9091-3f6fb101dbaa.png)

**Comment by wengxt** [comment]
gnome 3，没别的办法，只能用  https://extensions.gnome.org/extension/261/kimpanel/
