### ISSUE TITLE
how to use it in Fedora33 

### ISSUE THREAD

**Issue by tlsalex** [fcitx/fcitx5#153]
**Describe the bug**
I am Chinese , I wan to use fcitx5 on Fedora33, Dan wo bu zhi dao ru he pei zhi ta.

**To Reproduce**
   dnf install fcitx5 fcitx5-gtk fcitx5-qt fcitx5-configtool fcitx5-chinese-addons
   dnf install fcitx5-autostart

**Expected behavior**

**Desktop (please complete the following information):**
 - Desktop: GNOME
 - Display server type: I don't know how to check server type
 - The output of fcitx5-diagnose if possible.-- installation without problem. 

**Additional context**
I can launch fcitx5-configuration tool, after add Chinese input to system. and tried to type some Chinese words, however , it did not work, please provides some documents about the setup.

![image](https://user-images.githubusercontent.com/36788337/99906651-49c1d380-2d13-11eb-93cf-b21f0e05019a.png)

**Comment by firogh** [comment]
Add 'Pinyin' to 'Input method' from 'Available Input Method'.

**Comment by wengxt** [comment]
that "keyboard -" is not actual pinyin (I know it's a little bit confusing), search for pinyin

**Comment by tlsalex** [comment]
thank you!
