### ISSUE TITLE
deepin build failed

### ISSUE THREAD

**Issue by leemeans** [fcitx/fcitx5#155]
**Describe the bug**
tring to build fcitx5 on deepin v20, but it failed with those messages:
cannot locate ITS rules for /home/lee/Gitprojects/fcitx5rime/fcitx5/data/org.fcitx.Fcitx5.metainfo.xml.in

**To Reproduce**
1. install all dependcy and run cmake
2. mkdir build; cd build; cmake ..
3. make -j10

**Expected behavior**

**Desktop (please complete the following information):**
 - Desktop: DDE
 - Display server type: X11
 - The output of fcitx5-diagnose if possible.
bash: fcitx5-diagnose: command not found

**Additional context**
(! 2043)-> make org.fcitx.Fcitx5.metainfo.xml.in-fmt
Generating org.fcitx.Fcitx5.metainfo.xml
/usr/bin/msgfmt: cannot locate ITS rules for /home/lee/Gitprojects/fcitx5rime/fcitx5/data/org.fcitx.Fcitx5.metainfo.xml.in
make[3]: *** [data/CMakeFiles/org.fcitx.Fcitx5.metainfo.xml.in-fmt.dir/build.make:71: data/org.fcitx.Fcitx5.metainfo.xml] Error 1
make[2]: *** [CMakeFiles/Makefile2:2835: data/CMakeFiles/org.fcitx.Fcitx5.metainfo.xml.in-fmt.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2847: data/CMakeFiles/org.fcitx.Fcitx5.metainfo.xml.in-fmt.dir/rule] Error 2
make: *** [Makefile:851: org.fcitx.Fcitx5.metainfo.xml.in-fmt] Error 2

**Comment by wengxt** [comment]
where is the message?

**Comment by leemeans** [comment]
sorry, just under editing.

**Comment by leemeans** [comment]
here is the error logs:(! 2043)-> make org.fcitx.Fcitx5.metainfo.xml.in-fmt
Generating org.fcitx.Fcitx5.metainfo.xml
/usr/bin/msgfmt: cannot locate ITS rules for /home/lee/Gitprojects/fcitx5rime/fcitx5/data/org.fcitx.Fcitx5.metainfo.xml.in
make[3]: *** [data/CMakeFiles/org.fcitx.Fcitx5.metainfo.xml.in-fmt.dir/build.make:71: data/org.fcitx.Fcitx5.metainfo.xml] Error 1
make[2]: *** [CMakeFiles/Makefile2:2835: data/CMakeFiles/org.fcitx.Fcitx5.metainfo.xml.in-fmt.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2847: data/CMakeFiles/org.fcitx.Fcitx5.metainfo.xml.in-fmt.dir/rule] Error 2
make: *** [Makefile:851: org.fcitx.Fcitx5.metainfo.xml.in-fmt] Error 2

**Comment by wengxt** [comment]
Try install appstream?

**Comment by leemeans** [comment]
Then, below error shows.
[error.log](https://github.com/fcitx/fcitx5/files/5587297/error.log)

**Comment by wengxt** [comment]
the bug is in your compiler (An old version of gcc). If you can't update, you may try clang / clang++ to see if it helps.

**Comment by leemeans** [comment]
Solved, thanks very much.

**Comment by chenshijie-uos** [comment]
deepin how to use fcitx5.

https://shimo.im/docs/wV3RxPPqDCdhHvrv

后面还会更新.
