### ISSUE TITLE
fcitx 托盘icon 

### ISSUE THREAD

**Issue by wbmins** [fcitx/fcitx5#157]
**Describe the bug**
If the problem is about you can not use fcitx in certain application, or the input window is placed in wrong place, be sure to include which application is being typed, and the output of fcitx5-diagnose command.
**Additional context**
![image](https://user-images.githubusercontent.com/36689025/100230977-576c9880-2f61-11eb-8788-e6b219db2854.png)
polybar 托盘显示的是us, ~/.local/share/icon/的主题里添加了input-keyboard.png.没有读取

**Comment by wengxt** [comment]
us is not the icon. is the text that rendered by fcitx.

**Comment by wengxt** [comment]
emm, I just rechecked code, it should shown a input-keyboard

But I doubt there's some problem with theme detection, or you place the icon file in the wrong place.

BTW, you'll need to restart fcitx to make it render the new icon.

**Comment by wbmins** [comment]
我放在 .local/share/icons/AWEL-Lumine/apps/16/input-keyboard.png和.local/share/icons/AWEL-Lumine/panel/16/input-keyboard.png,它是读取不到的。

**Comment by RRRRRm** [comment]
@wbmins 请问找到解决方案了吗

**Comment by wengxt** [comment]
https://github.com/fcitx/fcitx5/commit/351e888de66b754ea734e687d964f2986363f8e2 可能这个能 fix 吧？非标准桌面之前会返回的默认图标主题是 hardcode 的，现在会尝试读 gtk 配置的图标

**Comment by wbmins** [comment]
非常感谢@wengxt！
@RRRRRm 已经修复，可以读取家目录.local/share/icons/主题/里面的名字为input-keyboard的png或svg图标。

**Comment by wbmins** [comment]
> [351e888](https://github.com/fcitx/fcitx5/commit/351e888de66b754ea734e687d964f2986363f8e2) 可能这个能 fix 吧？非标准桌面之前会返回的默认图标主题是 hardcode 的，现在会尝试读 gtk 配置的图标

非常感谢，已经成功读取Gtk配置的图标并显示
