### ISSUE TITLE
Don't eat the hotkey when Input method is deactivate

### ISSUE THREAD

**Issue by yutakatay** [fcitx/fcitx5#162]
**Describe the bug**

If Escape is set to deactivate, I cannot input Escape.  In the IME deactivated, I want fcitx5 to stop eating the keys. (I want you to go through the key sequence.)
In fcitx4 it was possible.

**To Reproduce**
1. Setup fcitx5 `Deactivate Input Method: Escape`
2. Open your terminal
3. Ctrl+v + Esc
4. I want to see `^[`

**Expected behavior**

On the first Escape input, deactivate the IME. On the second Escape input, send the Escape normally. Because the IME is already turned off.

**Actual behavior**

If Escape is set to deactivate, Escape cannot be inputted in any way.

**Desktop (please complete the following information):**
 - Desktop: i3
 - Display server type: X11

**Additional context**

Actually, I'm vim user. I don't want the IME to remain activated when returning to normal mode using Escape key.

**Comment by yutakatay** [comment]
I tried it. It seems to be working :tada: 

Thank you for your very quick response.

**Comment by WieeRd** [comment]
Is it possible to make fcitx5 not eat the deactivate hotkey regardless of whether IME is active or not? I'm also a Vim user and I want to disable IME and return to normal mode with a single Esc press.

**Comment by wengxt** [comment]
@WieeRd for vim, consider using fcitx.vim instead https://github.com/lilydjwg/fcitx.vim

**Comment by WieeRd** [comment]
Thanks! But I still want to do it "globally", as I have Vim keybind plugins installed everywhere and there is no way to add the IME-controlling hooks to those.
