### ISSUE TITLE
fcitx5 wont build: fails test 38 "testxim"

### ISSUE THREAD

**Issue by ekaunt** [fcitx/fcitx5#163]
**Describe the bug**
When compiling fcitx5 ([through the aur: fcitx5-git](https://aur.archlinux.org/packages/fcitx5-git/)), it builds just fine, but then when it goes through the tests, its fails test 38/38 which is called "testxim". I have properly installed and reinstalled [xcb-imdkit-git](https://aur.archlinux.org/packages/xcb-imdkit-git/), so that shouldn't be the issue.

**To Reproduce**
- Open a machine running Arch
- Install the package fcitx5-git
- It fails

**Expected behavior**
It should compile and install so that I can use the latest version of fcitx5 (with the new expand mode feature).

**Desktop (please complete the following information):**
 - Desktop: BSPWM
 - Display server type: X11

**Comment by wengxt** [comment]
try install xorg-server-xvfb maybe?.. but if it's not installed testxim shouldn't run in the first place I think.

Can you upload the file under your makepkg directory? src/fcitx5/Testing/Temporary/LastTest.log

**Comment by StepinSilence** [comment]
Hello @ekaunt and @wengxt!. I'm facing exactly the same issue and here is my [LastTest.log](https://pastebin.com/XveSzYaM).

**Comment by wengxt** [comment]
I don't really know why it fails on your system. This test is a little bit special because it starts a temporarily X server to run the test. So probably some non-obvious package would be required to run it properly. I'll just remove it from the test.

**Comment by StepinSilence** [comment]
Thanks for your response.

**Comment by ekaunt** [comment]
I actually happen to already have xorg-server-xvfb installed (didnt even know lol)

Heres my LastTest.log file:


```
38/38 Testing: testxim
38/38 Test: testxim
Command: "/home/user/.cache/yay/fcitx5-git/src/fcitx5/test/xvfb_wrapper.sh" "/usr/bin/Xvfb" "/home/user/.cache/yay/fcitx5-git/src/fcitx5/test/testxim"
Directory: /home/user/.cache/yay/fcitx5-git/src/fcitx5/test
"testxim" start time: Dec 02 16:48 EST
Output:
----------------------------------------------------------
Can't connect to Xvfb, retrying...
I2020-12-02 16:49:00.441660 instance.cpp:1267] Override Enabled Addons: {testui, xcb, xim, testfrontend, testim}
I2020-12-02 16:49:00.441719 instance.cpp:1268] Override Disabled Addons: {all}
I2020-12-02 16:49:00.554370 addonmanager.cpp:177] Loaded addon xcb
I2020-12-02 16:49:00.554561 addonmanager.cpp:177] Loaded addon testui
I2020-12-02 16:49:00.554688 addonmanager.cpp:177] Loaded addon testim
I2020-12-02 16:49:00.556233 addonmanager.cpp:177] Loaded addon xim
I2020-12-02 16:49:00.556293 inputmethodmanager.cpp:193] Found 3 input method(s) in addon testim
I2020-12-02 16:49:00.556327 inputmethodmanager.cpp:109] No valid input method group in configuration. Building a default one
I2020-12-02 16:49:00.556394 instance.cpp:655] Items in Default: [InputMethodGroupItem(keyboard-us,layout=)]
I2020-12-02 16:49:00.556421 instance.cpp:660] Generated groups: [Default]
/home/user/.cache/yay/fcitx5-git/src/fcitx5/test/xvfb_wrapper.sh: line 39: 3624403 Aborted                 (core dumped) "$@"
<end of output>
Test time =  21.64 sec
----------------------------------------------------------
Test Failed.
"testxim" end time: Dec 02 16:49 EST
"testxim" time elapsed: 00:00:21
----------------------------------------------------------

End testing: Dec 02 16:49 EST
```

# I figured it out!

After deleting the line with "`"$@"`" (line 39) in the file `/home/user/.cache/yay/fcitx5-git/src/fcitx5/test/xvfb_wrapper.sh`, it finished building properly!

**Comment by wengxt** [comment]
..... @ekaunt  sorry, but you remove the line that actually INVOKEs the test.
