### ISSUE TITLE
Fcitx5 pinyin IM can't be actived on Ubuntu 20.04.

### ISSUE THREAD

**Issue by hongyi-zhao** [fcitx/fcitx5#168]
On Ubuntu 20.04, I have compiled and installed all the needed components for running fcitx5 pinyin IM. The config file and autostart script are shown below:

```
$ cat ~/.config/fcitx5/profile 
[Groups/0]
# Group Name
Name=Default
# Layout
Default Layout=us
# Default Input Method
DefaultIM=pinyin

[Groups/0/Items/0]
# Name
Name=keyboard-us
# Layout
Layout=

[Groups/0/Items/1]
# Name
Name=pinyin
# Layout
Layout=

[GroupOrder]
0=Default

$ cat /etc/xdg/autostart/fcitx.desktop 
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=fcitx5
Comment=
Exec=/usr/local/bin/fcitx5
```
And the fcitx5 is really running:
```
$ pgrep -ax fcitx5 
5122 /usr/local/bin/fcitx5
```
But I still can't activate the pinyin IM even I click the pinyin entry on the dropdown list as shown below:

![image](https://user-images.githubusercontent.com/11155854/101322473-0e421000-38a2-11eb-91a0-9828b8b86656.png)

I stuck on this problem. Could someone here give me some hints/notes for solving this problem?

Regards,
HY

**Comment by wengxt** [comment]
Suggest run fcitx5-diagnose, mostly likely environment var is not correctly set and gtk im module cache is not updated. Especially you're compiling your own one, things like `gtk-query-immodules-3.0 --update-cache` would need to be execute manually.

**Comment by hongyi-zhao** [comment]
> Suggest run fcitx5-diagnose, mostly likely environment var is not correctly set 
```

$ egrep -v '^(#|$)' ~/.xprofile 
export GTK_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export QT_IM_MODULE=fcitx5
```

>and gtk im module cache is not updated. Especially you're compiling your own one, things like `gtk-query-immodules-3.0 --update-cache` would need to be execute manually.

I've run the following command, but still can't fix the problem:

`$ sudo /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 --update-cache`

**Comment by wengxt** [comment]
as you can see


        Found immodules cache for gtk `3.24.20` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.20

        **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`*

Most likely you need to run this (Pleas update the GTK_PATH value if I got the value wrong)

    GTK_PATH=/usr/local/lib/x86_64-linux-gnu/gtk-3.0/ gtk-query-immodules-3.0 --update-cache

See also: https://fcitx-im.org/wiki/Compiling_fcitx5

**Comment by wengxt** [comment]
Also, that's another reason why I don't recommend you to build it manually. gtk-query-immodules-3.0 --update-cache  will be executed whenever your packaging system want to update it, which would likely lead to the file need manual update again.

**Comment by hongyi-zhao** [comment]
> Most likely you need to run this (Pleas update the GTK_PATH value if I got the value wrong)
> 
> ```
> GTK_PATH=/usr/local/lib/x86_64-linux-gnu/gtk-3.0/ gtk-query-immodules-3.0 --update-cache
> ```

The above folder doesn't exist for my case at all. And even I create it first the command  `gtk-query-immodules-3.0` still can't be found:

```
$ sudo mkdir /usr/local/lib/x86_64-linux-gnu/gtk-3.0/
$ sudo GTK_PATH=/usr/local/lib/x86_64-linux-gnu/gtk-3.0/ gtk-query-immodules-3.0 --update-cache
sudo: gtk-query-immodules-3.0: command not found
```
Another very strange thing is that I find the problem can be fixed by the following steps:

```
$  sudo apt-get install fcitx-*
$ ps -C fcitx -o pid --no-headers | xargs -r sudo kill -9
$  fcitx5 >/dev/null 2>&1 &
```
So, I figure out the quick and dirty solution as shown below:

```
$ cat ~/.profile.d/300-fcitx5.bash 

# Still can't use the Chinese relevant IMs in the following case:
# sudo gedit 

fcitx5=/usr/local/bin/fcitx5 
if [ -x $fcitx5 ] || [[ $(ps -C fcitx5 -o cmd --no-headers) != $fcitx5 ]]; then
  # Based on my tries, there is no need to set the following environment variables.
  #  export GTK_IM_MODULE=fcitx
  #  export XMODIFIERS=@im=fcitx
  #  export QT_IM_MODULE=fcitx
  # Very strange thing, I must first install the fcitx relative stuff, otherwise the Chinese relevant IMs for fcitx5
  # won't be actived.
  #sudo apt-get install fcitx-*
  ps -C fcitx -o pid --no-headers | xargs -r sudo kill -9
  fcitx5 >/dev/null 2>&1 &
fi
```

I also commented some current problems and notes in the above script. Even thought, I still can't figure out why fcitx5 relies on some settings of  the ode version of fcitx. OTOH, even the fcitx5 can work smoothly, the **Failed to find fcitx5 in immodule cache** problem reported in the issue previously still exists.

Regards,
HY

**Comment by wengxt** [comment]
fcitx5's im module is in fcitx5-gtk, I don't know if you installed it or not.

**Comment by hongyi-zhao** [comment]
> fcitx5's im module is in fcitx5-gtk, I don't know if you installed it or not.

Yes. See the cmake manifest file for detailed info.
```
werner@X10DAi:~/Public/repo/github.com/fcitx/fcitx5-gtk.git/build$ cat install_manifest.txt 
/usr/local/lib/libFcitx5GClient.so.5.0.1
/usr/local/lib/libFcitx5GClient.so.1
/usr/local/lib/libFcitx5GClient.so
/usr/local/lib/pkgconfig/Fcitx5GClient.pc
/usr/local/include/Fcitx5/GClient/fcitx-gclient/fcitxgclient.h
/usr/local/include/Fcitx5/GClient/fcitx-gclient/fcitxgwatcher.h
/usr/local/lib/cmake/Fcitx5GClient/Fcitx5GClientTargets.cmake
/usr/local/lib/cmake/Fcitx5GClient/Fcitx5GClientTargets-noconfig.cmake
/usr/local/lib/cmake/Fcitx5GClient/Fcitx5GClientConfig.cmake
/usr/local/lib/cmake/Fcitx5GClient/Fcitx5GClientConfigVersion.cmake
/usr/share/gir-1.0/FcitxG-1.0.gir
/usr/lib/x86_64-linux-gnu/girepository-1.0/FcitxG-1.0.typelib
/usr/local/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so
```

The current relative info given by fcitx5-diagnose:
```
$ fcitx5-diagnose | grep -A5 -B5 '*Failed to find fcitx5 in immodule cache at'
        Found immodules cache for gtk `2.24.32` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.32

        **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**

        Found immodules cache for gtk `2.24.32` at `/etc/gtk-2.0/gtk.immodules`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.32

        **Failed to find fcitx5 in immodule cache at `/etc/gtk-2.0/gtk.immodules`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.20` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.20

        **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 3 in cache.**

4.  Gtk IM module files:
```
The screenshot when using fctix5-rime and luna_pinyin_simp schema:

![image](https://user-images.githubusercontent.com/11155854/101434941-71857e00-3946-11eb-97ba-fda347bfdfaf.png)

**Comment by wengxt** [comment]
as you can see, you didn't compile the Gtk 3 version of im module, but only gtk 2. You probably don't have gtk3 dev headers so it doesn't compile?

**Comment by hongyi-zhao** [comment]
See following:
```
$ dpkg -l | grep gtk.*-dev
ii  libgtk-3-dev:amd64                            3.24.20-0ubuntu1                           amd64        development files for the GTK library
ii  libgtk2.0-dev:amd64                           2.24.32-4ubuntu4                           amd64        development files for the GTK library

```
