### ISSUE TITLE
Tray menu not disappear with i3

### ISSUE THREAD

**Issue by madjxatw** [fcitx/fcitx5#169]
**Describe the bug**
I am running Debian unstable (bullseye) with i3 (with i3 status bar running), and using fcitx5 5.0.2. When right clicking on the fcitx5 tray icon to have the menu come up but doing nothing, and then click on another window:

- the menu doesn't disappear
- I couldn't work in the window I click on. For example, I click on a text editor but couldn't type anything in it even though the cursor is there.
- I have to use the i3 keyboard shortcut to switch to another window to get the menu gone.

**Expected behavior**
The tray menu should disappear right after a mouse clicking on another window, and that window should be focused on. All tray applications in my i3 status bar behave this way.

**Desktop (please complete the following information):**
 - Desktop: i3 (with i3 status bar running)
 - Display server type: X11

**Comment by wengxt** [comment]
Still working on it, but I noticed that if you move mouse to window title, then the focus is transferred to window and menu will disappear.

**Comment by madjxatw** [comment]
> Still working on it, but I noticed that if you move mouse to window title, then the focus is transferred to window and menu will disappear.

Yes, exactly! but you know for those who using i3, window title are usually disabled. :D

**Comment by mkrasnitski** [comment]
I'm experiencing a similar issue. I have window titles disabled on i3, so to remove the menu, I have to change workspaces or focus a different window than I had before I clicked on the tray icon. Also, clicking off the menu doesn't work either on i3. I would expect that clicking on the currently focused window would close the menu, but it doesn't.

**Comment by akshat157** [comment]
Experiencing the exact same issue on Awesome WM.

I also tested it with the latest i3 WM as well and the issue still exists.

It seems to be a problem in case of window managers only, since on testing the same on XFCE desktop environment, it did not behave like this, instead on a click (left or right) anywhere else on the screen, lost focus and closed the context menu.

**Comment by c02y** [comment]
Can I disable the system tray in i3 or any other de/wm? I personally don't need its system tray there forever.
