### ISSUE TITLE
Adjust the size of the IM UI and the font on it for fcitx5.

### ISSUE THREAD

**Issue by hongyi-zhao** [fcitx/fcitx5#170]
On Ubuntu 20.04, I've successfully compiled the fcitx5/fcitx5-rime/librime, and install the corresponding schemas with plum. When I input Chinese characters with the luna_pinyin_simp schema, I find that the size of the IM UI and the font on it are small as shown below: 

![image](https://user-images.githubusercontent.com/11155854/101439926-9f6fc000-3950-11eb-92a8-3cb0774b285a.png)

So I wan t to know how can I adjust the size of the IM UI and the font on it for fcitx5.

Any hints will be highly appreciated.

Regards,
HY

**Comment by hongyi-zhao** [comment]
I've figured out the method based on the solutions here:

```
https://www.wannaexpresso.com/2020/03/26/fcitx5/
https://github.com/hosxy/Fcitx5-Material-Color
```

**Comment by wengxt** [comment]
And I kindly ask you please don't open new issue anymore just for questions. Issue is not the right place to ask questions. Please use IRC, telegram, maillist fcitx@googlegroups.com for that.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your reminder. I apologize for this inappropriate behavior.
