### ISSUE TITLE
fcitx5 未能正确显示托盘图标

### ISSUE THREAD

**Issue by RRRRRm** [fcitx/fcitx5#171]
OS: ArchLinux
DE: i3wm + polybar

我使用的了一个自定义的图标主题并且配置了 `~/.local/share/icons/mytheme/status/32/input-keyboard.svg`
但托盘图标仍显示为 `/usr/share/icons/hicolor/32x32/status/input-keyboard.svg`

**Comment by wengxt** [comment]
我觉得是fcitx没辨认到你正在用的桌面一类的原因并不知道你用了哪个主题，你怎么配置的图标主题

**Comment by RRRRRm** [comment]
感谢! 的确已经解决了
