### ISSUE TITLE
拼音（不可用）

### ISSUE THREAD

**Issue by 1900011604** [fcitx/fcitx5#176]
**Desktop (please complete the following information):**
 - System: Manjaro 20.2
 - Desktop: (KDE)
 - Display server type: X11

![屏幕截图 2020-12-11 231741](https://user-images.githubusercontent.com/65082432/101920920-5d23d880-3c07-11eb-9417-f01e519b35f8.png)

**Comment by 1900011604** [comment]
There is still this problem, even after the last update. I typed the issue on Windows. Maybe you cannot see the screenshot, that is just the title.

**Comment by wengxt** [comment]
normally it would just mean your installation is broken. if you compile it from git or using non official package, you’d better take a look. (arch recently update boost you probably a rebuild is required.)

**Comment by adaaaaaa** [comment]
@1900011604 wo ye shi... ni jie jue le ma??

**Comment by wengxt** [comment]
@adaaaaaa 一般来说就是你系统升级不完全，更新系统或者如果你是自己编译的就需要重新编译来link新的库

**Comment by 1900011604** [comment]
没有，我换成正式版了，抛弃git版了
