### ISSUE TITLE
Failed to compile fcitx5 with harfbuzz on Ubuntu 20.10.

### ISSUE THREAD

**Issue by hongyi-zhao** [fcitx/fcitx5#177]
On Ubuntu 20.10, I compiled and installed the latest git master version of  [harfbuzz](https://github.com/harfbuzz/harfbuzz). Then I try to compile the latest git master version of fcitx5 but failed with the following error:

```
/usr/bin/ld: /usr/local/lib/libharfbuzz.a(harfbuzz.cc.o): warning: relocation against `_ZN2OT26hb_get_subtables_context_t8apply_toINS_14ContextFormat1EEEbPKvPNS_21hb_ot_apply_context_tE' in read-only section `.text._ZN2OT26hb_get_subtables_context_t8dispatchINS_14ContextFormat1EEE10hb_empty_tRKT_[_ZN2OT26hb_get_subtables_context_t8dispatchINS_14ContextFormat1EEE10hb_empty_tRKT_]'
/usr/bin/ld: /usr/local/lib/libharfbuzz.a(harfbuzz.cc.o): relocation R_X86_64_PC32 against symbol `_ZNK2OT10MarkRecord9get_classEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/ui/classic/CMakeFiles/classicui.dir/build.make:334: src/ui/classic/classicui.so] Error 1
make[2]: Leaving directory '/home/werner/Public/repo/github.com/fcitx/fcitx5.git/build'
make[1]: *** [CMakeFiles/Makefile2:2372: src/ui/classic/CMakeFiles/classicui.dir/all] Error 2
make[1]: Leaving directory '/home/werner/Public/repo/github.com/fcitx/fcitx5.git/build'
make: *** [Makefile:141: all] Error 2

```
Any hints for fixing this problem?

Regards,
HY

**Comment by wengxt** [comment]
I don't know why you compiled the static version of harfbuzz, but when you do, you need to use -fPIC to compile it to use it with shared library. Or just delete the static versio anyway.

**Comment by hongyi-zhao** [comment]
To be frank, I myself just use the default compile options shipped with harfbuzz as shown below:

```
git clone https://github.com/harfbuzz/harfbuzz.git harfbuzz.git
cd harfbuzz.git
mkdir build && cd $_
cmake ..
make -j44
sudo make install
```

**Comment by wengxt** [comment]
distro usually don't install static library by default. If you do want to use static version, you should compile it with -fPIC.

**Comment by hongyi-zhao** [comment]
I tried with the followng option to configure harfbuzz with cmake:

 `cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..`

But it still generates and installs the static version:

`-- Installing: /usr/local/lib/libharfbuzz.a`

Any hints?

**Comment by hongyi-zhao** [comment]
Got it. See [here](https://github.com/harfbuzz/harfbuzz/issues/2766#issuecomment-743713837) for more info.
