### ISSUE TITLE
Cannot connect to Fcitx by Dbus, is Fcitx running?

### ISSUE THREAD

**Issue by mrhieu059** [fcitx/fcitx5#178]
When I start fcitx5-configtool, it said that fcitx5 is not run. But I couldn't run fcitx5, could you please take a look to see what wrong with it?
- Desktop: Windows manager only (DWM)
 - Display server type: X11

**Additional context**
[diagnose.txt](https://github.com/fcitx/fcitx5/files/5688230/diagnose.txt)
[log-when-running-fcitx5.txt](https://github.com/fcitx/fcitx5/files/5688231/log-when-running-fcitx5.txt)

**Comment by wengxt** [comment]
How did you install fcitx5? IMHO your installation might be somehow broken.

Maybe you could run `fcitx5 --verbose=*=5` and paste the output.

**Comment by mrhieu059** [comment]
I installed fcitx5 via artix main repo, I tried to install a aur (git version but it failed to build). 
Here is the log

**Comment by wengxt** [comment]
Ok, now I kinda get it. You're using a non-systemd system with no desktop environment, so you probably didn't set up dbus properly.

You may need to add dbus-launch to your WM startup script.
https://fcitx-im.org/wiki/Configure_(Other)#Use_Slim_.28.7E.2F.xinitrc.29.2Fstartx

**Comment by zihenlin** [comment]
Hi, I am facing the same problem. I am using artix linux too. The propsed solution in [(https://fcitx-im.org/wiki/Configure_(Other)#Use_Slim_.28.7E.2F.xinitrc.29.2Fstartx)] doesn't work. I am using `runit`, and `dbus` is enabled by the init system and running. 

`fcitx5` is able to connect dbus using `dbus-launch fcitx5`, however, the problem persists. `fcitx5-configtool` unable to connect `fcitx5`.

**Comment by wengxt** [comment]
You need to use dbus-launch properly, other wise you're simply create different isolated dbus daemon.

Also, there are "system dbus" and "user dbus". We're talking about user session dbus  here.

BTW, I have no problem on artix KDE, because usually the DE that relies on more dbus will handle this for you.

**Comment by zihenlin** [comment]
`dbus-launch --sh-syntax --exit-with-session > /dev/null`
`${XDG_CONFIG_HOME:-$HOME/.config}/x11/setup.sh`
`/usr/bin/fcitx5 &`
`if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then`
`	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"`
`else`
`	. "$HOME/.xprofile"`
`fi`
`ssh-agent dwm`

This is my updated `.xinitrc`. Could you kindly point out what went wrong? 
The problem persists. `configtool` couldn't connect to `fcitx5` by `dbus`.

**Comment by zihenlin** [comment]
update: Got it working by deleting `dbus-launch --sh-syntax --exit-with-session > /dev/null`, changing `ssh-agent dwm` to `exec dbus-launch dwm`. 

Thank you for your time and attention wengxt!

**Comment by YellowOnion** [comment]
FYI @zihenlin I believe you're supposed to *use* the output of `dbus-launch --sh-syntax`, not pipe it to /dev/null, that's why it's not working.

`eval $(dbus-launch --sh-syntax)` or something similar.
