### ISSUE TITLE
The font in taskbar menu is too small

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/fcitx5#179]
I'm using fcitx5 on Xfce desktop. The font in fcitx5 taskbar menu is too small.

![fcit5-icon-menu](https://user-images.githubusercontent.com/34818411/102611343-1176af00-4172-11eb-937f-4089f93280fd.png)

See "設定" at bottom right.
Is it possible to use the font of "Classic User Interface" for taskbar menu?

**Comment by wengxt** [comment]
looking at the code.. the menu has its own font settings.. but i don’t remember why is that .. :/

I think we probably should add an separate global menu font option just like input panel.

**Comment by utuhiro78** [comment]
Old fcitx can configure "MenuFontSize" in fcitx_skin.conf,
so I can read "設定" easily.

![fcitx-menu-icon](https://user-images.githubusercontent.com/34818411/102646711-de4f1280-41a7-11eb-86be-d42d37fcd63f.png)

Thank you for developing fcitx/fcitx5.

**Comment by utuhiro78** [comment]
Sorry wengxt, I missed this.

> wengxt closed this in 3a8bd4b

I tested fcitx5-git and I can see the menu with a bigger font now.
Thank you so much! You are so fast!

![fcitx5-icon-menu-new](https://user-images.githubusercontent.com/34818411/102652053-d5af0a00-41b0-11eb-90ef-e9c8e99a301c.png)
