### ISSUE TITLE
Please add the option: Don't show the first input method information

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/fcitx5#180]
Old fcitx doesn't show the first input method information.
I'm using a Japanese keyboard, so fcitx5 shows "Keyboard - Japanese" or "ja" 
as the first input method. It looks like a Japanese input method (Mozc, Anthy etc).

**Comment by wengxt** [comment]
That is actually the name of your keyboard layout.

**Comment by utuhiro78** [comment]
> wengxt closed this in c7a60f8

Thanks wengxt! I tested fcitx5-git and I confirmed it didn't show the first input method.

> That is actually the name of your keyboard layout.

Yes. I know that but I feel I can type Japanese when I see "Keyboard - Japanese" or "ja". ;-)
