### ISSUE TITLE
[unexpected behavior] The reaction of the word selection box will become slow after long time use

### ISSUE THREAD

**Issue by ukari** [fcitx/fcitx5#181]
**Describe the bug**
After about 24hours running and 10000 Chinese character input, sometimes word selection box will act slowly. And restart fcitx5  could fix this.

**Expected behavior**
It's reaction shouldn't become slow after long time use.

**Desktop (please complete the following information):**
 - [x] Desktop: i3gaps
 - [x] Display server type: X11
 - [ ] The output of fcitx5-diagnose if possible.

**Additional context**
do not affect the use

**Comment by wengxt** [comment]
which input method are you using?
Does the memory and cpu looks normal?

**Comment by ukari** [comment]
pinyin.

I have notice this phenomenon for twice or three times. And the first time I notice it is about 2 weeks ago.

Both memory and cpu are normal. The largest memory usage is 0.6% or 6% of 16GB, I didn't remember it but the memory number is not a crazy number. But I didn't check cpu status during typing Chinese characters. I will collect more detailed information if I meet the same phenomenon again.

**Comment by ukari** [comment]
After about 67.5 hours running and 25000+ Chinese characters input, the slow down phenomenon happens again.

Memory usage is about 170MB. CPU usage is high when input with `pinyin`.

When I input about 12000 ~ 15000 Chinese characters, it is possible to notice a bit input latency. 

After 21000+ Chinese characters input, I am sure I feel input latency.

After 25000+ Chinese characters input, the input latency is obviously enough to be record.

Same latency could be found when use fcitx5 pinyin with emacs, urxvt and firefox.

Here is the mp4 record about [input latency](https://user-images.githubusercontent.com/10378269/102766286-ce852900-4375-11eb-888f-ad5612e6ed8e.mp4).

PS: I have finished input all the characters when fctix5 show `shijia`

**Comment by wengxt** [comment]
can you use sysprof to record some trace when you think it is slow?

**Comment by ukari** [comment]
seems to be a memory leak about pango

[fcitx5-capture.syscap.zip](https://github.com/fcitx/fcitx5/files/5727622/fcitx5-capture.syscap.zip)

**Comment by wengxt** [comment]
Thank you, may I ask which version you're using? This looks like #42 but was fixed.

**Comment by ukari** [comment]
4.99.0

**Comment by wengxt** [comment]
That would be really out of date. :)

Please update to a stable version maybe.

**Comment by wengxt** [comment]
Looks like you're probably using a debian/ubuntu based distro. If distro does not provide a up to data package, you can also try:

https://www.csslayer.info/wordpress/fcitx-dev/fcitx5-on-flatpak/
