### ISSUE TITLE
weird startup and shutdown behavior

### ISSUE THREAD

**Issue by ukari** [fcitx/fcitx5#182]
**Describe the bug**
1. startup. After fcitx5 start up, no actual input method would be chosen to use before some special interactive event happens like mouse clicking or using hotkey to call other program. I call this phenomenon with Temporal Dead Zone. With TDZ, it is impossible to input character after system startup with fcitx5 startup(click mouse will fix it). And the shell command `qdbus "org.fcitx.Fcitx5" "/controller" "org.fcitx.Fcitx.Controller1.CurrentInputMethod"` returns `""` during TDZ.
2. shutdown. If running `killall fctix5` in console(urxvt), the console will lose reaction.

**To Reproduce**
Steps to reproduce the `startup` behavior:
1. Open a console
2. Run `fcitx5 &` in shell
3. Press any key
4. Click mouse

Steps to reproduce the `shutdown` behavior:
1. Run fcixt5
2. Open a console
3. Run `killall fcitx5 &` in shell

**Expected behavior**
- No TDZ after fcitx5 startup. 
- `killall fcitx5` won't cause terminal lose reaction.

**Desktop (please complete the following information):**
 - [x] Desktop: i3gaps
 - [x] Display server type: X11
 - [ ] The output of fcitx5-diagnose if possible.

**Additional context**
1. These behaviours actually not affect the use
2. [TDZ mp4](https://user-images.githubusercontent.com/10378269/102622074-73b2be00-4138-11eb-877e-fb983921fc4b.mp4)

**Comment by wengxt** [comment]
that’s expected behavior.
CurrentInputMethod will return the input method for a certain input context that last being used. you need to focus in to a program.

As for urxvt, there’s nothing I can do about it because Xlib has a lot of synchronous call in XIM and would simply wait forever when server is gone.
