### ISSUE TITLE
ubuntu 20.10上的问题

### ISSUE THREAD

**Issue by jim19770812** [fcitx/fcitx5#184]
fcitx5版本号：0.0~git20200626.2e9821a-2build1
操作系统：ubuntu 20.10
尝试了两种桌面xserver和wayland
wayland在gedit里不显示待选词列表
xserver里表现要好很多，但发现在chromium浏览器里可以正常切换到拼音输入法，但输入不了中文，待选词窗口也不显示。其余都还正常

**Comment by wengxt** [comment]
Please report to ubuntu to ask them to include fcitx im module in snap runtime, like what is being done to flatpak.
