### ISSUE TITLE
The position candidate popup window is in a strange position on urxvt when I use on the spot mode

### ISSUE THREAD

**Issue by yutakatay** [fcitx/fcitx5#185]
**Describe the bug**

When I turn on OnTheSpot on urxvt so that I can type preedit inline. But the candidate popup window appears outside the window instead of near the cursor.
Is this the behavior you are expecting?
I want the candidate popup window to be near my cursor while I type inline.

*Enable "Use On The Spot Style"*
![2020-12-25_14-42](https://user-images.githubusercontent.com/8683947/103121435-788aeb00-46bf-11eb-86bb-7cc95baf48e5.png)

*Disable "Use On The Spot Style"*
![2020-12-25_14-39](https://user-images.githubusercontent.com/8683947/103121298-f4386800-46be-11eb-9a2e-42d6e4343203.png)

**To Reproduce**

1. Setup the "OnTheSpot" to `.Xresources`

```
! extensions
URxvt.perl-ext-common: default,matcher,resize-font,url-select,xim-onthespot
! IME
URxvt.inputMethod: fcitx
URxvt.preeditType: OnTheSpot
```

2. Enable "Use On The Spot Style" in fcitx5
3. Launch urxvt
4. IME ON
5. Type some words

**Expected behavior**

The candidate popup windows appear near the cursor.
(This is termite)
![2020-12-25_14-46](https://user-images.githubusercontent.com/8683947/103121554-08309980-46c0-11eb-850e-6fc85a3ff5eb.png)

**Desktop (please complete the following information):**
 - Desktop: i3
 - Display server type: X11
 - OS: ArchLinux
 - urxvt version: https://aur.archlinux.org/packages/rxvt-unicode-truecolor-wide-glyphs/
 - fcitx5: 5.0.3
 - IME: fcitx5-mozc
 - Installed: fcitx5-gtk, fcitx5-qt
 - The output of fcitx5-diagnose if possible.

<details>
<summary>fcitx5-diagnose</summary>

# System Info:
1.  `uname -a`:

        Linux host 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://www.archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux

5.  Desktop Environment:

    Cannot determine desktop environment.

6.  Bash Version:

        BASH_VERSION='5.1.4(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locale:

            C
            en_US.utf8
            ja_JP.utf8
            POSIX

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE=en_US.UTF-8
            LC_NUMERIC=en_US.UTF-8
            LC_TIME=en_US.UTF-8
            LC_COLLATE=en_US.UTF-8
            LC_MONETARY=en_US.UTF-8
            LC_MESSAGES=en_US.UTF-8
            LC_PAPER=en_US.UTF-8
            LC_NAME=en_US.UTF-8
            LC_ADDRESS=en_US.UTF-8
            LC_TELEPHONE=en_US.UTF-8
            LC_MEASUREMENT=en_US.UTF-8
            LC_IDENTIFICATION=en_US.UTF-8
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/yutakatay

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is set to `/home/yutakatay/.config`.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/yutakatay/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/dotfiles/.config/fcitx5` (`/home/yutakatay/.config/fcitx5`).

5.  Current user:

    The script is run as yutakatay (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.3`

3.  process:

    Found 1 fcitx5 process:

           1156 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.2`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `1156`.

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.24` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.24

        Found fcitx5 im modules for gtk `3.24.24`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.24` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.24

        Found fcitx5 im modules for gtk `3.24.24`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 19 enabled addons:

            Classic User Inteface
            Clipboard
            DBus
            DBus Frontend
            Emoji
            IBus Frontend
            Input method selector
            Keyboard
            KDE Input Method Panel
            Mozc
            Status Notifier
            Notification
            Quick Phrase
            Spell
            Unicode
            Wayland
            Wayland Input method frontend
            XCB
            X Input Method Frontend

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Inteface
        KDE Input Method Panel

# Log:
1.  `date`:

        Fri Dec 25 02:32:47 PM JST 2020

2.  `/home/yutakatay/.config/fcitx5/crash.log`:

    `/crash.log` not found.

</details>

**Comment by wengxt** [comment]
There is nothing we can do here.

Xlib in XIM doesn't send over the position when on the spot is used.
