### ISSUE TITLE
ubuntu 20.10中snap商店和chromium无法输入中文

### ISSUE THREAD

**Issue by opptimus** [fcitx/fcitx5#186]
症状：无法在ubuntu自带的Ubuntu Software商店的搜索框中输入中文，同时也无法切换为其他输入法。这个商店的引擎为snap。同时，通过snap商店安装的chromium浏览器（89.0版本）的下载文件保存对话框无法输入中文，但地址栏正常。
其他大部分应用使用正常。
请问大神们有没有修复的方法？
以下是我的工作环境：
ubuntu 20.10
fcitx5：0.0~git20200626.2e9821a-2build1
 - Desktop:GNOME
 - Display server type:  Wayland
 

`
已在/etc/environment和~/.bashrc设置了如下环境变量：`

```
export XIM=fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XIM_PROGRAM=fcitx5
export XMODIFIERS="@im=fcitx5"

```

**Comment by wengxt** [comment]
Duplicate of #184
