### ISSUE TITLE
config "unshow the input window when only one suggestion is shown in suggestions and preedit"

### ISSUE THREAD

**Issue by syui** [fcitx/fcitx5#187]
Are there any settings?

"unshow the input window when only one suggestion is shown in suggestions and preedit"

![](https://raw.githubusercontent.com/syui/img/master/other/fcitx_4_setting_01.jpg)

**Comment by wengxt** [comment]
no. may I ask which input method you want this feature? Because in fcitx 5 we try to avoid such global behavior and implement such thing in individual input method.

**Comment by syui** [comment]
Thank you very much for kind reply.
I don't think it's particularly necessary.
