### ISSUE TITLE
Please set HOME.

### ISSUE THREAD

**Issue by ztoiax** [fcitx/fcitx5#189]
I want to create the `systemd` startup service of fcitx5:
```bash
[Unit]
Description=Run a Custom Script at Startup
After=sddm.service
[Service]
ExecStart=/usr/bin/fcitx5
ExecStop=pkill fcitx5
[Install]
WantedBy=sddm.service
```

when I run  'systemctl start fcitx5.service,I get this error:
```bash
Dec 27 23:19:56 tz-pc fcitx5[75395]: Please set HOME.
```

**Comment by wengxt** [comment]
even if you want to use fcitx as a systemd service, you should create a user unit.

also I think the warning is expected, it doesn’t see the HOME envvar.
