### ISSUE TITLE
Unable to save modified quickphrase list.

### ISSUE THREAD

**Issue by ZWindL** [fcitx/fcitx5#19]
When I try to add single "keyword"->"phrase" or edit multiple lines, it works properly, until click "apply" or "OK" button. It can show in the "快速输入编辑器", but when you click "OK" and open the editor again, it's gone, and a file with same name as the list which has extension `.mb` appears in `~.local/share/fcitx5/data/quickphrase.d` and it's empty.

**Comment by wengxt** [comment]
Fixed by https://github.com/fcitx/fcitx5-qt/commit/f7616e2279de95e5bf8128753e9ef8226bb053e4
