### ISSUE TITLE
classicui: IVS (ideographic variation sequence) is not supported

### ISSUE THREAD

**Issue by szc126** [fcitx/fcitx5#190]
**Describe the bug**
[IVS](https://zh.wikipedia.org/wiki/異體字選擇器)es are not supported, and show up as the base character.

The UI is "classic UI" with the font HanaMinA. Firefox shows candidate 3 correctly.

![_](https://user-images.githubusercontent.com/29127915/103218945-418c2380-48d1-11eb-9541-37c37aff4bbb.png)

This might be the fault of the text rendering engine. I am not sure, but it seems like other programs like `gedit` also disobey IVS.

**Desktop (please complete the following information):**
 - Desktop: Arch Linux
 - Display server type: X11
 - The output of fcitx5-diagnose if possible.

**Comment by wengxt** [comment]
I think the fix belongs to either cairo or pango.
