### ISSUE TITLE
自己编绎的fcitx5在deepin20中firefox、chrome等程序内不能使用单行模式，且如果输入速度很快，偶尔会无法正确输入文字

### ISSUE THREAD

**Issue by thep0y** [fcitx/fcitx5#195]
![截图录屏_选择区域_20210103192242](https://user-images.githubusercontent.com/51874567/103477351-13d73b00-4df9-11eb-9492-10a611bcdaa7.png)
在manjaro中fcitx5是能在这些程序里使用单行模式的。

无法正确输入文字的具体表现：
我用的是五笔，在当打字速度快了以后，同样在不能用单行模式的程序里，正在输入的文字编码有时会上屏，也有时会将空格上屏，导致不能正确输入文字。

**Comment by wengxt** [comment]
看起来是在用 xim 没有用 fcitx 的输入法模块

fcitx5-diagnose 自己检查 GTK_IM_MODULE 环境变量和相关输入法模块的设置。

**Comment by thep0y** [comment]
环境变量的值之前设置为fctix5，所以才出现这个问题，改为fcitx后就能正常使用了。
wps里输入文字还需要再修改一下。

**Comment by wengxt** [comment]
只是 WPS 的话，你可以试试单独设置 QT4_IM_MODULE ，这样不影响 Qt 5 的

另外 WPS 设置成  fcitx5 只是让他 fallback 到 xim 而已。要么你就直接 QT4_IM_MODULE=xim …

**Comment by asdasd1dsadsa** [comment]
我GENTOO之前有相同情况，后来才知道是那些Electron应用都用的gtk，而我没装fcitx-gtk支持……装了就好了。
