### ISSUE TITLE
在终端里无法使用输入法

### ISSUE THREAD

**Issue by xiaohaoxiang** [fcitx/fcitx5#196]
我的环境：
 OS: Manjaro 20.2 Nibia
 Kernel: x86_64 Linux 5.10.2-2-MANJARO
 Uptime: 44m
 Packages: 1330
 Shell: bash
 Resolution: 2560x1440
 DE: KDE 5.77.0 / Plasma 5.20.4
 WM: KWin
 GTK Theme: Breath [GTK2/3]
 Icon Theme: breath2
 Disk: 28G / 112G (26%)
 CPU: Intel Core i7-10700K @ 16x 12GHz [36.0°C]
 GPU: GeForce RTX 3080
 RAM: 3416MiB / 32032MiB

使用pacman安装的。按Ctrl+T使用终端，这时候右下角显示的图标是“拼”，但在输入时输入法不会出现。

**Comment by wengxt** [comment]
fcitx5-diagnose please.

什么终端

**Comment by xiaohaoxiang** [comment]
> 
> 
> fcitx5-diagnose please.
> 
> 什么终端

KDE自带的终端，Konsole

**Comment by wengxt** [comment]
请贴 fcitx5-diagnose 的输出

fcitx5-qt 安装了吗
