### ISSUE TITLE
The strange package dependence problem: fcitx-frontend-qt5 must be installed for self-compiled fcitx5.

### ISSUE THREAD

**Issue by hongyi-zhao** [fcitx/fcitx5#197]
On Ubuntu 20.10, I've compiled and installed the following packages in order of number:

```
10-cldr-emoji-annotation.git
10-fmt.git
10-librime.git
10-xcb-imdkit.git
20-fcitx5.git
25-libime.git
30-fcitx5-gtk.git
30-fcitx5-lua.git
30-fcitx5-qt.git
30-fcitx5-rime.git
40-fcitx5-chinese-addons.git
40-fcitx5-configtool.git
```
But it seems that the input methods switch through the frontend of fcitx5 still needed the following package to be installed, otherwise the input methods switch will be disabled and not responds to the keystroke:
`$ sudo apt-get install -y fcitx-frontend-qt5`

I'm very confused on this problem can't figure out the reason. Any hints will be highly appreciated.

Regards,
HY

**Comment by wengxt** [comment]
such question belongs to mail list.

**Comment by wengxt** [comment]
Here's the thing, if anything doesn't work and so "fundamental", people should have noticed that. This means it must be your own configuration problem. Any of such problem, is not a bug and should not be reported here.

And I will not answer such question here anymore.

**Comment by hongyi-zhao** [comment]
I've re-posted on fcitx-dev list. To be frank, I really can't figure out what's the matter with my configuration, so I want to get some useful tips.
