### ISSUE TITLE
Add support for loading new addon on the fly.

### ISSUE THREAD

**Issue by wengxt** [fcitx/fcitx5#200]
Action items:
- Dependency checking with version
- Addon config need to contain version
- InputMethodManager need to support reload new items.

**Comment by tinywrkb** [comment]
Any chance to have the widget modules statically linked against the Fcitx5 libs? this would make it easier to load into Flatpak apps.  
This is why it would be preferred to have the Flatpak Freedesktop runtime split the Fcitx libs into a runtime extension that can be updated separately.  
To have this work with the org.kde.Kate Flatpak app I had to use QT_PLUGIN_PATH and also LD_LIBRARY_PATH to get the right lib versions from a master branch Fcitx5 build.

**Comment by wengxt** [comment]
I don't understand what you're talking about. This issue has nothing to do with im module that loaded by application.

Also, fcitx 4 im module has support for fcitx 5. And freedesktop runtime / kde runtime has fcitx im module built in. For now there's no need to use fcitx 5 im module. If you really want to, you may build your own freedesktop runtime / kde sdk for testing purpose.

Once I think it's ready I'll push fcitx 5 im module in to freedesktop / kde runtime to replace the fcitx 4 version.

**Comment by tinywrkb** [comment]
@wengxt Oh, sorry, I posted in the wrong issue.
