### ISSUE TITLE
嵌入编辑样式

### ISSUE THREAD

**Issue by yueduz** [fcitx/fcitx5#203]
![2021-01-13 21-29-36 的屏幕截图](https://user-images.githubusercontent.com/1448159/104458526-78a74800-55e6-11eb-9441-0f4435af6579.png)
fcitx5-rime的嵌入编辑有一个选择样式(蓝色背景)，fcitx5能不能也做一个?

**Comment by wengxt** [comment]
我个人不喜欢 :)
fcitx5-rime 要不是因为需要表达两种意思我也不用高亮
