### ISSUE TITLE
Flatpak apps seem to require org.fcitx.Fcitx-99 to have fcitx4frontend working correctly

### ISSUE THREAD

**Issue by tinywrkb** [fcitx/fcitx5#204]
So I tried solving [this WPS Flatpak issue](https://github.com/flathub/com.wps.Office/issues/80) by giving session bus access to the app with [this change](https://github.com/tinywrkb/com.wps.Office/commit/feb44589e64877ade5c38846b5d64607b79a2f4c).  
This change worked when running the Flatpak Fcitx5 package but not with the Arch Linux Fcitx5 package.  
The only difference I noticed is that the Fcitx5 Flatpak also creates `org.fcitx.Fcitx-99` user session bus interface.  
Starting WPS Flatpak with the environment variable `DISPLAY=:0` set in the sandbox made WPS work correctly with the Fcitx5 Arch Linux package.

Flatpak sets `DISPLAY=99.0` automatically, AFAIK there's no way to override it, I had to start a shell in the sandbox in order to change it and I don't believe xdg-dbus-proxy support rewriting an interface address yet, so I don't see how this can be fixed in the WPS Flatpak packaging.

A possible fix could be to always create `org.fcitx.Fcitx-99`.

**Comment by wengxt** [comment]
I don’t really think this would fix anything. 

first, with current wps‘s permission you can’t read .config/fcitx/dbus , which means it might not be able to talk to fcitx at all.

second, org.fcitx.Fcitx-99 is also not allowed by dbus proxy under current setup

The cause of this is simply because wps’s im module is written by wps due to they don’t want gpl, so their have their own implementation doesnt follow fcitx 4 im module.

While I contacted wps and says we relicensed im module code to bsd for them to include, they don’t really seem to do anything about it yet.

I’d rather suggest if someone could build an im module with wps qt library with actual fcitx code for this.

**Comment by tinywrkb** [comment]
> second, org.fcitx.Fcitx-99 is also not allowed by dbus proxy under current setup

This is not an issue, just adding `--talk-name=org.fcitx.Fcitx-99` or `--talk-name=org.fcitx.Fcitx-*` to the WPS Flatpak made it work correctly with the Flatpak Fcitx5 package that does create the `org.fcitx.Fcitx-99` interface.  
The problem is with the distro Fcitx5 package that doesn't create `org.fcitx.Fcitx-99` interface.

> first, with current wps‘s permission you can’t read .config/fcitx/dbus , which means it might not be able to talk to fcitx at all.

I didn't need to allow access to this path, it worked without it, I actually try to see if adding `--filesystem=xdg-config/fcitx` makes any difference but it didn't.

Just adding `addDisplay(":99");` to the `Fcitx4FrontendModule` constructor solves this issue.

**Comment by wengxt** [comment]
but still, it's weird to allow an relevant application to have such talk-name. I'd rather it to be solved in a proper way, by using the portal dbus name.

**Comment by tinywrkb** [comment]
> it's weird to allow an relevant application to have such talk-name

Is it really something to be concern about? it doesn't own the name.  

Do you see a problem with always creating `org.fcitx.Fcitx-99`?  
The Flatpak Fcitx5 package already creates this interface and I fail to understand its usefulness if relevant Flatpak apps won't access it, though I don't really know what Fcitx is doing so I might be wrong here.  
If Flatpak Fcitx5 already create this interface then why not have the distro Fcitx5 daemon also create it by default?  

```
diff --git a/src/frontend/fcitx4frontend/fcitx4frontend.cpp b/src/frontend/fcitx4frontend/fcitx4frontend.cpp
index f698094..4f5468d 100644
--- a/src/frontend/fcitx4frontend/fcitx4frontend.cpp
+++ b/src/frontend/fcitx4frontend/fcitx4frontend.cpp
@@ -335,6 +335,8 @@ Fcitx4FrontendModule::Fcitx4FrontendModule(Instance *instance)
     // Always create display number zero.
     addDisplay("");

+    addDisplay(":99");
+
     event_ = instance_->watchEvent(
         EventType::InputContextInputMethodActivated, EventWatcherPhase::Default,
         [this](Event &event) {
```

Isn't WPS useful enough to be worth this kind of workaround?  
In any case, the WPS Flatpak changes were already merged so this is solved for the Fcitx5 Flatpak package.

**Comment by wengxt** [comment]
a workaround is a workaround, especially when a proper way exists.

**Comment by wengxt** [comment]
I suggest to use this https://www.csslayer.info/wordpress/fcitx-dev/build-im-module-for-wps/

**Comment by wengxt** [comment]
https://github.com/flathub/com.wps.Office/pull/90

**Comment by tinywrkb** [comment]
Nice! It works perfectly, not sure why it didn't work for me when I built this. Thank you for taking care of this.

**Comment by lmmmmm000** [comment]
This is related to a similar issue I encountered with **Tencent's native Linux WeChat** (微信). The WeChat binary has an embedded fcitx-qt5 (fcitx4 protocol) plugin that hardcodes the D-Bus connection to `org.fcitx.Fcitx` (without any display suffix), but fcitx5's `fcitx4frontend` only registers display-specific names like `org.fcitx.Fcitx-0` and `org.fcitx.Fcitx-1`.

```
# Registered by fcitx5:
  org.fcitx.Fcitx-0       # For DISPLAY=:0
  org.fcitx.Fcitx-1       # For DISPLAY=:1  
  org.fcitx.Fcitx-{N}     # For DISPLAY=:N

# Expected by legacy fcitx4 apps (WeChat, etc.):
  org.fcitx.Fcitx         # ← Not registered!
```

## Workaround

I created a small LD_PRELOAD library that hooks `dbus_message_new_method_call()` to transparently redirect `org.fcitx.Fcitx` → `org.fcitx.Fcitx-0`, bridging the gap:

https://gist.github.com/lmmmmm000/0f8c7698b2c9b143f06577ce89400dbd

## Suggested Fix

Would it be possible for `fcitx4frontend` to also claim the display-agnostic well-known name `org.fcitx.Fcitx` (without suffix) in addition to the display-specific ones? This would maintain backward compatibility with legacy fcitx4 applications that hardcode the old address.

**Comment by lmmmmm000** [comment]
Updated Gist link (with full deployment instructions): https://gist.github.com/lmmmmm000/d55b13a228604ad315e4f14e7d506f03

**Comment by lmmmmm000** [comment]
Full source repository (updated): https://github.com/lmmmmm000/wechat-fcitx4-dbus-hook

**Comment by lmmmmm000** [comment]
Repo has Chinese/English bilingual README now: https://github.com/lmmmmm000/wechat-fcitx4-dbus-hook
