### ISSUE TITLE
Memory not released after Rime deployment

### ISSUE THREAD

**Issue by idnsunset** [fcitx/fcitx5#205]
**Describe the bug**

fcitx5-rime doesn't release the memory allocated for deployment (database build/rebuild). I am using a 40MB dictionary, fcitx5 takes around 1GB RAM for build and never gets it freed until I restart fcitx5. Not sure it is a issue of fcitx5 or librime1.

**To Reproduce**

Just clean up everything inside the `~/.local/share/fcitx5/rime/build` directory and perform a "Deploy" from the tray menu.

**Expected behavior**

The memory allocated for database build should be freed once the build is done.

**Desktop (please complete the following information):**
 - Desktop: i3
 - Display server type: X11
 - OS: Debian Unstable
 - Fcitx5 version: 5.0.3-2

**Comment by wengxt** [comment]
https://github.com/rime/librime/issues/440
