### ISSUE TITLE
aur安装报错

### ISSUE THREAD

**Issue by adaaaaaa** [fcitx/fcitx5#21]
``[ 41%] Built target spell
Scanning dependencies of target spell-en-download
-- Downloading 'https://download.fcitx-im.org/data/en_dict-20121020.tar.gz' to '/tmp/pamac-build-captain/fcitx5-git/src/fcitx5/src/modules/spell/dict/en_dict-20121020.tar.gz'...
CMake Error at spell-en-download-download.cmake:3 (file):
  file DOWNLOAD HASH mismatch

    for file: [/tmp/pamac-build-captain/fcitx5-git/src/fcitx5/src/modules/spell/dict/en_dict-20121020.tar.gz]
      expected hash: [c44a5d7847925eea9e4d2d04748d442cd28dd9299a0b572ef7d91eac4f5a6ceb]
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
             status: [22;"HTTP response code said error"]

make[2]: *** [src/modules/spell/dict/CMakeFiles/spell-en-download.dir/build.make:57：src/modules/spell/dict/CMakeFiles/spell-en-download] 错误 1
make[1]: *** [CMakeFiles/Makefile2:914：src/modules/spell/dict/CMakeFiles/spell-en-download.dir/all] 错误 2

**Comment by wengxt** [comment]
should be fine now
