### ISSUE TITLE
Idea无法输入中文

### ISSUE THREAD

**Issue by Skyxim** [fcitx/fcitx5#212]
在intellij idea中无法输入中文，表现为能够显示候选框，但是选择字后没有如何文字写到文件上，光标也没有移动，代码能够直接编译，说明没有任何键入
系统 Debain bullseye
uname -r
5.10.0-1-amd64
fcitx5 -v
5.0.3

**Comment by wengxt** [comment]
idea 是什么

**Comment by Skyxim** [comment]
> idea 是什么

intellij idea

**Comment by wengxt** [comment]
我在 archlinux 下安装了一个 intellij-idea-community-edition 2021.3.1，测试没有发现什么问题
<img width="248" alt="图片" src="https://user-images.githubusercontent.com/259684/105914405-2ea96380-5fe3-11eb-8537-36d751ab1029.png">

fcitx5-diagnose 的输出请贴一下

**Comment by Skyxim** [comment]
> 我在 archlinux 下安装了一个 intellij-idea-community-edition 2021.3.1，测试没有发现什么问题
> <img alt="图片" width="248" src="https://user-images.githubusercontent.com/259684/105914405-2ea96380-5fe3-11eb-8537-36d751ab1029.png">
> 
> fcitx5-diagnose 的输出请贴一下

感谢回答，我是在文本中没法输入，只有候选框，你这里也是正常的么？在窗口这些我好像没有试过，没注意

**Comment by wengxt** [comment]
<img width="410" alt="图片" src="https://user-images.githubusercontent.com/259684/105929744-1cd4ba00-5ffd-11eb-9442-5d94edbad6c3.png">
看起来没有

再重复一次： fcitx5-diagnose 的输出请贴一下

**Comment by Skyxim** [comment]
# System Info:
1.  `uname -a`:

        Linux debian 5.10.0-1-amd64 #1 SMP Debian 5.10.4-1 (2020-12-31) x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Debian
        Description:	Debian GNU/Linux bullseye/sid
        Release:	testing
        Codename:	bullseye

3.  `lsb_release -d`:

        Description:	Debian GNU/Linux bullseye/sid

4.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

5.  `/etc/os-release`:

        PRETTY_NAME="Debian GNU/Linux bullseye/sid"
        NAME="Debian GNU/Linux"
        ID=debian
        HOME_URL="https://www.debian.org/"
        SUPPORT_URL="https://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  Bash Version:

        BASH_VERSION='5.1.4(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locale:

            C
            C.UTF-8
            POSIX
            en_US.utf8

    2.  Current locale:

            LANG=mn_CN.UTF-8
            LANGUAGE=en_US:zh_CN
            LC_CTYPE=en_US.UTF-8
            LC_NUMERIC="mn_CN.UTF-8"
            LC_TIME="mn_CN.UTF-8"
            LC_COLLATE="mn_CN.UTF-8"
            LC_MONETARY="mn_CN.UTF-8"
            LC_MESSAGES="mn_CN.UTF-8"
            LC_PAPER="mn_CN.UTF-8"
            LC_NAME="mn_CN.UTF-8"
            LC_ADDRESS="mn_CN.UTF-8"
            LC_TELEPHONE="mn_CN.UTF-8"
            LC_MEASUREMENT="mn_CN.UTF-8"
            LC_IDENTIFICATION="mn_CN.UTF-8"
            LC_ALL=

        **Error occurs when running `locale`. Please check your locale settings.**

            locale: Cannot set LC_MESSAGES to default locale: No such file or directory
            locale: Cannot set LC_ALL to default locale: No such file or directory

4.  Directories:

    1.  Home:

            /home/frost

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/frost/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/frost/.config/fcitx5`).

5.  Current user:

    The script is run as frost (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.4`

3.  process:

    Found 1 fcitx5 process:

           1110 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.67`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `1110`.

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    Found fcitx5 kcm module.

        kcm_fcitx5                 - Configure Input Method

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    **Environment variable XMODIFIERS is "@im=fcitx5" instead of "@im=fcitx". Please check if you have exported it incorrectly in any of your init files.**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**

    Xim Server Name from Environment variable is fcitx5.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Environment variable QT_IM_MODULE is "fcitx5" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
    **You may have trouble using fcitx in qt4 programs.**

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

2.  qt5 - `${QT_IM_MODULE}`:

    **Environment variable QT_IM_MODULE is "fcitx5" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
    **You may have trouble using fcitx in qt5 programs.**

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

3.  Qt IM module files:

    Found unknown fcitx qt module: `/usr/lib/x86_64-linux-gnu/fcitx/qt/libfcitx-quickphrase-editor5.so`.
    Found unknown fcitx qt module: `/usr/lib/x86_64-linux-gnu/qt5/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 im module for qt5: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx5-skk-config.so`.
    Found fcitx5 qt5 module: `/usr/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Environment variable GTK_IM_MODULE is "fcitx5" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
    **You may have trouble using fcitx in gtk programs.**

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.24` at `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.24

        Found fcitx5 im modules for gtk `3.24.24`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 32 enabled addons:

            Chewing
            Simplified and Traditional Chinese Translation
            Classic User Inteface
            Clipboard
            Cloud Pinyin
            DBus
            DBus Frontend
            Emoji
            Fcitx4 Frontend
            Full width character
            Hangul
            IBus Frontend
            Lua IME API
            Input method selector
            Keyboard
            KDE Input Method Panel
            Lua Addon Loader
            Status Notifier
            Notification
            Pinyin
            Extra Pinyin functionality
            Punctuation
            Quick Phrase
            Rime
            Skk
            Spell
            Table
            Unicode
            Wayland
            Wayland Input method frontend
            XCB
            X Input Method Frontend

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Inteface
        KDE Input Method Panel

# Log:
1.  `date`:

        Wed Jan 27 12:28:06 CST 2021

2.  `/home/frost/.config/fcitx5/crash.log`:

    `/crash.log` not found.

**Comment by wengxt** [comment]
你的locale （mn_CN.UTF-8）没有生成
鉴于你是debian请参考 https://wiki.debian.org/Locale

正确配置后 locale -a 输出应当显示此项

然后再重启试试

**Comment by cnmade** [comment]
@wengxt 大大。idea 输入其实有个更大的问题，就是输入窗口不能正确跟随的问题。比如windows , mac下面，我们知道输入法的窗口是可以跟随输入光标的，例如这样：
![image](https://user-images.githubusercontent.com/278153/147426571-a5315a79-6589-4080-b2df-4b7523c1ef34.png)
恕本人才疏学浅，没办法定位到问题是JDK 的问题，还是x11的问题？

我猜想很可能是问题出在JDK swing 或者x11 input模块。但是无法确定，所以就不好给jdk 提交bug report

估计有不少人深受这个问题的折磨。

https://youtrack.jetbrains.com/issue/JBR-2460

**Comment by wengxt** [comment]
https://github.com/prehonor/myJetBrainsRuntime/blob/master/idea.patch 

网上流传的给jdk的修复patch，当然是报给jdk

**Comment by cnmade** [comment]
不是JDK开发者，根本就报不上去。。。。哈哈。JDK不接受来自于普通Java 用户的报告。

**Comment by lidaling** [comment]
> 你的locale （mn_CN.UTF-8）没有生成 鉴于你是debian请参考 https://wiki.debian.org/Locale
> 
> 正确配置后 locale -a 输出应当显示此项
> 
> 然后再重启试试

请问 mn_CN是什么编码？
