### ISSUE TITLE
无法找到依赖unicode-cldr-annotations

### ISSUE THREAD

**Issue by updater1234** [fcitx/fcitx5#215]
你好，我在manjaro 20.2上更新fcitx5-git是系统显示如下报错
![2021-01-26 07-35-53屏幕截图](https://user-images.githubusercontent.com/31512600/105779422-51b72180-5fa9-11eb-9bcd-78cff4508db6.png)
请问怎么解决？

**Comment by wengxt** [comment]
╮(￣▽￣)╭  等贵发行版同步 arch 的包。
