### ISSUE TITLE
A solution idea: fcitx5 inaccurate Chinese input position in JB-system IDE

### ISSUE THREAD

**Issue by xmuli** [fcitx/fcitx5#216]
For fcitx5 in the JB system IDE Chinese position input is not accurate, but the input English position is accurate defects.

Is this solution possible?

1. When detecting when you want to input Chinese in the IDE, switch to English mode in the background, and then get the 2. cursor coordinates (which are the correct coordinates at this time)
2. The correct coordinates are sent to the input method display box
3. Then switch to Chinese input box to show the correct position in the IDE

**Comment by yuyichao** [comment]
What do you mean by "inaccurate Chinese input position"? Is it where the text got inserted or where the candidate list overlay window is drawn?

I suspect you mean that when you type in English mode the text got inserted at the right place but when you type in Chinese mode the candidate list isn't draw at the right place. If that's the case, then no, the two has absolutely nothing to do with each other. Neither is under fcitx's control and if the two disagree it's completely the fault of the application. The current input method should not have any effect on this.

**Comment by wengxt** [comment]
There is nothing we can do on fcitx side.

Here's a patch to fix this AFAIK. I'm not sure if anyway has tried to submit it to upstream.

https://github.com/prehonor/myJetBrainsRuntime/blob/master/idea.patch
