### ISSUE TITLE
请问是否有快捷键，能删除在输入时，生成的错误的自造词？

### ISSUE THREAD

**Issue by ajmz** [fcitx/fcitx5#217]
如题。

**Comment by ajmz** [comment]
找到了，默认是control+7，不过为什么叫“忘记词汇”呢？

**Comment by wengxt** [comment]
因为只有用户词库里面的词可以删除，但即使词本身不能删除，也会从输入历史里面清除掉对应词的输入历史（影响词的评分 -> 排序）
