### ISSUE TITLE
关于shift+8修改默认中文乘号×为英文星号*的建议

### ISSUE THREAD

**Issue by just4StoringRepos** [fcitx/fcitx5#223]
我在实际使用中发现fcitx5默认拼音方案中按shift+8默认出的是中文乘号×，但是依我个人有限的经验做出的判断，似乎这个符号的使用频率远低于英文符号*，即使是在中文语境下。所以我建议将其修改成英文星号，请开发者大佬予以考量，谢谢。

另附手动修改的方法如下，方便有相同需求又其他搜索到这一条issue的筒子们
复制目录/usr/share/fcitx5/punctuation/下的相关文件到$HOME/.local/share/fcitx5/punctuation/下，并删除对应*  ×的那一行（在我的系统中是punc.mb.zh_HK、punc.mb.zh_CN punc.mb.zh_TW的第十四行），重启fcitx5

我的环境是：
Debian bullseye
fcitx5                                        5.0.4-3
fcitx5-chinese-addons                         5.0.3-2
fcitx5-chinese-addons-bin                     5.0.3-2
fcitx5-chinese-addons-data                    5.0.3-2
fcitx5-config-qt                              5.0.2-1
fcitx5-data                                   5.0.4-3
fcitx5-frontend-gtk3:amd64                    5.0.3-1
fcitx5-frontend-qt5                           5.0.2-1
fcitx5-material-color                         0.1-1  
fcitx5-module-chttrans:amd64                  5.0.3-2
fcitx5-module-cloudpinyin:amd64               5.0.3-2
fcitx5-module-emoji:amd64                     5.0.4-3
fcitx5-module-fullwidth:amd64                 5.0.3-2
fcitx5-module-pinyinhelper:amd64              5.0.3-2
fcitx5-module-punctuation:amd64               5.0.3-2
fcitx5-module-quickphrase:amd64               5.0.4-3
fcitx5-module-wayland:amd64                   5.0.4-3
fcitx5-module-xorg:amd64                      5.0.4-3
fcitx5-modules:amd64                          5.0.4-3
fcitx5-pinyin:amd64                           5.0.3-2
fcitx5-table:amd64                            5.0.3-2
kde-config-fcitx5:amd64                       5.0.2-1
libfcitx5-qt-data                             5.0.2-1
libfcitx5-qt1:amd64                           5.0.2-1
libfcitx5config6:amd64                        5.0.4-3
libfcitx5core7:amd64                          5.0.4-3
libfcitx5gclient1:amd64                       5.0.3-1
libfcitx5utils2:amd64                         5.0.4-3

**Comment by chenshijie-uos** [comment]
https://github.com/fcitx/fcitx5-chinese-addons/blob/master/modules/punctuation/punc.mb.zh_CN

**Comment by wengxt** [comment]
其实我觉得你说的有道理。对比一些 win 的输入法也是输出 * 

个人使用的时候…从来也没有真的需要输入过这个符号，都是需要输入星号。（特别 Linux 命令需要星号的情况更多）

目前也有很多别的手段可以用于输入这个…

**Comment by wengxt** [comment]
嘛…虽然这么说，但是这个理由也不一定就站得住，因为从输入命令的角度说 ￥ 也不怎么需要…

**Comment by just4StoringRepos** [comment]
哦吼我还真没留意到￥$的问题，大概确实没怎么在中文状态下敲过shift+4
