### ISSUE TITLE
Chrome 和 Chromium 中使用 fcitx5  pinyin 快速打字时字母自动上屏幕

### ISSUE THREAD

**Issue by flerxu** [fcitx/fcitx5#224]
**Describe the bug**
Chrome 和 Chromium中打字时，拼音字母经常自动上屏，特别是快速打字时，出错的概率极大。Firefox 中没有此现象。
比如我这里要打  xian jian , 结果字母 a 自动上屏，成“xian jin” 了。
 
![FireShot Capture 003 - Screenshot at 2021-02-16 00-20-47 png (1920×1080) - ](https://user-images.githubusercontent.com/2485590/107971394-60fc1e80-6fed-11eb-9cc3-fda8baebbb43.png)

又如，下面我要打 “ liao dao xin ting zhuo jiu bei”  , 结果字母 h 自动上屏， 成  “liao dao xin ting zuo jiu bei”
![aaa](https://user-images.githubusercontent.com/2485590/107972249-876e8980-6fee-11eb-9fae-557018526379.png)

**To Reproduce**
Chrome  和 Chromium 中使用 fcitx5 pinyin 快速打字。浏览器扩展全部删除后也是如此。

**Expected behavior**

**Desktop (please complete the following information):**
 - Desktop:  Mate desktop
 - Display server type: X11
 - The output of fcitx5-diagnose if possible.
 - OS:  fedora 33
 - Fcitx Version:  5.0.4
 
**Additional context**

**Comment by wengxt** [comment]
没用 gtk im module，安装 fcitx5-gtk 及配置环境变量
