### ISSUE TITLE
在wayland下，候选框大小出问题

### ISSUE THREAD

**Issue by so1ar** [fcitx/fcitx5#228]
***更新，经过测试，基于gtk的程序候选框大小正常，基于qt的程序运行在wayland模式，候选框就会变小，暂时解决方法是在~/.pam_environment中加入一行QT_QPA_PLATFORM=xcb让qt程序运行在下xwayland模式下，就是会有一定的性能损失。***

**Describe the bug**
以前使用一直很正常，最近一次更新后，在终端输入中文，候选框大小正常，但在浏览器和其他一些软件中输入中文，候选框很小。
![P10222-001229](https://user-images.githubusercontent.com/54471528/108631769-7ae2a900-74a6-11eb-8eae-fb715eb8fe75.jpg)
![P10222-001157](https://user-images.githubusercontent.com/54471528/108631778-8d5ce280-74a6-11eb-9cc6-45d1fafecc40.jpg)
通过鼠标光标可以比较出二者大小不同

**To Reproduce**
1. 打开浏览器，输入中文。
2. 候选框比在终端输入中文小很多。

**Expected behavior**
在所有地方输入中文都有一样的候选框大小。

**Desktop (please complete the following information):**
 - Desktop: Archlinux，5.10.16内核，sway窗口管理器。
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.
 `# 系统信息:
1.  `uname -a`:

        Linux liu 5.10.16-arch1-1 #1 SMP PREEMPT Sat, 13 Feb 2021 20:50:18 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` 未找到.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` 未找到.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://www.archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux

5.  桌面环境：

    无法确定桌面环境。

6.  Bash 版本：

        BASH_VERSION='5.1.4(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':1'

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale：

    1.  全部可用 locale：

            C
            en_US.utf8
            POSIX
            zh_CN.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME="zh_CN.UTF-8"
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/liu

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/liu/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/liu/.config/fcitx5`)。

5.  当前用户：

    脚本作为 liu (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: `5.0.5`

3.  进程：

    找到了 1 个 fcitx5 进程：

           1200 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` 工作正常。

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.9`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `1200`。

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

    **`kcmshell5` 未找到.**

# 前端设置：
## Xim:
1.  `${XMODIFIERS}`:

    **环境变量 XMODIFIERS 的值被设为了“@im=fcitx5”而不是“@im=fcitx”。请检查您是否在某个初始化文件中错误的设置了它的值。**

    **请使用您发行版提供的工具将环境变量 XMODIFIERS 设为 "@im=fcitx" 或者将 `export XMODIFIERS=@im=fcitx` 添加到您的 `~/.xprofile` 中。参见 [输入法相关的环境变量：XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#XMODIFIERS)。**

    从环境变量中获取的 Xim 服务名称为 fcitx5.

2.  根窗口上的 XIM_SERVERS：

    Xim 服务的名称与环境变量中设置的相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **环境变量 QT_IM_MODULE 的值被设为了“fcitx5”而不是“fcitx”。请检查您是否在某个初始化文件中错误的设置了它的值。**
    **您可能会在 qt4 程序中使用 fcitx 时遇到问题.**

    **请使用您发行版提供的工具将环境变量 QT_IM_MODULE 设为 "fcitx" 或者将 `export QT_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中。参见 [输入法相关的环境变量：QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#QT_IM_MODULE)。**

2.  qt5 - `${QT_IM_MODULE}`:

    **环境变量 QT_IM_MODULE 的值被设为了“fcitx5”而不是“fcitx”。请检查您是否在某个初始化文件中错误的设置了它的值。**
    **您可能会在 qt5 程序中使用 fcitx 时遇到问题.**

    **请使用您发行版提供的工具将环境变量 QT_IM_MODULE 设为 "fcitx" 或者将 `export QT_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中。参见 [输入法相关的环境变量：QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#QT_IM_MODULE)。**

3.  Qt 输入法模块文件：

    找到了未知的 fcitx qt 模块：`/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`。
    找到了 fcitx5 的 qt 输入法模块：`/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了 fcitx5 qt5 模块：`/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **环境变量 GTK_IM_MODULE 的值被设为了“fcitx5”而不是“fcitx”。请检查您是否在某个初始化文件中错误的设置了它的值。**
    **您可能会在 gtk 程序中使用 fcitx 时遇到问题.**

    **请使用您发行版提供的工具将环境变量 GTK_IM_MODULE 设为 "fcitx" 或者将 `export GTK_IM_MODULE=fcitx` 添加到您的 `~/.xprofile` 中。参见 [输入法相关的环境变量：GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-cn#GTK_IM_MODULE)。**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        在 `/usr/bin/gtk-query-immodules-2.0` 找到了 gtk `2.24.33` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        在 `/usr/bin/gtk-query-immodules-3.0` 找到了 gtk `3.24.25` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.25

        已找到 gtk `3.24.25` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        在 `/usr/lib/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.25` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.25

        已找到 gtk `3.24.25` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **无法找到 gtk 4 的输入法模块缓存**

        **无法在缓存中找到 gtk 4 的 fcitx5 输入法模块。**

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 27 个已启用的插件：

            Simplified and Traditional Chinese Translation
            Classic User Inteface
            Clipboard
            Cloud Pinyin
            DBus
            DBus Frontend
            Emoji
            Fcitx4 Frontend
            Full width character
            IBus Frontend
            Input method selector
            Keyboard
            KDE Input Method Panel
            Status Notifier
            Notification
            Pinyin
            Extra Pinyin functionality
            Punctuation
            Quick Phrase
            Rime
            Spell
            Table
            Unicode
            Wayland
            Wayland Input method frontend
            XCB
            X Input Method Frontend

    2.  找到了 0 个被禁用的插件：

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 2 个已启用的用户界面插件：

        Classic User Inteface
        KDE Input Method Panel

# 日志：
1.  `date`:

        2021年 02月 22日 星期一 00:37:56 CST

2.  `/home/liu/.config/fcitx5/crash.log`:

        =========================
        Fcitx 4.99.0 -- Get Signal No.: 11
        Date: try "date -d @1598511685" if you are using GNU date ***
        ProcessID: 1892
        /usr/bin/fcitx5(+0x9cfe)[0x55a734aa6cfe]
        /usr/lib/libc.so.6(+0x3d6a0)[0x7f2a1b9216a0]
        /usr/lib/fcitx5/wayland.so(+0xd3ce)[0x7f2a1adff3ce]
        /usr/lib/fcitx5/wayland.so(+0x1a8b9)[0x7f2a1ae0c8b9]
        /usr/lib/libffi.so.7(+0x6a8d)[0x7f2a1be67a8d]
        /usr/lib/libffi.so.7(+0x601b)[0x7f2a1be6701b]
        /usr/lib/libwayland-client.so.0(+0x9e92)[0x7f2a1adb5e92]
        /usr/lib/libwayland-client.so.0(+0x66c1)[0x7f2a1adb26c1]
        /usr/lib/libwayland-client.so.0(wl_display_dispatch_queue_pending+0x7c)[0x7f2a1adb3ccc]
        /usr/lib/fcitx5/wayland.so(+0x9000)[0x7f2a1adfb000]
        /usr/lib/fcitx5/wayland.so(+0x910e)[0x7f2a1adfb10e]
        /usr/lib/libFcitx5Utils.so.2(+0x345f5)[0x7f2a1bd1d5f5]
        /usr/lib/libsystemd.so.0(+0x5bb57)[0x7f2a1b818b57]
        /usr/lib/libsystemd.so.0(sd_event_dispatch+0x16e)[0x7f2a1b81a21e]
        /usr/lib/libsystemd.so.0(sd_event_run+0x99)[0x7f2a1b81c6a9]
        /usr/lib/libsystemd.so.0(sd_event_loop+0x58)[0x7f2a1b81c8c8]
        /usr/lib/libFcitx5Utils.so.2(_ZN5fcitx9EventLoop4execEv+0x12)[0x7f2a1bd1d6d2]
        /usr/lib/libFcitx5Core.so.6(_ZN5fcitx8Instance4execEv+0x4e)[0x7f2a1bde172e]
        /usr/bin/fcitx5(+0x8b82)[0x55a734aa5b82]
        /usr/lib/libc.so.6(__libc_start_main+0xf2)[0x7f2a1b90c152]
        /usr/bin/fcitx5(+0x8f6e)[0x55a734aa5f6e]

`

**Additional context**

**Comment by wengxt** [comment]
你如果在 classicui 里改字体设置，字体大小会变化么

**Comment by so1ar** [comment]
> 你如果在 classicui 里改字体设置，字体大小会变化么

抱歉这么久才回复消息。

我修改字体大小，候选框大小确实会变，但是基于qt程序候选框大小还是会比gtk程序小，我又试着把设置里面“按屏幕DPI使用”选项关掉，现在所有界面候选框大小都一致了，问题解决😂️
![1614056271_grim](https://user-images.githubusercontent.com/54471528/108804084-44f11200-75d7-11eb-8c6a-14bbff9a5ff2.png)
