### ISSUE TITLE
[Question] Where can I get instructions to create an IME for fcitx?

### ISSUE THREAD

**Issue by krafi99** [fcitx/fcitx5#230]
_As the title _says__

**Comment by wengxt** [comment]
currently there’s not one for fcitx5 yet (some doc still in my todo)

but you could start with an existing engine code.

Basically it will focus on implementing InputMethodEngine::keyEvent part.

I saw you want to have add some support for openbangla, so I guess you can just take the process_key_event and reimplement it in fcitx.

This is a simple engine to look at:
https://github.com/fcitx/fcitx5-sayura/tree/master/src

I think you could get how to install the required files for fcitx and do cmake setup for it.

SayuraEngine is the implementation for the InputMethodEngine class. SayuraState is the data that associate with a specific input context (you could think a input context is an application using input method).

**Comment by krafi99** [comment]
Actually, I wanted the instructions only to provide them to the devs of OpenBangla. But, as you already came to know that, please provide the instructions to devs and help them make it. I'll also collaborate if I can. 😄

**Comment by wengxt** [comment]
@krafi99 I already did the implementation and send a PR: https://github.com/OpenBangla/OpenBangla-Keyboard/pull/202

**Comment by wengxt** [comment]
https://fcitx-im.org/wiki/Develop_an_simple_input_method likely we'll go from there WIP.

**Comment by wengxt** [comment]
The initial version of instruction is finished. Close for now.
