### ISSUE TITLE
Is there a easy way to send a key to current IM?

### ISSUE THREAD

**Issue by mrbeardad** [fcitx/fcitx5#232]
I'm using fcitx5-rime，and I want to send a key to rime in order to switch between chinese mode and latin mode automatically.
Is therea easy way to do this?

PS: `fcitx5-remote -c` is not good enough for some reason.

**Comment by wengxt** [comment]
No.

**Comment by wengxt** [comment]
if you want to simulate a X key, use xdotool.

**Comment by mrbeardad** [comment]
> if you want to simulate a X key, use xdotool.

thanks for your reply
