### ISSUE TITLE
无法正常打出“艽”（q iu）字

### ISSUE THREAD

**Issue by fanganpai** [fcitx/fcitx5#236]
艽(q iu / j iao)是多音字，使用fcitx5时只能通过jiao打出艽，qiu无法打出艽

**Comment by YQ-YSY** [comment]
如果 Fcitx5 带有“单手笔顺输入法”编码，
遇到不会念、不会读的字，例如：这个“艽”字，就太容易打了：
六全码：1735，17 是 艹 ；35是 九 。
笔顺码：12235，122 是 艹 ；35是 九 。

所以再次建议：把“单手笔顺输入法”的码表，加入 Fcitx 的码表输入法中，
不论是作为”拼音的补充“，还是作为”单独的输入法“，都是好事。
更何况，数字编码并不影响拼音、英文的输入，可以同时存在。

已经有可用的“ 单手笔顺输入法（2.0版）软件”
基于 Rime 输入法引擎，支持Windows及Linux系统：
https://github.com/YQ-YSY/one-hand_Rime
目前，2.0版，我用了8个月，一直用一直爽，哈哈哈！

**Comment by wengxt** [comment]
https://github.com/fcitx/libime/commit/1cbdc65c91c38dd1d2147190d75f987de458c3ba Fixed
