### ISSUE TITLE
[Question] config files unlinked automatically after restart

### ISSUE THREAD

**Issue by owarai** [fcitx/fcitx5#240]
I manage my dotfiles through symbolic links, so that these configurations can be concentrated in one place,
But in the process of managing fcitx5 in this way, I found that after each restart, part of fcitx5
config file will automatically unlink and regenerate a corresponding file in its `xdg-config-dir`(`.config/fcitx5/`), like `profile`, `conf/pinyin.conf`.

Is this intentional or a bug?

P.S.: I **dotfile** fcitx5 config in file-level, because I don't want to manage all of fcitx5 configs(like `conf/cached_layouts` etc).

**Comment by wengxt** [comment]
To ensure the file is saved atomically, the file is always saved by
1. create a new temp file
2. write data
3. unlink the old file
4. rename the temp file

right now if you want to use symlink, you’d better do it on the directory instead of on the file.

**Comment by owarai** [comment]
Thanks, I will do as you suggested.
