### ISSUE TITLE
[Question] us-acentos keyboard layout name

### ISSUE THREAD

**Issue by rafaeor** [fcitx/fcitx5#242]
I'm new to linux using manjaro and began to use fcitx5. I wanted to configure my keyboard(US) to be able to make accents like [á], however I just found us keyboard layout in fcitx5 configuration interface.
I know the name of keyboard is "us-acentos", cant find the fcitx5 in ~/.local/share/fcitx5(No such file or directory) for changing it, so I depend on the configuration interface.
Tested a lot of keyboards and could not find the one to make accents with the English keyboard, whats the name of it? Tried to Google it but didin't find anything usefull

![Screenshot_20210312_004421](https://user-images.githubusercontent.com/80478882/110888996-1740e400-82cc-11eb-9af1-e52dfa61a726.png)

**Comment by wengxt** [comment]
I'm not so sure, but it might be "English (US, intl., with dead keys)"? This is I found via google that seems to match us-acentos.
us-acentos is the virtual console layout, not a X11 layout.

Fcitx's data is from /usr/share/X11/xkb/rules/evdev.xml , if can't find the corresponding layout in it, you should report it to xkeyboard-config on bugs.freedesktop.org

As for typing accent, you may also try Compose key? (E.g. set compose key to caps lock)

If you eventually found evdev.xml doesn't contain thet layout you want, I just wrote a blog post to explain how to setup a custom layout: https://www.csslayer.info/wordpress/fcitx-dev/how-to-use-a-missing-keyboard-layout-in-fcitx-5/

**Comment by siikamiika** [comment]
I just want to say that I've needed this feature for ~5 years but edited `evdev.xml` directly instead. Thanks so much!

There's a small typo in the article:
`~/.local/share/fcitx5inputmethod/keyboard-br-abnt2.conf`
should be
`~/.local/share/fcitx5/inputmethod/keyboard-br-abnt2.conf`

**Comment by wengxt** [comment]
@siikamiika  thanks, fixed in the post.
