### ISSUE TITLE
[Question] How to disable ime switch in program

### ISSUE THREAD

**Issue by plusls** [fcitx/fcitx5#243]
对于一个自己开发的程序，我希望在某些时候屏蔽掉输入法切换，只有在输入文本的时候允许切换输入法，应该怎么去实现呢？

fcitx5-remote 只能实现切换，貌似并不能实现禁用

**Comment by wengxt** [comment]
主要还是看你的程序是用什么实现的，例如 Qt：
https://doc.qt.io/qt-5/qt.html#InputMethodQuery-enum 可以通过这个属性设置某个 widget 不接受输入法

https://developer.gnome.org/gtk3/stable/GtkEntry.html 设置 im-module 属性为 gtk-im-context-simple

至于其他情况，不把按键发给输入法不就不能切换了么

**Comment by plusls** [comment]
对于java程序呢？应该如何阻止发送按键给输入法呢

**Comment by chenshijie-uos** [comment]
也许你可以动态修改当前运行程序的环境变量来解决这个问题。

可以正常切换，输入汉字的情况下是这样的。
GTK_IM_MODULE DEFAULT=fcitx
QT_IM_MODULE  DEFAULT=fcitx
XMODIFIERS    DEFAULT=\@im=fcitx
SDL_IM_MODULE DEFAULT=fcitx

在不想切换的时候，不想输入汉字的时候把当前程序的环境变量改成错的
GTK_IM_MODULE DEFAULT=ffcciittxx
QT_IM_MODULE  DEFAULT=ffcciittxx
XMODIFIERS    DEFAULT=\@im=ffcciittxx
SDL_IM_MODULE DEFAULT=ffcciittxx

**Comment by plusls** [comment]
emmm 试了一下好像不行，用 jni 的 put env 和 java 的反射都不行，不太理解具体的运作jili

底层调用的 lwjgl3

**Comment by plusls** [comment]
翻了一下代码，底层调用的 glfw，其使用了 XIM 协议来支持输入法

但是 glfw 本身并没有提供屏蔽输入法的接口，一接收到按键输入就会调用 Xutf8LookupString 来通知输入法，貌似没有特别优雅的方式来阻止它发送按键给输入法

主要是在 windows 上可以使用 ImmAssociateContext 来屏蔽掉输入法的输入，因此才询问 fcitx5 有没有类似的接口，毕竟都有类似 fcitx5-remote 这样切换输入法的 DBUS rpc

**Comment by wengxt** [comment]
这显然看起来就没啥希望了啊……XIM 的 input context 你没办法在程序内获得对应这个程序自己的信息，根本做不到只禁用这一个程序的

真要写只能整个系统一起

**Comment by plusls** [comment]
> 这显然看起来就没啥希望了啊……XIM 的 input context 你没办法在程序内获得对应这个程序自己的信息，根本做不到只禁用这一个程序的
> 
> 真要写只能整个系统一起

啊我还以为能像 windows 一样，让输入法不处理这个窗口的输入，就算数据发过来也不处理
