### ISSUE TITLE
在多屏幕 PC 上 fcitx5 候选窗口的定位问题（大概是这样描述）

### ISSUE THREAD

**Issue by LuXts** [fcitx/fcitx5#246]
**Describe the bug**
主要看截图，截图里面显示了候选框在不同屏幕会有不一样的绘制行为的问题。

**To Reproduce**
在第二块屏幕边缘打字。
截图：
第一张截图：看不到候选词。
![Screenshot_20210321_120340](https://user-images.githubusercontent.com/49251098/111893687-6232c800-8a3f-11eb-8acd-62c37020fcd1.png)
第二张截图：在左半边屏幕上可以在一个屏幕上看到候选词。
![Screenshot_20210321_120512](https://user-images.githubusercontent.com/49251098/111893731-9f975580-8a3f-11eb-9c42-bc4ecbeb7687.png)

**Desktop (please complete the following information):**
 - Desktop: (KDE)
 - Display server type: X11
 - Fcitx 5.0.5-1

**Comment by wengxt** [comment]
Duplicate of 239
