### ISSUE TITLE
使用双拼的时候 `alt + 字母' 输出字母

### ISSUE THREAD

**Issue by K-gihu** [fcitx/fcitx5#249]
**Describe the bug**
使用双拼（Shuangpin）输入法的时候，在多个应用程序下（比如在火狐中使用 ‘alt+d' ，在 emacs 中使用 alt+x'），使用带 alt 的快捷键的时候都会输出字母，而非运行快捷键的功能。而使用 rime 的时候不会有这个问题

**Desktop (please complete the following information):**
 - Desktop: xfce4 + bspwm
 - Display server type: X11
 - The output of fcitx5-diagnose if possible：
 # 系统信息:
1.  `uname -a`:

        Linux arch 5.11.7-arch1-1 #1 SMP PREEMPT Wed, 17 Mar 2021 16:59:58 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	1.4
        Distributor ID:	Arch
        Description:	Arch Linux
        Release:	rolling
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	Arch Linux

4.  `/etc/lsb-release`:

        LSB_VERSION=1.4
        DISTRIB_ID=Arch
        DISTRIB_RELEASE=rolling
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://www.archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux

6.  桌面环境：

    桌面环境为 `xfce`。

7.  Bash 版本：

        BASH_VERSION='5.1.4(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':0.0'

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale：

    1.  全部可用 locale：

            C
            en_US.utf8
            POSIX
            zh_CN.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME="zh_CN.UTF-8"
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/klu

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/klu/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/klu/.config/fcitx5`)。

5.  当前用户：

    脚本作为 klu (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: `5.0.6`

3.  进程：

    找到了 2 个 fcitx5 进程：

            800 fcitx5
          76338 fcitx5-config-q

4.  `fcitx5-remote`:

    `fcitx5-remote` 工作正常。

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.21505`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `800`。

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

    **`kcmshell5` 未找到.**

# 前端设置：
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    Xim 服务的名称与环境变量中设置的相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

3.  Qt 输入法模块文件：

    找到了未知的 fcitx qt 模块：`/usr/lib/office6/qt/plugins/inputmethods/libqim-fcitx.so`。
    找到了未知的 fcitx qt 模块：`/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`。
    找到了 fcitx5 的 qt 输入法模块：`/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了 fcitx5 qt5 模块：`/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

2.  `gtk-query-immodules`:

    1.  gtk 2:

        在 `/usr/bin/gtk-query-immodules-2.0` 找到了 gtk `2.24.33` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        在 `/usr/bin/gtk-query-immodules-3.0` 找到了 gtk `3.24.27` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.27

        已找到 gtk `3.24.27` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        在 `/usr/lib/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.27` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.27

        已找到 gtk `3.24.27` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **无法找到 gtk 4 的输入法模块缓存**

        **无法在缓存中找到 gtk 4 的 fcitx5 输入法模块。**

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 15 个已启用的插件：

            Simplified and Traditional Chinese Translation
            Classic User Inteface
            Cloud Pinyin
            DBus
            DBus Frontend
            Keyboard
            Status Notifier
            Notification
            Pinyin
            Punctuation
            Rime
            Table
            Unicode
            XCB
            X Input Method Frontend

    2.  找到了 12 个被禁用的插件：

            Clipboard
            Emoji
            Fcitx4 Frontend
            Full width character
            IBus Frontend
            Input method selector
            KDE Input Method Panel
            Extra Pinyin functionality
            Quick Phrase
            Spell
            Wayland
            Wayland Input method frontend

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 1 个已启用的用户界面插件：

        Classic User Inteface

# 日志：
1.  `date`:

        2021年 03月 23日 星期二 10:12:20 CST

2.  `/home/klu/.config/fcitx5/crash.log`:

    `/crash.log` 未找到.

**Comment by wengxt** [comment]
不能重现。我在 firefox 比如网页中输入框直接 alt + d 可以直接聚焦地址栏。

用如下命令启动之后，在你觉得有问题的程序里按对应按键有什么效果？
fcitx5 -rd --verbose=key_trace=5

**Comment by K-gihu** [comment]
我测试了使用双拼和英文输入法，二者输出的结果是一致的：

    D2021-03-23 10:41:10.554948 instance.cpp:954] KeyEvent: Key(Alt_L states=0) rawKey: Key(Alt_L states=0) origKey: Key(Alt_L states=0) Release:0
    D2021-03-23 10:41:10.555233 inputcontext.cpp:230] KeyEvent handling time: 0ms
    D2021-03-23 10:41:10.585486 instance.cpp:954] KeyEvent: Key(Alt+D states=8) rawKey: Key(Alt+d states=8) origKey: Key(Alt+d states=8) Release:0
    D2021-03-23 10:41:10.585869 inputcontext.cpp:230] KeyEvent handling time: 0ms
    D2021-03-23 10:41:10.658710 instance.cpp:954] KeyEvent: Key(Alt+Alt_L states=8) rawKey: Key(Alt+Alt_L states=8) origKey: Key(Alt+Alt_L states=8) Release:1
    D2021-03-23 10:41:10.659026 inputcontext.cpp:230] KeyEvent handling time: 0ms
    D2021-03-23 10:41:10.661935 instance.cpp:954] KeyEvent: Key(d states=0) rawKey: Key(d states=0) origKey: Key(d states=0) Release:1
    D2021-03-23 10:41:10.662173 inputcontext.cpp:230] KeyEvent handling time: 0ms

**Comment by wengxt** [comment]
你先更新一下 fcitx5 和 fcitx5-gtk 看看有没有变化，然而我确实不论是 emacs 还是 firefox 都不能重现你描述的问题

**Comment by wengxt** [comment]
你在哪输入的 alt + d？能不能用 screen key 录制个屏幕？
另外你有没有什么特别的和键盘相关的设置？（例如 xmodmap 之类）

**Comment by K-gihu** [comment]
也不知是啥原因，我把双拼的设置恢复默认然后重启输入法，但问题依旧存在，又过了一会问题没了。现在暂且这么用吧。麻烦您了。
