### ISSUE TITLE
切换输入法提示框没有了

### ISSUE THREAD

**Issue by so1ar** [fcitx/fcitx5#250]
**Describe the bug**
切换输入法提示框没有了，只剩一个方框，但是正常输入时候选框还在。
![P10324-200533(1)](https://user-images.githubusercontent.com/54471528/112308427-17ce7700-8cdd-11eb-92d1-f8a2966c9cd4.jpg)

**To Reproduce**
1. 启动输入法；
2. 使用快捷键切换输入法。

**Expected behavior**

**Desktop (please complete the following information):**
 - Desktop: sway
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

**Additional context**

**Comment by wengxt** [comment]
你这个黑 是你主题本来就黑还是…

能不能把你的主题打包发来看看

所有程序都是这样？

**Comment by so1ar** [comment]
> 你这个黑 是你主题本来就黑还是…
> 
> 能不能把你的主题打包发来看看
> 
> 所有程序都是这样？

主题本来就是黑色的，我用的是这个主题https://github.com/xTpx/Psionics-Remix

试了一圈发现还是和这个“按屏幕dpi使用”有关，勾选上就有提示框，但是这样的话qt程序候选框就会很小，不勾选切换输入法就没有提示框
![1616599116_grim](https://user-images.githubusercontent.com/54471528/112335543-4bb69600-8cf7-11eb-89e1-5f1fdb2a4a97.png)

**Comment by wengxt** [comment]
启动一个 Qt 程序，然后在终端运行
qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
我想看看你 qt 是用 wayland 还是 X

**Comment by wengxt** [comment]
不过 qt client side ui 就根本不管这个 DPI 选项，推测应该是 X 的。

那就再贴一下你的 xrandr 输出吧

**Comment by wengxt** [comment]
ok 调整了一下 dpi = 96 重现了

**Comment by so1ar** [comment]
> ok 调整了一下 dpi = 96 重现了

啊这，还要我贴输出吗，我都上床准备睡觉了

**Comment by wengxt** [comment]
不用
so1ar ***@***.***>于2021年3月24日 周三08:58写道：

**Comment by wengxt** [comment]
晚安

so1ar ***@***.***>于2021年3月24日 周三08:58写道：

**Comment by wengxt** [comment]
你可以更新 fcitx5 / fcitx5-gtk 试试…虽然感觉是个 cairo 的 bug，但是 workaround 了一下。

**Comment by wengxt** [comment]
针对你这个主题，也有一个 workaround 的办法，你把里面某个 =33 改成 =10 即可。

**Comment by wengxt** [comment]
https://github.com/xTpx/Psionics-Remix/pull/1
