### ISSUE TITLE
无法改变默认候选页大小

### ISSUE THREAD

**Issue by fanganpai** [fcitx/fcitx5#253]
我已经设置了：
~/.config/fcitx5/config:
……
DefaultPageSize=8
……

~/.config/fcitx5/conf/pinyin.conf:
……
PageSize=8
……

然而候选词还是只有5个，并且在重启fcitx5后，第二个文件被自动修改回PageSize=5.

OS:Manjaro 21.0
Kernel: Linux 5.9.16
Desktop: KDE
Display server type: X11

**Comment by wengxt** [comment]
要用配置工具，否则你只能在fcitx退出时再修改。
