### ISSUE TITLE
[Question] Where should I put the `punc.mb.zh_CN` file?

### ISSUE THREAD

**Issue by HnHareJin** [fcitx/fcitx5#255]
As the title says, I want to custom punctuation for myself, but I don't know which subdirectory of `~/.config/fcitx5` should I put the file.
A easy way is modify `/usr/share/fcitx5/punctuation/punc.mb.zh_CN` directly, but can not sync between multiple machine or a new machine.

**Comment by wengxt** [comment]
because it should be under ~/.local/share/fcitx5/punctuation
