### ISSUE TITLE
用泰文时，numpad 和 键盘上的数字不分开。

### ISSUE THREAD

**Issue by pypeetpy** [fcitx/fcitx5#256]
按numpad 的数字比如 5 会出现ถ 按 1 出现ๅ

**Comment by wengxt** [comment]
哪个泰文？

**Comment by pypeetpy** [comment]
![Uploading 2021-04-05-03:59:35.png…]()

**Comment by xingwozhonghua** [comment]
https://github.com/fcitx/fcitx5-libthai/blob/master/src/engine.cpp#L106

here？

**Comment by wengxt** [comment]
@xingwozhonghua , no that's irrelevant. his using thai from table engine.
