### ISSUE TITLE
Android Studio 中文输入乱码

### ISSUE THREAD

**Issue by thetaprimeprime** [fcitx/fcitx5#258]
**Describe the bug**
升级到 Fcitx 5.0.7 后，在 Android Studio 中输入后，输入的不是汉字，而是乱码。升级前没有这个问题。

**To Reproduce**
1. 打开 Android Studio 
2. 找到任意可输入的地方
3. 尝试输入“一二三”
4. 实际上输入的是 “ä¸äºä¸”

**Expected behavior**
不出现乱码

**Desktop (please complete the following information):**
 - Desktop: (GNOME 3.38.5)
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.
[diagnose.log](https://github.com/fcitx/fcitx5/files/6268479/diagnose.log)

**Additional context**
Android Studio 版本 4.1.3

**Comment by wengxt** [comment]
……你是不是也和 https://github.com/fcitx/fcitx5/issues/254 一样没更新 xcb-imdkit ？……

**Comment by thetaprimeprime** [comment]
> ……你是不是也和 #254 一样没更新 xcb-imdkit ？……

确实是
