### ISSUE TITLE
How to use fcitx5 under wayland

### ISSUE THREAD

**Issue by xeechou** [fcitx/fcitx5#259]
fcitx开发者你好，我是[taiwins](https://github.com/taiwins/taiwins)的维护者。taiwins是一个wayland compositor，我实现了text_input_v3和input_method_v2两个协议，但是现在不知道如何测试，也不知道有哪些client是支持text_input_v3。

我想请问一下你们有没有在wayland环境下做过测试？有使用了哪些compositor？测试的过程是什么样子的。

不好意思我并没有看过fcitx的代码，只是用Terminal跑了一下fcitx，根据log fcitx在bind input method manager之后就没有更新的操作了。

**Comment by wengxt** [comment]
你可以用 GTK_IM_MODULE=wayland gtk3-demo 来测试
