### ISSUE TITLE
"fcitx" does not work in qt5-based applications in Crostini (Linux container in chrome OS)

### ISSUE THREAD

**Issue by eliranwong** [fcitx/fcitx5#26]
I did a lot of testings on running "fcitx" in Crostini on my chromebook.

I recorded all my setups of "fcitx" at: https://github.com/eliranwong/Chrome-OS-Linux/blob/master/non-english/chinese.md#inputs

In my testings, "fcitx" works with the following applications:
LibreOffice, WPS office, Dolphin, Thunar, Atom, Geany, Leafpad, etc.

However, not all Linux applications work with "fcitx" in Crostini.

Running "im-config", the message there tells me that it supports gtk2, gtk3 & qt4 frontends. It does not mention qt5. Even we installed fcitx-frontend-qt5, I haven't managed to run "fcitx" in Qt5-based applications we tested.

I also tried to manually copy /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so to /Qt/plugins/platforminputcontexts/ folder of Qt5-based applications, but it does not work.

Please advise.  Thanks in advance.

**Comment by wengxt** [comment]
You should send question to mailing list instead of  issue (not to mention this is a fcitx 5 repo).

But following this blog post might help.
https://www.csslayer.info/wordpress/fcitx-dev/how-to-use-fcitx-on-ubuntu-17-10/
