### ISSUE TITLE
HELP: How to set comma and period as prevPage and nextPage key

### ISSUE THREAD

**Issue by zyf0330** [fcitx/fcitx5#261]

**Comment by wengxt** [comment]
Usually you'll need to go into each input method its own configuration to set it.

E.g. Pinyin.
<img width="659" alt="图片" src="https://user-images.githubusercontent.com/259684/114635717-296ec300-9c7a-11eb-92f0-9df49ed66db0.png">

If you're talking about the default for modules like quickphrase, then it's in global config.

**Comment by zyf0330** [comment]
![image](https://user-images.githubusercontent.com/11958657/114644600-62567880-9d0a-11eb-94a2-47b0b326e12a.png)
This is my config file, it works now.
