### ISSUE TITLE
无法在Chrome(Wayland)中使用fcitx5

### ISSUE THREAD

**Issue by thep0y** [fcitx/fcitx5#263]
**Describe the bug**
不能在Wayland启动的Chrome中使用fcitx5输入法

**To Reproduce**
1. 启动 Chrome
```shell
/usr/bin/google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland
```
2. 在任何输入框中都无法输入中文

**Expected behavior**
正常输入中文

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.
<details>
<summary>fcitx5-diagnose输出结果</summary>

# 系统信息:
1.  `uname -a`:

        Linux thepoy-archlinux 5.11.13-arch1-1 #1 SMP PREEMPT Sat, 10 Apr 2021 20:47:14 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` 未找到.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` 未找到.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://www.archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux

5.  桌面环境：

    桌面环境为 `kde`。

6.  Bash 版本：

        BASH_VERSION='5.1.4(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':1'

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)" };
                xkb_types     { include "complete"      };
                xkb_compat    { include "complete"      };
                xkb_symbols   { include "pc+us+inet(evdev)"     };
                xkb_geometry  { include "pc(pc105)"     };
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale：

    1.  全部可用 locale：

            C
            POSIX
            zh_CN.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME=zh_CN.UTF-8
            LC_COLLATE=C
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/thepoy

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/thepoy/.config`)。

    3.  Fcitx Settings Directory:

        Current fcitx settings directory is `~/.config/fcitx5` (`/home/thepoy/.config/fcitx5`).

5.  当前用户：

    脚本作为 thepoy (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  版本：

    Fcitx 版本: `5.0.7`

3.  进程：

    Found 1 fcitx process:

           6219 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` 工作正常。

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.171`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `6219`。

# Fcitx 配置界面：
1.  配置工具封装：

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  用于 gtk2 的配置界面：

    **未找到 gtk2 的配置界面.**

3.  用于 gtk3 的配置界面：

    **未找到 gtk3 的配置界面.**

4.  KDE 的配置界面：

    Found fcitx kcm module.

        kcm_fcitx5                 - 配置输入法

# 前端设置：
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    Xim 服务的名称与环境变量中设置的相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

3.  Qt 输入法模块文件：

    Found unknown fcitx5 qt module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for Qt5: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 im module for Qt5: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx5 qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    **Cannot find fcitx input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`。**

        **Cannot find fcitx im module for gtk 2.**

    2.  gtk 3:

        在 `/usr/bin/gtk-query-immodules-3.0` 找到了 gtk `3.24.28` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.28

        Found fcitx im modules for gtk `3.24.28`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        **无法找到 gtk 2 的输入法模块缓存**

        **Cannot find fcitx im module for gtk 2 in cache.**

    2.  gtk 3:

        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.28` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.28

        Found fcitx im modules for gtk `3.24.28`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    Found fcitx addon config directory: `/usr/share/fcitx5/addon`.

2.  插件列表：

    1.  找到了 20 个已启用的插件：

            Classic User Inteface
            Clipboard
            DBus
            DBus Frontend
            Emoji
            Fcitx4 Frontend
            IBus Frontend
            Input method selector
            Keyboard
            KDE Input Method Panel
            Status Notifier
            Notification
            Quick Phrase
            Rime
            Spell
            Unicode
            Wayland
            Wayland Input method frontend
            XCB
            X Input Method Frontend

    2.  找到了 0 个被禁用的插件：

3.  插件库: 

    **无法找到插件 `Rime` 的文件 `export:rime`。**

4.  用户界面：

    找到了 2 个已启用的用户界面插件：

        Classic User Inteface
        KDE Input Method Panel

## Input Methods:
1.  Found 2 enabled input methods:

        默认
        rime

2.  Default input methods:

    **Your first (default) input method is 默认 instead of a keyboard input method. You may have trouble deactivate fcitx.**

# 日志：
1.  `date`:

        2021年 04月 15日 星期四 08:23:04 CST

2.  `~/.config/fcitx5/log/`:

    `~/.config/fcitx5/log/` 未找到.
</details>

**Comment by wengxt** [comment]
please report to chrome.

**Comment by thep0y** [comment]
你好，请问能否告诉我应该报告什么问题给chromium。

**Comment by wengxt** [comment]
They just don't' support input method. You can report it as a general problem.

Also you might want to mention that OzoneWayland does not use Gtk im module (not so sure if they want to resolve it this way).

**Comment by wengxt** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1183262&q=ime%20wayland&can=2 You can follow this actually.

**Comment by ztoiax** [comment]
i have the same problem,but i use x11.When I upgrade to chrome 90,fcitx5-chinese-addons doesn't work

**Comment by wengxt** [comment]
@ztoiax that's unlikely to be the same problem. You'd better check fcitx5-diagnose for more information.

Also chrome all works for me.

**Comment by ztoiax** [comment]
> @ztoiax that's unlikely to be the same problem. You'd better check fcitx5-diagnose for more information.
> 
> Also chrome all works for me.

我已经解决了,是我卸载错包了

**Comment by darrist** [comment]
Do you have a solution for this? I am currently using

.pam_environment
```
# Wayland compatibility
QT_QPA_PLATFORM         DEFAULT=wayland
CLUTTER_BACKEND         DEFAULT=wayland
SDL_VIDEODRIVER         DEFAULT=wayland
MOZ_ENABLE_WAYLAND      DEFAULT=1
MOZ_WEBRENDER           DEFAULT=1
XDG_SESSION_TYPE        DEFAULT=wayland
XDG_CURRENT_DESKTOP     DEFAULT=sway

# QT-related theming
QT_QPA_PLATFORMTHEME    DEFAULT=qt5ct

# FCITX input-related
#GLFW_IM_MODULE         DEFAULT=ibus
GLFW_IM_MODULE          DEFAULT=fcitx
GTK_IM_MODULE           DEFAULT=fcitx
INPUT_METHOD            DEFAULT=fcitx
XMODIFIERS              DEFAULT=@im=fcitx
IMSETTINGS_MODULE       DEFAULT=fcitx
QT_IM_MODULE            DEFAULT=fcitx
```

It doesn't work in Chromium, but apps like Telegram can use the input.

**Comment by thep0y** [comment]
> Do you have a solution for this? I am currently using
> 
> .pam_environment
> 
> ```
> # Wayland compatibility
> QT_QPA_PLATFORM         DEFAULT=wayland
> CLUTTER_BACKEND         DEFAULT=wayland
> SDL_VIDEODRIVER         DEFAULT=wayland
> MOZ_ENABLE_WAYLAND      DEFAULT=1
> MOZ_WEBRENDER           DEFAULT=1
> XDG_SESSION_TYPE        DEFAULT=wayland
> XDG_CURRENT_DESKTOP     DEFAULT=sway
> 
> # QT-related theming
> QT_QPA_PLATFORMTHEME    DEFAULT=qt5ct
> 
> # FCITX input-related
> #GLFW_IM_MODULE         DEFAULT=ibus
> GLFW_IM_MODULE          DEFAULT=fcitx
> GTK_IM_MODULE           DEFAULT=fcitx
> INPUT_METHOD            DEFAULT=fcitx
> XMODIFIERS              DEFAULT=@im=fcitx
> IMSETTINGS_MODULE       DEFAULT=fcitx
> QT_IM_MODULE            DEFAULT=fcitx
> ```
> 
> It doesn't work in Chromium, but apps like Telegram can use the input.

https://bugs.chromium.org/p/chromium/issues/detail?id=1183262.
This bug has not been fixed.

**Comment by tinywrkb** [comment]
@darrist you should not use `.pam_environment` as by default it's not being read by PAM since v1.4.0, and most likely it will not be supported in the future.

> Do you have a solution for this?

Use the `Google Input Tools` extension instead of Fcitx or run Chromium as an X11/XWayland client.

**Comment by greenhat616** [comment]
@tinywrkb @thep0y As https://bugs.chromium.org/p/chromium/issues/detail?id=1183262&q=ime%20wayland&can=2 refered, fcitx can work now by adding flag: `--gtk-version=4`

**Comment by greenhat616** [comment]
![图片](https://user-images.githubusercontent.com/41122242/143155972-5fe519f1-36cc-4b77-8243-a659c18fa1a4.png)

**Comment by tinywrkb** [comment]
@greenhat616 that's with the kimpanel extension, so Gnome only. I'm not sure how is it with Plasma, but AFAIK, for anything wlroots based this isn't solved yet. See [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1265118).

**Comment by greenhat616** [comment]
@tinywrkb  You're right. While i disabled the kimpanel extension, fcitx was not work.

**Comment by wengxt** [comment]
It's not "not work", it's partially work (you can still type, but there will be no popup be shown.

**Comment by NgoHuy** [comment]
on Archlinux, gtk4 is required by chrome/chromium to make fcitx work.

**Comment by tinywrkb** [comment]
@NgoHuy last time I tried (I'm back to XWayland), I needed also the `--gtk-version=4` flag.

**Comment by NgoHuy** [comment]
> @NgoHuy last time I tried (I'm back to XWayland), I needed also the `--gtk-version=4` flag.

I meant this flag and gtk4 package.

**Comment by tinywrkb** [comment]
You might also want to use it with the IBus GTK4 IM module if you need the candidate box.

**Comment by ttys3** [comment]
> @tinywrkb @thep0y As [bugs.chromium.org/p/chromium/issues/detail?id=1183262&q=ime%20wayland&can=2](https://bugs.chromium.org/p/chromium/issues/detail?id=1183262&q=ime%20wayland&can=2) referred, fcitx can work now by adding flag: `--gtk-version=4`

just tested  `--gtk-version=4` with Chrome and Edge, both works like a charm

**Comment by tinywrkb** [comment]
> just tested `--gtk-version=4` with Chrome and Edge, both works like a charm

Right, there was a fix somewhere in Fcitx5 or Chromium that made the candidate box work recently.  
Like IBus, there's still the issue of candidate box positioning.  
And sometimes, though now pretty rarely, the key repetition issue shows up.

From a user perspective, there's the problem GTK4 is opt-in, and it's not even listed in `chrome://flags`, while for Ozone there's now even an auto platform mode for that prioritize Wayland (`ozone-platform-hint` or the `chrome://flags` entry).

Also, it doesn't seem to work with Electron. Vieb 7.2.0, with Electron 18 that finally has Wayland fixed, crashes when trying to use GTK4 and output the error.
```
GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported
```

Chrome devs need to implement the Wayland protocol extensions, instead of delivering bad experience to the user.

**Comment by Aleksanaa** [comment]
> > @tinywrkb @thep0y As [bugs.chromium.org/p/chromium/issues/detail?id=1183262&q=ime%20wayland&can=2](https://bugs.chromium.org/p/chromium/issues/detail?id=1183262&q=ime%20wayland&can=2) referred, fcitx can work now by adding flag: `--gtk-version=4`
> 
> just tested `--gtk-version=4` with Chrome and Edge, both works like a charm

This does not work for the flatpak version.

**Comment by tinywrkb** [comment]
> > > @tinywrkb @thep0y As [bugs.chromium.org/p/chromium/issues/detail?id=1183262&q=ime%20wayland&can=2](https://bugs.chromium.org/p/chromium/issues/detail?id=1183262&q=ime%20wayland&can=2) referred, fcitx can work now by adding flag: `--gtk-version=4`
> > 
> > 
> > just tested `--gtk-version=4` with Chrome and Edge, both works like a charm
> 
> This does not work with the flatpak version.

See https://github.com/flathub/org.chromium.Chromium.BaseApp/pull/2

**Comment by mnixry** [comment]
> Also, it doesn't seem to work with Electron. Vieb 7.2.0, with Electron 18 that finally has Wayland fixed, crashes when trying to use GTK4 and output the error.

It seems we must wait for https://github.com/electron/electron/issues/33690 to be solved :cry:

**Comment by ttys3** [comment]
wait https://bugs.chromium.org/p/chromium/issues/detail?id=1039161

**Comment by pedestrianlove** [comment]
## Not a workaround, but an alternative solution...
If you still want to use input method while waiting for the upstream to resolve the issue, you can try out this chrome extension:
- https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab

If you set the same shortcut inside the extension the same way as your system, you will have a nearly identical experience. Just that you can't use it in the address bar.

This setup is currently working on Brave 1.50.114 with Chromium on 112.0.5615.49.

**Comment by JuniorSuperTux** [comment]
Fcitx5 does work for me when adding additional ``--gtk-version=4`` flag to chromium for me, but the pop-up doesn't appear when attempting to select the correct character. How did you guys deal with this issue?

我在用 chromium 的時候如果加入``--gtk-version=4`` 的參數時 Fcitx5 能使用，但是它不會顯示選字的視窗。你們是怎麼解決這個問題的？

**Comment by wengxt** [comment]
https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron

**Comment by JuniorSuperTux** [comment]
> https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron

So if I understand correctly, candidate selection for Chromium would not work in Sway since text-input-v1 support isn't implemented?

**Comment by wengxt** [comment]
> > https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron
> 
> So if I understand correctly, candidate selection for Chromium would not work in Sway since text-input-v1 support isn't implemented?

you should use gtk 4 im module and enable xwayland. the ui for gtk im module will use X11.

**Comment by imethwang** [comment]
I add the flag --enable-wayland-ime to let the fcitx5 working in Chromium(Wayland):
https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron

**Comment by kohane27** [comment]
I can verify that adding the flag `--gtk-version=4` and my ime is working again:

```bash
# works
brave --gtk-version=4 --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer
# doesn't work
brave --enable-wayland-ime --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer
```

**Comment by FindHao** [comment]
> > Do you have a solution for this? I am currently using
> > .pam_environment
> > ```
> > # Wayland compatibility
> > QT_QPA_PLATFORM         DEFAULT=wayland
> > CLUTTER_BACKEND         DEFAULT=wayland
> > SDL_VIDEODRIVER         DEFAULT=wayland
> > MOZ_ENABLE_WAYLAND      DEFAULT=1
> > MOZ_WEBRENDER           DEFAULT=1
> > XDG_SESSION_TYPE        DEFAULT=wayland
> > XDG_CURRENT_DESKTOP     DEFAULT=sway
> > 
> > # QT-related theming
> > QT_QPA_PLATFORMTHEME    DEFAULT=qt5ct
> > 
> > # FCITX input-related
> > #GLFW_IM_MODULE         DEFAULT=ibus
> > GLFW_IM_MODULE          DEFAULT=fcitx
> > GTK_IM_MODULE           DEFAULT=fcitx
> > INPUT_METHOD            DEFAULT=fcitx
> > XMODIFIERS              DEFAULT=@im=fcitx
> > IMSETTINGS_MODULE       DEFAULT=fcitx
> > QT_IM_MODULE            DEFAULT=fcitx
> > ```
> > 
> > 
> > It doesn't work in Chromium, but apps like Telegram can use the input.
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=1183262. This bug has not been fixed.

ubuntu 22.04下` CLUTTER_BACKEND         DEFAULT=wayland`的选项导致无法打开系统设置中心。

**Comment by fecet** [comment]
> I add the flag --enable-wayland-ime to let the fcitx5 working in Chromium(Wayland):我添加了 --enable-wayland-ime 标记，以便让 fcitx5 在 Chromium（Wayland）中运行： https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron

使用这种方法启动的fcitx5只能在第一个chrome窗口使用，其他窗口无法输入

**Comment by milkpuff** [comment]
> > I add the flag --enable-wayland-ime to let the fcitx5 working in Chromium(Wayland):
> > https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron
> 
> 使用这种方法启动的fcitx5只能在第一个chrome窗口使用，其他窗口无法输入

我也遇到同样的问题。

**Comment by simline** [comment]
Linux fedora 6.9.7-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 27 18:11:45 UTC 2024 x86_64 GNU/Linux

Operating System: Fedora Linux
KDE Plasma Version: 6.1.1
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.1
Kernel Version: 6.9.7-200.fc40.x86_64
OS-Type: 64
Processor: 8 × Intel® Core™ i7 CPU

**Comment by teohhanhui** [comment]
@Biaogo https://issues.chromium.org/issues/345261080

You need to wait for the latest Google Chrome release. It's already fixed.

**Comment by bigzhu** [comment]
```bash
sudo nvim /usr/share/applications/google-chrome.desktop
```
Add tag  `--enable-wayland-ime`  like this:

```
...
Exec=/usr/bin/google-chrome-stable --enable-wayland-ime %U
...
```

**Comment by thyeun** [comment]
Pls create a brave-flags.conf at ~/ and put in like below, instead that put it in *.desktop file.
```
--enable-wayland-ime
```

**Comment by liinyun** [comment]
> Pls create a `brave-flags.conf` at `~/` and put in like below, instead that put it in *.desktop file.
> 
> ```
> --enable-wayland-ime
> ```

老哥，如果使用的是chrome-stable 是不是现在还是没办法在sway中显示候选框
Is it still unable to show candidate box in google-chrome-stable in swaywm

**Comment by thyeun** [comment]
@liinyun 怎麼說選框？用鼠鍵選框嗎？

**Comment by teohhanhui** [comment]
@liinyun You can try with these flags:

```
--enable-features=TouchpadOverscrollHistoryNavigation,WaylandWindowDecorations
--enable-wayland-ime
--ozone-platform=wayland
--wayland-per-window-scaling
--wayland-text-input-version=3
```

**Comment by stkevintan** [comment]
> @liinyun You can try with these flags:
> 
> ```
> --enable-features=TouchpadOverscrollHistoryNavigation,WaylandWindowDecorations
> --enable-wayland-ime
> --ozone-platform=wayland
> --wayland-per-window-scaling
> --wayland-text-input-version=3
> ```
Thanks worked!

**Comment by yuzujr** [comment]
对我来说，在hyprland上使fcitx5可用的最小命令是：`google-chrome --ozone-platform=wayland`
