### ISSUE TITLE
fcitx5在microsoft edge中显示异常

### ISSUE THREAD

**Issue by YaoLaiGang** [fcitx/fcitx5#264]
在edge for Linux 中，fcitx5的输入框会遮挡输入文字的位置
![image](https://user-images.githubusercontent.com/15951265/114804711-533bfd00-9dd4-11eb-89ea-de8153a5a814.png)
![image](https://user-images.githubusercontent.com/15951265/114804769-6e0e7180-9dd4-11eb-923c-99008d03eeb1.png)

**To Reproduce**
1. 打开edge for Linux
2. 输入文字

**Desktop (please complete the following information):**
 - Desktop: Ubuntu20.04 Gnome 3.36.8
 - Edge Browser: 版本 91.0.852.0 (官方内部版本) dev (64 位)
 - Fcitx5: flatpak.fcitx-im.org 5.0.7

**Comment by wengxt** [comment]
是 wayland 还是 X11？

**Comment by YaoLaiGang** [comment]
> 是 wayland 还是 X11？

X11

**Comment by wengxt** [comment]
贴一下
```
dbus-send --session --type=method_call --print-reply --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo 
```
的输出

**Comment by YaoLaiGang** [comment]
> 贴一下
> 
> ```
> dbus-send --session --type=method_call --print-reply --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo 
> ```
> 
> 的输出

`method return time=1618455203.086808 sender=:1.12 -> destination=:1.195 serial=7964 reply_serial=2
   string "Group [x11::99.0] has 27 InputContext(s)
  IC [7b0b93aa046c495aa407138c54833e1e] program: frontend:dbus cap:12 focus:0
  IC [3c3ec145d0c0408799df6f7a4640a94e] program: frontend:dbus cap:12 focus:0
  IC [788bacd3bebc48f19d1376d2e14ae6e5] program: frontend:dbus cap:12 focus:0
  IC [63d801cdb4af455f9b52aea9b431280d] program: frontend:dbus cap:12 focus:0
  IC [1cb5c6c6ca7e4d34b4ca7dc76536a340] program: frontend:xim cap:4000000000 focus:0
  IC [466f4fc5700c4231ad742db19a9eee52] program: frontend:dbus cap:12 focus:0
  IC [9f631178eb0b4c75882c7b861a23769e] program: frontend:dbus cap:12 focus:0
  IC [9b2fa37fd5f04fd58c1b3cd1da3b0317] program: frontend:dbus cap:12 focus:0
  IC [f33a27f5d90b4e378ce2370a3fbc8ab3] program: frontend:dbus cap:12 focus:0
  IC [f9008d0198c8452abd55de310e3e3d18] program:qv2ray frontend:dbus cap:800072 focus:0
  IC [64f21221eda84530bca1f7e076189ba1] program: frontend:dbus cap:12 focus:0
  IC [f50df6614563455a8b52165eb1095283] program: frontend:dbus cap:0 focus:0
  IC [c934a96fc40c4b9f86eb09eff2164891] program: frontend:dbus cap:12 focus:0
  IC [be6c121e9db042a593b9b1c4b709e83e] program: frontend:dbus cap:12 focus:0
  IC [c414bba9947d4c80abf319ab288abeaf] program:qv2ray frontend:dbus cap:800072 focus:0
  IC [4b1d683ae81546e984141a1b88912f57] program: frontend:dbus cap:12 focus:0
  IC [b2dae2d00cd34e2d9852746d134f01a8] program: frontend:dbus cap:12 focus:0
  IC [a85576e46e424d5ba3e5e2410cd54272] program: frontend:dbus cap:12 focus:0
  IC [7ed2ac4d87d34d78bb6f61ecd4e87a8d] program: frontend:dbus cap:12 focus:0
  IC [0065381184034444bbc6607c80d94334] program: frontend:dbus cap:12 focus:0
  IC [e99c8bb46c684a6db186a7a10afac126] program: frontend:dbus cap:12 focus:0
  IC [2efc488a59644a4a846b91a65b5af395] program: frontend:dbus cap:12 focus:0
  IC [7642d7eafad74e4382632aec8685913c] program: frontend:dbus cap:12 focus:0
  IC [16013e0699e0469b97d80cde3fb071d6] program: frontend:dbus cap:12 focus:1
  IC [975ada3b29ef4c6eb6c624a1ebc069e9] program: frontend:xim cap:4000000000 focus:0
  IC [a50f3ee6ef3a48209d1a9bddfa5e3dde] program: frontend:dbus cap:12 focus:0
  IC [1aa6df838ea94aeea2e8550e57644979] program: frontend:dbus cap:12 focus:0
Input Context without group
"`

**Comment by wengxt** [comment]
不是特别明白，我这里并不能重现这个问题，你试过别的浏览器例如 chrome 吗？
edge 是怎么安装的？系统是否有启用什么缩放之类的机制？

**Comment by YaoLaiGang** [comment]
> 不是特别明白，我这里并不能重现这个问题，你试过别的浏览器例如 chrome 吗？
> edge 是怎么安装的？系统是否有启用什么缩放之类的机制？

edge是直接通过apt升级的，实际上我使用chrome（beta stable）和firefox以及其他的程序都是正常的。由于我昨天**刚好更新edge**，有可能是edge dev版本（目前Linux只有dev版本）升级了最新的浏览器内核后造成的问题，我现在正在准备回退上一个edge版本来观察是否能结解决该问题。

**Comment by YaoLaiGang** [comment]
> 不是特别明白，我这里并不能重现这个问题，你试过别的浏览器例如 chrome 吗？
> edge 是怎么安装的？系统是否有启用什么缩放之类的机制？
降低版本后显示正常，我会将该问题反馈给edge
![image](https://user-images.githubusercontent.com/15951265/114813293-635bd880-9de4-11eb-8d4d-06e8f476884a.png)

**Comment by YaoLaiGang** [comment]
现在最新版的**edge和chrome beta都出现了该位置显示异常**，另外我已经测试过了缩放问题，和缩放没有关系。
![image](https://user-images.githubusercontent.com/15951265/115944684-be2eb780-a4e9-11eb-8df5-ee01c43ed038.png)
![image](https://user-images.githubusercontent.com/15951265/115944707-dbfc1c80-a4e9-11eb-9353-bba4f6af6c9d.png)
chrome版本：_91.0.4472.19（正式版本）beta （64 位）_
edge版本：_91.0.852.0-1 500_

**Comment by wengxt** [comment]
无法在我的 chrome 里重现，你是什么桌面环境？
chrome 运行时贴一下

dbus-send --session --type=method_call --print-reply --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo

的输出

**Comment by YaoLaiGang** [comment]
输入为：
```
method return time=1619237759.401724 sender=:1.160 -> destination=:1.280 serial=64 reply_serial=2
   string "Group [x11::99.0] has 26 InputContext(s)
  IC [c5dfcd6e7646411ab265cf51b72a6577] program: frontend:dbus cap:12 focus:0
  IC [c696a9bc8096445aaeeee9ce42810e94] program: frontend:dbus cap:12 focus:0
  IC [e5a6a6c9051548728d16a5587dd3107f] program: frontend:dbus cap:12 focus:0
  IC [8a6941d223b64a859072a8cffb6b2479] program: frontend:dbus cap:12 focus:0
  IC [c95d98cb3ebb499fa80a50053271c999] program:qv2ray frontend:dbus cap:800072 focus:0
  IC [dae9bef501ab438798124386aca6e459] program: frontend:dbus cap:12 focus:0
  IC [cc788bc6539e4e249ac4ac115f16c0b2] program:qv2ray frontend:dbus cap:800072 focus:0
  IC [ad40f2c0b3514646b83474e1a7af85e1] program: frontend:dbus cap:12 focus:0
  IC [80eb4d8dd89944c488cf442e067fa7df] program: frontend:dbus cap:12 focus:0
  IC [25731162cc45463b92d67aa4273a599e] program: frontend:dbus cap:12 focus:0
  IC [6fe7e192143b4b97ba78bc33bffad6fb] program: frontend:dbus cap:12 focus:0
  IC [49b3f34feb3d4bccbb7e6e22b747e358] program: frontend:dbus cap:12 focus:0
  IC [158df14963034baa964e3fdab53a289a] program: frontend:dbus cap:12 focus:0
  IC [6b62ab829e0d4be3b9d2cdb38a3f66ee] program:qv2ray frontend:dbus cap:0 focus:0
  IC [1228cb5847f84befa4575c4e78dc5753] program: frontend:dbus cap:12 focus:0
  IC [afd28226d0344242927251cd42cffc85] program: frontend:dbus cap:12 focus:0
  IC [50f111a744b64f76a35f90c3f67db362] program: frontend:dbus cap:12 focus:0
  IC [395f4de396604c86a7878e923201b61a] program:qv2ray frontend:dbus cap:0 focus:0
  IC [fdfb8053cedf490d92459e8a412da0ee] program: frontend:dbus cap:12 focus:0
  IC [babd5ce23eec4fafbef3f3958c5cd239] program: frontend:dbus cap:12 focus:0
  IC [90c0fd8f9c8345eb8bc8d9bfe841374d] program:qv2ray frontend:dbus cap:0 focus:0
  IC [ee7cb1bde1a749fa804a1f2f41da8668] program: frontend:dbus cap:12 focus:0
  IC [0a76de194429479d88c01ecee028dbe7] program: frontend:dbus cap:12 focus:1
  IC [fcaa1be7049c48e3805de07aa12791c3] program:qv2ray frontend:dbus cap:0 focus:0
  IC [5a822803efaa442b83b4d21b0c4c65dc] program: frontend:dbus cap:12 focus:0
  IC [4046779498884c76a0daffbf2a395b75] program: frontend:dbus cap:12 focus:0
Input Context without group
```
桌面环境为: **GNOME 3.36.5**

**Comment by YaoLaiGang** [comment]
> 无法在我的 chrome 里重现，你是什么桌面环境？
> chrome 运行时贴一下
> 
> dbus-send --session --type=method_call --print-reply --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
> 
> 的输出

输入为：
```
method return time=1619237759.401724 sender=:1.160 -> destination=:1.280 serial=64 reply_serial=2
   string "Group [x11::99.0] has 26 InputContext(s)
  IC [c5dfcd6e7646411ab265cf51b72a6577] program: frontend:dbus cap:12 focus:0
  IC [c696a9bc8096445aaeeee9ce42810e94] program: frontend:dbus cap:12 focus:0
  IC [e5a6a6c9051548728d16a5587dd3107f] program: frontend:dbus cap:12 focus:0
  IC [8a6941d223b64a859072a8cffb6b2479] program: frontend:dbus cap:12 focus:0
  IC [c95d98cb3ebb499fa80a50053271c999] program:qv2ray frontend:dbus cap:800072 focus:0
  IC [dae9bef501ab438798124386aca6e459] program: frontend:dbus cap:12 focus:0
  IC [cc788bc6539e4e249ac4ac115f16c0b2] program:qv2ray frontend:dbus cap:800072 focus:0
  IC [ad40f2c0b3514646b83474e1a7af85e1] program: frontend:dbus cap:12 focus:0
  IC [80eb4d8dd89944c488cf442e067fa7df] program: frontend:dbus cap:12 focus:0
  IC [25731162cc45463b92d67aa4273a599e] program: frontend:dbus cap:12 focus:0
  IC [6fe7e192143b4b97ba78bc33bffad6fb] program: frontend:dbus cap:12 focus:0
  IC [49b3f34feb3d4bccbb7e6e22b747e358] program: frontend:dbus cap:12 focus:0
  IC [158df14963034baa964e3fdab53a289a] program: frontend:dbus cap:12 focus:0
  IC [6b62ab829e0d4be3b9d2cdb38a3f66ee] program:qv2ray frontend:dbus cap:0 focus:0
  IC [1228cb5847f84befa4575c4e78dc5753] program: frontend:dbus cap:12 focus:0
  IC [afd28226d0344242927251cd42cffc85] program: frontend:dbus cap:12 focus:0
  IC [50f111a744b64f76a35f90c3f67db362] program: frontend:dbus cap:12 focus:0
  IC [395f4de396604c86a7878e923201b61a] program:qv2ray frontend:dbus cap:0 focus:0
  IC [fdfb8053cedf490d92459e8a412da0ee] program: frontend:dbus cap:12 focus:0
  IC [babd5ce23eec4fafbef3f3958c5cd239] program: frontend:dbus cap:12 focus:0
  IC [90c0fd8f9c8345eb8bc8d9bfe841374d] program:qv2ray frontend:dbus cap:0 focus:0
  IC [ee7cb1bde1a749fa804a1f2f41da8668] program: frontend:dbus cap:12 focus:0
  IC [0a76de194429479d88c01ecee028dbe7] program: frontend:dbus cap:12 focus:1
  IC [fcaa1be7049c48e3805de07aa12791c3] program:qv2ray frontend:dbus cap:0 focus:0
  IC [5a822803efaa442b83b4d21b0c4c65dc] program: frontend:dbus cap:12 focus:0
  IC [4046779498884c76a0daffbf2a395b75] program: frontend:dbus cap:12 focus:0
Input Context without group
```
桌面环境为: **GNOME 3.36.5**

**Comment by YaoLaiGang** [comment]
> 无法在我的 chrome 里重现，你是什么桌面环境？
> chrome 运行时贴一下
> 
> dbus-send --session --type=method_call --print-reply --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
> 
> 的输出

chrome和edge都只有最近更新的版本有问题，退回到旧版没有该问题，使用基于fcitx4的的输入法没有该问题，我这里是Ubuntu20.04，使用的为**flatpak**版的fcitx5，版本号为5.0.7

**Comment by YaoLaiGang** [comment]
> 无法在我的 chrome 里重现，你是什么桌面环境？
> chrome 运行时贴一下
> 
> dbus-send --session --type=method_call --print-reply --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
> 
> 的输出

我在查阅Arch Linux的帖子的时候发现，[类似的问题似乎在fcitx中出现过](https://bbs.archlinuxcn.org/viewtopic.php?id=3383)，我的DPI是96，在启动chrome时通过添加--force-device-scale-factor=1 **关闭HiDPI** 支持后，输入显示正常，然而浏览器就看起来怪怪的。

**Comment by wengxt** [comment]
你这个描述还是感觉不太对劲啊？一般来说 dpi 96 就是  scale 1 …

anyway 如果设置 --force-device-scale-factor=2 的话确实能重现你说的问题，但是我并没有任何办法。测试了 ibus fcitx fcitx5 都有一样的问题 你还是得去给 chromium 汇报。

我三年前汇报的bug，鬼知道他们怎么又改坏了，建议 reopen。
https://bugs.chromium.org/p/chromium/issues/detail?id=475718

另外，目前来说建议用 GDK_SCALE 来设置缩放。这样应该可以让 fcitx 获得一致的缩放信息。还是可以显示正确的位置的。

**Comment by wengxt** [comment]
I opened a new bug for chromium, FYI: https://bugs.chromium.org/p/chromium/issues/detail?id=1202531

**Comment by YaoLaiGang** [comment]
> 你这个描述还是感觉不太对劲啊？一般来说 dpi 96 就是 scale 1 …
> 
> anyway 如果设置 --force-device-scale-factor=2 的话确实能重现你说的问题，但是我并没有任何办法。测试了 ibus fcitx fcitx5 都有一样的问题 你还是得去给 chromium 汇报。
> 
> 我三年前汇报的bug，鬼知道他们怎么又改坏了，建议 reopen。
> https://bugs.chromium.org/p/chromium/issues/detail?id=475718
> 
> 另外，目前来说建议用 GDK_SCALE 来设置缩放。这样应该可以让 fcitx 获得一致的缩放信息。还是可以显示正确的位置的。

我找到问题的根本原因了！我一度怀疑是自己开了屏幕缩放功能，但是我寻找了任何设置都没有发现开启屏幕缩放问题。直到今天我闲逛设置时发现了通用辅助里打开了个**大号文本**。
所以问题的根源应该是**新版浏览器和大号字体一起使用**，**如果使用就会输入法定位偏差**，而旧版浏览器不会出现该问题！

**Comment by wengxt** [comment]
可能它的大号文本本质也是改变缩放律，而缩放确实出了问题。可能是同一个问题

残桥断雪 ***@***.***>于2021年4月25日 周日19:30写道：
