### ISSUE TITLE
How to switch input methods in terminal?

### ISSUE THREAD

**Issue by quantum-booty** [fcitx/fcitx5#269]
**Describe the bug**
Hi, I'm trying to use pinyin inside a Kitty terminal, however ctrl + space do not work.

**Desktop (please complete the following information):**
 - Desktop: i3
 - Display server type: X11
 - The output of fcitx5-diagnose if possible.
https://dropb.in/dius.sql

**Additional context**

**Comment by wengxt** [comment]
kitty has its own env var to make it work.

try set `GLFW_IM_MODULE=ibus`
