### ISSUE TITLE
是否可以提供一个固定词库功能？

### ISSUE THREAD

**Issue by yaocccc** [fcitx/fcitx5#270]
例如我需要写一个词库
qq = 123123123
dianhua = 15151515151

类似于这样的词库，并且该词库在候选项中 优先级最高。
请问fcitx5中是否可以实现该功能 fcitx4中是可以通过符号码表实现的

**Comment by yaocccc** [comment]
是的，不过快速输入必须指定一个 引导键进入呢，是否有办法在正常输入中也可以定义固定的词库，优先级最高 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月30日(星期五) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fcitx/fcitx5] 是否可以提供一个固定词库功能？ (#270)

**Comment by yaocccc** [comment]
![2021-04-30_18-11](https://user-images.githubusercontent.com/53512609/116681712-e766b080-a9df-11eb-9de7-aa3afc35bb15.png)
![2021-04-30_18-12](https://user-images.githubusercontent.com/53512609/116681718-ea61a100-a9df-11eb-8d40-42a55c0df246.png)

而在fcitx4, 我是用的拼音增强中的 符号 功能实现的   固定词库的功能，而在5中我尝试了很多方法，没有理想的解决方案

**Comment by wengxt** [comment]
说明一下，如果是合法拼音的话，是可以的，词库格式
https://github.com/fcitx/fcitx5-chinese-addons/blob/master/im/pinyin/emoji.txt
其他方法的话，如果要用汉字来对应的话就是这样（最后两个）
https://github.com/fcitx/fcitx5-chinese-addons/blob/master/im/pinyin/pinyin.lua

任意字符串的话，目前不行

**Comment by sanheiZY** [comment]
这个是不是容易泄露隐私呀

**Comment by yaocccc** [comment]
> 这个是不是容易泄露隐私呀

自己用的话，没什么泄漏隐私之说吧

**Comment by yaocccc** [comment]
已通过rime实现需求
