### ISSUE TITLE
每次重启fcitx5后，使用ibus的程序就无法再正常输入中文

### ISSUE THREAD

**Issue by unisgn** [fcitx/fcitx5#272]
目前使用的 kitty，在 /etc/environment 中设置了 GLFW_IM_MODULE=ibus，可以使用 fcitx5 正常输入中文，但是每次在 kitty 运行过程中重启了 fcitx5 后，kitty 就没法正常输入中文，每次按键出发报错：

[glfw error 65544]: IBUS: Failed to process key with error: [org.freedesktop.DBus.Error.UnknownObject] Unknown object '/org/freedesktop/IBus/InputContext_1'.

此时需要重启 kitty 才能正常在 kitty 里输入中文。

环境：
fcitx5
version=5.0.7-1

**Comment by wengxt** [comment]
kitty 的实现不是用 ibus 的库，检测 ibus 重启的方式不一样导致的，目前没有办法。

**Comment by unisgn** [comment]
我注意到了这个东西，
fcitx5 在 .config/ibus/bus 下写的地址信息类似:
IBUS_ADDRESS=unix:path=/run/user/1000/bus,fcitx_random_string=612701f1ab15459b835dbcfd87da1e4f
IBUS_DAEMON_PID=105354

而 ibus-daemon 写的地址信息类似:
IBUS_ADDRESS=unix:abstract=/home/xxxxxx/.cache/ibus/dbus-vo5dvgE6,guid=6836bd082d14d88caa645b176092e8c3
IBUS_DAEMON_PID=106924

fcitx5 把服务挂在了系统总线上，而 ibus-daemon 使用了独立总线。既然 fcitx5 实现了 ibus 前端或者说兼容 ibus 前端，是不是也可以建立一条独立总线呢？

**Comment by wengxt** [comment]
你说的是对的，只是浪费内存以及需要写更多代码。

**Comment by unisgn** [comment]
确实，实现的目标很小，代价却可能很大。我好像在 kitty 项目里看到你了，haha。kitty 里把远程对象缓存起来了，导致重启 fcitx5 这些缓存的远程对象就失效了，也就出现了最上面的报错。如果没有缓存远程对象，或者在出现 UnknownObject 错误后尝试重新获取远程对象，可能就解开了默认 ibus 是挂在独立总线的假设。
