### ISSUE TITLE
fcitx5 在flatpak环境中的Chrome无法输入中文，包括edge和Electron应用。

### ISSUE THREAD

**Issue by lhjok** [fcitx/fcitx5#273]
fcitx5 在wayland桌面下的flatpak环境中的Chrome无法输入中文，包括edge和Electron应用。

**Comment by tinywrkb** [comment]
I don't believe it's a Flatpak or Fcitx5 bug.

Google or Igalia needs to fix this.

* [Issue 1022724: [ozone/wayland] Keyboard and IME issues](https://bugs.chromium.org/p/chromium/issues/detail?id=1022724)
* [Issue 1183262: Add support for gtk im module on ozone wayland platform](https://bugs.chromium.org/p/chromium/issues/detail?id=1183262)
* [Issue 1039161: Ozone-wayland: support text_input_v3 protocol](https://bugs.chromium.org/p/chromium/issues/detail?id=1039161)

**Comment by wengxt** [comment]
You can run chrome with xwayland, otherwise there's nothing I can do.

**Comment by lhjok** [comment]
非flatpak环境中的Chrome是可以输入中文的，即使在wayland环境下，也是可以的。
