### ISSUE TITLE
fcitx5的皮肤设置无效

### ISSUE THREAD

**Issue by SimpleButNotNaive** [fcitx/fcitx5#275]
- fcitx5设置了皮肤之后没有效果，如图

![Screenshot_20210507_190601](https://user-images.githubusercontent.com/42604435/117463689-88c2a900-af82-11eb-8516-0f96843a75fb.png)

- 经典界面设置如图
![Screenshot_20210507_190713](https://user-images.githubusercontent.com/42604435/117464282-12727680-af83-11eb-8702-fed1d9464c93.png)

- classicui文件没问题

桌面环境为KDE
fcitx版本5.0.8

**Comment by wengxt** [comment]
因为你在用kimpanel…
