### ISSUE TITLE
Fcitx在Flatpak环境下的Chrome以及edge和Electron应用

### ISSUE THREAD

**Issue by lhjok** [fcitx/fcitx5#277]
我的环境是Gnome 3.38 Wayland 使用的是Fedora Silverblue 操作系统。在本机安装（非Flatpak）环境下Chrome是可以正常输入中文的，在Flatpak环境下，Chrome以及edge和Electron应用都无法输入中文。

**Comment by karuboniru** [comment]
别骂了别骂了，马上修

**Comment by karuboniru** [comment]
FYI:
[Fedora 33](https://bodhi.fedoraproject.org/updates/FEDORA-2021-a07ff439aa)
[Fedora 34](https://bodhi.fedoraproject.org/updates/FEDORA-2021-7798845ee1)

Those updates may need at most 1 week to hit stable repository

**Comment by lhjok** [comment]
非常感谢！已经可以了，今天起来收到一个系统更新，然后就可以了。
