### ISSUE TITLE
I want the activation key to always be IME ON

### ISSUE THREAD

**Issue by shelaf** [fcitx/fcitx5#279]
I want to stop inputting directly when I press the activate key twice.
What should I do?

fcitx5 version: 5.0.8
Linux distribution: Arch Linux

my config:
```
[Hotkey/ActivateKeys]
0=Henkan

[Hotkey/DeactivateKeys]
0=Muhenkan
```

Press Henkan key->
Current behavior:
first time: IME ON
2nd time: IME ON (direct input)
3rd time: IME ON (not direct input)
...

Expected behavior:
first time: IME ON
2nd time: IME ON (not direct input)
3rd time: IME ON (not direct input)
...

**Comment by wengxt** [comment]
emm, this sounds like the key is also handled by your input method? maybe you can also try to remove that key from the input method option?

**Comment by shelaf** [comment]
I'm using mozc for the input method. The imported mozc v4 settings didn't work as I expected, but when I changed the settings it worked as expected. Thank you!
