### ISSUE TITLE
对这个新版本，我有一个新建议--状态跟随光标

### ISSUE THREAD

**Issue by yueduz** [fcitx/fcitx5#28]
只要输入法激活就让状态栏跟随在光标上，当有候选时，隐藏状态栏，显示候选栏。一点也不冲突。

因为在开始输入法时我真的不知道我当前是中文状态还是英文状态啊。每次都输了四五个键又回头改。

**Comment by wengxt** [comment]
不会像你想象的工作的那么好，因为有些光标跟随问题是没法解决的，在一些情况下可能在奇怪的位置弹出窗口。
