### ISSUE TITLE
Active layout is no longer shown in KDE/GNOME layout indicator

### ISSUE THREAD

**Issue by Ai-rin** [fcitx/fcitx5#280]
**Describe the bug**
I have 4 layouts configured via "keyboard" entries and one via "input method" in fcitx. Previously (with fcitx v4) active layout was shown in DE's layout indicator in system tray. With fcitx5 however, this indicator always remains in its default state. Is there a way to make it work again?

**Expected behavior**
Working integration with DE's layout indicator, like in fcitx v4

**Desktop:**
 - Desktop: KDE, GNOME
 - Display server type: X11, Wayland
 
[fcitx5-diagnose.txt](https://github.com/fcitx/fcitx5/files/6489027/fcitx5-diagnose.txt)

**Comment by wengxt** [comment]
em, fcitx will manage your layout anyway.

but there’s something different in fcitx5, the system layout is bonded with the “group” in fcitx 5, the layout based in added in individual group will not affect system layout.

**Comment by wengxt** [comment]
so you may want to add 4 group, and set the system layout for every individual groups. That way, switch group will switch your system layout.

**Comment by Ai-rin** [comment]
This way it kinda works, but shares input state among all windows, even if configured not to do so.
An option to show current layout in system tray or kimpanel would eliminate this problem entirely.
