### ISSUE TITLE
Can't disable C-x bindings

### ISSUE THREAD

**Issue by spwhitton** [fcitx/fcitx5#282]
Hello,

C-x C-; is a standard Emacs binding but fcitx5 has taken it over.  I can't find any way to disable fcitx from binding this, and other things under C-x, in the fcitx5 configuration dialogue.  Am I missing something, or is this a missing feature?

Debian bullseye, using fcitx5 under sway 1.5.

Thanks for fcitx5!

**Comment by wengxt** [comment]
I think your problem is not about C-x but C-; ,which is binding to the clipboard addon in fcitx. You can go to clipboard addon config to disable it.

**Comment by spwhitton** [comment]
That works, thank you.

**Comment by dcunited001** [comment]
get rid of that clipboard nonsense
