### ISSUE TITLE
[Wayland] Repeated key rate is not respected

### ISSUE THREAD

**Issue by SuperBo** [fcitx/fcitx5#289]
**Describe the bug**
I am using sway and set repeated key option in config file. (repeat_rate 30, repeat_delay 300)
However, when I use fcitx5, the repeated key rate is quite slow compare to without fcitx5.

**To Reproduce**
1. Set repeat_rate to 30, repeat_delay to 300
2. Try to move cursor by pressing movement key (j,k) in vim in a terminal with and without fcitx5.

**Expected behavior**
Repeat_rate ,and repeat_delay should be kept the same in xkb.

**Desktop (please complete the following information):**
 - Desktop: Sway
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

**Additional context**
I use alacritty and neovim for my testing.

**Comment by SuperBo** [comment]
This is log of output info. Sway correctly put repeat rate (30, 300).

> [1897004.426] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897006.102]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 11, 64354)
> [1897006.120] zwp_input_method_keyboard_grab_v2@19.repeat_info(30, 300)
> [1897006.130] zwp_input_method_keyboard_grab_v2@19.modifiers(60717, 0, 0, 0, 0)
> [1897006.150]  -> zwp_virtual_keyboard_v1@15.modifiers(0, 0, 0, 0)
> [1897006.164] zwp_input_method_keyboard_grab_v2@19.modifiers(60718, 0, 0, 0, 0)
> [1897006.186]  -> zwp_virtual_keyboard_v1@15.modifiers(0, 0, 0, 0)
> [1897006.200] wl_callback@17.done(60718)
> [1897017.341] wl_buffer@6.release()
> [1897017.368] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897020.328]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897026.215] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897029.255]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897038.461] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897041.688]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897073.905] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897075.549]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897083.778] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897086.870]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897094.014] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897097.304]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897124.851] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897126.563]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897134.438] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897137.903]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897148.474] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897151.999]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897162.456] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897165.912]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897188.372] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897190.018]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897197.866] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897201.069]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897211.348] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897214.993]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897237.845] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897239.497]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897243.807] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897247.122]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897254.339] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897257.575]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897287.961] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64354)
> [1897289.688]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64354)
> [1897289.734] zwp_input_method_keyboard_grab_v2@19.keymap(1, fd 9, 64389)
> [1897292.698]  -> zwp_virtual_keyboard_v1@15.keymap(1, fd 10, 64389)
> [1897292.725] zwp_input_method_keyboard_grab_v2@19.repeat_info(30, 300)
> [1897292.741] zwp_input_method_keyboard_grab_v2@19.modifiers(60719, 0, 0, 0, 0)
> [1897292.769]  -> zwp_virtual_keyboard_v1@15.modifiers(0, 0, 0, 0)

I don't know what the prefix ([1897292.769] ) means. It's not unix timestamp but I think it maybe relevant to some time point. Based on that and number of keymap events, you can calculate the real repeated rate.

I also attached my full log here.

[logs.txt](https://github.com/fcitx/fcitx5/files/6690299/logs.txt)

**Comment by wengxt** [comment]
the problem seem to be the repetition time is not strictly followed. Instead of info not received.

Right now it always put an interval after the key repetition, instead of consider the time during the handling.

**Comment by ruby-R53** [comment]
i'm having the same issue under X.org as well, i'm using dwm and i set my keyboard repeat rate to 250 ms / 60 chars, but now that i set fcitx as the input method on my environment it seems to have fallen back to some default··· there's not even an option on `fcitx5-config-qt` related to this

**Comment by wengxt** [comment]
@ruby-R53 it's irrelevant.
