### ISSUE TITLE
Environment variable is "fcitx5" instead of "fcitx"

### ISSUE THREAD

**Issue by luni3359** [fcitx/fcitx5#295]
**Describe the bug**
I'm not sure if this intended but the environmental variables are being defined as `fcitx5` instead of `fcitx`. I followed the steps in [this page](https://zenn.dev/ikuya/articles/f42da50d670a8562a12e#インストール方法) to set it up. I wanted to edit the already defined variables but I can't find them anywhere in my home directory, I think they're being set somewhere else by `im-config`.

`XMODIFIERS` shows up correctly as `@im=fcitx`, but `GTK_IM_MODULE` and `QT_IM_MODULE` are `fcitx5`.

In this way, Fcitx5 starts up automatically and it works, but not in all programs. After adding `export GTK_IM_MODULE=fcitx`, `export QT_IM_MODULE=fcitx`, and `export XMODIFIERS=@im=fcitx` to my `.profile` Fcitx5 no longer starts automatically, but if I run it afterwards it works in the same way as the first (still doesn't work in some programs).

**To Reproduce**
1. `$ im-config -n fcitx5`

**Expected behavior**
All environmental variables are defined, but instead of `fcitx` they're `fcitx5`.

**Desktop:**
 - Desktop: KDE
 - Display server type: X11
 - [fcitx5-diagnose file without adding variables to .profile](https://gist.github.com/luni3359/d0d55435d6a56c4ebeaf9b6f53aab87d)
 - [fcitx5-diagnose file with variables added to .profile](https://gist.github.com/luni3359/3dff83d84d45d95c0a9077bb2cd0cb30)

**Additional context**
I'm not sure if this the intended but it was the default behavior. Maybe it should be able to understand it's still fcitx. Fcitx used to work correctly on fcitx4.

**Comment by zhsj** [comment]
This is a known issue which origins from Debian, https://wiki.debian.org/I18n/Fcitx5#Known_Issues https://bugs.debian.org/977203

It will be resolved in Debian 12, and has been fixed in Ubuntu 21.10.

**Comment by luni3359** [comment]
Thank you, I wasn't aware of it. I still had to revert to fcitx4 because even after setting the variables to `fcitx` programs like KWrite and the start menu on Plasma weren't switching to other languages.

**Comment by zhsj** [comment]
Basically fcitx5 in Ubuntu 20.04 is too old to use, you can try the backports like https://launchpad.net/~zhsj/+archive/ubuntu/fcitx5

**Comment by xingwozhonghua** [comment]
use Flatpak will be better.
You can get the latest version.

https://fcitx-im.org/wiki/Install_Fcitx_5

**Comment by wengxt** [comment]
set it as fcitx would have more compatibility, because some old application may only support fcitx4 im module.
