### ISSUE TITLE
fcitx-rime与libre office不兼容问题

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [fcitx/fcitx5#30]
使用的fcitx-rime输入法

fcitx-rime开启时，在libreoffice-writer里，
1. 鼠标点击无法移动光标位置
2. 打字第一次无法输入到文本，第二次才可以。每移动一次输入位置，都要输入两遍。
3. 打字出现在非光标位置，看不懂出现字位置的逻辑。

切换到其他中文输入法比如fcitx-google-pinyin就没这些问题。
发issue到librime他们说是fcitx-rime的问题，fcitx-rime那边是机器人自动打包的吗？没办法提交issue

**Comment by wengxt** [comment]
装一下 fcitx5-gtk

**Comment by GreatBigWhiteWorld** [comment]
看了下fcitx-gtk2和fcitx-gtk3都已经安装，没有fcitx5开头的包

**Comment by wengxt** [comment]
我自己测试的情况使用im module而不是xim的时候不会有你描述的问题。根据你使用的桌面，可能使用gtk3/qt5的im module。

目前来说似乎只有fcitx5的xim有这个现象fcitx4我暂时没有注意到，而且由于这个是fcitx5的issue，所以我默认你使用了fcitx5。大概是什么原因导致的我大概有点想法，我提出安装fcitx5的im module只是提供一个绕过问题的方法。可能你的im module没有配置正确？

Gtk的桌面
strace -f libreoffice  2>&1 | grep fcitx.*so
应当能显示
stat("/home/csslayer/Develop/build/fcitx5/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so", {st_mode=S_IFREG|0755, st_size=51368, ...}) = 0

或者KDE的应当能显示
strace -f libreoffice  2>&1 | grep fcitx.*so
openat(AT_FDCWD, "/home/csslayer/Develop/build/fcitx5/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 9

加载对应的im module，如果没有，建议检查一下fcitx的环境变量配置 
https://fcitx-im.org/wiki/Configure_(Other)

**Comment by GreatBigWhiteWorld** [comment]
opensuse KDE下，输入 strace -f libreoffice 2>&1 | grep fcitx.*so
没有任何显示。fcitx的环境变量也调整了，但是问题还一样。

**但是**，昨天libreoffice系统更新升级到6.3了，这个问题就消失了。
