### ISSUE TITLE
fcitx5 won't display candidate box in Xwayland programs when running as a pure Wayland process, or is very lagging in Wayland programs when running as a Xwayland program

### ISSUE THREAD

**Issue by VitalyAnkh** [fcitx/fcitx5#300]
**Describe the bug**
fcitx5 won't display candidate box when running as a wayland native process, or is very lagging when typing within wayland programs when running as a Xwayland program

**To Reproduce**
The first problem:
1. Make sure the fcitx5 runs under Xwayland (I don't know how to achieve this... Maybe after startup typing in Xwayland programs first?)
2. Type with fcitx5 within a Wayland program, it's lagging (compared to typing within Xwayland programs).
The second
1. Make sure the fcitx5 run under Wayland (not Xwayland)
2. Open a GUI that runs under Xwayland, when typing with fcitx5, there is no candidate box.

**Expected behavior**
No lagging, No no candidate box.

**Desktop (please complete the following information):**
 - Desktop: Gnome
 - Display server type: Wayland
 - The output of fcitx5-diagnose: Here is a gist: https://gist.github.com/VitalyAnkh/1aab6bf0412ca0db881cc69eb7884d6c

**Additional context**
Here is a  screen recording when fcitx5 runs as a pure Wayland program and when typing within Xwayland programs, there is no candidate box.

https://user-images.githubusercontent.com/24508452/123445703-bb942f80-d60a-11eb-895b-ddd09e483f63.mp4

**Comment by wengxt** [comment]
I don't think it's a fcitx issue. Can't reproduce here with gnome-wayland + intel.

I suggest you try other wayland de to compare.
