### ISSUE TITLE
Ubuntu Wayland support: candidate window is in the wrong place

### ISSUE THREAD

**Issue by xuzhongxing** [fcitx/fcitx5#303]
OS and environment: Ubuntu on Wayland 21.04, (dual 4k monitor, 1.5 scale factor, maybe this is unimportant)

Installed fcitx5 by: apt install fcitx5-chinese-addons
Switched to fcitx5 input method.
When typing pinyin, the candidate characters window appears in the place far away from the input cursor.

I know that Wayland support is in progress. Just keep a record of the issue here.

**Comment by wengxt** [comment]
There's only certain setup would work. See also: https://www.csslayer.info/wordpress/fcitx-dev/client-side-input-panel-for-fcitx-5/
If latest fcitx5-gtk/fcitx5-qt doesn't help, you may want to post the name of relevant application. And also kimpanel is in used or not.

**Comment by xuzhongxing** [comment]
我安装了fcitx5-frontend-gtk3和fcitx-module-kimpanel，系统环境还是ubuntu 21.04 wayland. 应用程序是firefox wayland模式。
输入法窗口还是在很远的地方出现。

**Comment by wengxt** [comment]
具体设置是什么样的，有没有缩放，是在哪个程序里输入

**Comment by xuzhongxing** [comment]
![a](https://user-images.githubusercontent.com/5483073/124429388-68577500-dda0-11eb-8ac9-0dfa74a0c1e3.jpg)

**Comment by xuzhongxing** [comment]
Gnome 1.5倍字体缩放

**Comment by xuzhongxing** [comment]
貌似和双显示器有关系。我是双显示器环境。
单显示器环境下是正常的。

**Comment by xuzhongxing** [comment]
总结一下触发条件：

Ubuntu Wayland环境
使用非xwayland应用，如gnome-terminal
1.5倍的scaling factor
双显示器

**Comment by wngtk** [comment]
这个问题还是存在。上次安装这个输入法的时候没有这个问题。有问题的是在Firfox，系统是Ubuntu 21.10
