### ISSUE TITLE
commit 9dd694248cbdb11030637493c6708ad815cb0010 cause wine output invalid character in chinese

### ISSUE THREAD

**Issue by l12436** [fcitx/fcitx5#304]
**Describe the bug**
after commit 9dd694248cbdb11030637493c6708ad815cb0010 update with xim, wine always receive incorrect character.

**To Reproduce**
1. wine notepad
2. try to type character with none English. I am libchewing user.

**Expected behavior**
It should output correct word

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: X11
 - The output of fcitx5-diagnose if possible.
   - [log.gz](https://github.com/fcitx/fcitx5/files/6739062/log.gz)

**Additional context**
revert commit 9dd694248cbdb11030637493c6708ad815cb0010 will work as expect.

**Comment by wengxt** [comment]
You need to upgrade xcb-imdkit to the latest version.
