### ISSUE TITLE
Cannot use English input as default

### ISSUE THREAD

**Issue by xxyangyoulin** [fcitx/fcitx5#307]
env：Ubuntu：Gnome / bspwm

Configured `DefaultIM=keyboard-us`，but it will automatically become `pinyin`！

**Comment by xxyangyoulin** [comment]
I have closed fcitx5 before proceeding with file modification

**Comment by wengxt** [comment]
Emm, I suggest you use fcitx5-configtool to do the configuration.

You need to add it to the group too.

**Comment by xxyangyoulin** [comment]
Thanks for your reply, it works very well！
