### ISSUE TITLE
[Feature Request] 由主题控制预编辑区文本和背景颜色

### ISSUE THREAD

**Issue by hosxy** [fcitx/fcitx5#31]
Fcitx5 最近加入了我非常喜欢的 inline_preedit 模式，但是我发现 预编辑区那块的文本和背景颜色 好像不能由主题控制，
比如同一个主题，fcitx5自带pinyin和fcitx5-rime 行为就不一致，如图：
fcitx5-rime：![深度截图_选择区域_20191227151405](https://user-images.githubusercontent.com/17108640/71506445-e7badd00-28bb-11ea-8fa1-dfa45cd5c229.png)
fcitx5-pinyin：![深度截图_选择区域_20191227151453](https://user-images.githubusercontent.com/17108640/71506449-e8ec0a00-28bb-11ea-87d3-8b81bd728070.png)

而且同样是fcitx5-rime，在gtk和qt程序中也不一致：

GTK：![深度截图_选择区域_20191227151405](https://user-images.githubusercontent.com/17108640/71506557-6879d900-28bc-11ea-852b-a162d6eecbd8.png)
QT：![深度截图_选择区域_20191227152006](https://user-images.githubusercontent.com/17108640/71506558-6879d900-28bc-11ea-8392-5659ee4f04da.png)

这一块的 文本颜色和背景高亮颜色 能否直接由fcitx5主题来控制，这样的话不同输入法在不同程序中也能做到外观一直

**Comment by wengxt** [comment]
首先fcitx正是使用主题颜色，出现如图的情况应该是你的主题配置/应用程序人为设置高亮颜色为那个颜色。
其次，每个输入法引擎可以自己选择是否使用“类高亮”来显示，不一致只是在实现上的选择而已。rime使用高亮只是为了和其他rime实现一致，而我自己其实不喜欢高亮所以fcitx自带拼音没有采用类似的方式。

**Comment by hosxy** [comment]
> 首先fcitx正是使用主题颜色，出现如图的情况应该是你的主题配置/应用程序人为设置高亮颜色为那个颜色。
> 其次，每个输入法引擎可以自己选择是否使用“类高亮”来显示，不一致只是在实现上的选择而已。rime使用高亮只是为了和其他rime实现一致，而我自己其实不喜欢高亮所以fcitx自带拼音没有采用类似的方式。

其实我的意思是
如果没有开  PreeditInApplicaation 那键入的字符显示在候选框里，这时候键入字符和背景高亮的确是受主题里的`HighlightColor`和`HighlightBackgroundColor`控制

但是如果开了 PreeditInApplicaation 的话，键入字符显示在预编辑区，这时候就不受主题里的`HighlightColor`和`HighlightBackgroundColor`控制了(其实我想表达的是预编辑区文本颜色和高亮不受主题控制)

**Comment by wengxt** [comment]
<img width="158" alt="Screenshot_20191230_183951" src="https://user-images.githubusercontent.com/259684/71608200-37a3d900-2b34-11ea-8e62-3295e71bece6.png">
<img width="158" alt="Screenshot_20191230_184130" src="https://user-images.githubusercontent.com/259684/71608201-37a3d900-2b34-11ea-9971-5d971c33651c.png">
参见图，我是不知道咋就不符合主题了

当然，如果你的意思是不符合皮肤的主题，那确实，因为程序中的预编辑是要符合程序自己的主题的。
