### ISSUE TITLE
chrome92的bug ，将预编辑关闭后删除键将拼音串和编辑框的都删除了

### ISSUE THREAD

**Issue by chenshijie-uos** [fcitx/fcitx5#311]
chrome92的bug ，将预编辑关闭后删除键将拼音串和编辑框的都删除了。
chrome91版本没有这个bug.

![录屏_选择区域_20210723115054](https://user-images.githubusercontent.com/69958796/126736040-34a690d7-a668-4d15-a3b9-3cb6d96eca78.gif)

记录一下chrome bug 单号，随后我会关闭issues.
https://bugs.chromium.org/p/chromium/issues/detail?id=1232283

**Comment by xingwozhonghua** [comment]
![file-read-230555](https://user-images.githubusercontent.com/18661883/128111293-35e32cdc-66e2-411d-9ce9-28c1e6afe3c5.png)

92.0.4514.131已经修复完毕
