### ISSUE TITLE
How to hide tray icon?

### ISSUE THREAD

**Issue by duongdominhchau** [fcitx/fcitx5#314]
How can I hide the tray icon? In Fcitx 4 I can set `UseTray=False` in `conf/fcitx-classic-ui.config`, but I can't find it in Fcitx 5. I'm using fcitx 5.0.8.

**Comment by wengxt** [comment]
There's no such an option, because we don't have floating window anymore, so tray icon is necessary to access some of the functionalities.

**Comment by duongdominhchau** [comment]
Ah, I see, thank you.
