### ISSUE TITLE
在webkit2gtk程序中，光标不跟随

### ISSUE THREAD

**Issue by yanwh0311** [fcitx/fcitx5#315]
fcitx5在webkit2gtk程序中，光标不跟随

ibus没有问题

**Comment by wengxt** [comment]
bug是webkit2gtk的。当预编辑文本光标不在预编辑结尾时webkit2gtk汇报的光标位置错误，如图，ibus有相同的问题（输入一段之后按左移动光标即可重现）。

![图片](https://user-images.githubusercontent.com/259684/127730505-244a6885-3ceb-4527-bfca-f419a526111f.png)

请汇报给 webkit2gtk。
