### ISSUE TITLE
Ctrl+5 doesn't work after starting fcitx

### ISSUE THREAD

**Issue by timshen91** [fcitx/fcitx5#319]
My environment:
* Manjaro + kde
* fcitx version 4.2.9.8-1

Repros:
* Open Google Chrome, create 10 tabs. Ctrl+{1,2,3,4,6,7,8,9} all work (it switches to the nth tab), but Ctrl+5 doesn't
* in other applications (e.g. a terminal app), binding Ctrl+5 to an action is successful, but the action can't be triggered
* `showkey -a` doesn't show ctrl+5

Close fcitx and everything comes back to normal.

**Comment by wengxt** [comment]
not relevant to fcitx5.

**Comment by MrQubo** [comment]
Can confirm, bug is not present on fcitx5. Where should I report the bug for fcitx?

**Comment by MrQubo** [comment]
Ctrl+5 by default is set to "Reload configuration".
It's in "Global Config" > "Hotkey", after checking "Show Advanced Options".
Just click on "Reload configuration" binding and press "Esc" to unbind, or choose some other binding.
