### ISSUE TITLE
能否默认登陆自动启动？

### ISSUE THREAD

**Issue by OkayPJ** [fcitx/fcitx5#323]
**Describe the bug**
`Fcitx5` 能否默认登陆自动启动？现在，可以使用
```
cp /usr/share/applications/org.fcitx.Fcitx5.desktop ~/.config/autostart/
```
来让 `Fcitx5` 登陆自动启动，是否可以在安装后就默认自动启动？

**To Reproduce**
1. 安装 `fcitx5`
2. 重新登陆/重启，不能默认启动

**Expected behavior**
登陆自动启动

**Desktop (please complete the following information):**
 - 桌面：Xfce
 - 显示服务器：X11

**Additional context**
Debian 11

**Comment by wengxt** [comment]
since you're using debian, try im-config.

**Comment by gnaggnoyil** [comment]
看了一下Debian 11的fcitx5包中缺少`/etc/xdg/autostart`中的对应启动项文件.很奇怪,fcitx5的默认构建过程应该是会向这个地方写入自己的启动项文件的,这个文件Archlinux的fcitx5包也有.

可能是Debian 11的bug. <s>当然也有可能是Debian 11的feature.</s>

**Comment by zhsj** [comment]
是feature，请参考Debian的文档 https://wiki.debian.org/zh_CN/I18n/Fcitx5

**Comment by mooction** [comment]
```text
$ sudo dpkg-query -S  im-launch.desktop
im-config: /etc/xdg/autostart/im-launch.desktop
$ cat /etc/xdg/autostart/im-launch.desktop 
[Desktop Entry]
Name=im-launch
Exec=sh -c 'if [ "x$XDG_SESSION_TYPE" = "xwayland" ] ; then exec env IM_CONFIG_CHECK_ENV=1 im-launch true; fi'
TryExec=im-launch
Type=Application
NoDisplay=true
```

**Comment by mooction** [comment]
```bash
ln -s /usr/share/applications/org.fcitx.Fcitx5.desktop ~/.config/autostart/
```
