### ISSUE TITLE
fcitx5+rime emoji cannot display

### ISSUE THREAD

**Issue by ytingone** [fcitx/fcitx5#325]
**Describe the bug**
![Screenshot_2021-08-19_15-55-13](https://user-images.githubusercontent.com/7035143/130188788-eb434182-4bd2-4a73-8f2c-56cb48d8a34f.png)

**To Reproduce**
1. Switch to fcitx5-rime
2. Try to type `ha`

**Desktop (please complete the following information):**
 - Desktop: Xfce 4.16 in Debian 11
 - Display server type: X11

**Additional context**
`Noto Sans CJK` & `Noto Color Emoji` both installed.
`.config/fcitx5/conf/classicui.conf` set fonts to `Noto Sans CJK SC`
`librime-data-emoji` installed

**Comment by wengxt** [comment]
建议研究你的字体配置解决。

**Comment by zombie110year** [comment]
我是在 `.local/share/fcitx5/conf/classicui.conf` 里面设置 `Font="Noto Color Emoji"` 解决的。

**Comment by jcleng** [comment]
> 我是在 `.local/share/fcitx5/conf/classicui.conf` 里面设置 `Font="Noto Color Emoji"` 解决的。

设置了emoji的字体显示也没有用,还有其他解决方案吗?
