### ISSUE TITLE
添加输入框不跟随光标选项

### ISSUE THREAD

**Issue by solly0880** [fcitx/fcitx5#329]
Hello， 想问下。fcitx5 是否能添加输入框不跟随光标的选项，类似mac自带输入法的输入效果。类似下面截图的效果：

![linux_输入法2](https://user-images.githubusercontent.com/56422293/131211610-f6f1e5b8-54b1-4eb6-91e5-474eb4ddb8f0.jpg)

**Comment by lilydjwg** [comment]
不知道 mac 那个是怎样的，不过 fcitx5 不是默认固定在预编辑区的开始处吗？跟图片里的几乎完全一样。

**Comment by solly0880** [comment]
我指的是在linux 环境下。。。默认是跟随光标的
![123](https://user-images.githubusercontent.com/56422293/131213058-ea48be8a-8a31-4aea-b6c3-3d788749625c.png)

**Comment by solly0880** [comment]
用的是fcitx5+rime @lilydjwg

**Comment by lilydjwg** [comment]
哦 rime 啊，我没在 fcitx* 下用过。原来它是这个样子的啊。

**Comment by solly0880** [comment]
你用的啥输入法呐～～

**Comment by lilydjwg** [comment]
我用 fcitx5 自带的五笔。

**Comment by solly0880** [comment]
关了吧。。
