### ISSUE TITLE
Repeated key in st

### ISSUE THREAD

**Issue by pickfire** [fcitx/fcitx5#33]
On some applications such as [st](st.suckless.org), fcitx5 have weird behavior such that there feels like some keys are slow to appear (on us-dvorak) when holding the keys for a short while, the problem does not appear on fcitx.

Holding the keys in fcitx5 shuangpin input and mozc japanese input causes fcitx to kimpanel to hang (or crash) and I need to xkill st. Not sure if this is a bug in st or fcitx5 since it works with fcitx.

For example, hold `j` for a while and then press `k` when stop holding the key, the old keys will still be inserted. Maybe because I have a high keyboard typematic rate, `xset r rate 150 60`?

**Comment by wengxt** [comment]
it's irrelevant IMHO. I think the cause is same as #30.

**Comment by wengxt** [comment]
Should be improved after https://github.com/fcitx/fcitx5/commit/75d5cbd6d530ff5b670a715b47fec42f4d303847 .

**Comment by wengxt** [comment]
Actually I just noticed that st use a very small buffer for key string, so it will not commit string longer than 32 bytes from im. Probably you should report this to st upstream (looking for the caller of XmbLookupString). Comparing to xterm, xterm uses 500 bytes as the buffer, which should be practical for any common usage.

**Comment by pickfire** [comment]
The issue still persists even in the latest commit. `r435.8d889da-1` guess maybe I should go and check on the st side.

**Comment by pickfire** [comment]
In the meantime, I increased the buffer from 32 to 64 to take in middle to long string from IME, so it should even work for sentences now, the patch was included in upstream https://git.suckless.org/st/commit/895e5b50a8cc835c19a45e1e328eb4dc78f5fd0c.html

**Comment by wengxt** [comment]
Tried multiple different xim based application (gtk-xim, xterm) non of them have the same problem. So I don't think the issue is in fcitx. I suspect st misses some XFlush call.

**Comment by pickfire** [comment]
But I tried using old fcitx and it works fine, okay I will check on the XFlush call.

**Comment by pickfire** [comment]
I believe it probably have something to do with high autorepeat I did with `xset r rate 150 60`, when I did not set that, it works nicely.

**Comment by wengxt** [comment]
When we are talking about the real cause of the bug, we are not talking
about what triggers the bug.

With that being said, under your autorepeat settings, xterm, gtk based xim,
work properly. I can only assume that the bug is in st.

**Comment by pickfire** [comment]
Ah, I believed I spot the issue in st, it was introduced in https://git.suckless.org/st/commit/e85b6b64660214121164ea97fb098eaa4935f7db.html#h0-0-3 where `xximspot` to update the cursor for XIM is called in every draw.

**Comment by pickfire** [comment]
Weird that `XNPreeditStartCallback` is not called on fcitx, but ibus is able to recognize that. Should i not use `XIMPreeditCallbacks`?

**Comment by wengxt** [comment]
on the spot uses  XNPreeditStartCallback
over the spot doesn’t use that.

fcitx by default uses over the spot style for xim, because on the spot
doesn’t suppose notify the cursor location.

**Comment by pickfire** [comment]
Okay, thanks a lot for the input. st is also using over-the-spot for now. I also found a patch to fix the repeated key issue, looks like this is an issue with st, not fcitx5 but just that it doesn't happen in fcitx.
