### ISSUE TITLE
Debian11的im-config工具与fcitx5兼容不佳

### ISSUE THREAD

**Issue by ovmonk** [fcitx/fcitx5#331]
使用debian自带的`im-config`在选择输入法时，如果选择“fcitx5小企鹅输入法“则它会很坑的自动把环境变量设为了`fcitx5`，这样会导致输入速度较快的情况下，会有随机字母上屏。用`fcitx5-diagnose.sh`工具检测也提示环境变量设置有误。目前在kde plasma X11桌面环境下测试是这个结果，但是我个人认为其他桌面环境应该也是如此。
解决办法是：
1. 将

	```
	export XIM=fcitx
	export GTK_IM_MODULE=fcitx
	export QT_IM_MODULE=fcitx
	export XIM_PROGRAM=fcitx
	export XMODIFIERS="@im=fcitx"
	```

	放入`～/.xprofile`中；
2. 将`～/.xinputrc`中的`run_im fcitx5`更改为`run_im fcitx`。

不知道这是不是一个bug？

**Comment by zhsj** [comment]
https://wiki.debian.org/zh_CN/I18n/Fcitx5#A.2BXfJ35ZXumJg-

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977203

**Comment by wengxt** [comment]
not a upstream issue.
