### ISSUE TITLE
papirus-icon-theme和deepin-icon-theme图片包影响输入法任务栏图标显示

### ISSUE THREAD

**Issue by wangmawubi** [fcitx/fcitx5#332]
需要删除掉papirus-icon-theme和deepin-icon-theme所有相关的fcitx图片，以便各个厂商开发的输入法软件在去掉kimpanel服务后，使用任务栏部分经典界面也可以显示对应输入法图标。

https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

根据freedesktop的规则。如果主题包中有图片的话优先用主题包的图片，如果没有全部匹配的图标就搜索前端部分字符匹配的图片。

如果还是没有找到的话就去hicolor-icon-theme包中修改。

现在第三方的输入法图标默认放在hicolor中，然而因为papirus-icon-theme和deepin-icon-theme软件包的fcitx图片导致任务栏图标没有生效。

需要把这两个仓库的的fcitx图片删除掉。
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/search?q=fcitx
https://github.com/linuxdeepin/deepin-icon-theme/search?p=4&q=fcitx

请问下，这样解决问题是否合理，有没有更好的方法？如果大家决定可以，我就去将这两个仓库添加一个issue。

**Comment by wengxt** [comment]
和 fcitx 有啥关系？你直接把图标命名不要用 fcitx 前缀不就完了？

比如 sogoupinyin 图标就叫 sogoupinyin ，不要叫 fcitx-sogoupinyin

**Comment by wangmawubi** [comment]
嗯嗯 好的 我推下 这个方案

https://github.com/fcitx/mozc/blob/fcitx/src/unix/fcitx/mozc.conf#L4

`
apt downoad fcitx-mozc

dpkg -X ./fcitx-mozc*.deb ./fcitx-mozc-bin

.
└── usr
    ├── lib
    │   └── x86_64-linux-gnu
    │       └── fcitx
    │           └── fcitx-mozc.so
    └── share
        ├── doc
        │   └── fcitx-mozc
        │       ├── changelog.Debian.gz
        │       └── copyright
        ├── fcitx
        │   ├── addon
        │   │   └── fcitx-mozc.conf
        │   ├── inputmethod
        │   │   └── mozc.conf
        │   └── mozc
        │       └── icon
        │           ├── mozc-alpha_full.png -> ../../../icons/mozc/ui-alpha_full.png
        │           ├── mozc-alpha_half.png -> ../../../icons/mozc/ui-alpha_half.png
        │           ├── mozc-dictionary.png -> ../../../icons/mozc/ui-dictionary.png
        │           ├── mozc-direct.png -> ../../../icons/mozc/ui-direct.png
        │           ├── mozc-hiragana.png -> ../../../icons/mozc/ui-hiragana.png
        │           ├── mozc-katakana_full.png -> ../../../icons/mozc/ui-katakana_full.png
        │           ├── mozc-katakana_half.png -> ../../../icons/mozc/ui-katakana_half.png
        │           ├── mozc.png -> ../../../icons/mozc/ime_product_icon_opensource-32.png
        │           ├── mozc-properties.png -> ../../../icons/mozc/ui-properties.png
        │           └── mozc-tool.png -> ../../../icons/mozc/ui-tool.png
        ├── lintian
        │   └── overrides
        │       └── fcitx-mozc
        └── locale
            ├── ja
            │   └── LC_MESSAGES
            │       └── fcitx-mozc.mo
            ├── zh_CN
            │   └── LC_MESSAGES
            │       └── fcitx-mozc.mo
            └── zh_TW
                └── LC_MESSAGES
                    └── fcitx-mozc.mo

21 directories, 20 files
`
