### ISSUE TITLE
Hotkeys do not trigger unless focused on an input control

### ISSUE THREAD

**Issue by cyqsimon** [fcitx/fcitx5#333]
## Issue description

fcitx hotkeys do not trigger a state change unless focused on an input control.

For example, when I want to switch input method groups on desktop, pressing <kbd>Alt</kbd> + <kbd>LeftShift</kbd> (My configured hotkey for said function) does nothing. I have to either focus on some text input control first, or use the mouse to switch with the tray icon, which is cumbersome.

There can be several reasons why someone would want to have this behaviour. For me, I only use QWERTY layout for typing Chinese and Dvorak for everything else (including shortcut keys), which means I often want to switch input methods (or layouts in this case) to comfortably use commonly used hotkeys (e.g. <kbd>Ctrl</kbd> + <kbd>C</kbd>/<kbd>V</kbd>). Another potential reason is that this is the default behaviour on Windows, which means transitioning users may find it more comfortable.

I do not wish for this to necessarily become the default behaviour - only that it is available as a toggle-able option. As far as I know, there is no such option now in fcitx5.

## To reproduce

1. Go to any interface where you are not focused on an input control (e.g. Desktop)
2. Try to use any fcitx hotkey (e.g. switch IME)

### Expected behaviour
Hotkey is triggered and the IME/layout is switched
### Actual behaviour
Nothing happens

## Environment
 - OS: Manjaro
 - Kernel: `5.10.60-1-MANJARO`
 - Desktop: KDE Plasma 5.22.4
 - Display server: X11

**Comment by cyqsimon** [comment]
Some other users also having this particular issue:

https://askubuntu.com/q/1082925/1020143

https://askubuntu.com/q/950109/1020143

**Comment by wengxt** [comment]
That's expected behavior. Only input method group is global hotkey and only that will touch the system layout. Try create multiple group and assign them with different layout

**Comment by ASong5** [comment]
> Some other users also having this particular issue:
> 
> [Configure fcitx input method and keyboard layout](https://askubuntu.com/questions/1082925/configure-fcitx-input-method-and-keyboard-layout#:~:text=allow%20fcitx%20to%20switch%20input%20method%20independently%20of%20what%20control%20has%20focus%3B)
> 
> [Keyboard settings changing partially/not at all in Ubuntu MATE](https://askubuntu.com/questions/950109/keyboard-settings-changing-partially-not-at-all-in-ubuntu-mate#:~:text=the%20strange%20thing%20is%20that%20i%20can't%20switch%20layout%20until%20i%20have%20an%20active%20cursor%20in%20a%20text%20box.%20in%20a%20browser%20i%20can't%20swich%20layout%20when%20no%20input%20box%20is%20focused.)

i know this is old, but was wondering if you figured out a workaround. id also like to toggle inputs without first focusing an input control

**Comment by wengxt** [comment]
@ASong5 The group switching key is global (super space), you can create multiple group for layout switching.

**Comment by ASong5** [comment]
@wengxt I tried creating a separate group and switching back and forth with super+space, but it still only works when focused on input control.

**Comment by ASong5** [comment]
I'm using wayland

**Comment by wengxt** [comment]
@ASong5 that’s pretty expected. There’s no standard way to implement global hotkey that fcitx need under wayland right now. Which compositor are you using?

**Comment by ASong5** [comment]
Ah I see. I am using kde/kwin

**Comment by wengxt** [comment]
@ASong5 You can go to system settings -> legacy application -> allow x11 application to listen to all keyboard event (I don’t remember the exact name since I’m replying on my phone)

Then the xcb keyboard grab used by fcitx5 can work under kwin wayland.

**Comment by ASong5** [comment]
> @ASong5 You can go to system settings -> legacy application -> allow x11 application to listen to all keyboard event (I don’t remember the exact name since I’m replying on my phone)
> 
> Then the xcb keyboard grab used by fcitx5 can work under kwin wayland.

it works perfectly now. thanks so much!

**Comment by lVentus** [comment]
> @ASong5这是意料之中的。目前在 wayland 下没有标准方法来实现 fcitx 所需的全局热键。你使用的是哪个合成器？

请问hyprland要如何设置？以及有什么方法能用快捷键切换到制定的输入法群组吗（就像输入法切换器插件那样）

**Comment by twilightty** [comment]
> @ASong5 You can go to system settings -> legacy application -> allow x11 application to listen to all keyboard event (I don’t remember the exact name since I’m replying on my phone)
> 
> Then the xcb keyboard grab used by fcitx5 can work under kwin wayland.

I'm using Hyprland, any method I can use to achieve the same result?

**Comment by RobberFox** [comment]
> @ASong5 The group switching key is global (super space), you can create multiple group for layout switching.

Group switching also works for me only when text input is focused. I'm on X11, AwesomeWM

**Comment by wengxt** [comment]
@RobberFox x11 should work, but does awesome already has key binding to super+space?

**Comment by RobberFox** [comment]
I had changed the fcitx5 group switching keybinding (`Super + Q`) to avoid conflicting keybindings, it's not the cause.

**Comment by wengxt** [comment]
@RobberFox It can still be. If the super key itself is somehow affected. I just tested with KDE X11 and it works. Can you might check some other wm like openbox？

**Comment by ThatLiquidSnake** [comment]
Faced the same bug but on Linux Mint. Was it fixed?
