### ISSUE TITLE
KDE无法配置fcitx5

### ISSUE THREAD

**Issue by aoeiuv-liu** [fcitx/fcitx5#337]
新安装的 `fcitx5-im` 组包 和 `fcitx5-configtool` ，直接通过右键托盘配置启动的界面里没有 全局选项 和 附加组件 的设置内容。
命令行运行 `fcitx5-configtool` 出现报错
![2021-09-14_21-53](https://user-images.githubusercontent.com/20061353/133270884-49e9156a-70fa-434f-8a07-23cfac91b9fa.png)
临时用 `fcitx5-config-qt` 代替可用。

**Comment by xingwozhonghua** [comment]
fcitx5-diagnose >fcitx.log

拜托贴一下fcitx.log里面的信息，方便排查

**Comment by aoeiuv-liu** [comment]
> fcitx5-diagnose >fcitx.log
> 
> 拜托贴一下fcitx.log里面的信息，方便排查

[fcitx.log](https://github.com/fcitx/fcitx5/files/7162719/fcitx.log)

**Comment by wengxt** [comment]
Duplicate of fcitx/fcitx-configtool#45
