### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by 13242084001** [fcitx/fcitx5#34]
# Prepare targets for installation.
         ([this](dbus::DBusStruct<bool> value) {
           ^
/root/fcitx5/src/lib/fcitx/../fcitx-utils/dbus/objectvtable.h:180:25: note: in definition of macro ‘FCITX_OBJECT_VTABLE_WRITABLE_PROPERTY’
         [this, method = SETMETHOD](::fcitx::dbus::Message &msg) {              \
                         ^~~~~~~~~
/root/fcitx5/src/frontend/ibusfrontend/ibusfrontend.cpp: In lambda function:
/root/fcitx5/src/frontend/ibusfrontend/ibusfrontend.cpp:596:13: error: ‘this’ was not captured for this lambda function
             clientCommitPreedit_ = std::get<0>(value);
             ^
/root/fcitx5/src/lib/fcitx/../fcitx-utils/dbus/objectvtable.h:180:25: note: in definition of macro ‘FCITX_OBJECT_VTABLE_WRITABLE_PROPERTY’
         [this, method = SETMETHOD](::fcitx::dbus::Message &msg) {              \
                         ^~~~~~~~~
/root/fcitx5/src/frontend/ibusfrontend/ibusfrontend.cpp:596:13: error: invalid use of non-static data member ‘fcitx::IBusInputContext::clientCommitPreedit_’
             clientCommitPreedit_ = std::get<0>(value);
             ^
/root/fcitx5/src/lib/fcitx/../fcitx-utils/dbus/objectvtable.h:180:25: note: in definition of macro ‘FCITX_OBJECT_VTABLE_WRITABLE_PROPERTY’
         [this, method = SETMETHOD](::fcitx::dbus::Message &msg) {              \
                         ^~~~~~~~~
/root/fcitx5/src/frontend/ibusfrontend/ibusfrontend.cpp:604:33: note: declared here
     bool clientCommitPreedit_ = false;
                                 ^~~~~
src/frontend/ibusfrontend/CMakeFiles/ibusfrontend.dir/build.make:62: recipe for target 'src/frontend/ibusfrontend/CMakeFiles/ibusfrontend.dir/ibusfrontend.cpp.o' failed
make[2]: *** [src/frontend/ibusfrontend/CMakeFiles/ibusfrontend.dir/ibusfrontend.cpp.o] Error 1
CMakeFiles/Makefile2:1918: recipe for target 'src/frontend/ibusfrontend/CMakeFiles/ibusfrontend.dir/all' failed
make[1]: *** [src/frontend/ibusfrontend/CMakeFiles/ibusfrontend.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wengxt** [comment]
looks like it's your compiler bug.

clang 9.0.1 and gcc 9.2.0 build it fine.
