### ISSUE TITLE
拼音输入“jv”等含“v”音节有问题

### ISSUE THREAD

**Issue by wszqkzqk** [fcitx/fcitx5#347]
目前“jv”只有输入“ju”才能识别，输入“jv”会识别成两个音节，这不合理吧……

**Comment by wengxt** [comment]
模糊音勾选 u v那项

**Comment by wszqkzqk** [comment]
可是本来应该是v才是对的啊

**Comment by wszqkzqk** [comment]
> 模糊音勾选 u v那项

可是本来应该是v才是对的啊

**Comment by CoelacanthusHex** [comment]
> > 模糊音勾选 u v那项
> 
> 可是本来应该是v才是对的啊

![图片](https://user-images.githubusercontent.com/43064781/135787444-2a7b3e2d-4711-42df-b979-e4e9ca702fcb.png)
摘自《汉语拼音方案》
