### ISSUE TITLE
Abolish bindings of keyboard input, use keycodes instead

### ISSUE THREAD

**Issue by Socialdarwinist** [fcitx/fcitx5#35]
The keybindings should be independent of the keyboard layout.

There are indefinitely many examples how the bindings of Fcitx do not work because it uses the strings produced via the keyboard layout for input.

One example: Shift + Ctrl + Alt + U is the default binding for the Unicode typing add-on. But it only works if you have a Latin layout. If you have switched to an input method which is not a Latin layout, i.e. for example you type Arabic or Russian and want to browse in Unicode, you cannot use this bind.
Another example: “-” “=” are keybindings for switching between candidates. Currently these do not make sense at all if your default layout is for example German, where the hyphen-minus character “-” is mapped on ⟨AB10⟩ and the equality sign “=” on ⟨AE10⟩.
Third example: The same way it does not make sense to map the combination to activate the Input Method as Ctrl + some alphabetic key like Control + i because then you cannot change back to your default layout.

I know that there countless examples of such a programming accross all types of programs, but I strongly affirm that there is no good reason whatsoever to do that – it’s a child of Anglosaxon sloth. And an IME is the most wrong place for it, because it is not only one of the most blatant offences against multilingualization in computing, but an offence against m17n directly rooted in a lack of concern for different keyboard layouts. I have caused this bug to vanish in [some dwindling games where only few could care](https://github.com/ddnet/ddnet/issues/796#issuecomment-316681081) – it inflicts dire grief that such an error is present in Fcitx, the purpose of which is exactly to put in various languages, in the whole systems of users.

**Comment by wengxt** [comment]
This is already implemented in fcitx5 and fcitx5-qt.

**Comment by Socialdarwinist** [comment]
@wengxt Since a few weeks, the old behaviour or similar is reintroduced by something. E.g.:

I switch to an input method which is the Russian keyboard layout and press Ctrl + V to paste a text into an input field. But I obtain the character м instead which is in the position of that letter key, the keyboard combination is not passed.

Likewise Ctrl + Shift + Alt + U does not open the Unicode selector when the input method is active.

Using Fedora and KDE now; the set-up of fcitx5 done by `im-config`, there being also alternative options including environment variables and apparently – reading the issues – graphical ones based in the desktop environment as well.

There have been many commits also introducing new settings. Am I supposed to switch something or is it just a bug?

**Comment by Socialdarwinist** [comment]
After an update of fcitx5 of yesterday, this appears fixed. Guess I have mentioned it for history then.
