### ISSUE TITLE
fcitx5 附加组件 经典用户界面无法设置字体

### ISSUE THREAD

**Issue by unknowndevQwQ** [fcitx/fcitx5#366]
**Describe the bug**
![image](https://user-images.githubusercontent.com/52807407/139520694-d3cdfcac-f8dc-4243-b7af-362daf0d0b9b.png)
图中两处字体设置更改后，应用按钮不可按下，按下确定按钮并重新打开设置时会发现字体依旧是更改之前的
另一个小问题是显示字体的框长度并不会跟随字体长度的改变而改变（可能会在下一个 issue 中描述）

**To Reproduce**
1. 右键托盘并点击配置，选择配置附加组件，选择经典用户界面
2. 设置「字体」或者「菜单字体」
3. 点击确定并重新打开上述配置窗口

**Expected behavior**
可以设置想要的字体并保存，或者选择跟随跟桌面环境的设置

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: X11

**Comment by wengxt** [comment]
保存测试没有问题，你 fcitx5-configtool 是什么版本

**Comment by unknowndevQwQ** [comment]
> 保存测试没有问题，你 fcitx5-configtool 是什么版本

版本如何查看？

**Comment by unknowndevQwQ** [comment]
比较奇怪的是，如果我先用 fcitx5-config-qt 设置一次字体并确认，在这之后 fcitx5-configtool 也可以设置

**Comment by wengxt** [comment]
@unknowndevQwQ 这个是脚本，是说包

**Comment by wengxt** [comment]
@unknowndevQwQ 那你试试 1、退出 fcitx5

**Comment by wengxt** [comment]
那你试试
1、退出 fcitx5
2、删除 ~/.config/fcitx5/conf/classicui.conf
3、启动 fcitx5
4、用 kcmshell5 fcitx5 配置字体

是否能重现你的问题

**Comment by unknowndevQwQ** [comment]
> 那你试试 1、退出 fcitx5 2、删除 ~/.config/fcitx5/conf/classicui.conf 3、启动 fcitx5 4、用 kcmshell5 fcitx5 配置字体
> 
> 是否能重现你的问题

这样的话就能正常设置了

**Comment by wengxt** [comment]
@unknowndevQwQ 那你还能重现你的问题吗

**Comment by unknowndevQwQ** [comment]
> @unknowndevQwQ 那你还能重现你的问题吗

如果我把字体设置为 `Noto Sans Mono Medium Medium 10` 之后问题可以重现
![image](https://user-images.githubusercontent.com/52807407/139562998-b13cdc6b-4db8-449d-b71c-97cc1460332b.png)

同如果再打开配置的话，它弹出的字体选择是 `Noto Sans Mono Medium 10`
![image](https://user-images.githubusercontent.com/52807407/139563020-5e634b1d-7a72-4145-936e-4ce3d7557b3f.png)
