### ISSUE TITLE
The computer does not start automatically after restarting

### ISSUE THREAD

**Issue by P-rctica** [fcitx/fcitx5#369]
The Fcitx5 configuration shows: Cannot connect to Fcitx via DBus. Is Fcitx running?

# 系统信息:
1.  `uname -a`:

        Linux Kali 5.14.0-kali2-amd64 #1 SMP Debian 5.14.9-2kali1 (2021-10-04) x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Kali
        Description:	Kali GNU/Linux Rolling
        Release:	2021.3
        Codename:	kali-rolling

3.  `lsb_release -d`:

        Description:	Kali GNU/Linux Rolling

4.  `/etc/lsb-release`:

    `/etc/lsb-release` 未找到.

5.  `/etc/os-release`:

        PRETTY_NAME="Kali GNU/Linux Rolling"
        NAME="Kali GNU/Linux"
        ID=kali
        VERSION="2021.3"
        VERSION_ID="2021.3"
        VERSION_CODENAME="kali-rolling"
        ID_LIKE=debian
        ANSI_COLOR="1;31"
        HOME_URL="https://www.kali.org/"
        SUPPORT_URL="https://forums.kali.org/"
        BUG_REPORT_URL="https://bugs.kali.org/"

6.  桌面环境：

    桌面环境为 `kde`。

7.  Bash 版本：

        BASH_VERSION='5.1.8(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':0'

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn", "", ""

3.  Locale：

    1.  全部可用 locale：

            C
            C.UTF-8
            POSIX
            zh_CN.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LANGUAGE=zh_CN:zh
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME="zh_CN.UTF-8"
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/turing

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/turing/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/turing/.config/fcitx5`)。

5.  当前用户：

    脚本作为 turing (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: `5.0.9`

3.  进程：

    **Fcitx5 没有在运行。**
    **请访问 [入门指南](http://fcitx-im.org/wiki/Beginner%27s_Guide/zh-cn) 页面上对应您发行版的配置链接查看如何配置 fcitx5 的自动启动.**

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

    找到了 fcitx5 的 kcm 模块。

        kcm_fcitx5                 - 配置输入法

# 前端设置：
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    **无法在根窗口找到 xim_server。**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

3.  Qt 输入法模块文件：

    找到了未知的 fcitx qt 模块：`/lib/x86_64-linux-gnu/qt5/plugins/kcms/kcm_fcitx5.so`。
    找到了 fcitx5 的 qt5 输入法模块：`/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了 fcitx5 qt5 模块：`/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`。**

        **无法找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        **无法找到 gtk 3 的 `gtk-query-immodules`。**

        **无法找到 gtk 3 的 fcitx5 输入法模块。**

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        在 `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        **无法输入法模块缓存 `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 中找到 fcitx5**

        **无法在缓存中找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        在 `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.30` 的输入法模块缓存。
        版本行：

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.30

        已找到 gtk `3.24.30` 的 fcitx5 输入法模块。

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        在 `/lib/x86_64-linux-gnu/gtk-4.0/4.0.0/immodules/giomodule.cache` 找到了 gtk `4` 的输入法模块缓存。
        已找到 gtk `4` 的 fcitx5 输入法模块。

            libim-fcitx5.so: gtk-im-module

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 26 个已启用的插件：

            Simplified and Traditional Chinese Translation
            Classic User Inteface
            Clipboard
            Cloud Pinyin
            DBus
            DBus Frontend
            Emoji
            Fcitx4 Frontend
            Full width character
            IBus Frontend
            Input method selector
            Keyboard
            KDE Input Method Panel
            Status Notifier
            Notification
            Pinyin
            Extra Pinyin functionality
            Punctuation
            Quick Phrase
            Spell
            Table
            Unicode
            Wayland
            Wayland Input method frontend
            XCB
            X Input Method Frontend

    2.  找到了 0 个被禁用的插件：

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 2 个已启用的用户界面插件：

        Classic User Inteface
        KDE Input Method Panel

# 日志：
1.  `date`:

        2021年 10月 31日 星期日 11:22:54 CST

2.  `/home/turing/.config/fcitx5/crash.log`:

    `/crash.log` 未找到.

**Comment by P-rctica** [comment]
The Fcitx5 configuration shows: Cannot connect to Fcitx via DBus. Is Fcitx running?

**Comment by wengxt** [comment]
就单纯没启动吧，手动启动有错误吗？

**Comment by P-rctica** [comment]
就是没有启动，手动是可以正常启动的。在终端直接输入**‘fcitx5’**就可以直接启动

**Comment by wengxt** [comment]
那感觉和fcitx没关系啊，要么是你的发行版打包没包含 etc/xdg/autostart 那个文件，要么是你的桌面没支持（diagnose看起来是kde,应该有支持），要么是你不知怎么禁用了。

**Comment by chenshijie-uos** [comment]
有一个简单点的方式，可以解决你的问题，在etc/profile 
末尾加上
fcitx5&
就可以

**Comment by wengxt** [comment]
@chenshijie-uos 这个问题很大，请不要这么做。
Fcitx 5 其实不在意 X 是不是已经运行，完全可以无视 X 的存在工作。如果要启动之后再连接 X 需要特殊的请求才行

既然你在用 kde 你直接去 kde 的自动启动里添加一个就可以了。

**Comment by gnaggnoyil** [comment]
kali的fcitx5 package确实没有打包`etc/xdg/autostart`. 我猜这里应该和Debian一样,使用im-config.

@chenshijie-uos

**Comment by chenshijie-uos** [comment]
> kali的fcitx5 package确实没有打包`etc/xdg/autostart`. 我猜这里应该和Debian一样,使用im-config.
> 
> @chenshijie-uos

https://salsa.debian.org/input-method-team/fcitx5/-/tree/master/data

是的确实没有

应该是为了兼容im-config

可能debian系更希望用户使用im-config管理输入法框架

**Comment by P-rctica** [comment]
我就是在 kde 的自动启动里添加一个

**Comment by P-rctica** [comment]
我就是在kde自动启动加了一个，确实可以了
