### ISSUE TITLE
功能建议：按住shift时如果鼠标有按键操作，则在松开shift时不响应“按下shift”的快捷键

### ISSUE THREAD

**Issue by pikakolendo02** [fcitx/fcitx5#370]
Arch Linux + KDE
```
fcitx5 5.0.9-1
fcitx5-chinese-addons 5.0.7-1
fcitx5-configtool 5.0.6-1
fcitx5-gtk 5.0.8-1
fcitx5-material-color 0.2.1-1
fcitx5-mozc 2.26.4360.102.gca82d39-1
fcitx5-pinyin-moegirl 20211014-1
fcitx5-pinyin-zhwiki 1:0.2.3.20211016-1
fcitx5-qt 5.0.7-1
fcitx5-table-extra 5.0.5-1
fcitx5-table-other 5.0.5-1
```
比如我习惯将shift作为输入法激活/非激活切换。
假如我在文字编辑器（Libreoffice Writer或Kate）中，想选择一段文字，先将光标定位到选择区域开头，按着shift键单击结尾，此时松开shift，输入法会切换激活状态，有一点点不方便。
再假如我在使用blender，按住shift+鼠标中键移动视图，松开shift时也会切换激活状态。
使用shift+上下左右等键盘上的按键进行选择，则不会出现这种情况。
谢谢开发者的阅读，希望fcitx5越做越好！

**Comment by pikakolendo02** [comment]
奇怪的是，火狐里面的输入框中使用“shift+单击”的选择方式，并不会切换😂

**Comment by wengxt** [comment]
你好，我检查了一下 QPlatformInputContext 里面的回调，在没有输入文字时看起来并没有能通知输入法中间进行了任何行为的方式，所以可能没办法实现这种功能。

我可能只能建议比如你把你切换输入法的 shift 放到右边，左侧 shift 选择文字这样……

**Comment by pikakolendo02** [comment]
在Cinnamon里面的xed里按shift+单击也会触发切换输入法😭
