### ISSUE TITLE
bug: fcitx5 的 kcm 配置界面 -> 附加组件 -> 经典用户界面 显示问题

### ISSUE THREAD

**Issue by unknowndevQwQ** [fcitx/fcitx5#374]
**Describe the bug**
这是 kcm 界面最大化后显示比较长的字体时的情况
![image](https://user-images.githubusercontent.com/52807407/139615357-97cbef17-5101-40a0-b00f-7d4d6e428ade.png)

这是 `fcitx5-config-qt` 界面最大化后显示比较长的字体时的情况
![image](https://user-images.githubusercontent.com/52807407/139615584-92839614-a0d5-4ab3-8bd0-436756884946.png)

fcitx5 的 kcm 界面不会因为字体长度或者窗口大小而改变

**Expected behavior**

fcitx5 的 kcm 界面会因为字体长度或者窗口大小而改变成合适的大小

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: X11

**Comment by wengxt** [comment]
已经修了？

**Comment by unknowndevQwQ** [comment]
> 已经修了？

在上一个我开的 issue 里一并修了？

**Comment by unknowndevQwQ** [comment]
问题已解决
