### ISSUE TITLE
反馈一个奇怪的「码表不可用」问题

### ISSUE THREAD

**Issue by yanhuacuo** [fcitx/fcitx5#376]
现在的 debian 11 上，已经默认带了 fcitx5，就尝试着将 fcitx4 上用的码表转译成二进制表挂入。

发现在 fcitx5 上，已经采用了新的「表头」，不过「码表正文」依然是相同的格式。

于是使用 **libime_tabledict -u xx.txt xx.dict** 来转译新表，新表及配置备份在此：[我的码表](https://github.com/yanhuacuo/fcitx5-issues)

参考了内置的表头，概况如下：

这个码表正文，应该没有问题，从 fcitx4 就一直在用，编码方面是 UTF-8，带不带 BOM 都试了不能正常工作。

``````
﻿KeyCode=abcdefghijklmnopqrstuvwxy
Length=4
Pinyin=@
[Rule]
e2=p11+p12+p21+p22
e3=p11+p21+p31+p32
a4=p11+p21+p31+n11
[Data]
a 工
a 戈
aa 式
aa 藏
aaa 工
aaaa 工
aaaa 㠭
aaab 㐂
aaau 菚
aad 匿
aad 匞
aadj 䘌
aadk 匿
aadn 慝
aadr 茙
aafo 蘜
aagf 䒰
aah 芽
aahb 䓉
aahc 菣
aahh 茝
aahh 茞
aahl 藍
aahm 藖
aaht 芽
``````

求指点

**Comment by wengxt** [comment]
你用的参数不对，fcitx5的词库管理方式和fcitx4有所不同。fcitx5的二进制词库合适分为系统词库和用户词库两个， -u 是生成用户词库

另外需要放的文件位置数据文件要基于 ~/.loca/share/fcitx5 不像fcitx4都是 ~/.config/fcitx

**Comment by yanhuacuo** [comment]
> 你用的参数不对，fcitx5的词库管理方式和fcitx4有所不同。fcitx5的二进制词库合适分为系统词库和用户词库两个， -u 是生成用户词库
> 
> 另外需要放的文件位置数据文件要基于 ~/.loca/share/fcitx5 不像fcitx4都是 ~/.config/fcitx

fcitx5 的结构已经了解了，码表转换不有 -u 就可以用了，非常感谢。

[测试可用的98五笔配置分享](https://github.com/yanhuacuo/fcitx5-issues)
