### ISSUE TITLE
关闭alacritty后，其他软件无法正常输入

### ISSUE THREAD

**Issue by nsxz1234** [fcitx/fcitx5#377]
每次关闭alacritty之后，其他软件就无法输入中文了，而且输入面板只会出现在已经关闭的alacritty的位置。这个问题只在gnome的wayland模式下出现，x11模式没有这个问题。还有就是其它terminal也没有这个问题，只有alacritty是这样的。

https://user-images.githubusercontent.com/26622011/141150389-09851ac7-f599-48e1-bd6d-fc29370a4c86.mp4

**Comment by wengxt** [comment]
用纯 ibus （完全没有 fcitx 情况） 测试了一下，这是 gnome 的 bug。请汇报给 gnome。

text-input-v3 也是通过 gnome shell 对接给 ibus 的，在 alacritty 退出之后，并没有取消这个虚拟的 input context 焦点，同时 gnome shell 把所有窗口的按键依然发送给这个虚拟的 ibus input context。

你以为你输入了其实 gnome-shell 夺走了所有的按键发送给了这个虚拟的 input context，它没有对应的程序。

暂时的 workaround 就是你进入 super 键的 dashboard 界面，那个地方的搜索框也使用这个虚拟 input context ，这样你可以把它的焦点重置

**Comment by nsxz1234** [comment]
还有一个问题，在某些软件中输入时，输入面板会不断的闪烁（比如firefox会闪，chrome不会）。这个问题在gnome的wayland模式以及sway wm会出现，x11没这个问题。还有就是如果把fcitx5-gtk退回到5.0.6或更早的版本，就没问题了。

https://user-images.githubusercontent.com/26622011/141164163-b0d2a2b5-2fe0-441f-a2b0-2544da962d6b.mp4

**Comment by wengxt** [comment]
怎么说呢，这是没办法的，有些compositor会更明显一点，有些不会。这个是为了能在 wayland 下正确显示输入窗口位置进行的妥协。gnome-shell 下推荐用这个 extensions https://extensions.gnome.org/extension/261/kimpanel/ 就不会闪了

**Comment by wengxt** [comment]
我突然想到一个另外的办法，如果我用两个窗口同时显示另一个隐藏的话是不是可以一定程度减少闪烁…我会考虑试一下

**Comment by wengxt** [comment]
关于闪烁，写了一段更详细的解释， 主要还是技术限制：
https://fcitx-im.org/wiki/FAQ#Candidate_window_is_blinking_under_wayland_with_Fcitx_5

**Comment by nsxz1234** [comment]
好的，虽然不是很懂，但是已经很好用了

**Comment by AlynxZhou** [comment]
> 用纯 ibus （完全没有 fcitx 情况） 测试了一下，这是 gnome 的 bug。请汇报给 gnome。
> 
> text-input-v3 也是通过 gnome shell 对接给 ibus 的，在 alacritty 退出之后，并没有取消这个虚拟的 input context 焦点，同时 gnome shell 把所有窗口的按键依然发送给这个虚拟的 ibus input context。
> 
> 你以为你输入了其实 gnome-shell 夺走了所有的按键发送给了这个虚拟的 input context，它没有对应的程序。
> 
> 暂时的 workaround 就是你进入 super 键的 dashboard 界面，那个地方的搜索框也使用这个虚拟 input context ，这样你可以把它的焦点重置

糟了，为啥我没法复现这个，我关了 alacritty 之后输入法是好的啊

**Comment by AlynxZhou** [comment]
很奇怪，刚才切到Atom没问题，切到Telegram就能复现

**Comment by wengxt** [comment]
@AlynxZhou 
1、同时打开多个程序
2、关闭后不要切换到 dashboard，否则问题就恢复了

我个人推荐 alacritty，然后后台放一个根本用不了输入法的程序（我绞尽脑汁想到的是 glxgears），然后你会发现 glxgears 的按键甚至都被发给输入法了。

考虑到以上因素，推测可能需要关闭 alacritty 后切换到的程序是 xwayland 程序？

**Comment by AlynxZhou** [comment]
> @AlynxZhou 1、同时打开多个程序 2、关闭后不要切换到 dashboard，否则问题就恢复了
> 
> 我个人推荐 alacritty，然后后台放一个根本用不了输入法的程序（我绞尽脑汁想到的是 glxgears），然后你会发现 glxgears 的按键甚至都被发给输入法了。
> 
> 考虑到以上因素，推测可能需要关闭 alacritty 后切换到的程序是 xwayland 程序？

我 Telegram 是 Wayland，反而 Atom 是 XWayland

**Comment by AlynxZhou** [comment]
@nsxz1234 这个 bug 是更新到 GNOME 41 才出现的吗

**Comment by wengxt** [comment]
@AlynxZhou 反正我是在 gnome 41 上测试的，很容易就重现了

**Comment by nsxz1234** [comment]
> @nsxz1234 这个 bug 是更新到 GNOME 41 才出现的吗

40就有

**Comment by AlynxZhou** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4776

总之先踢给上游，我怎么觉得说不定是 alacritty 的 wayland 实现有点问题（比如没好好退出什么的，我这边 alacritty 本身就巨卡无比），而且我这 focus 的位置都是正确的，只是没法上屏。

**Comment by wengxt** [comment]
@AlynxZhou 不可能是alacrity的问题。当alacritty退出的时候，和它相关的wayland object自然应当一起删除并清除他们造成的影响。只可能gnome shell的问题。

**Comment by wengxt** [comment]
@AlynxZhou 你监听和ibus相关通信就可以知道，问题出现时，所有的按键都在被发给gnome shell和ibus之间的连接，因为text input v3本质上只有一个链接。简单来说就是gnomeshell内部grab了之后没有ungrab这样的问题。

**Comment by lilydjwg** [comment]
闪烁的问题，我在想，compositer 能不能识别候选词窗口，然后在隐藏的时候稍微晚那么一两帧？

**Comment by wengxt** [comment]
@lilydjwg 不划算，不值得，特别是协议自己已经支持了，但问题是gtk3和qt5都没有新版本了，你要是gtk4就不会用这个hack

**Comment by wengxt** [comment]
@lilydjwg 我打算试试类似double buffer的办法用两个窗口（仅仅猜想）

**Comment by lilydjwg** [comment]
qt5 倒是还好，gtk3 不知道什么时候才能消失呢，我 gtk2 都还在 QAQ

**Comment by wengxt** [comment]
@lilydjwg gtk2是x，没有这种烦恼。另外qt5讲真，比gtk3更不闪…不知道是否和内部控制频率之类有关

**Comment by lilydjwg** [comment]
qt5 不移动位置的时候就不会闪啊，代码里有做判断。gtk3 是无论如何都会闪一下（不过 gtk3 也能把窗口伸到应用程序的窗口外边去）。我现在就是靠着自己 patch gtk3 模块来不闪的，不过它刚有更新，我得重新 patch 一份了。

我是指摆脱旧版本 gtk 看起来挺不容易的。
