### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5#378]
1, Currently the UI doesn't look very compact, there is too much space:
![image](https://user-images.githubusercontent.com/11857205/141229524-a14dc1d8-ea93-430d-84a9-8263e88acba7.png)

2, Could fcitx5 follow KDE's kcm style? This looks a bit better:
![image](https://user-images.githubusercontent.com/11857205/141229736-bdb0c322-2c2b-478b-8b61-05f080e2985e.png)

**Comment by wengxt** [comment]
No. Actually I didn't do any size customization and code is also following other KDE KCM. It is same as another activity KCM.

![图片](https://user-images.githubusercontent.com/259684/141231074-cfce78a7-02d8-4c83-9ad4-bb6ecd0b41c5.png)

**Comment by trmdi** [comment]
But fcitx does not use the same components and layout as KDE Shortcut kcm. And please see the first screenshot, don't you think that window is too big? Don't you think there is something could be improved here?

// Sorry if I bother you, I just want to improve it, not blame you or anything else.

**Comment by wengxt** [comment]
@trmdi I’m not fully understand where do you think it’s taking too much space, especially we have button but short cut is an arrow indicate the expand state.  

And as I stated, I didn’t set any additional spacing to make it larger. The size is just kirigami defaults.
