### ISSUE TITLE
Letters keep missing while you type fast

### ISSUE THREAD

**Issue by indam** [fcitx/fcitx5#379]
Manjaro系统，今天从fcitxi升级到fcitx5， 用的是fcitx5-chinese的小鹤双拼方案。
在Chrome和微信中打字时遇到丢字、错乱的问题，在终端好像没有这个问题。

What I typed was fa, but I got 'af'
![2021-11-11_16-37](https://user-images.githubusercontent.com/1610302/141269812-b96c0e0a-9216-469f-b327-9e4cf8550da9.jpg)

And here, I input 'Chrome' under Chinese mode, but 'o' slipped away from the candidate box. Annoying.
![2021-11-11_17-05](https://user-images.githubusercontent.com/1610302/141269819-bdde95ef-bb6d-4f10-86e1-08178f6c49b0.jpg)

**Comment by rocka** [comment]
终端运行 `fcitx5-diagnose` ，然后把结果发上来。这个问题大概率是没有安装 fcitx5-gtk

**Comment by indam** [comment]
> 终端运行 `fcitx5-diagnose` ，然后把结果发上来。这个问题大概率是没有安装 fcitx5-gtk

`# 系统信息:
1.  `uname -a`:

        Linux xp 5.10.61-1-MANJARO #1 SMP PREEMPT Thu Aug 26 20:36:54 UTC 2021 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	ManjaroLinux
        Description:	Manjaro Linux
        Release:	21.1.2
        Codename:	Pahvo

3.  `lsb_release -d`:

        Description:	Manjaro Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID=ManjaroLinux
        DISTRIB_RELEASE=21.1.2
        DISTRIB_CODENAME=Pahvo
        DISTRIB_DESCRIPTION="Manjaro Linux"

5.  `/etc/os-release`:

        NAME="Manjaro Linux"
        ID=manjaro
        ID_LIKE=arch
        BUILD_ID=rolling
        PRETTY_NAME="Manjaro Linux"
        ANSI_COLOR="32;1;24;144;200"
        HOME_URL="https://manjaro.org/"
        DOCUMENTATION_URL="https://wiki.manjaro.org/"
        SUPPORT_URL="https://manjaro.org/"
        BUG_REPORT_URL="https://bugs.manjaro.org/"
        LOGO=manjarolinux

6.  桌面环境：

    无法确定桌面环境。

7.  Bash 版本：

        BASH_VERSION='5.1.8(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':0'

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+inet(evdev)+terminate(ctrl_alt_bksp)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn", "", "terminate:ctrl_alt_bksp"

3.  Locale：

    1.  全部可用 locale：

            aa_DJ.utf8
            aa_ER.utf8
            aa_ER.utf8@saaho
            aa_ET.utf8
            af_ZA.utf8
            agr_PE.utf8
            ak_GH.utf8
            am_ET.utf8
            an_ES.utf8
            anp_IN.utf8
            ar_AE.utf8
            ar_BH.utf8
            ar_DZ.utf8
            ar_EG.utf8
            ar_IN.utf8
            ar_IQ.utf8
            ar_JO.utf8
            ar_KW.utf8
            ar_LB.utf8
            ar_LY.utf8
            ar_MA.utf8
            ar_OM.utf8
            ar_QA.utf8
            ar_SA.utf8
            ar_SD.utf8
            ar_SS.utf8
            ar_SY.utf8
            ar_TN.utf8
            ar_YE.utf8
            as_IN.utf8
            ast_ES.utf8
            ayc_PE.utf8
            az_AZ.utf8
            az_IR.utf8
            be_BY.utf8
            be_BY.utf8@latin
            bem_ZM.utf8
            ber_DZ.utf8
            ber_MA.utf8
            bg_BG.utf8
            bhb_IN.utf8
            bho_IN.utf8
            bho_NP.utf8
            bi_VU.utf8
            bn_BD.utf8
            bn_IN.utf8
            bo_CN.utf8
            bo_IN.utf8
            br_FR.utf8
            brx_IN.utf8
            bs_BA.utf8
            byn_ER.utf8
            C
            ca_AD.utf8
            ca_ES.utf8
            ca_ES.utf8@valencia
            ca_FR.utf8
            ca_IT.utf8
            ce_RU.utf8
            chr_US.utf8
            cmn_TW.utf8
            crh_UA.utf8
            csb_PL.utf8
            cs_CZ.utf8
            cv_RU.utf8
            cy_GB.utf8
            da_DK.utf8
            de_AT.utf8
            de_BE.utf8
            de_CH.utf8
            de_DE.utf8
            de_IT.utf8
            de_LI.utf8
            de_LU.utf8
            doi_IN.utf8
            dsb_DE.utf8
            dv_MV.utf8
            dz_BT.utf8
            el_CY.utf8
            el_GR.utf8
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IL.utf8
            en_IN.utf8
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SC.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM.utf8
            en_ZW.utf8
            eo.utf8
            es_AR.utf8
            es_BO.utf8
            es_CL.utf8
            es_CO.utf8
            es_CR.utf8
            es_CU.utf8
            es_DO.utf8
            es_EC.utf8
            es_ES.utf8
            es_GT.utf8
            es_HN.utf8
            es_MX.utf8
            es_NI.utf8
            es_PA.utf8
            es_PE.utf8
            es_PR.utf8
            es_PY.utf8
            es_SV.utf8
            es_US.utf8
            es_UY.utf8
            es_VE.utf8
            et_EE.utf8
            eu_ES.utf8
            fa_IR.utf8
            ff_SN.utf8
            fi_FI.utf8
            fil_PH.utf8
            fo_FO.utf8
            fr_BE.utf8
            fr_CA.utf8
            fr_CH.utf8
            fr_FR.utf8
            fr_LU.utf8
            fur_IT.utf8
            fy_DE.utf8
            fy_NL.utf8
            ga_IE.utf8
            gd_GB.utf8
            gez_ER.utf8
            gez_ER.utf8@abegede
            gez_ET.utf8
            gez_ET.utf8@abegede
            gl_ES.utf8
            gu_IN.utf8
            gv_GB.utf8
            hak_TW.utf8
            ha_NG.utf8
            he_IL.utf8
            hif_FJ.utf8
            hi_IN.utf8
            hne_IN.utf8
            hr_HR.utf8
            hsb_DE.utf8
            ht_HT.utf8
            hu_HU.utf8
            hy_AM.utf8
            ia_FR.utf8
            id_ID.utf8
            ig_NG.utf8
            ik_CA.utf8
            is_IS.utf8
            it_CH.utf8
            it_IT.utf8
            iu_CA.utf8
            ja_JP.utf8
            kab_DZ.utf8
            ka_GE.utf8
            kk_KZ.utf8
            kl_GL.utf8
            km_KH.utf8
            kn_IN.utf8
            kok_IN.utf8
            ko_KR.utf8
            ks_IN.utf8
            ks_IN.utf8@devanagari
            ku_TR.utf8
            kw_GB.utf8
            ky_KG.utf8
            lb_LU.utf8
            lg_UG.utf8
            li_BE.utf8
            lij_IT.utf8
            li_NL.utf8
            ln_CD.utf8
            lo_LA.utf8
            lt_LT.utf8
            lv_LV.utf8
            lzh_TW.utf8
            mag_IN.utf8
            mai_IN.utf8
            mai_NP.utf8
            mfe_MU.utf8
            mg_MG.utf8
            mhr_RU.utf8
            mi_NZ.utf8
            miq_NI.utf8
            mjw_IN.utf8
            mk_MK.utf8
            ml_IN.utf8
            mni_IN.utf8
            mn_MN.utf8
            mnw_MM.utf8
            mr_IN.utf8
            ms_MY.utf8
            mt_MT.utf8
            my_MM.utf8
            nan_TW.utf8
            nan_TW.utf8@latin
            nb_NO.utf8
            nds_DE.utf8
            nds_NL.utf8
            ne_NP.utf8
            nhn_MX.utf8
            niu_NU.utf8
            niu_NZ.utf8
            nl_AW.utf8
            nl_BE.utf8
            nl_NL.utf8
            nn_NO.utf8
            nr_ZA.utf8
            nso_ZA.utf8
            oc_FR.utf8
            om_ET.utf8
            om_KE.utf8
            or_IN.utf8
            os_RU.utf8
            pa_IN.utf8
            pap_AW.utf8
            pap_CW.utf8
            pa_PK.utf8
            pl_PL.utf8
            POSIX
            ps_AF.utf8
            pt_BR.utf8
            pt_PT.utf8
            quz_PE.utf8
            raj_IN.utf8
            ro_RO.utf8
            ru_RU.utf8
            ru_UA.utf8
            rw_RW.utf8
            sah_RU.utf8
            sa_IN.utf8
            sat_IN.utf8
            sc_IT.utf8
            sd_IN.utf8
            sd_IN.utf8@devanagari
            se_NO.utf8
            sgs_LT.utf8
            shn_MM.utf8
            shs_CA.utf8
            sid_ET.utf8
            si_LK.utf8
            sk_SK.utf8
            sl_SI.utf8
            sm_WS.utf8
            so_DJ.utf8
            so_ET.utf8
            so_KE.utf8
            so_SO.utf8
            sq_AL.utf8
            sq_MK.utf8
            sr_ME.utf8
            sr_RS.utf8
            sr_RS.utf8@latin
            ss_ZA.utf8
            st_ZA.utf8
            sv_FI.utf8
            sv_SE.utf8
            sw_KE.utf8
            sw_TZ.utf8
            szl_PL.utf8
            ta_IN.utf8
            ta_LK.utf8
            tcy_IN.utf8
            te_IN.utf8
            tg_TJ.utf8
            the_NP.utf8
            th_TH.utf8
            ti_ER.utf8
            ti_ET.utf8
            tig_ER.utf8
            tk_TM.utf8
            tl_PH.utf8
            tn_ZA.utf8
            to_TO.utf8
            tpi_PG.utf8
            tr_CY.utf8
            tr_TR.utf8
            ts_ZA.utf8
            tt_RU.utf8
            tt_RU.utf8@iqtelif
            ug_CN.utf8
            uk_UA.utf8
            unm_US.utf8
            ur_IN.utf8
            ur_PK.utf8
            uz_UZ.utf8
            uz_UZ.utf8@cyrillic
            ve_ZA.utf8
            vi_VN.utf8
            wa_BE.utf8
            wae_CH.utf8
            wal_ET.utf8
            wo_SN.utf8
            xh_ZA.utf8
            yi_US.utf8
            yo_NG.utf8
            yue_HK.utf8
            yuw_PG.utf8
            zh_CN.utf8
            zh_HK.utf8
            zh_SG.utf8
            zh_TW.utf8
            zu_ZA.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC=zh_CN.UTF-8
            LC_TIME=zh_CN.UTF-8
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY=zh_CN.UTF-8
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER=zh_CN.UTF-8
            LC_NAME=zh_CN.UTF-8
            LC_ADDRESS=zh_CN.UTF-8
            LC_TELEPHONE=zh_CN.UTF-8
            LC_MEASUREMENT=zh_CN.UTF-8
            LC_IDENTIFICATION=zh_CN.UTF-8
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/x

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/x/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/x/.config/fcitx5`)。

5.  当前用户：

    脚本作为 x (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: `5.0.9`

3.  进程：

    找到了 1 个 fcitx5 进程：

           9876 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` 工作正常。

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.308`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `9876`。

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

    **`kcmshell5` 未找到.**

# 前端设置：
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    Xim 服务的名称与环境变量中设置的相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

3.  Qt 输入法模块文件：

    找到了未知的 fcitx qt 模块：`/usr/lib/office6/qt/plugins/inputmethods/libqim-fcitx.so`。
    找到了 fcitx5 的 qt6 输入法模块：`/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了未知的 fcitx qt 模块：`/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`。
    找到了 fcitx5 的 qt 输入法模块：`/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了 fcitx5 qt5 模块：`/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

2.  `gtk-query-immodules`:

    1.  gtk 2:

        在 `/usr/bin/gtk-query-immodules-2.0` 找到了未知 gtk 版本的 `gtk-query-immodules`。

        **无法在 `/usr/bin/gtk-query-immodules-2.0` 的输出中找到 fcitx5。**

        **无法找到 gtk 2 的 `gtk-query-immodules`。**

        **无法找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        在 `/usr/bin/gtk-query-immodules-3.0` 找到了未知 gtk 版本的 `gtk-query-immodules`。

        **无法在 `/usr/bin/gtk-query-immodules-3.0` 的输出中找到 fcitx5。**

        **无法找到 gtk 3 的 `gtk-query-immodules`。**

        **无法找到 gtk 3 的 fcitx5 输入法模块。**

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        在 `/usr/lib/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        **无法输入法模块缓存 `/usr/lib/gtk-2.0/2.10.0/immodules.cache` 中找到 fcitx5**

        **无法在缓存中找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.30` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.30

        **无法输入法模块缓存 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 中找到 fcitx5**

        **无法在缓存中找到 gtk 3 的 fcitx5 输入法模块。**

    3.  gtk 4:

        **无法找到 gtk 4 的输入法模块缓存**

        **无法在缓存中找到 gtk 4 的 fcitx5 输入法模块。**

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 27 个已启用的插件：

            Simplified and Traditional Chinese Translation
            Classic User Inteface
            Clipboard
            Cloud Pinyin
            DBus
            DBus Frontend
            Emoji
            Fcitx4 Frontend
            Full width character
            IBus Frontend
            Input method selector
            Keyboard
            KDE Input Method Panel
            Status Notifier
            Notification
            Pinyin
            Extra Pinyin functionality
            Punctuation
            Quick Phrase
            Rime
            Spell
            Table
            Unicode
            Wayland
            Wayland Input method frontend
            XCB
            X Input Method Frontend

    2.  找到了 0 个被禁用的插件：

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 2 个已启用的用户界面插件：

        Classic User Inteface
        KDE Input Method Panel

# 日志：
1.  `date`:

        2021年 11月 11日 星期四 19:08:25 CST

2.  `/home/x/.config/fcitx5/crash.log`:

    `/crash.log` 未找到.
`

**Comment by indam** [comment]
> 终端运行 `fcitx5-diagnose` ，然后把结果发上来。这个问题大概率是没有安装 fcitx5-gtk

我先装一个试一下

**Comment by indam** [comment]
fixed with installing fcitx5-gtk, thx
