### ISSUE TITLE
Chromium/Electron(Ozone) Apps doesn't work with fcitx5

### ISSUE THREAD

**Issue by Neubulae** [fcitx/fcitx5#381]
**Describe the bug**
Under Chromium(Ozone)/Electron(Ozone) Apps, fcitx5 ceases to function. 

**To Reproduce**
1. `chrome/chrome-dev/electron --enable-features=UseOzonePlatform --ozone-platform=wayland`
2. Try to type.
3. Bruh moment.

**Expected behavior**
Expected something to show up.

**Desktop (please complete the following information):**
 - Desktop: GNOME 41
 - Display server type: Wayland

`fcitx5-diagnose >>`
<details>
# 系统信息:
1.  `uname -a`:

        Linux neubulae 5.15.2-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 12 Nov 2021 19:22:07 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	1.4
        Distributor ID:	Arch
        Description:	Arch Linux
        Release:	rolling
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	Arch Linux

4.  `/etc/lsb-release`:

        LSB_VERSION=1.4
        DISTRIB_ID=Arch
        DISTRIB_RELEASE=rolling
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux-logo

6.  桌面环境：

    桌面环境为 `gnome3`。

7.  Bash 版本：

        BASH_VERSION='5.1.8(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY='wayland-0'

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale：

    1.  全部可用 locale：

            C
            en_US.utf8
            POSIX
            zh_CN.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME="zh_CN.UTF-8"
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/neubulae

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/neubulae/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/neubulae/.config/fcitx5`)。

5.  当前用户：

    脚本作为 neubulae (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: `5.0.10`

3.  进程：

    找到了 1 个 fcitx5 进程：

           1036 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` 工作正常。

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.77`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `1036`。

    来自 dbus 的调试信息：

           Group [wayland:] has 7 InputContext(s)
          IC [618540553f934469bf8ce8b61df49117] program:gnome-terminal-server frontend:dbus cap:6001000012 focus:0
          IC [5b94cdcd70ec42bd9e9221e1f766290c] program:deadbeef frontend:dbus cap:6001000012 focus:0
          IC [80a7f04f611e43b683899fc38840d6f4] program:steam frontend:dbus cap:f0b3d23400000012 focus:0
          IC [e12b9016f5954df6ad2e6d8a948829f1] program:deadbeef frontend:dbus cap:6001000012 focus:0
          IC [b195ac0f19374f24bf525d3043ce0d60] program:org.gnome.Software frontend:dbus cap:6001000012 focus:0
          IC [1e8d5a80fead4eb5b17667d9cb93bbc2] program:steamwebhelper frontend:dbus cap:c9e6d64000000012 focus:0
          IC [13d3357c26544d349c77c14f8a745c96] program: frontend:ibus cap:52 focus:0
        Group [x11::0] has 12 InputContext(s)
          IC [552cfd60028c43d88c6084a518925aa8] program:yakuake frontend:dbus cap:6000800072 focus:0
          IC [6cdbae77eed843afbec19a9974dd124c] program:kotatogram-desktop frontend:fcitx4 cap:800072 focus:0
          IC [e5d0559b894e4e7b909212cd2ec267a2] program:electron frontend:dbus cap:6000000012 focus:0
          IC [db81ae89c19b4f29b29c0b7aff4fb79b] program:electron frontend:dbus cap:6000000012 focus:0
          IC [eb42c98e95cc492fb341f429992b8655] program:okular frontend:dbus cap:6000800072 focus:0
          IC [7ab8b5570c7d4194a68f1c5ea97b33a1] program:electron frontend:dbus cap:6000000012 focus:0
          IC [9e12cdb78eff4f0488767f8df717bb7d] program:firefox frontend:dbus cap:6000000012 focus:0
          IC [2366200eaf8f4ee38222c4e4040b29ae] program:firefox frontend:dbus cap:6000000052 focus:0
          IC [8924f73dde7048afb29d8f676dc7a3dd] program:yakuake frontend:dbus cap:6000800072 focus:1
          IC [42eeaa6d69d74970b99130c78387af73] program:firefox frontend:dbus cap:6000000012 focus:0
          IC [234622187daa406ead75485778cea8de] program:firefox frontend:dbus cap:6000000012 focus:0
          IC [29036c4e9e2d418ca2578a4ac17801c5] program:firefox frontend:dbus cap:6000000012 focus:0
        Input Context without group

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

# 前端设置：
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    Xim 服务的名称与环境变量中设置的相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

3.  Qt 输入法模块文件：

    找到了 fcitx5 的 qt 输入法模块：`/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了未知的 fcitx qt 模块：`/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`。
    找到了 fcitx5 qt5 模块：`/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    找到了 fcitx5 的 qt6 输入法模块：`/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

2.  `gtk-query-immodules`:

    1.  gtk 2:

        在 `/usr/bin/gtk-query-immodules-2.0` 找到了 gtk `2.24.33` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

        在 `/usr/bin/gtk-query-immodules-2.0-32` 找到了 gtk `2.24.33` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0-32 from gtk+-2.24.33

        **无法在 `/usr/bin/gtk-query-immodules-2.0-32` 的输出中找到 fcitx5。**

    2.  gtk 3:

        在 `/usr/bin/gtk-query-immodules-3.0` 找到了 gtk `3.24.30` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.30

        已找到 gtk `3.24.30` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

        在 `/usr/bin/gtk-query-immodules-3.0-32` 找到了 gtk `3.24.30` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0-32 from gtk+-3.24.30

        **无法在 `/usr/bin/gtk-query-immodules-3.0-32` 的输出中找到 fcitx5。**

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        在 `/usr/lib/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

        在 `/usr/lib32/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by usr/bin/gtk-query-immodules-2.0-32 from gtk+-2.24.33

        **无法输入法模块缓存 `/usr/lib32/gtk-2.0/2.10.0/immodules.cache` 中找到 fcitx5**

    2.  gtk 3:

        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.30` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.30

        已找到 gtk `3.24.30` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

        在 `/usr/lib32/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.30` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0-32 from gtk+-3.24.30

        **无法输入法模块缓存 `/usr/lib32/gtk-3.0/3.0.0/immodules.cache` 中找到 fcitx5**

    3.  gtk 4:

        在 `/usr/lib/gtk-4.0/4.0.0/immodules/giomodule.cache` 找到了 gtk `4` 的输入法模块缓存。
        已找到 gtk `4` 的 fcitx5 输入法模块。

            libim-fcitx5.so: gtk-im-module

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 20 个已启用的插件：

            Classic User Inteface 5.0.10
            Clipboard 5.0.10
            DBus 5.0.10
            DBus Frontend 5.0.10
            Emoji 5.0.10
            Fcitx4 Frontend 5.0.10
            IBus Frontend 5.0.10
            Input method selector 5.0.10
            Keyboard 5.0.10
            KDE Input Method Panel 5.0.10
            Status Notifier 5.0.10
            Notification 5.0.10
            Quick Phrase 5.0.10
            Rime 5.0.7
            Spell 5.0.10
            Unicode 5.0.10
            Wayland 5.0.10
            Wayland Input method frontend 5.0.10
            XCB 5.0.10
            X Input Method Frontend 5.0.10

    2.  找到了 0 个被禁用的插件：

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 2 个已启用的用户界面插件：

        Classic User Inteface
        KDE Input Method Panel

    Kimpanel 进程:

            742 /usr/bin/gnome-shell

## 输入法：
1.  `/home/neubulae/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=默认
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=rime

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=rime
        # Layout
        Layout=

        [GroupOrder]
        0=默认

# 日志：
1.  `date`:

        2021年 11月 13日 星期六 18:37:58 CST

2.  `/home/neubulae/.config/fcitx5/crash.log`:

    `/crash.log` 未找到.

**警告：fcitx5-diagnose 的输出可能包含敏感信息，包括发行版名称，内核版本，正在运行的程序名称等。**

**尽管这些信息对于开发者诊断问题有帮助，请在公开发送到在线网站前检查并且根据需要移除的对应信息。**

</details>

**Additional context**
Probably related issues:
https://bugs.chromium.org/p/chromium/issues/detail?id=1183262
https://bugs.chromium.org/p/chromium/issues/detail?id=1265118

**Comment by wengxt** [comment]
--gtk_version=4 + version 98.

Also you'll need to use https://extensions.gnome.org/extension/261/kimpanel/. 
That's the only working combination. Close since it's not fcitx bug.

**Comment by Neubulae** [comment]
I was using kimpanel but I never tested with Chrome 98, would you pin this issue for visibility as a lot of people doesn't seem to know the problem?

**Comment by Neubulae** [comment]
Tested with Chrome 98, still didn't work :thinking:
