### ISSUE TITLE
输入法输入框在一个特定的情况下自动关闭

### ISSUE THREAD

**Issue by YinAqu** [fcitx/fcitx5#383]
**Describe the bug**
网页版飞书 使用fcitx5在飞书消息输入框中输入文字的同时,有飞书的新消息提醒(chromium的弹出消息提醒),输入法输入框会自动关闭,输入的文字会变得混乱,不切换到其他网页,在此网页切换输入法仍会持续出现这个问题.

**To Reproduce**
1. 打开chromium
2. 打开飞书网页版
3. 允许飞书在chromium中的notification
3. 点击飞书任意联系人
4. 光标焦点聚焦联系人消息输入框
5. 在消息输入框中输入消息的同时,收到飞书的新消息

**Expected behavior**
能正常输入文字

**Desktop (please complete the following information):**
 - Desktop: Archlinux5.15.2
 - Display server type: X11, dwm
 

**Additional context**
推测不仅是飞书, 浏览器的消息弹窗都会导致该问题

**Comment by wengxt** [comment]
在kwin x11 测试了一下，好像没有问题？
https://user-images.githubusercontent.com/259684/141889073-b4644cbe-5506-471e-b843-8b5cae191708.mp4

**Comment by wengxt** [comment]
基本上我认为可能的原因是 dwm 处理窗口焦点有问题
另外我不明白你说的「变得混乱」是什么意思
