### ISSUE TITLE
关机时间很长， 查看日志好像是fcitx5造成的

### ISSUE THREAD

**Issue by epubreader** [fcitx/fcitx5#385]
11月 17 11:12:35 mason systemd[653]: Stopped GNOME keyboard configuration service.
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908149 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908164 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908179 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908194 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908208 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908223 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908237 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908250 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908264 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908278 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908292 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908306 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908320 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908334 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908349 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908363 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908376 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908391 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908405 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908420 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908434 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908449 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.908463 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason udisksd[941]: udisks daemon version 2.9.4 exiting
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909461 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909482 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909496 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909510 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909524 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909538 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909552 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909566 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909581 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909595 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909608 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909622 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909637 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909652 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909667 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909681 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909695 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909710 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909724 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909740 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909754 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909769 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909783 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909797 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909812 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909828 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909842 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909857 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909872 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909889 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909904 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909918 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909933 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909948 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909966 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.909986 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910001 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910018 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910032 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910047 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910072 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910088 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910103 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910118 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910134 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910149 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910163 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910178 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910583 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910602 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910618 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910634 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910650 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910666 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910681 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910697 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910711 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910726 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910740 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910753 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910767 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910781 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910795 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910809 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910825 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910838 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910853 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910867 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910882 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910895 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910909 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910925 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910940 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910953 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910971 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.910985 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911000 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911013 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911028 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911042 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911056 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911069 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911085 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911100 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911114 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911127 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911141 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911156 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911170 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911183 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911200 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911214 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911230 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911244 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911260 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911274 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911288 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911302 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911316 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911329 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911343 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911356 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911370 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911384 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911398 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911413 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911426 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911440 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911456 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911508 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911523 xcbeventreader.cpp:34] XCB connection ":0" got error: I2021-11-17 11:12:35.911547 addonmanager.cpp:2951
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: W2021-11-17 11:12:35.911568 xcbeventreader.cpp:34] XCB connection ":0" got error: 1
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: ] Unloading addon W2021-11-17 11:12:35.911601 xcbeventreader.cpppinyin
11月 17 11:12:35 mason org.fcitx.Fcitx5.desktop[1133]: :34] XCB connection ":0" got error:

**Comment by wengxt** [comment]
@epubreader 你好，我想了解一下你具体使用的版本，因为我阅读这段代码的话理解上应该不会出现这种情况…包括发行版是什么

**Comment by wengxt** [comment]
请问你能尝试一下 -git 的版本看看是否解决了你的问题吗？如果还有类似问题再 reopen
