### ISSUE TITLE
Bad icon on light themed Panel

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5#388]
The current icon for English method looks broken on light theme such as Breeze light:
![image](https://user-images.githubusercontent.com/11857205/142964653-ed864226-36a8-4697-a933-2c95f2f14cd9.png)

**Comment by wengxt** [comment]
That really depends on your font i think.. what's your font? Also the color is customizable.

**Comment by trmdi** [comment]
> That really depends on your font i think.. what's your font? Also the color is customizable.

I use the default font set by Plasma: Noto Sans.
Yeah, I know it is customizable, but the setting is a bit too hidden, hard to discover, maybe the default should be something else better. For example, use the same font and color set by the theme ?

**Comment by wengxt** [comment]
It's hard for fcitx to know what color is being used by the system. The only thing that I can think of is to use black and white so it's more generic to theme.

**Comment by trmdi** [comment]
I remember in fcitx4, the icon for unikey can set by the Plasma theme. Is it applied to other input method such as English?

**Comment by wengxt** [comment]
As for that it's only apply to kimpanel. SNI doesn't have such a feature, only pixmap.

If you're talking about icon theme, breeze does have some fcitx icons, but doesn't ever have a unikey icon.

**Comment by trmdi** [comment]
**How do I tell fcitx that I prefer pixmap icon to the text one? Uncheck that option but it still prefer the text icon.**
![image](https://user-images.githubusercontent.com/11857205/143172949-974b1fa0-7b56-446b-8aa7-03cf4c2169f1.png)

**I think when that option is unchecked, fcitx should always use the pixmap one, including the case when the icon is `input-keyboard`.**



**And when the user choose it, it should always use the text icon, not like this:**

![image](https://user-images.githubusercontent.com/11857205/143173279-426baeb7-4e42-42e7-a307-24e4f483c21d.png)

**Comment by trmdi** [comment]
> If you're talking about icon theme, breeze does have some fcitx icons, but doesn't ever have a unikey icon.

It has. The icon is inside `/usr/share/plasma/desktoptheme/default/icons/fcitx.svgz` which is provided by `plasma-framework` on my system.

**Comment by wengxt** [comment]
The keyboard layout is using input-keyboard, which is bad at indiciating which layout is being used. keyboard layout is hardcoded to always prefer text icon.

**Comment by wengxt** [comment]
As for the svg you point to, I'd suggest you extract the icon and send a PR to breeze-icons to add them into the icon theme. Obviously SNI tray icon doesn't seems to support such svg file. Kimpanel does support such icon, you can use that plasmoid instead.

**Comment by trmdi** [comment]
> Obviously SNI tray icon doesn't seems to support such svg file. 

It does support when you're using Plasma. See my screenshot, that is SNI tray icon, not KIM Panel.

**Comment by trmdi** [comment]
> The keyboard layout is using input-keyboard, which is bad at indiciating which layout is being used. keyboard layout is hardcoded to always prefer text icon.

What about the usecase when the user only use one layout for English and Unikey (me as example) ?
That indicator is still very good.

I mean that Prefer option should work like this:
- Check: use text icon
- Uncheck: use pixmap icon
