### ISSUE TITLE
Raspberry pi 4B display error

### ISSUE THREAD

**Issue by pumpkin-nbc** [fcitx/fcitx5#391]
![image](https://user-images.githubusercontent.com/58675642/143678075-9cc62823-0d58-4ec2-806a-6b1151c87a78.png)

As shown in the figure, this happens every time you start up, and you must restart
Restarting will make xrdp unusable

**Comment by wengxt** [comment]
The icon in this picture indicates it's fcitx4 not fcitx5 . This is fcitx 5 issue list.
