### ISSUE TITLE
输入一码回车时不能编码上屏

### ISSUE THREAD

**Issue by yueduz** [fcitx/fcitx5#404]
我启用了回车编码上屏。当我在chrome地址栏中输入文字时，输入一码回车时不能编码上屏，会直接发起搜索。输入一码以上回车能编码上屏

 - Desktop: Gnome archlinux
 - Display server type: X11
 - fcitx -v :5.0.10

**Comment by wengxt** [comment]
哪个输入法？怎么启用的

**Comment by yueduz** [comment]
在程序显示预编辑文本不打开会出现这种情况，启用了就不会。rime和libime都会，libime好像是默认的回车编码上屏

**Comment by wengxt** [comment]
测试了一下，应该是 chrome 的 bug https://bugs.chromium.org/p/chromium/issues/detail?id=1278989
