### ISSUE TITLE
Fcitx5在Vivaldi浏览器的侧边Web Tab中的预输入被打断

### ISSUE THREAD

**Issue by SergeFan** [fcitx/fcitx5#407]
**Fcitx5在Vivaldi浏览器的侧边Web Tab中的预输入被打断**
Fcitx5在Vivaldi浏览器的侧边Web Tab中无法输入中文或者是日语，所有输入都被切断成单个字母并被强行转换。

**问题网页**
主要发生在Google翻译界面，暂时还未在其他网页上确认到类似问题
1. 在Vivaldi浏览器的侧边Web Tab中加入Google翻译的网址
2. 打开Google翻译的侧边Tab
3. 使用输入法输入中文或日语

**桌面环境**
 - 桌面：KDE Plasma 5.23, X11

**效果截图**
![image](https://user-images.githubusercontent.com/63533445/145801313-2b482973-1aea-4bf3-9df1-fb9b07e8b045.png)
如图所示，预输入“nihao”全部被打断成单个字母被转换。并且光标被固定在先头位置，转换出来的文字都是倒序。

**Comment by wengxt** [comment]
看起来是没用 im module的原因，建议检查环境变量 GTK_IM_MODULE=fcitx，以及 fcitx5-gtk 已经安装

**Comment by SergeFan** [comment]
按照Arch wiki在/etc/environment中设置了GTK_IM_MODULE=fcitx，并且确定已经安装了 fcitx5-gtk ，问题依然存在。且该问题目前只存在于Google翻译页面，不确定原因源自Fcitx还是Vivaldi，所以也向Vivaldi方面反映过，不过没有得到答复。

**Comment by wengxt** [comment]
有些时候浏览器和预编辑配合的不好，如果你不能在不同内核的浏览器（如firefox）中重现，那就是浏览器的问题。

我测试了一下，vivaldi 在输入的时候会一直发送失去焦点导致fcitx重置状态，非侧边没有这个问题，那肯定是 vivaldi 自己的问题了，你可以 ctrl + alt + p 临时禁用fcitx预编辑来workaround一下。
