### ISSUE TITLE
can not run in manjaro

### ISSUE THREAD

**Issue by pincman** [fcitx/fcitx5#411]
**Describe the bug**
install 
```sh
yay -S fcitx5 fcitx5-qt fcitx5-gtk fcitx5-configtool
yay -S fcitx5-rime
```
reboot system

**To Reproduce**
click fcitx app

**Expected behavior**
can not run and config tools show me "dbus can not connect fcitx"

**Desktop (please complete the following information):**
 - Desktop: (manjaro kde

**Additional context**

**Comment by wengxt** [comment]
can you post the output of fcitx5-diagnose ?

**Comment by wengxt** [comment]
I think your problem is that you didn't run fcitx5 at all.
