### ISSUE TITLE
Flatpak版本的Fcitx5最近在elementary OS 6系统上经常无法输入

### ISSUE THREAD

**Issue by loaden** [fcitx/fcitx5#414]
之前一切正常，但最近经常出现无法输入的情况，不但无法输入汉字，连英文也输入不了。Fcitx5托盘“重新启动“可以临时解决问题。

**Comment by wengxt** [comment]
flatpak安装的版本是？
不能输入的情况是一开始就无法输入还是正常使用一段时间后无法使用？

环境变量是？GTK_IM_MODULE

**Comment by loaden** [comment]
> flatpak安装的版本是？ 不能输入的情况是一开始就无法输入还是正常使用一段时间后无法使用？
> 
一开始就不能用。重启fcitx5可以输入英文，但无法输入中文。
> 环境变量是？GTK_IM_MODULE
ibus

**Comment by wengxt** [comment]
你的flatpak 版本，是装的 flathub 的，还是 fcitx unstable的？最近确实有一个 flatpak 变化导致 fcitx5 取代系统的 ibus 有一些问题，在这个地方修复的 https://github.com/fcitx/fcitx5/commit/8048f3b8436872ad9bab7ee57016a6e52932827f#diff-c43d8624d5d21c89bfa2c488a87a1510062f0a696098971b12f1b9ae7b685448

有几个方案你可以考虑一下，一个是安装 fcitx 的 im module （如果有 fcitx4 的，也可以），然后环境设置成 GTK_IM_MODULE=fcitx
另一个就是装 unstable 的，参考 https://fcitx-im.org/wiki/Install_Fcitx_5#Install_Fcitx_5_from_Flatpak

**Comment by loaden** [comment]
我安装了unstable，并且切换到了RIME输入法，现在一切正常。
感谢！！
