### ISSUE TITLE
[Feature request] Always use first input method after switching application

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/fcitx5#415]
Hello,
Is it possible to add the option to "Share Input State" ?

```
Always use first input method after switching application
```

Example:
$ mousepad
Press Ctrl+space. (Second input method)

$ xfce4-terminal
Press Ctrl+space. (Second input method)

Switch to mousepad. (First input method)
Switch to xfce4-terminal. (First input method)

I often forget the current input method,
so I want to use first input method after switching application.

**Comment by wengxt** [comment]
I don't want to add such an option for a random request, but it is possible to implement an addon with such functionality yourself.

The easiest way is to use fcitx5-lua. Create a .lua file and put it under ~/.local/share/fcitx5/lua/imeapi/extensions

```
local fcitx = require("fcitx")

fcitx.watchEvent(fcitx.EventType.FocusIn, "switch_input_method")

function switch_input_method()
    fcitx.setCurrentInputMethod("keyboard-us")
end
```

**Comment by wengxt** [comment]
Also as a alternative solution, fcitx5 has this option  "Show input method information when changing focus".
 
![图片](https://user-images.githubusercontent.com/259684/147025492-92795476-69d5-43aa-93be-dd5e173191ff.png)

You might want to enable it so you can always know what's the current input method when you switch application.

**Comment by QiangF** [comment]
The best is the default setting to remember input method state. However, for terminal such as xterm, I want the next focus in will have the english input set, also for firefox. Can you please add a window class check for this extension? ie. if the focus window is Xterm or firefox, set the input to english.

> The easiest way is to use fcitx5-lua. Create a .lua file and put it under ~/.local/share/fcitx5/lua/imeapi/extensions
> 
> ```
> local fcitx = require("fcitx")
> 
> fcitx.watchEvent(fcitx.EventType.FocusIn, "switch_input_method")
> 
> function switch_input_method()
>     fcitx.setCurrentInputMethod("keyboard-us")
> end
> ```

**Comment by wengxt** [comment]
https://fcitx.github.io/fcitx5-lua/modules/fcitx.html#currentProgram

**Comment by QiangF** [comment]
I can't ge this work for WM_CLASS st

    local fcitx = require("fcitx")

    fcitx.watchEvent(fcitx.EventType.FocusIn, "focus_event")

    local mylog = assert(io.open("/tmp/myfcitx.txt", "w+"))
    function focus_event()
        local cp = fcitx.currentProgram()
        mylog:write(string.format("%s\n", cp))

        if string.find(cp, "firefox") or string.find(cp, "Firefox") or string.find(cp, "St") or string.find(cp, "st") then
           fcitx.setCurrentInputMethod("keyboard-us")
        end

        -- io.popen(string.format("/usr/bin/notify-send '%s'", fcitx.currentProgram()))
        -- fcitx.setCurrentInputMethod("keyboard-us")
    end


Output of xprop for st term:

    q@mypc:~$ xprop
    _NET_WM_ICON_NAME(UTF8_STRING) = "q@mypc:/home/q"
    WM_ICON_NAME(UTF8_STRING) = "q@mypc:/home/q"
    _NET_WM_ICON_GEOMETRY(CARDINAL) = 100, 1080, 395, 20
    WM_STATE(WM_STATE):
                    window state: Normal
                    icon window: 0x0
    _NET_WM_DESKTOP(CARDINAL) = 0
    _NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _OB_WM_ACTION_UNDECORATE
    _KDE_NET_WM_FRAME_STRUT(CARDINAL) = 0, 0, 23, 0
    _NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 23, 0
    _NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
    _OB_APP_TYPE(UTF8_STRING) = "normal"
    _OB_APP_TITLE(UTF8_STRING) = "st"
    _OB_APP_GROUP_CLASS(UTF8_STRING) =
    _OB_APP_GROUP_NAME(UTF8_STRING) =
    _OB_APP_CLASS(UTF8_STRING) = "St"
    _OB_APP_NAME(UTF8_STRING) = "st"
    _OB_APP_ROLE(UTF8_STRING) =
    _NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "q@mypc:/home/q"
    _NET_WM_VISIBLE_NAME(UTF8_STRING) = "q@mypc:/home/q"
    WM_LOCALE_NAME(STRING) = "zh_CN.UTF-8"
    WM_CLASS(STRING) = "st", "St"
    WM_HINTS(WM_HINTS):
                    Client accepts input or input focus: True
    WM_NORMAL_HINTS(WM_SIZE_HINTS):
                    program specified size: 804 by 460
                    program specified minimum size: 14 by 23
                    program specified resize increment: 10 by 19
                    program specified base size: 4 by 4
    WM_CLIENT_MACHINE(STRING) = "mypc"
    _NET_WM_NAME(UTF8_STRING) = "q@mypc:/home/q"
    WM_NAME(UTF8_STRING) = "q@mypc:/home/q"
    _NET_WM_PID(CARDINAL) = 1216
    _NET_WM_ICON(CARDINAL) =        Icon (64 x 64):

**Comment by wengxt** [comment]
fcitx 读到的程序名参考  dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo

另外刚刚发现个bug，FocusIn 的 value 写反了……

修复了一下
https://github.com/fcitx/fcitx5-lua/commit/d8d2c3d2d3ce125d179d311d3d8f5fd14e217ceb

暂时你可以用那个 int 的 0x0001003 代替 FocusIn

**Comment by QiangF** [comment]
Thank you!
Turns out the program name for st is frontend:xim
To avoid name collision, better to use an external script:

    local fcitx = require("fcitx")
    
    fcitx.watchEvent(0x0001003, "focus_event")
    
    function focus_event()
        io.popen("focus_monitor.sh")
    end
    
    
focus_monitor.sh
    
    #!/usr/bin/bash
    
    active_window=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)
    wm_class=$(xprop -id ${active_window} WM_CLASS | sed -e 's/.*= "\([^"]*\)".*/\1/')
    
    wm_class_lower=${wm_class,,}
    
    if [ "$wm_class_lower" == 'firefox' ] || \
           [ "$wm_class_lower" == 'navigator' ] || \
           [ "$wm_class_lower" == 'firefox-esr' ] || \
           [ "$wm_class_lower" == 'st' ] ; then
        fcitx5-remote -c
    fi
