### ISSUE TITLE
Swap Input Method Shortcuts Flimsy on Latest KDE Versions

### ISSUE THREAD

**Issue by dginovker** [fcitx/fcitx5#418]
**Describe the bug**

After installing `kde-config-fcitx`, the global shortcut to swap keyboard layouts doesn't work until you re-enter a new shortcut for the first time.

**To Reproduce**
0. Install the latest [KDE Neon iso](https://neon.kde.org/download) in Gnome Boxes or other VM Manager
1. Install `kde-config-fcitx` on KDE Neon
2. Install `fcitx-hangul`
3. Reboot
4. Open Settings > Regional Settings > Input Method > Global Config
6. Observe at this time the shortcut is set to `ctrl + space`:

![image](https://user-images.githubusercontent.com/32943174/147366060-635afb05-d8e6-4444-8f12-2d741d772c72.png)

7. Go to a browser or something, type in English (default), hit `ctrl + space`
8. Observe the same US/default keyboard is selected as the input method for fcitx
9. Go back to the settings window, remove the `ctrl + space` Trigger Input Method

![image](https://user-images.githubusercontent.com/32943174/147366120-c8fc04f7-b51b-4b29-8169-49f6e6052c92.png)

10. Re-enter `ctrl + space` as the Trigger Input Method, hit Apply
11. Go back to browser, hit `ctrl + space`, observe Korean (hangul) is selected as the input method for fcitx

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: X11
 - Tested on both latest Unstable KDE Neon and Arch Linux
 - fcitx-5 diagnose: https://gist.github.com/dginovker/92856f31b4c4ed8af80a6e9093d92034

**Additional context**

KDE recently did a push to make locale easier. Perhaps they broke something?

Also much <3 for fcitx

**Comment by wengxt** [comment]
this repo is for fcitx 5. you’re using fcitx4.

**Comment by dginovker** [comment]
Confirmed works great on fcitx5
