### ISSUE TITLE
fcitx5 在使用较长时间后，会出现卡顿的现象

### ISSUE THREAD

**Issue by t123yh** [fcitx/fcitx5#42]
操作系统是 Manjaro Linux KDE，内核版本是 5.5。

卡顿的时候，可以在 htop 里面看到 fcitx5 进程的 CPU 占用率为 100%。

这个是否有办法调试？

**Comment by wengxt** [comment]
sysprof 一下看看时间花在哪

**Comment by t123yh** [comment]
之前用 kprof 打开过后直接卡得无法运行，我试一下 sysprof
