### ISSUE TITLE
Is there a way to disable preedit permanently?

### ISSUE THREAD

**Issue by wanghuibin0** [fcitx/fcitx5#421]
I know that preedit can be temporarily toggled off by hotkey ctrl-alt-p. I want to turn it off permanently. May I ask if there is a way to do that?

**Comment by wengxt** [comment]
Why would you want to do that?

**Comment by wanghuibin0** [comment]
> Why would you want to do that?

This relates to another issue that I have just opened, https://github.com/fcitx/fcitx5/issues/419#issue-1088622261. 

Someone advises me that I should turn off preedit, to reduce the possibility of the bypass described in that issue. I have tried the advice. It seems that turning of preedit is helpful, for I feel that the bypass occurs less frequently, if it is not my illusion. That's why this issue is opened. 

Surely, such a feature may be unnecessary if the previous bug is fixed.

**Comment by wengxt** [comment]
@wanghuibin0 So that would be really weird, because fcitx doesn’t use on the spot by default in xim, which means preedit should not be used in emacs at all, unless you changed an option in xim. Is that the case?

**Comment by wanghuibin0** [comment]
> @wanghuibin0 So that would be really weird, because fcitx doesn’t use on the spot by default in xim, which means preedit should not be used in emacs at all, unless you changed an option in xim. Is that the case?

Oh, I don't know that. I just followed someone's advice and pressed ctrl-alt-p in emacs. I thought I had closed preedit. After reading your comment, I realize I was wrong. The feeling that the bypass occurs less frequently is probably my illusion. 

The issue #419 is my real concern. 
Sorry to disturb you.
