### ISSUE TITLE
elementary OS 6 托盘图标丢失（ wingpanel-indicator-ayatana插件）

### ISSUE THREAD

**Issue by loaden** [fcitx/fcitx5#422]
部分Flatpak应用会导致这个插件无法正常显示图标：[https://github.com/Lafydev/wingpanel-indicator-ayatana/issues/26](https://github.com/Lafydev/wingpanel-indicator-ayatana/issues/26)
这个问题可能是插件的问题，但也可能是应用的问题。
Flatpak的Stable版本（Flathub）不存在这个问题。是今天切换到Unstable版本后发现的。

**Comment by loaden** [comment]
![2021-12-29 16-15-06 的屏幕截图](https://user-images.githubusercontent.com/490433/147643735-6e30b98d-f762-4e85-adbe-e677f87e1774.png)
抱歉，刚才主题忘了上传图片。补上。

**Comment by wengxt** [comment]
我在原始 bug 回复了一下，但是尽管有 IconPixmap 的问题，但是如果你没有配置超过两个以上的键盘布局的话应该还是会显示键盘图标的，你配置了超过两个键盘布局吗？我在 KDE 下测试没有发现图标问题

另外就是你的环境变量有没有包括 flaptak 的？
echo $XDG_DATA_DIRS 
/home/csslayer/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

**Comment by loaden** [comment]
> loaden@yuchen:~$ echo $XDG_DATA_DIRS
/usr/share/gnome:/usr/share/pantheon:/home/loaden/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

我只有一个默认的键盘布局。上面是我的XDG_DATA_DIRS环境变量输出。我尝试删除“分组2”，好像输入法图标就正常显示了。我再重启电脑试一下。

**Comment by loaden** [comment]
删除“分组2”之后，注销电脑重新登录，托盘图标也正常了。

**Comment by loaden** [comment]
> 删除“分组2”之后，注销电脑重新登录，托盘图标也正常了。所以，感觉很奇怪：为什么删除分组2会正常显示图标。

我明白了，原来分组2就是第二个键盘布局（汉语）。

**Comment by wengxt** [comment]
姑且也增加了一个选项强制使用键盘图标

**Comment by firstuanl** [comment]
好像也是这个问题引图无图标。
