### ISSUE TITLE
Vertical candidate box despite selection horizontal

### ISSUE THREAD

**Issue by gevhaz** [fcitx/fcitx5#423]
**Describe the bug**
I don't get a horizontal candidate list even when I specifically select that. This is when using fcitx5 with mocz. I know skk has a specific setting for horizontal list, but mocz doesn't seem to. So I use the setting in "Classic user interface".

**To Reproduce**
1. Open fcitx5-configtool
2. In `Addons` -> `Classic user interface` -> `settings wheel`, uncheck "Vertical Candidate List"
3. Save settings (and even restart computer or fcitx5)
4. Type something that yields multiple suggestions

**Expected behavior**
Horizontal candidate list

**Actual behavior**
Vertical candidate list

**Desktop (please complete the following information):**
 - Desktop: dwm
 - Display server type: X11

**Comment by wengxt** [comment]
This is actually by design, because it can only work properly with a vertical list.

The option in classic UI is only a hint. Input method may choose to ignore it.

**Comment by gevhaz** [comment]
Got it, thanks.

**Comment by wengxt** [comment]
Well, I could still add an option to mozc to make it horizontal. Just certain feature will be disabled (mainly the dictionary feature)

**Comment by gevhaz** [comment]
The option to do it would be nice :)


Dec 30, 2021, 00:58 by ***@***.***:
