### ISSUE TITLE
Theme not applied to Flatpak Qt apps under KDE Wayland

### ISSUE THREAD

**Issue by hexchain** [fcitx/fcitx5#432]
**To Reproduce**
1. Open a Flatpak app that uses Qt, runs in native Wayland, and has an input box under KDE wayland (e.g. org.telegram.desktop, com.notepadqq.Notepadqq)
2. Try to type

**Expected behavior**
The theme of the input panel for the flatpak app should be the same as for non-flatpak apps. However, it seems to always be the default theme.

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible: [fcitx5-diagnose.txt](https://github.com/fcitx/fcitx5/files/7876423/fcitx5-diagnose.txt)

Flatpak:
![ime-wayland-flatpak](https://user-images.githubusercontent.com/529520/149648078-ae1bb60c-1d0b-4695-8d5b-0b0cf9295a43.png)

Non-flatpak:
![ime-wayland-non-flatpak](https://user-images.githubusercontent.com/529520/149648080-5b9767aa-6d6d-4da9-9dcd-dbd63c9e5822.png)

**Comment by wengxt** [comment]
That’s expected. client side input panel need to read host /usr/share which is commonly not enabled.
