### ISSUE TITLE
剪贴板历史的安全性问题

### ISSUE THREAD

**Issue by mentha** [fcitx/fcitx5#434]
剪贴板历史记录不应该默认打开，至少打开前要提醒用户。

今天在一台用了一年多的xubuntu上按错键，意外发现有这个功能。

虽然剪贴板设计上不是太安全，但处理一些不太重要的敏感数据时还是挺常用的。比如测试用的密码和令牌之类，有的环境不支持文字拖放，复制粘贴应该是最方便的。这种场景下，一般是在结束后复制新的东西，覆盖清除敏感信息。但fcitx的剪贴板历史会在后台记录所有内容，fcitx4还会写入硬盘。这个功能在4和5里都是默认打开的，而且设置比较隐蔽，没仔细看过设置就会中招。

**Comment by wengxt** [comment]
KDE has klipper by default.
