### ISSUE TITLE
After autostarting, the icon looks buggy

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5#435]
When autostarting:
![image](https://user-images.githubusercontent.com/11857205/150051529-ff44dea1-39aa-4e51-aad6-bb3d7a10a463.png)

When you quit it and launch it from the App launcher
![image](https://user-images.githubusercontent.com/11857205/150051596-58003d47-59f0-434c-829c-15ecd02c89e0.png)

**Comment by wengxt** [comment]
I doubt it's a fcitx issue. All that fcitx send to tray is 'show me the "input-keyboard"' icon.

The icon in the first image is just a lower resolution input-keyboard icon.

**Comment by trmdi** [comment]
But this is still an unsolved issue. Can you keep it opened?

**Comment by wengxt** [comment]
No, why should I keep an "not us" issue open? Unless you root cause it to fcitx, there is no reason to keep it open.

**Comment by trmdi** [comment]
> No, why should I keep an "not us" issue open? Unless you root cause it to fcitx, there is no reason to keep it open.

This didn't happen with fcitx4, so maybe it has something to do with fcitx5?

**Comment by wengxt** [comment]
I can think of one possible reason that affect this, if the prefer symbolic code path is executed, can you provide the output of

strings /proc/`pidof fcitx5`/environ | grep XDG

before and after you restart the new fcitx5?

**Comment by wengxt** [comment]
```
dbus-monitor | grep -A 5 IconName
```

Also can you share the output for this command (switch input method to trigger some changes to it), it should contain things like 

```
--
         string "IconName"
         variant             string "fcitx-pinyin"
      )
```

**Comment by trmdi** [comment]
**Before start new fcitx:**

`$ strings /proc/`pidof fcitx5`/environ | grep XDG`

    XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session4
    XDG_SEAT=seat0
    XDG_SESSION_DESKTOP=KDE
    XDG_SESSION_TYPE=x11
    XDG_CURRENT_DESKTOP=KDE
    XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
    XDG_SESSION_CLASS=user
    XDG_VTNR=7
    XDG_SESSION_ID=5
    XDG_RUNTIME_DIR=/run/user/1000

`$ dbus-monitor | grep -A 5 IconName`

             string "AttentionIconName"
             variant             string ""
          )
          dict entry(
             string "AttentionIconPixmap"
             variant             array [
    --
             string "IconName"
             variant             string "fcitx-unikey"
          )
          dict entry(
             string "IconPixmap"
             variant             array [
    --
             string "OverlayIconName"
             variant             string ""
          )
          dict entry(
             string "OverlayIconPixmap"
             variant             array [
    --
             string "AttentionIconName"
             variant             string ""
          )
          dict entry(
             string "AttentionIconPixmap"
             variant             array [
    --
             string "IconName"
             variant             string "input-keyboard-symbolic"
          )
          dict entry(
             string "IconPixmap"
             variant             array [
    --
             string "OverlayIconName"
             variant             string ""
          )
          dict entry(
             string "OverlayIconPixmap"
             variant             array [

**After start new fcitx:**

`$ strings /proc/`pidof fcitx5`/environ | grep XDG`

    XDG_CONFIG_DIRS=/home/trmdi/.config/kdedefaults:/etc/xdg:/usr/etc/xdg
    XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session2
    XDG_SEAT=seat0
    XDG_SESSION_DESKTOP=KDE
    XDG_SESSION_TYPE=x11
    XDG_CURRENT_DESKTOP=KDE
    XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
    XDG_SESSION_CLASS=user
    XDG_VTNR=7
    XDG_SESSION_ID=3
    XDG_RUNTIME_DIR=/run/user/1000
    XDG_DATA_DIRS=/home/trmdi/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/share

`$ dbus-monitor | grep -A 5 IconName`

             string "AttentionIconName"
             variant             string ""
          )
          dict entry(
             string "AttentionIconPixmap"
             variant             array [
    --
             string "IconName"
             variant             string "fcitx-unikey"
          )
          dict entry(
             string "IconPixmap"
             variant             array [
    --
             string "OverlayIconName"
             variant             string ""
          )
          dict entry(
             string "OverlayIconPixmap"
             variant             array [
    --
             string "AttentionIconName"
             variant             string ""
          )
          dict entry(
             string "AttentionIconPixmap"
             variant             array [
    --
             string "IconName"
             variant             string "input-keyboard"
          )
          dict entry(
             string "IconPixmap"
             variant             array [
    --
             string "OverlayIconName"
             variant             string ""
          )
          dict entry(
             string "OverlayIconPixmap"
             variant             array [

**Comment by wengxt** [comment]
How did you start fcitx5? I would assume that desktop detection doesn't work properly.

I think you probably using some custom script?

Especially "XDG_SESSION_PATH" looks mismatch, are you checking the output in the same session or did you log out?

**Comment by wengxt** [comment]
Also, can you share the output of this command when the icon looks bad?
```
strings /proc/`pidof fcitx5`/environ | grep KDE
```

I'd expect to get a KDE_SESSION_VERSION=5.

**Comment by trmdi** [comment]
▶ strings /proc/`pidof fcitx5`/environ | grep KDE
XDG_SESSION_DESKTOP=KDE
XDG_CURRENT_DESKTOP=KDE

**Comment by wengxt** [comment]
That would be the reason, are you using XDG autostart? Here's what I have.

```
$ strings /proc/`pidof fcitx5`/environ | grep KDE
XDG_SESSION_DESKTOP=KDE
XDG_CURRENT_DESKTOP=KDE
KDE_FULL_SESSION=true
KDE_SESSION_VERSION=5
KDE_SESSION_UID=1000
KDE_APPLICATIONS_AS_SCOPE=1
```

**Comment by trmdi** [comment]
> How did you start fcitx5? I would assume that desktop detection doesn't work properly.
> 
> I think you probably using some custom script?
> 
> Especially "XDG_SESSION_PATH" looks mismatch, are you checking the output in the same session or did you log out?

Yes, they are tested in different session since I logout and login again and test again.
I don't have any auto start script, just the default setup by fcitx from the git source.

**Comment by trmdi** [comment]
Ok, the latest commit fixed it. Thank you!

**Comment by wengxt** [comment]
But the issue is not really solved, I don’t think your environment is expected. Especially missing KDE_* variable could be a problem to the process forked by fcitx.

Are you using systemd based xdg autostart? Can you share the systemctl output? I wonder if fcitx5 is started in some special way

**Comment by wengxt** [comment]
systemctl status

**Comment by trmdi** [comment]
**When autostart:**

    ● linux
        State: running
        Jobs: 0 queued
    Failed: 0 units
        Since: Wed 2022-01-19 09:10:06 +07; 1h 39min ago
    CGroup: /
            ├─user.slice
            │ └─user-1000.slice
            │   ├─session-9.scope
            │   │ ├─11957 /usr/libexec/sddm/sddm-helper --socket /tmp/sddm-auth26af54d5-eb4b-4953-81c9-b3e9085456ff --id 8 --start /usr/bin/startplasma-x11 --user trmdi
            │   │ ├─11958 /usr/bin/startplasma-x11
            │   │ ├─12034 /usr/bin/ssh-agent /usr/bin/gpg-agent --sh --daemon --keep-display /usr/libexec/xinit/xinitrc
            │   │ ├─12035 /usr/bin/gpg-agent --sh --daemon --keep-display /usr/libexec/xinit/xinitrc
            │   │ ├─12057 /usr/lib64/libexec/kf5/start_kdeinit
            │   │ ├─12058 kdeinit5: Running...
            │   │ ├─12059 /usr/lib64/libexec/kf5/klauncher --fd=9
            │   │ ├─12072 /usr/bin/kded5
            │   │ ├─12076 /usr/bin/kwin_x11
            │   │ ├─12089 /usr/bin/ksmserver
            │   │ ├─12094 /usr/bin/xsettingsd
            │   │ ├─12107 /usr/bin/kaccess
            │   │ ├─12110 /usr/lib64/libexec/polkit-kde-authentication-agent-1
            │   │ ├─12113 /usr/bin/plasmashell
            │   │ ├─12120 /usr/bin/xembedsniproxy
            │   │ ├─12122 /usr/lib64/libexec/org_kde_powerdevil
            │   │ ├─12131 /usr/bin/gmenudbusmenuproxy
            │   │ ├─12197 fcitx5 -d

**Comment by trmdi** [comment]
Ah, there are a file at `/usr/etc/X11/xim.d/fcitx ` which is installed by openSUSE. Maybe it is the culprit.

**Comment by wengxt** [comment]
Yeah, opensuse has its own way to start input method, which likely runs before KDE

**Comment by trmdi** [comment]
Here is that file, I'm not sure if is the caller.
https://build.opensuse.org/package/view_file/M17N/fcitx5/xim.d-fcitx5?expand=1

**Comment by trmdi** [comment]
Let me tag @marguerite because he is the maintainer of openSUSE's fcitx5 package.

**Comment by tiwai** [comment]
The script invokes manually only for unknown $WINDOWMANAGER value is set. This might need updates for catching up the recent development, I suppose.
Which value do you have in $WINDOWMANAGER environment variable?

**Comment by wengxt** [comment]
@tiwai I doubt if WINDOWMANAGER still used by anyone. On Archlinux, I don't have this variable at all.

XDG_CURRENT_DESKTOP is a much more standardized option:

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
$XDG_CURRENT_DESKTOP should have been set by the login manager, according to the value of the DesktopNames found in the session file. The entry in the session file has multiple values separated in the usual way: with a semicolon.

**Comment by trmdi** [comment]
> Which value do you have in $WINDOWMANAGER environment variable?

Here is mine:

    $ printenv WINDOWMANAGER
    /usr/bin/startplasma-x11

**Comment by wengxt** [comment]
@trmdi, thanks, actually I think WINDOWMANAGER is now an opensuse specific thing.

@tiwai, filed a bug on 
https://bugzilla.opensuse.org/show_bug.cgi?id=1194916

Looks like ibus script in opensuse was already updated to match *plasma*
