### ISSUE TITLE
my fcitx5 not work in jetbrains product

### ISSUE THREAD

**Issue by owarai** [fcitx/fcitx5#44]
my fcitx5 not work in jetbrains product, and I cannot figure its reason. 

Is there some clue you can provide to help me?

OS: archlinux
Installation: through archlinuxcn repo
Problem: works perfectly in other applications, but not in jetbrains products, like idea, goland, etc.

Thank you very much.

**Comment by St-kai** [comment]
vmoption
>-Dauto.disable.input.methods=false

**Comment by fei12358** [comment]
I already tried this solution from https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006740379-2019-3-Update-disabled-Fcitx-input-Ubuntu. 

Both add this line to {product}.vmoptions and  {product}64.vmoptions.

But it seems not work.

**Comment by wengxt** [comment]
which package? intellij-idea-community-edition works fine for me.

**Comment by wengxt** [comment]
I tried multiple package from arch/arch-cn repo, without problem (didn't do anything about vm option or so, it just work out of the box). 
Assume this is a configuration problem. read
https://fcitx-im.org/wiki/Install_and_Configure
https://wiki.archlinux.org/index.php/fcitx for more information.

**Comment by owarai** [comment]
sorry, I figured out what the reason is.

I don't follow the convention strictly to add my input method config to `~/.xprofile` based on my `XDG_SESSION_TYPE`=x11 but add it to `~/.pam_environment` previously. 

I moved these config to `~/.xprofie` and it works.
