### ISSUE TITLE
Fcitx5 can't work in steam and dota2

### ISSUE THREAD

**Issue by cathaysia** [fcitx/fcitx5#442]
Enverment:
SDL_IM_MODULE=fcitx
fedora 35

As the title said, fcitx5 can't work in steam and dota2, I search this question and find it seems this bug come from SDL2, so I open a issue: https://github.com/libsdl-org/SDL/issues/5124

Recently, a archlinux developer contact me for solve this bug. I used the system's libSDL2-2.0.so.0 instead of the ones that came with Steam. But it can't work still.

Then the friend point this maybe cause by fedora's packager, so he send me a binary and I use it do a test. But it still can not work.

So I am here to ask help of you. Did you have some suggestions about this?

**Comment by wengxt** [comment]
nothing work in steam, except big picture mode.
![图片](https://user-images.githubusercontent.com/259684/151688666-78599050-28d0-406b-8119-fb915e51f002.png)

as for dota2, it works here, though pop up position may not be correct.
![图片](https://user-images.githubusercontent.com/259684/151688490-b8ec399c-58a8-4cf9-bc7e-c6b97bf03fc2.png)
![图片](https://user-images.githubusercontent.com/259684/151688540-98dd733c-8b6a-42ae-86ff-a8772f517835.png)

**Comment by wengxt** [comment]
There was a bug in SDL2 that may prevent it from working properly (though the bug was originally introduced by me unfortunately)  I fixed recently in SDL https://github.com/libsdl-org/SDL/pull/5056/commits/6e0db3159dcc9c55d8ed023a2fe62e80c607ca98

Also, I'm also aware that steam may not have up to date SDL, so I also tried to workaround the SDL bug in fcitx 5. https://github.com/fcitx/fcitx5/commit/1e7cf7e7c508d75e17966bd869ff50dcffa40852
As long as you're using fcitx 5.0.11+, you should be good.

**Comment by cathaysia** [comment]
I' using fcitx5 5.0.12, and I retest this. It works surely. But not so perfect. That means when I get into dota2, then press Ctrl+Shift, I can't using fcitx5 still, then I need switch to other program (such krunner), and switch to Chinese input method, then switch dota2.

One solution for me is using Ctrl + Space to enable fcitx5. But I don't know why I can't use Ctrl + Shift, which can work in other program.

**Comment by cathaysia** [comment]
I' using fcitx5 5.0.12, and I retest this. It works surely. But not so perfect. That means when I get into dota2, then press Ctrl+Shift, I can't using fcitx5 still, then I need switch to other program (such krunner), and switch to Chinese input method, then switch dota2.

One solution for me is using Ctrl + Space to enable fcitx5. But I don't know why I can't use Ctrl + Shift, which can work in other program.

**Comment by wengxt** [comment]
The issue is that SDL doesn't send key release event to input method. Pure modifier hotkey like Ctrl+Shift require key release event to work.

**Comment by wengxt** [comment]
I wrote a PR for SDL to fix it: https://github.com/libsdl-org/SDL/pull/5281 .

**Comment by asukaminato0721** [comment]
now it works

```bash
XMODIFIERS=@im=fcitx LANG=zh_CN.UTF-8 steam
```

ref <https://github.com/ValveSoftware/steam-for-linux/issues/3255#issuecomment-2565050431>

![Image](https://github.com/user-attachments/assets/927877cd-64a5-4fcd-833d-80b230f394ba)
