### ISSUE TITLE
Qt Creator 6 无法使用 fcitx5(QT creator 6 cannot use fcitx5)

### ISSUE THREAD

**Issue by Six-6Chen** [fcitx/fcitx5#444]
fcitx5的(libfcitxplatforminputcontextplugin.so)库在我的QT creator 6中无法使用

**Comment by Six-6Chen** [comment]
The (libfcitxplatforminputcontextplugin. So) library of fcitx5 cannot be used in my QT creator 6

**Comment by wengxt** [comment]
你有两种选择，一个是安装发行版自己构建的qt creator，这样可以用发行版的qt6（当然你还得装qt6的im module）

另一种是你QT_IM_MODULE=ibus 来启动qtcreator让它通过qt自带的ibus im module来用fcitx5
