### ISSUE TITLE
space is inserted at front of preedit string while committed by input method

### ISSUE THREAD

**Issue by ganadist** [fcitx/fcitx5#445]
## Steps to reproduce

 1. Run gtk4-demo
 2. Find text entry
 3. Enter shift+space to switch hangul mode
 4. type `gksrmf` (`한글`)
 5. type ` `(space)

## Current behavior

  * screenshot of reproducing step 4  
    ![image](https://gitlab.gnome.org/GNOME/gtk/uploads/9d312d228b2c25ae18ae304b409e43b2/image.png)
  * screenshot of reproducing step 5  
    ![image](https://gitlab.gnome.org/GNOME/gtk/uploads/d3c82be38b00a5ab5bc8170ea944182d/image.png)
  * composited string is  `한 글` (space is inserted at front of preedit string while committed)
## Expected outcome

  * Same behavior with gtk3
  * screenshot of reproducing step 4  
    ![image](https://gitlab.gnome.org/GNOME/gtk/uploads/0244f401a570f925ebe8ded81c09816f/image.png)
  * screenshot of reproducing step 5  
    ![image](https://gitlab.gnome.org/GNOME/gtk/uploads/10c3f7ed9d4a3500e1f8b95618614a7a/image.png)
  * composited string should be `한글 ` (space should inserted after committed)
## Version information
GTK+ : [4.6.0  (4.6.0-3)](https://archlinux.org/packages/extra/x86_64/gtk4/)  
OS : Archlinux  
  
## Additional information

 * gnome-shell 41.3 (wayland session)
 * fcitx: 5.0.13-1
 * fcitx-gtk : 5.0.11-1, 5.0.12
 * fcitx5-hangul : 5.0.6-1
 * gtk3: 3.24.31-1
 * X-posted : https://gitlab.gnome.org/GNOME/gtk/-/issues/4679

**Comment by wengxt** [comment]
Can you verify if fcitx5-gtk + fcitx5 last git version fix this?

**Comment by ganadist** [comment]
Tested with 
 https://github.com/fcitx/fcitx5/commit/b83372a6589566e37cef93a7e889dd9ed639e7b3 + https://github.com/fcitx/fcitx5-gtk/commit/a1ebe6f97dc1a33d5ac2794554dd31d49e889f13

It works well on gtk4-demo and google chrome 98 (with argument `--ozone-platform-hint=auto --gtk-version=4` to enable ozone wayland + gtk4 )

Thank you very much.

**Comment by wildwestrom** [comment]
Sorry to open an old issue, but I am having the same exact issue.

```
Distro: Arch
Kernel: 5.18.16-arch1-1
fcitx5: 5.0.18
fcitx5-hangul: 5.0.10-1
```

**Comment by wengxt** [comment]
@wildwestrom which application are you having the issue with? can you provide the output of fcitx5-diagnose?

Also it's always better to open a new issue instead reusing an old report. Please open new issue next time.
