### ISSUE TITLE
Tray Icon of Fcitx5 has no texts with Pango-CRITICAL error

### ISSUE THREAD

**Issue by noisnemid** [fcitx/fcitx5#446]
**Describe the bug**
Right Menu of the tray icon of Fcitx5 has not any characters, and CLI gave erros:
```
(process:7469): Pango-CRITICAL **: 23:33:50.052: pango_font_description_set_absolute_size: assertion 'size >= 0' failed
```

**To Reproduce**
1. Archlinux, new installed;
2. sudo pacman -Syu
3. sudo pacman -S fcitx5-im fcitx-rime trayer stalonetray
4. install dwm and config it
5. startx
6. fcitx5 -dr & trayer& (or stalonetray &)
7. right click on the trayicon of Fcitx5

**Expected behavior**
The menu shows and display fight

**Desktop (please complete the following information):**
 - Desktop: Archlinux,DWM
 - Display server type: X11
 - The output of fcitx5-diagnose if possible.

**Additional context**

![1](https://user-images.githubusercontent.com/16525011/152688404-7ea747d8-2653-4ff1-a914-937198e2ad5e.png)
![2](https://user-images.githubusercontent.com/16525011/152688407-bab828f0-b1cb-466f-8fa7-48a64083b2d1.png)

**Comment by wengxt** [comment]
Do you have a file: ~/.config/fcitx5/conf/classicui.conf ?

If so, what's its content?

**Comment by noisnemid** [comment]
> Do you have a file: ~/.config/fcitx5/conf/classicui.conf ?
> If so, what's its content?

I found that that file does not exist.
So I ran ``fcitx5-config-qt`` and modify some parameter of the classic ui addon, and that file appeared.
```

```
then I ran ``fcitx5 -dr`` , it's still not ok.
I'm going to re-install the OS later (maybe tonight, I think it might be the problem of archlinux itself.), and try again whether there's still this issue.

**Comment by noisnemid** [comment]
I re-installed the Archlinux and it's normal now.
Don't know why.
Maybe some packages' installation or remove caused this.

**Comment by noisnemid** [comment]
> If you ask me, I'd guess it's either related to font, or your locale didn't setup correctly.
I think so too!
Because even the second time I install Arch Linux, fcitx5-rime got font issues!
This small problem was solved when I changed/setup the font from ``sans 10`` to ``noto sans 10`` in ``classicui.conf``.
:lol:

**Comment by aowon** [comment]
I have the same problem, and I changed the `classicui.conf` as above, there's still this problem. 
```
# Vertical Candidate List
Vertical Candidate List=True
# Use Per Screen DPI
PerScreenDPI=True
# Use mouse wheel to go to prev or next page
WheelForPaging=True
# Font
Font="Noto Sans 10"
# Menu Font
MenuFont="Noto Sans 10"
# Tray Font
TrayFont="Noto Sans 10"
# Tray Label Outline Color
TrayOutlineColor=#00aaff
# Tray Label Text Color
TrayTextColor=#000000
# Prefer Text Icon
PreferTextIcon=False
# Show Layout Name In Icon
ShowLayoutNameInIcon=True
# Use input method language to display text
UseInputMethodLangaugeToDisplayText=True
# Theme
Theme=Nord-Dark
```
I use ArchLinux and the AwesomeWm, this is my `/etc/locate.conf` file:
```
LANG=en_US.UTF-8
```
