### ISSUE TITLE
Boshiamy outputs Simplified Chinese characters

### ISSUE THREAD

**Issue by johnliu55tw** [fcitx/fcitx5#448]
**Describe the bug**
I just upgraded from fcitx4 to fcitx5 on openSUSE Tumbleweed, and the Boshiamy IM now outputs Simplified Chinese characters. I can see those Traditional Chinese characters in the selection list, but Simplified Chinese character has the top priority.

I tried switching the Tradition/Simplified mode (`Ctrl-Shift-F`), but that doesn't affect anything.

I tested on Chewing IM and it output Traditional Chinese characters by default.

**To Reproduce**

https://user-images.githubusercontent.com/5047724/153744741-b7e7d6c6-5206-467b-83cb-7f61e4f1bb50.mp4

**Expected behavior**
Boshiamy should output Traditional Chinese characters by default, or there should be a way to switch between Traditional/Simplified Chinese characters.

**Desktop (please complete the following information):**
 - Desktop: Sway
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible: I can provide if it's necessary

**Additional context**

**Comment by wengxt** [comment]
I don't think it's table's problem.

For example, "caur" only has 
```
caur 輸
caur 蝓
caurv 蝓
```
It's not possible for boshiamy to produce "输" for caur without using the chttrans module.

Can you double check the state of simp/trad mode? (From system tray) In fcitx5 it's slightly different, this state is 'per input method'. So you can have different simp/trad mode for boshiamy, cangjie or chewing.

**Comment by johnliu55tw** [comment]
I had installed fcitx5 on another Tumbleweed system and boshiamy outputs Trad. Chinese characters just fine. Could be some configuration error in my current Tumbleweed... Thanks for clarifying it's not the table's problem btw.

**Comment by wengxt** [comment]
I'll close this for now, because i think there's no bug. But you can still reply if you need help figure out what configuration you need to change.

Can you check ~/.config/fcitx5/conf/chttrans.conf ?

Especially this line "EnabledIM" part.
