### ISSUE TITLE
Please add wubi or wubipy table.

### ISSUE THREAD

**Issue by alvin998179** [fcitx/fcitx5#45]
Could you please add wubi or wubipy table or  tell me how to transform it from fcitx4 wubi or wubipy table?  Thanks.

**Comment by wengxt** [comment]
it’s all in in fcitx5-chinese-addon.

**Comment by alvin998179** [comment]
But I do not know how to configure, could you please tell me?

**Comment by alvin998179** [comment]
And how to make it work in alacritty ? I found it can not use in alacritty with sway wm , arch linux.

**Comment by wengxt** [comment]
install kcm-fcitx5 for gui.

don’t ask question on github issue.

mail list irc, telegram are more appropriate place for such question .

**Comment by alvin998179** [comment]
Thank you!
