### ISSUE TITLE
linuxmint cinnamon 上使用 flatpak fcitx5 ，任务栏右键输入法图标大小不一致。

### ISSUE THREAD

**Issue by xingwozhonghua** [fcitx/fcitx5#451]
**Describe the bug**
If the problem is about you can not use fcitx in certain application, or the input window is placed in wrong place, be sure to include which application is being typed, and the output of fcitx5-diagnose command.

**To Reproduce**

选择 linuxmint cinnamon 进行安装。
安装系统后使用 flatpak 安装 fcitx5 输入法。

目前发现三个问题，应该是和 cinnamon 环境有关系，记录一下。

1. 右键任务栏菜单图标大小不一致。
2. 当前桌面环境下附加组件条目显示不完整。（因为字体文件不一样，所以显示效果不一样，建议可不可以一起讨论下，设计一套新的条目显示方式。）
3. flatpak无法使用 fcitx5-diagnose 
4. 输入法配置列表更新，点击应用之后右键菜单列表不更新

![2022-02-16_13-51](https://user-images.githubusercontent.com/18661883/154205225-ba29c8eb-e1bf-4a4c-a985-9cc86dd94fbc.png)

![image](https://user-images.githubusercontent.com/18661883/154205742-7849a87a-0f79-4047-9829-7ab7b436263c.png)

**Expected behavior**

**Desktop (please complete the following information):**

# System Info:
1.  `uname -a`:

        Linux uos-virtual-machine 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Linuxmint
        Description:	Linux Mint 20.3
        Release:	20.3
        Codename:	una

3.  `lsb_release -d`:

        Description:	Linux Mint 20.3

4.  `/etc/lsb-release`:

        DISTRIB_ID=LinuxMint
        DISTRIB_RELEASE=20.3
        DISTRIB_CODENAME=una
        DISTRIB_DESCRIPTION="Linux Mint 20.3 Una"

5.  `/etc/os-release`:

        NAME="Linux Mint"
        VERSION="20.3 (Una)"
        ID=linuxmint
        ID_LIKE=ubuntu
        PRETTY_NAME="Linux Mint 20.3"
        VERSION_ID="20.3"
        HOME_URL="https://www.linuxmint.com/"
        SUPPORT_URL="https://forums.linuxmint.com/"
        BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
        PRIVACY_POLICY_URL="https://www.linuxmint.com/"
        VERSION_CODENAME=una
        UBUNTU_CODENAME=focal

6.  Desktop Environment:

    Desktop environment is `cinnamon`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.0.17(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+inet(evdev)+group(win_space_toggle)+terminate(ctrl_alt_bksp)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn", "", "grp:win_space_toggle,terminate:ctrl_alt_bksp"

3.  Locale:

    1.  All locales:

            C
            C.UTF-8
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IL
            en_IL.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            POSIX
            zh_CN.utf8

    2.  Current locale:

            LANG=zh_CN.UTF-8
            LANGUAGE=zh_CN:zh
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME="zh_CN.UTF-8"
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/uos

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/uos/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/uos/.config/fcitx5`).

5.  Current user:

    The script is run as uos (1000).

# Fcitx State:
1.  executable:

    **Cannot find fcitx5 executable!**
    **Please check [Beginner's Guide](http://fcitx-im.org/wiki/Beginner%27s_Guide) for how to install fcitx5.**

**Additional context**

**Comment by wengxt** [comment]
这托盘自己的问题吧……它不懂缩放图标我有啥办法…

虽然倒是可以提供几个简易的hack就是我把小图标都安装一份

**Comment by chenshijie-uos** [comment]
> 这托盘自己的问题吧……它不懂缩

> 这托盘自己的问题吧……它不懂缩放图标我有啥办法…
> 
> 虽然倒是可以提供几个简易的hack就是我把小图标都安装一份

嗯嗯，确认是桌面环境托盘的问题，那还是应该cinnamon的托盘模块改。个人感觉没必要修改fcitx的图标。

**Comment by wengxt** [comment]
加几个文件倒是不费事，指望 cinnamon 改不知道得猴年马月，另外反正图标也不好看，随便缩放一下就得了

**Comment by xingwozhonghua** [comment]
cinnamon还有三个点，有点小问题：

1. 当前桌面环境下附加组件条目显示不完整。（因为字体文件不一样，所以显示效果不一样，建议可不可以一起讨论下，设计一套新的条目显示方式。）

![](https://user-images.githubusercontent.com/18661883/154205225-ba29c8eb-e1bf-4a4c-a985-9cc86dd94fbc.png)

2. flatpak无法使用 fcitx5-diagnose

3. 输入法配置列表更新，点击应用之后右键菜单列表不更新，看下图的配置界面和右键菜单。

![](https://user-images.githubusercontent.com/18661883/154205742-7849a87a-0f79-4047-9829-7ab7b436263c.png)

**Comment by wengxt** [comment]
2 基本上不能算个问题吧…… flatpak 哪还能额外装个命令的

3 就是 #460 ，应该一起修复了，libdbusmenu-gtk bug真多……
