### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by condy0919** [fcitx/fcitx5#456]
https://github.com/fcitx/fcitx5/blob/31bdbdfb9910d445a50eb76246125fbf6df48d44/src/lib/fcitx/globalconfig.cpp#L149

`ShowInputMethodInformation` is in upper case, while `showInputMethodInformationWhenFocusIn` is in lower case.

**Comment by wengxt** [comment]
While it's indeed inconsistent, I'd prefer not to fix it because it's already in user's config. Renaming it would make user lost their configuration for this option.
