### ISSUE TITLE
deepin桌面环境必须禁用dbusmenu模块才能出现任务栏菜单

### ISSUE THREAD

**Issue by chenshijie-uos** [fcitx/fcitx5#464]
**Describe the bug**
deepin桌面环境必须禁用dbusmenu模块才能出现任务栏菜单

**To Reproduce**
按照archlinux安装fcitx5.
重新启动系统，输入法可以正常使用，正常切换。
右下角输入法菜单不见了。
执行fcitx5 -r,托盘中输入法菜单闪烁后消失。
打开输入法配置禁用掉dbusmenu模块。执行fcitx5 -r,托盘任务栏菜单出现是经典界面的任务栏。

**Expected behavior**

deepin桌面环境在不禁用dbusmenu时，任务栏输入法托盘及菜单可以正常显示。（顺便说一句同样的环境下flatpak fcitx5可以正常显示托盘及菜单）

**Additional context**
[fcitx5.log](https://github.com/fcitx/fcitx5/files/8315697/fcitx5.log)

**Comment by wengxt** [comment]
首先，如果重启 dde-dock，图标就会出现了

虽然我建议还是应该 dde-dock 修复一下，但我还是 workaround 了一下 https://github.com/fcitx/fcitx5/commit/e37c29c8fb2d53e0abefdb329901558264f4aa90

fcitx5 的 sni 是向 dde-session-daemon 注册，而 dde-dock 则和 dde-session-daemon 交互来获取哪些托盘，我随便看了看 dde-dock 我推测原因是 同一个进程只能有一个托盘一类的限制，所以虽然workaround  延迟一些时间来启用 xembed 托盘而不是像当前这样先 xembed 然后再注册完成后切换，但并不能保证它一定能总是起作用。

**Comment by kt286** [comment]
其实不用重启 dde-dock，只需要启动或关闭一个有托盘图标的程序就可以了，例如深度音乐
