### ISSUE TITLE
Wayland 下部分应用内 RIME 不会应用系统的 Caps Lock as Ctrl 配置

### ISSUE THREAD

**Issue by outloudvi** [fcitx/fcitx5#467]
在 GNOME (on Wayland) 下，当透过 `gnome-tweaks > "Keyboard & Mouse" > "Additional Layout Options"` 中的 `“Caps Lock behavior” > "Make Caps Lock an additional Ctrl"` 和/或 `"Ctrl position" > "Caps Lock as Ctrl"` 将 `Caps Lock` 替换为 `Ctrl` 时（启用两者其一或其二），RIME 依旧会在部分应用中（例如 Telegram、Chromium 和 VSCode）将按下 `Caps Lock` 的行为认作 `Caps Lock`，而非 `Ctrl`。

此现象在 GNOME on Xorg 中没有出现。

我尝试在 `~/.local/share/fcitx5/rime/default.custom.yaml` 中应用：

``` yml
patch:
  # ...
  “ascii_composer/switch_key/Caps_Lock”: noop
```

但是似乎在重部署后也未能阻止 RIME 在 `Caps_Lock` 时切换 `ascii_mode`。

---

受影响的应用日志：
```
rimeengine.cpp:310] Rime receive key: Key(Caps_Lock states=0) 0
rimeengine.cpp:332] Notification: 93912239288112 option ascii_mode
rimeengine.cpp:310] Rime receive key: Key(Control+Caps_Lock states=4) 1
```

其它应用日志：

```
rimeengine.cpp:310] Rime receive key: Key(Control_L states=0) 0
rimeengine.cpp:310] Rime receive key: Key(Control+Control_L states=4) 1
```

相关包版本（Arch Linux）：
* gnome-session 41.3-1
* gnome-tweaks 40.10-1
* wayland 1.20.0-1
* fcitx5 5.0.15-1
* fcitx5-rime 5.0.12-1

根据 fcitx/fcitx5-rime#25，贴 `~/.config/fcitx5/profile`：
``` ini
[Groups/0]
# Group Name
Name=Keyboard
# Layout
Default Layout=us
# Default Input Method
DefaultIM=keyboard-us

[Groups/0/Items/0]
# Name
Name=keyboard-us
# Layout
Layout=

[Groups/1]
# Group Name
Name=CJK
# Layout
Default Layout=us
# Default Input 

> Method

DefaultIM=mozc

[Groups/1/Items/0]
# Name
Name=rime
# Layout
Layout=

[Groups/1/Items/1]
# Name
Name=mozc
# Layout
Layout=

[GroupOrder]
0=CJK
1=Keyboard
```

**Comment by wengxt** [comment]
主要就是 wayland 下没有获取 xkb option 的统一的办法，之前不支持读取 gnome的 xkb option，在应用到 xwayland 的部分就没有应用对应的 xkb option 

加上了读 gnome 的 xkb option 的支持你可以试试

**Comment by outloudvi** [comment]
在 c08160b6 的 `fcitx-git` 确认问题不再出现。谢谢！

（不过为了各种其它软件的兼容性，大概我还是换到 hwdb 去好了。）
