### ISSUE TITLE
Fcitx5 sometimes makes shift be "sticky"

### ISSUE THREAD

**Issue by Ai-rin** [fcitx/fcitx5#469]
Under some conditions (like focus change with shift pressed) fcitx5 makes it stuck until i press it again. In some applications it happens even when I just press shift + enter.
To reproduce:

1. open text editor
2. choose an input method, type some text
3. press and hold shift, change focus for a moment using mouse, release shift
4. type some more

Result: shift is stuck until you press it again.
This happens both in Xorg and Wayland.
Tested with Ukrainian, Russian and Hebrew.

Output of fcitx5-diagnose:
[fcitx5-diagnose.txt](https://github.com/fcitx/fcitx5/files/8357653/fcitx5-diagnose.txt)

**Comment by wengxt** [comment]
Can you help check if the commit above fix the issue?

**Comment by Ai-rin** [comment]
@wengxt Yes, the problem is gone, thanks!
