### ISSUE TITLE
fcitx5在wayland下没有候选框

### ISSUE THREAD

**Issue by VitalyAnkh** [fcitx/fcitx5#47]
我使用gnome on wayland，输入法配置为fcitx5，在wayland原生软件下不显示候选框，但能看到输入的字，可以通过tab选词，很不方便；在通过Xwayland运行的X应用下有输入框，但因为我的屏幕是2k分辨率，由于Xwayland的只会渲染出1080P的像素，再由系统放大2倍，所有界面模糊

搜遍了文档和各种fcitx5介绍文章，没看到相关的解决方法。通过xeyes我看到fcitx5的输入框是运行在Xorg下的，所以跟wayland原生软件不太搭，是否可以迫使它运行在wayland下来解决？

我的系统是Arch Linux， 内核5.6.3，fcitx5的版本是4.99.0

请问该怎么解决这问题呢？

**Comment by vowstar** [comment]
> 我使用gnome on wayland，输入法配置为fcitx5，在wayland原生软件下不显示候选框，但能看到输入的字，可以通过tab选词，很不方便；在通过Xwayland运行的X应用下有输入框，但因为我的屏幕是2k分辨率，由于Xwayland的只会渲染出1080P的像素，再由系统放大2倍，所有界面模糊
> 
> 搜遍了文档和各种fcitx5介绍文章，没看到相关的解决方法。通过xeyes我看到fcitx5的输入框是运行在Xorg下的，所以跟wayland原生软件不太搭，是否可以迫使它运行在wayland下来解决？
> 
> 我的系统是Arch Linux， 内核5.6.3，fcitx5的版本是4.99.0
> 
> 请问该怎么解决这问题呢？

你可以先试试装这个插件 https://extensions.gnome.org/extension/261/kimpanel/

我在wayland 1.18下实际测试输入框和文字显示正常。我是gentoo (profile 17.1)
fcitx5 -v
4.99.0

**Comment by VitalyAnkh** [comment]
@vowstar 我装了kde版本的kimpanel，它可以在gnome下运行，运行X11软件时可以显示候选框，但问题是在wayland原生应用下无候选框。原因是否为候选框不支持原生地运行在wayland（不使用Xwayland）？

**Comment by wengxt** [comment]
那两个不是一回事。gnome shell 下就是上面那个插件。

**Comment by vowstar** [comment]
> @vowstar 我装了kde版本的kimpanel，它可以在gnome下运行，运行X11软件时可以显示候选框，但问题是在wayland原生应用下无候选框。原因是否为候选框不支持原生地运行在wayland（不使用Xwayland）？

我就是在原生wayland下测试的 
```bash
$ env | grep XDG_SESSION_TYPE
XDG_SESSION_TYPE=wayland
```

**Comment by wengxt** [comment]
总之不能算是一个 bug，因为 wayland 如果不用 wayland 的 im protocol，那就只能在可以进行绝对定位的程序中显示面板才能保证位置正确。当然你如果要问，「我不关心输入框显示在哪能不能就随便画一个显示在随机位置」……我觉得这种事没意义不打算做。

**Comment by HougeLangley** [comment]
> > 我使用gnome on wayland，输入法配置为fcitx5，在wayland原生软件下不显示候选框，但能看到输入的字，可以通过tab选词，很不方便；在通过Xwayland运行的X应用下有输入框，但因为我的屏幕是2k分辨率，由于Xwayland的只会渲染出1080P的像素，再由系统放大2倍，所有界面模糊
> > 搜遍了文档和各种fcitx5介绍文章，没看到相关的解决方法。通过xeyes我看到fcitx5的输入框是运行在Xorg下的，所以跟wayland原生软件不太搭，是否可以迫使它运行在wayland下来解决？
> > 我的系统是Arch Linux， 内核5.6.3，fcitx5的版本是4.99.0
> > 请问该怎么解决这问题呢？
> 
> 你可以先试试装这个插件 https://extensions.gnome.org/extension/261/kimpanel/
> 
> 我在wayland 1.18下实际测试输入框和文字显示正常。我是gentoo (profile 17.1)
> fcitx5 -v
> 4.99.0

是的，确实可以用了

**Comment by HougeLangley** [comment]
用 kimpanel 确实能够显示候选框，不过另外的问题就是看不清自己打字的内容

**Comment by wengxt** [comment]
@HougeLangley 看不清是什么意思？觉得颜色不好？可以在扩展里面改改字体大小等。

**Comment by VitalyAnkh** [comment]
@wengxt @HougeLangley 我也使用kimpanel，默认配色的确很难看清候选字，而且用gnome-tweaks改字体大小和候选框颜色不起作用。后来我发现只要把gnome主题改成暗色色调的，kimpanel的候选框也就变成暗色的，就可以看清楚了。

**Comment by fansuregrin** [comment]
> @wengxt @HougeLangley 我也使用kimpanel-for-gnome-shell，默认配色的确很难看清候选字，而且用gnome-tweaks改字体大小和候选框颜色不起作用。后来我发现只要把gnome主题改成暗色色调的，kimpanel的候选框也就变成暗色的，就可以看清楚了。

是的我也遇到了同样的问题，使用kimpanel-for-gnome-shell这个扩展的话，fcitx5设置的皮肤样式不起作用。搜索了一些关键词，不知道怎么解决。朋友，你现在解决了吗？

**Comment by HougeLangley** [comment]
> @HougeLangley 看不清是什么意思？觉得颜色不好？可以在扩展里面改改字体大小等。

后来这个问题通过修改shell主题解决了

**Comment by HougeLangley** [comment]
> > @wengxt @HougeLangley 我也使用kimpanel-for-gnome-shell，默认配色的确很难看清候选字，而且用gnome-tweaks改字体大小和候选框颜色不起作用。后来我发现只要把gnome主题改成暗色色调的，kimpanel的候选框也就变成暗色的，就可以看清楚了。
> 
> 是的我也遇到了同样的问题，使用kimpanel-for-gnome-shell这个扩展的话，fcitx5设置的皮肤样式不起作用。搜索了一些关键词，不知道怎么解决。朋友，你现在解决了吗？

这个只能套用gnome-shell的主题，想用fcitx5的主题只能去用kde了

**Comment by calidion** [comment]
Ubuntu 22.04 fcitx 5 没有提示框。
以前fcitx 4好好的。现在一更新就升级到5了。导致输入提示框没有了。
目前也没有发现解决办法。

并没有找到fcitx5版本的kimpanel

**Comment by calidion** [comment]
我使用的是unbuntu unity桌面

**Comment by calidion** [comment]
```
sudo apt install fcitx5-module-wayland fcitx-module-x11 
```

安装了上面的两个组件，再乱点了一通配置后，现在输入法在非snap应用下算是恢复了。

不知道是配置问题，还是组件没有安装的问题。

**Comment by wengxt** [comment]
多半是没有安装全的问题

**Comment by yunnysunny** [comment]
都安装了，还是不行
