### ISSUE TITLE
virtualkeyboard分支

### ISSUE THREAD

**Issue by zcj-git520** [fcitx/fcitx5#475]
您好！
1.virtualkeyboard这个分支是支持软键盘是么？
2.我在编译virtualkeyboard分支上报错：
| CMake Error at spell-en-download-download.cmake:3 (file):
|   file DOWNLOAD HASH mismatch
| 
|     for file: [/home/zcj/Documents/yocto/build/tmp/work/armv8a-poky-linux/fcitx5/1.0-r0/fcitx5/src/modules/spell/dict/en_dict-20121020.tar.gz]
|       expected hash: [c44a5d7847925eea9e4d2d04748d442cd28dd9299a0b572ef7d91eac4f5a6ceb]
|         actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
|              status: [77;"Problem with the SSL CA cert (path? access rights?)"]

**Comment by wengxt** [comment]
分支里面还没什么实际的东西，建议不用尝试

报错的地方建议检查网络

真的需要用不如尝试这个（需要支持 zwp_input_method_v1 的 wayland compositor）

https://github.com/clear-code/fcitx5-virtualkeyboard-ui

**Comment by zcj-git520** [comment]
好的，谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fcitx/fcitx5] virtualkeyboard分支 (Issue #475)





 
分支里面还没什么实际的东西，建议不用尝试
 
报错的地方建议检查网络
 
真的需要用不如尝试这个（需要支持 zwp_input_method_v1 的 wayland compositor）
 
https://github.com/clear-code/fcitx5-virtualkeyboard-ui

**Comment by zcj-git520** [comment]
您好！
&nbsp;在打扰您一下，我有两个问题：
1、我使用yocto进行https://github.com/clear-code/fcitx5-virtualkeyboard-ui的编译，发现在do_pake报错了，ERROR: fcitx5-virtualkeyboard-ui-5.0.0-r0 do_package_qa: QA Issue: fcitx5-virtualkeyboard-ui: The compile log indicates that host include and/or library paths were used.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Please check the log '/home/zcj/Documents/yocto/build/tmp/work/armv8a-poky-linux/fcitx5-virtualkeyboard-ui/5.0.0-r0/temp/log.do_compile' for more information. [compile-host-path]
ERROR: fcitx5-virtualkeyboard-ui-5.0.0-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: /home/zcj/Documents/yocto/build/tmp/work/armv8a-poky-linux/fcitx5-virtualkeyboard-ui/5.0.0-r0/temp/log.do_package_qa.19368
2、编译出来的只有一个动态库：libvirtualkeyboardui.so，不知道是否正常
3、您那边有相应的bbfile么
谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fcitx/fcitx5] virtualkeyboard分支 (Issue #475)





 
分支里面还没什么实际的东西，建议不用尝试
 
报错的地方建议检查网络
 
真的需要用不如尝试这个（需要支持 zwp_input_method_v1 的 wayland compositor）
 
https://github.com/clear-code/fcitx5-virtualkeyboard-ui

**Comment by ashie** [comment]
(Sorry, I can't speak Chinese.)

Which recipe did you use to build Fcitx5 core?
This one?: https://gitlab.com/clear-code/meta-inputmethod/

And, did you create a new recipe for fcitx5-virtualkeyboard-ui?
(We don't yet publish the recipe for it.)

**Comment by zcj-git520** [comment]
Hello!

Yes, I created fcitx5 using this https://gitlab.com/clear-code/meta-inputmethod/.

Now I need to create support for virtual keyboards in Weston. I tried to create fcitx5-virutalkeyboard -ui.bb in yocto, but there was a problem. I don't know if this is supported

Looking forward to your reply, thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fcitx/fcitx5] virtualkeyboard分支 (Issue #475)





 
(Sorry, I can't speak Chinese.)
 
Which recipe did you use to build Fcitx5 core?
 This one?: https://gitlab.com/clear-code/meta-inputmethod/
 
And, did you create a new recipe for fcitx5-virtualkeyboard-ui?
 (We don't yet publish the recipe for it.)

**Comment by wengxt** [comment]
@zcj-git520 Suggest to try cmake directly and give us the error when you with cmake. I never used yocto before so I can't help there.

**Comment by ashie** [comment]
(We already have the recipe for fcitx5-virutalkeyboard-ui internally but cannot publish it for now in some reason, sorry.)

> fcitx5-virtualkeyboard-ui-5.0.0-r0 do_package_qa: QA Issue: fcitx5-virtualkeyboard-ui: The compile log indicates that host include and/or library paths were used.

Probably it means your recipe lacks some dependencies.
Dependency of fcitx5-virutalkeyboard-ui is similar with fcitx5's one since some of codes in fcitx5-virutalkeyboard-ui are copied from fcitx5, please check it.

**Comment by zcj-git520** [comment]
Hello!

Could you please help me change the BB file of FCITx5-VirtualKeyboard - UI? I am using FCITx5-5.0.8

Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 中午1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fcitx/fcitx5] virtualkeyboard分支 (Issue #475)





 
(We already have the recipe for fcitx5-virutalkeyboard-ui internally but cannot publish it for now in some reason, sorry.)
  
fcitx5-virtualkeyboard-ui-5.0.0-r0 do_package_qa: QA Issue: fcitx5-virtualkeyboard-ui: The compile log indicates that host include and/or library paths were used.
  
Probably it means your recipe lacks some dependencies.
 Dependency of fcitx5-virutalkeyboard-ui is similar with fcitx5's one since some of codes in fcitx5-virutalkeyboard-ui are copied from fcitx5, please check it.

**Comment by zcj-git520** [comment]
hello


(Based on fcitx5-virutalkeyboard-ui5.0.08)&nbsp; Soft keyboard: characters can not be used, numbers and other characters can be used, why


Hope to reply!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 中午1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fcitx/fcitx5] virtualkeyboard分支 (Issue #475)





 
(We already have the recipe for fcitx5-virutalkeyboard-ui internally but cannot publish it for now in some reason, sorry.)
  
fcitx5-virtualkeyboard-ui-5.0.0-r0 do_package_qa: QA Issue: fcitx5-virtualkeyboard-ui: The compile log indicates that host include and/or library paths were used.
  
Probably it means your recipe lacks some dependencies.
 Dependency of fcitx5-virutalkeyboard-ui is similar with fcitx5's one since some of codes in fcitx5-virutalkeyboard-ui are copied from fcitx5, please check it.

**Comment by zcj-git520** [comment]
Thank you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 中午1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fcitx/fcitx5] virtualkeyboard分支 (Issue #475)





 
(We already have the recipe for fcitx5-virutalkeyboard-ui internally but cannot publish it for now in some reason, sorry.)
  
fcitx5-virtualkeyboard-ui-5.0.0-r0 do_package_qa: QA Issue: fcitx5-virtualkeyboard-ui: The compile log indicates that host include and/or library paths were used.
  
Probably it means your recipe lacks some dependencies.
 Dependency of fcitx5-virutalkeyboard-ui is similar with fcitx5's one since some of codes in fcitx5-virutalkeyboard-ui are copied from fcitx5, please check it.

**Comment by zcj-git520** [comment]
Hello!

ok,Fcitx5 - VirtualKeyboard - UI is supported for virtual keyboards in Weston.

Looking forward to your reply, thank you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fcitx/fcitx5] virtualkeyboard分支 (Issue #475)





 
@zcj-git520 Suggest to try cmake directly and give us the error when you with cmake. I never used yocto before so I can't help there.

**Comment by zcj-git520** [comment]
您好！
&nbsp;-- Could NOT find EGL (missing: HAVE_EGL) (found version "1.5")
| CMake Error at CMakeLists.txt:57 (include):
|&nbsp;&nbsp; include could not find load file:
| 
|&nbsp;&nbsp;&nbsp;&nbsp; /usr/lib/cmake/Fcitx5Utils/Fcitx5CompilerSettings.cmake
这个怎么解决呀



谢谢呀！

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fcitx/fcitx5] virtualkeyboard分支 (Issue #475)





 
@zcj-git520 Suggest to try cmake directly and give us the error when you with cmake. I never used yocto before so I can't help there.
