### ISSUE TITLE
关于显示输入法状态的问题

### ISSUE THREAD

**Issue by yyy33** [fcitx/fcitx5#477]
**Describe the bug**
If the problem is about you can not use fcitx in certain application, or the input window is placed in wrong place, be sure to include which application is being typed, and the output of fcitx5-diagnose command.

Specifically, it is Ok to write the issue in Chinese (either Simplified or Traditional).
可以用中文(简体或繁体)汇报问题。
作者你好,我想在获得输入焦点的时候就显示当前输入法的状态,然后我勾选了图中的选项,并没有其作用
![2022-04-22_18-21](https://user-images.githubusercontent.com/51548147/164694163-06e78acd-8c2e-4b54-bad8-83801b21c003.png)

**To Reproduce**
1. Open ... app
2. Try to type ...

**Expected behavior**

**Desktop (please complete the following information):**
 - Desktop: (KDE, GNOME, etc)
 - Display server type: X11, Wayland
 - The output of fcitx5-diagnose if possible.

**Additional context**

**Comment by wengxt** [comment]
你截图的配置工具是fcitx4，报给fcitx5，你到底在用fcitx4还是5？
