### ISSUE TITLE
Use zwlr_foreign_toplevel_manager_v1 to obtain the current running wayland application for wlroots based compositor

### ISSUE THREAD

**Issue by wengxt** [fcitx/fcitx5#487]
So we can detect the current app name.

**Comment by CoelacanthusHex** [comment]
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/156

**Comment by CoelacanthusHex** [comment]
And another read only protocol https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/155
