### ISSUE TITLE
[Feature Request] 对特定程序使用特定输入法

### ISSUE THREAD

**Issue by hosxy** [fcitx/fcitx5#49]
希望能够增加一个能够手动指定特定程序默认使用特定输入法，而不是全局状态。比如
对于 konsole，gnome-terminal，xfce4-terminal 等这种终端类程序默认使用英文输入法比较好，
而对于中文用户 telegram，firefox 这种默认使用中文输入法可能会好点.

因为不同 APP 功能不同，对于默认输入法有不同的需求，希望能够增加一个类似白名单东西，用户可以手动指定某个程序默认使用某个输入，比如：指定 xfce下文本编辑器 mousepad 默认使用 rime 输入法，指定xfce4-terminal默认使用英文输入法(非激活状态?)

**Comment by wengxt** [comment]
建议自己实现一下。

可以监听一下 InputContextCreatedEvent。

**Comment by hosxy** [comment]
额，不会写代码 (⋟﹏⋞)，
rime在windows和osx下的实现有这个功能，还是希望作者能考虑下

**Comment by hosxy** [comment]
fcitx5-lua 好像也只能监听 KeyEvent 这一个事件

**Comment by wengxt** [comment]
> fcitx5-lua 好像也只能监听 KeyEvent 这一个事件

写 C++ 代码啊。lua 的那个本来就是因为没有实际使用场景，所以只提供了有限的支持。

**Comment by hosxy** [comment]
> > fcitx5-lua 好像也只能监听 KeyEvent 这一个事件
> 
> 写 C++ 代码啊。lua 的那个本来就是因为没有实际使用场景，所以只提供了有限的支持。

lua 倒是可以速成一下，C++ 是真的没办法速成，写不出代码😭

**Comment by kenarp** [comment]
标记一下，挺希望有这个功能的，看看以后会不会有人实现（或者自己学C++😂）

**Comment by CoelacanthusHex** [comment]
> 标记一下，挺希望有这个功能的，看看以后会不会有人实现（或者自己学C++😂）

其实提问题的同学已经写完了
https://github.com/hosxy/fcitx5-lua-spusim

**Comment by kenarp** [comment]
> > 标记一下，挺希望有这个功能的，看看以后会不会有人实现（或者自己学C++joy）
> 
> 其实提问题的同学已经写完了 https://github.com/hosxy/fcitx5-lua-spusim

谢谢回复。已经装好了，很好用的feature。
