### ISSUE TITLE
How to disable quickphrase? I have other use for Win+; binding.

### ISSUE THREAD

**Issue by QiangF** [fcitx/fcitx5#491]
Seems like the hot key is hard coded in https://github.com/fcitx/fcitx5/blob/08e0a5f9367466fb4360d0a8c2dbc80e9406d9ff/src/modules/quickphrase/quickphrase.h

**Comment by rocka** [comment]
https://github.com/fcitx/fcitx5/blob/e4c7170cf6ca26a9840818b792cc4553a02787ee/src/modules/quickphrase/quickphrase.h#L33-L38

这个地方的设置只是默认值。在 fcitx5-configtool 里找到 Addons -> QuickPhrase ，然后按后面的设置按钮，就能设置快捷键了。

![image](https://user-images.githubusercontent.com/13914967/167601828-eeae1504-ae40-4dfd-a4cd-cf87b111f527.png)

![image](https://user-images.githubusercontent.com/13914967/167601940-53371d37-e347-4711-8260-a8403b0e3e91.png)

**Comment by QiangF** [comment]
啊，之前没注意到，谢谢！
另外好像下面两个快捷键在图形界面里没有对应的设置：
[Hint Trigger]
[One Time Hint Trigger]

**Comment by QiangF** [comment]
@rocka quickphrase的弹出框如果能换成emacs buffer就好了, emacs-anywhere 可以在任何输入框使用 emacs 编辑，就是太绕

**Comment by wengxt** [comment]
> 啊，之前没注意到，谢谢！
> 另外好像下面两个快捷键在图形界面里没有对应的设置：
> [Hint Trigger]
> [One Time Hint Trigger]

键盘的配置里

**Comment by QiangF** [comment]
看到了，谢谢！
