### ISSUE TITLE
[ 68%] Generating org.fcitx.Fcitx5.metainfo.xml 错误

### ISSUE THREAD

**Issue by ChenKE404** [fcitx/fcitx5#492]
错误信息: /usr/bin/msgfmt: 无法定位 /home/xxxx/fcitx5-5.0.15/data/org.fcitx.Fcitx5.metainfo.xml.in 的 ITS 规则
OS: Ubuntu 20.04

**Comment by ChenKE404** [comment]
I dont know how & i dont know why

**Comment by wengxt** [comment]
install appstream

**Comment by ChenKE404** [comment]
oh yeah,it's work! thanks!
