### ISSUE TITLE
Moving to xwayland from pure wayland causes fcitx5 to generate lots of key presses.

### ISSUE THREAD

**Issue by crocket** [fcitx/fcitx5#496]
**Describe the bug**

If I'm on a pure wayland application, moving to an xwayland window results in lots of keypresses. `t` or any other key is pressed by fcitx5 a lot automatically until I press a key on my keyboard.

Gtk or Qt applications that run on wayland don't cause this issue. Pure wayland applications do.

**To Reproduce**

* Activate fcitx5 by opening a Qt or Gtk application.
* Open an xwayland window such as
  * `env WINIT_UNIX_BACKEND=x11 alacritty`
  * st terminal emulator.
* Open a pure wayland window such as
  * alacritty
  * foot terminal emulator
  * `env SDL_VIDEODRIVER=wayland dosbox-x`
* Move focus back to the previously opened xwayland window by clicking it or with a keyboard shortcut.
* Stop automatic keypresses from fcitx5 by pressing `t` or any key. Press `Ctrl+u` to clear the command line.
* Focus on the pure wayland window. Move focus back to the xwayland window again.

**Expected behavior**

fcitx5 doesn't press `t` repetitively.

**Desktop (please complete the following information):**
 - Desktop: Sway wayland compositor
 - Display server type: wayland
 - [fcitx5-diagnose.txt](https://github.com/fcitx/fcitx5/files/8760843/fcitx5-diagnose.txt)

**Comment by wengxt** [comment]
I can't reproduce this, what's the version of your sway and wlroots?

What exact step you need to do to reproduce this?

Here's what I tried:
1. open foot, and open xterm. 
2. Move mouse to foot, switch fcitx to either keyboard or pinyin
3. Press t
4. move mouse to xterm

Or 
2. move mouse to xterm, switch fcitx to either keyboard or pinyin
3. press t
4. move mouse to foot.

Either way I can't reproduce your issue.

This might be the fix you're looking for if your wlroots doesn't have it: https://github.com/swaywm/wlroots/pull/2918/commits/ad386c642ddcea68b8683f68489f07dec427e298

**Comment by crocket** [comment]
Sway 1.7
Wlroots 0.15.1 https://gitlab.freedesktop.org/wlroots/wlroots/-/tags

1. Open qutebrowser or firefox or any Gtk/Qt program to activate fcitx5. You don't need to change input method.
2. Open foot
3. Open xterm
4. Move window focus to foot
5. Move window focus back to xterm
6. Do 4 and 5 several times.

**Comment by wengxt** [comment]
do you press any key during these steps?
how do you launch foot and xterm?

is the key being repeated pressed during any of the steps?

I’d assume if everything is launched with pure mouse click it won’t happen right? (Though I don’t know how to do that under sway)

**Comment by crocket** [comment]
When focus moves to xterm, a key should be repeatedly pressed by fcitx5.

I launch web browser with a sway keyboard shortcut and terminal emulators with keyboard shortcuts.

Add the following lines to sway config.

```
# Mod4 means win key.
set $mod Mod4

bindsym $mod+Return exec foot
bindsym $mod+Shift+Return exec xterm
bindsym $mod+b exec firefox
```

With keyboard shortcuts, it is easy to test the issue.

I also move window focus by pressing `$mod+l` and `$mod+h` which are defined by default sway config.

**Comment by wengxt** [comment]
Can you describe in more details steps? Or screen recording may also be helpful.

I tried open foot, and open xterm, and keep some key pressed when moving focus between xterm and foot, still can't reproduce it. Do you set key repetition rate to some very high number?

Also, can you run fcitx5 with --verbose=key_trace=5, and tell me what's the output when the issue is triggered?

**Comment by crocket** [comment]
Try opening foot after opening xterm. Switching to tab layout in sway makes it easier to trigger the issue.

**Comment by crocket** [comment]
When moving from frontend:wayland_v2 of foot to frontend:xim of alacritty, foot's focus becomes 0, and alacritty's focus becomes 1. I also see a lot of `t`s pressed in x11 alacritty.

**Comment by crocket** [comment]
What I discovered with

> watch -n 2 dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo

is that if I have one xorg terminal emulator open, there is one x11 input context with frontend:xim and one wayland input context with frontend:wayland_v2.

The weird thing is that the same wayland input context is used by wayland terminal emulators like foot.

When there is only x11 alacritty.

```
Group [x11::0] has 1 InputContext(s)
  IC [f61f5891bcb4426aa8c0164489c35334] program:alacritty frontend:xim cap:4000000000 focus:1
Group [wayland:] has 1 InputContext(s)
  IC [2bc70b8005db436b9447926aab1d2b40] program: frontend:wayland_v2 cap:100000052 focus:0
```

When there are foot and x11 alacritty with the window focus on foot,

```
Group [x11::0] has 1 InputContext(s)
  IC [f61f5891bcb4426aa8c0164489c35334] program:alacritty frontend:xim cap:4000000000 focus:0
Group [wayland:] has 1 InputContext(s)
  IC [2bc70b8005db436b9447926aab1d2b40] program: frontend:wayland_v2 cap:100000052 focus:1
```

**Comment by wengxt** [comment]
I'm trying to understand where the key "t" comes from. So basically, since alacritty is a X client, and X11 key repetition comes from X server. It could be Xwayland doesn't handle focus way or sth.

It could be Xwayland was wrongly generating key repetition. What's your version of Xwayland btw? I have 22.1.2 here.

While fcitx also generate key repetition for client that use wayland_v2, the timer will stop if wayland_v2 has no focus. And there's code to ensure it always send a fake release if the last virtual key is press, to ensure key release always happens.

 I want to make sure whether it's fcitx's keep sending fake key event, or it's Xwayland generating key repetition. 

Can you start fcitx with following command?
 WAYLAND_DEBUG=1 fcitx5 -r 2>&1 | grep 'zwp_virtual_keyboard_v1.*key(' 

And check if fcitx continously produce new lines when the issue happens, or what's the last a few lines before the issue happens?

**Comment by crocket** [comment]
fcitx5 doesn't continuously produce new lines when the issue happens. This is what I got before and during the issue.
```
[3832886.130]  -> zwp_virtual_keyboard_v1@14.key(6405950, 38, 0)
[3834229.227]  -> zwp_virtual_keyboard_v1@14.key(6407293, 125, 1)
[3834241.246]  -> zwp_virtual_keyboard_v1@14.key(6407293, 125, 0)
```

**Comment by wengxt** [comment]
I believe the log you show means you pressed Super+L to move the focus in sway.

One of my question is , did you ever pressed the key being repeated during the test?
And another thing I want to check is that, if xwayland generates these repeat keys.

Can you run ```xinput test-xi2 --root``` before the test and keep it running (ignore the warning that "it's running against xwayland") and check if there's any continuously output when the issue happens.

If xwayland is generating the repeats, I'd expect  lots of output like
```
EVENT type 2 (KeyPress)
    device: 9 (9)
    detail: 41
    flags: repeat
    root: 654.00/399.00
    event: 654.00/399.00
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x3c6 event 0x3c6 child 0x20002
```

Also I want to know if it is the interaction between zwp_input_method_v2's keyboard grab somehow conflicts, can you also do another test by starting fcitx with ```fcitx5 -r --disable waylandim```, and check the issue can still be reproduced or not.

**Comment by crocket** [comment]
I pressed `t` only to stop fcitx5 or xwayland from automatically pressing `t` infinitely.

I see this event repeated a lot when the issue occurs on x11 alacritty.

```
tEVENT type 2 (KeyPress)
    device: 9 (9)
    detail: 28
    flags: repeat
    root: 787.00/296.00
    event: 787.00/296.00
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x3c6 event 0x3c6 child 0x1c00004
```

Notice `t` before `EVENT`.

`fcitx5 -r --disable waylandim` works around the issue, but I need waylandim for foot terminal emulator.

**Comment by wengxt** [comment]
1. would you mind share your sway/config? I wonder if there's anything hidden in your configuration.
2. Can you test this: logout and login into sway, do not ever press "t" under any circumstances until you reproduce your issue. Is that doable? I don't know if it's always "t" or some other key, but I just wonder if you don't press the key being repeated at all, that might exclude the possibility that it comes from fcitx. Fcitx does send "virtual key", but it only sends whatever is being pressed.

**Comment by crocket** [comment]
I finally found a way to reproduce the issue reliably with this minimal sway config.

```
# vim: filetype=i3
set $mod Mod4

exec fcitx5 -dr

bindsym $mod+Return exec /usr/bin/st
bindsym $mod+Shift+Return exec /usr/bin/foot
bindsym $mod+d exec bemenu-run

# move focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
```

1. Press $mod+Shift+Return to launch foot
2. Press `exi`
3. Press `t` and Enter "very quickly".
4. Press $mod+Shift+Return to launch foot again
5. Press $mod+Return to launch st

**Comment by wengxt** [comment]
Thanks, your instruction really helps. Just a slightly adjustment in the steps:
you don't need to be really fast, but to ensure that "t' is still pressed after foot exits.

Can you verify if git master fix the issue?

**Comment by crocket** [comment]
I just tested the git master, and the issue seems to have been fixed. Great Work.
