### ISSUE TITLE
Pressing Shift or Alt cancels new compose method

### ISSUE THREAD

**Issue by maxigaz** [fcitx/fcitx5#497]
**Describe the bug**
Compose Key combinations that involve holding Shift or Alt don't work if 'New compose behavior' is enabled in the configuration of fcitx5.

**To Reproduce**
1. Open the configuration window of fcitx5.
1. Select the current input method (in my case, it's 'Keyboard - Hungarian'), and click on the cogwheel icon in the centre.
1. Make sure the option 'New compose behavior' is enabled.
1. Change focus to an application with text input (e.g. Firefox or Alacritty).
1. Try to type <kbd>Compose</kbd>-<kbd>RightAlt</kbd>-<kbd>y</kbd>.
1. `>` is printed.

**Expected behavior**
<kbd>Compose</kbd>-<kbd>RightAlt</kbd>-<kbd>y</kbd> prints the character `»`.

**Desktop (please complete the following information):**
 - Desktop: i3-gaps
 - Display server type: X11
 - The output of fcitx5-diagnose: [fcitx-diagnose.txt](https://github.com/fcitx/fcitx5/files/8774299/fcitx-diagnose.txt)

**Additional context**
A workaround is to disable the option 'New compose behavior'.

**Comment by wengxt** [comment]
can you help verify if the fix works for you?
