### ISSUE TITLE
If I activate input method, it is deactivated and activated infinitely.

### ISSUE THREAD

**Issue by crocket** [fcitx/fcitx5#502]
**Describe the bug**

I'm on b65e22c5a223f1ad7935ecf0a68f16496ba1d1e6

I don't know how to reproduce the issue, yet.

When the issue occurs, if I activate input method, it is deactivated and activated infinitely. I can't type anything.

**To Reproduce**

**Desktop (please complete the following information):**
 - Desktop: Sway
 - Display server type: Wayland

**Additional context**

The fix for my last issue probably caused this issue.

**Comment by wengxt** [comment]
Does the issue happen in xwayland or wayland application?

**Comment by wengxt** [comment]
Can you try master? I won't say I fixed anything I can only blindly change some code at this point.

Also I believe your issue is something like ctrl+space being repeated or sth. Try press some key to prevent repetition as a workaround.

**Comment by crocket** [comment]
I press ctrl+shift+space to toggle input method.

**Comment by crocket** [comment]
Somehow, I think this issue is probably a sway issue or a qutebrowser issue.

Perhaps, the window focus moves between windows due to a sway bug.

Closing this issue for now.

**Comment by crocket** [comment]
I will open another issue if I can reproduce it reliably.

**Comment by wengxt** [comment]
I seems to accidentally triggered this once, but unfortunately I also don't know how to re-produce it. In my case it's a wayland konsole window that having this problem, which is kinda weird because it's using fcitx im module and I can see fcitx isn't receiving extra key.
