### ISSUE TITLE
Input window no longer visible on Sway with 5.0.17 (Japanese)

### ISSUE THREAD

**Issue by kekkoudesu** [fcitx/fcitx5#505]
**Describe the bug**

With 5.0.16 on Sway with Firefox, I was able to see the the input window when typing in Japanese so I could select the correct kanji. This does not happen with version 5.0.17.

**To Reproduce**
1. Open Firefox
2. Change input method to Japanese
3. Start typing
4. Press space to change characters
5. Input window does not appear

**Expected behavior**

**Desktop (please complete the following information):**
 - Desktop: Sway
 - Display server type:  Wayland
 - Distribution: Arch Linux
 - The output of fcitx5-diagnose if possible.
[fcitx-diag.txt](https://github.com/fcitx/fcitx5/files/8826143/fcitx-diag.txt)

**Additional context**
I am using fcitx-mozc.

**Comment by wengxt** [comment]
You doesn't seem to set GTK_IM_MODULE=fcitx from your fcitx5 diagnose output.

I don't think fcitx5 upgrade to 5.0.17 may affect this.

Please check 
https://wiki.archlinux.org/title/Fcitx5
https://fcitx-im.org/wiki/Setup_Fcitx_5
for how to set it.

You're possibly just using gtk's text-input-v3 and sway's zwp_input_method_v2 to type, which doesn't support input popup surface.
https://github.com/swaywm/sway/pull/5890

**Comment by wengxt** [comment]
though, I do find a [bug](https://github.com/fcitx/fcitx5/commit/6ad3aa04476470200ceb1a5f5ce0c2441a240899) (which does not exactly match your description) and ask arch maintainer to update, you might want to check it out.
