### ISSUE TITLE
dingtalk not able to switch Chinese IME

### ISSUE THREAD

**Issue by cetsupport** [fcitx/fcitx5#509]
**Describe the bug**

Not able to input Chinese in dingtalk (official release from dingtalk homepage).

**To Reproduce**
1. Open dintalk app
2. Try to switch Chinese input mode and type Chinese.

**Expected behavior**
Be able input Chinese.

**Desktop (please complete the following information):**
 - Desktop: (KDE, GNOME, etc)
 Gnome 3.
 - Display server type: X11, Wayland
 Wayland
 - The output of fcitx5-diagnose if possible.

# System Info:
1.  `uname -a`:

        Linux eeeaaa 5.15.0-35-generic #36-Ubuntu SMP Sat May 21 02:24:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu 22.04 LTS
        Release:	22.04
        Codename:	jammy

3.  `lsb_release -d`:

        Description:	Ubuntu 22.04 LTS

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=22.04
        DISTRIB_CODENAME=jammy
        DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"

5.  `/etc/os-release`:

        PRETTY_NAME="Ubuntu 22.04 LTS"
        NAME="Ubuntu"
        VERSION_ID="22.04"
        VERSION="22.04 LTS (Jammy Jellyfish)"
        VERSION_CODENAME=jammy
        ID=ubuntu
        ID_LIKE=debian
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        UBUNTU_CODENAME=jammy

6.  Desktop Environment:

    Desktop environment is `gnome3`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

8.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY='wayland-0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IL
            en_IL.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            POSIX
            zh_CN
            zh_CN.gb18030
            zh_CN.gb2312
            zh_CN.gbk
            zh_CN.utf8
            zh_SG.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LANGUAGE=en_US:en
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC=zh_CN.UTF-8
            LC_TIME=zh_CN.UTF-8
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY=zh_CN.UTF-8
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER=zh_CN.UTF-8
            LC_NAME=zh_CN.UTF-8
            LC_ADDRESS=zh_CN.UTF-8
            LC_TELEPHONE=zh_CN.UTF-8
            LC_MEASUREMENT=zh_CN.UTF-8
            LC_IDENTIFICATION=zh_CN.UTF-8
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/eeeaaa

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/eeeaaa/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/eeeaaa/.config/fcitx5`).

5.  Current user:

    The script is run as eeeaaa (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.14`

3.  process:

    Found 1 fcitx5 process:

           2501 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.81`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `2501`.

    Debug information from dbus:

           Group [x11::0] has 4 InputContext(s)
          IC [df29e4d77dd848399aab517b7dffc377] program:google-chrome-stable frontend:dbus cap:6000000012 focus:0
          IC [80813e8174f141838425755179c6f419] program:google-chrome-stable frontend:dbus cap:6000000012 focus:0
          IC [46ae96ac581c472a93d74183c758565d] program:snap-store frontend:fcitx4 cap:1000012 focus:0
          IC [e94c270c8f3648c2b1198425dae9ff36] program:ulauncher frontend:dbus cap:6000000012 focus:0
        Group [wayland:] has 3 InputContext(s)
          IC [be309be8148d4ba18210630e3b3d629c] program:gnome-terminal-server frontend:dbus cap:e001000012 focus:1
          IC [b23ec62ab5334c928a58cbf47dc0c288] program: frontend:ibus cap:52 focus:0
          IC [1ec3332cb77c4b2a82e0341cd9ffca8e] program: frontend:ibus cap:5a focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    Found fcitx5 kcm module.

        kcm_fcitx5       - Configure Input Method

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for qt5: `/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/lib/x86_64-linux-gnu/qt5/plugins/kcms/kcm_fcitx5.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.33` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.33

        Found fcitx5 im modules for gtk `3.24.33`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 26 enabled addons:

            Simplified and Traditional Chinese Translation 5.0.11
            Classic User Inteface 5.0.14
            Clipboard 5.0.14
            Cloud Pinyin 5.0.11
            DBus 5.0.14
            DBus Frontend 5.0.14
            Emoji 5.0.14
            Fcitx4 Frontend 5.0.14
            Full width character 5.0.11
            IBus Frontend 5.0.14
            Input method selector 5.0.14
            Keyboard 5.0.14
            KDE Input Method Panel 5.0.14
            Status Notifier 5.0.14
            Notification 5.0.14
            Pinyin 5.0.11
            Extra Pinyin functionality 5.0.11
            Punctuation 5.0.11
            Quick Phrase 5.0.14
            Spell 5.0.14
            Table 5.0.11
            Unicode 5.0.14
            Wayland 5.0.14
            Wayland Input method frontend 5.0.14
            XCB 5.0.14
            X Input Method Frontend 5.0.14

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Inteface
        KDE Input Method Panel

## Input Methods:
1.  `/home/eeeaaa/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=pinyin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=pinyin
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        2022年 06月 05日 星期日 19:26:48 CST

2.  `/home/eeeaaa/.config/fcitx5/crash.log`:

    `/home/eeeaaa/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Additional context**

**Comment by wengxt** [comment]
do you have a link ? I can't find it.

Also do you mean the windows version?

**Comment by CoelacanthusHex** [comment]
应该是说的这个页面的 https://alidocs.dingtalk.com/i/p/nb9XJlJ7QbxN8GyA/docs/ROGpvEna5YQWmaPgQ156W4ykmK3zoB27

**Comment by wengxt** [comment]
not a bug in fcitx. Also I don't have issue on arch linux's dingtalk.
