### ISSUE TITLE
fcitx only works in terminal

### ISSUE THREAD

**Issue by unusualcrow** [fcitx/fcitx5#510]
**Describe the bug**
I am unable to use fcitx in any application except for my terminal (Alacritty).

**To Reproduce**
Open Alacritty. Hit key combo. Language changes as expected.
Open any other app - Firefox, LibreOffice Writer, or Discord for example. Hit key combo. Nothing happens.

**Expected behavior**
Should be able to switch language in any application.

**Desktop (please complete the following information):**
 - Desktop: i3-gaps
 - Display server type: X11
 - Diagnose Output: https://pastebin.com/Vx0sHRTr

**Additional context**
dbus is started with "exec dbus-run-session i3" in .xinitrc
fcitx5 is started with "exec fcitx5 -d" in i3 config

**Comment by wengxt** [comment]
Just missing some package,

Install as needed ("needed" it means: whether you use gtk2, gtk3, gtk4, qt5/6 app.)

For the application that you mentioned, firefox, libreoffice, discord should be gtk3.

[fcitx5-gtk+2](https://github.com/void-linux/void-packages/tree/master/srcpkgs/fcitx5-gtk+2)
[fcitx5-gtk+3](https://github.com/void-linux/void-packages/tree/master/srcpkgs/fcitx5-gtk+3)
[fcitx5-gtk4](https://github.com/void-linux/void-packages/tree/master/srcpkgs/fcitx5-gtk4)
[fcitx5-qt5](https://github.com/void-linux/void-packages/tree/master/srcpkgs/fcitx5-qt5)
[fcitx5-qt6](https://github.com/void-linux/void-packages/tree/master/srcpkgs/fcitx5-qt6)

**Comment by unusualcrow** [comment]
Oh, I didn't know those applications ALL used GTK3. I feel silly now. Thank you for such a quick reply.

**Comment by wengxt** [comment]
libreoffice may also use qt5 if it's running under kde, it has multiple toolkit backend. I'm not sure how void linux packaged it, please double check the dependency from your package manager.

discord IMHO it's more like a specialized chrome wrapper, so that's why it's using gtk3.
