### ISSUE TITLE
Ctrl+C does not copy but clear the text in Firefox or LibreOffice

### ISSUE THREAD

**Issue by equalis3r** [fcitx/fcitx5#514]
**Describe the bug**
In Firefox or LibreOffice (maybe any gtk apps?), any text that can be editable will be cleared instead of being copied with the first Ctrl+C. Undo and Ctrl+C will copy the text.

Similarly, Ctrl+A will not work properly either.

**To Reproduce**
1. Open Firefox or LibreOffice)
2. Go to address bar on Firefox or type any text in LibreOffice
3. Select the text
4. Copy with Ctrl+C
5. Undo and Ctrl+C

**Expected behavior**
Ctrl+C should 

**Desktop (please complete the following information):**
 - Desktop: swaywm
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.
 
<details>
<summary>
Output of fcitx5-diagnose
</summary>
# System Info:

1.  `uname -a`:

        Linux t14s 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

6.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

7.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux-logo

8.  Desktop Environment:

    Cannot determine desktop environment.

9.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

10.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY='wayland-1'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an XWayland server
            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.UTF-8
            POSIX
            en_US.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE=C
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/equalis3r

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/equalis3r/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/equalis3r/.config/fcitx5`).

5.  Current user:

    The script is run as equalis3r (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.17`

3.  process:

    Found 1 fcitx5 process:

          20684 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.41`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `20684`.

    Debug information from dbus:

           Group [x11::0] has 0 InputContext(s)
        Group [wayland:] has 1 InputContext(s)
          IC [483dc061de3e4eb5afeecf9f1608ec88] program: frontend:wayland_v2 cap:100000052 focus:1
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    **Config GUI for qt not found.**

3.  Config GUI for kde:

    **`kcmshell5` not found.**

    **Cannot find a GUI config tool, please install one of `kcm-fcitx5`, or `fcitx5-config-qt`.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx5-unikey-keymap-editor.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx5-unikey-macro-editor.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.34` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0`**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.34` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 3 in cache.**

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 20 enabled addons:

            Classic User Interface 5.0.17
            Clipboard 5.0.17
            DBus 5.0.17
            DBus Frontend 5.0.17
            Emoji 5.0.17
            Fcitx4 Frontend 5.0.17
            IBus Frontend 5.0.17
            Input method selector 5.0.17
            Keyboard 5.0.17
            KDE Input Method Panel 5.0.17
            Status Notifier 5.0.17
            Notification 5.0.17
            Quick Phrase 5.0.17
            Spell 5.0.17
            Unicode 5.0.17
            Unikey Wrapper For Fcitx 5.0.10
            Wayland 5.0.17
            Wayland Input method frontend 5.0.17
            XCB 5.0.17
            X Input Method Frontend 5.0.17

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/equalis3r/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=unikey

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=unikey
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Tue Jun  7 01:19:08 PM CEST 2022

2.  `/home/equalis3r/.config/fcitx5/crash.log`:

    `/home/equalis3r/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**
</details>

**Comment by wengxt** [comment]
An immediate workaround is to use Fcitx's gtk im module instead of gtk's text-input-v3 by install fcitx5-gtk and set GTK_IM_MODULE=fcitx.

Also can you help check if the commit above fix the issue?

**Comment by equalis3r** [comment]
Thanks a lot for the quick help. The commit fixed the issue.

I did set the environment GTK_IM_MODULE=fcitx and everything worked just fine until 2-3 weeks ago.

**Comment by wengxt** [comment]
@equalis3r Ah, sorry, I mean based on your fcitx5-diagnose output, you don't seem to have fcitx5-gtk installed. The value of GTK_IM_MODULE indeed looks ok.
