### ISSUE TITLE
Fcitx5 crashes when window focus changed from LibreOffice

### ISSUE THREAD

**Issue by mekmai** [fcitx/fcitx5#515]
**Describe the bug**
Fcitx5 crashes when window focus changed from LibreOffice to another one, leaving following logs gotten by `fcitx5 -rd` .

```
I2022-06-07 21:47:20.310536 instance.cpp:1252] Override Enabled Addons: {}
I2022-06-07 21:47:20.310653 instance.cpp:1253] Override Disabled Addons: {}
I2022-06-07 21:47:20.325022 addonmanager.cpp:191] Loaded addon xcb
I2022-06-07 21:47:20.329187 addonmanager.cpp:191] Loaded addon quickphrase
I2022-06-07 21:47:20.330161 addonmanager.cpp:191] Loaded addon imselector
I2022-06-07 21:47:20.337350 addonmanager.cpp:191] Loaded addon keyboard
I2022-06-07 21:47:20.340073 addonmanager.cpp:191] Loaded addon dbus
I2022-06-07 21:47:20.341560 addonmanager.cpp:191] Loaded addon dbusfrontend
I2022-06-07 21:47:20.344368 addonmanager.cpp:191] Loaded addon fcitx4frontend
I2022-06-07 21:47:20.349701 addonmanager.cpp:191] Loaded addon ibusfrontend
I2022-06-07 21:47:20.353002 addonmanager.cpp:191] Loaded addon xim
I2022-06-07 21:47:20.356572 addonmanager.cpp:191] Loaded addon wayland
I2022-06-07 21:47:20.358411 addonmanager.cpp:191] Loaded addon clipboard
I2022-06-07 21:47:20.360131 addonmanager.cpp:191] Loaded addon waylandim
I2022-06-07 21:47:20.361701 addonmanager.cpp:191] Loaded addon unicode
I2022-06-07 21:47:20.399656 inputmethodmanager.cpp:198] Found 721 input method(s) in addon keyboard
I2022-06-07 21:47:20.416234 addonmanager.cpp:191] Loaded addon kimpanel
I2022-06-07 21:47:20.439628 addonmanager.cpp:191] Loaded addon classicui
I2022-06-07 21:47:20.441633 addonmanager.cpp:191] Loaded addon notificationitem
I2022-06-07 21:47:20.443110 addonmanager.cpp:191] Loaded addon notifications
I2022-06-07 21:47:20.673830 addonmanager.cpp:191] Loaded addon mozc
I2022-06-07 21:47:20.675359 kimpanel.cpp:112] Kimpanel new owner:

E2022-06-07 21:47:47.861498 waylandmodule.cpp:158] Wayland connection got error: 32
I2022-06-07 21:47:47.866340 addonmanager.cpp:297] Unloading addon mozc
I2022-06-07 21:47:47.866585 addonmanager.cpp:297] Unloading addon notifications
I2022-06-07 21:47:47.866695 addonmanager.cpp:297] Unloading addon notificationitem
I2022-06-07 21:47:47.866857 addonmanager.cpp:297] Unloading addon classicui
I2022-06-07 21:47:47.868244 addonmanager.cpp:297] Unloading addon kimpanel
I2022-06-07 21:47:47.868301 addonmanager.cpp:297] Unloading addon unicode
I2022-06-07 21:47:47.868339 addonmanager.cpp:297] Unloading addon waylandim
I2022-06-07 21:47:47.868378 addonmanager.cpp:297] Unloading addon clipboard
I2022-06-07 21:47:47.868425 addonmanager.cpp:297] Unloading addon wayland
I2022-06-07 21:47:47.868469 addonmanager.cpp:297] Unloading addon xim
I2022-06-07 21:47:47.868574 addonmanager.cpp:297] Unloading addon ibusfrontend
I2022-06-07 21:47:47.870193 addonmanager.cpp:297] Unloading addon fcitx4frontend
I2022-06-07 21:47:47.870264 addonmanager.cpp:297] Unloading addon dbusfrontend
I2022-06-07 21:47:47.870312 addonmanager.cpp:297] Unloading addon dbus
I2022-06-07 21:47:47.870375 addonmanager.cpp:297] Unloading addon keyboard
I2022-06-07 21:47:47.870524 addonmanager.cpp:297] Unloading addon imselector
I2022-06-07 21:47:47.870555 addonmanager.cpp:297] Unloading addon quickphrase
I2022-06-07 21:47:47.870748 addonmanager.cpp:297] Unloading addon xcb
I2022-06-07 21:47:47.870774 inputcontextmanager.cpp:318] All display connections are gone, exit now.
```

The crash occured at the timing in the blank line above.

**To Reproduce**

1. Start Sway and Fcitx5
1. Open LibreOffice and focus the window
1. Change window focus from LibreOffice to another one
    - While focusing LibreOffice, input method must not be switched.
    - If switched, the crash does not occur.
1. Fcitx5 crashes

**Expected behavior**
Fcitx5 does not crash.

**Desktop (please complete the following information):**
Desktop: Sway
Display server type: Wayland

**Output of fcitx5-diagnose**

# System Info:
1.  `uname -a`:

        Linux rednote-2014 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux-logo

5.  Desktop Environment:

    Cannot determine desktop environment.

6.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='tty'

7.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=''

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            Cannot open display "default display"

    2.  `xprop`:

            xprop:  unable to open display ''

3.  Locale:

    1.  All locales:

            C
            en_US.utf8
            ja_JP.utf8
            POSIX

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/yu

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is set to `/home/yu/.config`.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/yu/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/yu/.config/fcitx5`).

5.  Current user:

    The script is run as yu (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.17`

3.  process:

    Found 1 fcitx5 process:

           4321 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.3`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `4321`.

    Debug information from dbus:

           Group [x11::0] has 3 InputContext(s)
          IC [126b8bdda18241b5aa29c6ca9ba6a5a4] program:alacritty frontend:xim cap:4000000000 focus:0
          IC [071d890e2db34210871ff16d91527b4b] program:alacritty frontend:xim cap:4000000000 focus:0
          IC [6ef4fb5b5e6a438c978b0894925cc7a5] program:chrome frontend:xim cap:4000000012 focus:0
        Group [wayland:] has 1 InputContext(s)
          IC [03a044a7bf82419c9616a7c06174c13b] program: frontend:wayland_v2 cap:52 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS is not set**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    **Cannot find xim_server on root window.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

2.  qt5 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

3.  Qt IM module files:

    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-2.0`**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.34` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0`**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.34` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 3 in cache.**

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 20 enabled addons:

            Classic User Interface 5.0.17
            Clipboard 5.0.17
            DBus 5.0.17
            DBus Frontend 5.0.17
            Emoji 5.0.17
            Fcitx4 Frontend 5.0.17
            IBus Frontend 5.0.17
            Input method selector 5.0.17
            Keyboard 5.0.17
            KDE Input Method Panel 5.0.17
            Mozc
            Status Notifier 5.0.17
            Notification 5.0.17
            Quick Phrase 5.0.17
            Spell 5.0.17
            Unicode 5.0.17
            Wayland 5.0.17
            Wayland Input method frontend 5.0.17
            XCB 5.0.17
            X Input Method Frontend 5.0.17

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/yu/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=jp
        # Default Input Method
        DefaultIM=mozc

        [Groups/0/Items/0]
        # Name
        Name=keyboard-jp
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=mozc
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Wed Jun  8 09:38:38 PM JST 2022

2.  `/home/yu/.config/fcitx5/crash.log`:

    `/home/yu/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Additional context**

```shell
$ pacman -Qi fcitx5
Name            : fcitx5
Version         : 5.0.17-2
Description     : Next generation of fcitx
Architecture    : x86_64
URL             : https://github.com/fcitx/fcitx5
Licenses        : GPL
Groups          : fcitx5-im
Provides        : None
Depends On      : cairo  enchant  iso-codes  libgl  libxkbcommon-x11  pango  systemd  wayland  wayland-protocols  xcb-imdkit  xcb-util-wm  libxkbfile  fmt  gdk-pixbuf2  unicode-cldr-annotations
Optional Deps   : None
Required By     : fcitx5-mozc  fcitx5-qt
Optional For    : None
Conflicts With  : fcitx
Replaces        : None
Installed Size  : 11.22 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Fri 03 Jun 2022 03:14:48 AM JST
Install Date    : Fri 03 Jun 2022 09:19:39 PM JST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
$ libreoffice --version
LibreOffice 7.2.7.2 20(Build:2)
$ sway --version
sway version 1.7
```

**Comment by wengxt** [comment]
Alternatively, you may use flatpak version to test.

1. install flatpak and reboot
2. Install fcitx5 master version from flatpak

```
# Add flatub repo, fcitx5-unstable also relies on some runtime packages in it.
flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
# Optionally: Add fcitx 5 unstable repo if you want to use the unstable version.
flatpak remote-add --user --if-not-exists fcitx5-unstable https://flatpak.fcitx-im.org/unstable-repo/fcitx5-unstable.flatpakrepo
flatpak install org.fcitx.Fcitx5
flatpak install org.fcitx.Fcitx5.Addon.Mozc
```

Make sure you select the version from fcitx5-unstable.

Then you can just run `org.fcitx.Fcitx5 -rd` to start the flatpak version.

You may run `flatpak remove --all` (or remove the package individually with package name) afterwards to remove all the installed flatpak package.

**Comment by mekmai** [comment]
The issue was fixed in my environment, thank you!
I tried the flatpak way and ran the exact same commands you showed.
