### ISSUE TITLE
输入';'号时,会弹出选词框"快速输入:;以;回车以;"

### ISSUE THREAD

**Issue by JustinWuCN** [fcitx/fcitx5#517]
我在五笔输入状态下,按分号键';'时,分号不会插入到文档里,而是弹出选词框,里面有一句话: "快速输入:;以;回车以;"
查了一下fcitx配置,里面有"快速输入"这一项,但是触发键是"super+;".
为什么在五笔状态下,我没有按super+;组合键,会触发出这个弹出框呢?

我使用的是archlinux 系统

**Comment by wengxt** [comment]
五笔配置里有针对五笔的快速输入按键

快速输入自己配置里的是全局的

**Comment by JustinWuCN** [comment]
谢谢,我找到了,原来是每种输入法都有一个快速输入的快捷键,默认的快捷键就是分号.
我现在把这个快捷键去掉就可以正常输入";"了.
