### ISSUE TITLE
如何在仅需要输入英文的时候关闭fcitx 5的激活状态

### ISSUE THREAD

**Issue by twinfishxixi** [fcitx/fcitx5#525]
系统是`Ubuntu 20.04`，通过`flatpak`安装好了`fcitx 5`，发现一个`fcitx 4`上已经解决的旧问题又出现了，即无法直接输入英文，虽然通过`Ctrl+空格`可以将中文输入法切换到英文输入法，但`fcitx 5`始终会显示输入英文选择框，导致终端输入命令或者密码的时候都会显示出来，既尴尬又非常不便，如何可以直接在有需求的程序输入界面将`fcitx 5`关闭激活呢，相当于直接调用键盘的输入。

按说`Ctrl+空格`应该是`启用/禁用`输入法之间切换，貌似没有起到作用呢。
还有就是在`全局设置`处有`激活`、`取消激活`，从实际效果来看相当于增设了一个快速输入切换代替`Ctrl+空格`的功能，不过从`fcitx 4`时代开始，这一直是我个人比较迷惑的地方，因为始终觉得这两个功能是重复的吧，不过不知道是否可以这么理解：
`Ctrl+空格`相当于是`fcitx`的一个总开关，打开之后就可以启用和选用各种输入法，而`激活`、`取消激活`（我设置的是`左Shift`）则是在输入过程中的一个二级开关，输入动作仍旧是受`fcitx`管理的，`fcitx`实际上一直在后台保持运行，当按下`左Shift`后就关闭了汉字输入法，将键盘输入的字符直接传输给`fcitx`并传给系统了。（不懂输入法设计的结构哈，就是我个人的理解……）

之前`fcitx 4`时代的问题链接：[ 英文输入时出现下拉菜单和候选词，想知道如何关闭这个功能 #161 ](https://github.com/fcitx/fcitx/issues/161)

**Comment by rocka** [comment]
想要输入英文的时候不显示候选词，在键盘设置里关闭 enable hint by default 即可

![image](https://user-images.githubusercontent.com/13914967/174260103-4c12a98b-8c92-4a8d-a4df-0967ee6b3df6.png)

**Comment by twinfishxixi** [comment]
挺奇怪，之前我也关闭了的，但一直还是有提示框，刚才又重新按您的方法操作了一遍，并且把`选词修饰键`选为`无`再测试就正常了，不知道问题出在哪里，哈哈！～

**Comment by wengxt** [comment]
切换的快捷键是 ctlr alt h (只提示一次是 ctrl + alt + j)
