### ISSUE TITLE
fcitx5无法在mendeley中输入

### ISSUE THREAD

**Issue by realasking** [fcitx/fcitx5#53]
大家好。这两天又尝试了一下fcitx5，没有其它什么毛病了，就是不能在mendeley（1.19.5）中输入。
我的系统是manjaro，qt版本是5.14.2，而mendeley自带的qt版本是5.10.1。
我尝试编译fcitx5-qt，但发现需要安装5.10.1的qt；
编译该版本的qt时，发现gcc 9.3无法产生其需要的qmake；
因而没法获得mendeley所需的libfcitxplatforminputcontextplugin.so文件，
而fcitx的该文件拷贝过去没有用了。
请问有没有什么解决办法？

**Comment by wengxt** [comment]
安装不 bundle qt 的或者 https://aur.archlinux.org/packages/mendeleydesktop-bundled-fcitx/

**Comment by realasking** [comment]
> 安装不 bundle qt 的或者 https://aur.archlinux.org/packages/mendeleydesktop-bundled-fcitx/

您好。不bundle qt的早就不能用了啊，安装不bundle qt的mendeley会提示symbol查找错误，然后就段错误退出的。您放那个包也是针对fcitx的，fcitx5用它就是没有用啊。我想迁移到fcitx5上，但是没有办法让它能在mendeley上输入。

**Comment by wengxt** [comment]
但反正不是 fcitx 的 bug 啊。
你不如试试用 ibus immodule不知道 mendeley 有没有带
或者建议 blog 作者编译一个最新版的 fcitx-qt5 / fcitx5-qt 都能同时给 fcitx4 / 5 用

**Comment by realasking** [comment]
> 但反正不是 fcitx 的 bug 啊。
> 你不如试试用 ibus immodule不知道 mendeley 有没有带
> 或者建议 blog 作者编译一个最新版的 fcitx-qt5 / fcitx5-qt 都能同时给 fcitx4 / 5 用

嗯，谢谢。看来和fcitx5无缘了，ibus能正常使用。
