### ISSUE TITLE
拼音输入有几率漏掉字母

### ISSUE THREAD

**Issue by ChenKe404** [fcitx/fcitx5#531]
如题，特别是刚开机或者电脑稍微有点卡顿的时候最明显
fcitx5版本5.0.16
OS:ubuntu 20.04
安装方式: 源码编译安装
libfcitx5platforminputcontextplugin动态库qt5和qt6都有

另外一台Arch linux并使用pacman安装的相同版本fcitx5也存在相同问题，不过只有打字太快的情况下有几率出现

**Comment by wengxt** [comment]
感觉是 chrome 没有配置 gtk im module。建议通过 fcitx5-diagnose 检查环境变量配置
