### ISSUE TITLE
怎么设置pinyin可以用空格选中第一个词?

### ISSUE THREAD

**Issue by ganghuang** [fcitx/fcitx5#534]
几乎所有其他输入法都习惯了用空格选中第一个词,如果用回车就当作英文输入。
但是安装fcitx5-pinyin之后，发现只能用数字键选第一个词。
按空格就切换回英文了，并且把刚输入的拼音也当作英文输入了
系统是刚安装的debian 11
试了bullseye里面的5.0.4-1 和bookworm里面的5.0.13-1版本
在terminal和firefox里面的表现是一致的
请问怎么设置pinyin可以用空格选中第一个词?
谢谢

**Comment by wengxt** [comment]
看起来像是 space 被判断成了 ctrl space

你是什么桌面？是 wayland 吗？早几个版本的情况我已经记不太清了，但有可能在 sway 上的 native client 有 ctrl 状态之类的问题？

你在用 im module 吗？

fcitx5-diagnose 输出贴一份

**Comment by wengxt** [comment]
Close for now. There were some modifier key related fcitx for native wayland / layout translation. Please open a new one if you still have problem.
