### ISSUE TITLE
Fcitx5 在 i3wm 下显示托盘图标有一个黑框。

### ISSUE THREAD

**Issue by aeghn** [fcitx/fcitx5#54]
# 环境变量
export QT_QPA_PLATFORMTHEME=qt5ct
export XDG_CURRENT_DESKTOP=gnome 

# fcitx 版本
$ fcitx5 --version
4.99.0

# i3wm version
$ i3 --version
i3 version 4.18.1 (2020-04-23) © 2009 Michael Stapelberg and contributors

# i3bar version
$ i3bar --versionl
i3bar version 4.18.1 (2020-04-23) © 2010 Axel Wagner and contributors

尝试过重启电脑和 fcitx， 黑边均没有消失。

另外 fcitx5 不会随图标主题改变（通过 qt5ct 修改图标主题）。
下图中为 papirus 主题。

![p-200509_092135](https://user-images.githubusercontent.com/51843252/81460223-87776880-91d6-11ea-8f3f-b080975cede2.png)
![p-200509_092148](https://user-images.githubusercontent.com/51843252/81460224-88a89580-91d6-11ea-8129-515e57ed6289.png)

**Comment by roachsinai** [comment]
fcitx在xfce上也是自己的图标。使用微风，papirus图标也没有变化。

**Comment by aeghn** [comment]
我还以为只有 i3WM 有不能更换 tray 图标的这个问题。

不过问题 #55 ，你发得图片中 tray 里不是默认图标啊。

**Comment by roachsinai** [comment]
本来是KDE，安装了XFCE之后在xfce里面就是这样了...

**Comment by wengxt** [comment]
https://github.com/fcitx/fcitx5/issues/57 关于用图标主题的问题
