### ISSUE TITLE
unable to switch to japanese IME in firefox

### ISSUE THREAD

**Issue by panjidinata** [fcitx/fcitx5#541]
**Describe the bug**
Unable to switch to japanese IME in firefox

**To Reproduce**
1. Open firefox
2. Switch to japanese(Mozc)

**Expected behavior**
IME switch from US to Japanese, and able to input in japanese.

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: X11
 
# System Info:
1.  `uname -a`:

        Linux mylepi 5.18.10-artix1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Jul 2022 07:26:22 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	Artix
        Description:	Artix Linux
        Release:	rolling
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	Artix Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="Artix"
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="Artix Linux"

5.  `/etc/os-release`:

        NAME="Artix Linux"
        PRETTY_NAME="Artix Linux"
        ID=artix
        BUILD_ID=rolling
        ANSI_COLOR="0;36"
        HOME_URL="https://www.artixlinux.org/"
        DOCUMENTATION_URL="https://wiki.artixlinux.org/"
        SUPPORT_URL="https://forum.artixlinux.org/"
        BUG_REPORT_URL="https://bugs.artixlinux.org/"
        LOGO=artixlinux
        VERSION_ID=20220123
        VARIANT=plasma-openrc

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc104", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.UTF-8
            en_US.utf8
            id_ID.utf8
            POSIX

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC=id_ID.UTF-8
            LC_TIME=id_ID.UTF-8
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY=id_ID.UTF-8
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER=id_ID.UTF-8
            LC_NAME=id_ID.UTF-8
            LC_ADDRESS=id_ID.UTF-8
            LC_TELEPHONE=id_ID.UTF-8
            LC_MEASUREMENT=id_ID.UTF-8
            LC_IDENTIFICATION=id_ID.UTF-8
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/panjidinata

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/panjidinata/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/panjidinata/.config/fcitx5`).

5.  Current user:

    The script is run as panjidinata (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.18`

3.  process:

    Found 1 fcitx5 process:

         2955 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.41`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `2955`.

    Debug information from dbus:

           Group [x11::0] has 3 InputContext(s)
          IC [b1681167c5f440e9996f09d11acb44fa] program:plasmashell frontend:dbus cap:6000800072 focus:0
          IC [62d4ca6e19ab4498a36861f53cdc5aa9] program:plasmashell frontend:dbus cap:6000800072 focus:0
          IC [2650591b2c70408e8dda30d43550c323] program:plasmashell frontend:dbus cap:6800800072 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    **Config GUI for qt not found.**

3.  Config GUI for kde:

    **Cannot find a GUI config tool, please install one of `kcm-fcitx5`, or `fcitx5-config-qt`.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM for Emacs:

    **Your LC_CTYPE is set to en_US.UTF-8 instead of one of zh, ja, ko. You may not be able to use input method in emacs because of an really old emacs bug that upstream refuse to fix for years.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-2.0`**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.34` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0`**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.34` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 3 in cache.**

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 20 enabled addons:

            Classic User Interface 5.0.18
            Clipboard 5.0.18
            DBus 5.0.18
            DBus Frontend 5.0.18
            Emoji 5.0.18
            Fcitx4 Frontend 5.0.18
            IBus Frontend 5.0.18
            Input method selector 5.0.18
            Keyboard 5.0.18
            KDE Input Method Panel 5.0.18
            Mozc 
            Status Notifier 5.0.18
            Notification 5.0.18
            Quick Phrase 5.0.18
            Spell 5.0.18
            Unicode 5.0.18
            Wayland 5.0.18
            Wayland Input method frontend 5.0.18
            XCB 5.0.18
            X Input Method Frontend 5.0.18

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/panjidinata/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=mozc

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=mozc
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Rab 13 Jul 2022 05:54:32  WITA

2.  `/home/panjidinata/.config/fcitx5/crash.log`:

    `/home/panjidinata/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Additional context**
Firefox version: 102.0.1

**Comment by wengxt** [comment]
The Gtk section in the diagnose shows you didn't have fcitx5-gtk installed. Otherwise environment variable are set correctly.

Please check if install fcitx5-gtk (and restart firefox) can fix your issue.
