### ISSUE TITLE
自定义热键

### ISSUE THREAD

**Issue by ercao** [fcitx/fcitx5#543]
**Describe the bug**
是否有一种方式可以自定义 某些行为的热键
比如 输入中文时的退格键、输入中文时的 ESC键

**Expected behavior**

比如 
当输入 `Ctrl + [` 会退出这个框(不是disactive fcitx5) (代替`ESC`) 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/51725284/179134397-eb0220c6-96b3-4790-a645-f9a09196ba75.png">

当输入 `Ctrl + H` 删除这里的字符(代替`BackSpace`键)
<img width="316" alt="image" src="https://user-images.githubusercontent.com/51725284/179134135-cabb9443-6c0f-4de1-a5c2-a7a986fb1d1b.png">

**Desktop (please complete the following information):**
 - Desktop: none+xmonad
 - Display server type: X11

**Comment by wengxt** [comment]
我可以提供一些思路
你可以实现一个 addon 干这个。首先在 pre input method 阶段拦截你想要的按键，然后创建一个假的 key event 塞进去。

但我对fcitx内置实现这样的功能不感兴趣，所以close。

如果你自己实现有任何问题可以到
https://github.com/fcitx/fcitx5/discussions
提问。

关于如何写一个 addon 的框架代码可以参考 https://fcitx-im.org/wiki/Develop_an_simple_input_method
