### ISSUE TITLE
fcitx5 loaded but not working (dbus)

### ISSUE THREAD

**Issue by coolmule0** [fcitx/fcitx5#546]
**Describe the bug**

Unable to use fcitx5 (and mozc addon). Tray icon appears, but cannot be interacted with (no windows pop-up interacting with it. Cannot change languages or use at all. No way to interact graphically with fcitx5

**To Reproduce**
Start fcitx5 through KDE autostart on login. Unable to access fcitx5-related activities on any type of window

**Expected behavior**
Be able to change languages, be able to access fcitx5 specific windows and configurations.

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: X11

fxitx5-diagnose hints that it could be dbus:
[fcitx5-diag.txt](https://github.com/fcitx/fcitx5/files/9125951/fcitx5-diag.txt)

and starting fctix5 manually: 
[fcitx5-log.txt](https://github.com/fcitx/fcitx5/files/9125956/fcitx5-log.txt)

**Comment by wengxt** [comment]
Why keyboard addon is disabled? It's a dependency of dbus addon, which breaks all the dbus related functionality. I guess I'd better give a better warning when you might disable dbus addon in configtool

    2.  Found 1 disabled addons:

            Keyboard 5.0.18

If you don't know how to restore it, just delete ~/.config/fcitx5/config
