### ISSUE TITLE
如何导入和导出用户词表和词频记录

### ISSUE THREAD

**Issue by QiangF** [fcitx/fcitx5#552]
无论预设词库多大，用户自己的词库不可或缺，如人名、行业特有的词等。rime有个命令支持导出和导入用户词表和词频记录（custom_phrase.txt, pinyin_simp.userdb），并且custom_phrase.txt可以编辑的。fcitx5 的 user.dict user.history 的导出和导入命令是什么呢？

**Comment by wengxt** [comment]
导入

![图片](https://user-images.githubusercontent.com/259684/180905834-cad1e8bb-0d37-4c92-8633-e5ee3de161fb.png)

**Comment by QiangF** [comment]
哦，明白了，导出用

    Usage: libime_pinyindict [-d] <source> <dest>
    -d: Dump binary to text
    -h: Show this help

**Comment by QiangF** [comment]
如果只提供一个词语列表，没有拼音和词频，词库怎么转换呀

    libime_pinyindict contacts.txt contacts.dict

**Comment by wengxt** [comment]
> 如果提供一个从词语列表，没有拼音和词频，转换成词库的方法就更好了
> 
> ```
> libime_pinyindict contacts.txt contacts.dict
> ```

因为有多音字，读音是必须的。

词频大部分情况也不在词库里，不需要管
