### ISSUE TITLE
Reload fcitx5 doesn't reload dict file in user dir

### ISSUE THREAD

**Issue by QiangF** [fcitx/fcitx5#553]
I use "fcitx5-remote -r" to reload, but the newly added dict file is not reloaded.

    libime_pinyindict contacts.txt ~/.local/share/fcitx5/pinyin/dictionaries/contacts.dict

I tried to restart fcitx5, but that operation freezes the xserver, and I need to force shut down the system. Rebooting loads the new dict successfully.

**Comment by wengxt** [comment]
reload config in fcitx5-remote is pretty useless because it only reload the global config

```
qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.ReloadAddonConfig pinyin
```

**Comment by QiangF** [comment]
I have tried to add a new word, reconverted the dict file, and run your command, still the dict is not reloaded, I couldn't type the word. BTW, what's the dbus-send alternative, I have tried this:

    dbus-send --session --print-reply --dest org.fcitx.Fcitx5 --type string /controller/org.fcitx.Fcitx.Controller1.ReloadAddonConfig pinyin

**Comment by wengxt** [comment]
ah, I remembered that you Reload pinyin addon config doesn't reload dictionary.
```
qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.SetConfig fcitx://config/addon/pinyin/dictmanager 0
```

This should work for reloading dictionary.

**Comment by QiangF** [comment]
Work perfect! But reloading dict is slow. Sometimes I just need to add a single word from emacs buffer and use immediately, is there a way to add the word to "user.dict" via dbus interface?

   dbus-command "词语" "ci'yu"

I used to do that with an input method called pyim in emacs.

**Comment by wengxt** [comment]
No.

PRs are welcome.
