### ISSUE TITLE
Feature request: support multiple candidate in quickphrase

### ISSUE THREAD

**Issue by QiangF** [fcitx/fcitx5#554]
Looks like the current quickphrase is one to one. Rime has a symbol feature that is one to many, for example, type jt (箭头）, and you will get a list of arrows to select from.

    jt ↑ ↓ ← → ↕ ↔ ↖ ↗ ↙ ↘ 

In latex.mb there are a ton of symbols, it is very hard to remember their names, but it is easy to remember their category, like the 箭头 in my above example.  One code to multiple candidates is very convenient.

Is there a replacement for that feature?
[symbols.txt](https://github.com/fcitx/fcitx5/files/9188367/symbols.txt)

**Comment by rocka** [comment]
quickphrase is not one-to-one, you can bind multiple phrase to one keyword. So you can write your own .mb file and map all kinds of arrows to "jt".

As for latex, it's just standard latex symbol map, can be convenient if you are familiar with it.

There is a similar symbol selector feature in fcitx5-chinese-addons, which requires fcitx5-lua
https://github.com/fcitx/fcitx5-chinese-addons/blob/9466a5a32942be461c1264097b1733571ed70f0f/im/pinyin/pinyin.lua
enter quickphrase mode when pinyin input method is active, and type "fh", then you can choose category and then symbols.
