### ISSUE TITLE
在 ubuntu 22.04 树莓派版本下 fcitx5 无法在 firefox (snap)、chromium (snap) 中显示候选栏

### ISSUE THREAD

**Issue by sysserkl** [fcitx/fcitx5#555]
**Describe the bug**
在 ubuntu 22.04 树莓派版本下 fcitx5 无法在 firefox (snap)、chromium (snap) 中显示候选栏

**To Reproduce**
fcitx5 在 geany、LibreOffice 能正常使用，可以显示候选栏。
但在 firefox 中无法显示候选栏，可以输入汉字，但只能靠瞎蒙选择字词。chromium 也同样情况。是因为 snap 的原因吗？

**Desktop**
硬件：树莓派4B
操作系统：Ubuntu 22.04 64位
桌面：xfce4

**Comment by wengxt** [comment]
请在 firefox 和chromium 正在运行的情况下运行一下 fcitx5-diagnose

曾经在虚拟机里测试过 firefox 和 22.04 没发现什么问题

**Comment by sysserkl** [comment]
fcitx5-diagnose
# System Info:
1.  `uname -a`:

        Linux pi-4b 5.15.0-1012-raspi #14-Ubuntu SMP PREEMPT Fri Jun 24 13:10:28 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu 22.04 LTS
        Release:	22.04
        Codename:	jammy

3.  `lsb_release -d`:

        Description:	Ubuntu 22.04 LTS

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=22.04
        DISTRIB_CODENAME=jammy
        DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"

5.  `/etc/os-release`:

        PRETTY_NAME="Ubuntu 22.04 LTS"
        NAME="Ubuntu"
        VERSION_ID="22.04"
        VERSION="22.04 LTS (Jammy Jellyfish)"
        VERSION_CODENAME=jammy
        ID=ubuntu
        ID_LIKE=debian
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        UBUNTU_CODENAME=jammy

6.  Desktop Environment:

    Desktop environment is `xfce`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0.0'


        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IL
            en_IL.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            POSIX
            zh_CN.utf8
            zh_SG.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LANGUAGE=en_US
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC=zh_CN.UTF-8
            LC_TIME=zh_CN.UTF-8
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY=zh_CN.UTF-8
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER=zh_CN.UTF-8
            LC_NAME=zh_CN.UTF-8
            LC_ADDRESS=zh_CN.UTF-8
            LC_TELEPHONE=zh_CN.UTF-8
            LC_MEASUREMENT=zh_CN.UTF-8
            LC_IDENTIFICATION=zh_CN.UTF-8
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/pi

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/pi/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/pi/.config/fcitx5`).

5.  Current user:

    The script is run as pi (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.14`

3.  process:

    Found 1 fcitx5 process:

           1628 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.15`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `1628`.

    Debug information from dbus:

           Input Context without group
          IC [f272d2a585774f8faa355b802f5a36d0] program:wrapper-2.0 frontend:dbus focus:0
          IC [ab6c481eb8684343ad101ddd2fb5ae74] program:firefox frontend:fcitx4 focus:0
          IC [526d640298eb4ecf9c50e4c8ab67b123] program:firefox frontend:fcitx4 focus:0
          IC [23c000cc45a741b2a4dfb2a08aae6c33] program:firefox frontend:fcitx4 focus:0
          IC [763bb50a110841ca80f64c73564add86] program:firefox frontend:fcitx4 focus:0
          IC [2cd3adf4e02b450aac9213da77ec980a] program:chrome frontend:fcitx4 focus:0
          IC [15cb9a6a48664ac2b9913f41539c0435] program:xfce4-terminal frontend:dbus focus:1

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    **Cannot find xim_server on root window.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 qt5 module: `/lib/aarch64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found unknown fcitx qt module: `/lib/aarch64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    Found fcitx5 im module for qt5: `/lib/aarch64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/lib/aarch64-linux-gnu/fcitx/qt/libfcitx-quickphrase-editor5.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/lib/aarch64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/aarch64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/aarch64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.33` at `/lib/aarch64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/aarch64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.33

        Found fcitx5 im modules for gtk `3.24.33`.

            "/usr/lib/aarch64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 18 enabled addons:

            Classic User Inteface 5.0.14
            Clipboard 5.0.14
            Cloud Pinyin 5.0.11
            DBus 5.0.14
            DBus Frontend 5.0.14
            Fcitx4 Frontend 5.0.14
            IBus Frontend 5.0.14
            Input method selector 5.0.14
            Keyboard 5.0.14
            KDE Input Method Panel 5.0.14
            Status Notifier 5.0.14
            Notification 5.0.14
            Pinyin 5.0.11
            Extra Pinyin functionality 5.0.11
            Punctuation 5.0.11
            Spell 5.0.14
            Table 5.0.11
            Unicode 5.0.14

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Inteface
        KDE Input Method Panel

## Input Methods:
1.  `/home/pi/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=pinyin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=pinyin
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        2022年 07月 27日 星期三 10:45:39 CST

2.  `/home/pi/.config/fcitx5/crash.log`:

    `/home/pi/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by wengxt** [comment]
你缺少了一些对应的包 fcitx5-module-xorg 

建议安装时不要用 --no-recommends 否则安装得到一些缺少功能的结果是很正常的。
