### ISSUE TITLE
全局为Neo2时，阿拉伯语布局捕捉不到撤回快捷键（ctrl+z）

### ISSUE THREAD

**Issue by yue-dongchen** [fcitx/fcitx5#557]
**Describe the bug**
全局为Neo2时，阿拉伯语（所有`لا`键与Neo2的`z`键重合的布局）捕捉不到control+z。 该快捷键在全局为QWERTY下正常。
QWERTY的`z`键对应阿拉伯的`ئ`，Neo2的对应`لا`（该键代表两个符号：ل与ا）

**To Reproduce**
1. 进入任何文本编辑器（例如LibreOffice）
2. 键入一些内容
3. 按下control+z快捷键

**Expected behavior**
撤回

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland

**Comment by wengxt** [comment]
预期中的行为，ctrl z 的位置是根据全局的 z 的位置决定的。

如果你想要你说的那种方式，你可以换一种配置方式，创建一个分组，把阿拉伯语键盘作为那个分组的全局。

**Comment by yue-dongchen** [comment]
可能我没表达清楚。我指的就是Neo2全局的control z - 阿拉伯语键盘下会遗漏。control c, v, p等都没问题

**Comment by wengxt** [comment]
neo 2 我搜了一下是德语键盘吧？是不是 qwertz ？所以你以为你在按阿拉伯语的 qwerty 的 ctrl z ，实际是 ctrl y

你具体配置的是什么样的

**Comment by yue-dongchen** [comment]
对。不过不是传统德语QWERTZ。Neo2的z在QWERTY的b的位置上。我按的对应的就是control+b
https://upload.wikimedia.org/wikipedia/commons/4/4f/Neo2_keyboard_layout.svg

**Comment by wengxt** [comment]
对，所以你阿拉伯语也是 ctrl + b。

如果布局不是全局的话，对于不产生符号的按键，程序看见的永远是全局的那个布局的。也就是程序一样认为你在 ctrl b

特意这么设计的，避免切换布局快捷键位置就变了

**Comment by yue-dongchen** [comment]
对。rime下control+b正常撤回，但阿拉伯键盘会键入b对应的键

**Comment by yue-dongchen** [comment]
因为阿拉伯语b键产生两个符号

**Comment by yue-dongchen** [comment]
https://thumbs.dreamstime.com/b/arabic-computer-keyboard-arabic-computer-keyboard-isolated-transparent-background-113530404.jpg
阿拉伯键盘

**Comment by wengxt** [comment]
> 对。rime下control+b正常撤回，但阿拉伯键盘会键入b对应的键

我的意思是，你按 control + （neo 的那个 z 的位置） ，能撤回吗

**Comment by yue-dongchen** [comment]
不行，会产生لا

**Comment by wengxt** [comment]
Fixed by 
https://github.com/fcitx/fcitx5/commit/bd797044f27e75fe964ed412e6b21628a66f780c
