### ISSUE TITLE
[feature request] Freedesktop color-scheme support

### ISSUE THREAD

**Issue by tinywrkb** [fcitx/fcitx5#562]
Documentation is under the [Settings Portal section](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings).

Requirements:

* gsettings-desktop-schemas>=42.0
* xdg-desktop-portal>=1.12.0
* One of the supporting Settings Portal implementation
    * KDE Plasma>=5.24
    * Gnome>=42.0
    * [darkman](https://gitlab.com/WhyNotHugo/darkman)

Might want first to switch to Qt6 as [this is in 6.3.0](https://invent.kde.org/qt/qt/qtbase/-/commit/3c6b61a6e14962969e7e9dc5909cd746e38f8de7), but if Qt6 still doesn't subscribe to the `SettingChanged` signal, then maybe be better to implement this in Fcitx.

**Comment by wengxt** [comment]
I think it's a good idea because default theme can be adapted to use the system color.

Though I don't see why it need qt6 anyway. Fcitx doesn't use qt.

**Comment by tinywrkb** [comment]
> Though I don't see why it need qt6 anyway. Fcitx doesn't use qt.

Oh, right! I was thinking about config tool.
