### ISSUE TITLE
“fcitx5-remote -t” doesn't toggle input method in firefox-esr (on archlinux)

### ISSUE THREAD

**Issue by QiangF** [fcitx/fcitx5#569]
Set the keybinding in fcitx5-config is not an option, because I need to put that in a script.
1. bind "fcitx5-remote -t" to a hot key in your window manager
2. open firefox
3. type the hotkey in step one

 - Desktop: i3wm
 - Display server type: X11
 - The output of fcitx5-diagnose:
  
    # System Info:
    1.  `uname -a`:

            Linux mypc 5.15.41-1-lts #1 SMP Wed, 18 May 2022 13:37:06 +0000 x86_64 GNU/Linux

    2.  `lsb_release -a`:

            LSB Version:	n/a
            Distributor ID:	Arch
            Description:	Arch Linux
            Release:	rolling
            Codename:	n/a

    3.  `lsb_release -d`:

            Description:	Arch Linux

    4.  `/etc/lsb-release`:

            DISTRIB_ID="Arch"
            DISTRIB_RELEASE="rolling"
            DISTRIB_DESCRIPTION="Arch Linux"

    5.  `/etc/os-release`:

            NAME="Arch Linux"
            PRETTY_NAME="Arch Linux"
            ID=arch
            BUILD_ID=rolling
            ANSI_COLOR="38;2;23;147;209"
            HOME_URL="https://archlinux.org/"
            DOCUMENTATION_URL="https://wiki.archlinux.org/"
            SUPPORT_URL="https://bbs.archlinux.org/"
            BUG_REPORT_URL="https://bugs.archlinux.org/"
            LOGO=archlinux-logo

    6.  Desktop Environment:

        Cannot determine desktop environment.

    7.  XDG SESSION TYPE:

            XDG_SESSION_TYPE='x11'

    8.  Bash Version:

            BASH_VERSION='5.1.16(1)-release'

    # Environment:
    1.  DISPLAY:

            DISPLAY=':0'

            WAYLAND_DISPLAY=''

    2.  Keyboard Layout:

        1.  `setxkbmap`:

                xkb_keymap {
                    xkb_keycodes  { include "evdev+aliases(qwerty)"	};
                    xkb_types     { include "complete"	};
                    xkb_compat    { include "complete"	};
                    xkb_symbols   { include "pc+us+inet(evdev)"	};
                    xkb_geometry  { include "pc(pc105)"	};
                };

        2.  `xprop`:

                _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

    3.  Locale:

        1.  All locales:

                C
                C.UTF-8
                en_US.utf8
                POSIX
                zh_CN.gb18030
                zh_CN.utf8

        2.  Current locale:

                LANG=en_US.UTF-8
                LC_CTYPE=zh_CN.UTF-8
                LC_NUMERIC=zh_CN.UTF-8
                LC_TIME=zh_CN.UTF-8
                LC_COLLATE=zh_CN.UTF-8
                LC_MONETARY=zh_CN.UTF-8
                LC_MESSAGES=en_US.UTF-8
                LC_PAPER=zh_CN.UTF-8
                LC_NAME=zh_CN.UTF-8
                LC_ADDRESS=zh_CN.UTF-8
                LC_TELEPHONE=zh_CN.UTF-8
                LC_MEASUREMENT=zh_CN.UTF-8
                LC_IDENTIFICATION=zh_CN.UTF-8
                LC_ALL=

    4.  Directories:

        1.  Home:

                /home/q

        2.  `${XDG_CONFIG_HOME}`:

            Environment variable `XDG_CONFIG_HOME` is set to `/home/q/.config`.

            Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/q/.config`).

        3.  Fcitx5 Settings Directory:

            Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/q/.config/fcitx5`).

    5.  Current user:

        The script is run as q (1000).

    # Fcitx State:
    1.  executable:

        Found fcitx5 at `/usr/bin/fcitx5`.

    2.  version:

        Fcitx version: `5.0.18`

    3.  process:

        Found 1 fcitx5 process:

                774 fcitx5

    4.  `fcitx5-remote`:

        `fcitx5-remote` works properly.

    5.  DBus interface:

        Using `dbus-send` to check dbus.

        Owner of DBus name `org.fcitx.Fcitx5` is `:1.6`.

        PID of DBus name `org.fcitx.Fcitx5` owner is `774`.

        Debug information from dbus:

               Group [x11::0] has 7 InputContext(s)
              IC [31e202a496834ef98e58a5328ccbccf5] program:firefox-esr frontend:dbus cap:6000000012 focus:0
              IC [fa01c473c45f4398baaa39e62c3158ae] program:firefox-esr frontend:dbus cap:6000000012 focus:0
              IC [65509072525c442db77f12222f0df858] program:emacs-28.1 frontend:xim cap:4000000000 focus:0
              IC [e05972654f6a416b93659168af06d4ee] program:firefox-esr frontend:dbus cap:6000000012 focus:0
              IC [f74a166589e44e31b706be435ab19ffe] program:firefox-esr frontend:dbus cap:6000000052 focus:0
              IC [d858cc79db4b4414b5c6a8d8180b4022] program: frontend:xim cap:4000000000 focus:1
              IC [6008dd36a3dd4293b37720a693141dca] program:emacs-28.1 frontend:xim cap:4000000000 focus:0
            Input Context without group

    # Fcitx Configure UI:
    1.  Config Tool Wrapper:

        Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

    2.  Config GUI for qt:

        Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

    3.  Config GUI for kde:

        **`kcmshell5` not found.**

    # Frontends setup:
    ## Xim:
    1.  `${XMODIFIERS}`:

        Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
        Xim Server Name from Environment variable is fcitx.

    2.  XIM_SERVERS on root window:

        Xim server name is the same with that set in the environment variable.

    ## Qt:
    1.  qt4 - `${QT4_IM_MODULE}`:

        Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    2.  qt5 - `${QT_IM_MODULE}`:

        Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    3.  Qt IM module files:

        Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
        Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
        Found unknown fcitx qt module: `/usr/lib/office6/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
        Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
        Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
        **Cannot find fcitx5 input method module for Qt4.**

    ## Gtk:
    1.  gtk - `${GTK_IM_MODULE}`:

        Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

    2.  `gtk-query-immodules`:

        1.  gtk 2:

            Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
            Version Line:

                # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

            Found fcitx5 im modules for gtk `2.24.33`.

                "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
                "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
                "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

        2.  gtk 3:

            Found `gtk-query-immodules` for gtk `3.24.34` at `/usr/bin/gtk-query-immodules-3.0`.
            Version Line:

                # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

            Found fcitx5 im modules for gtk `3.24.34`.

                "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
                "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
                "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  Gtk IM module cache:

        1.  gtk 2:

            Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
            Version Line:

                # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

            Found fcitx5 im modules for gtk `2.24.33`.

                "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
                "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
                "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

        2.  gtk 3:

            Found immodules cache for gtk `3.24.34` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
            Version Line:

                # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

            Found fcitx5 im modules for gtk `3.24.34`.

                "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
                "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
                "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

        3.  gtk 4:

            **Cannot find immodules cache for gtk 4**

            **Cannot find fcitx5 im module for gtk 4 in cache.**

    4.  Gtk IM module files:

        1.  gtk 2:

            All found Gtk 2 immodule files exist.

        2.  gtk 3:

            All found Gtk 3 immodule files exist.

        3.  gtk 4:

            All found Gtk 4 immodule files exist.

    # Configuration:
    ## Fcitx Addons:
    1.  Addon Config Dir:

        Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

    2.  Addon List:

        1.  Found 28 enabled addons:

                Simplified and Traditional Chinese Translation 5.0.14
                Classic User Interface 5.0.18
                Cloud Pinyin 5.0.14
                DBus 5.0.18
                DBus Frontend 5.0.18
                Emoji 5.0.18
                Fcitx4 Frontend 5.0.18
                Full width character 5.0.14
                IBus Frontend 5.0.18
                Lua IME API 5.0.9
                Input method selector 5.0.18
                Keyboard 5.0.18
                KDE Input Method Panel 5.0.18
                Lua Addon Loader 5.0.9
                Status Notifier 5.0.18
                Notification 5.0.18
                Pinyin 5.0.14
                Extra Pinyin functionality 5.0.14
                Punctuation 5.0.14
                Quick Phrase 5.0.18
                Rime 5.0.14
                Spell 5.0.18
                Table 5.0.14
                Unicode 5.0.18
                Wayland 5.0.18
                Wayland Input method frontend 5.0.18
                XCB 5.0.18
                X Input Method Frontend 5.0.18

        2.  Found 1 disabled addons:

                Clipboard 5.0.18

    3.  Addon Libraries:

        All libraries for all addons are found.

    4.  User Interface:

        Found 2 enabled user interface addons:

            Classic User Interface
            KDE Input Method Panel

    ## Input Methods:
    1.  `/home/q/.config/fcitx5/profile`:

            [Groups/0]
            # Group Name
            Name=默认
            # Layout
            Default Layout=us
            # Default Input Method
            DefaultIM=rime

            [Groups/0/Items/0]
            # Name
            Name=keyboard-us
            # Layout
            Layout=

            [Groups/0/Items/1]
            # Name
            Name=rime
            # Layout
            Layout=

            [GroupOrder]
            0=默认

    # Log:
    1.  `date`:

            2022年 08月 11日 星期四 21:12:29 CST

    2.  `/home/q/.config/fcitx5/crash.log`:

            =========================
            Fcitx 5.0.18 -- Get Signal No.: 6
            Date: try "date -d @1659016661" if you are using GNU date ***
            ProcessID: 782
            fcitx5(+0x12ccc)[0x56069ff7fccc]
            /usr/lib/libc.so.6(+0x3e8e0)[0x7f7fd7dbb8e0]
            /usr/lib/libc.so.6(+0x8e36c)[0x7f7fd7e0b36c]
            /usr/lib/libc.so.6(raise+0x18)[0x7f7fd7dbb838]
            /usr/lib/libc.so.6(abort+0xcf)[0x7f7fd7da5535]
            /usr/lib/libFcitx5Utils.so.2(+0x2976f)[0x7f7fd824f76f]
            /usr/lib/libsystemd.so.0(+0x36e7d)[0x7f7fd7c85e7d]
            /usr/lib/libsystemd.so.0(+0x4615a)[0x7f7fd7c9515a]
            /usr/lib/libsystemd.so.0(+0x4e098)[0x7f7fd7c9d098]
            /usr/lib/libsystemd.so.0(+0x799fb)[0x7f7fd7cc89fb]
            /usr/lib/libsystemd.so.0(sd_event_dispatch+0x116)[0x7f7fd7cd3056]
            /usr/lib/libsystemd.so.0(sd_event_run+0x119)[0x7f7fd7cd32d9]
            /usr/lib/libsystemd.so.0(sd_event_loop+0x60)[0x7f7fd7cd34b0]
            /usr/lib/libFcitx5Utils.so.2(_ZN5fcitx9EventLoop4execEv+0x16)[0x7f7fd8262eb6]
            /usr/lib/libFcitx5Core.so.7(_ZN5fcitx8Instance4execEv+0x57)[0x7f7fd83280c7]
            fcitx5(+0x10ee0)[0x56069ff7dee0]
            /usr/lib/libc.so.6(+0x29290)[0x7f7fd7da6290]
            /usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7f7fd7da634a]
            fcitx5(+0x122a5)[0x56069ff7f2a5]

    **Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

    **Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by wengxt** [comment]
The command only works if there's an input context has focus. Your key binding probably steal the focus away? Try add a small period of delay before the command.

**Comment by QiangF** [comment]
Problem solved. Thank you so much!
