### ISSUE TITLE
在gnome overview与app grid界面的搜索栏中输入时无法显示候选词

### ISSUE THREAD

**Issue by Corona09** [fcitx/fcitx5#573]
**Describe the bug**
在gnome overview与app grid界面的搜索栏中输入时无法显示候选词，wayland 与 xorg 环境下都存在该问题

![](https://raw.githubusercontent.com/Corona09/images/main/fcitx5-gnome-popup.png)
![](https://raw.githubusercontent.com/Corona09/images/main/fcitx5-gnome-popup-2.png)

**To Reproduce**
1. 进入 gnome 环境
2. 按下 super 键或点击左上角进入 overview 界面；或者连续按下两次 super 键进入 app grid 界面
3. 将光标聚焦到界面上方搜索栏中，切换到中文拼音输入法；
4. 输入任意中文，无法显示候选词

**Expected behavior**
输入中文后能够显示候选词，如下
![](https://raw.githubusercontent.com/Corona09/images/main/fcitx5-expected.png)

**Desktop (please complete the following information):**
 - System: fedora 36
 - Desktop: GNOME 42
 - Display server type: X11, Wayland 都存在该问题

**Comment by rocka** [comment]
https://www.csslayer.info/wordpress/fcitx-dev/fcitx5-dev-keyevent-from-app-to-fcitx/ :

> 因为 GNOME-Shell 自己它砍掉了 Gtk 的 IM Module 部分而直接采用了 IBus ，因此在 GNOME-Shell 的搜索框就必须用 Fcitx 5 才能正常输入。

想要正常显示输入法 UI ，需要使用这个： https://github.com/wengxt/gnome-shell-extension-kimpanel

**Comment by Corona09** [comment]
> https://www.csslayer.info/wordpress/fcitx-dev/fcitx5-dev-keyevent-from-app-to-fcitx/ :
> 
> > 因为 GNOME-Shell 自己它砍掉了 Gtk 的 IM Module 部分而直接采用了 IBus ，因此在 GNOME-Shell 的搜索框就必须用 Fcitx 5 才能正常输入。
> 
> 想要正常显示输入法 UI ，需要使用这个： https://github.com/wengxt/gnome-shell-extension-kimpanel

该方法可行，谢谢！
