### ISSUE TITLE
咨询：请问fcitx5可以在termux使用吗？

### ISSUE THREAD

**Issue by EdwardZhangLink** [fcitx/fcitx5#576]
我已经按照[https://github.com/termux/termux-x11](https://github.com/termux/termux-x11)里的方法在原生的termux里配置好了图形界面，但是缺少中文输入法。我现在由于知识匮乏，不清楚fcitx5能否可以在这样的环境下运行。不知是只是人们没有尝试过，还是由于技术原因根本无法实现。希望可以得到指点，万分感谢。

**Comment by wengxt** [comment]
xfce 都能跑，fcitx 没什么道理不行。

**Comment by 2096779623** [comment]
依赖有亿点多
![image](https://user-images.githubusercontent.com/57583560/186081355-f0f4d3d2-ac5e-4ea4-a60d-9a542358ec1e.png)

**Comment by EdwardZhangLink** [comment]
> 依赖有亿点多 硬编码路径多 搓个fcitx5-configtool就差把整个KDE拉下来 ![image](https://user-images.githubusercontent.com/57583560/186081355-f0f4d3d2-ac5e-4ea4-a60d-9a542358ec1e.png)

这么狠的吗？[捂脸]还是算了吧

**Comment by wengxt** [comment]
自己编译就禁用kcm，就几个qt和kf

乐意你也可以手搓配置
