### ISSUE TITLE
中文输入状态下输入英文标点

### ISSUE THREAD

**Issue by aleck099** [fcitx/fcitx5#578]
我的输入法由于不知道按到了什么键,现在中文输入状态下会输入英文标点
我在设置里无法找到相关项
怎么改回来

**Comment by rocka** [comment]
全角/标点的默认切换按键是 <kbd>Ctrl</kbd> + <kbd>.</kbd> ，在插件设置-标点里可以更改。另外在输入法托盘图标的右键菜单里也可以切换标点输入模式。

![image](https://user-images.githubusercontent.com/13914967/185787479-d9d7a76e-db93-44fd-8f40-64bcc313dbe0.png)

**Comment by aleck099** [comment]
OK! 另外方头括号（【）怎么输入

**Comment by rocka** [comment]
[默认的映射](https://github.com/fcitx/fcitx5-chinese-addons/blob/5.0.14/modules/punctuation/punc.mb.zh_CN) 不包含 【】这两个符号，但可以在 拼音输入法设置→标点 中进行修改。

**Comment by aleck099** [comment]
为什么我用的是Wubi输入法（Table），却用的是Pinyin的标点配置

**Comment by wengxt** [comment]
@aleck099 中文输入法的标点配置都是共享的

**Comment by wengxt** [comment]
哦，另外的原因是配置标点的界面是后来才有的，以前都是改配置文件，所以没做码表配置里导航到标点配置的地方

**Comment by aleck099** [comment]
标点配置目前只能从Pinyin里进入吗？有其它全局性的入口吗

**Comment by terloo** [comment]
@rocka 请问这个快捷键在哪配置呢？GUI里找不到，搜了一圈配置文件里也没找到这个Key叫什么

**Comment by rocka** [comment]
@aleck099 

> 标点配置目前只能从Pinyin里进入吗？有其它全局性的入口吗

是的，目前没有别的入口。

---

@terloo 

> 请问这个快捷键在哪配置呢？

在 配置附加组件→标点 里
![image](https://user-images.githubusercontent.com/13914967/186822996-a228db65-97a6-4997-b316-875ba77a06f7.png)
