### ISSUE TITLE
Build failed when #define CAIRO_EGL_FOUND

### ISSUE THREAD

**Issue by 12101111** [fcitx/fcitx5#58]
```
In file included from ../fcitx5-999999999/src/ui/classic/waylandeglwindow.cpp:13:
In file included from ../fcitx5-999999999/src/ui/classic/waylandeglwindow.h:16:
In file included from ../fcitx5-999999999/src/ui/classic/waylandui.h:11:
In file included from ../fcitx5-999999999/src/ui/classic/classicui.h:12:
In file included from ../fcitx5-999999999/src/lib/fcitx-config/configuration.h:10:
In file included from ../fcitx5-999999999/src/lib/fcitx-config/option.h:17:
In file included from ../fcitx5-999999999/src/lib/fcitx-config/marshallfunction.h:14:
In file included from ../fcitx5-999999999/src/lib/fcitx-utils/key.h:22:
../fcitx5-999999999/src/lib/fcitx-utils/keysym.h:23:5: error: expected identifier
    None = 0,
    ^
/usr/include/X11/X.h:115:30: note: expanded from macro 'None'
#define None                 0L /* universal null resource or null atom */
                             ^
```

include tree:
1. src/ui/classic/waylandeglwindow.cpp: 11 #include <cairo/cairo-gl.h>
2. [/usr/include/cairo/cairo-gl.h](https://github.com/freedesktop/cairo/blob/master/src/cairo-gl.h#L96) #include <GL/glx.h>
3. [/usr/include/GL/glx.h](https://github.com/NVIDIA/libglvnd/blob/master/include/GL/glx.h#L30): #include <X11/Xlib.h>
4. [/usr/include/X11/Xlib.h](https://github.com/freedesktop/xorg-libX11/blob/master/include/X11/Xlib.h#L44): #include <X11/X.h>
5. [/usr/include/X11/X.h](https://github.com/freedesktop/xorg-proto-x11proto/blob/master/X.h#L115): #define None

See also:
https://github.com/microcai/gentoo-zh/pull/592#issuecomment-627733807
https://github.com/fcitx/fcitx5/pull/52

Please note Archlinux disable cargo-gl: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/cairo

**Comment by wengxt** [comment]
err.. reference to the wrong bug number.
