### ISSUE TITLE
Debian 11 (gnome) : 只能在Terminal/Text Editor/File等自带程序中使用fcitx5-pinyin

### ISSUE THREAD

**Issue by w3ntao** [fcitx/fcitx5#580]
**Describe the bug**
Debian 11 (gnome) : 只能在Terminal/Text Editor中使用fcitx5-pinyin

**To Reproduce**
目前已知的可以输入拼音的程序：Terminal/Text Editor/File
目前已知的不能输入拼音的程序：
- firefox (91.12.0esr)
- Chrome - Version 104.0.5112.101 (Official Build) (64-bit)
- Chromium - Version 104.0.5112.101 (Official Build) built on Debian 11.4, running on Debian 11.4 (64-bit)
- Hyper 3.2.3 (stable)
- VS code - 1.70.2

**Desktop (please complete the following information):**
 - Desktop: GNOME 3.38.6
 - Display server type: Wayland
 - fcitx5-diagnose:  https://www.dropbox.com/s/6cax9b67odt3fs2/fcitx5_diagnose.txt?dl=0
 - im-config已配置为fcitx5：https://www.dropbox.com/s/b4f98nmjqxyuctu/im-config.png?dl=0

**update (Aug 22 15:38)
已经通过im-config配置为fcitx5,并且更新fcitx5-diagnose，但症状不变

**Comment by rocka** [comment]
从 diagnose 的输出来看，所有输入法相关的环境变量都设置成了 ibus ，不能输入很正常 ... 建议按照 debian 的 im-config 配置一下环境变量

https://manpages.debian.org/unstable/im-config/im-config.8.en.html

**Comment by w3ntao** [comment]
> 从 diagnose 的输出来看，所有输入法相关的环境变量都设置成了 ibus ，不能输入很正常 ... 建议按照 debian 的 im-config 配置一下环境变量
> 
> https://manpages.debian.org/unstable/im-config/im-config.8.en.html

已经通过im-config配置为fcitx5,并且更新fcitx5-diagnose，但症状不变

**Comment by rocka** [comment]
diagnose 输出显示的还是 ibus ，要不登出重新登录或者干脆重启试试？

**Comment by w3ntao** [comment]
@rocka 已经重启几次了，同样的结果。有没有可能bug出现在im-config？
https://www.dropbox.com/s/b4f98nmjqxyuctu/im-config.png?dl=0

**Comment by wengxt** [comment]
……你这个版本有点老啊……不过也有ibus frontend 了，关系应该不大？

你添加了中文输入法了吗？添加的是拼音吗？

这个命令输出什么？
dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo

**Comment by wengxt** [comment]
首先是环境变量设置的问题

`GTK_IM_MODULE=fcitx firefox` 这样启动firefox的话，能不能输入？

**Comment by hosiet** [comment]
还可以试试看下面的步骤：

* 卸载全部和 ibus 有关的软件包然后重启再试
* 检查家目录下面的 .xprofile 或者 .bashrc 或者任何类似的文件，看是否有手动设置输入法环境变量为 ibus
* 新建一个干净的用户，在新建用户下运行 `im-config` 并选中 fcitx5，然后重启在新用户下面运行 fcitx5-diagnose 看看输出

**Comment by hosiet** [comment]
另外还可以检查一下家目录下 `.xinputrc` 文件的内容，如果这里配置为 fcitx5 那么 im-config 的配置就是正确的，反则不正确。

**Comment by wengxt** [comment]
im-config 可能对 gnome3 不太好用，你可以尝试一下我以前写的针对 ubuntu 的内容

https://www.csslayer.info/wordpress/fcitx-dev/how-to-use-fcitx-on-ubuntu-17-10/

**Comment by w3ntao** [comment]
> 首先是环境变量设置的问题
> 
> `GTK_IM_MODULE=fcitx firefox` 这样启动firefox的话，能不能输入？

设置后可以在firefox里使用拼音

**Comment by w3ntao** [comment]
@hosiet 
ibus已经完全卸载：
```
$ apt list --installed | grep -w ibus
gir1.2-ibus-1.0/stable,now 1.5.23-2 amd64 [installed]
python3-ibus-1.0/stable,now 1.5.23-2 all [installed]
```
剩下的两项删了就没法用gnome


新的fcitx5-diagnose：
https://www.dropbox.com/s/e3rxmldrzqf6s0f/fcitx5_diagnose_new.txt?dl=0

```
$ cat ~/.xinputrc
# im-config(8) generated on Wed, 31 Aug 2022 08:17:38 +0800
run_im fcitx5
# im-config signature: 6950448e9d3af916ec41bb4c955ba197  -
```
看样子im-config设置正常
