### ISSUE TITLE
Plasma wayland 模式英语键盘输入bug

### ISSUE THREAD

**Issue by tony2038** [fcitx/fcitx5#599]
使用Plasma wayland模式，kde部分程序（比如，kate、Konsole）使用英语键盘输入时在光标的下方会带一个很小图形的提示，使用光标键移动光标或使用退格键删除时显得非常的卡顿。
Gnome的程序不会出现这样的情况。
切换到Plasma x11模式也不会出现这样的情况。
不知道是不是设置的问题，未找到相应的设置。
![image](https://user-images.githubusercontent.com/33409664/190045284-7a76b649-a7ad-467f-809f-4fbb38c96a97.png)
——————
补充一点：经测试这种情况只在【全局选项】中关闭［在程序中显示预编辑文本］时出现。
——————
操作系统： Fedora Linux 36
KDE Plasma 版本： 5.25.5
KDE 程序框架版本： 5.97.0
Qt 版本： 5.15.5
内核版本： 5.19.8-200.fc36.x86_64 (64-位)
图形平台： Wayland
处理器： 8 × 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz
内存： 23.3 GiB 内存
图形处理器： Mesa Intel® Xe Graphics

**Comment by wengxt** [comment]
fixed by https://github.com/fcitx/fcitx5-qt/commit/afa070250057e49100c4be839061f74ef8650f48
