### ISSUE TITLE
部分应用中 fcitx5 的单行默认无效

### ISSUE THREAD

**Issue by Zangwill** [fcitx/fcitx5#60]
终端、Firefox、Chrome等中单行正常，Sublime Text 和 WPS 中就只显示双行，如图
xfce4-terminal、Firefox、Chrome 正常:
![1](https://tvax3.sinaimg.cn/large/005NLHW7ly1geumy2yiqoj30mg0bw7bj.jpg)
![2](https://tvax2.sinaimg.cn/large/005NLHW7ly1geumy3a37nj30jg0a6gm6.jpg)
到WPS、subl中就变成了双行模式：
![3](https://tvax2.sinaimg.cn/large/005NLHW7ly1geumy25id9j30ok0f63zp.jpg)
![4](https://tva3.sinaimg.cn/large/005NLHW7ly1geumy2ek1qj30mn0dht9a.jpg)

**Comment by wengxt** [comment]
因为那些程序本身不支持。
wps是因为自己的qt而用了xim吧
sublime 也可能没有对应的gtk im module

**Comment by thep0y** [comment]
> 因为那些程序本身不支持。
> wps是因为自己的qt而用了xim吧
> sublime 也可能没有对应的gtk im module

你好，sublime开发人员问应该用gtk什么模块，他们用的是`‎GtkIMContext`。
https://github.com/sublimehq/sublime_text/issues/4012
