### ISSUE TITLE
Whenever commit string on hangul mode, preedit string is resetted when using fcitx immodule on gtk 4.8

### ISSUE THREAD

**Issue by ganadist** [fcitx/fcitx5#600]
**To Reproduce**
1. run gtk4-demo with fcitx module
  ``` env GTK_IM_MODULE=fcitx gtk4-demo --run=search_entry ```
2. Focus to text entry, and switch to hangul mode
3. type `gksrm` to composite `한그`,  but composited result was `한ㅡ` and 4th character (`r/ㄱ`) was ignored

**Expected behavior**
`한그` should be composited.

**Desktop (please complete the following information):**
 - Desktop: GNOME 43
 - Display server type: wayland
 - Gtk Toolkit : 4.8.1
 - The output of fcitx5-diagnose : https://gist.github.com/ganadist/215b3bfc6ac1c728444d3969fb147e85

**Additional context**
 - When type `r/ㄱ` (4th character) on step 3,  `한` should be committed and `ㄱ` should be preedit string, but when committed `한`, it seems preedit string (`ㄱ`) is resetted.
 - When set `GTK_IM_MODULE=wayland`, it works well as intended

**Comment by wengxt** [comment]
Thanks for reporting, I can confirm the issue.

**Comment by wengxt** [comment]
ok.. I reproduced this with ibus too..

**Comment by wengxt** [comment]
I'll try to bisect gtk to see if I can find the culprit commit, and then see how can we workaround or ask gtk to fix.

**Comment by wengxt** [comment]
I reported the issue to gtk. https://gitlab.gnome.org/GNOME/gtk/-/issues/5200

**Comment by wengxt** [comment]
I submitted a workaround in fcitx5-gtk, please give it try if possible. I'll do a release afterwards.

**Comment by ganadist** [comment]
@wengxt 
Thanks for your support.
And I can confirm this issue was fixed with https://github.com/fcitx/fcitx5-gtk/commit/beee3a92a1881df7f16ff04b618d86883ba1d467
