### ISSUE TITLE
xubuntu 22.04.1 无剪贴板历史，另一台机器从21.10升级到22.04使用的是fcitx4一切正常

### ISSUE THREAD

**Issue by takeseem** [fcitx/fcitx5#610]
xubuntu 22.04.1 无剪贴板历史，另一台机器从21.10升级到22.04使用的是fcitx4一切正常

用不习惯系统自带的，望早日修复bug

**Comment by wengxt** [comment]
@takeseem fcitx5-diagnose 我怀疑你没装

**Comment by takeseem** [comment]
```
sudo apt install fcitx5-diagnose

正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 fcitx5-diagnose
```

**Comment by takeseem** [comment]
fcitx5 --verbose default=5 -D
启动后没看到任何的出错信息 ：（
![image](https://user-images.githubusercontent.com/4768523/192562679-fe1ac119-b934-4203-8f16-52babdd0260a.png)

**Comment by wengxt** [comment]
@takeseem fcitx5的剪贴板历史不再存储在磁盘上，刚一启动确实没有历史。

**Comment by wengxt** [comment]
@wengxt 你启动后去复制一段文字看看有没有历史更新

**Comment by takeseem** [comment]
您好，我已经复制了文本，但是确实没有内容。

**Comment by takeseem** [comment]
@wengxt 果真是缺少一个包导致，我安装这个包后就正常了。

`sudo apt install fcitx5-module-xorg`

**Comment by wengxt** [comment]
你喜欢用 --no-recommends 装包？……

**Comment by takeseem** [comment]
@wengxt 系统安装后，进入设置，选择语言支持时会自动安装缺失的中文支持。

![image](https://user-images.githubusercontent.com/4768523/192572316-796547b2-cb17-4a5c-8434-753fc8161bf1.png)

**Comment by takeseem** [comment]
@wengxt 推荐中文输入法安装：  `sudo apt install fcitx5`

我之前安装过 fcitx5，单独apt remove fcitx5，重新安装时不会自动安装相关推荐依赖，导致功能各种不正常。
这时应先卸载所有fcitx5再重新安装：
`sudo apt purge -y fcitx* && sudo apt autoremove -y && sudo apt install fcitx5-chinese-addons fcitx5-frontend-gtk2`

**Comment by takeseem** [comment]
制粘贴测试复制粘贴

**Comment by takeseem** [comment]
登陆后自动启动fcitx5，发现剪贴板只有最近一次复制记录，无其他历史。
杀掉fcitx5进程重新启动后，就正常了。

**Comment by wengxt** [comment]
我其实在某台 debian 上遇见了同样的问题，一开始我还以为是公司电脑特别的限制，现在你这么一说确实在重启之后对 CLIPBOARD 的监听就正常了，PRIMARY 则是一直都可以

**Comment by takeseem** [comment]
今天新买的电脑又出现这个问题，花了半天时间，最后通过搜索找到了这里，搞定了。。。同一个地方栽了2次跟头了。。。

**Comment by alephpi** [comment]
> 登陆后自动启动fcitx5，发现剪贴板只有最近一次复制记录，无其他历史。 杀掉fcitx5进程重新启动后，就正常了。

我也是这个问题。请问除了杀掉重启还有什么办法吗？每次重启很麻烦呢
