### ISSUE TITLE
如何显示状态栏?

### ISSUE THREAD

**Issue by yar999** [fcitx/fcitx5#62]
以前用fcitx4的时候,可以显示出输入法的状态栏(看中英文状态), 现在换成 fcitx5 不知道显示输入法状态栏了.

我用的是kde环境,虽然有输入法小部件可以看中英文状态,但是用了输入法小部件,fcitx5配置的皮肤就会改成系统默认的,系统默认的皮肤颜色选字序号不易看清,所以不想用输入法小部件.

**Comment by wengxt** [comment]
fcitx5 没有状态栏。只有托盘。只看中英文状态的话托盘可以了

默认皮肤也不会那么看不清吧…字号可以配置你可以把字弄大点？……

**Comment by yar999** [comment]
好吧, 感谢回复.

默认的皮随岁系统主题变,序号很暗

![QQ图片20200523142313](https://user-images.githubusercontent.com/7338900/82723357-f8ec0680-9d00-11ea-8351-549eb5355569.png)

**Comment by wengxt** [comment]
https://invent.kde.org/plasma/plasma-desktop/-/commit/cc89c2e099846275378e1ad29663de3f4c0b5f44

我调整了一下 kde 的那个颜色，以后会颜色深一点

**Comment by yar999** [comment]
非常感谢,我参照那个提交手动修改了下,很清晰了.
