### ISSUE TITLE
Kwin下启用托盘模糊无法保存

### ISSUE THREAD

**Issue by Aleksanaa** [fcitx/fcitx5#622]
**Describe the bug**
fcitx => 配置附加组件 => Classic User Interface => 主题（kde plasma 实验性）=> 设置 =>  Kwin下启用模糊，默认打开，关闭后仅在当前会话中有效，注销后再次登录会变成打开。

**To Reproduce**
1. 关闭Kwin下启用模糊。
2. 注销。
3. 登录，发现模糊被打开且此选项被打开。

**Expected behavior**
取消选择后，重新登录保持关闭。

**Desktop (please complete the following information):**
 - Desktop: KDE Plasma 5.26.0
 - Display server type: Wayland

**Comment by wengxt** [comment]
这是预期中的行为，这个主题是全自动生成的，如果你想要自定义请复制一份

我应该考虑不让它可以被配置以免出现这种误会
