### ISSUE TITLE
hyprland下，GTK、Xwayland和其他wayland应用的输入框大小不同

### ISSUE THREAD

**Issue by Aleksanaa** [fcitx/fcitx5#623]
**Describe the bug**

如题。这可能有一部分属于Hyprland的bug。

**To Reproduce**

1. 打开GTK应用并输入，输入框显示正常，字体清晰；
2. 打开Qt应用（已确定运行在wayland上）并输入，输入框比前者略小，字体有模糊；
3. 打开Xwayland应用（例如，`GDK_BACKEND=x11 gthumb` 、`QT_QPA_PLATFORM=xcb fcitx5-configtool`或者 chrome和vscode）并输入，输入框非常小，大约只有前者的一半大小。
4. 打开或关闭Classic User Interface > use per screen dpi，均可复现。

**Expected behavior**
输入框的大小不改变。

**Desktop (please complete the following information):**
 - Desktop: Hyprland r1909.3a27ef5-1 (昨天的git版) / 0.16.0beta-1，按照[文档](https://wiki.hyprland.org/Configuring/XWayland/)使用了xwayland和wlroots的patch，并设置了`xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2`，环境变量中有`GDK_SCALE=2`和`QT_FONT_DPI=96`，未设置xft dpi。设置了1.25的分数倍缩放。
 - Display server type: Wayland
 - fcitx5-diagnose: http://fars.ee/xyMq
 
**Additional context**
可能与Xwayland的缩放方式有关，在加入xwayland-hidpi.patch之后，因为其upscale之后downscale，fcitx没有读取正确的dpi。
GTK和其他wayland应用可能与 #228 有关，但设置use per screen dpi无效果。

**Comment by wengxt** [comment]
你运行 xrandr 的输出是？

**Comment by Aleksanaa** [comment]
> 你运行 xrandr 的输出是？
```
❯ xrandr
Screen 0: minimum 16 x 16, current 3584 x 2240, maximum 32767 x 32767
XWAYLAND0 connected 3584x2240+0+0 (normal left inverted right x axis y axis) 300mm x 190mm
   3584x2240     59.98*+
   2048x1536     59.95  
   1920x1440     59.97  
   1600x1200     59.87  
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   2560x1600     59.99  
   1920x1200     59.88  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   3200x1800     59.99  
   2880x1620     59.96  
   2560x1440     59.96  
   2048x1152     59.90  
   1920x1080     59.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77  
```

**Comment by wengxt** [comment]
然后你的其他 x 程序大小正常么？特别是纯 X 程序例如 xterm。

我觉得 fcitx 大概干的事情都是预期中的。你可能还是需要设置 Xft.dpi

**Comment by Aleksanaa** [comment]
> `fcitx5 -r --verbose=classicui=5`
> 
> 在里面找类似这样的输出
> D2022-10-25 13:22:41.637850 xcbui.cpp:286] Xft.dpi: 120
> D2022-10-25 13:22:41.637981 xcbui.cpp:439] Screen rects are: [(Rect(0,0+1920x1080), 161)] Primary DPI: 161 XScreen DPI: 96
> 
> 你的具体输出是？

D2022-10-26 12:59:23.300114 xcbui.cpp:286] Xft.dpi: -1
D2022-10-26 12:59:23.300221 xcbui.cpp:439] Screen rects are: [(Rect(0,0+3584x2240), 299)] Primary DPI: -1 XScreen DPI: 96
D2022-10-26 12:59:23.300277 xcbui.cpp:468] Refresh color map: 18874370 vid: 107 CompMgr: 2097156

**Comment by Aleksanaa** [comment]
> 然后你的其他 x 程序大小正常么？特别是纯 X 程序例如 xterm。
> 
> 我觉得 fcitx 大概干的事情都是预期中的。你可能还是需要设置 Xft.dpi 

用xrdb设置成192之后正常了，然后就是gtk和qt的问题

**Comment by wengxt** [comment]
client side input panel 用不同 toolkit 渲染效果略有差别是在预期中的

不过你描述的问题可能是没设置 fontconfig 相关次像素或者平滑选项。
