### ISSUE TITLE
Is it doable for fcitx to notify a desktop notification server when certain events are triggered

### ISSUE THREAD

**Issue by pingz** [fcitx/fcitx5#625]
This is a feature request.
I think it is would be nicer that a more noticeable message could be displayed via desktop mechanism when an important event like the input method switch happened.

**Comment by wengxt** [comment]
So first of all, input method name is already displayed with the input popup when switching. I don't really want to add a new way to display it.

If you want to do this on your own with a separate addon, you can re-use existing notifications addon api to do it. Or write a lua script with fcitx5-lua and launch notify-send.

**Comment by pingz** [comment]
Thanks, for personal usage, `fcitx5-lua` should be enough.

**Comment by pingz** [comment]
a simple gist script:
https://gist.github.com/pingz/2bf2edba0acc012af2f87b1c844a1c1e
