### ISSUE TITLE
[feature request] Standard Unicode codepoint input

### ISSUE THREAD

**Issue by xorgy** [fcitx/fcitx5#631]
I've been a long-time iBus user, and my understanding is that fcitx also used to have a standard <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> functionality where you could just type the codepoint number in hex and insert that character. Recently, after switching over to Fcitx5 from iBus, I realized this keybinding was gone, and in its place is <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd>, which serves a different purpose and is not adequate to my use case. A search box is great if you don't know the codepoint you're looking for, but completely useless for rapidly inserting one that you know by heart (some I use all the time: 2018/2019, 201c/201d, 3bc, e1, e9, c9, e7, c7, 2009, a0, etc).

If this is just a matter of this feature not being interesting to the maintainers, then I might get around to writing a module for it, if it could be upstreamed.

This feature is very important to me, when it was broken in iBus I made sure to get it fixed upstream (even if it ended up behind a configuration flag).

**Comment by wengxt** [comment]
The trigger key in fcitx4 has always been using ctrl alt shift u.

![图片](https://user-images.githubusercontent.com/259684/198731321-c5a98403-466e-48db-965c-b5c70a0622c7.png)

The key sequence is customizable, you can simply go to unicode addon configuration and change it.

Also, type 0x prefix will allow you to search by code point in hex, or simply in decimal.

Also, you might be looking for quick phrase in fcitx, which allows you to customize anything. 

![图片](https://user-images.githubusercontent.com/259684/198732049-d0265d0b-daff-45ce-b1b7-0756bd243711.png)

**Comment by xorgy** [comment]
I don't want to _search_ for a codepoint, I already know what I want, I just want to type it.

**Comment by wengxt** [comment]
I'm not sure what you mean. can you explain it? what key you press and what's the outcome?

I mean you can do something like this.
![图片](https://user-images.githubusercontent.com/259684/198753250-11a8cc4a-98df-45ab-8609-7337c01666e1.png)

As for quick phrase you can do something very similar

![图片](https://user-images.githubusercontent.com/259684/198753553-80bd8c55-b734-4c67-ae52-61e20fcb499f.png)

**Comment by xorgy** [comment]
I press C-S-u 2019 , press space or enter, and `‘` is input immediately.

**Comment by xorgy** [comment]
謝謝您！ :+ )
