### ISSUE TITLE
在mc中没有预编辑(就是打字未选择时输入框被选中的拼音)

### ISSUE THREAD

**Issue by tksmly** [fcitx/fcitx5#653]
在minecraft聊天中,打错拼音删除的时候,由于没有预编辑(或者是其他的原因?)导致拼音和前面输好的字也删了(悲

**Comment by CoelacanthusHex** [comment]
我怀疑是 MC 或者 lwjgl 的实现有问题，因为无论开不开预编辑，都只有 MC 有这个问题（MC 在1.13用上 lwjgl3 之前甚至连输入法都不支持

**Comment by wengxt** [comment]
你在 minecraft 在前台能输入的时候运行的时候执行一下 

```
 dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
```

输出是什么？

**Comment by tksmly** [comment]
IC [4f2fe53854894ccbb8d2a5ac7183c9ba] program:java frontend:xim cap:4000000000 focus:0
要这个吗

**Comment by wengxt** [comment]
重新读了一下描述，看起来只是一个老的退格键同时被程序和输入法处理的问题。这是 mc 自己的问题，和预编辑也没什么关系，mc也没声明自己支持内嵌预编辑，行为符合预期。

**Comment by bczhc** [comment]
See also: https://bugs.mojang.com/browse/MC-258708
