### ISSUE TITLE
Manjaro更新后无法切换输入法。

### ISSUE THREAD

**Issue by GainSky** [fcitx/fcitx5#656]
系统是Manjaro，桌面是i3wm，之前一直都正常使用，包括kitty终端与firefox浏览器等都能正常使用fcitx5-rime输入，但自从十月份一次全面更新后就再也无法切换输入法了，fcitx5-chinese-addons中的那些也无法切换过去，之后试了重装fcitx5，删除.config/fcitx5与.local/share/fcitx5，更换桌面为xfce4，安装manjaro-asian-input-support-fcitx5，都无法解决问题，查看fcitx5-diagnose也没有看出什么问题，只好来求助了。
fcitx5-diagnose.txt在xfce4桌面下生成。
[fcitx5-diagnose.txt](https://github.com/fcitx/fcitx5/files/10022961/fcitx5-diagnose.txt)

**Comment by wengxt** [comment]
没看出什么问题，xfce4-terminal看起来正常连接到fcitx5了

你可以试试 ctrl + ；应该能叫出fcitx的剪贴板吧

你那几个快捷键配制成什么样？

**Comment by GainSky** [comment]
上班中，晚上回去后试一下剪贴板功能，快捷键是默认的。

> 没看出什么问题，xfce4-terminal看起来正常连接到fcitx5了
> 
> 你可以试试 ctrl + ；应该能叫出fcitx的剪贴板吧
> 
> 你那几个快捷键配制成什么样？

**Comment by wengxt** [comment]
你在终端里面用 `fcitx5 -rd —verbose=key_trace=5`  然后按按你配置的切换键看看（根据你的配置应该是ctrl space？）

把按键产生的输出贴上来

**Comment by memorydream** [comment]
arch linux 上在最近出现类似的问题，我在使用 kde，X11 / XWayland 下 fcitx5 可以正常使用

Wayland 下无法切换输入法、打开剪切板，在托盘上可以打开输入法图标的右键菜单，但也无法通过右键菜单切换输入法

**Comment by GainSky** [comment]
解决啦，原因是[.pam_environment已经被弃用了](https://bugs.archlinux.org/task/68945)，昨天关机前有把.pam_environment备份了下就先删了，今天开机发现突然能用了，但是kitty中依然用不了，就看了下环境，发现少了GLFW_IM_MODULE=ibus，其他的相关条目则还在，那些条目猜测是manjaro-asian-input-support-fcitx5添加的，于是又翻了下archwiki关于环境变量的条目才知道已经被弃用了，但明明是早就被弃用了的，我之前还能用也是奇怪。现在环境变量条目已经全部从.pam_environment转移到了/etc/security/pam_env.conf中，就都能正常使用了。之前环境下的话剪贴板无法使用，按键事件也都没有产生任何输出。
感谢两位大佬的回答，谢谢！
