### ISSUE TITLE
不能配置？

### ISSUE THREAD

**Issue by adaaaaaa** [fcitx/fcitx5#66]
打开fcitx5 配置弹出：无法打开URI“file://home/xxx/.config/fcitx5/-config"
Error when getting information for file "/home/xxx/.config/fcitx5/-config":没有哪个文件或目录.

什么时候有：-config这种文件？？不是.config哦。。。🙃

**Comment by wengxt** [comment]
你点了哪个功能？ anyway 反正直接打开对应文件也不再合适了，所以直接改成打开文件夹。
配置工具在另外的包里。
