### ISSUE TITLE
xdroid 中无法输入中文

### ISSUE THREAD

**Issue by yar999** [fcitx/fcitx5#67]
xdroid 4.0 中无法输入中文, 在 xdroid 中也无法切换输入法

换成 fcitx4 可以正常使用

**Comment by yar999** [comment]
这个可能是xdroid那边的问题,我先关闭了,反馈到那边

**Comment by wengxt** [comment]
看起来是用 sdl 支持的，sdl 刚刚才合并 fcitx 5 的支持

sdl发布新版本之前，你暂时可以用 SDL_IM_MODULE=ibus 来用 fcitx 5 输入

**Comment by yar999** [comment]
添加过下面的,没效果哦

SDL_IM_MODULE=ibus
或
SDL_IM_MODULE=fcitx
或
SDL_IM_MODULE=fcitx5

**Comment by wengxt** [comment]
我不知道你问的是安卓里面还是应用中心，应用中心我这里可以输入。还是挺老的一个 2.7 版本

**Comment by wengxt** [comment]
下载了一个 xdroid v4 测试，可以正常输入。

**Comment by yar999** [comment]
xdroid 4.0,应用中心搜索那里和进入具体安装的app比如qq也无法输入中文

我的fcitx4和fcitx5设置的切换输入法快捷键是ctrl+shift

fcitx4 可以在应用中心搜索那里输入中文,但是进入具体的app之后也无法输入中文(按输入法快捷键没有任何反应,手动点鼠标切换也生效)

fcitx5 无法在应用中心搜索那里输入中文,进入具体的app之后也无法输入中文,(这2个地方按输入法快捷键没有任何反应,手动点鼠标切换也不生效)

以前用xdroid 3.0的版本是可以输入,估计是那边的问题吧

用xdroid4.0 的你可以输入? 那就奇怪了

我本地 manjaro kde 环境

```
$ cat ~/.xprofile 
#fcitx
#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx
#export XMODIFIERS="@im=fcitx"

#fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
fcitx5 &
```

**Comment by wengxt** [comment]
建议都设置成 fcitx 再试试。

**Comment by yar999** [comment]
试过了, 也不行的.
反应到xdroid那边说让安装搜狗看看, 搜狗输入法优麒麟社区版(ctrl+v)按键有时候不准,不想用,估计还是他们那边的问题,先就这样吧, 谢谢回复~

**Comment by yar999** [comment]
今天manjaro更新了下系统,xdroid下输入正常了
