### ISSUE TITLE
Dead keys don't work in KDE applications on Debian

### ISSUE THREAD

**Issue by vivia** [fcitx/fcitx5#677]
**Describe the bug**
Using Debian sid, fcitx5 with default/mozc/hangul with setxkbmap configured between US(altgr) and Greek. In other applications, deadkeys (such as Compose key, or Greek accents) work. In ~~telegram-desktop~~ KDE applications they are ignored.

**To Reproduce**
1. Open e.g. telegram-desktop app
2. Switch keyboard layout to Greek
3. Type an accent, followed by a vowel
4. A non-accented vowel will appear

**Expected behavior**
An accented vowel appears

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: X11
<details>
<summary markdown="span">fcitx5-diagnose</summary>

# System Info:

1.  `uname -a`:

        Linux atlas 6.0.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.8-1 (2022-11-11) x86_64 GNU/Linux

2.  `lsb_release -a`:

        Distributor ID:	Debian
        Description:	Debian GNU/Linux bookworm/sid
        Release:	n/a
        Codename:	bookworm

3.  `lsb_release -d`:

        Description:	Debian GNU/Linux bookworm/sid

4.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

5.  `/etc/os-release`:

        PRETTY_NAME="Debian GNU/Linux bookworm/sid"
        NAME="Debian GNU/Linux"
        VERSION_CODENAME=bookworm
        ID=debian
        HOME_URL="https://www.debian.org/"
        SUPPORT_URL="https://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.2.2(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete+ledscroll(group_lock)"	};
            	xkb_symbols   { include "pc+us(intl-unicode)+gr:2+inet(evdev)+group(alt_shift_toggle)+compose(lwin)+eurosign(5)+terminate(ctrl_alt_bksp)"	};
            	xkb_geometry  { include "pc(pc101)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc101", "us,gr", "intl-unicode,", "grp:alt_shift_toggle,grp_led:scroll,compose:lwin,terminate:ctrl_alt_bksp,eurosign:5"

3.  Locale:

    1.  All locales:

            C
            C.utf8
            el_GR
            el_GR@euro
            el_GR.iso88597
            el_GR.iso88597@euro
            el_GR.utf8
            en_DK.utf8
            en_GB.utf8
            en_US.utf8
            greek
            ja_JP
            ja_JP.eucjp
            ja_JP.ujis
            ja_JP.utf8
            japanese
            japanese.euc
            POSIX

    2.  Current locale:

            LANG=en_GB.UTF-8
            LANGUAGE=en_GB
            LC_CTYPE=el_GR.UTF-8
            LC_NUMERIC=en_GB.UTF-8
            LC_TIME=en_DK.UTF-8
            LC_COLLATE=el_GR.UTF-8
            LC_MONETARY=el_GR.UTF-8
            LC_MESSAGES=en_GB.UTF-8
            LC_PAPER=el_GR.UTF-8
            LC_NAME=el_GR.UTF-8
            LC_ADDRESS=el_GR.UTF-8
            LC_TELEPHONE=el_GR.UTF-8
            LC_MEASUREMENT=el_GR.UTF-8
            LC_IDENTIFICATION=el_GR.UTF-8
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/vivia

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/vivia/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/vivia/.config/fcitx5`).

5.  Current user:

    The script is run as vivia (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.21`

3.  process:

    Found 1 fcitx5 process:

         339904 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.767`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `339904`.

    Debug information from dbus:

           Group [x11::0] has 21 InputContext(s)
          IC [a1d03855176840609378df25eb142be6] program:gvim frontend:dbus cap:6000000000 focus:0
          IC [d9e71505666642b58a3848f9db79a327] program:Firefox frontend:dbus cap:6000000012 focus:0
          IC [6fea9d219605469aaea5648bf9a2e041] program:org.gajim.Gajim frontend:dbus cap:6000000052 focus:0
          IC [c68184e4b8944183913602d84e373014] program:org.gajim.Gajim frontend:dbus cap:6000000012 focus:0
          IC [1f998edf326f4ff1a472ab11d8e1d6a4] program:org.gajim.Gajim frontend:dbus cap:6000000012 focus:0
          IC [443dfb1685da458ba3858ea7340d9bd7] program:org.gajim.Gajim frontend:dbus cap:6000000012 focus:0
          IC [094d8eea8d2b4af7a27e8270a60ee2d9] program:gnome-terminal-server frontend:dbus cap:6000000012 focus:0
          IC [29a8d449fa2440749c00f5e60428cb95] program:gnome-terminal-server frontend:dbus cap:6000000012 focus:0
          IC [e19ef290ee1a43d5a56f9b48316248b1] program:nextcloud frontend:dbus cap:6000800072 focus:0
          IC [2eee44220a304cf2bc8092dd7cab889a] program:Firefox frontend:dbus cap:6000000012 focus:0
          IC [b84b04d31bc441b8a8096446aabe23a2] program:gvim frontend:dbus cap:6000000000 focus:0
          IC [d95c4465cde3440aba4e19ee50f3aa93] program:telegram-desktop frontend:dbus cap:6800800072 focus:0
          IC [ce7b9ea5ced44aa881bf79a75b81e87e] program:plasmashell frontend:dbus cap:6000800072 focus:0
          IC [53e72f9042f74b7c8114679cbc8798e1] program:plasmashell frontend:dbus cap:6000800072 focus:0
          IC [c7b4f682239d485eb228e3b4ff4fae82] program:Firefox frontend:dbus cap:6000000052 focus:0
          IC [9e82c539aa13479987c5b36def28d78a] program:plasmashell frontend:dbus cap:6000800072 focus:0
          IC [99dc4b0d16f84f57a7261068ad8627af] program:plasmashell frontend:dbus cap:6000800072 focus:0
          IC [0b5bd1c83e4445219c0100c2ac1884df] program:org.gajim.Gajim frontend:dbus cap:6000000012 focus:0
          IC [54e8f02d09ce44019dd14df3abba1611] program:signal-desktop frontend:dbus cap:6000000012 focus:0
          IC [615c87b0f5684e2da00622dcbe18259b] program:Firefox frontend:dbus cap:6000000012 focus:0
          IC [43f1ac64f8a9473e8e4855ed9faaadb5] program:org.gajim.Gajim frontend:dbus cap:6000000012 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 im module for qt6: `/usr/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for qt5: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.35` at `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.35

        Found fcitx5 im modules for gtk `3.24.35`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 21 enabled addons:

            Classic User Interface 5.0.21
            Clipboard 5.0.21
            DBus 5.0.21
            DBus Frontend 5.0.21
            Emoji 5.0.21
            Fcitx4 Frontend 5.0.21
            Hangul 5.0.10
            IBus Frontend 5.0.21
            Input method selector 5.0.21
            Keyboard 5.0.21
            KDE Input Method Panel 5.0.21
            Mozc 
            Status Notifier 5.0.21
            Notification 5.0.21
            Quick Phrase 5.0.21
            Spell 5.0.21
            Unicode 5.0.21
            Wayland 5.0.21
            Wayland Input method frontend 5.0.21
            XCB 5.0.21
            X Input Method Frontend 5.0.21

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/vivia/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=group
        # Layout
        Default Layout=us-altgr-intl
        # Default Input Method
        DefaultIM=mozc

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us-altgr-intl
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=mozc
        # Layout
        Layout=

        [Groups/0/Items/2]
        # Name
        Name=hangul
        # Layout
        Layout=

        [GroupOrder]
        0=group

# Log:
1.  `date`:

        2022-11-30T17:41:08 EET

2.  `/home/vivia/.config/fcitx5/crash.log`:

    `/home/vivia/.config/fcitx5/crash.log` not found.

</details>

**Additional context**

<details>
<summary markdown="span">strace -f fcitx5 2>&1 | grep Compose</summary>

```
vivia@atlas ~ [SIGINT]> strace -f fcitx5 2>&1 | grep Compose
openat(AT_FDCWD, "/home/vivia/.config/XCompose", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/vivia/.XCompose", O_RDONLY) = 6
openat(AT_FDCWD, "/home/vivia/.config/XCompose", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/vivia/.XCompose", O_RDONLY) = 6
```

</details>

<details>
<summary markdown="span">fcitx5 -r --verbose=key_trace=5</summary>

```
D2022-11-30 17:46:44.085908 instance.cpp:890] KeyEvent: Key(Multi_key states=0) rawKey: Key(Multi_key states=16) origKey: Key(Multi_key states=16) Release:0
D2022-11-30 17:46:44.086034 inputcontext.cpp:275] KeyEvent handling time: 0ms result:1
D2022-11-30 17:46:44.211684 instance.cpp:890] KeyEvent: Key(Multi_key states=0) rawKey: Key(Multi_key states=16) origKey: Key(Multi_key states=16) Release:1
D2022-11-30 17:46:44.211757 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:44.658864 instance.cpp:890] KeyEvent: Key(t states=0) rawKey: Key(t states=16) origKey: Key(t states=16) Release:0
D2022-11-30 17:46:44.659017 inputcontext.cpp:275] KeyEvent handling time: 0ms result:1
D2022-11-30 17:46:44.749975 instance.cpp:890] KeyEvent: Key(t states=0) rawKey: Key(t states=16) origKey: Key(t states=16) Release:1
D2022-11-30 17:46:44.750083 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:44.783844 instance.cpp:890] KeyEvent: Key(e states=0) rawKey: Key(e states=16) origKey: Key(e states=16) Release:0
D2022-11-30 17:46:44.783984 inputcontext.cpp:275] KeyEvent handling time: 0ms result:1
D2022-11-30 17:46:44.887895 instance.cpp:890] KeyEvent: Key(a states=0) rawKey: Key(a states=16) origKey: Key(a states=16) Release:0
D2022-11-30 17:46:44.888040 inputcontext.cpp:275] KeyEvent handling time: 0ms result:1
D2022-11-30 17:46:44.940387 instance.cpp:890] KeyEvent: Key(e states=0) rawKey: Key(e states=16) origKey: Key(e states=16) Release:1
D2022-11-30 17:46:44.940481 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:45.028759 instance.cpp:890] KeyEvent: Key(a states=0) rawKey: Key(a states=16) origKey: Key(a states=16) Release:1
D2022-11-30 17:46:45.028854 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:45.822982 instance.cpp:890] KeyEvent: Key(Alt_L states=0) rawKey: Key(Alt_L states=16) origKey: Key(Alt_L states=16) Release:0
D2022-11-30 17:46:45.823074 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:46.001797 instance.cpp:890] KeyEvent: Key(Alt+ISO_Next_Group states=8) rawKey: Key(Alt+ISO_Next_Group states=24) origKey: Key(Alt+ISO_Next_Group states=24) Release:0
D2022-11-30 17:46:46.001936 inputcontext.cpp:275] KeyEvent handling time: 0ms result:1
D2022-11-30 17:46:46.125910 instance.cpp:890] KeyEvent: Key(Alt+Alt_L states=8) rawKey: Key(Alt+Alt_L states=8216) origKey: Key(Alt+Alt_L states=8216) Release:1
D2022-11-30 17:46:46.126008 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:46.150829 instance.cpp:890] KeyEvent: Key(Shift_L states=0) rawKey: Key(Shift_L states=8208) origKey: Key(Shift_L states=8208) Release:1
D2022-11-30 17:46:46.150912 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:46.898068 instance.cpp:890] KeyEvent: Key(dead_acute states=0) rawKey: Key(dead_acute states=8208) origKey: Key(dead_acute states=8208) Release:0
D2022-11-30 17:46:46.898206 inputcontext.cpp:275] KeyEvent handling time: 0ms result:1
D2022-11-30 17:46:46.944122 instance.cpp:890] KeyEvent: Key(Greek_epsilon states=0) rawKey: Key(Greek_epsilon states=8208) origKey: Key(Greek_epsilon states=8208) Release:0
D2022-11-30 17:46:46.944249 inputcontext.cpp:275] KeyEvent handling time: 0ms result:1
D2022-11-30 17:46:46.975961 instance.cpp:890] KeyEvent: Key(dead_acute states=0) rawKey: Key(dead_acute states=8208) origKey: Key(dead_acute states=8208) Release:1
D2022-11-30 17:46:46.976063 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:47.022923 instance.cpp:890] KeyEvent: Key(Greek_epsilon states=0) rawKey: Key(Greek_epsilon states=8208) origKey: Key(Greek_epsilon states=8208) Release:1
D2022-11-30 17:46:47.023005 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:47.420168 instance.cpp:890] KeyEvent: Key(Alt_L states=0) rawKey: Key(Alt_L states=8208) origKey: Key(Alt_L states=8208) Release:0
D2022-11-30 17:46:47.420250 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:47.454103 instance.cpp:890] KeyEvent: Key(Alt+ISO_Next_Group states=8) rawKey: Key(Alt+ISO_Next_Group states=8216) origKey: Key(Alt+ISO_Next_Group states=8216) Release:0
D2022-11-30 17:46:47.454298 inputcontext.cpp:275] KeyEvent handling time: 0ms result:1
D2022-11-30 17:46:47.503973 instance.cpp:890] KeyEvent: Key(Alt+Alt_L states=8) rawKey: Key(Alt+Alt_L states=24) origKey: Key(Alt+Alt_L states=24) Release:1
D2022-11-30 17:46:47.504078 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
D2022-11-30 17:46:47.542941 instance.cpp:890] KeyEvent: Key(Shift_L states=0) rawKey: Key(Shift_L states=16) origKey: Key(Shift_L states=16) Release:1
D2022-11-30 17:46:47.543038 inputcontext.cpp:275] KeyEvent handling time: 0ms result:0
```

</details>

**Comment by wengxt** [comment]
Did you do anything special to fcitx xcb addon? Otherwise I believe fcitx will override your setxkbmap settings (layout part)

You should try to add greek in fcitx config, instead of using setxkbmap.

One way is to add en-us, mozc, hangul, greek in the same group. Then switch to greek just like how you use mozc/hangul.

Another way is to add two group in fcitx, one with en-us hangul mozc, another with greek hangul, mozc (make sure you also make system layout greek in fcitx kcm), and use super space(you can change the key in fcitx config) to switch group.

Also, you seem to have a .XCompose file under your home, is that what you want?

**Comment by vivia** [comment]
Hi, thanks for your reply!

> Did you do anything special to fcitx xcb addon? Otherwise I believe fcitx will override your setxkbmap settings (layout part)

I tried telling it to not override these settings, in case something worked better. No luck.

> You should try to add greek in fcitx config, instead of using setxkbmap.
> 
> One way is to add en-us, mozc, hangul, greek in the same group. Then switch to greek just like how you use mozc/hangul.

I tried this. It was worse, accented letters didn't work in gnome-terminal either.

Also, my problem is not only with Greek accented letters. The Compose key doesn't work either.

> Also, you seem to have a .XCompose file under your home, is that what you want?

Yes.

**Comment by wengxt** [comment]
So might share your ~/.XCompose ? I'm using the system default compose file and everything works fine.

**Comment by vivia** [comment]
Oh you're right, moving away .XCompose fixes it! I will try trimming it down, because it contains a lot of stuff I don't need, and seeing what happens. Thanks!

[XCompose.txt](https://github.com/fcitx/fcitx5/files/10132089/XCompose.txt)

**Comment by wengxt** [comment]
I mean, I don't want you to disable fcitx's layout management.

Keep it as default, then create two groups
![图片](https://user-images.githubusercontent.com/259684/205044088-4dbf399c-916c-4cc9-b3bb-8e1ef25d883c.png)

1st group:
![图片](https://user-images.githubusercontent.com/259684/205044966-0e04f289-4ad2-415e-b63d-46862bc55017.png)

2nd group:
![图片](https://user-images.githubusercontent.com/259684/205045251-7a935f6d-1ce9-469f-9c39-0be7d3f31cb7.png)

With that I have no problem using things like (altgr + quote , A) to type á  or ὰ 

Also I noticed that you're trying to type (compose t e a ), which I believe from your own ~/.XCompose because this sequence doesn't exist in the default X11 Compose. But it could be possible that your own compose file is not a valid file accepted by xkbcommon.

Gtk uses its own code to parse XCompose, pure X app use libX11, and Qt and fcitx5 uses xkbcommon. And they are 3 different implementations. I used to hit a xkbcommon bug and tried to write a fix for it that actuall rejects certain sequence to be applied.

If you let me guess I guess that might be the reason that your compose file only works in some app. So I probably need your ~/.XCompose file to verify this theory.

**Comment by vivia** [comment]
I found the problem.

```
<Multi_key> <macron> <Odiaeresis>	: "Ȫ" U022A # LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
[...]
<Multi_key> <macron> #<dead_diaeresis> <O>	: "Ȫ" U022A # LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
```

Clumsy commenting out stuff had resulted in duplicated key combinations.

I will clean up my .XCompose now to avoid such issues.

**Comment by wengxt** [comment]
Actually at this point, I'll close this and you may report it to xkbcommon if you think your file should be accepted by xkbcommon. And let them judge if your request is legit or you should fix your compose instead.
