### ISSUE TITLE
Word not commit is deleted on QT app when focus out

### ISSUE THREAD

**Issue by zenfas** [fcitx/fcitx5#687]
I test with fcitx5-unikey, fcitx5-bamboo and fcitx5-m17n, when I move out QT app by mouse, current word in preedit status was deleted instead of committed and keep it 
![Peek 2022-12-15 15-34 Delete word focus out](https://user-images.githubusercontent.com/66258788/207813115-83374566-e78e-406b-bb6c-55461253522a.gif)

GTK will commit and keep it normally

**Comment by zenfas** [comment]
kbuntu@vKbuntu:~$ fcitx5-diagnose  
# System Info: 
1.  `uname -a`: 

       Linux vKbuntu 5.19.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct 12 18:33:17 UTC 202
2 x86_64 x86_64 x86_64 GNU/Linux 

2.  `lsb_release -a`: 

       No LSB modules are available. 
       Distributor ID: Ubuntu 
       Description:    Ubuntu Lunar Lobster (development branch) 
       Release:        23.04 
       Codename:       lunar 

3.  `lsb_release -d`: 

       Description:    Ubuntu Lunar Lobster (development branch) 

4.  `/etc/lsb-release`: 

       DISTRIB_ID=Ubuntu 
       DISTRIB_RELEASE=23.04 
       DISTRIB_CODENAME=lunar 
       DISTRIB_DESCRIPTION="Ubuntu Lunar Lobster (development branch)" 

5.  `/etc/os-release`: 

       PRETTY_NAME="Ubuntu Lunar Lobster (development branch)" 
       NAME="Ubuntu" 
       VERSION_ID="23.04" 
       VERSION="23.04 (Lunar Lobster)" 
       VERSION_CODENAME=lunar 
       ID=ubuntu 
       ID_LIKE=debian 
       HOME_URL="https://www.ubuntu.com/" 
       SUPPORT_URL="https://help.ubuntu.com/" 
       BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" 
       PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" 
       UBUNTU_CODENAME=lunar 
       LOGO=ubuntu-logo 

6.  Desktop Environment: 

   Desktop environment is `kde`. 

7.  XDG SESSION TYPE: 

       XDG_SESSION_TYPE='x11' 

8.  Bash Version: 

       BASH_VERSION='5.2.2(1)-release' 

# Environment: 
1.  DISPLAY: 

       DISPLAY=':0' 


       WAYLAND_DISPLAY='' 

2.  Keyboard Layout: 

   1.  `setxkbmap`: 

           xkb_keymap { 
               xkb_keycodes  { include "evdev+aliases(qwerty)" }; 
               xkb_types     { include "complete"      }; 
               xkb_compat    { include "complete"      }; 
               xkb_symbols   { include "pc+us+inet(evdev)"     }; 
               xkb_geometry  { include "pc(pc104)"     }; 
           }; 

   2.  `xprop`: 

           _XKB_RULES_NAMES(STRING) = "evdev", "pc104", "us", "", "" 

3.  Locale: 

   1.  All locales: 

           C 
           C.utf8 
           en_AG 
           en_AG.utf8 
           en_AU.utf8 
           en_BW.utf8 
           en_CA.utf8 
           en_DK.utf8 
           en_GB.utf8 
           en_HK.utf8 
           en_IE.utf8 
           en_IL 
           en_IL.utf8 
           en_IN 
           en_IN.utf8 
           en_NG 
           en_NG.utf8 
           en_NZ.utf8 
           en_PH.utf8 
           en_SG.utf8 
           en_US.utf8 
           en_ZA.utf8 
           en_ZM 
           en_ZM.utf8 
           en_ZW.utf8 
           POSIX 
           vi_VN 
           vi_VN.utf8 

   2.  Current locale: 

           LANG=en_US.UTF-8 
           LANGUAGE= 
           LC_CTYPE="en_US.UTF-8" 
           LC_NUMERIC=vi_VN 
           LC_TIME=vi_VN 
           LC_COLLATE="en_US.UTF-8" 
           LC_MONETARY=vi_VN 
           LC_MESSAGES="en_US.UTF-8" 
           LC_PAPER=vi_VN 
           LC_NAME=vi_VN 
           LC_ADDRESS=vi_VN 
           LC_TELEPHONE=vi_VN 
           LC_MEASUREMENT=vi_VN 
           LC_IDENTIFICATION=vi_VN 
           LC_ALL= 

4.  Directories: 

   1.  Home: 

           /home/kbuntu 

   2.  `${XDG_CONFIG_HOME}`: 

       Environment variable `XDG_CONFIG_HOME` is not set. 

       Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/kbuntu/.config`). 

   3.  Fcitx5 Settings Directory: 

       Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/kbuntu/.config/fcitx5`). 

5.  Current user: 

   The script is run as kbuntu (1000). 

# Fcitx State: 
1.  executable: 

   Found fcitx5 at `/usr/bin/fcitx5`. 

2.  version: 

   Fcitx version: `5.0.21` 

3.  process: 

   Found 1 fcitx5 process: 

          2392 fcitx5 

4.  `fcitx5-remote`: 

   `fcitx5-remote` works properly. 

5.  DBus interface: 

   Using `dbus-send` to check dbus. 

   Owner of DBus name `org.fcitx.Fcitx5` is `:1.131`. 

   PID of DBus name `org.fcitx.Fcitx5` owner is `2392`. 

   Debug information from dbus: 

          Group [x11::0] has 16 InputContext(s) 
         IC [7ecd8a65383d40daa1f35a19ae0fe294] program:plasmashell frontend:dbus cap:16000800072 
focus:0 
         IC [d415e2c075824052b7ee62ef361ae34e] program:gedit frontend:dbus cap:6000000052 focus:0 
         IC [a191ac1dd1a64848b7cdb4d3c8834832] program:gedit frontend:dbus cap:6000000012 focus:0 
         IC [7fa03583af024e68ad649d1bff8e5b17] program:gedit frontend:dbus cap:6000000012 focus:0 
         IC [04b027777b5c4d4ba432655d15f26f26] program:gedit frontend:dbus cap:6000000012 focus:0 
         IC [dfd3077d7d584bb7af89b7401b035644] program:firefox frontend:fcitx4 cap:12 focus:0 
         IC [d331f95602d548bb81b78e38e9c63c48] program:featherpad frontend:dbus cap:6800800072 fo
cus:0 
         IC [6d4f3c71dbf8470b8f66a3824eeea23f] program:firefox frontend:fcitx4 cap:12 focus:0 
         IC [9f609946004d44d49e00c1bfc1ce0fea] program:konsole frontend:dbus cap:6000800072 focus
:1 
         IC [a9ad0762f6074777a73c7e5dcbe1c85a] program:kate frontend:dbus cap:6000800072 focus:0 
         IC [9ddce97a4ca04f79b4562cc2e1460c3d] program:plasmashell frontend:dbus cap:16000800072 
focus:0 
         IC [b5f7354111784849b50e331421137ce9] program:gedit frontend:dbus cap:6000000012 focus:0 
         IC [03ad4ea3d7c7445aaae5aab1e79062ea] program:plasmashell frontend:dbus cap:16000800072 
focus:0 
         IC [fa2a31087b3a4b84ada6f31372fb1f86] program:featherpad frontend:dbus cap:16000800072 f
ocus:0 
         IC [37e6c3314ccc415782c80cb93d8a908e] program:firefox frontend:fcitx4 cap:52 focus:0 
         IC [fc4ac9ca09f64532894d13d2ae9ac82b] program:firefox frontend:fcitx4 cap:12 focus:0 
       Input Context without group 

# Fcitx Configure UI: 
1.  Config Tool Wrapper: 

   Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`. 

2.  Config GUI for qt: 

   Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`. 

3.  Config GUI for kde: 

# Frontends setup: 
## Xim: 
1.  `${XMODIFIERS}`: 

   Environment variable XMODIFIERS is set to "@im=fcitx" correctly. 
   Xim Server Name from Environment variable is fcitx. 

2.  XIM_SERVERS on root window: 

   Xim server name is the same with that set in the environment variable. 

## Qt: 
1.  qt4 - `${QT4_IM_MODULE}`: 

   Environment variable QT_IM_MODULE is set to "fcitx" correctly. 

2.  qt5 - `${QT_IM_MODULE}`: 

   Environment variable QT_IM_MODULE is set to "fcitx" correctly. 


3.  Qt IM module files: 

   Found fcitx5 im module for qt6: `/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfc
itx5platforminputcontextplugin.so`. 
   Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`. 
   Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx5-unikey-macro-editor.so`. 
   Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx5-unikey-keymap-editor.so`. 
   Found fcitx5 im module for qt5: `/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfc
itx5platforminputcontextplugin.so`. 

   Following error may not be accurate because guessing Qt version from path depends on how your 
distribution packages Qt. It is not a critical error if you do not use any Qt application with cer
tain version of Qt or you are using text-input support by Qt under Wayland. 
   **Cannot find fcitx5 input method module for Qt4.** 

## Gtk: 
1.  gtk - `${GTK_IM_MODULE}`: 

   Environment variable GTK_IM_MODULE is set to "fcitx" correctly. 

2.  `gtk-query-immodules`: 

   1.  gtk 2: 

       **Cannot find `gtk-query-immodules` for gtk 2** 

       **Cannot find fcitx5 im module for gtk 2.** 

   2.  gtk 3: 

       **Cannot find `gtk-query-immodules` for gtk 3** 

       **Cannot find fcitx5 im module for gtk 3.** 

3.  Gtk IM module cache: 

   1.  gtk 2: 

       Found immodules cache for gtk `2.24.33` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules
.cache`. 
       Version Line: 

           # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2
.24.33 

       **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodul
es.cache`** 

       **Cannot find fcitx5 im module for gtk 2 in cache.** 

   2.  gtk 3: 

       Found immodules cache for gtk `3.24.35` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.
cache`. 
       Version Line: 

           # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.
24.35 

       Found fcitx5 im modules for gtk `3.24.35`. 

           "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so"  
           "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*
"  
           "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:
*"  

   3.  gtk 4: 

       **Cannot find immodules cache for gtk 4** 

       **Cannot find fcitx5 im module for gtk 4 in cache.** 

4.  Gtk IM module files: 

   1.  gtk 2: 

       All found Gtk 2 immodule files exist. 

   2.  gtk 3: 

       All found Gtk 3 immodule files exist. 

   3.  gtk 4: 

       All found Gtk 4 immodule files exist. 

# Configuration: 
## Fcitx Addons: 
1.  Addon Config Dir: 

   Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`. 

2.  Addon List: 

   1.  Found 23 enabled addons: 

           Bamboo Wrapper For Fcitx 1.0.2 
           Classic User Interface 5.0.21 
           Clipboard 5.0.21 
           DBus 5.0.21 
           DBus Frontend 5.0.21 
           Emoji 5.0.21 
           Fcitx4 Frontend 5.0.21 
           IBus Frontend 5.0.21 
           Input method selector 5.0.21 
           Keyboard 5.0.21 
           Keyman 1.0.6 
           KDE Input Method Panel 5.0.21 
           M17N 5.0.11 
           Status Notifier 5.0.21 
           Notification 5.0.21 
           Quick Phrase 5.0.21 
           Spell 5.0.21 
           Unicode 5.0.21 
           Unikey Wrapper For Fcitx 5.0.12 
           Wayland 5.0.21 
           Wayland Input method frontend 5.0.21 
           XCB 5.0.21 
           X Input Method Frontend 5.0.21 

   2.  Found 0 disabled addons: 

3.  Addon Libraries: 

   All libraries for all addons are found. 

4.  User Interface: 

   Found 2 enabled user interface addons: 

       Classic User Interface 
       KDE Input Method Panel 

## Input Methods: 
1.  `/home/kbuntu/.config/fcitx5/profile`: 

       [Groups/0] 
       # Group Name 
       Name=Default 
       # Layout 
       Default Layout=us 
       # Default Input Method 
       DefaultIM=unikey 

       [Groups/0/Items/0] 
       # Name 
       Name=keyboard-us 
       # Layout 
       Layout= 

       [Groups/0/Items/1] 
       # Name 
       Name=unikey 
       # Layout 
       Layout= 

       [Groups/0/Items/2] 
       # Name 
       Name=bamboo 
       # Layout 
       Layout= 

       [Groups/0/Items/3] 
       # Name 
       Name=keyman:vietnamese_telex 
       # Layout 
       Layout= 

       [Groups/0/Items/4] 
       # Name 
       Name=m17n_vi_telex 
       # Layout 
       Layout= 

       [GroupOrder] 
       0=Default 

# Log: 
1.  `date`: 

       Thứ năm, 15 Tháng 12 năm 2022 15:36:09 +07 

2.  `/home/kbuntu/.config/fcitx5/crash.log`: 

   `/home/kbuntu/.config/fcitx5/crash.log` not found.

**Comment by wengxt** [comment]
can't reproduce.

https://user-images.githubusercontent.com/259684/207889566-ff3e0962-c7ca-480f-88b9-78de3097457a.mp4

This supposed to be handled by the code here
https://github.com/fcitx/fcitx5-qt/blob/85c164e261169d492a0b45b20a9b2282ca8437de/qt5/platforminputcontext/qfcitxplatforminputcontext.cpp#L362

**Comment by zenfas** [comment]
0:19 do you see "ương" disappear on second Windows

**Comment by zenfas** [comment]
@zenfas I tested with ibus-m17n the same when I move from QT app (Kate, FeatherPad) to GTK app (Firefox, Xfce terminal), the same issue

**Comment by wengxt** [comment]
> 0:19 do you see "ương" disappear on second Windows

ah, I see, sorry. Yeah, you're right.

I think I got what happened. 
1. First application has preedit
2. second application send focus in
3. focus group policy kicks first application and make it focus out. -> at this point, preedit will be reset to empty
4. first application send focus out.

If focus is moved within the same qt application, the client side commit preedit would take effect before the reset happens.

**Comment by zenfas** [comment]
It maybe relate to your issue fcitx/fcitx5-unikey#35 @trmdi

**Comment by trmdi** [comment]
@wengxt 
FYI, this bug only happens when you're switching between different processes.

**Comment by wengxt** [comment]
> @wengxt FYI, this bug only happens when you're switching between different processes. It's fine when you're switching between 2 Kate windows (they belong to a same process)

yes, I already explained in https://github.com/fcitx/fcitx5/issues/687#issuecomment-1353230594

**Comment by zenfas** [comment]
@wengxt  with newest git of fcitx5, fcitx5-qt and fcitx5-gtk, this error revert, happen on gtk. Now if type on gtk app and move to any other windows, word not commit on gtk app will be deleted

**Comment by wengxt** [comment]
@zenfas should be fixed by https://github.com/fcitx/fcitx5-gtk/commit/4883a2e090d13dd5e373852df81cfb23058be004

**Comment by zenfas** [comment]
> @zenfas should be fixed by [fcitx/fcitx5-gtk@4883a2e](https://github.com/fcitx/fcitx5-gtk/commit/4883a2e090d13dd5e373852df81cfb23058be004)

Ok now, thank you
