### ISSUE TITLE
candidate box has wrong position when typing in Jetbain applications (IDEA, Pycharm)

### ISSUE THREAD

**Issue by wen-zheng** [fcitx/fcitx5#689]
**Describe the bug** 
candidate box has wrong position when type in Jetbain applications (IDEA, Pycharm)

**To Reproduce**
1. Open Pycharm (IDEA)
2. Try to type Chinese or other input languages having candidate box

**Expected behavior**
candidate box is located under the cursor

**Desktop (please complete the following information):**
Operating System: openSUSE Tumbleweed 20221216
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.0.12-1-default (64-bit)
Graphics Platform: Wayland
Graphics Processor: Mesa Intel® Xe Graphics

**Comment by wengxt** [comment]
its java issue, not fcitx’s.

there is a patch to jdk in the wild

https://github.com/prehonor/myJetBrainsRuntime/blob/master/idea.patch

**Comment by wen-zheng** [comment]
ok, thx
