### ISSUE TITLE
wayland下应用predit的使用体验不同与xorg?

### ISSUE THREAD

**Issue by guyuming76** [fcitx/fcitx5#699]
问题的背景源于 https://github.com/fcitx/fcitx5-anthy/issues/6

我尝试在 wayland (dwl) 下用 fcitx5 加日文 anthy. 一开始发觉在foot, alacritty 里日文的 preedit 不显示。后来貌似升级了 alacritty 发觉可以了（具体是否是alacritty 升级或 foot 升级我记不清了），但一个重要的使用体验改变是，包括中文输入法，preedit 的显示都改由应用程序，如 foot, alacritty 来完成，而输入法的弹出框只是完成让用户从candidate 选择的功能，中文输入法弹出框本来有两行，上面一行显示preedit,下面一行显示 candidate, 但现在弹出框只剩一行，即candidates,而 preedit 改由应用，如alacritty 来显示。我的理解是这是不是要求所有希望有fcitx5中日文输入的应用，都要改变，添加preedit 的某种支持？

而我在同一台机器上，用xorg (dwm) fcitx5 不管是中文输入，还是日文anthy 输入，都是通过弹出框来显示 preedit, 以及让用户完成 candidate的选择。在wayland (dwl) 上，之前中文输入的体验和xorg (dwm) 上是一致的，后来不知咋的 wayland 体验就变了，仅仅是为了增加 fcitx5-anthy 的支持改变了 predit 的处理方式？

**我的问题是能否让wayland 下 fcitx5 中日文的输入都和 xorg 的体验保持一致？如有困难，困难在哪里？ 如果按我现在在机器上体验到的wayland下需要应用如alacritty去显示 preedit, 是不是意味着应用或某个底层库需要额外的适配？如果是只需要在wayland相关的底层库修改，而无需逐个应用改动，那么这种不同于xorg下preedit显示的好处在哪里呢？** 

我的意思是之前 wayland (dwl) 上一切工作得似乎都挺好，除了 anthy 不知为啥有些问题。现在 anthy 貌似能工作了，但似乎所有应用都要增加对preedit的支持？

我对这中间的架构还不是很理解，包括对preedit的定义, 如果有啥理解错误或表达不清的地方，还请指正，感觉这个问题还挺重要。

**Comment by wengxt** [comment]
preedit 尽管是一种可选的功能，但是协议是否支持声明「不支持 preedit」这件事是不一定的。例如 wayland 的输入法协议就不支持声明支持 preedit 与否，这点上反而还不如古老的 xim。

这导致的结果就是，fcitx 只能认为所有采用 wayland 输入法协议的情况都支持 preedit（当然你也可以说为什么不假定都不支持呢？简单来说这就是我的选择，因为 preedit 对很多语言都是很必要的功能）。而这种无 toolkit 纯手写的客户端对输入法的支持是残缺的情况是非常常见的。而相对的，如果它使用 xim 的情况，根据 fcitx 的默认选项，是会要求客户端不使用 preedit （这个牵扯到一个历史悠久的 libx11 bug，libx11 在使用 preedit 的时候会不发送光标位置导致弹出窗口位置不正确。）所以你用 xwayland 的模式跑那些终端反而更可能得到更「正常」的结果。

alacritty 支持 preedit 相关的 pr
https://github.com/rust-windowing/winit/pull/2154

根据现在协议的功能情况，能做的事情，就是要求那些程序全都去实现 preedit 支持，因为这是协议隐含假定必须支持的。
快速 workaround 可以用 ctrl + alt + P 一键强行让 fcitx 不用 preedit。

**Comment by guyuming76** [comment]
多谢！果然 ctrl+alt+p 就可以切换preedit的显示位置了：

![20230110_07h47m35s_grim](https://user-images.githubusercontent.com/12045548/211430794-f5c15711-4e2c-48e8-ab40-752014962d63.png)
![20230110_07h47m20s_grim](https://user-images.githubusercontent.com/12045548/211430851-4d42f0ed-8abb-44e3-b804-07571762b021.png)
