### ISSUE TITLE
[Feature Request] 希望添加查询选中字符unicode编码的功能

### ISSUE THREAD

**Issue by cathaysia** [fcitx/fcitx5#70]
我发现了这个网页：http://www.pgygho.com/help/soft/word/33853.html
首先选择单个字符，然后按下 alt + x 可以查询对应字符的编码，我感觉这个小功能有时候可能会非常有用。希望您能考虑这个小功能

**Comment by wengxt** [comment]
<img width="310" alt="图片" src="https://user-images.githubusercontent.com/259684/83280573-bbb5c780-a18b-11ea-82c6-39ad8d3bc4f9.png">
第一次触发 unicode 时将显示选中字符的 unicode 信息。

**Comment by cathaysia** [comment]
> <img alt="图片" width="310" src="https://user-images.githubusercontent.com/259684/83280573-bbb5c780-a18b-11ea-82c6-39ad8d3bc4f9.png">
> 第一次触发 unicode 时将显示选中字符的 unicode 信息。

请问这个功能如何使用呢？我今天已经更新到 0.0.0.20200530-1 版本了，但是不知道怎样才能使用这个功能

**Comment by wengxt** [comment]
ctrl alt shift u
