### ISSUE TITLE
请教一下 Fcitx 支持通过ssh x11 forwarding环境下使用么？

### ISSUE THREAD

**Issue by AndrewTsao** [fcitx/fcitx5#700]
请教一下，在Centos 7.9的服务器环境下，开启了X11 Forwarding，然后通过Mobaxterm客户端启动的spyder窗口中，使用Fcitx输入中文。

能够配置使用Fcitx中文输入法么？我现在没有搞定，不知道是本身不支持，还是我配置有问题。

**Comment by AndrewTsao** [comment]
谢谢你的答复。我测试了xterm或者geditor，能够调出输出法。

Spyder是QT5的应用程序。可能是有其它的配置问题，我再检查一下。

**Comment by wengxt** [comment]
qt5不支持xim，这就没特别好的办法了

一种是你把dbus forward过去，在另一边设置DBUS_SESSION_BUS_ADDRESS到forward的socket

另一种就是干脆在那边运行另一个fcitx来输入

**Comment by AndrewTsao** [comment]
谢谢你的解答。
