### ISSUE TITLE
classiui option "Vertical Candidate List" has spaces

### ISSUE THREAD

**Issue by stanzgy** [fcitx/fcitx5#706]
I'm switching to fcitx5 recently. When configuring classicui, it's a little weird that only option "Vertical Candidate List" contains spaces, while other options like "PerScreenDPI" has no spaces. Is this an issue or just intended to be like this?

https://github.com/fcitx/fcitx5/blob/c8518ff74cb55424a64f666e935b83b0c9a2d199/src/ui/classic/classicui.h#L96-L109

**Comment by wengxt** [comment]
Yeah, I know. It doesn’t really matter in terms of functionality. But if we rename it the existing user configuration would be reset to default value (or we need to write fancy migration code for it), so I’d prefer leave it as is.
