### ISSUE TITLE
Plasma 5.27: When using Kimpanel and zwp_text_input, the candidate panel stays at screen top left corner

### ISSUE THREAD

**Issue by hexchain** [fcitx/fcitx5#707]
**Describe the bug**
In Plasma 5.27, when using Kimpanel and the app supports zwp_text_input_v*, the candidate list stays at the top left corner of the screen.

**To Reproduce**
1. Open any Qt app with QT_IM_MODULE unset (text-input-v2), or WezTerm with use_ime=true (text-input-v3).
2. Try to type anything

**Expected behavior**
The candidate list should appear around the cursor.

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland
 - The output of fcitx5-diagnose: [fcitx5-diagnose.txt](https://github.com/fcitx/fcitx5/files/10558810/fcitx5-diagnose.txt)

**Additional context**
![image](https://user-images.githubusercontent.com/529520/216093051-0a6b1f58-c5e9-440c-852c-55d35ad83b3e.png)

**Comment by wengxt** [comment]
this is expected and not a fcitx issue.

**Comment by hexchain** [comment]
But the Classic UI can position itself correctly. Should Kimpanel be able to do something similar?

**Comment by rocka** [comment]
Classic UI is using ["Client Side Input panel"](https://www.csslayer.info/wordpress/fcitx-dev/client-side-input-panel-for-fcitx-5/) to let the client render input panel itself, using im modules.

Kimpanel is rendered by plasmashell, it has to know the absolute position on screen of the input panel, to render the popup in the correct position. On X11, client windows can provide the absolute position. But on Wayland it couldn't, because wayland window does not know it's position.

An idea would be rewrite Kimpanel as a KWin Script, KWin (compositor) knows all the window position and can move the input panel relative to the focused window, similar to how GNOME kimpanel extension works.

**Comment by hexchain** [comment]
Is the client-side input panel also in use when the application (neither Qt nor GTK) uses text-input-v*?

**Comment by rocka** [comment]
No, Client Side Input panel can only be used with im modules, since it injects into the client application and render the input panel in "client side".

**Comment by hexchain** [comment]
That's what I imagined too, but this issue is about text-input-v* without IM modules. Classic UI works well with text-input-v*, for example:

![image](https://user-images.githubusercontent.com/529520/216245848-5af81274-455b-45cc-9fb2-27bdd97ff13e.png)

The candidate window follows the cursor just fine in WezTerm, which uses text-input-v3.

**Comment by rocka** [comment]
Classic UI runs in the same process of fcitx5, it can use `zwp_input_method_*` to talk to the compositor and ask it to position the input panel surface. But Kimpanel' UI runs in plasmashell, which does not have the privilege.

**Comment by hexchain** [comment]
> Kimpanel' UI runs in plasmashell, which does not have the privilege.

Since Fcitx knows the position, it surely can pass that information to plasmashell/Kimpanel via D-Bus, no?
Unless `org.kde.impanel2.Set*Rect` methods don't work at all under Wayland?

**Comment by rocka** [comment]
On Wayland, that's the "relative" position to client window, not absolute position on screen. So you have to know the window's position in order to position input panel correctly, which only the compositor can do.

**Comment by hexchain** [comment]
Ah, I see where the problem is. In Fcitx there are mentions of `org.kde.impanel2.SetRelativeSpotRect{,V2}` which I imagine should take care of relevant coordinates, but these methods do not actually exist in Kimpanel.

**Comment by rocka** [comment]
Even if there were those methods, plasmashell can't use the "relative" coordinate, because it does not know which window the input panel is relative to, nor the window's position.

**Comment by hexchain** [comment]
Yes, but technically it is possible. There are quite a few custom Wayland interfaces between kwin and plasmashell. Maybe something could be hacked together with these interfaces, but that's another issue.
