### ISSUE TITLE
在gnome中，wine程序的输入候选框不在窗口下方，而在屏幕右下角。

### ISSUE THREAD

**Issue by woqulegenicheng** [fcitx/fcitx5#71]
输入候选框无法截图，在kde中表现很好，但在gnome中，wine程序的窗口要输入时，不像kde或者fcitx一样在窗口左下方，而在更远的右下方，脱离窗口边缘，好似是根据屏幕的大小确定的位置，不知道是我设置问题还是bug,先反馈一下。

**Comment by woqulegenicheng** [comment]
我再次试了试，应该是跟随窗口的，但是位置是在窗口右下角，距离窗口边缘大概三厘米。

**Comment by woqulegenicheng** [comment]
其实kde桌面上也不跟随wine窗口位置，只是会在你移动窗口后出现，在gnome上一开始就是偏离的。

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/85912505-89b58500-b85f-11ea-84a9-9b26d6872c81.png)

`Xfce`光标不跟随。候选框显示的位置是Konsole窗口在最大化或者在左侧时候的位置。如下：

![image](https://user-images.githubusercontent.com/9500049/85912558-caad9980-b85f-11ea-940e-12f7efd21d5f.png)

---

也就是说将Konsole窗口移到右侧，候选狂显示的位置是Konsole窗口还在左侧是对应的位置。

---

fcitx version: `local/fcitx5-git r602.2e9821a-1`

**Comment by wengxt** [comment]
@roachsinai  无法重现，你这个看着也不像 konsole 啊。什么窗口管理器

**Comment by wengxt** [comment]
@woqulegenicheng wine 就那样，没有办法。

**Comment by roachsinai** [comment]
emm,就是Xfce自带的，设置不显示标题。然后自定义了konsole的tab bar。

有一种情况我这里可以重现：我使用了一个记笔记的软件[joplin](https://joplinapp.org/)，编辑内容可以通过外置命令打开。设置在konsole中用vim打开之后出现这个情况。
