### ISSUE TITLE
Wrong candidate box position when typing in Chinese on telegram desktop

### ISSUE THREAD

**Issue by wen-zheng** [fcitx/fcitx5#710]
**Describe the bug**
Wrong candidate box position when typing in Chinese on telegram desktop

**To Reproduce**
1. Open telegram app
2. Try to type in Chinese

**Expected behavior**
correct candidate box position (following cursor)

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland

**Comment by rocka** [comment]
Can you attach some screenshots to demonstrate how is it wrong? Where did the candidate window located, and where you'd expect it to be?

**Comment by wen-zheng** [comment]
![image](https://user-images.githubusercontent.com/33896328/216760622-1a84494a-0357-4d08-9117-05b2c553e5d4.png)

**Comment by rocka** [comment]
Can you attach output of the command `fcitx5-diagnose`? I can't reproduce it on KDE Wayland.

**Comment by wen-zheng** [comment]
[diagnose.txt](https://github.com/fcitx/fcitx5/files/10608339/diagnose.txt)

**Comment by rocka** [comment]
Able to reproduce this after set `QT_IM_MODULE` to `fcitx` on KDE Wayland. Since Qt supports wayland's text-input protocol, you can just unset `QT_IM_MODULE` for telegram-desktop or even globally, it should work fine.

**Comment by wen-zheng** [comment]
OK, thx

**Comment by wengxt** [comment]
This is due to telegram-desktop bundles fcitx4 and fcitx5 im module together. It actually means you're using fcitx4 im module. This is not a bug on fcitx side, but the weird way that telegram bundles fcitx im module.

If you set environment variable manually to fcitx5, I think your problem may gone away too.
