### ISSUE TITLE
在 virtualbox 里面的虚拟机运行guest  additon 会和 fcitx5冲突，导致 guest addition 出现内存泄露

### ISSUE THREAD

**Issue by rico256-cn** [fcitx/fcitx5#718]
在 virtualbox 里面的虚拟机运行guest  additon 会和 fcitx5冲突，导致 guest addition 出现内存泄露。

virtualbox 通过 guest additon组件为host <-> guest 提供剪切板复制等功能，其中剪切板复制和 fcitx5冲突。（virtualbox 的 guest additon 多个版本均测试过，和guest  addition版本无关）

测试和重现方法：

在virtualbox 的linux 虚拟机里面从  https://download.virtualbox.org/virtualbox/7.0.6/VBoxGuestAdditions_7.0.6.iso 下载，运行里面的 lvbox_linux_guest.run完成安装重启后, lsmod | grep vboxguest 检查模块加载， ps -ef | grep VB 查看是否 VBoxClient --clipboard 进程正常拉起，并且在 virtualbox 上配置共享剪贴板双向打开。

然后 kill 掉默认安装的VBoxClient --clipboard进程后，手工运行如下进程，然后在有输入法运行的情况下，在 host 上找个 excel 文件，复制里面的内容，就会触发 vboxclient 如下错误，并且导致内存泄露最终搞崩进程或者guest os。（退出 fcitx5进程后一切正常）

$ VBoxClient --clipboard -f -v
12:35:17.391248 main     VBoxClient 7.0.4 r154605 (verbosity: 1) linux.amd64 (Nov 16 2022 17:25:53) release log
12:35:17.391250 main     Log opened 2023-02-12T12:35:17.391244000Z
12:35:17.391293 main     OS Product: Linux
12:35:17.391306 main     OS Release: 6.1.3-0110
12:35:17.391335 main     OS Version: #1 SMP Tue Jan 10 16:43:59 CST 2023
12:35:17.391347 main     Executable: /opt/VBoxGuestAdditions-7.0.4/bin/VBoxClient
12:35:17.391348 main     Process ID: 1123
12:35:17.391349 main     Package type: LINUX_64BITS_GENERIC
12:35:17.391363 main      VBoxClient 7.0.4 r154605 started. Verbose level = 1. Wayland environment detected: no
12:35:17.391392 main      Service: Shared Clipboard
12:35:17.391629 main      Initializing service ...
12:35:17.391662 main      Creating worker thread ...
12:35:17.396355 main      Service started
12:35:21.005882 SHCLX11   Shared Clipboard: Converting VBox formats 'UNICODETEXT, BITMAP, HTML' to 'INVALID' for X11 (idxFmtX11=0, fmtX11=0, atomTarget='COMPOUND_TEXT') failed, rc=VERR_NOT_SUPPORTED
12:35:21.006849 SHCLX11   Shared Clipboard: Converting VBox formats 'UNICODETEXT, BITMAP, HTML' to 'INVALID' for X11 (idxFmtX11=0, fmtX11=0, atomTarget='COMPOUND_TEXT') failed, rc=VERR_NOT_SUPPORTED
12:35:23.018530 SHCLX11   Shared Clipboard: Converting VBox formats 'UNICODETEXT, BITMAP, HTML' to 'INVALID' for X11 (idxFmtX11=0, fmtX11=0, atomTarget='COMPOUND_TEXT') failed, rc=VERR_NOT_SUPPORTED
12:35:23.020613 SHCLX11   Shared Clipboard: Converting VBox formats 'UNICODETEXT, BITMAP, HTML' to 'INVALID' for X11 (idxFmtX11=0, fmtX11=0, atomTarget='COMPOUND_TEXT') failed, rc=VERR_NOT_SUPPORTED

**Comment by rico256-cn** [comment]
我的场景并不需要 fcitx5 参与剪贴板的数据管理，所以能否增加一个编译参数 禁用fcitx5的剪贴板相关操作功能？

**Comment by rico256-cn** [comment]
进一步测试，在 fcitx5里面可以关闭剪贴板模块规避这个问题，但提示会同时禁用 额外拼音功能和 unicode 功能，  

请问额外拼音功能的作用是啥？

**Comment by rocka** [comment]
> 请问额外拼音功能的作用是啥？

拼音中的笔画筛选（快捷键 <kbd>\`</kbd> 反引号）以及笔画输入（`hspnz` 对应 `横竖撇捺折`）

**Comment by wengxt** [comment]
禁用「某些」功能，不是禁用所有功能

**Comment by rico256-cn** [comment]
@wengxt  没事，我 编译好之后 删除掉对应的so，也算是彻底禁用了相关功能了。。。

**Comment by wengxt** [comment]
你说的问题， fcitx5 是运行在哪一侧，是在虚拟机里面还是在外面

**Comment by wengxt** [comment]
我找了个虚拟机测试了一下，因为实质问题是只要有东西读取剪贴板 vboxclient 就需要转换

即使 fcitx 不运行，我想 gnome / kde 桌面也完全会触发这种问题。

问题应当由 vboxclient 解决，特别是它已经有新剪贴板之后应该清空老的数据

![图片](https://user-images.githubusercontent.com/259684/224463201-b176371c-9f68-407a-ab56-81578185e900.png)
