### ISSUE TITLE
Foxit Reader 2.4.4.0911 无法输入中文

### ISSUE THREAD

**Issue by yar999** [fcitx/fcitx5#72]
manjaro kde环境
Foxit Reader 2.4.4.0911 无法输入中文

按快捷键也无法激活fcitx5-rime中文输入, (用fcitx4可以输入中文)

**Comment by xuzhao9** [comment]
将QT_IM_MODULE，GTK_IM_MODULE设置为fcitx，XMODIFIERS设置为“@im=fcitx”试试看？可能Foxit Reader只认识fcitx，不认识fcitx5

**Comment by wengxt** [comment]
上游带的 fcitx 的 im module 太老了，不支持 fcitx 5。建议上游更新比较合适
