### ISSUE TITLE
请协助验证下 google chrome 112版本在 wayland 环境下可否支持输入框正确显示了？

### ISSUE THREAD

**Issue by rico256-cn** [fcitx/fcitx5#721]
https://aur.archlinux.org/packages/google-chrome-dev

https://bugs.chromium.org/p/chromium/issues/detail?id=1039161
根据google 内部反馈，112版本会解决输入法的问题。

google chrome 112版本已经出来了，我在 archlinux 上运行 labwc + waybar测试使用 --ozone-platform-hint=wayland --gtk-version=4 ， 可以触发输入法状态变化，可以输入汉字，但是这次是完全看不到输入框了。不清楚如何使用使用 wayland 的原声 input_method_v3?
![image](https://user-images.githubusercontent.com/60219649/219371314-8f7488bb-3f53-4633-8b17-b6a404486357.png)

不知道是不是我的姿势不对？

/usr/lib/gtk-4.0/4.0.0目录下文件如下：

![image](https://user-images.githubusercontent.com/60219649/219370901-b92b5ca0-b891-40a3-a832-d1ca4d18872b.png)

根据下面这里的说法，fcitx5是否需要更新一下？ 我尝试用gio-querymodules 生成cache 文件不成功。
https://gitlab.gnome.org/GNOME/gtk/-/issues/1181

GTK+ 4.0 will not support IM modules, and has moved to GIO extension points:

* https://blog.gtk.org/2018/03/06/input-methods-in-gtk-4/

So there is no need to have `gtk4-query-immodules`.

**Comment by rico256-cn** [comment]
在 sway-im 1.7.2环境下，单独 使用--enable-wayland-ime 候选框是全黑色, 在 labwc 下 也是如此，位置是对了，但输入框是黑色的
![image](https://user-images.githubusercontent.com/60219649/219388199-600925ae-02f0-4c41-bb81-dc1370f1c726.png)

**Comment by rico256-cn** [comment]
fcitx5-configtool 界面也是全黑， 请问要怎么解决啊。  我的环境是 archlinux.

**Comment by wengxt** [comment]
不知道，我不研究sway自己的问题。

**Comment by rico256-cn** [comment]
@wengxt 输入框和 config 工具都是 qt 渲染的吧？感觉 chrome 问题解了，主要就是 qt 应用不能正常显示的问题需要排查下了，这个可否提供一些线索
