### ISSUE TITLE
fcitx5-remote core dumped

### ISSUE THREAD

**Issue by baoheping** [fcitx/fcitx5#723]
fcitx5-remote命令在Linux终端里面调用没有问题，但在websocketd服务中调用时会报错。比如，我在shell脚本中调用fcitx5-remote -o 或者 fcit5-remote -s pinyin，并且这个脚本在websocketd服务中被执行时，会报core dumped 错误。下面是websocketd的报错日志内容：

Sun, 19 Feb 2023 17:15:16 +0800 | INFO   | server     |  | Serving using application   : /usr/bin/bash ws_manager.sh
Sun, 19 Feb 2023 17:15:16 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://ubuntusrv:8080/
Sun, 19 Feb 2023 17:15:16 +0800 | INFO   | server     |  | Developer console enabled   : http://ubuntusrv:8080/
Sun, 19 Feb 2023 17:15:21 +0800 | ACCESS | http       | url:'http://localhost:8080/' | DEVCONSOLE
Sun, 19 Feb 2023 17:15:21 +0800 | ACCESS | http       | url:'http://localhost:8080/favicon.ico' | DEVCONSOLE
Sun, 19 Feb 2023 17:15:24 +0800 | ACCESS | session    | url:'http://localhost:8080/' id:'1676798124487563879' remote:'::1' command:'/usr/bin/bash' origin:'http://localhost:8080' | CONNECT
Sun, 19 Feb 2023 17:15:29 +0800 | ERROR  | stderr     | url:'http://localhost:8080/' id:'1676798124487563879' remote:'::1' command:'/usr/bin/bash' origin:'http://localhost:8080' pid:'2787' | terminate called after throwing an instance of 'std::runtime_error'
Sun, 19 Feb 2023 17:15:29 +0800 | ERROR  | stderr     | url:'http://localhost:8080/' id:'1676798124487563879' remote:'::1' command:'/usr/bin/bash' origin:'http://localhost:8080' pid:'2787' |   what():  Failed to create dbus connection
Sun, 19 Feb 2023 17:15:29 +0800 | ERROR  | stderr     | url:'http://localhost:8080/' id:'1676798124487563879' remote:'::1' command:'/usr/bin/bash' origin:'http://localhost:8080' pid:'2787' | /home/htht/script/wss_local/im_set_chinese.sh: line 19:  2821 Aborted                 (core dumped) fcitx5-remote -o

**Comment by rocka** [comment]
`fcitx5-remote` 命令需要连接 session bus 调用 dbus 上 Fcitx5 的接口才能使用
https://github.com/fcitx/fcitx5/blob/22454ff00ade7cf3c36e3958474a4807bb733f7f/src/lib/fcitx-utils/dbus/libdbus/bus.cpp#L257-L268
请检查运行的程序是否能连接到 dbus ，比如 DBUS_SESSION_BUS_ADDRESS 或 XDG_RUNTIME_DIR 环境变量，或者运行程序用户的权限

**Comment by baoheping** [comment]
环境变量分别是unix:path=/run/user/1000/bus和/run/user/1000，用sudo启动websocketd服务并sudo执行脚本也报同样的错误。

**Comment by rocka** [comment]
是那个 websocketd 运行 `fcitx5-remote` 时的环境变量，不是用户的环境变量。建议在 im_set_chinese.sh 里输出一下这两个变量的值看看。

**Comment by baoheping** [comment]
im_set_chinese.sh里面打印出来的是空串。说明websocketd这个服务不能连接dbus是吗？

**Comment by rocka** [comment]
是的。这不是 fcitx 的问题。

**Comment by wengxt** [comment]
建议从你的websocketd的用户开始检查

如果实现成systemd user unit大概能直接用

**Comment by baoheping** [comment]
换了一种方式实现输入法切换：xdotool key ctrl+shift
