### ISSUE TITLE
在 Firefox wayland 中唤起 fcitx 疑似唤起了 x11 版本的 fcitx

### ISSUE THREAD

**Issue by yfwz100** [fcitx/fcitx5#725]
**Describe the bug**

在 Firefox wayland 中唤起 fcitx 疑似唤起了 x11 版本的 fcitx ，现象如下：
1. 输入法本身比较模糊（Plasma 5.24 还不支持独立设置 xwayland 的缩放因子，因此采用了软件缩放的效果，因此模糊）;
2. 输入法的位置不对，基本上是光标距离的两倍，和软件缩放的效果类似。
3. 在 Firefox x11 没有这个问题，输入法正常跟随光标。

不知道是 fcitx 配置的原因还是 Firefox wayland 支持的原因？

**To Reproduce**

1. 打开 Firefox wayland （即设置环境变量 MOZ_ENABLE_WAYLAND 后启动 Firefox）；
2. 按 ctrl+space 唤起输入法。

**Expected behavior**

应该和其他 wayland 程序（主要是 KDE 应用）一样，输入法显示清晰且能跟随光标。

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.
   <details>
     <summary>fcitx5-diagnose 的输出</summary>

   # 系统信息:
   1.  `uname -a`:
   
           Linux zhi-mbp 5.19.0-35-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 3 18:36:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
   
   2.  `lsb_release -a`:
   
           No LSB modules are available.
           Distributor ID: Ubuntu
           Description:    Ubuntu 22.10
           Release:        22.10
           Codename:       kinetic
   
   3.  `lsb_release -d`:
   
           Description:    Ubuntu 22.10
   
   4.  `/etc/lsb-release`:
   
           DISTRIB_ID=Ubuntu
           DISTRIB_RELEASE=22.10
           DISTRIB_CODENAME=kinetic
           DISTRIB_DESCRIPTION="Ubuntu 22.10"
   
   5.  `/etc/os-release`:
   
           PRETTY_NAME="Ubuntu 22.10"
           NAME="Ubuntu"
           VERSION_ID="22.10"
           VERSION="22.10 (Kinetic Kudu)"
           VERSION_CODENAME=kinetic
           ID=ubuntu
           ID_LIKE=debian
           HOME_URL="https://www.ubuntu.com/"
           SUPPORT_URL="https://help.ubuntu.com/"
           BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
           PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
           UBUNTU_CODENAME=kinetic
           LOGO=ubuntu-logo
   
   6.  桌面环境：
       桌面环境为 `kde`。
   7.  XDG 会话类型：
           XDG_SESSION_TYPE='wayland'
   
   8.  Bash 版本：
           BASH_VERSION='5.2.2(1)-release'
   
   # 环境：
   1.  DISPLAY:
   
           DISPLAY=':1'
   
   
           WAYLAND_DISPLAY='wayland-0'
   
   2.  键盘布局：
       1.  `setxkbmap`:
   
               WARNING: Running setxkbmap against an XWayland server
               xkb_keymap {
                   xkb_keycodes  { include "evdev+aliases(qwerty)" };
                   xkb_types     { include "complete"      };
                   xkb_compat    { include "complete"      };
                   xkb_symbols   { include "pc+us+inet(evdev)"     };
                   xkb_geometry  { include "pc(pc105)"     };
               };
   
       2.  `xprop`:
   
               _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
   
   3.  Locale：
       1.  全部可用 locale：
               C
               C.utf8
               en_AG
               en_AG.utf8
               en_AU.utf8
               en_BW.utf8
               en_CA.utf8
               en_DK.utf8
               en_GB.utf8
               en_HK.utf8
               en_IE.utf8
               en_IL
               en_IL.utf8
               en_IN
               en_IN.utf8
               en_NG
               en_NG.utf8
               en_NZ.utf8
               en_PH.utf8
               en_SG.utf8
               en_US.utf8
               en_ZA.utf8
               en_ZM
               en_ZM.utf8
               en_ZW.utf8
               POSIX
               zh_CN.utf8
   
       2.  当前 locale：
               LANG=zh_CN.UTF-8
               LANGUAGE=zh_CN:zh
               LC_CTYPE="zh_CN.UTF-8"
               LC_NUMERIC="zh_CN.UTF-8"
               LC_TIME="zh_CN.UTF-8"
               LC_COLLATE="zh_CN.UTF-8"
               LC_MONETARY="zh_CN.UTF-8"
               LC_MESSAGES="zh_CN.UTF-8"
               LC_PAPER="zh_CN.UTF-8"
               LC_NAME="zh_CN.UTF-8"
               LC_ADDRESS="zh_CN.UTF-8"
               LC_TELEPHONE="zh_CN.UTF-8"
               LC_MEASUREMENT="zh_CN.UTF-8"
               LC_IDENTIFICATION="zh_CN.UTF-8"
               LC_ALL=
   
   4.  目录：
       1.  主目录：
               /home/zhi
   
       2.  `${XDG_CONFIG_HOME}`:
   
           环境变量 `XDG_CONFIG_HOME` 没有设定。
           `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/zhi/.config`)。
       3.  Fcitx5 设置目录：
           当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/zhi/.config/fcitx5`)。
   5.  当前用户：
       脚本作为 zhi (1000) 运行。

   # Fcitx状态:

   1.  可执行文件：
       在 `/usr/bin/fcitx5` 找到了 fcitx5。

   2.  版本：
       Fcitx 版本: `5.0.18`
   
   3.  进程：
       找到了 1 个 fcitx5 进程：
           12121 fcitx5
   
   4.  `fcitx5-remote`:
   
       `fcitx5-remote` 工作正常。

   5.  DBus 界面：

       使用 `dbus-send` 来检查 dbus。

       DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.413`。

       DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `12121`。

       来自 dbus 的调试信息：

           Group [x11::1] has 4 InputContext(s)
           IC [fcd1085240ce490083e105d5234d98c4] program:firefox frontend:fcitx4 cap:1000012 focus:0
           IC [02bedf1b19f04679b7b787fb68f3006c] program:firefox frontend:fcitx4 cap:1000012 focus:0
           IC [04d840c2b00c4f9f80276d955e95df35] program:firefox frontend:fcitx4 cap:1000012 focus:0
           IC [758f499f5fd54c838a1833858b132d74] program:firefox frontend:fcitx4 cap:1000052 focus:0
           Group [wayland:] has 4 InputContext(s)
           IC [76dd89098ec8471cb2dd9ed8e7b4e4ca] program:konsole frontend:dbus cap:e001800072 focus:1
           IC [cf7814f7ec8b43d6933c3a29fe135eb5] program:plasmashell frontend:dbus cap:e001820072 focus:0
           IC [ce078086bd8b4af08daa508188c4c4bb] program:systemsettings frontend:dbus cap:e001800072 focus:0
           IC [c84f38f4b4034be08b87f3124cf33162] program:plasmashell frontend:dbus cap:e001800072 focus:0
           Input Context without group
   
   # Fcitx 配置界面：

   1.  配置工具封装：
       在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

   2.  Qt 的配置界面：
       在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

   3.  KDE 的配置界面：
       找到了 fcitx5 的 kcm 模块。
           kcm_fcitx5                     - 配置输入法

   # 前端设置：
   ## Xim:
   1.  `${XMODIFIERS}`:
   
       环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。    从环境变量中获取的 Xim 服务名称为 fcitx.
   
   2.  根窗口上的 XIM_SERVERS：
       Xim 服务的名称与环境变量中设置的相同。

   ## Qt:

   1.  qt4 - `${QT4_IM_MODULE}`:
   
       环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

   2.  qt5 - `${QT_IM_MODULE}`:
   
       环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

   3.  Qt 输入法模块文件：

       找到了 fcitx5 qt5 模块：`/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。    找到了 fcitx5 的 qt5 输入法模块：`/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。    找到了未知的 fcitx qt 模块：`/lib/x86_64-linux-gnu/qt5/plugins/kcms/kcm_fcitx5.so`。    找到了 fcitx5 的 qt6 输入法模块：`/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。    **无法找到 Qt4 的 fcitx5 输入法模块。**
   
   ## Gtk:

   1.  gtk - `${GTK_IM_MODULE}`:
   
       环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

   2.  `gtk-query-immodules`:
   
       1.  gtk 2:
   
           **无法找到 gtk 2 的 `gtk-query-immodules`。**
   
           **无法找到 gtk 2 的 fcitx5 输入法模块。**
   
       2.  gtk 3:
   
           **无法找到 gtk 3 的 `gtk-query-immodules`。**
   
           **无法找到 gtk 3 的 fcitx5 输入法模块。**
   
   3.  Gtk 输入法模块缓存：

       1.  gtk 2:
   
           **无法找到 gtk 2 的输入法模块缓存**
   
           **无法在缓存中找到 gtk 2 的 fcitx5 输入法模块。**
   
       2.  gtk 3:
   
           在 `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.34` 的输入法模块缓存。        版本行：
               # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.34
   
           已找到 gtk `3.24.34` 的 fcitx5 输入法模块。

               "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
               "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
               "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
   
       3.  gtk 4:
   
           **无法找到 gtk 4 的输入法模块缓存**
   
           **无法在缓存中找到 gtk 4 的 fcitx5 输入法模块。**
   
   4.  Gtk 输入法模块文件：

       1.  gtk 2:
   
           找到的全部 Gtk 2 输入法模块文件均存在。

       2.  gtk 3:
   
           找到的全部 Gtk 3 输入法模块文件均存在。

       3.  gtk 4:
   
           找到的全部 Gtk 4 输入法模块文件均存在。

   # 配置:

   ## Fcitx 插件：

   1.  插件配置文件目录：
       找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

   2.  插件列表：

       1.  找到了 28 个已启用的插件：

               Simplified and Traditional Chinese Translation 5.0.14
               Classic User Interface 5.0.18
               Clipboard 5.0.18
               Cloud Pinyin 5.0.14
               DBus 5.0.18
               DBus Frontend 5.0.18
               Emoji 5.0.18
               Fcitx4 Frontend 5.0.18
               Full width character 5.0.14
               IBus Frontend 5.0.18
               Lua IME API 5.0.9
               Input method selector 5.0.18
               Keyboard 5.0.18
               KDE Input Method Panel 5.0.18
               Lua Addon Loader 5.0.9
               Status Notifier 5.0.18
               Notification 5.0.18
               Pinyin 5.0.14
               Extra Pinyin functionality 5.0.14
               Punctuation 5.0.14
               Quick Phrase 5.0.18
               Spell 5.0.18
               Table 5.0.14
               Unicode 5.0.18
               Wayland 5.0.18
               Wayland Input method frontend 5.0.18
               XCB 5.0.18
               X Input Method Frontend 5.0.18
   
       2.  找到了 0 个被禁用的插件：

   3.  插件库: 
   
       所有插件所需的库都被找到。

   4.  用户界面：

       找到了 2 个已启用的用户界面插件：
           Classic User Interface
           KDE Input Method Panel
   
   ## 输入法：

   1.  `/home/zhi/.config/fcitx5/profile`:
   
           [Groups/0]
           # Group Name
           Name=默认        # Layout
           Default Layout=us
           # Default Input Method
           DefaultIM=pinyin
   
           [Groups/0/Items/0]
           # Name
           Name=keyboard-us
           # Layout
           Layout=
   
           [Groups/0/Items/1]
           # Name
           Name=pinyin
           # Layout
           Layout=
   
           [GroupOrder]
           0=默认

   # 日志：

   1.  `date`:
   
           2023年 02月 22日 星期三 23:17:46 CST
   
   2.  `/home/zhi/.config/fcitx5/crash.log`:
   
       `/home/zhi/.config/fcitx5/crash.log` 未找到.
   </details>

**Additional context**

**Comment by wengxt** [comment]
你的 firefox 使用了 fcitx4 的 im module

IC [fcd1085240ce490083e105d5234d98c4] program:firefox frontend:fcitx4 cap:1000012 focus:0
IC [02bedf1b19f04679b7b787fb68f3006c] program:firefox frontend:fcitx4 cap:1000012 focus:0
IC [04d840c2b00c4f9f80276d955e95df35] program:firefox frontend:fcitx4 cap:1000012 focus:0
IC [758f499f5fd54c838a1833858b132d74] program:firefox frontend:fcitx4 cap:1000052 focus:0

我不知道是因为你的 firefox 也许是 snap 的原因，还是因为你同时也安装了 fcitx4 的 im module 的原因。

如果 firefox 是 snap，建议装普通的 firefox，如果你装了 fcitx-frontend-gtk3 （不是 fcitx5-frontend-gtk3），那你可以卸载

或者 GTK_IM_MODULE=fcitx5 也应该能让他用fcitx5 的 im module，当然如果 snap 里面没有那也没办法 ´_>` ……

**Comment by yfwz100** [comment]
这么回事，我用的是 snap 的。是不是换回 fcitx 4 就可以？

**Comment by wengxt** [comment]
snap应该还没打什么fcitx5相关的吧，毕竟进ubuntu源时间还不长…我甚至都不知道去哪报bug

flatpak我都很勤快的把runtime里的都替换为fcitx5的了
