### ISSUE TITLE
Have you team considered to integrate fcitx(fcitx5) into KDE plasma by default?

### ISSUE THREAD

**Issue by wen-zheng** [fcitx/fcitx5#731]
I know Weng Xuetian (the main contributor of fcitx5) is also a KDE developer, so have you considered to integrate fcitx5 into KDE plasma by default (have you submitted a similar proposal to the KDE team)?  gnome has integrated ibus by default, why not KDE integrates fcitx5 by default? haha, just a proposal

**Comment by CoelacanthusHex** [comment]
I don't think it's necessary at all, the integration has two parts, startup and configuration. Regarding startup, fcitx5 already has its own xdg startup file; regarding configuration, kde’s setting center can be extended by a third party using kcm (while gnome’s setting center is hard-coded, and third parties cannot be extended during runtime, it must be supported by gnome self), no need to be integrated by kde, and fcitx5 has already realized this part of the function.
The only change that might be needed is to make fcitx5 a mandatory dependency for plasma like gnome does for ibus, but that's by no means a good thing for the Linux desktop environment ecosystem.

**Comment by wen-zheng** [comment]
yes, but input method is actually a necessary part of desktop environments, ibus is out of box on most distros using gnome, while ibus/fcitx is not out of box on most distros using KDE.

**Comment by wen-zheng** [comment]
如果我们完全站在用户体验的角度来看这个问题，毫无疑问，gnome做的不错，因为对于CNHK用户，他们无需做额外的操作，输入法就是可用的，但是kde不然，而fcitx却是kde下（linux桌面世界）用户体验最好的，单纯站在用户体验的角度来看，集成fcitx到kde无论是对kde还是fcitx都是一件好事。同样的例子在linux世界层出不穷，比如systemd，比如network-manager，虽然在精神上这有些monopoly的意味，但是对用户体验来说，无疑是积极影响大于消极影响

**Comment by CoelacanthusHex** [comment]
> 如果我们完全站在用户体验的角度来看这个问题，毫无疑问，gnome做的不错，因为对于CNHK用户，他们无需做额外的操作，输入法就是可用的，但是kde不然，

对我来说并不是这样，他的默认集成 ibus 根本无法满足我的需求，而 GNOME 集成 ibus 后几乎完全放弃了对其他输入法的支持，很多界面在 Wayland 下只有 ibus 才能弹出输入法，并且在 Wayland 下拒绝支持标准的 input-method 协议，仅支持 ibus 的私有协议，导致所有不支持 ibus 私有协议的输入法无法在 wayland gnome 环境下使用（fcitx5 能使用单纯是因为开发者实现了 ibus 的协议以换取兼容性）。这实际上是对 Linux 桌面环境输入法生态的极大破坏，从片面看提升了普通 GNOME 用户的输入法体验，却从整体上严重破坏了所有输入法用户的体验。

> 而fcitx却是kde下（linux桌面世界）用户体验最好的，单纯站在用户体验的角度来看，集成fcitx到kde无论是对kde还是fcitx都是一件好事。同样的例子在linux世界层出不穷，比如systemd，比如network-manager，虽然在精神上这有些monopoly的意味，但是对用户体验来说，无疑是积极影响大于消极影响

我赞同集成输入法，但不赞同由 KDE 集成 Fcitx5，原因如上，如果真的要集成，应该设计一个规范使得所有桌面环境可以自动集成所有实现了标准规范的输入法，而不是每个桌面环境各自集成一个输入法然后别的输入法就不管了，这会极大地分裂 Linux 桌面环境的生态。

**Comment by wen-zheng** [comment]
所以貌似应该给freedesktop提需求😞
