### ISSUE TITLE
“固定嵌入预编辑文本光标在预编辑的开头”在某些情况下无效

### ISSUE THREAD

**Issue by alohaia** [fcitx/fcitx5#733]
**Describe the bug**

“固定嵌入预编辑文本光标在预编辑的开头”，也就是 `PreeditCursorPositionAtBeginning=True` 在 kitty 终端、Chrome 网址栏无效，所使用的输入法是 rime。

**To Reproduce**

在 kitty 或 Chrome 网址栏使用输入法输入。

**Expected behavior**

光标和预选框固定在预编辑文本的开头。

**Desktop (please complete the following information):**

 - Desktop: KDE
 - Display server type: X11

# 系统信息:
1.  `uname -a`:

        Linux Hostname 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	Arch
        Description:	Arch Linux
        Release:	rolling
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	Arch Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="Arch"
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

6.  桌面环境：

    桌面环境为 `kde`。

7.  XDG 会话类型：

        XDG_SESSION_TYPE='x11'

8.  Bash 版本：

        BASH_VERSION='5.1.16(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn(altgr-pinyin)+inet(evdev)+capslock(swapescape)+compose(ralt)"	};
            	xkb_geometry  { include "pc(pc86)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc86", "cn", "altgr-pinyin", "caps:swapescape,compose:ralt"

3.  Locale：

    1.  全部可用 locale：

            C
            C.UTF-8
            en_GB.utf8
            POSIX
            zh_CN.utf8

    2.  当前 locale：

            LANG=en_GB.UTF-8
            LC_CTYPE="en_GB.UTF-8"
            LC_NUMERIC="en_GB.UTF-8"
            LC_TIME="en_GB.UTF-8"
            LC_COLLATE="en_GB.UTF-8"
            LC_MONETARY="en_GB.UTF-8"
            LC_MESSAGES="en_GB.UTF-8"
            LC_PAPER="en_GB.UTF-8"
            LC_NAME="en_GB.UTF-8"
            LC_ADDRESS="en_GB.UTF-8"
            LC_TELEPHONE="en_GB.UTF-8"
            LC_MEASUREMENT="en_GB.UTF-8"
            LC_IDENTIFICATION="en_GB.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/xxx

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/xxx/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/xxx/.config/fcitx5`)。

5.  当前用户：

    脚本作为 xxx (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: `5.0.21`

3.  进程：

    找到了 2 个 fcitx5 进程：

          16541 fcitx5
          16544 fcitx5-plasma-t

4.  `fcitx5-remote`:

    `fcitx5-remote` 工作正常。

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.302`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `16541`。

    来自 dbus 的调试信息：

           Group [x11::0] has 9 InputContext(s)
          IC [7cd10555817443d8a0471ea86062c2e7] program:kwin_x11 frontend:dbus cap:16000800072 focus:0
          IC [b93b4ffc46cd4fbf84c9e43d6dbfce6e] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [7a5d936df21745ea887e65cfa8eba323] program:systemsettings frontend:dbus cap:6000800072 focus:0
          IC [ac36ffa01d294a25a34d7527dfc5007f] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [4df1efdb7f964923a1d07119f665eb64] program:google-chrome frontend:dbus cap:6000000012 focus:0
          IC [8e407ca6ae364aec8a519ee2701bc234] program:plasmashell frontend:dbus cap:16000800072 focus:0
          IC [8e5e0f644fb345edbcc61432aae09a62] program:linuxqq frontend:dbus cap:6000000012 focus:0
          IC [e9688c0383734185ac6fb2ccfc4c94ef] program:okular frontend:dbus cap:16000800072 focus:0
          IC [5ee52ed662fb47d59d0d46dc098ec2fb] program: frontend:ibus cap:12 focus:1
        Input Context without group

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

    找到了 fcitx5 的 kcm 模块。

        kcm_fcitx5                     - 配置输入法

# 前端设置：
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    Xim 服务的名称与环境变量中设置的相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

3.  Qt 输入法模块文件：

    找到了 fcitx5 的 qt 输入法模块：`/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了未知的 fcitx qt 模块：`/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`。
    找到了 fcitx5 qt5 模块：`/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    找到了 fcitx5 的 qt6 输入法模块：`/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。

    下列错误也许并不准确，因为对 Qt 版本的猜测取决于发行版如何打包 Qt。如果您不使用任何对应版本的 Qt 程序，或者在 Wayland 下使用 Qt 的 text-input 支持，下列错误也也不是严重问题。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

2.  `gtk-query-immodules`:

    1.  gtk 2:

        在 `/usr/bin/gtk-query-immodules-2.0` 找到了 gtk `2.24.33` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        在 `/usr/bin/gtk-query-immodules-3.0` 找到了 gtk `3.24.36` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.36

        已找到 gtk `3.24.36` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        在 `/usr/lib/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.36` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.36

        已找到 gtk `3.24.36` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    3.  gtk 4:

        **无法找到 gtk 4 的输入法模块缓存**

        **无法在缓存中找到 gtk 4 的 fcitx5 输入法模块。**

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 20 个已启用的插件：

            Classic User Interface 5.0.21
            Clipboard 5.0.21
            DBus 5.0.21
            DBus Frontend 5.0.21
            Emoji 5.0.21
            Fcitx4 Frontend 5.0.21
            IBus Frontend 5.0.21
            Input method selector 5.0.21
            Keyboard 5.0.21
            KDE Input Method Panel 5.0.21
            Status Notifier 5.0.21
            Notification 5.0.21
            Quick Phrase 5.0.21
            Rime 5.0.15
            Spell 5.0.21
            Unicode 5.0.21
            Wayland 5.0.21
            Wayland Input method frontend 5.0.21
            XCB 5.0.21
            X Input Method Frontend 5.0.21

    2.  找到了 0 个被禁用的插件：

3.  插件库:

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 2 个已启用的用户界面插件：

        Classic User Interface
        KDE Input Method Panel

## 输入法：
1.  `/home/xxx/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=默认
        # Layout
        Default Layout=cn-altgr-pinyin
        # Default Input Method
        DefaultIM=rime

        [Groups/0/Items/0]
        # Name
        Name=keyboard-cn-altgr-pinyin
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=rime
        # Layout
        Layout=

        [GroupOrder]
        0=默认

# 日志：
1.  `date`:

        Tue 28 Feb 19:52:22 CST 2023

2.  `/home/xxx/.config/fcitx5/crash.log`:

        =========================
        Fcitx 5.0.14 -- Get Signal No.: 6
        Date: try "date -d @1646308041" if you are using GNU date ***
        ProcessID: 8210
        fcitx5(+0xd164)[0x55f41c920164]
        /usr/lib/libc.so.6(+0x42560)[0x7fc6b3a2e560]
        /usr/lib/libc.so.6(+0x8f34c)[0x7fc6b3a7b34c]
        /usr/lib/libc.so.6(raise+0x18)[0x7fc6b3a2e4b8]
        /usr/lib/libc.so.6(abort+0xd3)[0x7fc6b3a18534]
        /usr/lib/libstdc++.so.6(+0x997ee)[0x7fc6b3cac7ee]
        /usr/lib/libstdc++.so.6(+0xa5c4c)[0x7fc6b3cb8c4c]
        /usr/lib/libstdc++.so.6(+0xa4bfa)[0x7fc6b3cb7bfa]
        /usr/lib/libstdc++.so.6(__gxx_personality_v0+0x9b)[0x7fc6b3cb837b]
        /usr/lib/libgcc_s.so.1(+0x10f64)[0x7fc6b3c06f64]
        /usr/lib/libgcc_s.so.1(_Unwind_Resume+0x12e)[0x7fc6b3c079ae]
        /usr/lib/librime.so.1(+0xccfaf)[0x7fc6b0a3ffaf]
        /usr/lib/librime.so.1(_ZN4rime8DeployerD2Ev+0x17)[0x7fc6b0a7b127]
        /usr/lib/librime.so.1(_ZN4rime7ServiceD2Ev+0x3a)[0x7fc6b0a9a5aa]
        /usr/lib/librime.so.1(_ZNSt10unique_ptrIN4rime7ServiceESt14default_deleteIS1_EED2Ev+0x12)[0x7fc6b0a9d3d2]
        /usr/lib/libc.so.6(+0x44c05)[0x7fc6b3a30c05]
        /usr/lib/libc.so.6(on_exit+0x0)[0x7fc6b3a30d80]
        /usr/lib/libc.so.6(+0x2d317)[0x7fc6b3a19317]
        /usr/lib/libc.so.6(__libc_start_main+0x81)[0x7fc6b3a193c1]
        fcitx5(+0xc74e)[0x55f41c91f74e]

**Comment by wengxt** [comment]
请汇报给对应的程序。
