### ISSUE TITLE
unexpected behavior of "¥" key on jis keyboards

### ISSUE THREAD

**Issue by Hexadecimaaal** [fcitx/fcitx5#736]
**Describe the bug**
screen recording reproducing the issue:

https://user-images.githubusercontent.com/30397776/222353395-158127ac-225f-4b4b-b6cf-eb427f905d73.mp4

**To Reproduce**
1. get a jis compatible keyboard; the key left to backspace is "¥"
2. set the "System Layout" option to "Japanese (OADG 109A)"
3. using either rime or mozc, type something, while the substitution list is on-screen, press ¥
4. the ¥ appears after the input code, not highlighted
5. after pressing space to commit, the ¥ is instead inserted before the unsubstituted input codes

**Expected behavior**
¥ should behave the same way as any other symbols. (this is probably also the issue that prevents you from mapping the ¥ key under rime?)

**Desktop (please complete the following information):**
 - Desktop: KDE 5.27
 - Display server type: reproduced on both xorg and wayland
 - The output of fcitx5-diagnose: https://gist.github.com/Hexadecimaaal/33dce253197ffc3ea0b411a937d66c3f

**Comment by wengxt** [comment]
I think it's that the relevant engine doesn't handle such a unrecognized key. I would suggest you report it to rime / mozc upstream since those two engines are the kind of engines that handles all key event like a black box. Doing it in fcitx5-rime / fcitx5-mozc is more fragile to future changes.
