### ISSUE TITLE
输入法框太小

### ISSUE THREAD

**Issue by Starslayerx** [fcitx/fcitx5#74]
It's too **small**, and I don't know how to make it bigger in fcitx-configtool.
I'm using archlinux in xfce and installed compiz to replace xfwm4.
I viewed arch wiki about fcitx, but didn't find a way to slove this.
![image](https://user-images.githubusercontent.com/53030987/84287675-c7819080-ab72-11ea-94ec-18506a351959.png)
This it my configtool, I saw some people got a **appreance** config in configtool,I don't have **appreance** config.（git version)
![image](https://user-images.githubusercontent.com/53030987/84287857-03b4f100-ab73-11ea-9552-c3beb15eeb86.png)

**Comment by Starslayerx** [comment]
Thank u!

**Comment by aScHEABL** [comment]
I tried this, but it only made it worse. Specifically the input bar will be smaller than it already was.
Please check the following screenshots. @wengxt 

![Image](https://github.com/user-attachments/assets/f485d535-1b00-4ff8-a2a5-f0ae37b1ba7c)

![Image](https://github.com/user-attachments/assets/a084a5d2-941e-49f5-bd7a-4696f5ce3735)

If I clicked the font and enter "pick a font" window and adjust font size there, it doesn't make an impact to the input bar itself.

**Comment by wengxt** [comment]
@aScHEABL  size "2" is definitely super small, isn't it? larger number means larger font.

**Comment by aScHEABL** [comment]
> [@aScHEABL](https://github.com/aScHEABL) size "2" is definitely super small, isn't it? larger number means larger font.

Okay, that was stupid on my part. I thought it's an incremental thing that add on top of my original size...
For instance, the font size might be 10, and then if I input "2" on that text field then it becomes 10 + 2 = 12...
I was troubled for this issue for hours, now I feel I'm incredibly stupid...
Sorry to bother you.

**Comment by carafelix** [comment]
`nano ~/.config/fcitx5/conf/classicui.conf`
`Font="Noto Sans Regular 14"`
did it for me
