### ISSUE TITLE
Not working in Electron-based applications

### ISSUE THREAD

**Issue by JCDetwiler** [fcitx/fcitx5#740]
**Describe the bug**
I'm not able to use `Keyboard - Polish` to type diacritics in apps that are made in Electron. Affected apps for me include Element, Discord, VS Code, and probably more.

**To Reproduce**
1. Open Element (Matrix client)
2. I switch to my Polish keyboard with `Ctrl`+`Space`
3. I try to type an ó with `Right Alt`+`o`

**Expected behavior**
The `Right Alt` modifier should work like it does in GTK, QT, etc. (like how I just typed ó in Firefox just now).

**Desktop (please complete the following information):**
 - Desktop: XFCE
 - Display server type: X11
 - The output of fcitx5-diagnose: [my output here][1].

**Additional context**
Other input methods like `Pinyin` and `Mozc` still work in Electron-based programs. Moreover, I do see the popup in the textbox say it's switching to Polish, it just doesn't produce the expected text. I thought Electron might be messing with the `Right Alt` key somehow, but I tried changing the configuration to use a different modifier and no luck.

[1]: https://controlc.com/63d9a51c

**Comment by wengxt** [comment]
so basically, if a non-system keyboard layout is used by application, chrome doesn't see iso level 3 shift, instead, it still see it as right alt and when application handles the key before input method, it may cause some issues.

So far I have two options for you:
1. create another input method group, and set it's system layout as pl
    (Group 1: us pinyin mozc) (Group2: pl pinyin, mozc)
   So the PL will be the actual system layout and chrome will see the key as iso level 3 shift
2. Use XKB option to override Right Alt as ISO level 3 shift, in kde it's sth like this:
![图片](https://user-images.githubusercontent.com/259684/224523331-009f83c0-da77-4095-bd82-cc9eb40e6641.png)

**Comment by JCDetwiler** [comment]
Thank you, option 1 is exactly what I was looking for! I knew Chromium/Electron was messing with the shift you mention. I'm going to try to add this into the Arch Wiki so it's more accessible. Thanks again, and have a donation! :)
