### ISSUE TITLE
Don't display nothing even with variables on

### ISSUE THREAD

**Issue by d4n1eu04** [fcitx/fcitx5#741]
I've done everything alright to set up fcitx5 and mozc, but nothing shows up when i hit the shortcut to change input method.

I have japanese fonts, environment variables all ok (even fcitx5 diagnose shows that variables are fine)

Tried every stuff on the arch wiki also, nothing worked.
Im on Arch, using AwesomeWM.

at this point I honestly dunno if it is a real bug or there's something i've left behind, but i'm sure that i need help. 

PS: also tried installing XFCE to see if the problem was AwesomeWM but with no success.

**Comment by wengxt** [comment]
Please paste the whole output of fcitx5-diagnose.

**Comment by d4n1eu04** [comment]
[ 11:38 ]  [ daniell@Vivobook15:~ ]
 $ fcitx5-diagnose
# System Info:
1.  `uname -a`:

        Linux Vivobook15 6.2.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:40 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

5.  Desktop Environment:

    Cannot determine desktop environment.

6.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

7.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'


        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+br+inet(evdev)"};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "abnt2", "br", "", ""

3.  Locale:

    1.  All locales:

            C
            C.UTF-8
            POSIX
            pt_BR.utf8

    2.  Current locale:

            LANG=pt_BR.UTF-8
            LC_CTYPE="pt_BR.UTF-8"
            LC_NUMERIC="pt_BR.UTF-8"
            LC_TIME="pt_BR.UTF-8"
            LC_COLLATE="pt_BR.UTF-8"
            LC_MONETARY="pt_BR.UTF-8"
            LC_MESSAGES="pt_BR.UTF-8"
            LC_PAPER="pt_BR.UTF-8"
            LC_NAME="pt_BR.UTF-8"
            LC_ADDRESS="pt_BR.UTF-8"
            LC_TELEPHONE="pt_BR.UTF-8"
            LC_MEASUREMENT="pt_BR.UTF-8"
            LC_IDENTIFICATION="pt_BR.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/daniell

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/daniell/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/daniell/.config/fcitx5`).

5.  Current user:

    The script is run as daniell (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.22`

3.  process:

    **Fcitx5 is not running.**
    **Please check the Configure link of your distribution in [Beginner's Guide](http://fcitx-im.org/wiki/Beginner%27s_Guide) for how to setup fcitx5 autostart.**

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.37` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.37

        Found fcitx5 im modules for gtk `3.24.37`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found immodules cache for gtk `3.24.37` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.37

        Found fcitx5 im modules for gtk `3.24.37`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 17 enabled addons:

            Classic User Interface 5.0.22
            Clipboard 5.0.22
            DBus 5.0.22
            DBus Frontend 5.0.22
            Emoji 5.0.22
            Fcitx4 Frontend 5.0.22
            IBus Frontend 5.0.22
            Input method selector 5.0.22
            Keyboard 5.0.22
            Mozc
            Status Notifier 5.0.22
            Notification 5.0.22
            Quick Phrase 5.0.22
            Spell 5.0.22
            Unicode 5.0.22
            XCB 5.0.22
            X Input Method Frontend 5.0.22

    2.  Found 3 disabled addons:

            KDE Input Method Panel 5.0.22
            Wayland 5.0.22
            Wayland Input method frontend 5.0.22

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 1 enabled user interface addons:

        Classic User Interface

## Input Methods:
1.  `/home/daniell/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=br
        # Default Input Method
        DefaultIM=mozc

        [Groups/0/Items/0]
        # Name
        Name=keyboard-br
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=mozc
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        ter 14 mar 2023 23:39:31 -03

2.  `/home/daniell/.config/fcitx5/crash.log`:

    `/home/daniell/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by wengxt** [comment]
It says fcitx is not running.

Also what’s your desktop?

can you run fcitx5-diagnose again when fcitx5 and some application that you want to type with fcitx5 are both running?

**Comment by d4n1eu04** [comment]
[ 12:15 ]  [ daniell@Vivobook15:~ ]
 $ fcitx5-diagnose
# System Info:
1.  `uname -a`:

        Linux Vivobook15 6.2.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:40 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

5.  Desktop Environment:

    Cannot determine desktop environment.

6.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

7.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'


        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+br+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "abnt2", "br", "", ""

3.  Locale:

    1.  All locales:

            C
            C.UTF-8
            POSIX
            pt_BR.utf8

    2.  Current locale:

            LANG=pt_BR.UTF-8
            LC_CTYPE="pt_BR.UTF-8"
            LC_NUMERIC="pt_BR.UTF-8"
            LC_TIME="pt_BR.UTF-8"
            LC_COLLATE="pt_BR.UTF-8"
            LC_MONETARY="pt_BR.UTF-8"
            LC_MESSAGES="pt_BR.UTF-8"
            LC_PAPER="pt_BR.UTF-8"
            LC_NAME="pt_BR.UTF-8"
            LC_ADDRESS="pt_BR.UTF-8"
            LC_TELEPHONE="pt_BR.UTF-8"
            LC_MEASUREMENT="pt_BR.UTF-8"
            LC_IDENTIFICATION="pt_BR.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/daniell

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/daniell/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/daniell/.config/fcitx5`).

5.  Current user:

    The script is run as daniell (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.22`

3.  process:

    Found 1 fcitx5 process:

          28413 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.57`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `28413`.

    Debug information from dbus:

           Group [x11::0] has 0 InputContext(s)
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.37` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.37

        Found fcitx5 im modules for gtk `3.24.37`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found immodules cache for gtk `3.24.37` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.37

        Found fcitx5 im modules for gtk `3.24.37`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 17 enabled addons:

            Classic User Interface 5.0.22
            Clipboard 5.0.22
            DBus 5.0.22
            DBus Frontend 5.0.22
            Emoji 5.0.22
            Fcitx4 Frontend 5.0.22
            IBus Frontend 5.0.22
            Input method selector 5.0.22
            Keyboard 5.0.22
            Mozc
            Status Notifier 5.0.22
            Notification 5.0.22
            Quick Phrase 5.0.22
            Spell 5.0.22
            Unicode 5.0.22
            XCB 5.0.22
            X Input Method Frontend 5.0.22

    2.  Found 3 disabled addons:

            KDE Input Method Panel 5.0.22
            Wayland 5.0.22
            Wayland Input method frontend 5.0.22

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 1 enabled user interface addons:

        Classic User Interface

## Input Methods:
1.  `/home/daniell/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=br
        # Default Input Method
        DefaultIM=mozc

        [Groups/0/Items/0]
        # Name
        Name=keyboard-br
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=mozc
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        qua 15 mar 2023 00:15:53 -03

2.  `/home/daniell/.config/fcitx5/crash.log`:

    `/home/daniell/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by d4n1eu04** [comment]
maybe it can be something related to ibus or dbus, but i'm not sure.

**Comment by wengxt** [comment]
@d4n1eu04 how do you start xfce? also in what application you tried it doesn’t work?

**Comment by d4n1eu04** [comment]
im using lightdm to start, and every single application don't work

**Comment by wengxt** [comment]
what’s the output of `echo $DBUS_SESSION_BUS_ADDRESS` ?

Also, even if it looks right in terminal, it doesn’t mean the environment variable is set against the desktop session.

Can you also check if you start an application from the terminal, does it work?

Which file did you put the settings of XMODIFIERS GTK_IM_MODULE, QT_IM_MODULE?

**Comment by d4n1eu04** [comment]
$ echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/run/user/1000/bus 

That's the output

**Comment by d4n1eu04** [comment]
Even opening things from terminal it doesn't work.

The XMODIERS stuff is in my .zshenv

**Comment by wengxt** [comment]
I doubt .zshenv is read by lightdm. 

Can you try: `env GTK_IM_MODULE=fcitx gtk3-demo-application` (available in gtk3-demos) and see if fcitx5 can work there.

If it works there (try "Ctrl + ;" , it should show a clipboard popup from fcitx ), consider put 
```
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
```
lines in ~/.xprofile and re-login.

You may also verify the environment variable with /proc. 
E.g. you can start an application, and then use `strings /proc/[pid of the app]/environ` to inspect the actual value.

**Comment by d4n1eu04** [comment]
Dude thank you soooooo much, after all the issue was on me hahaha, now it works.
Honestly I never messed with the env variables on Linux that much.
