### ISSUE TITLE
外观上，可添加圆角吗？

### ISSUE THREAD

**Issue by bczhc** [fcitx/fcitx5#745]
如题。找了几个fcitx5主题，总感觉还是不太对劲，才发现是缺了圆角的问题。

**Comment by yunsii** [comment]
支持配置但是做个提示如果系统兼容性就放弃这个特性，不知道这个方案怎么样？

**Comment by bczhc** [comment]
我是用picom做到的，这玩意在Linux上都是交给compositor做的，软件应该无能为力。

**Comment by yunsii** [comment]
Linux 这么神奇嘛？不过做不了就算了，我就不折腾了 😂 稍微调整下也比默认主题好多了

**Comment by wengxt** [comment]
只是看着圆角是很简单的，背景图片是带透明的圆角即可 

![图片](https://github.com/user-attachments/assets/cfe1ba9c-0765-46f1-9ce0-1306b6133862)

原理就是背景图片切九宫格，图片透明即可 https://fcitx-im.org/wiki/Fcitx_5_Theme

但是没有打算修改默认主题。

**Comment by yunsii** [comment]
感谢大佬的补充说明，有机会我试试 😄

**Comment by wengxt** [comment]
我的截图是内置的自动基于 kde 主题生成的功能

![图片](https://github.com/user-attachments/assets/cce2b5b7-6f1b-4f57-8bdd-62f78134c4e6)

**Comment by yunsii** [comment]
再次感谢，我现在就是基于一个主题改的，不过当时没注意到哪个做了圆角的，这下不得不试试了。
