### ISSUE TITLE
Likely regression in 5.0.22: Issues with key bindings involving modifiers in GTK apps

### ISSUE THREAD

**Issue by Ben-Kerman** [fcitx/fcitx5#747]
Key bindings that consist only of super and another modifier key no longer work in some programs, seemingly only GTK apps. The bindings in question work without problem in programs using Qt (as well as Alacritty, which afaik isn't either Qt or GTK). Prior to 5.0.21 these same bindings worked just fine in all programs I use.

**To Reproduce:**
1. Set any (global?) key binding to super+right/left alt or super+right/left shift, for example as in the image below.
2. Try using the binding in a GTK app after applying the settings.

![](https://user-images.githubusercontent.com/21299619/225640960-bb106231-e6c0-4146-90f8-5ac977e9db0c.png)

**Desktop:**
- System: Arch Linux
- Display server: X11
- Desktop: none (i3)

[Output of fcitx5-diagnose](https://github.com/fcitx/fcitx5/files/10996438/fcitx5-diagnose-output.txt)

---

I did skim through recent issues to see if there already was one about this and didn't find one in English. I don't know Chinese, so sorry if this was already reported.

**Comment by wengxt** [comment]
The issue is due to adding the handling for gtk's virtual super mask.

**Comment by Ben-Kerman** [comment]
Works like a charm after updating to 5.0.23. Thanks for the fix!
