### ISSUE TITLE
在firefox中使用fcitx时，在打得较快的情况下keydown event会有丢失。chrome下一个按键对应2个keydown

### ISSUE THREAD

**Issue by Frefreak** [fcitx/fcitx5#748]
**Describe the bug**

**firefox**
如题，keyup事件几乎正常，但keydown事件在输入很快时会有概率缺失（输入的内容是正确无误的）。怀疑当按键弹起时间短的时候更容易发生。
![image](https://user-images.githubusercontent.com/7122156/226379251-a38efa84-2718-4f61-a022-eaab802de351.png)

**chrome**
输入法composing时按一下字母，对应2个一样的keydown event，keyCode = 229, key = unidentified

**To Reproduce**

**firefox**

1. 用下面这段html/javascript在firefox中打开
2. 很快速的用输入法进行输入，或用再下面这段脚本模拟输入（需要根据输入法调整模拟的按键）

textarea中输入前先点击clear arr清空并打开控制台，切换到输入法，输入完成后点击print arr在控制台中观察keydown和keyup记录的按键

**chrome**

直接在输入法下按一个键，观察console输出

**firefox复现相关脚本**

html:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
  </head>
  <body>
    <textarea id="txt"></textarea>
    <button id='btn_clear'>clear arr</button>
    <button id='btn_print'>print arr</button>
    <script>
      var keydown_arr = []
      var keyup_arr = []
      document.getElementById('txt').addEventListener('keydown', function(e) {
        console.log('down ', e)
        keydown_arr.push(e.code)
      })
      document.getElementById('txt').addEventListener('keyup', function(e) {
        console.log('up ', e)
        if (e.key != 'Process') {
          keyup_arr.push(e.code)
        }
      })
      document.getElementById('btn_clear').addEventListener('click', function(e) {
        keydown_arr = []
        keyup_arr = []
      })
      document.getElementById('btn_print').addEventListener('click', function(e) {
        console.log('keydown ', keydown_arr)
        console.log('keyup', keyup_arr)
      })
    </script>
  </body>
</html>

```

```sh
#!/usr/bin/env bash

sleep 3
xdotool key --delay 50 f space
xdotool key --delay 50 m e space
xdotool key --delay 50 t s space
xdotool key --delay 50 y s space
xdotool key --delay 50 w u space
xdotool key --delay 50 a l space
xdotool key --delay 50 r q space
xdotool key --delay 50 h b space
xdotool key --delay 50 k j space
xdotool key --delay 50 d k k space

```

**Expected behavior**

**firefox**
keyup和keydown记录的按键一样 （实际不一样，keyup的可能会比keydown的要多）

**chrome**
和firefox类似或是和其它平台上chrome的表现一致

**Desktop (please complete the following information):**
 - Desktop: KDE （5.27.2）
 - Display server type: X11

**Comment by wengxt** [comment]
你能用 dbus-monitor 对照一下发生了什么吗

**Comment by Frefreak** [comment]
好的，我对照下看看

**Comment by Frefreak** [comment]
因为dbus-monitor的输出太长了，我用了下面这个脚本捕获`org.fcitx.Fcitx.InputContext1`下面的Method，但复现后并**没有**观察到少的key和没少的key之间的调用模式有明显区别。还需要捕获其它的interface吗？

```python
import dbus
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import GLib

DBusGMainLoop(set_as_default=True)

def msg_cb(_, msg):
    if msg.get_member() == 'ProcessKeyEvent':
        args = msg.get_args_list()
        print(f'\x1b[32;1m{msg.get_member()}\x1b[0m', f'\x1b[31;1m{chr(int(args[0]))}\x1b[0m', msg.get_args_list())
    else:
        print(msg.get_member(), msg.get_args_list())

bus = dbus.SessionBus()
bus.add_match_string("interface='org.fcitx.Fcitx.InputContext1',eavesdrop='true'")
bus.add_message_filter(msg_cb)
[logs.txt](https://github.com/fcitx/fcitx5/files/11047919/logs.txt)

loop = GLib.MainLoop()
loop.run()

```

---

举例来说，下面这段序列用某形码打出的是"一二三四五六七八九〇"
```python
['KeyF', 'Space', 'KeyM', 'KeyE', 'Space', 'KeyT', 'KeyS', 'Space', 'KeyY', 'KeyS', 'Space', 'KeyW', 'KeyU', 'Space', 'KeyA', 'KeyL', 'Space', 'KeyR', 'KeyQ', 'Space', 'KeyH', 'KeyB', 'Space', 'KeyK', 'KeyJ', 'Space', 'KeyD', 'KeyK', 'KeyK', 'Space']
```

在这次测试中少了两个keydown —— `ts<space>` (三) 中的`t`，和`rq<space>` (七)中的`q`：

```python
['KeyF', 'Space', 'KeyM', 'KeyE', 'Space', 'KeyS', 'Space', 'KeyY', 'KeyS', 'Space', 'KeyW', 'KeyU', 'Space', 'KeyA', 'KeyL', 'Space', 'KeyR', 'Space', 'KeyH', 'KeyB', 'Space', 'KeyK', 'KeyJ', 'Space', 'KeyD', 'KeyK', 'KeyK', 'Space']
```

我上面的脚本打印出的日志如附件（对`ProcessKeyEvent`我加了一些颜色)。
![image](https://user-images.githubusercontent.com/7122156/227129070-1b2efba3-1507-416f-9337-8fa9aefbb382.png)
[logs.txt](https://github.com/fcitx/fcitx5/files/11047925/logs.txt)


---

我试着在这里随便加了一些打印，每个输入的key的执行路径看上去也是一样的（每个space一样，不同的字母之间也一样）。

https://github.com/fcitx/fcitx5/blob/3b6113c0afc00a6187fafc308c5e1e5de5d1614c/src/lib/fcitx/instance.cpp#L1425-L1457

**Comment by Frefreak** [comment]
> Chrome: 输入法composing时按一下字母，对应2个一样的keydown event，keyCode = 229, key = unidentified

上面测试主要针对的是firefox中keydown丢失的情况，chrome里的感觉是另外一种问题了，目前先不关心

**Comment by wengxt** [comment]
输入法它的工作原理是这样的，按键如果被输入法处理逻辑上对程序就不再可见，大部分输入法只处理 key down 并且将其过滤。

特别如果是在 wayland 下运行的话按键是在compositor 就被抓走了，key down 应该更少，当然你这里并不是

如果你只是在意你的什么测试的话，可以试试用 FCITX_ENABLE_SYNC_MODE=1 来启动 firefox

**Comment by Frefreak** [comment]
> 按键如果被输入法处理逻辑上对程序就不再可见

是说丢失的地方可能不在fcitx控制范围内了吗

设置FCITX_ENABLE_SYNC_MODE=1后确实准确了，这个是在fcitx5-gtk和firefox里同时起作用吗？（搜到了相关代码），但在fcitx5-gtk里因为check_app_name的存在（https://github.com/fcitx/fcitx5-gtk/blob/dec1a13928577e7f43df53ab115e34b5d8419534/gtk3/fcitximcontext.cpp#LL301C22-L301C22） 看上去应该一直是sync的

测试结果倒还好，可以专门编译一个用keyup检测的版本自己用，主要是想理解是哪个环节导致的。

**Comment by Frefreak** [comment]
近期我理解一下输入法这块的原理，暂时先关闭了
