### ISSUE TITLE
在 kde + wayland 下无法显示候选词

### ISSUE THREAD

**Issue by rhjdvsgsgks** [fcitx/fcitx5#75]
具体表现类似 #47 ，但使用的是 kde 而不是 gnome。
系统 arch Linux
fcitx5 4.99.0
kcm-fcitx5 fcitx5-qt fcitx5-gtk 已安装且为最新版
kdeplasma-addons 5.19.2-1
plasma-desktop 5.19.2-1
wayland 1.18.0-2
具体表现为切换到输入法时 log 显示 `Kimpanel new owner` 后方为空，并没有显示某个数字
安装 kimtoy 后倒是 `Kimpanel new owner` 后面有数字了，但 kimtoy 并不能正常识别 fcitx5 ，输入法面板会在屏幕左上角显示(而不是状态栏)，在使用拼音输入时 kimtoy 会尝试显示候选词并闪退

**Comment by zexi** [comment]
+1, 遇到了同样的问题 , 在 wayland 里面的 terminal 无法显示输入候选词.
![test](https://user-images.githubusercontent.com/10767027/86559869-950b5d80-bf8f-11ea-93b8-a737635ff372.gif)

**Comment by wengxt** [comment]
用 KDE 的 kimpanel 应该可以显示出来。其他的情况目前来说只能说建议不要用 wayland，反正定位也不对

**Comment by rhjdvsgsgks** [comment]
没找到 kimpanel ，不知道这是个包还是个 kde 插件

**Comment by wengxt** [comment]
添加部件，搜索输入法面板

rhjdvsgsgks <notifications@github.com>于2020年7月8日 周三19:46写道：

**Comment by zexi** [comment]
> 用 KDE 的 kimpanel 应该可以显示出来。其他的情况目前来说只能说建议不要用 wayland，反正定位也不对

好吧，目前暂时解决方案是启动 terminal 的时候加上 GDK_BACKEND=x11 环境变量，运行在 XWayland 里面可以正常显示

**Comment by rhjdvsgsgks** [comment]
> 添加部件，搜索输入法面板
感谢指点，现在可以正常显示候选词了(虽然位置是固定的)，之前搜 kimpanel 没找到，原来叫 input method panel
