### ISSUE TITLE
[新功能请求]针对不支持IME的软件的支持

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [fcitx/fcitx5#752]
针对不支持输入法的软件，制作一个虚拟输入栏，检查特定进程是否存在来启用，当输入框启用时，用户输入会先输入到虚拟输入栏，随着确认打出字符后，直接向进程传递该字符输入［该操作实现参考kde connect］。

假设的实现场景：

linux图形桌面打开异星工厂后，虚拟输入栏启动，用户打字会在屏幕任意处出现候选词，选中候选后该候选字符会直接传递给异星工厂的输入。

**Comment by CoelacanthusHex** [comment]
我觉得这个更适合作为一个单独的项目来维护。而且需要 hook 进程来完成这些操作（GUI 程序并不像 cli 程序那样直接使用 STDIN 作为输入，如果要往某个输入框填充字符，需要深入 GUI 框架的实现），而如果能 hook 进程的话，就不如直接实现一个 hook 版本的输入法协议实现来一劳永逸地解决这个问题，还能得到无缝的体验。

> ［该操作实现参考kde connect］

kdeconnect 没有这种功能， KDE Connect 的远程输入的实现是模拟键盘输入，你可以试一下，使用远程输入的话，你在 Android 侧使用输入法打中文 Linux 侧不会有任何反应，因为一个键盘不支持输入中文 keysym.

**Comment by wengxt** [comment]
xdotool type 可以支持任意字符，但实现非常hacky 并且不支持wayland

windows上是有类似的弹出窗口，但我感觉和fcitx本身关系就不大了并不需要作为fcitx的项目
