### ISSUE TITLE
Application based shortctus not working when using cyrillic input.

### ISSUE THREAD

**Issue by Steamvoker** [fcitx/fcitx5#753]
When I'm using a cyrillic input (i.e. russian or ukrainian) I can't use any shortcuts like Ctrl+A to select all text, or Ctrl+W to close tabs in a browser.

1. Add input group
2. Add input method (using cyrillic alphabet)
3. Switch to the input group with cyrillic input method
4. Open any text input field
5. Press Ctrl+A

**Expected behavior**
Pressing Ctrl+A should select all text in current input field.

**Desktop (please complete the following information):**
 - Desktop: KDE Plasma 5.27.3
 - Display server type: X11

**Comment by wengxt** [comment]
Well, the answer to this is tricky. I think what you see is expected.

If you are using a layout that does not produce A-Z character at all, it's expected to see certain application doesn't behave correctly.

I know Qt has a workaround to internally apply en-us layout if the xkbmap does not produce latin at all for hot key handling, but you certainly don't expect this works for all the applications.

If you want to solve this within fcitx framework, you may do things like this:
1. Create a group,
2. add cyrillic alphabet
3. (optional) add additional layout that you want to use.
4. Set system layout to the layout you want to use as the hot key.

![image](https://user-images.githubusercontent.com/259684/228328006-62299068-fd39-4432-ac53-718f8214c6bb.png)
