### ISSUE TITLE
在 Ubuntu Kylin 优麒麟 20.04 和 Debian 10 中，唯独缺少 kde-config-fcitx5 这个软件包

### ISSUE THREAD

**Issue by imChipo** [fcitx/fcitx5#76]
在 Ubuntu Kylin 优麒麟 20.04 和 Debian 10 中，fcitx5 的安装软件包是比较齐全的。但是唯独缺少 kde-config-fcitx5 这个软件包。导致无法在 KDE 中配置 fcitx5 输入法。不知道什么时候可以进入软件源。

**Comment by wengxt** [comment]
not fcitx bug.

**Comment by imChipo** [comment]
Does this mean that fcitx5 can run normally in ubuntu 20.04 and debian 10? It's just that the distribution has not been packaged yet?

**Comment by yuyichao** [comment]
Not necessarily (though I don't see why not) but the absense of the package doesn't mean much. If you try to compile or if the distro maintainer have specific problem packaging it then that'll be a fcitx issue. As reported there's nothing to do here.

**Comment by wengxt** [comment]
打包问题，需要你去找对应的发行版的人 @hosiet

**Comment by imChipo** [comment]
Good news, some developers have made ppa for ubuntu 20.04 LTS. sudo add-apt-repository ppa:hosxy/test

**Comment by hosiet** [comment]
我不是 Ubuntu 开发者，Ubuntu 20.04 官方仓库如果想得到 kde-config-fcitx5 软件包的话需要其他 Ubuntu 开发者帮忙。

PPA 由第三方维护，其安全性与兼容性无法保证，请自行斟酌使用。

未来的 Ubuntu 20.10 以及以后的版本软件源中已经可以找到 kde-config-fcitx5。

**Comment by hosiet** [comment]
另：Debian 10 中的 fcitx5 不可用，请勿使用或请升级为 Debian Testing / Debian Unstable。因 fcitx5 所需求的 Qt 版本过高，目前无法在 Debian 10 上构建 fcitx5。

**Comment by imChipo** [comment]
> 我不是 Ubuntu 开发者，Ubuntu 20.04 官方仓库如果想得到 kde-config-fcitx5 软件包的话需要其他 Ubuntu 开发者帮忙。
> PPA 由第三方维护，其安全性与兼容性无法保证，请自行斟酌使用。
> 未来的 Ubuntu 20.10 以及以后的版本软件源中已经可以找到 kde-config-fcitx5。
> 另：Debian 10 中的 fcitx5 不可用，请勿使用或请升级为 Debian Testing / Debian Unstable。因 fcitx5 所需求的 Qt 版本过高，目前无法在 Debian 10 上构建 fcitx5。

These warnings are very important, thank you very much!
