### ISSUE TITLE
Is there a chance that I can build fcitx5 on Windows?

### ISSUE THREAD

**Issue by Dlinuigh** [fcitx/fcitx5#762]
I'd love to use fcitx5 everywhere, but last time I failed to build fcitx5 on Windows 11.

**Comment by rocka** [comment]
No.

Even if you managed to build all the required libraires and finally build fcitx5, you still need to write ["frontend"](https://github.com/fcitx/fcitx5/tree/5.0.23/src/frontend) and ["ui"](https://github.com/fcitx/fcitx5/5.0.23/master/src/ui) module, to make it work as input method on Windows. Not to mention working around all kinds of "quirks" among different applications.

More on Microsoft's documentation:

- [Input Method Editors (IME)](https://learn.microsoft.com/en-us/windows/apps/design/input/input-method-editors#creating-an-ime)
- [Custom Input Method Editor (IME) requirements](https://learn.microsoft.com/en-us/windows/apps/design/input/input-method-editor-requirements)
- [Text Services Framework (Text Services Framework)](https://learn.microsoft.com/en-us/windows/win32/tsf/text-services-framework)

**Comment by wengxt** [comment]
We don't have resource to work on windows support. But feel free to send PR if anyone is willing to work on it for making it build on windows
