### ISSUE TITLE
[typo] 中文翻译 typo

### ISSUE THREAD

**Issue by sukanka** [fcitx/fcitx5#763]
**Describe the bug**
发现一个中文翻译typo
https://github.com/fcitx/fcitx5/blob/fa09120eca87dcd772d37515965e518f0662258e/po/zh_CN.po#L852-L855
此处 `下列错误也也不是严重问题` 多了一个 `也`
繁体中文也有同样问题
https://github.com/fcitx/fcitx5/blob/fa09120eca87dcd772d37515965e518f0662258e/po/zh_TW.po#L858-L860

**Comment by wengxt** [comment]
已修复
