### ISSUE TITLE
Fn key (keysym 0x0) triggers quickphrase in Pinyin

### ISSUE THREAD

**Issue by tianze0926** [fcitx/fcitx5#765]
**Describe the bug**
Pressing `Fn` key on keyboard Rapoo 9000G would trigger quickphrase in Pinyin mode.

`xev` output indicates that the `Fn` key on this keyboard actually sends X events:

```
KeyPress event, serial 34, synthetic NO, window 0x3c00001,
    root 0x6ca, subw 0x0, time 140695566, (271,259), root:(1043,765),
    state 0x0, keycode 248 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x3c00001,
    root 0x6ca, subw 0x0, time 140695774, (271,259), root:(1043,765),
    state 0x0, keycode 248 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

After testing with `xdotool` to send custom key events, I found that sending a KeyPress event with keysym `0x0` would trigger quickphrase.

**To Reproduce**
1. Install `xdotool`
2. Type `xdotool keydown 0x0` in a terminal
3. Switch to Pinyin
4. Press Enter to execute the command and send the event
5. Quick phrase will be triggered

**Expected behavior**
Quick phrase should not be triggered by keysym `0x0`, right?

**Desktop:**
 - Desktop: i3wm
 - Display server type: X11
 - The output of fcitx5-diagnose: https://gist.github.com/tianze0926/e8ed1c19e46dcee29db3355aeb2987d1

**Comment by wengxt** [comment]
so two things:
1. fcitx::Key uses 0x0 as "no key"
2. you see quickphrase trigger key in pinyin to "no key", by default it's semicolon though.
3. pinyin check this key and thing it's key to trigger quick phrase.

if you want a quick workaround, change quickphrase key trigger in pinyin configuration.

fix will be done in fcitx::Key.
