### ISSUE TITLE
在切换输入法时，如何预览所有已安装的输入法。

### ISSUE THREAD

**Issue by tomatl45** [fcitx/fcitx5#774]
你好，

当我按下快捷键，以切换输入法时，我是否有办法让屏幕上弹出一个小小的界面，显示出我安装的所有输入法，并且，每当我按下一次切换输入法的快捷键时，这个界面上有一个光标移动，指示我目前所选定的输入法。

我安装了许多不同语言的输入法，如果可以即时预览，列出所有的输入法，并且当我按快捷键切换输入法时，有一个光标帮助指示我已经选中了哪一个输入法的话，会非常方便。

我的fcitx5版本是5.0.23。

谢谢大家！

**Comment by wengxt** [comment]
首先，系统上支持的所有的不太现实……默认安装完默认的有的比你想的多得多得多（上百）。

其次，你是不是在找，它的功能是列出所有你添加到列表中的输入法：

![图片](https://user-images.githubusercontent.com/259684/233728175-ba925c30-5247-4325-a397-7d4a3bb4c55b.png)

![图片](https://user-images.githubusercontent.com/259684/233728205-4120f9ad-4cd0-483a-93e8-844616d2a340.png)

**Comment by tomatl45** [comment]
> 首先，系统上支持的所有的不太现实……默认安装完默认的有的比你想的多得多得多（上百）。
> 
> 其次，你是不是在找，它的功能是列出所有你添加到列表中的输入法：
> 
> ![图片](https://user-images.githubusercontent.com/259684/233728175-ba925c30-5247-4325-a397-7d4a3bb4c55b.png)
> 
> ![图片](https://user-images.githubusercontent.com/259684/233728205-4120f9ad-4cd0-483a-93e8-844616d2a340.png)

是的，谢谢！我确实只想尝试预览我手动添加的输入法（只有几个），而不是所有存在的输入法（几百个）。

我目前看到两种切换输入法的快捷键：第一种是在fcitx5的全局设置中看到的，第二种是在fcitx5的附加组件中找到输入法选择器的选项时看到的。

第一种快捷键只需我连续按下相同的快捷键数次，便可逐个在所有已添加的输入法之间切换。但它只显示当前输入法的名称，不会预览所有输入法。

第二种快捷键按下之后，便会弹出一个小小的界面（也就是上面的图片中看到的界面），预览所有输入法。但我需要在按下快捷键之后，再按下对应的数字键，或是用鼠标点击这个小小的界面，才能切换输入法。

我想知道是否有办法调整设置，只需要连续按下同一个快捷键数次，便可遍历所有已添加的输入法，同时，还可以用一个小小的界面来预览所有已添加的输入法。我猜也许我可以在这两种快捷键的基础上进一步调整一些设置？

谢谢！

**Comment by wengxt** [comment]
第一个问题，默认ctrl space反复按就已经有这样的功能

第二个，上面的截图就是这样用的

**Comment by tomatl45** [comment]
> 第一个问题，默认ctrl space反复按就已经有这样的功能
> 
> 第二个，上面的截图就是这样用的

感谢迅捷的回复！我想知道是否有办法组合这两种行为，同时实现这两样方便的功能——在反复按下Ctrl+Space的同时，能够像上面的截图一样预览所有已添加的输入法。

**Comment by tomatl45** [comment]
> 第一个问题，默认ctrl space反复按就已经有这样的功能
> 
> 第二个，上面的截图就是这样用的

我在fcitx5中启用了很多个输入法，用以输入各种不同的语言，并且需要经常在它们之间（有时是非常频繁地）切换，所以，我在想是否有办法能够以更加可视化的方式来方便、快速地切换输入法，譬如通过上面讨论的方式，或者也可以通过其它我没有想到的方式。谢谢！

**Comment by wengxt** [comment]
输入法选择器里也有可以通过配置多个键跳转到第x个选项，配置方式参考上面的图
