### ISSUE TITLE
输入法切换问题

### ISSUE THREAD

**Issue by a188037445** [fcitx/fcitx5#78]
问题是这样的，我设置的输入法切换键是 shift 键，在我打开 kde 的文件对话框选择文件时，我用 shift 批量选择文件的同时， fcitx5 的输入法也切换了，而这个时候焦点并没有在输入框里。

这应该是个 bug 吧？在其他情况下，只要焦点没有在输入框里，按 shift 键是不会导致输入法切换的。

**Comment by wengxt** [comment]
什么版本的 fcitx5-qt？

哪个程序的对话框？例如 kwrite 的 打开？

**Comment by a188037445** [comment]
fcitx5-frontend-qt5/testing,now 0.0~git20200615.b6f2ef3-1

**Comment by wengxt** [comment]
建议录像看看

**Comment by a188037445** [comment]
我录了个 gif：
![Peek 2020-07-09 06-11](https://user-images.githubusercontent.com/46810417/86975577-30c4e580-c1ab-11ea-857b-7146dc4f76a5.gif)

**Comment by Aloxaf** [comment]
噫 我这里也能复现

![图片](https://user-images.githubusercontent.com/17017672/86984869-57424b00-c1c2-11ea-86b9-a6cef71626b3.png)

**Comment by wengxt** [comment]
读了一下 Qt 的代码，这是 feature。

因为你按键根据输入的内容可以跳转到对应条目，甚至输入的是中文也可以。

https://code.woboq.org/qt5/qtbase/src/widgets/itemviews/qabstractitemview.cpp.html#146
