### ISSUE TITLE
输入中文的时候突然输入一个英文大写，就会被强迫回车？

### ISSUE THREAD

**Issue by gddg** [fcitx/fcitx5#785]
输入中文的时候突然输入一个英文大写，就会被强迫回车？丢失刚才那个字母。
这个是可以配置的吗？

**Comment by chopin1998** [comment]
好像只有在chrome里h会则有，d不知奥为什么。

用其他记事本n射门的打开，都o 美玉问题。

g山脉n这毒啊i文字，不是我故意打错 的，确实一边打字i一般丢字， a很烦恼脑

**Comment by wengxt** [comment]
@chopin1998 贴一下fcitx5-diagnose的输出

**Comment by wengxt** [comment]
@gddg  没有注意到是另一个人回复的，你是用哪个输入法有这个现象？拼音 或者 五笔 都应该不是这种行为。

@chopin1998 你环境变量配置的有问题，没有应用到你整个桌面 frontend:xim 表示你在用 xim，xim 对 chrome 是有问题的，但其他部分显示你已经安装了所有需要的包，所以只是环境配置的问题，ubuntu 建议用 im-config 来配置

**Comment by chopin1998** [comment]
你的环境变量配置有问题， 没有应用到你整个桌面fonrtend

> 

非常感谢， 现在 chrome的 frontend 指向 dbus, 似乎没有问题了， 非常非常感谢！
