### ISSUE TITLE
GTK4 doesn't work any more after Microsoft Edge recent update

### ISSUE THREAD

**Issue by kenarp** [fcitx/fcitx5#786]
**Describe the bug**
I used to use --gtk-version=4 command to run Edge so that Fcitx5 worked fine in the browser. However, after the most recent update(version 113.0.1774.35-1), with the --gtk-version=4 flag, Edge won't launch. I'm looking for a new method to solve the problem, or if I can do some configurations on the Edge to let the GTK4 flag works again. Thank you in advance!

**To Reproduce**
1. Open Edge browser with parameter --gtk-version=4, the browser won't launch
2. By removing the parameter, browser will run but Fcitx5 won't work

**Expected behavior**
A new way to make Fcitx5 work in Edge again

**Desktop (please complete the following information):**
 - Desktop:  GNOME 44.1
 - Display server type: Wayland

**Comment by wengxt** [comment]
It's not an issue can be solved from fcitx side.

Also it works for me.

```
GTK_IM_MODULE=fcitx microsoft-edge-stable --enable-features=UseOzonePlatform --ozone-platform-hint=auto  --gtk-version=4
```

113.0.1774.35-1
