### ISSUE TITLE
intellij 系列的 ide 中输入框位置不正确

### ISSUE THREAD

**Issue by a188037445** [fcitx/fcitx5#79]
我在 idea 和 clion 里都测试了，输入框只在左下角显示，下面是截图：
![Screenshot_20200709_155304](https://user-images.githubusercontent.com/46810417/87013006-99887e00-c1fc-11ea-92e5-50c2fbceac1c.png)

我的环境是 debian testing 系统（已更新到最新）、kde 桌面、idea 2020.1.3 和 clion 2020.1.2。

**Comment by wengxt** [comment]
一些 java 程序就是这样，没办法获得位置。

**Comment by stalkerg** [comment]
you should just make an issue on JetBrains issue tracker they usually very quick fix such things.

**Comment by qwIvan** [comment]
看起來Arch可以裝這幾個包 https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=java11-jetbrains-imfix

**Comment by cheng-shuai** [comment]
> 看起來Arch可以裝這幾個包 https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=java11-jetbrains-imfix

这个有用吗？我老是编译失败

**Comment by SergeFan** [comment]
> 一些 java 程序就是这样，没办法获得位置。

我发现在自己编写的Java程序（非常简单的窗口程序）中也出现了同样的问题，请问如果我希望Fcitx能够正确获取位置的话应该注意什么事项？比如在Fcitx是如何获取Java窗口程序中的位置信息的？

**Comment by wengxt** [comment]
@SergeFan 是程序告诉fcitx，而不是fcitx有什么办法，请去找java报bug
