### ISSUE TITLE
fcitx5 segmentation fault 

### ISSUE THREAD

**Issue by manateelazycat** [fcitx/fcitx5#798]
fcitx5-diagnose                                                                                  

 xrandr                                                                                           
Screen 0: minimum 320 x 200, current 2560 x 1600, maximum 16384 x 16384
eDP-1 connected primary 2560x1600+0+0 (normal left inverted right x axis y axis) 344mm x 215mm
   2560x1600    240.02*+  60.01 +  59.99    59.97  
   2560x1440     59.99    59.99    59.96    59.95  
   2048x1536     85.00    75.00    60.00  
   1920x1440     85.00    75.00    60.00  
   1856x1392     75.00    60.01  
   1792x1344     75.00    60.01  
   2048x1152     59.99    59.98    59.90    59.91  
   1920x1200     59.88    59.95  
   1920x1080     60.01    59.97    59.96    59.93  
   1600x1200     85.00    75.00    70.00    65.00    60.00  
   1680x1050     59.95    59.88  
   1400x1050     74.76    59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     85.02    75.02    60.02  
   1400x900      59.96    59.88  
   1280x960      85.00    60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      75.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      85.00    75.05    60.04    85.00    75.03    70.07    60.00  
   1024x768i     86.96  
   960x720       85.00    75.00    60.00  
   928x696       75.00    60.05  
   896x672       75.05    60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   832x624       74.55  
   960x540       59.96    59.99    59.63    59.82  
   800x600       85.00    75.00    70.00    65.00    60.00    85.14    72.19    75.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       74.76    59.98  
   800x450       59.95    59.82  
   640x512       85.02    75.02    60.02  
   700x450       59.96    59.88  
   640x480       85.09    60.00    85.01    72.81    75.00    59.94  
   720x405       59.51    58.99  
   720x400       85.04  
   684x384       59.88    59.85  
   640x400       59.88    59.98    85.08  
   576x432       75.00  
   640x360       59.86    59.83    59.84    59.32  
   640x350       85.08  
   512x384       85.00    75.03    70.07    60.00  
   512x384i      87.06  
   512x288       60.00    59.92  
   416x312       74.66  
   480x270       59.63    59.82  
   400x300       85.27    72.19    75.12    60.32    56.34  
   432x243       59.92    59.57  
   320x240       85.18    72.81    75.00    60.05  
   360x202       59.51    59.13  
   360x200       85.04  
   320x200       85.27  
   320x180       59.84    59.32  
   320x175       85.27  
DP-1 disconnected (normal left inverted right x axis y axis)

# 系统信息:
1.  `uname -a`:

        Linux freedom 6.1.29-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed May 17 14:00:55 UTC 2023 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	ManjaroLinux
        Description:	Manjaro Linux
        Release:	22.1.2
        Codename:	Talos

3.  `lsb_release -d`:

        Description:	Manjaro Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID=ManjaroLinux
        DISTRIB_RELEASE=22.1.2
        DISTRIB_CODENAME=Talos
        DISTRIB_DESCRIPTION="Manjaro Linux"

5.  `/etc/os-release`:

        NAME="Manjaro Linux"
        PRETTY_NAME="Manjaro Linux"
        ID=manjaro
        ID_LIKE=arch
        BUILD_ID=rolling
        ANSI_COLOR="32;1;24;144;200"
        HOME_URL="https://manjaro.org/"
        DOCUMENTATION_URL="https://wiki.manjaro.org/"
        SUPPORT_URL="https://forum.manjaro.org/"
        BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
        PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
        LOGO=manjarolinux

6.  桌面环境：

    桌面环境为 `gnome3`。

7.  XDG 会话类型：

        XDG_SESSION_TYPE='x11'

8.  Bash 版本：

        BASH_VERSION='5.1.16(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+us:2+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn,us", ",", ""

3.  Locale：

    1.  全部可用 locale：

            C
            C.UTF-8
            en_US.utf8
            POSIX
            zh_CN.utf8

    2.  当前 locale：

            LANG=zh_CN.UTF-8
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC=zh_CN.UTF-8
            LC_TIME=zh_CN.UTF-8
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY=zh_CN.UTF-8
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER=zh_CN.UTF-8
            LC_NAME=zh_CN.UTF-8
            LC_ADDRESS=zh_CN.UTF-8
            LC_TELEPHONE=zh_CN.UTF-8
            LC_MEASUREMENT=zh_CN.UTF-8
            LC_IDENTIFICATION=zh_CN.UTF-8
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/andy

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/andy/.config`)。

    3.  Fcitx5 设置目录：

        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/andy/.config/fcitx5`)。

5.  当前用户：

    脚本作为 andy (1000) 运行。

# Fcitx 状态:
1.  可执行文件：

    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：

    Fcitx 版本: ``

3.  进程：

    找到了 1 个 fcitx5 进程：

          65942 fcitx5

4.  `fcitx5-remote`:
/usr/bin/fcitx5-diagnose：行 916: 67071 段错误               （核心已转储）fcitx5-remote &> /dev/null

    **无法连接到 fcitx5。**

5.  DBus 界面：

    使用 `dbus-send` 来检查 dbus。

    **找不到 DBus 名称 `org.fcitx.Fcitx5` 的所有者。**

    **找不到 DBus 名称 `org.fcitx.Fcitx5` 的 pid 所有者。**

# Fcitx 配置界面：
1.  配置工具封装：

    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：

    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：

    **`kcmshell5` 未找到.**

# 前端设置：
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：

    **Xim 服务名称：“ibus”与环境变量中设置的值“fcitx”不同。**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

3.  Qt 输入法模块文件：

    找到了 fcitx5 qt5 模块：`/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`。
    找到了 fcitx5 的 qt6 输入法模块：`/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。
    找到了未知的 fcitx qt 模块：`/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`。
    找到了 fcitx5 的 qt 输入法模块：`/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。

    下列错误也许并不准确，因为对路径所对应的 Qt 版本的猜测取决于发行版如何打包 Qt。如果您不使用任何对应版本的 Qt 程序，或者在 Wayland 下使用 Qt 的 text-input 支持，下列错误也不是严重问题。
    **无法找到 Qt4 的 fcitx5 输入法模块。**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`。**

        **无法找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        在 `/usr/bin/gtk-query-immodules-3.0` 找到了 gtk `3.24.37` 的 `gtk-query-immodules`。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.37

        已找到 gtk `3.24.37` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk 输入法模块缓存：

    1.  gtk 2:

        **无法找到 gtk 2 的输入法模块缓存**

        **无法在缓存中找到 gtk 2 的 fcitx5 输入法模块。**

    2.  gtk 3:

        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.37` 的输入法模块缓存。
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.37

        已找到 gtk `3.24.37` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk 输入法模块文件：

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:

        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：
1.  插件配置文件目录：

    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：

    1.  找到了 26 个已启用的插件：

            Simplified and Traditional Chinese Translation 5.0.17
            Classic User Interface 5.0.23
            Clipboard 5.0.23
            Cloud Pinyin 5.0.17
            DBus 5.0.23
            DBus Frontend 5.0.23
            Emoji 5.0.23
            Fcitx4 Frontend 5.0.23
            Full width character 5.0.17
            IBus Frontend 5.0.23
            Input method selector 5.0.23
            Keyboard 5.0.23
            KDE Input Method Panel 5.0.23
            Status Notifier 5.0.23
            Notification 5.0.23
            Pinyin 5.0.17
            Extra Pinyin functionality 5.0.17
            Punctuation 5.0.17
            Quick Phrase 5.0.23
            Spell 5.0.23
            Table 5.0.17
            Unicode 5.0.23
            Wayland 5.0.23
            Wayland Input method frontend 5.0.23
            XCB 5.0.23
            X Input Method Frontend 5.0.23

    2.  找到了 0 个被禁用的插件：

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面：

    找到了 2 个已启用的用户界面插件：

        Classic User Interface
        KDE Input Method Panel

## 输入法：
1.  `/home/andy/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=pinyin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=pinyin
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# 日志：
1.  `date`:

        2023年 05月 21日 星期日 07:31:09 CST

2.  `/home/andy/.config/fcitx5/crash.log`:

        =========================
        Fcitx 5.0.23 -- Get Signal No.: 11
        Date: try "date -d @1684625468" if you are using GNU date ***
        ProcessID: 67073
        /usr/bin/fcitx5(+0x10aac)[0x55626e260aac]
        /usr/lib/libc.so.6(+0x38f50)[0x7f209be51f50]
        /usr/lib/libstdc++.so.6(_ZNSo6sentryC1ERSo+0x1a)[0x7f209c13b65a]
        /usr/lib/libstdc++.so.6(_ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l+0x3d)[0x7f209c13c14d]
        /usr/lib/libFcitx5Utils.so.2(_ZN5fcitx17LogMessageBuilderC1ERSoNS_8LogLevelEPKci+0x452)[0x7f209c3d4d32]
        /usr/lib/libFcitx5Core.so.7(_ZN5fcitx8Instance10initializeEv+0x23c)[0x7f209c4842fc]
        /usr/lib/libFcitx5Core.so.7(_ZN5fcitx8Instance4execEv+0x30)[0x7f209c484990]
        /usr/bin/fcitx5(+0xef5f)[0x55626e25ef5f]
        /usr/lib/libc.so.6(+0x23790)[0x7f209be3c790]
        /usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7f209be3c84a]
        /usr/bin/fcitx5(+0x10335)[0x55626e260335]

**To Reproduce**
1. Open terminal
2. type ```fcitx5```

**Expected behavior**
No throw segmentation fault

**Desktop (please complete the following information):**
 - Desktop: Gnome3
 - Display server type:  XWayland

**Comment by manateelazycat** [comment]
Arch 中安装了 fcitx5-git 导致的， 换成 fcitx5 以后， 就不会有段错误了。

**Comment by wengxt** [comment]
你重新编译 fcitx5-git 还会有同样的问题么？

**Comment by manateelazycat** [comment]
暂时没有折腾编译了， 估计是 git 的某个补丁导致 LogMessageBuilder 这个函数挂了。

**Comment by wengxt** [comment]
@manateelazycat 希望帮忙重新编译确认一下原因，也许只是需要重新编译，因为没有遇见相同问题

**Comment by manateelazycat** [comment]
重新编译后， 我还需要做什么吗？

**Comment by wengxt** [comment]
@manateelazycat 测试一下还有没有之前的问题
