### ISSUE TITLE
快捷键设置

### ISSUE THREAD

**Issue by a188037445** [fcitx/fcitx5#81]
我看到 fcitx5 的设置界面相比 fcitx4 少了很多快捷键的设置，请问以后会加上去吗？

我觉得有必要让用户看到并可以修改所有的快捷键，因为我需要知道有哪些快捷键可以用，同时有些快捷键会和其他程序中的快捷键产生冲突，也有些快捷键的默认设置不符合我的使用习惯，这些情况下都会需要修改快捷键。

**Comment by wengxt** [comment]
基本上没有不能改的，只是分布到每个附加组件里去了
