### ISSUE TITLE
Option to resize virtual keyboard

### ISSUE THREAD

**Issue by 9r0x** [fcitx/fcitx5#810]
Hi,

When I toggle the virtual keyboard on my touchscreen laptop, the virtual keyboard UI is tiny. I was wondering if there would be support for resizing the virtual keyboard.

If no support is planned in the short term, could you show me where I could change the default UI size/dimension in the codebase?

Thank you

**Comment by wengxt** [comment]
fcitx5 does not have virtual keyboard feature

**Comment by wengxt** [comment]
@wengxt you are probably asking about fcitx4 but that was under maintenance mode only. It was removed due to there’s no integration with actually input method. The future plan was to implement a proper virtual keyboard (like the one you see on mobile phone), but that’s still yet to be done.

**Comment by 9r0x** [comment]
@wengxt Got it, thanks. I was mistakenly asking about fcitx4 yesterday.

However, I did try the virtual keyboard today within fcitx5 on KDE(Wayland); I did not succeed in evoking the virtual keyboard. Is this due to it still being work in progress phase?

**Comment by wengxt** [comment]
@9r0x  the "virtual keyboard" kcm name is not really accurate, it just a thing for kwin to start input method process that is allowed to use protocol. Initially it was used for plasma mobile so it's called "virtual keyboard".

it doesn't really have anything to do with "virtual keyboard".

**Comment by 9r0x** [comment]
@wengxt Okay, this clarifies it a lot, thank you. 

One weird issue I encountered is that after installing fcitx5, [Maliit](https://maliit.github.io/) and other virtual keyboards no longer can be evoked when I touch the screen. Not sure what caused this.

Also, if I want to contribute to the virtual keyboard implementation in fcitx5, where would you recommend I to start?

**Comment by wengxt** [comment]
The zwp_input_method_v1 is by design can be only used by one input method process. If you want maliit you need to switch back in the virtual keyboard kcm.

As for the latter, there's some work happening on the dev branch, but you might want to join the channel first (see readme)
