### ISSUE TITLE
为什么需要一个专门用来启动fcitx5的desktop文件？

### ISSUE THREAD

**Issue by black-desk** [fcitx/fcitx5#812]
我不是很理解这个desktop文件的作用。

一个没有gui的程序我不太明白什么情况下才会需要从启动器中点击它启动。

如果真的有用 是不是可以考虑设置一下Hidden=true？

**Comment by CoelacanthusHex** [comment]
1. XDG Autostarts 需要一个 desktop entry
2. 方便手动启动（在终端里 `fcitx5 &` 终端退出就挂了，用 `systemd-run` 命令太长并且需要 systemd），只需要在应用管理器搜索点击即可
3. 获得较好的 cgroup 管理，资源分配和 oom kill 都会更好地运行（其他方式启动的 fcitx5 直接位于上层 cgroup，不便管理）

**Comment by CoelacanthusHex** [comment]
关于 Hidden，我记得 Plasma 添加自动启动项的时候是搜不到 Hidden 的应用的。

**Comment by rocka** [comment]
> Hidden should have been called Deleted. It means the user deleted (at their level) something that was present (at an upper level, e.g. in the system dirs). It's strictly equivalent to the .desktop file not existing at all

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys

**Comment by black-desk** [comment]
> 3. 获得较好的 cgroup 管理，资源分配和 oom kill 都会更好地运行（其他方式启动的 fcitx5 直接位于上层 cgroup，不便管理）

dbus拉起+systemd service的方式启动才是最合理的cgroup管理方式吧？
依靠桌面环境启动desktop时把pid扔到cgroup里有各种各样的bug.

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6565#login-pane

https://bugs.kde.org/show_bug.cgi?id=423756

**Comment by black-desk** [comment]
> 2. 方便手动启动（在终端里 `fcitx5 &` 终端退出就挂了，用 `systemd-run` 命令太长并且需要 systemd），只需要在应用管理器搜索点击即可

get

**Comment by wengxt** [comment]
1、首先 fcitx 并不是什么没有 gui 的程序，fcitx有托盘有窗口，这些不都是 gui。但即使纯 terminal 应用都可以有一个 desktop file
2、这个 KDE 的功能需要一个 desktop file
![图片](https://github.com/fcitx/fcitx5/assets/259684/73e10f5e-707f-4282-8225-e2b30e7375d8)，还有很多别的原因例如 flatpak，appstream 等
3、Hidden 是当作不存在，NoDisplay 是不显示，但我认为还是应该显示一个的，偶尔可能有手动启动的需求。
