### ISSUE TITLE
在 libwebkit-gtk（gtk4）的应用下（例如 GNOME Web / Epiphany）无法实现输入跟随

### ISSUE THREAD

**Issue by yfwz100** [fcitx/fcitx5#815]
**Describe the bug**

在 libwebkit-gtk（gtk4）的应用下（例如 GNOME Web）无法实现输入跟随

**To Reproduce**

1. 打开 libwebkit-gtk 的应用程序，例如 GNOME Web ;
2. 在网页中切换输入法为 fcitx5 ，输入法后选词框总在左上方，无法跟随。（做为对比，在网址输入框上可以跟随，而且 ibus 没问题）

**Expected behavior**

输入候选词框应该在 libwebkit-gtk 的应用下实现输入跟随。

**Desktop (please complete the following information):**
 - Desktop: GNOME / KDE （现在在 GNOME 测试的，但实际上 KDE 也一样，之前以为 KDE 不支持所以没报告）
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible. 见附件。

**Additional context**

[fcitx5-diagnose.txt](https://github.com/fcitx/fcitx5/files/11854434/fcitx5-diagnose.txt)

**Comment by wengxt** [comment]
我认为是 webkit gtk 的 bug，触发的条件是嵌入预编辑的光标位置在预编辑起始位置

![图片](https://github.com/fcitx/fcitx5/assets/259684/0932d701-5e54-4907-8f50-e3c3826d4136)

如果你去掉这个选项应该发现可以正常跟随

**Comment by wengxt** [comment]
https://bugs.webkit.org/show_bug.cgi?id=218148

**Comment by yfwz100** [comment]
看起来确实是这样，虽然也不怎么用得到 webkit-gtk，就是看着别扭。还是不去掉方便一点。ibus 应该默认没启用预编辑模式吧，用了一段时间 ibus ，实在无法忍受 ibus 极慢的响应速度甚至于失去响应，懒得提意见了，囧。

**Comment by wengxt** [comment]
> 看起来确实是这样，虽然也不怎么用得到 webkit-gtk，就是看着别扭。还是不去掉方便一点。ibus 应该默认没启用预编辑模式吧，用了一段时间 ibus ，实在无法忍受 ibus 极慢的响应速度甚至于失去响应，懒得提意见了，囧。

启用了，只是它的光标是你输入的位置

fcitx 的拼音输入框为了不随着输入移动保持在光标开头，你可以把我上面截图的选项勾掉
