### ISSUE TITLE
Classic UI candidates list window gets stretched (kde wayland)

### ISSUE THREAD

**Issue by oldherl** [fcitx/fcitx5#818]
**Describe the bug**
The candidates list window gets stretched horizontally. But after I select a candidate and type another letter, the new candidates will show up correctly.
See the left side of the following screenshot.
![ui-streched](https://github.com/fcitx/fcitx5/assets/172495/6fa0655e-81b8-4588-978b-fbd4ef2e7830)

**To Reproduce**
It's not 100% reproducible, but it happens when I switch to Telegram (telegram-desktop) and start typing. After selecting a candidate, it's no longer stretched any more.

**Expected behavior**
The candidates list should not be stretched, like the right side of the screenshot.

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible. https://gist.github.com/oldherl/3d54df970284f181f14a07f709dcd2bc

**Additional context**
I am using 200% scale on all screens, and only one external screen is enabled at the moment. The other (laptop) screen is disabled. But when it was last used, it was also in 200% scale. However, this stretched window is not 200% of the normal width.

**Comment by wengxt** [comment]
is it classic ui, or ui from im module?

**Comment by oldherl** [comment]
> is it classic ui, or ui from im module?
How to confirm that?

**Comment by wengxt** [comment]
from fcitx5-diagnose it’s im module’s ui

**Comment by oldherl** [comment]
OK, then you can fix the title/description. I thought everything except kimpanel was classic UI.

**Comment by wengxt** [comment]
then it seems to be a bug in qt or kwin. You can WAYLAND_DEBUG=1 and see if there's anything interesting about surface size.

Or , just unset QT_IM_MODULE and follow https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma to use text-input for qt.

**Comment by oldherl** [comment]
Should I set WAYLAND_DEBUG=1 to telegram-desktop or to fcitx5?

**Comment by wengxt** [comment]
telegram-desktop

**Comment by oldherl** [comment]
Thanks. I will try it when I find a way to reproduce the bug.

**Comment by wengxt** [comment]
@oldherl you can try to move your mouse on to the candidate window  when this happens and see what happens.
