### ISSUE TITLE
Wayland输入法协议？

### ISSUE THREAD

**Issue by shangjiaxuan** [fcitx/fcitx5#82]
看起来wlroots最近merge进去了一个实现输入法选词框的协议，有没有考虑加入支持？

**Comment by wengxt** [comment]
尽管实现了，依然没有什么用，因为没有compositor 完整支持，而且这个协议本身看起来也并不好用。
例如：https://github.com/swaywm/wlroots/issues/2352

**Comment by wengxt** [comment]
Also, lack of input method keyboard grab https://github.com/swaywm/sway/pull/4932 also makes it currently useless.
