### ISSUE TITLE
How to disable notifications, and switch grouping back to the first input method

### ISSUE THREAD

**Issue by Ocyss** [fcitx/fcitx5#831]
如何禁用通知,和切换分组回到第一个输入法

I just came to `Arch`, and I am used to using `Sogou` on `Windows`, and I think this logic is really good.
That is, when I am using the pinyin input method, press `shift` to switch to English, and then press to switch to Chinese.
Then `alt`+`shift `is to switch to English (pressing `shift` in this state will not switch to Chinese), which can effectively reduce false touches

When I use the implementation of fcitx5, switching groups can perfectly realize this function
I only need two groups
-en
-cn,en

Then `shift` to switch the input method, `alt`+`shift` to switch the group
But I have two headaches

1. Every time I switch, I will be notified, I switch very frequently, it is very eye-catching, obsessive-compulsive disorder.. There is indeed a notification option in the add-on, but I don’t know how to turn it off, and I can’t find the documentation, wiki
2. When I like to switch groups, I can return to the default first input method, which is cn. Otherwise, it records the input method en of the last group. When I go from group 1 to 2, it is `en` => `en`, and he does not prompt, I don’t know that the group has been switched (notice No!)

---

我刚来Arch,我平时用习惯了`Windows`的搜狗,也觉得这种逻辑确实挺不错的.
就是当我是拼音输入法的时候,按`shift`切换成英文,在按就是中文.
然后`alt`+`shift`是切换到英文(该状态下按`shift`不会切换到中文),能非常有效的减少误触

当我使用`fcitx5`的实现,切换分组能完美实现这种功能
我只需要两个组
- en
- cn,en

然后 `shift` 切换输入法,`alt`+`shift`切换分组
但我遇到两个头痛的问题

1. 每次切换都会通知,我切换很频繁,很碍眼,强迫症..附加组件中确实有通知选项,但我不知道怎么关闭他,也找不到文档,wiki

2. 我喜欢切换分组的时候,可以回到默认的第一个输入法,也就是`cn`.不然他记录了上次分组的输入法`en`  当我从分组1到2,就是`en` => `en`,他没有提示,我不知道已经切换了分组(不要通知!)

**Comment by wengxt** [comment]
@Ocyss 你的通知长什么样，上面应该有一个“不再显示”的按钮

**Comment by rocka** [comment]
如果你只需要在中文和英文之间切换，可以尝试一下这样的设置：

只设置一个默认分组，第一个输入法是键盘（英文），第二个输入法是中文。

全局选项中：
- 切换启用/禁用输入法： <kbd>Alt</kbd> + <kbd>Shift</kbd>
- 临时在当前和第一个输入法之间切换： <kbd>Shift</kbd>

这样，在英文（即第一个输入法）状态下，按 <kbd>Shift</kbd> 不会切换到中文，只有按 <kbd>Alt</kbd> + <kbd>Shift</kbd> 才可以；
在中文（不是第一个输入法）状态下，按 <kbd>Shift</kbd> 切换到英文后，再次按 <kbd>Shift</kbd> 可以切回中文；但是按 <kbd>Alt</kbd> + <kbd>Shift</kbd> 切换到英文后，再次按 <kbd>Shift</kbd> 不会切换到中文。

**Comment by wengxt** [comment]
@Ocyss

**Comment by wengxt** [comment]
@Ocyss …你哪来的自信说大部分都没有的…这个功能早约 20 年前 libnotify 刚诞生的初期版本的时候就有了
我去阅读了一下 dunst 的代码它发现都是支持的，设置一下dunst鼠标按键功能就可以叫出对应功能
你也可以在通知的 addon 的配置里手动添加一个 enumerate-group 来禁用对应项目

**Comment by wengxt** [comment]
![图片](https://github.com/fcitx/fcitx5/assets/259684/99979a2e-77cb-4388-8f6a-e9eb6b9351ee)

**Comment by Ocyss** [comment]
> 如果你只需要在中文和英文之间切换，可以尝试一下这样的设置：
> 
> 只设置一个默认分组，第一个输入法是键盘（英文），第二个输入法是中文。
> 
> 全局选项中：
> 
> * 切换启用/禁用输入法： Alt + Shift
> * 临时在当前和第一个输入法之间切换： Shift
> 
> 这样，在英文（即第一个输入法）状态下，按 Shift 不会切换到中文，只有按 Alt + Shift 才可以； 在中文（不是第一个输入法）状态下，按 Shift 切换到英文后，再次按 Shift 可以切回中文；但是按 Alt + Shift 切换到英文后，再次按 Shift 不会切换到中文。

试了下，真的实现了，谢谢

**Comment by Ocyss** [comment]
> @Ocyss …你哪来的自信说大部分都没有的…这个功能早约 20 年前 libnotify 刚诞生的初期版本的时候就有了 我去阅读了一下 dunst 的代码它发现都是支持的，设置一下dunst鼠标按键功能就可以叫出对应功能 你也可以在通知的 addon 的配置里手动添加一个 enumerate-group 来禁用对应项目

我是说不再通知的按钮，通知服务器不再通知功能有基本都有，只是需要去配置，或某些主题实现了不再通知的按钮？dunst 我看国内相关资料挺少的，就简单抄了个主题，确实没去深读代码。

**Comment by wengxt** [comment]
@Ocyss 那个按钮不是来自服务的，是fcitx这边传递给通知服务的。通知服务支持指定一个通知带有多个action
