### ISSUE TITLE
Monitor events with `fcitx5-remote`

### ISSUE THREAD

**Issue by musjj** [fcitx/fcitx5#834]
I'm trying to monitor input switch events from fcitx5, and this is how I do it:

```bash
dbus-monitor --session destination=org.freedesktop.IBus |
  grep --line-buffered '65505\|65509' | while read -r _; do
  fcitx5-remote
done
```

But unfortunately, this doesn't get triggered when you switch using `fcitx5-remote -t`. An integrated monitor command like `fcitx5-remote monitor` can potentially solve this issue.

**Comment by wengxt** [comment]
I don't know what are you trying to do with ibus service in fcitx. While fcitx indeed support ibus's dbus interface, but that doesn't mean all the client are using ibus's dbus protocol on your system, specifically, xim.

Next thing, not all input context object are exposed in dbus, there's no way for fcitx5-remote to implement such a thing.

Finally, for the solution you're really asking for, you can implement an addon in fcitx, and use some api to watch for the event.

https://codedocs.xyz/fcitx/fcitx5/classfcitx_1_1Instance.html#a19894a928b3b511422682609dcfbe4b7

lua is also available 
https://fcitx.github.io/fcitx5-lua/modules/fcitx.html#watchEvent
