### ISSUE TITLE
opensuse leap 15.5 配置界面打不开

### ISSUE THREAD

**Issue by VoidYin** [fcitx/fcitx5#840]
**Describe the bug**
配置界面打不开，提示如下信息：
您正在图形界面下运行 fcitx，但是 fcitx-configtool 未被找到，软件包名通常为 fcitx-config-gtk，fcitx-config-gtk3，或者 fcitx-configtool。现在将用默认文本编辑器打开配置文件。

**Desktop (please complete the following information):**
 - os：opensuse leap 15.5
 - Desktop: xfce
 - Display server type: X11

**Comment by VoidYin** [comment]
将安装以下 1 个新软件包：
  fcitx-config-gtk3

将移除以下 1 个软件包：
  fcitx5-configtool

这样就好了。

**Comment by gostsdmitry** [comment]
> **Describe the bug**
> 配置界面打不开，提示如下信息：
> 您正在图形界面下运行 fcitx，但是 fcitx-configtool 未被找到，软件包名通常为 fcitx-config-gtk，fcitx-config-gtk3，或者 fcitx-configtool。现在将用默认文本编辑器打开配置文件。

对于 fcitx(4)，您需要安装 fcitx-configtool 软件包、fcitx-config-gtk 或 fcitx-config-gtk3。
对于 fcitx5，您需要安装 fcitx5-configtool 软件包。

**Comment by VoidYin** [comment]
刚安装的leap 15.5是好的，更新到最新后，就出问题了。
我看了下，好像安装的是fcitx，不是fcitx5。
那为什么要给我安装fcitx5-configtool？

**Comment by gostsdmitry** [comment]
> 刚安装的leap 15.5是好的，更新到最新后，就出问题了。
> 我看了下，好像安装的是fcitx，不是fcitx5。
> 那为什么要给我安装fcitx5-configtool？

如果您使用 fcitx，则不需要 fcitx5-configtool。

**Comment by wengxt** [comment]
因为这是fcitx5的repo，不是fcitx4的

**Comment by wengxt** [comment]
你搜索提供 /usr/bin/fcitx-config-gtk3 的包即可

opensuse的包名叫fcitx-config-gtk3
