### ISSUE TITLE
Hotkeys bubble up to an application

### ISSUE THREAD

**Issue by andrhua** [fcitx/fcitx5#845]
**Describe the bug**
I want "Enumerate Input Method Forward" to be right alt key, and it works given the currently focused application doesn't recognize Alt as shorcut. Unfortunately, some graphical apps like Firefox and Slack bring up menu on alt press, and it's not always possible to disable this behavior.

**To Reproduce**
1. Configure IM switch to be alt
2. Open firefox/slack
3. Press alt

**Expected behavior**
Hotkeys, at least IM switching ones, do not bubble up to other apps, similarly to how `grp:..` xorg options work - once you set caps lock to switch layout, you basically lose the ordinary caps lock functionality.

**Desktop (please complete the following information):**
 - Desktop: i3
 - Display server type: X11

**Comment by wengxt** [comment]
such thing is unavoidable, since under X11, usually it's application has higher priority to handle the key.

I'd suggest you try right ctrl or use a combination e.g. alt + shift.

**Comment by wengxt** [comment]
An alternative solution is to use group switching in fcitx, which does use key grab. But I found some bug that prevent this option to work with modifier keys, which was fixed in 191660bb.

If you want to try that, simply create multiple groups and put only 1 input method within each group.
