### ISSUE TITLE
Do fcitx5 support fcitx-diagnostic?

### ISSUE THREAD

**Issue by yzh119** [fcitx/fcitx5#85]
Dear authors,

Thanks for developing fcitx5, the user experience is much better than fcitx4. However, I found fcitx5 does not work on some applications such as emacs & wine-wechat in my machine. I wonder do you have plan to develop fcitx5-diagnostic (like fcitx-diagnostic) so that I could locate where the problem is more easily?

Thanks.

**Comment by wengxt** [comment]
@yuyichao
