### ISSUE TITLE
Missing UI component with fcitx 5.1.0

### ISSUE THREAD

**Issue by chaserhkj** [fcitx/fcitx5#852]
**Describe the bug**
The selection box border and primary text are missing with fcitx5 5.1.0 (fcitx5-gtk 5.1.0 fcitx5-qt 5.1.0)
![1](https://github.com/fcitx/fcitx5/assets/1768423/041d21ef-e738-4d4f-a02f-f6ee966f6596)

After downgrading fcitx5 to 5.0.23-2, fcitx5-gtk to 5.0.23-1, fcitx5-qt to 5.0.17-7, restarting the application and fcitx5, everything works fine:
![2](https://github.com/fcitx/fcitx5/assets/1768423/8545c2bd-7280-4727-a4c4-5ee627981762)

**To Reproduce**
1. Open any app with fcitx5 5.1.0
2. Try to type anything

**Expected behavior**
The selection box should display the border and primary text.

**Desktop (please complete the following information):**
On Arch Linux, both these setups would behave the same and produce the bug:
- i3 w/ pimco on X11
- sway on Wayland

**Additional context**
N/A

**Comment by wengxt** [comment]
old theme was based on png while new version of default theme isn’t and png were removed.

**Comment by chaserhkj** [comment]
Fixed, thanks a lot!
