### ISSUE TITLE
Record and Restore Keyboard Layout on Input Method Switch

### ISSUE THREAD

**Issue by nameyouxuan** [fcitx/fcitx5#858]
**Description:**
I would like to propose a new feature for fcitx5 that involves recording and restoring the current keyboard layout when switching input methods. Currently, there is a need for a more seamless transition between input methods while retaining the user's preferred keyboard layout.

**Feature Details:**

Recording Keyboard Layout: Upon switching to a different input method, fcitx5 should record the current keyboard layout in use by the user.
Setting Keyboard Layout: The keyboard layout should be automatically set to a predefined layout (e.g., QWERT) whenever a new input method is selected.
Restoring Original Layout: Upon returning to the previous input method, fcitx5 should restore the original keyboard layout that was being used before the switch.

I couldn't find the documentation, but I've looked through the code and still gained no insight.

If a hook that gets triggered when the input method switching state is available could be provided, I'd be very interested in participating in the project.

**Comment by wengxt** [comment]
@nameyouxuan you can assign the layout to be used for certain input method with fcitx5-configtool
