### ISSUE TITLE
cannot start fcitx5

### ISSUE THREAD

**Issue by Boltzmachine** [fcitx/fcitx5#86]
When I run fcitx5 in my terminal (arch linux), I got

```
...
E2020-07-27 22:09:02.685770 addonloader.cpp:57] Failed to create addon: dubs Unable to request dbus name
...
```
and the fcitx5 failed to start.

**Comment by wengxt** [comment]
it seems that there's already one fcitx5 running. Did you configure it properly ?( env var, adding im)

**Comment by 1900011604** [comment]
I also meet this, but if I kill the fcitx5 and restart it, it still meets this problem.

Fcitx5 also does not display the “拼” addon on the system tray.
