### ISSUE TITLE
The first row of input box disappear

### ISSUE THREAD

**Issue by sokinpui** [fcitx/fcitx5#860]
I suddenly find the first row disappear, I try to reboot and restart fcitx5, still disappear.
![image](https://github.com/fcitx/fcitx5/assets/104958540/80ea9eb9-9e0a-46ad-a556-e005156f954a)

Sorry that I can't show you how to reproduce, Since it is suddenly be that in some day. I am trying to find the main reason causing this issue.

Env: Fedora Gnome Wayland

**Comment by rocka** [comment]
TLDR: remove ~/.local/share/fcitx5/themes/default

#852

**Comment by wengxt** [comment]
确实是个问题……主要是老主题配置如果你修改过的话，就会有过时的配置

目前解决方法就是删掉老主题的配置
