### ISSUE TITLE
Spaces after Hangul behaves weirdly.

### ISSUE THREAD

**Issue by km19809** [fcitx/fcitx5#870]
**Describe the bug**
If I type a Hangul word and a space, the space is inserted at the front of the Hangul word.
However, if I type a Hangul word, lose focus on the text, and type a space after focusing again, the space is inserted the back of the word. (Works correctly!)

I found that it happens at various places, but I cannot figure out the exact condition.

Here are screen captures of Settings (Arch Linux) and Visual Studio Code.
*Settings*
![settings](https://github.com/fcitx/fcitx5/assets/20869932/f3129235-5c89-4347-ac9c-e96d25fb4251)
if I type a space:
![settings_space](https://github.com/fcitx/fcitx5/assets/20869932/b295dc18-e6c5-47b2-8933-8fbffb657803)
*VS Code*
![vscode](https://github.com/fcitx/fcitx5/assets/20869932/053249c7-bb49-41e7-8d7b-7fe478c07462)
if I type a space:
![vscode_space](https://github.com/fcitx/fcitx5/assets/20869932/642bfad4-b183-471e-897b-caafa2a6c067)

**To Reproduce**
1. Run Settings or Visual Studio code
2. Find text entry
3. Enter shift+space to switch hangul mode
4. type gksrmf (`한글`)
5. type  (space)

**Expected behavior**
The space should be appended to the end of the word.

**Desktop (please complete the following information):**
- OS: SteamOS Holo (ArchLinux)
 - Desktop: KDE
 - Display server type: X11
 - The output of fcitx5-diagnose if possible

<details>
 <summary>
Click to show the diagnose output.
</summary>
# System Info:
1.  `uname -a`:

        Linux steamdeck 5.13.0-valve37-1-neptune #1 SMP PREEMPT Thu, 17 Aug 2023 23:47:04 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	SteamOS
        Description:	SteamOS Holo
        Release:	rolling
        Codename:	Holo

3.  `lsb_release -d`:

        Description:	SteamOS Holo

4.  `/etc/lsb-release`:

        DISTRIB_ID="SteamOS"
        DISTRIB_RELEASE="rolling"
        DISTRIB_CODENAME="Holo"
        DISTRIB_DESCRIPTION="SteamOS Holo"

5.  `/etc/os-release`:

        NAME="SteamOS"
        PRETTY_NAME="SteamOS"
        VERSION_CODENAME=holo
        ID=steamos
        ID_LIKE=arch
        ANSI_COLOR="1;35"
        HOME_URL="https://www.steampowered.com/"
        DOCUMENTATION_URL="https://support.steampowered.com/"
        SUPPORT_URL="https://support.steampowered.com/"
        BUG_REPORT_URL="https://support.steampowered.com/"
        LOGO=steamos
        VARIANT_ID=steamdeck-rc
        BUILD_ID=20230831.1
        VERSION_ID=3.4.10

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc104", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.UTF-8
            en_US.utf8
            ko_KR.utf8
            POSIX

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/deck

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/deck/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/deck/.config/fcitx5`).

5.  Current user:

    The script is run as deck (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.19`

3.  process:

    Found 1 fcitx5 process:

           3046 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.55`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `3046`.

    Debug information from dbus:

           Group [x11::0] has 13 InputContext(s)
          IC [6cb5ec36406a4e8abcda230ea311b638] program: frontend:ibus cap:52 focus:1
          IC [2164199a390d4ed89b88b305bf205ce7] program: frontend:ibus cap:52 focus:0
          IC [0ee596c029c74a66815cc4964d5986fc] program: frontend:ibus cap:52 focus:0
          IC [f6c592003183407faa2db25044e91806] program: frontend:ibus cap:52 focus:0
          IC [37a54c466d9e4191be38cae6b725c7b0] program: frontend:ibus cap:12 focus:0
          IC [30eeec015f7f494fbc08abb8f6f17d5c] program: frontend:ibus cap:52 focus:0
          IC [491a510fc62f4332b0902104e99ca850] program: frontend:ibus cap:12 focus:0
          IC [8aa840fddb2b48469c4dabcf1a9b8012] program: frontend:ibus cap:12 focus:0
          IC [b55af92ff5cc4c9eba7566db7318d9cd] program: frontend:ibus cap:52 focus:0
          IC [81b8f89db389474f9abc48f67a69c6cc] program: frontend:ibus cap:52 focus:0
          IC [26ea27bc88b047d8a09fc5cdff4276ab] program: frontend:ibus cap:12 focus:0
          IC [29bf868a8e7a4821bf6b470183d9422f] program: frontend:ibus cap:52 focus:0
          IC [8fc793a0598a434ab79e24879690b5f5] program: frontend:ibus cap:12 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    Found fcitx5 kcm module.

        kcm_fcitx5                     - Configure Input Method

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS is not set**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Environment variable QT_IM_MODULE is "ibus" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
    **You may have trouble using fcitx in qt4 programs.**

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

2.  qt5 - `${QT_IM_MODULE}`:

    **Environment variable QT_IM_MODULE is "ibus" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
    **You may have trouble using fcitx in qt5 programs.**

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

3.  Qt IM module files:

    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Environment variable GTK_IM_MODULE is "ibus" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
    **You may have trouble using fcitx in gtk programs.**

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.34` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        Found fcitx5 im modules for gtk `3.24.34`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.34` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        Found fcitx5 im modules for gtk `3.24.34`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 20 enabled addons:

            Classic User Interface 5.0.19
            Clipboard 5.0.19
            DBus 5.0.19
            DBus Frontend 5.0.19
            Emoji 5.0.19
            Fcitx4 Frontend 5.0.19
            Hangul 5.0.10
            IBus Frontend 5.0.19
            Input method selector 5.0.19
            Keyboard 5.0.19
            KDE Input Method Panel 5.0.19
            Status Notifier 5.0.19
            Notification 5.0.19
            Quick Phrase 5.0.19
            Spell 5.0.19
            Unicode 5.0.19
            Wayland 5.0.19
            Wayland Input method frontend 5.0.19
            XCB 5.0.19
            X Input Method Frontend 5.0.19

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/deck/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=hangul

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=hangul
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Thu Sep 21 07:46:29 PM KST 2023

2.  `/home/deck/.config/fcitx5/crash.log`:

    `/home/deck/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

</details>

**Additional context**

Similar Issue: https://github.com/fcitx/fcitx5/issues/445

This is well-known behavior for Korean Steam Deck Users.
Please watch [this video tutorial](https://youtu.be/7Pp9hv8GkU0?si=mQAChEr4xh-OToUJ&t=723) (It takes 32 seconds,`12:03`~`12:35`): 
It is Korean, but sufficient to understand what's going on, with auto-translated caption.

**Comment by wengxt** [comment]
can you set GTK_IM_MODULE=fcitx and QT_IM_MODULE=fcitx and install fcitx5-gtk and fcitx5-qt and retest?

I can see you're using ibus im module instead.

**Comment by wengxt** [comment]
there's indeed a bug ibusfrontend what assume ibus im module can do the same thing like fcitx5 ones though.

But I think easier way for you to make it working is to use fcitx5's im module instead.

**Comment by km19809** [comment]
> can you set GTK_IM_MODULE=fcitx and QT_IM_MODULE=fcitx and install fcitx5-gtk and fcitx5-qt and retest?
> 
> I can see you're using ibus im module instead.

I set those environment variable in `/etc/environment`, however, it changes to ibus everytime I turn on the shell.
Also, I checked all the paths, such as `~/.bashrc`, `~/.profile`, `/etc/profile`, `/etc/profile.d/*`, `~/.xprofile`, and `~/.xinputrc`.
However, none of them sets these environment variables.
How can I use fcitx frontend?

**Comment by wengxt** [comment]
@km19809 Well. I'm not sure, since I don't have a steam deck. I believe there's a steam specific patch, or a steam deck specific config file that does this.

One option is , try to grep against your whole filesystem, though sounds silly, but it does work. you can start with all files under /etc.

**Comment by wengxt** [comment]
@km19809 another option is, try set it in a file that you know about and hope it can override whatever being done by steam os.

I could also list some other possibility of such files e.g.
/etc/environment.d /usr/lib/environment.d /etc/xdg/plasma-workspace/env ~/.config/plasma-workspace/env

**Comment by km19809** [comment]
@wengxt I found it a script in /etc/xdg/plasma-workspace.
Thank you for the advice!

**Comment by wengxt** [comment]
@km19809 based on kde's implemenation, you can write a file under ~/.config/plasma-workspace/env/[pick a name].sh to override it.

https://github.com/KDE/plasma-workspace/blob/c524c7e59134290d3661322f283765894d8dae1a/startkde/startplasma.cpp#L284

the user file should be source later than the system file. so you don't need to modify any system files.
