### ISSUE TITLE
app-org.fcitx.Fcitx5@autostart.service每次开机时都会启动失败

### ISSUE THREAD

**Issue by Bryan2333** [fcitx/fcitx5#871]
**Describe the bug**
app-org.fcitx.Fcitx5@autostart.service每次开机时都会启动失败

systemctl status --user app-org.fcitx.Fcitx5@autostart.service 里面Active显示为failed，但奇怪的是我进入桌面后Fcitx5是正常的，没有什么问题。

**To Reproduce**
1. 开机登录

**Expected behavior**
没有报错

**Desktop (please complete the following information):**
 - Desktop: KDE 5.27.8
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible: https://pastebin.com/SABut8yu

**Additional context**

app-org.fcitx.Fcitx5@autostart.service的日志：https://pastebin.com/5AAk6hyE

**Comment by wengxt** [comment]
@Bryan2333 你可能有超过一种自动启动它的方式，没什么好在意的，你既然用kde wayland可能是在虚拟键盘里配置了fcitx5,这样会由kwin启动fcitx5

**Comment by Bryan2333** [comment]
原理是这样啊，了解
