### ISSUE TITLE
[建议] 云拼音在获取到和已显示候选词相同结果时仍然占据第二候选词栏位

### ISSUE THREAD

**Issue by escape0707** [fcitx/fcitx5#885]
由于不是 bug 而是特性讨论，不太适用报 bug 模板，便简要描述如下：
在启用云拼音后，云拼音的候选词在获取结果的过程中占据第二号候选词位置的。但是如果获取的结果和已经显示的其他候选词重复的时候它就会直接消失，这时后面的关键词们就会往前移一位。这导致如果有时候网络较慢，已经准备手动选择三、四号词，结果云拼音位置突然消失则就会选错。降低输入效率。

可否参考其他有云拼音的输入法（比如 Windowns 10/11 上的微软拼音），即使云拼音获得了与已显示的其他候选词相同的结果，也保留其云朵的 emoji 在第二位，稳定其他候选词的位置呢？

**Comment by wengxt** [comment]
网络慢的情况 3 4 的序号会保持不变

**Comment by escape0707** [comment]
但是可否作为一个 accessibilty 选项提供一个不论网速快慢都保留下icon的功能呢？因为候选词跳动对于一部分对闪烁或者跳动敏感的用户来说容易产生不适。

**Comment by wengxt** [comment]
@escape0707 候选词如果正常加载出现就已经会跳动了

**Comment by escape0707** [comment]
按照我的使用体验总结来说：

- 云拼音结果与本地候选词一致时：
  - 延迟高：云候选 emoji 不会消失，候选词的序号和位置稳定
  - 延迟低：
    - 阅读速度/反应比延迟慢：如 issue 中所述，加之似乎是因为已查询过的云候选词有缓存而不会再查询，故在持续输入的时候云候选 emoji 的有无会反复变化，导致后面的候选词位置跳动更加频繁无法更好的阅读。此外阅读的过程中得到了和本地结果一直的候选词也会导致后面的候选词序号和位置变化，打断阅读。
    - 阅读速度/反应比延迟快：即使更快看准了后面的候选词也不容易选中，因为该词的序号在看准到按键的过程中仍然可能变化。
- 云拼音结果与本地候选词不一致时：
  - 延迟高：
    - 阅读速度/反应比延迟慢：读完第一候选词开始读云候选词，无影响。
    - 阅读速度/反应比延迟快：读完了第一和第三候选词。并且候选词序号稳定，需要后面的候选词可以放心选择。如果本地候选词不理想也已经提前转移目光等待云候选结果，再决定是否采用，这一次跳动完全不影响阅读。
  - 延迟低：
    - 阅读速度/反应比延迟慢：读完第一候选词开始读云候选词，无影响。
    - 阅读速度/反应比延迟快：如果已经读到第三候选词，此时如果云候选与本地候选词不一致，往往已经发现第三候选词不合适。同时云候选词可能更符合想要输入的语句，更值得一看，否则用户会选择关掉云拼音功能。因此一般也不会转移视线而是已经转移目光等待阅读云候选词，无影响。

所以按照上面的总结，正是因为 Fcitx5 中文拼音本地预测比较准确，再加上有时候有人到谷歌的延迟特别低，这时候才会遇到被候选词反复跳动困扰的情况。而且具体体验上述何种状况、会根据当时输入拼音的长度、个人的阅读速度、当时的网络状况、Fcitx5 硬编码的“高”“低”延迟的阈值之间互相影响而决定。体验并不统一。

所以我认为加入一个无障碍功能来使得云候选固定不消失对于提升一些阅读困难的用户的使用舒适度。希望能够听听开发者的意见。

**Comment by wengxt** [comment]
改成不消失我认为是可以的，但是不能使用同一个 emoji，因为用户不知道是否还有希望等到云返回（例如云已经返回了和本地相同的结果），有什么好的建议吗

**Comment by escape0707** [comment]
我认为可以参考微软或者搜狗的云拼音设计，要么在获取候选词时和获得一致结果后采用不同的 emoji（微软）；要么在仍在获取候选词时不使用第二候选词的位置，而是在其他地方显示一个图标表示仍在获取，而当获取与本地不一致的云拼音结果时，直接讲结果插入一二候选词中间的位置，因为往往云拼音会更准确（以我们真的可以用到这么好的云拼音引擎为前提）。

搜狗我已经太多年没用过了，记忆也可能有出入，我记得以前是在候选框的上方展示一个小云朵，不同的结果出来以后直接用不同的颜色插入到一二候选词中间。

**Comment by escape0707** [comment]
如果获得了和本地一致的结果，将云朵替换成对勾类的 emoji 如何呢？比如 ✅

**Comment by wengxt** [comment]
另外为什么会闪烁，你在用 wayland 吗？

**Comment by wengxt** [comment]
窗口应当完全不会有闪烁只是有内容变化而已

**Comment by escape0707** [comment]
以前用GNOME wayland的时候闪烁，后来查了 Fcitx Wiki 装了 kimpanel 扩展就好了。上面论证的时候只是想到对这类现象敏感的人群然后顺着就打出来了（

**Comment by wengxt** [comment]
@escape0707 那种闪烁只是因为环境问题，其实最完美的配置是不会闪烁的，另外你给的方案也并不能解决闪烁与否的问题。

**Comment by escape0707** [comment]
请忽视掉闪烁的问题，只是之前回复的时候写错了。发issue其实只想讨论候选词位置变化跳动的问题。
