### ISSUE TITLE
Switch Focus between Firefox and Alacritty,Fcitx get segmentation fault.(wayland,hyprland)

### ISSUE THREAD

**Issue by go0d1uck** [fcitx/fcitx5#888]
**Describe the bug**
In Hyprland(wayland) enviroment,
switch focus between Firefox and Alacritty,
sometimes,In the Alacritty,I can't active the method
the fcitx5 log follows
```
D2023-10-31 23:45:57.966956 instance.cpp:2317] Instance::deactivateInputMethod event_type=4100
D2023-10-31 23:45:57.966998 instance.cpp:2335] Deactivate: [Last]:keyboard-us [Deactivating]:keyboard-us
D2023-10-31 23:45:57.967652 instance.cpp:2275] Instance::activateInputMethod
D2023-10-31 23:45:57.967672 instance.cpp:2280] Activate: [Last]: [Activating]:keyboard-us
D2023-10-31 23:45:57.974198 instance.cpp:2317] Instance::deactivateInputMethod event_type=4100
D2023-10-31 23:45:57.974233 instance.cpp:2335] Deactivate: [Last]:keyboard-us [Deactivating]:keyboard-us
```
the Activate:..... not show,also,when i try to set --verbose '*=5' to find what happened,
switch the focus between the Firefox and Alacritty, the fcitx5 will get segmentation fault.

log follows
```
Fcitx 5.1.1 -- Get Signal No.: 11
Date: try "date -d @1698767500" if you are using GNU date ***
ProcessID: 2302243
fcitx5(+0x1030c)[0x5595874dc30c]
/usr/lib/libc.so.6(+0x3e710)[0x7f2da385c710]
/usr/lib/libFcitx5Core.so.7(_ZNK5fcitx12InputContext7programB5cxx11Ev+0x4)[0x7f2da4023524]
/usr/lib/fcitx5/libclassicui.so(+0x6a2c9)[0x7f2da19cf2c9]
/usr/lib/fcitx5/libclassicui.so(+0x5509e)[0x7f2da19ba09e]
/usr/lib/libFcitx5Core.so.7(_ZNK5fcitx8Instance9postEventERNS_5EventE+0x1e6)[0x7f2da40044b6]
/usr/lib/libFcitx5Core.so.7(_ZN5fcitx10FocusGroup22setFocusedInputContextEPNS_12InputContextE+0x10f)[0x7f2da402726f]
/usr/lib/fcitx5/libwaylandim.so(+0x35202)[0x7f2da2392202]
/usr/lib/fcitx5/libwaylandim.so(+0x2ea82)[0x7f2da238ba82]
/usr/lib/fcitx5/libwaylandim.so(+0x399b1)[0x7f2da23969b1]
/usr/lib/libffi.so.8(+0x74f6)[0x7f2da25664f6]
/usr/lib/libffi.so.8(+0x3f5e)[0x7f2da2562f5e]
/usr/lib/libffi.so.8(ffi_call+0x123)[0x7f2da2565b73]
/usr/lib/libwayland-client.so.0(+0x7645)[0x7f2da28f8645]
/usr/lib/libwayland-client.so.0(+0x7e73)[0x7f2da28f8e73]
/usr/lib/libwayland-client.so.0(wl_display_dispatch_queue_pending+0x7c)[0x7f2da28f913c]
/usr/lib/fcitx5/libwayland.so(+0x10832)[0x7f2da2913832]
/usr/lib/libFcitx5Utils.so.2(+0x419b3)[0x7f2da3f389b3]
/usr/lib/libsystemd.so.0(+0x83fba)[0x7f2da3dd0fba]
/usr/lib/libsystemd.so.0(sd_event_dispatch+0x11e)[0x7f2da3dd12de]
/usr/lib/libsystemd.so.0(sd_event_run+0x119)[0x7f2da3dd2fe9]
/usr/lib/libsystemd.so.0(sd_event_loop+0x60)[0x7f2da3dd31c0]
/usr/lib/libFcitx5Utils.so.2(_ZN5fcitx9EventLoop4execEv+0x16)[0x7f2da3f367f6]
/usr/lib/libFcitx5Core.so.7(_ZN5fcitx8Instance4execEv+0x57)[0x7f2da40075e7]
fcitx5(+0xe6df)[0x5595874da6df]
/usr/lib/libc.so.6(+0x27cd0)[0x7f2da3845cd0]
/usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7f2da3845d8a]
fcitx5(+0xfb95)[0x5595874dbb95]
[1]    2302243 segmentation fault (core dumped)  fcitx5 --verbose '*=5' -r
```

**To Reproduce**
1. Open firefox(nightly version)
2. Open alacritty
3. switch the focus to the firefox
4. switch the focus to the alacritty
5. if Fcitx5 work normal,i can active input-method,but now it can't

**Expected behavior**

**Desktop (please complete the following information):**
 - Desktop: hyprland
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.
2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	Arch
        Description:	Arch Linux
        Release:	rolling
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	Arch Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="Arch"
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

6.  Desktop Environment:

    Cannot determine desktop environment.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

8.  Bash Version:

        BASH_VERSION='5.2.15(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':1'

        WAYLAND_DISPLAY='wayland-1'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            POSIX

    2.  Current locale:

            LANG=C.UTF-8
            LC_CTYPE="C.UTF-8"
            LC_NUMERIC="C.UTF-8"
            LC_TIME="C.UTF-8"
            LC_COLLATE="C.UTF-8"
            LC_MONETARY="C.UTF-8"
            LC_MESSAGES="C.UTF-8"
            LC_PAPER="C.UTF-8"
            LC_NAME="C.UTF-8"
            LC_ADDRESS="C.UTF-8"
            LC_TELEPHONE="C.UTF-8"
            LC_MEASUREMENT="C.UTF-8"
            LC_IDENTIFICATION="C.UTF-8"
            LC_ALL=

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.1`

3.  process:

    Found 1 fcitx5 process:

        2257484 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.284`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `2257484`.

    Debug information from dbus:

           Group [x11::1] has 0 InputContext(s)
        Group [wayland:] has 4 InputContext(s)
          IC [3de7c680d0134511b56834d971fdb6bc] program:firefox-nightly frontend:wayland_v2 cap:52 focus:0
          IC [3f3267aa66eb473497408f7ef3782057] program:Alacritty frontend:wayland_v2 cap:100000052 focus:0
          IC [f4fb65b4bde043eda036920fc5c11224] program:Alacritty frontend:wayland_v2 cap:100000052 focus:0
          IC [31633fee04c64ee1aa1fb32cbe491803] program: frontend:wayland_v2 cap:100000052 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS is not set**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt5 built-in Wayland im module if your compositor fully supports text-input protocol used by qt5.**

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QComposeInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt6 built-in Wayland im module if your compositor fully supports text-input protocol used by qt6.**

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=
        IM_MODULE_CLASSNAME=QtWaylandClient::QWaylandInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

    **It is OK to use gtk built-in Wayland im module if your compositor fully supports text-input protocol used by gtk.**

    Using fcitx5-gtk2-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx5

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=wayland

    Using fcitx5-gtk4-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=wayland

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.38` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.38

        Found fcitx5 im modules for gtk `3.24.38`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found immodules cache for gtk `3.24.38` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.38

        Found fcitx5 im modules for gtk `3.24.38`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 27 enabled addons:

            Simplified and Traditional Chinese Translation 5.1.1
            Classic User Interface 5.1.1
            Clipboard 5.1.1
            Cloud Pinyin 5.1.1
            DBus 5.1.1
            DBus Frontend 5.1.1
            Emoji 5.1.1
            Fcitx4 Frontend 5.1.1
            Full width character 5.1.1
            IBus Frontend 5.1.1
            Input method selector 5.1.1
            Keyboard 5.1.1
            KDE Input Method Panel 5.1.1
            Status Notifier 5.1.1
            Notification 5.1.1
            Pinyin 5.1.1
            Extra Pinyin functionality 5.1.1
            Punctuation 5.1.1
            Quick Phrase 5.1.1
            Spell 5.1.1
            Table 5.1.1
            Unicode 5.1.1
            DBus Virtual Keyboard 5.1.1
            Wayland 5.1.1
            Wayland Input method frontend 5.1.1
            XCB 5.1.1
            X Input Method Frontend 5.1.1

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=pinyin

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=pinyin
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Tue Oct 31 23:36:42 CST 2023

2.  `/home/***/.config/fcitx5/crash.log`:

        =========================
        Fcitx 5.1.1 -- Get Signal No.: 11
        Date: try "date -d @1698764824" if you are using GNU date ***
        ProcessID: 2176598
        fcitx5(+0x1030c)[0x55f79356330c]
        /usr/lib/libc.so.6(+0x3e710)[0x7ff3af45c710]
        /usr/lib/libFcitx5Core.so.7(_ZNK5fcitx12InputContext7programB5cxx11Ev+0x4)[0x7ff3afbc0524]
        /usr/lib/fcitx5/libclassicui.so(+0x6a2c9)[0x7ff3ad5692c9]
        /usr/lib/fcitx5/libclassicui.so(+0x5509e)[0x7ff3ad55409e]
        /usr/lib/libFcitx5Core.so.7(_ZNK5fcitx8Instance9postEventERNS_5EventE+0x1e6)[0x7ff3afba14b6]
        /usr/lib/libFcitx5Core.so.7(_ZN5fcitx10FocusGroup22setFocusedInputContextEPNS_12InputContextE+0x10f)[0x7ff3afbc426f]
        /usr/lib/fcitx5/libwaylandim.so(+0x35202)[0x7ff3adf2c202]
        /usr/lib/fcitx5/libwaylandim.so(+0x2ea82)[0x7ff3adf25a82]
        /usr/lib/fcitx5/libwaylandim.so(+0x399b1)[0x7ff3adf309b1]
        /usr/lib/libffi.so.8(+0x74f6)[0x7ff3ae1004f6]
        /usr/lib/libffi.so.8(+0x3f5e)[0x7ff3ae0fcf5e]
        /usr/lib/libffi.so.8(ffi_call+0x123)[0x7ff3ae0ffb73]
        /usr/lib/libwayland-client.so.0(+0x7645)[0x7ff3ae492645]
        /usr/lib/libwayland-client.so.0(+0x7e73)[0x7ff3ae492e73]
        /usr/lib/libwayland-client.so.0(wl_display_dispatch_queue_pending+0x7c)[0x7ff3ae49313c]
        /usr/lib/fcitx5/libwayland.so(+0x10832)[0x7ff3ae4ad832]
        /usr/lib/libFcitx5Utils.so.2(+0x419b3)[0x7ff3afad59b3]
        /usr/lib/libsystemd.so.0(+0x83fba)[0x7ff3af96dfba]
        /usr/lib/libsystemd.so.0(sd_event_dispatch+0x11e)[0x7ff3af96e2de]
        /usr/lib/libsystemd.so.0(sd_event_run+0x119)[0x7ff3af96ffe9]
        /usr/lib/libsystemd.so.0(sd_event_loop+0x60)[0x7ff3af9701c0]
        /usr/lib/libFcitx5Utils.so.2(_ZN5fcitx9EventLoop4execEv+0x16)[0x7ff3afad37f6]
        /usr/lib/libFcitx5Core.so.7(_ZN5fcitx8Instance4execEv+0x57)[0x7ff3afba45e7]
        fcitx5(+0xe6df)[0x55f7935616df]
        /usr/lib/libc.so.6(+0x27cd0)[0x7ff3af445cd0]
        /usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7ff3af445d8a]
        fcitx5(+0xfb95)[0x55f793562b95]
**Additional context**
nothing

**Comment by wengxt** [comment]
Fixed in 5.1.2+ 7bf330412cef5906eac8a386c4e324ee0e95eac9

**Comment by wengxt** [comment]
So, crash can only be triggered by *=5 flag, that's irrelevant to the "can not activate" in alacritty issue.

As for that, I believe it's a hyprland bug.

Basically, the conclusion of this is done via run WAYLAND_DEBUG=1 fcitx5 and WAYLAND_DEBUG=1 alacritty.

Whenever fcitx5 receives a "activate", it will know desktop want to use input method, when deactivate is sent, it will release the keyboard grab.

When you can't use input method in alacritty, I can clearly see that deactivate is sent to fcitx in the latest message. And alacritty also correctly send text_input_v3.enter .

This leads to the conclusion that hyprland is wrongly send deactivate while there is still active application want input method. Please report the bug to hyprland.

**Comment by go0d1uck** [comment]
Thank you very much for your works. fcitx5 is the best Linux input method I've ever used. I believe this must be an issue with Hyprland. Thank you so much!
