### ISSUE TITLE
kde plasma Wayland 下打开非活动窗口变暗特效导致输入法框变暗

### ISSUE THREAD

**Issue by detiam** [fcitx/fcitx5#890]
**Describe the bug**
关闭非活动窗口变暗：
![image](https://github.com/fcitx/fcitx5/assets/44510779/685c6d3c-24f9-4daa-a87f-1302f7a732fb)
开启非活动窗口变暗：
![image](https://github.com/fcitx/fcitx5/assets/44510779/ab25fa09-97b4-4048-9b50-46f4de5f5383)

在X下没有这个问题，只能通过关闭这个特效解决吗，如果关闭这个特效 Electron 应用没有阴影会很难看

**To Reproduce**
1. 设置内设置 工作区行为 - 桌面特效 -焦点增强 - 非活动窗口变暗
2. Try to type

**Expected behavior**
输入法框亮度正常

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

**Additional context**

**Comment by wengxt** [comment]
https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma 用 wayland 前端有这个问题吗？

**Comment by wengxt** [comment]
测试了一下，应该是这样才有这个问题……我觉得应该汇报个bug给 kwin，应该不难解决，因为输入法窗口有特殊的 role 可以写点代码判断

**Comment by wengxt** [comment]
https://invent.kde.org/plasma/kwin/-/merge_requests/4637 我给你在 plasma6 修了一下
