### ISSUE TITLE
wayland下gtk/electron应用`在程序中显示预编辑文本`功能失效。

### ISSUE THREAD

**Issue by yorunning** [fcitx/fcitx5#891]
**Describe the bug**
wayland下gtk/electron应用`在程序中显示预编辑文本`功能失效。

**To Reproduce**
当我按照fcitx的弹窗提醒取消`/etc/environment`中的`GTK_IM_MODULE=fcitx`，gtk/electron应用中的`在程序中显示预编辑文本`功能失效，将这个配置加回去又正常了，QT应用正常（不设置`QT_IM_MODULE=fcitx`的情况下）。

**Expected behavior**

**Desktop (please complete the following information):**
 - Desktop: KDE 5.27.9
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

**Additional context**

**Comment by wengxt** [comment]
@yorunning 因为你在用xwayland的electron，关于electron原生wayland和用原生wayland输入法请参考

https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma

**Comment by yorunning** [comment]
加上参数启动就没问题了
