### ISSUE TITLE
Fcitx5 causes plasma to shut down very slowly

### ISSUE THREAD

**Issue by mingti** [fcitx/fcitx5#896]
[shutdown_journal_log.txt](https://github.com/fcitx/fcitx5/files/13398823/shutdown_journal_log.txt)
[fcitx5_diagnose.txt](https://github.com/fcitx/fcitx5/files/13398824/fcitx5_diagnose.txt)

I use arch+kde ,I find that shutdown is always slow when I click shutdown or restart button in the application board, and there is no problem with using the "restart" or "shutdown" commands. Then I use"yay -Rdd fcitx5" to force uninstall fcitx5 and return to normal.

Attached is the journal log and  fcitx5 diagnose.

Here are the packages I installed for the fcitx5.
![image](https://github.com/fcitx/fcitx5/assets/24843766/09b18828-f794-4904-b4db-38ca4c9c6323)

**Comment by wengxt** [comment]
I believe it's caused by fcitx5-im-emoji-picker-git since it's using Qt, otherwise there's no reason that fcitx will block session.

I don't really recommend this 3rd party addon since it's approach is very hacky and has caused a lot of issues.

**Comment by mingti** [comment]
> I believe it's caused by fcitx5-im-emoji-picker-git since it's using Qt within fcitx5 process, otherwise there's no reason that fcitx will block session.
> 
> I don't really recommend this 3rd party addon since it's approach is very hacky and has caused a lot of issues.

Thank you very much, after uninstall "fcitx5-im-emoji-picker-git", return to normal
