### ISSUE TITLE
Candidate window gets stuck in foot-server after closing the footclient?

### ISSUE THREAD

**Issue by name-snrl** [fcitx/fcitx5#897]
**Describe the bug**
Hi, today I upgraded my system (some NixOS related info):
```
    'github:nixos/nixpkgs/ca012a02bf8327be9e488546faecae5e05d7d749' (2023-10-16)
  → 'github:nixos/nixpkgs/c757e9bd77b16ca2e03c89bf8bc9ecb28e0c06ad' (2023-11-17)
```
and I previously used `nixos/nixpkgs/35d8d1c9e71edd309a89c7eed0955935a184c04f` for the `fcitx5` package. Now all system on `nixos/nixpkgs/c757e9bd77b16ca2e03c89bf8bc9ecb28e0c06ad`.

Before the update there were `fcitx 5.1.0` and `foot 1.16.1`, now `5.1.5` and `1.16.2`, respectively.

Now to the heart of the matter. I'm using `foot` in server mode. Once the system boots up, everything works fine (`foot-server` is already running). Then I open `footclient` or several, and as long as at least one `footclient` exists, everything is fine, but if I close them all and try to write something in any window, the window-candidate closes instantly after spawn.

The problem only occurs if `foot` is running as a server.

Not sure is the problem on `fcitx5` or `foot` side. When I try to install a previous version of `fcitx5` on the current system - `mozc` just doesn't work. I will also post this in `foot` issues.

**To Reproduce**
1. Start foot-server, as systemd service.
2. Open and close `footclient`.
3. Try to type something somewhere using mozc.

**Expected behavior**
The candidate window appears even if no footclient exists.

**Desktop (please complete the following information):**
 - Desktop: sway
 - Display server type: Wayland
 - [The output of fcitx5-diagnose](https://github.com/fcitx/fcitx5/files/13401218/fcitx5-diagnose.txt)

**Additional context**

https://github.com/fcitx/fcitx5/assets/72071763/55b99fbc-ce8a-4d5c-971a-a0315e33f9e6

**Comment by wengxt** [comment]
can you run foot with WAYLAND_DEBUG=1 and grep for text_input_v3

**Comment by name-snrl** [comment]
> can you run foot with WAYLAND_DEBUG=1

Yeah, sure:

[debug_server.log](https://github.com/fcitx/fcitx5/files/13402679/debug_server.log)
[grepped.txt](https://github.com/fcitx/fcitx5/files/13402680/grepped.txt)

But here is the interesting behavior I noticed when performing this. At first I thought "oke, I'll run `foot-server` in another terminal emulator", but when I did - everything works fine... I created a bind in `sway` to open `alacritty`, from inside I ran `WAYLAND_DEBUG=1 foot --server &> ~/debug_server.log` and after opening and closing `footclient` everything worked fine.

Okay, so I started experimenting with this and here's what I found out: **the problem only occurs if the _last_ closed window in the previous workspace was `footclient`**.

it adds some conditions to reproduce the problem:
- If you open/close `footclient` in the same workspace that `firefox` is in, everything will work fine.
- If any other window exists in the workspace where you switch to open/close `footclient`, everything will work fine. (is what happened in the case described above)

**Comment by wengxt** [comment]
There's some other bug on hyprland https://github.com/hyprwm/Hyprland/issues/3896 , it's also wlroots based.

Would you mind test kwin? (I personally contribute code to kwin so I'm more familiar with its code and confident about its text-input implementation). 

As some other way, can you also just unset GTK_IM_MODULE, or set it to GTK_IM_MODULE=wayland? So firefox can use text-input-v3 (via gtk's built in im module).

Make all client text-input-v3 may be able to avoid certain issues as a workaround.

**Comment by name-snrl** [comment]
> There's some other bug on hyprland

I've read this, but it's not my case. Fcitx works in my case, but changes are committed instantly when I stop writing. I can also change the layout, which the guys from this issue can't do.

> Would you mind test kwin? (I personally contribute code to kwin so I'm more familiar with its code and confident about its text-input implementation).

Everything works well in kwin, I thing you are right and the problem is on sway/wlroots side.

> As some other way, can you also just unset GTK_IM_MODULE, or set it to GTK_IM_MODULE=wayland? So firefox can use text-input-v3 (via gtk's built in im module).

it seems to work, even though I don't have a candidate window (applying the mentioned patch to sway was not easy), I can choose among them. It doesn't commit instantly.

> Make all client text-input-v3 may be able to avoid certain issues as a workaround

As I realized after this article https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland, this is not possible for Qt (most of my applications) on sway :c

**Comment by name-snrl** [comment]
Holy f**k... The problem was in [clight](https://github.com/FedeDP/Clight), more specifically in the `scree` functionality that uses `wlr-screencopy-unstable-v1`

https://github.com/FedeDP/Clightd/wiki/Screen#wl
