### ISSUE TITLE
尝试将中文输入设为第一语言之后， 在某些程序下（例如 konsole), 单按 Shift 无法切换中英文了？ 

### ISSUE THREAD

**Issue by zw963** [fcitx/fcitx5#899]
更改默认输入语言为中文。正如如下截图描述的那样。

![image](https://github.com/fcitx/fcitx5/assets/549126/209d976e-4138-4c3f-98c1-7696491a6ccf)

然后，我就发现，无法使用 Shift 来快速的单键切换中英文了。

恢复默认语言英文（默认），则 Shift 又可以正常工作了。

谢谢。

------------------

EDIT: Arch Linux, 当前系统环境及 locale 香瓜设置均为英文。

**Comment by wengxt** [comment]
设计就是这样的。第一个输入法就是非激活状态，其他输入法是激活状态
shift 是允许从激活状态切回来

如果你想默认中文，英文放在第一个，然后
在全局选项里改为默认状态为激活。

**Comment by zw963** [comment]
请教一个问题，我希望进系统默认输入字符就是英文，但是可以单按 Shift 切换到中文。（就是省略 Ctrl + Space 这一步），又该如何做？

目前我知道能做到的是：

1. 进系统打字立即就是中文这不是我想要的。
2. 进系统打字英文，但是按 Shift 没任何反应。需要 Ctrl + Space 切换后，才能 Shift 切换。
谢谢。

**Comment by wengxt** [comment]
把现在配置里的shift去掉，然后添加到ctrl space那里
