### ISSUE TITLE
禁用历史记录/用户词库？

### ISSUE THREAD

**Issue by reveperdu** [fcitx/fcitx5#903]
我正在使用fcitx5自带的拼音（双拼）输入，找了找好像没看到有禁用历史记录/用户词库的功能，在未来版本会考虑加入吗？
（虽然好像可以通过`rm .local/share/fcitx5/pinyin/user.history`删除历史记录，但我略微更倾向于输入法一开始就不记录输入历史，或者至少在配置面板中提供清除历史的功能）
我的系统是Debian 12,通过apt安装的fcitx5,软件包的版本是5.0.21-3,fcitx5-chinese-addons版本是5.0.16-1

**Comment by wengxt** [comment]
词典管理里可以清空

**Comment by reveperdu** [comment]
> 词典管理里可以清空

好的，抱歉之前没看到
