### ISSUE TITLE
KDE Wayland下使用text-input后Libreoffice Impress输入法不跟随

### ISSUE THREAD

**Issue by Bob0111** [fcitx/fcitx5#906]
**Describe the bug**
当我在libreoffice impress（后端为kf5）中输入中文，如若切换幻灯片或输入的文本框，fcitx5无法在新的输入正确弹出输入框.
**To Reproduce**
1. 打开libreoffice impress，新建幻灯片
2. 在标题栏输入任意文字
3. 在副标题中输入任意文字
4. 输入框依然出现在标题栏附近

**Expected behavior**
输入框出现到新的输入位置。

**Desktop (please complete the following information):**
 - Desktop:KDE
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

**Comment by wengxt** [comment]
坐标是 libreoffice 汇报的，和 fcitx 无关，根据 WAYLAND_DEBUG 是 qt 实现汇报光标位置不及时。

fcitx5-qt 的 im module 里面实际是有很多 hack 来更积极地获取光标位置的，可能遮掩了 libreoffice qt plugin 自己的 bug。

你可以用 gtk 来使用 gtk text input 实现，看起来比较好一点
