### ISSUE TITLE
Why can't make my own customized words library in fcitx5-pinyin?

### ISSUE THREAD

**Issue by hwypengsir** [fcitx/fcitx5#909]
I want to make my own customized word library:

```
cat  sample.txt
月令	yue'ling	0
```
There is only one line in it,i want to show 月令 when to type yue'ling in fcitx5-pinyin,converti the sample.txt into my.dict,and copy it into dictionaries directory:
```
/usr/bin/libime_pinyindict  sample.txt  sample.dict
cp  sample.dict   $HOME/.local/share/fcitx5/pinyin/dictionaries
```
Reboot ,start fcitx5-pinyin,no 月令 shown when to type yue'ling,how to fix it?

**Comment by wengxt** [comment]
to be honest, with the latest version , "yue ling" even appear without any dictionary.

![图片](https://github.com/fcitx/fcitx5/assets/259684/8d409dc2-7f5b-4fbc-8ff7-0461f91b0533)

Which indicates you might be using a very old version of libime/fcitx5/fcitx5-chinese-addons

but I add a random word for yue'ling just to test it and it works.

```
ABCDEF  yue'ling        0
```

![图片](https://github.com/fcitx/fcitx5/assets/259684/d6531c85-1970-4c9d-bf9d-fadba483dc53)

In the older version of libime, the short word in dict might be in the 2nd 3rd pages, can you check if it's there?

Also, please test on the latest version and see if you can still reproduce.

**Comment by hwypengsir** [comment]
fcitx5  -version
5.0.5

What is your version then?

**Comment by wengxt** [comment]
5.0.5 is almost 3 years old. FYI.
