### ISSUE TITLE
Cannot set Alt+Shift or Control+Super as key method input switchers.

### ISSUE THREAD

**Issue by mindey** [fcitx/fcitx5#914]
**Describe the bug**
Simple. There's no way to use Alt+Shift or Ctrl+Super.

**To Reproduce**
1. Open Fcitx Configuration > Global Options
2. Click on the area Enumerate Input Method Forward (or other) to capture chosen key combinations.
3. Type: Left Alt + Left Shift: result is that only Left Alt is entered.
4. Type: Left Control + Super: result is that only Left Control is entered.

**Expected behavior**
On 3rd step above:
Typing Left Alt + Left Shift would result in setting Left Alt + Left Shift.
Typing Super + Left Control would result in setting Super + Left Control.

**Desktop (please complete the following information):**
 - Desktop: xfce4
 - Display server type: x11

**Additional context**
fcitx5 version 5.0.21 on debian 12

**Comment by wengxt** [comment]
Can you try the latest version ?
I can’t reproduce it here.
You can install it from fcitx5-unstable flatpak.

https://fcitx-im.org/wiki/Install_Fcitx_5#Install_Fcitx_5_from_Flatpak

`flatpak run --command=fcitx5-config-qt org.fcitx.Fcitx5` should launch the latest config qt.

Please reopen if you can reproduce.
