### ISSUE TITLE
Option to disable layout switching, please.

### ISSUE THREAD

**Issue by mindey** [fcitx/fcitx5#921]
**Describe the bug**
If I start fcitx5, it takes over the keyboard layout switching, but I want to use it as IME solution only.

**To Reproduce**
1. For example, in xfce4 desktop environment, there's tray icon for layout switcher ( https://docs.xfce.org/xfce/xfce4-settings/keyboard ), add that tray icon, and a few layouts.
2. Then start fcitx5. The fcitx5 takes over layout switching, and renders the default xfce4 layout switcher frozen.

https://github.com/fcitx/fcitx5/assets/384735/5e0823c2-4c2c-4341-800b-e3aa6bb5a354

**Expected behavior**
Fcitx5 should ask, if you want it to take over the layout switching, or only use as IME solution, with user taking care of their layout switching by themselves. There should be option "Allow fcitx5 to switch keyboard layouts." If this option is not selected, then fcitx5 should never not touch the keyboard layouts even upon restarts.

Among other useful options for behavior, would be to synchronize the behavior of native keyboard layout switcher with Fcitx5, or the feature enabling for switching keyboard layouts without changing IME within Fcitx5.

**Desktop (please complete the following information):**
 - Desktop: xfce4
 - Display server type: X11

**Additional context**
Debian 12

**Comment by wengxt** [comment]
there’s a such option in xcb addon.

**Comment by wengxt** [comment]
but, I don’t agree. Input method and keyboard layout should be managed all together.

If you find any issue using fcitx 5’s layout management, it should be fixed.

That option is left as a workaround.
