### ISSUE TITLE
fcitx5 chinese input failed when the try icon indicate current langauge is Chinese with no any changes

### ISSUE THREAD

**Issue by zw963** [fcitx/fcitx5#922]
**Describe the bug**

Don't know what happens, I just keeping updating fcitx5 to newest version follow arch rolling but keeping old config, but Chinese input is invalid yesterday, even after reboot. the tray icon in the GNOME indicate current is Chinese input(see following screen), but when typing, still get English char input.

![image](https://github.com/fcitx/fcitx5/assets/549126/299012a4-4bcc-4b09-b0c9-b71c94d72a20)

I test this on both konsole, firefox,telegram, both not work.

**Expected behavior**
It should ouput Chinese char.

**Desktop (please complete the following information):**
 - Desktop: GNOME 45
 - Display server type: Wayland
 
<details>
<summary>fcitx5-diagnose output</summary>
# System Info:
1.  `uname -a`:

        Linux mingfan 6.6.8-x64v2-xanmod1-1 #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 12:43:54 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	Arch
        Description:	Arch Linux
        Release:	rolling
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	Arch Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="Arch"
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

6.  Desktop Environment:

    Desktop environment is `gnome3`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

8.  Bash Version:

        BASH_VERSION='5.2.21(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY='wayland-0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            en_US.utf8
            POSIX
            zh_CN.utf8
            zh_TW.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/zw963

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/zw963/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/zw963/.config/fcitx5`).

5.  Current user:

    The script is run as zw963 (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/sbin/fcitx5`.

2.  version:

    Fcitx version: `5.1.5`

3.  process:

    Found 1 fcitx5 process:

           6613 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.592`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `6613`.

    Debug information from dbus:

           Group [x11::0] has 4 InputContext(s)
          IC [01808b231102411db17c23b750e8dfe9] program:goldendict frontend:dbus cap:6000800072 focus:0
          IC [a276a1e5878b435cbd14c6402b0801b4] program:qq frontend:dbus cap:6000000032 focus:0
          IC [16343856320843dbada89934fe8507e2] program:copyq frontend:dbus cap:16000800072 focus:0
          IC [36370503e5244c52a9ae93663cd39b2f] program:konsole frontend:dbus cap:6000820872 focus:1
        Group [wayland:] has 8 InputContext(s)
          IC [af638042f43847b4ba3164649a4559cc] program:gnome-extensions-app frontend:dbus cap:4001000032 focus:0
          IC [60bcf7689fa34b5b9fa0712781840b0e] program:firefox frontend:dbus cap:6001000032 focus:0
          IC [323d6e18904b416894a4c22e0392742d] program:telegram-desktop frontend:dbus cap:6801800072 focus:0
          IC [f4322f92837e4a20858e2e5a7f2af505] program:firefox frontend:dbus cap:6001000032 focus:0
          IC [86b438c7928e483c9df198d7bb7970f6] program:firefox frontend:dbus cap:6001000032 focus:0
          IC [53c2c187d2ef410d8e0d4eb1468fc726] program:firefox frontend:dbus cap:6001000072 focus:0
          IC [9387f73326304955af4a459256d8ec21] program: frontend:ibus cap:52 focus:0
          IC [c71e0a92dd464623b478d0cbffc7aa3e] program:fsearch frontend:dbus cap:6001000072 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/sbin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/sbin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM for Emacs:

    **Your LC_CTYPE is set to en_US.UTF-8 instead of one of zh, ja, ko. You may not be able to use input method in emacs because of an really old emacs bug that upstream refuse to fix for years.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT4_IM_MODULE is set to "fcitx" correctly.

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt5-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

3.  qt6 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-qt6-immodule-probing to check the actual im module to be used under current environment:

        QT_QPA_PLATFORM=wayland
        QT_IM_MODULE=fcitx
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext

4.  Qt IM module files:

    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

    Using fcitx5-gtk2-immodule-probing to check the actual im module to be used under current environment:

    Using fcitx5-gtk3-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

    Using fcitx5-gtk4-immodule-probing to check the actual im module to be used under current environment:

        GTK_IM_MODULE=fcitx

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.39` at `/usr/sbin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/sbin/gtk-query-immodules-3.0 from gtk+-3.24.39

        Found fcitx5 im modules for gtk `3.24.39`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.39` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.39

        Found fcitx5 im modules for gtk `3.24.39`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 27 enabled addons:

            Simplified and Traditional Chinese Translation 5.1.2
            Classic User Interface 5.1.5
            Clipboard 5.1.5
            Cloud Pinyin 5.1.2
            DBus 5.1.5
            DBus Frontend 5.1.5
            Emoji 5.1.5
            Fcitx4 Frontend 5.1.5
            Full width character 5.1.2
            IBus Frontend 5.1.5
            Input method selector 5.1.5
            Keyboard 5.1.5
            KDE Input Method Panel 5.1.5
            Status Notifier 5.1.5
            Notification 5.1.5
            Pinyin 5.1.2
            Extra Pinyin functionality 5.1.2
            Punctuation 5.1.2
            Quick Phrase 5.1.5
            Spell 5.1.5
            Table 5.1.2
            Unicode 5.1.5
            DBus Virtual Keyboard 5.1.5
            Wayland 5.1.5
            Wayland Input method frontend 5.1.5
            XCB 5.1.5
            X Input Method Frontend 5.1.5

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

    Kimpanel process:

           1440 /usr/bin/gnome-shell

## Input Methods:
1.  `/home/zw963/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=keyboard-cn

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=keyboard-cn
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Mon Dec 25 08:38:09 PM CST 2023

2.  `/home/zw963/.config/fcitx5/crash.log`:

    `/home/zw963/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**
</details>

**Additional context**

**Comment by zw963** [comment]
BTW: this should not a config issue, because after i delete config in `~/.config/fcitx5`, then reboot, Chinese input still not available.

Thanks

**Comment by wengxt** [comment]
I didn't see you added pinyin, can you re-add that with config tool?

**Comment by wengxt** [comment]
since you're using arch, can you also
```
pacman -Qs fcitx
pacman -Qs libime
```

In case you have some non-offical package installed?

**Comment by zw963** [comment]
Oops, my fault. too long not change fcitx5 config, probably somethings broken make `pinyin` gone ... i search `Chinese`, add a `Keyboard - Chinese` back.

![image](https://github.com/fcitx/fcitx5/assets/549126/5538505c-2d32-4837-8218-16fc0bd39c53)

After add `pinyin` back, it works, it isn't fcitx version conflict or libime issue, thanks!
