### ISSUE TITLE
How can let fcitx5 work in kodi ?

### ISSUE THREAD

**Issue by oooxxooo** [fcitx/fcitx5#923]
**Describe the bug**
If the problem is about you can not use fcitx in certain application, or the input window is placed in wrong place, be sure to include which application is being typed, and the output of fcitx5-diagnose command.

Specifically, it is Ok to write the issue in Chinese (either Simplified or Traditional), because lots of developers understand Chinese.
可以用中文(简体或繁体)汇报问题。

The opened issue might be closed right away if it is considered a configuration issue (E.g. required packages not installed, wrong environment variables, misconfiguration like not adding wrong input method engine to the configuration, etc), but you may continue to use the issue comment to follow up for support.

**To Reproduce**
1. Open ... app
2. Try to type ...

**Expected behavior**
How can let fcitx5 work in kodi ?
My OS is Arch linux & WM is I3 , everything work fine but kodi ,
it looks like kodi need an addon for fcitx or something else .
Maybe kodi need a virtual keyboard addon, or something else.
我的系统是linux窗口管理是I3，除了kodi其它app都正常工作。
感觉好像kodi需要一个插件或者其它东西。
也许kodi需要一个虚拟键盘插件，或者其它东西。
Maybe I can help out. I can code a little.
But I did know much about IME.
也许我能帮助解决这个问题，我能码一点点。
但是我不太懂输入法。

**Desktop (please complete the following information):**
 - Desktop: ( -- )
 - Window manager: I3
 - Display server type: X11

**Additional context**

**Comment by oooxxooo** [comment]
I found this. 我找到这个。
https://forum.kodi.tv/showthread.php?pid=1218524

**Comment by wengxt** [comment]
那个是另一个问题，我注意到 kodi 是有初始化 xim 的，而且也做了对应的设置，但是不知道为何按键并没有被发送给输入法

**Comment by wengxt** [comment]
kodi 自己的插件确实有提供输入法的（类似chrome插件提供网页内的输入法），和系统的输入法无关，这个你就自己研究一下吧，我只关注 kodi 和系统输入法之间的问题

**Comment by oooxxooo** [comment]
大哥，那怎么才能在kodi上用fcitx呀？

import os
import ChineseKeyboard
# from lib.ChineseKeyboard import *


os.system(' fcitx5-remote -t ')

default=''
heading='中文输入法'
keyboard = ChineseKeyboard.Keyboard(default,heading)
keyboard.doModal()
if (keyboard.isConfirmed()):
    # input_string = keyboard.getText()
    input_string = 'abcd'

插件我只能写到这样，写不下去了，fcitx可以作切换，但是不知道怎么获取内容。
安卓上也是调不出系统输入法的，感觉kodi把自己作为系统设计，有个虚拟键盘的设置。
他把我github的问题关了，让我去论坛，我是不知道怎么在他的论坛搞事情。

**Comment by wengxt** [comment]
@oooxxooo 我已经找到他们代码的bug了，正在写pr

**Comment by oooxxooo** [comment]
初始化 xim ， 这些东西我都不太懂，有什么可以帮忙的吗?
这个软件有fcitx就完美了。

**Comment by oooxxooo** [comment]
> @oooxxooo 我已经找到他们代码的bug了，正在写pr

好的，谢谢了。

**Comment by wengxt** [comment]
https://github.com/xbmc/xbmc/pull/24393

然后你还需要上面那个  xcb-imdkit 的修改， https://github.com/fcitx/xcb-imdkit/commit/2553f2ec1397cd93facde4bff9fd841056611ddc 就可以用了

**Comment by oooxxooo** [comment]
dd

> [xbmc/xbmc#24393](https://github.com/xbmc/xbmc/pull/24393)
> 
> 然后你还需要上面那个 xcb-imdkit 的修改， [fcitx/xcb-imdkit@2553f2e](https://github.com/fcitx/xcb-imdkit/commit/2553f2ec1397cd93facde4bff9fd841056611ddc) 就可以用了

大哥，没太看懂要作什么操作呀？

**Comment by oooxxooo** [comment]
> [xbmc/xbmc#24393](https://github.com/xbmc/xbmc/pull/24393)
> 
> 然后你还需要上面那个 xcb-imdkit 的修改， [fcitx/xcb-imdkit@2553f2e](https://github.com/fcitx/xcb-imdkit/commit/2553f2ec1397cd93facde4bff9fd841056611ddc) 就可以用了

```git clone https://github.com/fcitx/xcb-imdkit
mkdir build
cmake -S xcb-imdkit -B build # need extra-cmake-modules and libxcb devel files.
cmake --build build
./build/test/test_server &
XMODIFIERS=@im=test_server kodi
```
大哥，这个操作下来，Ctrl-Space没有反应哦，我定义的是Ctrl+Shift也不行。

**Comment by oooxxooo** [comment]
> @oooxxooo 首先patch kodi，用那个pr里的patch，重新编译。然后更新xcb imdkit到master，我在里面的命令是给他们kodi的人测试用的…

大哥，有时间教下我怎么patch kodi吗，我一直都只是在写shell脚本和配置文件，
不会patch，麻烦了。

**Comment by oooxxooo** [comment]
> @oooxxooo 首先patch kodi，用那个pr里的patch，重新编译。然后更新xcb imdkit到master，我在里面的命令是给他们kodi的人测试用的…

是下载源码，然后修改你说的文件，然后编译整个kodi，这样吗？

**Comment by wengxt** [comment]
@oooxxooo 推荐用你的发行版的打包脚本打包而不是make install

**Comment by oooxxooo** [comment]
> @oooxxooo 推荐用你的发行版的打包脚本打包而不是make install

太尴尬，为什么你说的我都不知道怎么操作。。。

**Comment by oooxxooo** [comment]
> @oooxxooo 推荐用你的发行版的打包脚本打包而不是make install

大哥，说的是这个东西吗？
”Arch Linux的打包脚本通常使用PKGBUILD文件来定义。“
```
# Maintainer: Your Name <your@email.com>
pkgname=package-name
pkgver=1.0.0
pkgrel=1
pkgdesc="Package description"
url="https://example.com/package"
license=("MIT")
depends=(dependency1 dependency2)
makedepends=(build-dependency1 build-dependency2)
source=(https://github.com/username/repository/archive/v${pkgver}.tar.gz)
sha256sums=('SHA256_HASH')
 
prepare() {
    cd "${srcdir}/package-${pkgver}"
}
 
build() {
    make
}
 
install() {
    make install DESTDIR="${pkgdir}"
}
```

**Comment by wengxt** [comment]
你会 makepkg 吗……

https://wiki.archlinux.org/title/makepkg

不过既然你用 arch 我就送佛送到西了 

你用这个 makepkg 就行了，我在官方 https://gitlab.archlinux.org/archlinux/packaging/packages/kodi/ 打包的基础上加了我的 patch

[kodi-20.2-6.src.tar.gz](https://github.com/fcitx/fcitx5/files/13812422/kodi-20.2-6.src.tar.gz)

**Comment by oooxxooo** [comment]
> 你会 makepkg 吗……
> 
> https://wiki.archlinux.org/title/makepkg
> 
> 不过既然你用 arch 我就送佛送到西了
> 
> 你用这个 makepkg 就行了，我在官方 https://gitlab.archlinux.org/archlinux/packaging/packages/kodi/ 打包的基础上加了我的 patch
> 
> [kodi-20.2-6.src.tar.gz](https://github.com/fcitx/fcitx5/files/13812422/kodi-20.2-6.src.tar.gz)

补课中。。。

**Comment by oooxxooo** [comment]
大哥这饭都喂到嘴里了，实在是惭愧呀，丢人。。。
还说自己用ARCH，PKGBUILD也不会，makepkg也不会。

先下载大哥这个，[kodi-20.2-6.src.tar.gz](https://github.com/fcitx/fcitx5/files/13812422/kodi-20.2-6.src.tar.gz)。
然后解压文件，然后去到文件夹，
看到有PKGBUILD这个文件，就可以makepkg了。
我的环境，还少依赖，
```
sudo pacman -Sy afpfs-ng \
  doxygen             \
  java-runtime        \
  libaacs             \
  libmpeg2            \
  libva-vdpau-driver  \
  nasm                \
  python-pybluez      \
  swig                \
  rapidjson           \
  meson               \
  gtest               \
  graphviz            \
  wayland-protocols 
```
```
sudo pacman -Sy jre17-openjdk
```
```
cd ./kodi  # 文件解压目录
```
```
makepkg
```

**Comment by oooxxooo** [comment]
makepkg, build 了半个多小时，失败了 。。。
再试一次，看看。

**Comment by oooxxooo** [comment]
makepkg , build 不起来呀，大哥。。。

[ 96%] Building CXX object build/interfaces/python/CMakeFiles/python_interface.dir/PyContext.cpp.o
[ 96%] Linking CXX static library python_interface.a
[ 96%] Built target python_interface
[ 96%] Generating AddonModuleXbmcwsgi.i.cpp
Caught: BUG! exception in phase 'semantic analysis' in source unit '/0000/HH¦DATA/80_down/firefox/kodi-/src/xbmc-20.2-Nexus/tools/codegenerator/Generator.groovy' Unsupported class file major version 65
BUG! exception in phase 'semantic analysis' in source unit '/0000/HH¦DATA/80_down/firefox/kodi-/src/xbmc-20.2-Nexus/tools/codegenerator/Generator.groovy' Unsupported class file major version 65
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
make[2]: *** [build/swig/CMakeFiles/python_binding.dir/build.make:118: build/swig/AddonModuleXbmcwsgi.i.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:12706: build/swig/CMakeFiles/python_binding.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by oooxxooo** [comment]
build不了，可能是多个java-runtime的原因。
现在makepkg成功了，但是我运行build好的kodi还是不行哦。

==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "kodi-dev"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: kodi 20.2-6 (Wed 03 Jan 2024 05:20:58 PM HKT)

**Comment by oooxxooo** [comment]
大哥，不行哦，没有办法调出fcitx。
我这边怎么排查？
```
sudo pacman -U ./kodi-20.2-6-x86_64.pkg.tar.zst
```

**Comment by oooxxooo** [comment]
> 你会 makepkg 吗……
> 
> https://wiki.archlinux.org/title/makepkg
> 
> 不过既然你用 arch 我就送佛送到西了
> 
> 你用这个 makepkg 就行了，我在官方 https://gitlab.archlinux.org/archlinux/packaging/packages/kodi/ 打包的基础上加了我的 patch
> 
> [kodi-20.2-6.src.tar.gz](https://github.com/fcitx/fcitx5/files/13812422/kodi-20.2-6.src.tar.gz)



> 大哥，不行哦，没有办法调出fcitx。 我这边怎么排查？
> 
> ```
> sudo pacman -U ./kodi-20.2-6-x86_64.pkg.tar.zst
> ```

**Comment by oooxxooo** [comment]
> 大哥，不行哦，没有办法调出fcitx。 我这边怎么排查？
> 
> ```
> sudo pacman -U ./kodi-20.2-6-x86_64.pkg.tar.zst
> ```



> 你会 makepkg 吗……
> 
> https://wiki.archlinux.org/title/makepkg
> 
> 不过既然你用 arch 我就送佛送到西了
> 
> 你用这个 makepkg 就行了，我在官方 https://gitlab.archlinux.org/archlinux/packaging/packages/kodi/ 打包的基础上加了我的 patch
> 
> [kodi-20.2-6.src.tar.gz](https://github.com/fcitx/fcitx5/files/13812422/kodi-20.2-6.src.tar.gz)

大哥，不行哦，没有办法调出fcitx。
我这边怎么排查？
```
sudo pacman -U ./kodi-20.2-6-x86_64.pkg.tar.zst
```

**Comment by wengxt** [comment]
@oooxxooo 我不是说了还要更新xcb-imdkit到master吗，安装aur的xcb-imdkit-git
