### ISSUE TITLE
fcitx5-mozc romaji input issue in YouTube live chat

### ISSUE THREAD

**Issue by TakuikaNinja** [fcitx/fcitx5#925]
**Describe the bug**
This is a very specific issue I ran into while watching a Japanese live stream on YouTube. The romaji input accepts the first consonant as a full-width Latin character immediately, causing the rest of the input to not be converted correctly. If the keys are pressed at the same time, the conversion goes through properly sometimes (affected by keyboard ghosting).

![Screenshot_2023-12-27_14-27-05](https://github.com/fcitx/fcitx5/assets/43363447/e74677cf-7eb5-403d-80d2-b0475e841c9f)
Above: The text is supposed to be `げ` but the `g` has been treated as its own letter.

This issue does not occur in the comments section or any other text field on YouTube.

**To Reproduce**
1. Open a YouTube live stream in Firefox
2. Try to type in the chat with romaji input

**Expected behavior**
The romaji input is correctly converted to Japanese, regardless of any delays between keys.

**Desktop:**
 - OS: EndeavourOS (Arch-based)
 - Desktop: XFCE4
 - Display server type: X11
 - The output of fcitx5-diagnose has been attached. [fcitx5.log](https://github.com/fcitx/fcitx5/files/13774833/fcitx5.log)

**Additional context**
I checked with Edge & Firefox on a Windows VM and the romaji input is handled correctly.

**Comment by TakuikaNinja** [comment]
On further inspection, this may be an issue with Firefox on linux.

**Comment by wengxt** [comment]
This kind of issue is because the application that you're typing with sending a reset signal (to indicate input method that need to reset the state) to input method. Input method can do nothing with it.

However, you can temporarily disable preedit temporarily which is usually the trigger of this reset signal, by pressing "Ctrl+Alt+P".
