### ISSUE TITLE
[wayland] wrong IM state after closing and re-opening windows

### ISSUE THREAD

**Issue by lilydjwg** [fcitx/fcitx5#928]
**Describe the bug**
With wlroots, the initial IM state may be wrong after closing and re-opening windows.

**To Reproduce**
1. Open alacritty and activate IM
2. Close alacritty
3. Open another alacritty
4. The IM state is activated

**Expected behavior**

The initial IM state on the newly created alacritty should be deactivated like other newly created alacritty windows.

**Desktop (please complete the following information):**
 - Desktop: Wayfire (my fork), Hyprland 0.33.1
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

**Additional context**

https://github.com/fcitx/fcitx5/blob/a4e4311226ead198a17248a62ac1ad05a964d43c/src/frontend/waylandim/wlrappmonitor.cpp#L81-L82

The ZwlrForeignToplevelHandleV1 handle address is reused. A newly created window has the handle with address
the same as a previously-closed one.

**Comment by wengxt** [comment]
I don't really get it, you mean zwlr_foreign_toplevel_handle_v1.closed() is not called?

Otherwise why would the address be reused?

**Comment by lilydjwg** [comment]
It's called. It's been freed and so can be reused?

**Comment by lilydjwg** [comment]
I don't know how this reuse relates to the problem. It's only an observation. The window id from the Wayland protocol is reused too.

**Comment by wengxt** [comment]
@lilydjwg I think the issue is that ::remove() missing a call to refresh

**Comment by lilydjwg** [comment]
Yes, adding a refresh call fixes it.
