### ISSUE TITLE
Can't assign both Alt+Shift and Shift+Alt to switch beetwen input methods.

### ISSUE THREAD

**Issue by RobberFox** [fcitx/fcitx5#930]
**Describe the bug**
Assigning `Alt-Shift` to switch input methods works. But `Shift+Alt` doesn't work, istead `Shift+Super+Meta_L` is being assigned.
![image](https://github.com/fcitx/fcitx5/assets/142990781/554e7450-4d12-495a-90f4-815e4dd07ebe)
I would like to be able to assign both Alt+Shift and Shift+Alt shortcuts for comfortable switching between input methods.

**I use:** Ubuntu 22.04 LTS, GNOME 3, X11

Here is the output of `fcitx5-diagnose`: [fcitx5diagnose.txt](https://github.com/fcitx/fcitx5/files/13816183/fcitx5diagnose.txt)

**Additional context:** I've installed fcitx5 through the Ubuntu's software center.

**Comment by wengxt** [comment]
I think that's expected, because meta_L is indeed what's generated by the keyboard.
