### ISSUE TITLE
主题能否更改候选词序号的字体和颜色？

### ISSUE THREAD

**Issue by JadeVane** [fcitx/fcitx5#933]
**Describe the bug**
我最近在制作一个fcitx5的主题，没找到相关的文档，所以只能自己摸索。但现在发现默认生成的主题文件里面没有更改候选词序号的配置，请问有提供更改的方式吗

**Expected behavior**
修改候选词序号的字号和颜色

**Desktop (please complete the following information):**
 - Desktop: GNOME
 - Display server type: Wayland

**Additional context**
就是这个序号，每个词前面的1、2、3...
![图片](https://github.com/fcitx/fcitx5/assets/34258753/a9daa529-8753-4ccc-8d2c-1ae4be0dbc59)

**Comment by oldherl** [comment]
目前没有

**Comment by wengxt** [comment]
没有，你截图的多半是 kimpanel，就更没有了。数字和候选词也是作为一个整体，并不能单独设置字体。
