### ISSUE TITLE
With sway layout conversion does not work

### ISSUE THREAD

**Issue by eternal-sorrow** [fcitx/fcitx5#935]
**Describe the bug**
I set up `xkb_layout us,ru,jp` in sway config and also I set up three input groups in the fcitx config - one with US keyboard, one with Russian keyboard and one with JP keyboard and Anthy IME. I can't get it to work. What I want to do is to activate IME only when I switch to JP layout. Right now it does not activate at all. If I setup only 1 input group with Anthy IME, it activates alright, but It is always active, no matter the current layout and I have no way to deactivate it, so I cant type English or Russian.

**To Reproduce**
1. Open any app that supports IME (for me it's GTK apps and foot terminal)
2. Switch layouts.
3. Nothing happens.

**Expected behavior**
IME activates only with JP layout.

**Desktop (please complete the following information):**
 - Desktop: Sway
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

# System Info:
1.  `uname -a`:

        Linux renoir 6.6.8-zen1 #1 ZEN SMP PREEMPT_DYNAMIC Thu Dec 28 00:30:12 +10 2023 x86_64 AMD Ryzen 7 PRO 5850U with Radeon Graphics AuthenticAMD GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	Gentoo
        Description:	Gentoo Linux
        Release:	2.14
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	Gentoo Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="Gentoo"

5.  `/etc/os-release`:

        NAME=Gentoo
        ID=gentoo
        PRETTY_NAME="Gentoo Linux"
        ANSI_COLOR="1;32"
        HOME_URL="https://www.gentoo.org/"
        SUPPORT_URL="https://www.gentoo.org/support/"
        BUG_REPORT_URL="https://bugs.gentoo.org/"
        VERSION_ID="2.14"

6.  Desktop Environment:

    Cannot determine desktop environment.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

8.  Bash Version:

        BASH_VERSION='5.2.21(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY='wayland-1'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            WARNING: Running setxkbmap against an Xwayland server
            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            en_DK.utf8
            en_GB.utf8
            en_US.utf8
            POSIX
            ru_RU.utf8

    2.  Current locale:

            LANG=en_GB.UTF-8
            LC_CTYPE="en_GB.UTF-8"
            LC_NUMERIC=ru_RU.UTF-8
            LC_TIME=en_DK.UTF-8
            LC_COLLATE="en_GB.UTF-8"
            LC_MONETARY=ru_RU.UTF-8
            LC_MESSAGES="en_GB.UTF-8"
            LC_PAPER="en_GB.UTF-8"
            LC_NAME="en_GB.UTF-8"
            LC_ADDRESS="en_GB.UTF-8"
            LC_TELEPHONE="en_GB.UTF-8"
            LC_MEASUREMENT=en_DK.UTF-8
            LC_IDENTIFICATION="en_GB.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/sorrow

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/sorrow/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/sorrow/.config/fcitx5`).

5.  Current user:

    The script is run as sorrow (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.1.6`

3.  process:

    Found 1 fcitx5 process:

          71646 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.148`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `71646`.

    Debug information from dbus:

           Group [wayland:] has 3 InputContext(s)
          IC [b4865217efa14b86b8d1e7f1b3c76239] program:foot frontend:wayland_v2 cap:100000052 focus:1
          IC [78b5008e77254012945293897d84f0cf] program:foot frontend:wayland_v2 cap:100000052 focus:0
          IC [e96592a6a02d47f4823d3f9baecc0881] program: frontend:wayland_v2 cap:100000052 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    **Config GUI for qt not found.**

3.  Config GUI for kde:

    **`kcmshell5` not found.**

    **Cannot find a GUI config tool, please install one of `kcm-fcitx5`, or `fcitx5-config-qt`.**

# Frontends setup:
The environment variable checked by this script only shows the environment under current shell. It is still possible that you did not set the environment to the whole graphic desktop session. You may inspect the actual environment variable of a certain process by using `xargs -0 -L1 /proc/$PID/environ` for a certain process that you find not working.

## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS is not set**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    **Cannot find xim_server on root window.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **`fcitx5-qt4-immodule-probing` not found.**

2.  qt5 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt5 built-in Wayland im module if your compositor fully supports text-input protocol used by qt5.**

    **`fcitx5-qt5-immodule-probing` not found.**

3.  qt6 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

    **It is OK to use qt6 built-in Wayland im module if your compositor fully supports text-input protocol used by qt6.**

    **`fcitx5-qt6-immodule-probing` not found.**

4.  Qt IM module files:

    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.freedesktop.Platform.Compat.i386/x86_64/23.08/9713fca68a826b152683399d5355367957af10236ed8c6ecfff2552f7c3ff8d9/files/gtk-3.0/3.0.0/immodules/im-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.freedesktop.Sdk/x86_64/23.08/577729a99bf72b75182a2ded6dab759d18d46a4130dfa7dc0578f468f93014ae/files/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.freedesktop.Sdk/x86_64/22.08/1ddba5e92137b828b8179a21f774a3be0b7bc01e4ffcadb902bf4d0af509679b/files/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.gnome.Platform/x86_64/45/6581b4aef0e8fb497c25ddaadd384bf8dbd7f690aa724f41b3fa565cc8d5681d/files/lib/x86_64-linux-gnu/gtk-4.0/4.0.0/immodules/libim-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.gnome.Platform/x86_64/45/6581b4aef0e8fb497c25ddaadd384bf8dbd7f690aa724f41b3fa565cc8d5681d/files/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.gnome.Platform/x86_64/43/72c5f3d0de590e85995322e18b56731a4b7ed8b47d5fba615dae7ca5c6741930/files/lib/x86_64-linux-gnu/gtk-4.0/4.0.0/immodules/libim-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.gnome.Platform/x86_64/43/72c5f3d0de590e85995322e18b56731a4b7ed8b47d5fba615dae7ca5c6741930/files/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.gnome.Platform/x86_64/44/8633b80ad57b272e38c51a53704f1c096fd1a1bd3da5005241f9beb1d123fd71/files/lib/x86_64-linux-gnu/gtk-4.0/4.0.0/immodules/libim-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.gnome.Platform/x86_64/44/8633b80ad57b272e38c51a53704f1c096fd1a1bd3da5005241f9beb1d123fd71/files/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.gnome.Platform.Compat.i386/x86_64/44/d689024f01e711fc981dda1b06837b0199f7a92ca4b04bbacdcbc4ea6a6c20ec/files/gtk-4.0/4.0.0/immodules/libim-fcitx5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/runtime/org.gnome.Platform.Compat.i386/x86_64/44/d689024f01e711fc981dda1b06837b0199f7a92ca4b04bbacdcbc4ea6a6c20ec/files/gtk-3.0/3.0.0/immodules/im-fcitx5.so`.
    Found fcitx5 im module for qt: `./.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/0b7b6994be103a36917d828c8c511ea5d3d5f3f2c32657400f82d1a03dcda505/files/lib/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `./.local/share/flatpak/app/org.fcitx.Fcitx5/x86_64/stable/8a3703c072235643c65aea1f0f67911d515f2a57d19818005aa1ddfdce2497cc/files/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/app/org.fcitx.Fcitx5/x86_64/stable/8a3703c072235643c65aea1f0f67911d515f2a57d19818005aa1ddfdce2497cc/files/lib/fcitx5/libfcitx4frontend.so`.
    Found fcitx5 im module for qt: `./.local/share/flatpak/app/org.fcitx.Fcitx5/x86_64/stable/8a3703c072235643c65aea1f0f67911d515f2a57d19818005aa1ddfdce2497cc/files/lib/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `./.local/share/flatpak/app/org.fcitx.Fcitx5/x86_64/stable/8a3703c072235643c65aea1f0f67911d515f2a57d19818005aa1ddfdce2497cc/files/lib/plugins/kcms/kcm_fcitx5.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**
    **Cannot find fcitx5 input method module for Qt6.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

    **It is OK to use gtk built-in Wayland im module if your compositor fully supports text-input protocol used by gtk.**

    **`fcitx5-gtk2-immodule-probing` not found.**

    **`fcitx5-gtk3-immodule-probing` not found.**

    **`fcitx5-gtk4-immodule-probing` not found.**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.38` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.38

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0`**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        **Cannot find immodules cache for gtk 2**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.38` at `/usr/lib64/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/x86_64-pc-linux-gnu-gtk-query-immodules-3.0 from gtk+-3.24.38

        **Failed to find fcitx5 in immodule cache at `/usr/lib64/gtk-3.0/3.0.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 3 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 19 enabled addons:

            Anthy 5.1.3
            Classic User Interface 5.1.6
            Clipboard 5.1.6
            DBus 5.1.6
            DBus Frontend 5.1.6
            Emoji 5.1.6
            Fcitx4 Frontend 5.1.6
            IBus Frontend 5.1.6
            Input method selector 5.1.6
            Keyboard 5.1.6
            KDE Input Method Panel 5.1.6
            Status Notifier 5.1.6
            Notification 5.1.6
            Quick Phrase 5.1.6
            Spell 5.1.6
            Unicode 5.1.6
            DBus Virtual Keyboard 5.1.6
            Wayland 5.1.6
            Wayland Input method frontend 5.1.6

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 3 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel
        DBus Virtual Keyboard

## Input Methods:
1.  `/home/sorrow/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name="Group 3"
        # Layout
        Default Layout=jp
        # Default Input Method
        DefaultIM=anthy

        [Groups/0/Items/0]
        # Name
        Name=anthy
        # Layout
        Layout=jp

        [Groups/1]
        # Group Name
        Name="Group 1"
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=keyboard-us

        [Groups/1/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/2]
        # Group Name
        Name="Group 2"
        # Layout
        Default Layout=ru
        # Default Input Method
        DefaultIM=keyboard-ru

        [Groups/2/Items/0]
        # Name
        Name=keyboard-ru
        # Layout
        Layout=

        [GroupOrder]
        0="Group 1"
        1="Group 2"
        2="Group 3"

# Log:
1.  `date`:

        2024-01-14T14:39:49 +10

2.  `/home/sorrow/.config/fcitx5/crash.log`:

    `/home/sorrow/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Additional context**

**Comment by wengxt** [comment]
Yes, that's expected. 

Duplicated of #438

**Comment by eternal-sorrow** [comment]
https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Fcitx_managed_XKB_layout

>As for other desktop, in order to make this "semi" work you'll need to ensure following:
>
>* The XKB layout of the input method group should be the same as the actual xkb layout you configured for the compositor. Fcitx will "think" the layout is the same and bypass the key conversion logic.
>* If you need other layout for text typing (e.g. Arabic), just add them to the Fcitx. As long as the key is forwarded to fcitx, it should work.

This does not work on sway? What "other" desktop is implied here?

**Comment by wengxt** [comment]
@eternal-sorrow  they are two different things.

The thing that I say don't work is for fcitx to changing the sway's keymap.

Under X11, there's a standard mechanism setxkbmap and it will change the display server's layout.
There's no equivalent thing under wayland.
So you can see there's code like this https://github.com/fcitx/fcitx5/blob/06879fe144e7992635026ee28589ce9c7d140412/src/modules/wayland/waylandmodule.cpp#L413 to do it separately to KDE/GNOME.

But, fcitx can also use its own layout conversion internally when your key is going through input method. You should be able to use it to type text, but the layout seen by application are still the one you configured.

For the things in wiki page, you should only use ONE group, and put every thing in the same group.

**Comment by eternal-sorrow** [comment]
>The thing that I say don't work is for fcitx to changing the sway's keymap.

I don't need that. I can change the sway keymap just fine by myself. What I want is for fcitx to change the input method when I change the sway keymap.

**Comment by wengxt** [comment]
That's impossible to implement.
What can fcitx see is only a compiled keymap. Fcitx does not even know "us,ru,jp".
Even if we want to, fcitx still can't mapping input method to layout group.

For that matters, the only way and the current way that fcitx is being implemented, is to let fcitx to be the root of source for layout information.

**Comment by eternal-sorrow** [comment]
Alright, back to anthywl then. Fcitx does not bring me any advantage over it.
