### ISSUE TITLE
Emoji quick phrases mangle text in preview box

### ISSUE THREAD

**Issue by WhyNotHugo** [fcitx/fcitx5#941]
**Describe the bug**

If I trigger quick phrases and type `:heart`, the preview window shows some emoji, but the preview is kind of mangled; the text that I have typed is replaced by the emoji itself, and the rest of the emoji name is displayed.

For example, when typing `:heart`, one of the options is (see below for screenshot):

> 💟_decoration

This simply looks broken. Inserting the emoji works fine and has not issues.

**To Reproduce**
1. `QT_IM_MODULE=fcitx featherpad`
3. Press <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+u
4. Type `:heart` and observe the popup

**Expected behavior**

Ideally, this should display `💟 heart_decoration`, so that the name of the emoji itself is not mangled.

**Desktop (please complete the following information):**
 - Desktop: swaywm
 - Display server type: Wayland
 - The output of fcitx5-diagnose: https://paste.sr.ht/~whynothugo/f518df7b8e7d5b1f1a491491c731e87523e36839

**Additional context**

Screenshot:

![Screenshot from 2024-01-17 at 11_16_39 093131762](https://github.com/fcitx/fcitx5/assets/730811/9567b2d7-81a0-42fe-b768-edeed2caec47)

**Comment by wengxt** [comment]
@WhyNotHugo that's by design and to hint you the remaining code of this item.

**Comment by WhyNotHugo** [comment]
Wouldn't it be clearer to show the entire name instead? E.g.: `💟 heart_decoration`?

**Comment by wengxt** [comment]
fixed with 57f77691a5001e5f42af34eba607b47ffb2557e7
