### ISSUE TITLE
kcm_fcitx5 is not work on plasma 6

### ISSUE THREAD

**Issue by wen-zheng** [fcitx/fcitx5#946]
**Describe the bug**
kcm_fcitx5 is not work on plasma 6

**To Reproduce**
try plasma 6, install fcitx5 and kcm-fcitx5

**Expected behavior**
fcitx can be found on system settings

**Desktop (please complete the following information):**
 - Desktop: kde plasma 6
 - Display server type:Wayland

**Additional context**
none

**Comment by wengxt** [comment]
well, you certainly need to rebuild it against qt6.
