### ISSUE TITLE
最新的arch上fcitx5-git让原本能用的xfce4-terminal --drop-down终端不再能使用fcitx5

### ISSUE THREAD

**Issue by vincentaxhe** [fcitx/fcitx5#950]
我一直用在manjaro上使用fcitx5-git，同时使用xfce4-terminal --drop-down来方便笔记，但今晚更新了最新的fcitx5-git后，就不能在上面的终端中输入了，同为drop-down特色（不真正退出，随时唤出）的终端guake也不能工作了。当downgrade或不使用git版后又正常工作，特来提醒。
不能工作的fcitx-git构建的版本是5.1.7.r21.g7a9121c-1，窗口管理器是Hyprland。

**Comment by wengxt** [comment]
无法在这里重现，工作很正常，请你 bisect 一下

另外你可以贴一下 fcitx5-diagnose

**Comment by wengxt** [comment]
![20240121_09h57m17s_grim](https://github.com/fcitx/fcitx5/assets/259684/4f48b4f0-876f-41be-b1f0-20a69b16bfc6)

**Comment by vincentaxhe** [comment]
我又试了下重装了fcitx5-git，的确可以正常工作，可能是fcitx5-qt4-git fcitx5-qt5-git fcitx5-qt6-git的问题，我之前用fcitx5-git的同时，也用的是qt-git版本而不是fcitx5-qt集合版。
那算是没问题吧。但用qt-git一起应该是有问题的，也许可以再复现下。

**Comment by wengxt** [comment]
@vincentaxhe xfce4是gtk程序，关qt何事呢……

**Comment by vincentaxhe** [comment]
> @vincentaxhe xfce4是gtk程序，关qt何事呢……

首个嫌疑人当然是fcitx5-git，但不是排除了吗，那嫌疑人只能是其它在作案现场的人了。

**Comment by wengxt** [comment]
@vincentaxhe 我的意思是你排除的还是不对…
