### ISSUE TITLE
qt: input window position lags behind one key press

### ISSUE THREAD

**Issue by lilydjwg** [fcitx/fcitx5#955]
**Describe the bug**

**To Reproduce**
1. Open a Qt app (e.g. Telegram, fcitx5-config-qt)
2. Switch fcitx5 to Wubi and type `wqvbk`
3. `你好` is committed, `中` is the preedit string. Cursor is before `中`. The input window aligns before `你好`
4. Type one more key e.g. `b`, the preedit string updates, and finally the input window catches up.

**Expected behavior**
The input window aligns where the cursor is.

**Desktop (please complete the following information):**
 - Desktop: KDE, Wayfire (patched)
 - Display server type: Wayland
 - happens with qt5 or qt6 im module or wayland protocol
[diagnose.txt](https://github.com/fcitx/fcitx5/files/14022309/diagnose.txt)

**Additional context**

**Comment by wengxt** [comment]
not a fcitx bug.
