### ISSUE TITLE
arcolinuxb deepin fcitx5 输入法不能用

### ISSUE THREAD

**Issue by xingwozhonghua126** [fcitx/fcitx5#958]
系统信息:
1.  `uname -a`:                                                       
                                                                      
        Linux csj-vmwarevirtualplatform 6.7.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:14:10 +0000 x86_64 GNU/Linux               
                                                                      
2.  `lsb_release -a`:
                                                                      
        LSB Version:    n/a
        Distributor ID: ArcoLinux                                     
        Description:    ArcoLinux                                     
        Release:        rolling                                       
        Codename:       n/a                                           
                                                                      
3.  `lsb_release -d`:
                                                                      
        Description:    ArcoLinux
                                                                      
4.  `/etc/lsb-release`:
                                                                      
        DISTRIB_ID=ArcoLinux
        DISTRIB_RELEASE="rolling"                                     
        DISTRIB_DESCRIPTION="ArcoLinux"                               
                                                                      
5.  `/etc/os-release`:
                                                                      
        NAME=ArcoLinux
        ID=arcolinux                                                  
        ID_LIKE=arch                                                  
        BUILD_ID=rolling                                              
        ANSI_COLOR="0;36"                                             
        HOME_URL="https://arcolinux.info/"                            
        SUPPORT_URL="https://arcolinuxforum.com/"                     
        BUG_REPORT_URL="https://github.com/arcolinux"                 
        LOGO=arcolinux-hello                                          
                                                                      
6.  桌面环境：
                                                                      
    桌面环境为 `deepin`。

7.  XDG 会话类型：
                                                                      
        XDG_SESSION_TYPE='x11'
                                                                      
8.  Bash 版本：
                                                                      
        BASH_VERSION='5.2.26(1)-release'
                                                                      
# 环境：
1.  DISPLAY:                                                          
                                                                      
        DISPLAY=':0'
                                                                      

        WAYLAND_DISPLAY=''
                                                                      
2.  键盘布局：
                                                                      
    1.  `setxkbmap`:
                                                                      
            xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)" };    
                xkb_types     { include "complete"      };            
                xkb_compat    { include "complete"      };            
                xkb_symbols   { include "pc+cn+inet(evdev)+terminate(ctrl_alt_bksp)"  };                                                    
                xkb_geometry  { include "pc(pc105)"     };            
            };                                                        
                                                                      
    2.  `xprop`:
                                                                      
            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn", "", "terminate:ctrl_alt_bksp"                                                
                                                                      
3.  Locale：
                                                                      
    1.  全部可用 locale：
                                                                      
            C
            C.utf8                                                    
            en_US.utf8                                                
            POSIX                                                     
            zh_CN.utf8                                                
                                                                      
    2.  当前 locale：
                                                                      
            LANG=zh_CN.UTF-8
            LC_CTYPE="zh_CN.UTF-8"                                    
            LC_NUMERIC=zh_CN.UTF-8                                    
            LC_TIME=zh_CN.UTF-8                                       
            LC_COLLATE="zh_CN.UTF-8"                                  
            LC_MONETARY=zh_CN.UTF-8                                   
            LC_MESSAGES="zh_CN.UTF-8"                                 
            LC_PAPER=zh_CN.UTF-8                                      
            LC_NAME=zh_CN.UTF-8                                       
            LC_ADDRESS=zh_CN.UTF-8                                    
            LC_TELEPHONE=zh_CN.UTF-8                                  
            LC_MEASUREMENT=zh_CN.UTF-8                                
            LC_IDENTIFICATION=zh_CN.UTF-8                             
            LC_ALL=                                                   
                                                                      
4.  目录：
                                                                      
    1.  主目录：
                                                                      
            /home/csj
                                                                      
    2.  `${XDG_CONFIG_HOME}`:
                                                                      
        环境变量 `XDG_CONFIG_HOME` 是设定为 `/home/csj/.config` 。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/csj/.config`)。

    3.  Fcitx5 设置目录：
                                                                      
        当前 fcitx5 设置目录是 `~/.config/fcitx5` (`/home/csj/.config/fcitx5`)。                                                            

5.  当前用户：
                                                                      
    脚本作为 csj (1000) 运行。

# Fcitx 状态:
1.  可执行文件：                                                      
                                                                      
    在 `/usr/bin/fcitx5` 找到了 fcitx5。

2.  版本：
                                                                      
    Fcitx 版本: `5.1.7`

3.  进程：
                                                                      
    找到了 1 个 fcitx5 进程：

           3066 fcitx5
                                                                      
4.  `fcitx5-remote`:
                                                                      
    `fcitx5-remote` 工作正常。

5.  DBus 界面：
                                                                      
    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx5` 的所有者是 `:1.123`。

    DBus 名称 `org.fcitx.Fcitx5` 的 PID 所有者是 `3066`。

    来自 dbus 的调试信息：

           Group [x11::0] has 7 InputContext(s)
          IC [7264a95ead904e3dab6ebff8e846ae39] program:dde-dock frontend:dbus cap:16000800072 focus:0                                      
          IC [56cd7cd4274b45d49a35563542038ea5] program:dde-dock frontend:dbus cap:16000800072 focus:0                                      
          IC [bb8cde4ab3b74c22bd255291ac98a4f7] program:dde-dock frontend:dbus cap:16000800072 focus:0                                      
          IC [4a2dd43aec1b425994232bee2b0cec35] program:dde-desktop frontend:dbus cap:16000800072 focus:0                                   
          IC [3bf71eec8a9f4428a1484bbaaeb3d70a] program:dde-dock frontend:dbus cap:16000800072 focus:0                                      
          IC [5b4661d7c44d4410957db42e8eaa396d] program:deepin-terminal frontend:dbus cap:6000800072 focus:1                                
          IC [3a3422b125b6464eb70ddea348835a4d] program:dde-launchpad frontend:dbus cap:16000800072 focus:0                                 
        Input Context without group                                   
                                                                      
# Fcitx 配置界面：
1.  配置工具封装：                                                    
                                                                      
    在 `/usr/bin/fcitx5-configtool` 找到了 fcitx5-configtool。

2.  Qt 的配置界面：
                                                                      
    在 `/usr/bin/fcitx5-config-qt` 找到了 `fcitx5-config-qt`。

3.  KDE 的配置界面：
                                                                      
    **`kcmshell5` 未找到.**
                                                                      
# 前端设置：
此脚本检查的环境变量仅能显示当前命令行的环境。仍有可能您的环境并没有应用于整个桌面。您可以通过使用命令对某个无法正常工作的进程使用命令 `xargs -0 -L1 /proc/$PID/environ` 检查此进程的实际的环境变量。

## Xim:
1.  `${XMODIFIERS}`:                                                  
                                                                      
    环境变量 XMODIFIERS 已经正确地设为了“@im=fcitx”。
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS：
                                                                      
    Xim 服务的名称与环境变量中设置的相同。

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:                                         
                                                                      
    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

    **`fcitx5-qt4-immodule-probing` 未找到.**
                                                                      
2.  qt5 - `${QT_IM_MODULE}`:
                                                                      
    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

    使用 fcitx5-qt5-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx                                            
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext         
                                                                      
3.  qt6 - `${QT_IM_MODULE}`:
                                                                      
    环境变量 QT_IM_MODULE 已经正确地设为了“fcitx”。

    使用 fcitx5-qt6-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        QT_QPA_PLATFORM=xcb
        QT_IM_MODULE=fcitx                                            
        IM_MODULE_CLASSNAME=fcitx::QFcitxPlatformInputContext         
                                                                      
4.  Qt 输入法模块文件：
                                                                      
    找到了 fcitx5 qt6 模块：`/usr/lib/fcitx5/qt6/libfcitx-quickphrase-editor5.so`。                                                         
    找到了 fcitx5 的 qt6 输入法模块：`/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。                  
    找到了 fcitx5 的 qt 输入法模块：`/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`。                    
    找到了未知的 fcitx qt 模块：`/usr/lib/qt/plugins/plasma/kcms/systemsettings/kcm_fcitx5.so`。                                            

    下列错误也许并不准确，因为对路径所对应的 Qt 版本的猜测取决于发行版如何打包 Qt。如果您不使用任何对应版本的 Qt 程序，或者在 Wayland 下使用 Qt 的 text-input 支持，下列错误也不是严重问题。
    **无法找到 Qt4 的 fcitx5 输入法模块。**
                                                                      
## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:                                         
                                                                      
    环境变量 GTK_IM_MODULE 已经正确地设为了“fcitx”。

    使用 fcitx5-gtk2-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        GTK_IM_MODULE=fcitx
                                                                      
    使用 fcitx5-gtk3-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        GTK_IM_MODULE=fcitx
                                                                      
    使用 fcitx5-gtk4-immodule-probing 来检查在当前环境下将被实际使用的输入法模块：

        GTK_IM_MODULE=fcitx
                                                                      
2.  `gtk-query-immodules`:
                                                                      
    1.  gtk 2:
                                                                      
        在 `/usr/bin/gtk-query-immodules-2.0` 找到了 gtk `2.24.33` 的 `gtk-query-immodules`。                                               
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33                                                                 
                                                                      
        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"                                         
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"                                        
                                                                      
    2.  gtk 3:
                                                                      
        在 `/usr/bin/gtk-query-immodules-3.0` 找到了 gtk `3.24.41` 的 `gtk-query-immodules`。                                               
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.41                                                                 
                                                                      
        已找到 gtk `3.24.41` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"                                         
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"                                        
                                                                      
3.  Gtk 输入法模块缓存：
                                                                      
    1.  gtk 2:
                                                                      
        在 `/usr/lib/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存。                                                
        版本行：

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33                                                                 
                                                                      
        已找到 gtk `2.24.33` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"                                         
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"                                        
                                                                      
    2.  gtk 3:
                                                                      
        在 `/usr/lib/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.41` 的输入法模块缓存。                                                 
        版本行：

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.41                                                                 
                                                                      
        已找到 gtk `3.24.41` 的 fcitx5 输入法模块。

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"                                         
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"                                        
                                                                      
4.  Gtk 输入法模块文件：
                                                                      
    1.  gtk 2:
                                                                      
        找到的全部 Gtk 2 输入法模块文件均存在。

    2.  gtk 3:
                                                                      
        找到的全部 Gtk 3 输入法模块文件均存在。

    3.  gtk 4:
                                                                      
        找到的全部 Gtk 4 输入法模块文件均存在。

# 配置:
## Fcitx 插件：                                                       
1.  插件配置文件目录：                                                
                                                                      
    找到了 fcitx5 的插件配置目录：`/usr/share/fcitx5/addon`。

2.  插件列表：
                                                                      
    1.  找到了 27 个已启用的插件：
                                                                      
            Simplified and Traditional Chinese Translation 5.1.3
            Classic User Interface 5.1.7                              
            Clipboard 5.1.7                                           
            Cloud Pinyin 5.1.3                                        
            DBus 5.1.7                                                
            DBus Frontend 5.1.7                                       
            Emoji 5.1.7                                               
            Fcitx4 Frontend 5.1.7                                     
            Full width character 5.1.3                                
            IBus Frontend 5.1.7                                       
            Input method selector 5.1.7                               
            Keyboard 5.1.7                                            
            KDE Input Method Panel 5.1.7                              
            Status Notifier 5.1.7                                     
            Notification 5.1.7                                        
            Pinyin 5.1.3                                              
            Extra Pinyin functionality 5.1.3                          
            Punctuation 5.1.3                                         
            Quick Phrase 5.1.7                                        
            Spell 5.1.7                                               
            Table 5.1.3                                               
            Unicode 5.1.7                                             
            DBus Virtual Keyboard 5.1.7                               
            Wayland 5.1.7                                             
            Wayland Input method frontend 5.1.7                       
            XCB 5.1.7                                                 
            X Input Method Frontend 5.1.7                             
                                                                      
    2.  找到了 0 个被禁用的插件：
                                                                      
3.  插件库: 
                                                                      
    所有插件所需的库都被找到。

4.  用户界面：
                                                                      
    找到了 3 个已启用的用户界面插件：

        Classic User Interface
        KDE Input Method Panel                                        
        DBus Virtual Keyboard                                         
                                                                      
## 输入法：
1.  `/home/csj/.config/fcitx5/profile`:                               
                                                                      
        [Groups/0]
        # Group Name                                                  
        Name="分组 2"                                                 
        # Layout                                                      
        Default Layout=us                                             
        # Default Input Method                                        
        DefaultIM=pinyin                                              
                                                                      
        [Groups/0/Items/0]                                            
        # Name                                                        
        Name=keyboard-us                                              
        # Layout                                                      
        Layout=                                                       
                                                                      
        [Groups/0/Items/1]                                            
        # Name                                                        
        Name=pinyin                                                   
        # Layout                                                      
        Layout=                                                       
                                                                      
        [Groups/1]                                                    
        # Group Name                                                  
        Name="分组 1"                                                 
        # Layout                                                      
        Default Layout=cn                                             
        # Default Input Method                                        
        DefaultIM=pinyin                                              
                                                                      
        [Groups/1/Items/0]                                            
        # Name                                                        
        Name=keyboard-cn                                              
        # Layout                                                      
        Layout=                                                       
                                                                      
        [Groups/1/Items/1]                                            
        # Name                                                        
        Name=pinyin                                                   
        # Layout                                                      
        Layout=                                                       
                                                                      
        [GroupOrder]                                                  
        0="分组 1"                                                    
        1="分组 2"                                                    
                                                                      
# 日志：
1.  `date`:                                                           
                                                                      
        2024年 01月 27日 星期六 20:34:16 CST
                                                                      
2.  `/home/csj/.config/fcitx5/crash.log`:
                                                                      
    `/home/csj/.config/fcitx5/crash.log` 未找到.

**警告：fcitx5-diagnose 的输出可能包含敏感信息，包括发行版名称，内核版本，正在运行的程序名称等。**                                          
                                                                      
**尽管这些信息对于开发者诊断问题有帮助，请在公开发送到在线网站前检查并且根据需要移除的对应信息。**                                          

没感觉哪里有问题，但是无法输入中文

**Comment by wengxt** [comment]
看起来没什么问题，怎么不能用了？

你可以 Ctrl + ; 看看有没有弹出fcitx 的剪贴板功能

**Comment by xingwozhonghua126** [comment]
> 看起来没什么问题，怎么不能用了？
> 
> 你可以 Ctrl + ; 看看有没有弹出fcitx 的剪贴板功能

很奇怪剪切板，能显示出来，但是无法切换到中文，输入汉字，不管是shift切换。还是鼠标点击都不行。

**Comment by xingwozhonghua126** [comment]
火狐浏览器能输入，但是系统自带的深度文本编辑器不能输入中文。

**Comment by mokapsing** [comment]
> 火狐浏览器能输入，但是系统自带的深度文本编辑器不能输入中文。

深度文本编辑器应该支持f5，不支持ibus

**Comment by wengxt** [comment]
![图片](https://github.com/fcitx/fcitx5/assets/259684/884f703d-a561-4485-9592-59d9f674da8f)

设置好 im module 的话应该都可以用吧
