### ISSUE TITLE
英文输入模式下，在google、github的搜索栏中持续按住同一个键会很慢

### ISSUE THREAD

**Issue by ukari** [fcitx/fcitx5#96]
比如在google搜索框中持续按住一个'a'键，大概需要10多秒才会出现第2个'a'。在github的issue界面，按键到出现第二个'a'大概有3秒的反应时间，并且持续按键的时候fcitx5的cpu占用率很低没有明显变化。

关掉fcitx5后，输入表现正常。

系统： Ubuntu 20.04.1 LTS
内核： Linux 5.4.0-42-generic
fcitx版本： 4.99.0
浏览器： Mozilla Firefox 79.0
桌面：Airblader/i3 4.18.2-224-gdaac56b0 (2020-07-26, branch "gaps-next")

**Comment by wengxt** [comment]
环境变量设置成 fcitx 的话就可以。否则享受不到 firefox 对 fcitx 的特别设置。

**Comment by ukari** [comment]
感谢回复，不过我已经设置了.xprofile里的环境变量但是问题还在

``` shell
$ echo $INPUT_METHOD 
fcitx5
$ echo $GTK_IM_MODULE 
fcitx5
$ echo $QT_IM_MODULE 
fcitx5
$ echo $XMODIFIERS 
@im=fcitx5
$ cat ~/.xprofile 
export INPUT_METHOD=fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
```

另外做这个持续按键的实验后发现firefox有几率会crash掉，在其他的程序里好像也没这个问题，在firefox的地址栏里也没这个问题，只有firefox网页里的文本编辑有这个问题。

大概原因是在firefox那边，可能是firefox本身的渲染或者输入的实现有问题，错误报告已经提交给火狐官方，希望他们能重视吧

**Comment by wengxt** [comment]
我的意思是，设置成 fcitx 而不是 fcitx5

**Comment by ukari** [comment]
看错了，试了一下可行，感谢！
