### ISSUE TITLE
当焦点在 Chrome、Electron 时重启 fcitx5，会导致 Chrome、Electron 不能打开任何菜单

### ISSUE THREAD

**Issue by antonchen** [fcitx/fcitx5#960]
环境比较复杂，我目前不能确定是哪个的问题。
目前同样的环境使用 ibus-rime 没有问题。实际上我准备从 ibus-rime 换到 fcitx5-rime，使用了一会出现了这个问题。

表现出的情况是：Chrome、Electron 中的菜单会因为 fcitx5-rime 或 fcitx5 影响导致打不开（一闪而过），包括不限于菜单栏，Chrome 书签栏，右键菜单。
不能判定触发条件，正常使用十来分钟就会出问题。切换 bspwm 桌面或打开新窗口后，出问题的程序会恢复正常。退出 fcitx5 也会恢复。

我的环境：
Debian testing
bspwm + picom
fcitx5 5.1.7-1
fcitx5-rime 5.1.4-1

Xorg -version
```
X.Org X Server 1.21.1.10
X Protocol Version 11, Revision 0
Current Operating System: Linux AntonPC.local 6.2.12-x64v3-xanmod1 #0~20230420.98e6d2d9 SMP PREEMPT_DYNAMIC Thu Apr 20 23:08:51 UTC x86_64
Kernel command line: root=LABEL=Root rootflags=subvol=@ rw hibernate=nocompress libata.noacpi=1 quiet initrd=\@\initrd.img
xorg-server 2:21.1.10-1 (https://www.debian.org/support) 
Current version of pixman: 0.42.2
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

Rime 配置：https://github.com/iDvel/rime-ice

我本机受影响的程序是 Google Chrome、VSCode

**Comment by wengxt** [comment]
试试 master branch

**Comment by hantengc** [comment]
@antonchen 这个一闪而过的问题我在我们系统上遇到过

**Comment by antonchen** [comment]
> 试试 master branch

测试了，已修复。
