### ISSUE TITLE
Let upstream "Qt Base" include fcitx-qt, so Qt AppImage users won't struggle with IME | 让上游Qt的"Qt Base"接受包含fcitx-qt，以使Qt AppImage用户能用输入法

### ISSUE THREAD

**Issue by garywill** [fcitx/fcitx5#961]
IME users need a kind of Qt plugin "platform input context plugin" to use IME on Qt apps.
As we all know, many fcitx users usually struggle with AppImage-packed Qt apps.

Many Qt app developers release their `.AppImage` with ibus support (`plugins/platforminputcontexts/libibusplatforminputcontextplugin.so`). ibus and fcitx are both CJK IME. fcitx is also widely used so should not be excluded from app developers' support list.

To find out how those many `.AppImage` packs include ibus, I searched for their packing config and build log and found something like:

```python
runtimeDependencies["libs/qt5/qtbase"]
runtimeDependencies["libs/qt6/qtbase"]
```

```
Updating rpath for /builds/....../linux-64-gcc/build/libs/qt5/qtbase/image-RelWithDebInfo-kde_5.15/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so: {'/builds/sysadmin/ci-management/linux-64-gcc/lib', '$ORIGIN/../../lib'} -> {'/builds/....../linux-64-gcc/lib', '$ORIGIN/../../lib'}
Updating rpath for /builds/....../linux-64-gcc/build/libs/qt5/qtbase/image-RelWithDebInfo-kde_5.15/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so: {'/builds/sysadmin/ci-management/linux-64-gcc/lib', '$ORIGIN/../../lib'} -> {'/builds/....../linux-64-gcc/lib', '$ORIGIN/../../lib'}
```

So the reason is: Qt Base already includes ibus support, but no fcitx: https://github.com/qt/qtbase/tree/dev/src/plugins/platforminputcontexts

And we can see KDE use image `libs/qt5/qtbase` to do AppImage packs: https://github.com/search?q=org%3AKDE+libs%2Fqt5%2Fqtbase+language%3APython&type=code&l=Python&p=2

Besides KDE, other Qt Apps use `libs/qt5/qtbase` too: https://github.com/search?q=libs%2Fqt5%2Fqtbase&type=code

I'm a user. I think it's time for fcitx team to talk with Qt team, and let [Qt Base](https://github.com/qt/qtbase) include fcitx-qt (`plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`), just one file < 200 KiB

-------------------

IME用户需要一种Qt插件“平台输入上下文插件”才能在Qt应用程序上使用IME。

众所周知，许多 fcitx 用户通常会为打包 AppImage 的 Qt 应用程序而苦苦挣扎。

许多Qt应用程序开发人员发布了他们的 .AppImage ibus支持（ `plugins/platforminputcontexts/libibusplatforminputcontextplugin.so` ）。ibus 和 fcitx 都是 CJK 输入法。FCITX 也被广泛使用，因此不应被排除在应用程序开发人员的支持列表中。

为了了解这些 .AppImage 包是如何包含 ibus 的，我搜索了他们的打包配置和构建日志，并找到了如下内容：
```python
runtimeDependencies["libs/qt5/qtbase"]
runtimeDependencies["libs/qt6/qtbase"]
```

```
Updating rpath for /builds/....../linux-64-gcc/build/libs/qt5/qtbase/image-RelWithDebInfo-kde_5.15/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so: {'/builds/sysadmin/ci-management/linux-64-gcc/lib', '$ORIGIN/../../lib'} -> {'/builds/....../linux-64-gcc/lib', '$ORIGIN/../../lib'}
Updating rpath for /builds/....../linux-64-gcc/build/libs/qt5/qtbase/image-RelWithDebInfo-kde_5.15/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so: {'/builds/sysadmin/ci-management/linux-64-gcc/lib', '$ORIGIN/../../lib'} -> {'/builds/....../linux-64-gcc/lib', '$ORIGIN/../../lib'}
```

所以原因是：Qt Base已经包含ibus支持，但没有fcitx：https://github.com/qt/qtbase/tree/dev/src/plugins/platforminputcontexts

我们可以看到 KDE 使用镜像 `libs/qt5/qtbase` 来做 AppImage 包： https://github.com/search?q=org%3AKDE+libs%2Fqt5%2Fqtbase+language%3APython&type=code&l=Python&p=2

除了KDE，其他Qt应用程序也使用 `libs/qt5/qtbase` ： https://github.com/search?q=libs%2Fqt5%2Fqtbase&type=code

我是个用户，我认为fcitx团队该出面和Qt团队谈，让[Qt Base](https://github.com/qt/qtbase)包含fcitx-qt（ `plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so` ），只需一个文件<200 KiB

**Comment by wengxt** [comment]
No.

First of all, please use flatpak, not appimage. AppImage is a old-era solution that could easily goes wrong.  If you use flatpat or even snap, the fcitx plugin would be just included in the runtime. Appimage itself could even not package ibus or do wrong packaging that we have seen it from time to time.
Secondly, with fcitx5, just use QT_IM_MODULE=ibus would be able to use fcitx5 with those app image that bundles ibus plugin.
Thirdly, put code upstream would make it hard to pick up any new API added in fcitx. I prefer to maintain it by fcitx, not by qt.
