### ISSUE TITLE
`fcitx::InputBuffer::charAt(1)` returns bogus values

### ISSUE THREAD

**Issue by yukijoou** [fcitx/fcitx5#965]
**Describe the bug**

When developing a plugin, `fcitx::InputBuffer::charAt(1)` always seems to return 2^32 - 2, for some odd reason

**To Reproduce**

```cpp
fcitx::InputBuffer test_buf{{fcitx::InputBufferOption::NoOption}};
test_buf.type('a');
test_buf.type('a');
FCITX_INFO() << "Value: " << test_buf.charAt(1) << " → " << fcitx::utf8::UCS4ToUTF8(test_buf.charAt(1)) << " vs. actual: " << test_buf.userInput()[1];
```

This snippet currently logs:

```
Value: 4294967294 → ������ vs. actual: a
```

**Expected behavior**

This should log

```
Value: 97 → a vs. actual: a
```

**Desktop (please complete the following information):**
 - Desktop: GNOME
 - Display server type: Wayland
 - The output of fcitx5-diagnose: probably irrelevant, but I can provide it if needs be :)

**Comment by wengxt** [comment]
charAt is actually buggy on non ascii.. I guess the reason is no one actually use it.. or, the one from libime::InputBuffer's operator[] is returning string view which is easier to use.

If you don't really need non-ascii buffer, you may set Ascii option to it.

**Comment by yukijoou** [comment]
ah, got it! maybe a deprecation warning should be added to it then... i'm not at my computer to write a patch for it right now though

also, it seems like it's also broken with ascii too, since my test code only types 2 ascii `a`s

**Comment by wengxt** [comment]
@yukijoou I mean the constructor has a ascii only mode flag
