### ISSUE TITLE
Navicat中， 中文输入法不可用

### ISSUE THREAD

**Issue by Ray2310** [fcitx/fcitx5#968]
**Describe the bug**
系统： Ubuntu22.04
软件： Navicat16

**To Reproduce**
1. Open ... app
2. Try to type ...
3. 使用Fcitx5，切换置中文
4. 输入内容，显示内容还是英文

**Additional context**
![image](https://github.com/fcitx/fcitx5/assets/109897266/f71a98d6-fcaf-496a-9f1a-a9e33478c78f)

**Comment by bczhc** [comment]
看起来像是个QT应用，其他QT应用能用吗？检查一下输入法集成
```bash
export GTK_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE=fcitx
```

一开始我还以为会是这个QT程序没集成fcitx5模块，像这个问题：https://github.com/fcitx/fcitx/issues/372

但我装了AUR [navicat16-premium-en](https://aur.archlinux.org/packages/navicat16-premium-en) 包，fcitx5是直接可用的。

![image](https://github.com/fcitx/fcitx5/assets/49330580/542dff42-4a55-49fc-87c2-b23bdd5aa24d)

**Comment by Ray2310** [comment]
> 看起来像是个QT应用，其他QT应用能用吗？检查一下输入法集成
> 
> ```shell
> export GTK_IM_MODULE=fcitx
> export XMODIFIERS="@im=fcitx"
> export QT_IM_MODULE=fcitx
> ```
> 
> 一开始我还以为会是这个QT程序没集成fcitx5模块，像这个问题：[fcitx/fcitx#372](https://github.com/fcitx/fcitx/issues/372)
> 
> 但我装了AUR [navicat16-premium-en](https://aur.archlinux.org/packages/navicat16-premium-en) 包，fcitx5是直接可用的。
> 
> ![image](https://private-user-images.githubusercontent.com/49330580/304762870-542dff42-4a55-49fc-87c2-b23bdd5aa24d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODI5MzAsIm5iZiI6MTcwNzk4MjYzMCwicGF0aCI6Ii80OTMzMDU4MC8zMDQ3NjI4NzAtNTQyZGZmNDItNGE1NS00OWZjLTg3YzItYjIzYmRkNWFhMjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA3MzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOTQ4NjU4YTk2ZTExZmYzYzI0NWNiMjk1MGE3MTQ3MTY5ZDBjODNkZGE0ZTEzNWM0OWNlZjVlZTRjNDM1NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tk3qGAtvcz69XxXe4HjBpdWcZOq2DBfNfbumeiCb9oM)
> 
> ArchLinux `6.7.0-rc7-modified-g861deac3b092-dirty`; Fcitx5 5.1.7


你用的是Arch系统吗？ 有没有可能是系统软件兼容性的问题呢？
> 但我装了AUR [navicat16-premium-en](https://aur.archlinux.org/packages/navicat16-premium-en) 包

你装的是Arch的软件包吧

**Comment by bczhc** [comment]
是啊。所以就是列一下在我系统上的情况，即没有问题。那个AUR包，就是个appimage，如果在Ubuntu上也可运行的话你可以试一下 [navicat16-premium-en.AppImage](https://github.com/nninjia/navicat16-premium-en-aur/releases/download/v16.0.11/navicat16-premium-en.AppImage)

**Comment by Ray2310** [comment]
> 是啊。所以就是列一下在我系统上的情况，即没有问题。那个AUR包，就是个appimage，如果在Ubuntu上也可运行的话你可以试一下 [navicat16-premium-en.AppImage](https://github.com/nninjia/navicat16-premium-en-aur/releases/download/v16.0.11/navicat16-premium-en.AppImage)


sorry, 还是一样的。 并没有任何变化。

**Comment by wengxt** [comment]
`QT_DEBUG_PLUGINS=1 QT_IM_MODULE=fcitx ./navicat16-premium-en.AppImage` 有什么输出

**Comment by wengxt** [comment]
测试了虚拟机里 ubuntu 22.04 上 appimage  也是可以输入的

请提供相关信息才能帮你看过
