### ISSUE TITLE
Support automatic commit when only one candidate in QuickPhrase?

### ISSUE THREAD

**Issue by eternaleye** [fcitx/fcitx5#97]
I use QuickPhrase for inputting LaTeX escapes while programming, and the need to explicitly commit gets old quite quickly in Unicode-heavy languages, such as theorem provers. Would it be possible to add an option to QuickPhrase to immediately commit when there is only one candidate?

**Comment by wengxt** [comment]
I don't think it's reasonable to support it in quickphrase.

However, you may consider to use ~/.XCompose to do some customization. You can set Compose key to sth like caps lock in xkb option. E.g. Caps lock = c will produce €
FYI: https://wiki.debian.org/XCompose (ignore the xmodmap part, use xkb option to set the location of compose key instead).

Another solution that might work for you is to create a table and use it with the table engine in fcitx5-chinese-addons, that engine has ability to do auto commit.

**Comment by eternaleye** [comment]
I think you misunderstood my intent - I _do_ use a key to begin QuickPhrase, and in fact use it _in place of_ XCompose. However, what I'd like to avoid is needing to hit space to _terminate_ a symbol.

If I type `CapsLock, >, >, Space` then I get `»` - but I'd like to avoid the `Space`.
