### ISSUE TITLE
Popup candidate window covers the input area (Wayland `text-input-*`)

### ISSUE THREAD

**Issue by HardGraphite** [fcitx/fcitx5#971]
**Describe the bug**
The popup candidate window covers the input line when the `text-input-*` protocol is being used in Wayland. The upper left corner of the popup window is placed exactly where the text will be entered.

**To Reproduce**
1. Unset `GTK_IM_MODULE`, `QT_IM_MODULE`, and `XMODIFIERS`.
2. Start a GUI program and type.

I have tried server programs. Most of them like Firefox (GTK) and Alacritty (winit) have the problem; but Neovide (winit) works well.

Alacritty:

![1](https://github.com/fcitx/fcitx5/assets/64914256/ab63f2d7-69f1-4096-b014-7126004dad42)

Firefox:

![2](https://github.com/fcitx/fcitx5/assets/64914256/e5113367-fe0e-4c5b-a5fb-a9735e31beee)

**Expected behavior**
The popup window should be under the input line.

Neovide (expected behavior):

![3](https://github.com/fcitx/fcitx5/assets/64914256/bad06e7b-8a08-45ea-82bf-b6a51468ede7)

**Desktop (please complete the following information):**
 - Desktop: Niri, a Wayland compositor
 - Display server type: Wayland
 - The output of fcitx5-diagnose: Nothing special, just complaining about the environment variables not set

**Additional context**
When using Firefox, the popup window always appears at the position of the previous input word. I don't know whether the problem is related to this issue.

**Comment by CoelacanthusHex** [comment]
When use text-input protocols, popup is placed by compositor, so it should be a bug of your wayland compositor.

**Comment by kchibisov** [comment]
yeah, that's compositor bug.
