### ISSUE TITLE
[feature request] allow prohibiting connections to X

### ISSUE THREAD

**Issue by HardGraphite** [fcitx/fcitx5#973]
I'm trying to migrate to Wayland, and I find that most of the programs I use can run natively in Wayland. However, when Fictx starts, it will try to connect to the X server, which then starts the XWayland. This is not what I want.

Is it OK to add a switch to disable the X? It can be a command-line argument or an environment variable to avoid connections to X server, so that resources can be saved if XWayland is never needed.

**Comment by wengxt** [comment]
@HardGraphite https://groups.google.com/g/fcitx-announce/c/K7W1ATH2Viw

**Comment by wengxt** [comment]
In short:
If fcitx will ignore DISPLAY if you run it with this
```
fcitx5 -o xcb=nodefault
```

and, if your compositor support /etc/xdg/Xwayland-session.d/, Xwayland will be automatically connected when Xwayland starts with the script under it /etc/xdg/Xwayland-session.d/20-fcitx-x11.

If your compositor doesn't support this directory, you will need to find a way to execute `fcitx5-remote -x` to open the X display specified by DISPLAY.
