### ISSUE TITLE
wayland input method v2: modifier lost when IM context loses focus

### ISSUE THREAD

**Issue by lilydjwg** [fcitx/fcitx5#977]
**Describe the bug**
Firefox Alt+number switching stuck when text focus is lost.

**To Reproduce**
1. Open Firefox
2. Open one tab and ensure it has no text focus (let's say it's the first tab)
3. Open another tab, focus the urlbar (let's say it's the second tab)
4. Press down `Alt`, and press and release `1`. The first tab should now be focused
5. Press and release `2`. The second tab is not focused.

**Expected behavior**
In step 5 the second tab should be focused.

**Desktop (please complete the following information):**
 - Desktop: Wayfire git
 - Display server type: Wayland

**Additional context**
This is due to keyboard modifier is cleared by https://github.com/fcitx/fcitx5/blob/495b8ed9906d4d17911a868d1b765bd07db2a592/src/frontend/waylandim/waylandimserverv2.cpp#L165.

**Comment by wengxt** [comment]
@lilydjwg does it help if I destroy vk everytime?

**Comment by lilydjwg** [comment]
How? Can you give me a patch to try?

**Comment by wengxt** [comment]
@lilydjwg try this commit https://github.com/fcitx/fcitx5/compare/495b8ed9906d...b2924bd36168

**Comment by lilydjwg** [comment]
Not good. It solves the firefox issue, but has other issues:

1. a lot of Xwayland xkbcomp warnings due to frequent switching of keyboards (this happens for sway too)
2. the issue solved by f8ab6e377997f437f9f641e58b53fb33f9973011 and 495b8ed9906d4d17911a868d1b765bd07db2a592 comes back

**Comment by wengxt** [comment]
@lilydjwg for 1, I don’t care. it’s compositor task to try to avoid send the same key map. 

for 2, I don’t get why it comes back. Feels like a compositor bug.

**Comment by wengxt** [comment]
@wengxt I’m not sure if I could just avoid sending keymap at all, if so, I’m happy to do that.

**Comment by wengxt** [comment]
@wengxt Apparently, the protocol doesn't allow me to do that 
wp_virtual_keyboard_v1@21: error 0: Cannot send a keypress before defining a keymap

**Comment by lilydjwg** [comment]
> Feels like a compositor bug.

Unfortunately it's a feature. wlroots will synthesize those release events.

> I’m not sure if I could just avoid sending keymap at all.

It doesn't seem so. It doesn't seem very OK to skip a lot of initialization code to avoid the keymap, repeat_info and modifiers events.

**Comment by lilydjwg** [comment]
No, it's not only the keyboard init code. Client setting keymap will trigger it too. So it's unavoidable.

Also the compositor can't get notified before wlroots synthesizes those release events so I can't block them in advance.

**Comment by wengxt** [comment]
@lilydjwg here's the thing, if you treat virtual keyboard a temporarily "overlay" on the real keyboard, when it's removed, the original keyboard status should be exposed.

**Comment by lilydjwg** [comment]
Yes, just like input method v1. Except that it's unavailable in wlroots. It needs to be done in wlroots. If I were to do it, I might have a better experience to just implement input method v1 instead.

**Comment by wengxt** [comment]
@wengxt it's ok that wlroots generate key release, but the point is, the modifier mask shouldn't be updated.

So imagine this:
you have two phyiscal keyboards.
You press alt on both keyboards.
You release alt one of the keyboard.
Now, should the xkb state with alt pressed, or not?

**Comment by lilydjwg** [comment]
wlroots doesn't generate modifier events. Modifier is OK now, but the generated key releases push things back to various checks / hacks I need to have in wayfire.

**Comment by wengxt** [comment]
@lilydjwg generate key release makes sense. Imagine you have a physical keyboard plugged. now, you press a key, and keep holding the key when unplug it.

Then compositor would have to release whatever key  you pressed, otherwise, it will be just pressed forever.

**Comment by lilydjwg** [comment]
That's why I say it's a feature. I've spent too much time on it but made little progress. I'd have better experience to implement input method v1. Just see how well kwin has done. It was a wrong invest to v2.

**Comment by wengxt** [comment]
@wengxt you know.. because virtual keyboard is modeled the same way like an another real physical keyboard in wlroots, you'd expect those things happens.
