### ISSUE TITLE
打字过快会导致漏掉某些字母

### ISSUE THREAD

**Issue by Asthestarsfalll** [fcitx/fcitx5#979]
**Describe the bug**

如题，打字过快会导致漏掉某些特定的字母。使用hyprland之后出现的问题，不能稳定复现，因此不好录制视频。举个例子，比如要输入 计算机 这三个汉字，会有概率漏掉a，这时候选框上就只剩 jisunji，如下图

![image](https://github.com/fcitx/fcitx5/assets/72954905/ea41408a-1197-4dc5-bdf0-d968bf0e6b5d)

**Desktop (please complete the following information):**
 - Display server type: Wayland

**Comment by CoelacanthusHex** [comment]
所有应用吗？理论上这个应该只发生于使用 XIM 的 Chromium based 应用。

**Comment by Asthestarsfalll** [comment]
> 所有应用吗？理论上这个应该只发生于使用 XIM 的 Chromium based 应用。

目前只在chrome和obsidian上发现这个问题

**Comment by CoelacanthusHex** [comment]
那让他不要用 XIM 就好了，chrome 可以 --gtk-version=4，obsidian 的话……hyprland 支持 text-input-v1 吗？

**Comment by wengxt** [comment]
GTK_IM_MODULE=fcitx 启动 chrome 或者 electron

**Comment by heheda123123** [comment]
kde6 wayland chrome ，上面的方法无效
