### ISSUE TITLE
是否支持热重载码表？

### ISSUE THREAD

**Issue by UM-Li** [fcitx/fcitx5#980]
请问 Fcitx5 有没有运行时重载码表的命令？

背景是使用[官方仓库](https://github.com/fcitx/fcitx5-table-extra)的郑码码表，Ctrl+8 自组词功能似乎不能正常工作（用五笔试了下，Ctrl+8 能自动生成新词的编码，但郑码会提示 “没有对应的码” #969 也不能添词，抱歉真的没搞懂怎么用）。

至今（X 环境）的处理是把词语写进总码表，生成新的 `zhengma.main.dict`，放进 `~/.local/share/fcitx5/table` 并重启 Fcitx。刚换到 Plasma 6 + Wayland，Fcitx 要求选择虚拟键盘后由 KWin 调出自己，手动在命令行退出重启也调不出输入法；这样如果想重启 Fcitx 是不是要一并重启 KWin 了…？

能热重载码表则不用重启 Fcitx；尝试了 `fcitx5-remote -r` 和 `fcitx5 -d -r`，两个命令都没有重载码表。

- **系统**：Arch Linux
- **Plasma**：v6.0.1（Wayland）
- **Fcitx**：v5.1.8
- **libime**：v1.1.6

**Comment by wengxt** [comment]
@UM-Li 在 kwin 下重启非常简单，只需要展开托盘，点两下那个输入法图标就行了

**Comment by wengxt** [comment]
@UM-Li 郑码的构词码好像被意外删掉了…我得研究一下…

**Comment by UM-Li** [comment]
> @UM-Li 在 kwin 下重启非常简单，只需要展开托盘，点两下那个输入法图标就行了

解了燃眉之急，感谢！没想到这么简单 :joy:

**Comment by wengxt** [comment]
修复郑码的问题 https://github.com/fcitx/fcitx5-table-extra/commit/75c3605dff279c9fedb49ea7f35a9054f451d594

**Comment by wengxt** [comment]
最后，重载码表的命令

```
qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.SetConfig 'fcitx://config/addon/table/reloaddict' ''
```
