### ISSUE TITLE
Fcitx5 flatpak Rime 无法使用

### ISSUE THREAD

**Issue by Redv123** [fcitx/fcitx5#981]
**Describe the bug**
尝试输入的时候提示 Rime not available. 配置那里一片空白，无法更改 Rime 的设置。Mozc 可以正常输入文字，只有 Rime 出现了问题。原本是可以输入的，不过刚刚 flatpak 更新 fcitx5 后就无法使用了。
![Bug](https://github.com/fcitx/fcitx5/assets/161664341/f6a15243-f6f6-4501-9ba9-835eb49a4e58)

**Desktop (please complete the following information):**
 - Desktop: KDE
 - Display server type: Wayland

**Comment by wengxt** [comment]
@Redv123 flatpak 它这个rebuild只能一个个来…没有很好的staging一起发布的办法，你要是想马上就能用可以装fcitx5-unstable里那一整套，暂时先不用flathub里那个

等我都更新好应该就可以了

**Comment by Redv123** [comment]
原来如此，那我还是等等更新好了。

**Comment by wengxt** [comment]
已经更新了
