### ISSUE TITLE
Firefox displays wrong popup position on Wayland

### ISSUE THREAD

**Issue by musjj** [fcitx/fcitx5#983]
**Describe the bug**
The popup indicator when you switch input methods is sometimes displayed on the wrong position on Firefox (Wayland).

**To Reproduce**
1. Open a new tab in Firefox and go to https://www.google.com
2. Press `Ctrl+F`, followed by `Esc`. Google's search box should be focused now
3. Press the shortcut you set for `Trigger Input Method`

The popup will appear in the location where the last focused input box was. In this case it was the `Find in page...` input box, at the bottom left.

You can also reproduce it simply by switching between any two input boxes. When you switch input methods, the popup indicator will always be displayed over the last focused input box.

**Expected behavior**
The popup should appear where the currently focused input box is.

**Desktop (please complete the following information):**
 - Desktop: Hyprland
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

**Additional context**

**Comment by wengxt** [comment]
popup position is moved by compositor. I heard it's a firefox / gtk bug.

https://gitlab.gnome.org/GNOME/gtk/-/issues/6293

https://bugzilla.mozilla.org/show_bug.cgi?id=1865779
