### ISSUE TITLE
CLI support for EnumerateForwardKeys

### ISSUE THREAD

**Issue by Martin-Lndbl** [fcitx/fcitx5#988]
Currently `fcitx5-remote` has the option to set the group with the `-g` option followed by the group name. I think it would be useful to add an option that behaves identical to the `EnumerateForwardKeys` set in Hotkeys, to change to the next input group.
By example by making the `<group>` parameter optional and changing to the next one if omitted.

**Comment by wengxt** [comment]
The group switching logic is alt-tab.

If you have more than 2 groups, having such command can only allow you to switch between first two groups.

Can you explain your use case instead?

**Comment by Martin-Lndbl** [comment]
For various reasons, I want to handle all my hotkeys via window-manager (Hyprland). For that I need a cli option to "toggle" my groups. I only need to be able to switch between `mozc` and `default keyboard`.

**Comment by wengxt** [comment]
Maybe, you want to do some scripting instead?

fcitx5-remote -q can query the current group name.

**Comment by Martin-Lndbl** [comment]
That would be elegant, if I could write a [nix home-manager](https://github.com/nix-community/home-manager) module, so adding a new group could be done in one place. This would create a symlink at `$XDG_CONFIG_HOME/fcitx5/profile`. However, the file gets overwritten from `fcitx5` on startup even if the configuration is unchanged.
Is there a way to prevent fcitx5 from overwriting this file other than changing its permissions?
If not, I will just live with the less elegant solution.

**Comment by wengxt** [comment]
Symlink the whole fcitx5 directory instead, maybe?

When fcitx write data, it always uses write to temp and then rename. That's why the symlink won't work as expected.

**Comment by Martin-Lndbl** [comment]
After an initial crash after symlinking the whole folder, it now works as expected. Thanks!
