### ISSUE TITLE
KDE6 Wayland 下候选框字体渲染问题

### ISSUE THREAD

**Issue by heddxh** [fcitx/fcitx5#992]
**Describe the bug**

![图片](https://github.com/fcitx/fcitx5/assets/63106571/98f34412-8b8b-41ff-9537-d634e388147b)

目前我只发现了“拔”这个字渲染有问题

**To Reproduce**
1. 任何地方
2. 输入ba

**Expected behavior**

正常的字体渲染

**Desktop (please complete the following information):**
 - Desktop: KDE6 
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

http://fars.ee/952d

**Additional context**
在KDE5 X11下是没有问题的。
系统没有缩放（全局100%）。

**Comment by wengxt** [comment]
和fcitx无关

**Comment by heddxh** [comment]
所以这是一个KDE/QT的问题吗？我在桌面的其他地方没有遇到这个问题哎

**Comment by wengxt** [comment]
@heddxh fcitx 绘制也就是调用别的库，渲染有什么问题 bug 也不是在 fcitx 里面
