### ISSUE TITLE
Fcitx在Neovim插入模式下使用时，文本颜色和背景颜色相同

### ISSUE THREAD

**Issue by la1den** [fcitx/fcitx5#995]
**Describe the bug**

fcitx在插入模式下，文本会和背景几乎一个颜色。
![屏幕截图_20240323_135517](https://github.com/fcitx/fcitx5/assets/55609004/b26bd3fc-a341-45af-b532-61a0c4366cbb)

但是在普通模式却是正常的。
![屏幕截图_20240323_135452](https://github.com/fcitx/fcitx5/assets/55609004/dfd35cc6-6264-4890-ba18-ba8f0bfcf654)

**To Reproduce**
1. 在Konsole中将主题设置为深色。
2. 打开nvim并使用一款浅色主题。
```
:colorscheme morning
```
3.进入插入模式，开启输入法进行输入。

**Expected behavior**

插入模式的表现应该和普通模式相同。

**Desktop (please complete the following information):**
 - Desktop: KDE6
 - Display server type: X11
 - The output of fcitx5-diagnose if possible.

**Additional context**

**Comment by la1den** [comment]
尝试了在Fish、kitty、alacritty中运行，Fish和Konsole同样的问题，但是kitty、alacritty表现是正常的

**Comment by wengxt** [comment]
请汇报给对应的终端。fcitx 控制不了自定义 widget 绘制 preedit 使用的颜色和方式

**Comment by wengxt** [comment]
你可以 Ctrl+Alt+P 快速禁用预编辑

**Comment by wengxt** [comment]
例如，konsole 采用的是当前终端颜色来绘制预编辑文本。

https://github.com/KDE/konsole/blob/29eb4f5cc71c146eeb220bb69322bb1159f2e372/src/terminalDisplay/TerminalPainter.cpp#L755

另外，既然你喜欢浅色，你也可以调整终端的配色调整称浅色而不是黑底白字，我自己测试 konsole 使用浅色作为终端配色的时候看起来还是能配合到一起的

**Comment by la1den** [comment]
> 你可以 Ctrl+Alt+P 快速禁用预编辑

感谢！！找了半天不知道哪个才能关。我是习惯终端的背景是深色，编辑器背景浅色，比较好区分两种模式。

有没有办法能够默认禁用预编辑呢？配置里好像没有看到有这个选项。

**Comment by wengxt** [comment]
![image](https://github.com/fcitx/fcitx5/assets/259684/906b9104-a3ad-457a-a3ba-fa60fa582ce3)

你可以给 konsole 建立多个 profile 快速切换
