### ISSUE TITLE
quick phrase can't input trailing space

### ISSUE THREAD

**Issue by lilydjwg** [fcitx/fcitx5#997]
**Describe the bug**

**To Reproduce**
1. In `QuickPhrase.mb` write `x y `
2. Invoke quick phrase and type x and choose it
3. `y` is inputted.

**Expected behavior**
`y ` should be inputted.

**Desktop (please complete the following information):**
 - Desktop: Wayfire
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

**Additional context**
My use case is that western-developed applications usually use spaces to terminate words. A trailing space can stop completion and the user can e.g. press Enter to submit inputted text. Without a trailing space Enter might be used to choose an entry from the completion, forcing the user to type more.

**Comment by wengxt** [comment]
This is supported.
Try
```
x "y "
```

Also, if you edit from GUI, you don't need to care about how to escape the value field.
![图片](https://github.com/fcitx/fcitx5/assets/259684/7d8664b1-3be8-49e5-bcef-bcb6cc9b8362)
