### ISSUE TITLE
Request: update Unicode data in fcitx5

### ISSUE THREAD

**Issue by silmeth** [fcitx/fcitx5#998]
The Unicode data in fcitx5 seems to be a few years old – and thus it doesn’t allow one to select more recent Unicode characters by name using the <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>U</kbd> combo.

For example I sometimes need to input the “Old Polish o” character, ⟨Ꟁ, ꟁ⟩ (`u+a7c0` uppercase, `u+a7c1` lowercase). This character was added in Unicode 14 in 2021.

I can do it with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>U</kbd> and then the hex codepoint, but I can’t use the “find by name” feature, typing “Old Polish” (which I generally did with ibus).

Also, when I select this character and hit the combo above it displays “&lt;not assigned&gt;” next to it instead of “LATIN SMALL/CAPITAL LETTER OLD POLISH O”.

The current Unicode version at the time of writing this is 15.1.0.

**Comment by wengxt** [comment]
You can manually download the new file in https://github.com/fcitx/fcitx5/commit/f45c693306dc554b7ecc6d3b91b35ea026fd9249 and replace the /usr/share/fcitx5/unicode/charselectdata so you don't need to wait for next release.

**Comment by silmeth** [comment]
Thanks, the new data file works. :)

**Comment by oldherl** [comment]
U+2C386 𬎆 still shows as <not assigned>

Arch Linux extra/fcitx5 5.1.9-1

**Comment by wengxt** [comment]
@oldherl https://www.unicode.org/Public/UNIDATA/UnicodeData.txt doesn't have it, what can i say ..

**Comment by oldherl** [comment]
But it should be given a general name, just like characters in CJK Basics (U+8888 etc) are named `CJK UNIFIED IDEOGRAPH-XXXX`

**Comment by wengxt** [comment]
@oldherl yes, but all the information are derived from the official unicode data. I can't just randomly do adhoc fix downstream.

**Comment by oldherl** [comment]
CJK Basics such as U+8888 are not in UnicodeData.txt, either. Only a range included. But your current parser can give them a general name. The same approach should apply to all other ranges.
